### ISSUE TITLE
OAuth2.0 Help

### ISSUE THREAD

**Issue by kelvinma** [ga-wdi-boston/capstone-project#1]
A sizable number of us are interested in implementing OAuth2.0 in our projects. Are there any instructors who are familiar with this who wouldn't mind taking some time this morning to offer some guidance?

**Comment by jrhorn424** [comment]
What is a "sizable number"? Do you have a count?

(To be clear, I've never implemented OAuth, but I understand the high-level steps.)

**Comment by kelvinma** [comment]
At least 4 in Classroom 2.

**Comment by jrhorn424** [comment]
Thanks!

**Comment by kelvinma** [comment]
I think I'm on my way to finding a solution. Antony told me about ngrok, so I've got that tunneling in to localhost, which is letting me do the OAuth2.0 redirects. Currently reading up on ways to set up token exchange via the express routers.

**Comment by kelvinma** [comment]
Yeah, this might be a little bit more than handle right now. Pulling the plug on OAuth2.0
