### ISSUE TITLE
1:1 Requested reevaluation of project scope and strategy

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/capstone-project#101]
I've been running into a lot of Ember issues so far that I haven't been able to effectively debug on my own, so I'm reevaluating and simplifying core features of my project.

I'm creating an activity-tracking app, with Ember front end and rails back end (where companies have users, and users have activities that earn them points). I was planning to have a leaderboard for each company, an admin dashboard, and/or a "challenge another user" feature, but I won't have time to do all 3. I am unsure how to approach any of these using Ember, and I get the sense that mixing in vanilla JS is a bad idea. I seriously regret building this in Ember, but at the same time, I want a front-end framework to be part of my portfolio.

ERD and Wireframes attached.
[ERD and Wireframes for EarthWars.pdf](https://github.com/ga-wdi-boston/capstone-project/files/203455/ERD.and.Wireframes.for.EarthWars.pdf)

**Comment by jrhorn424** [comment]
Do you have CRUD working for your entities yet? If not, I would work on that first. Then, you should find it simpler to attach building your dashboard and leaderboard.

**Comment by jenweber** [comment]
From the front end, I have authenticated CRD working for user activities, CR for organizations, and user CRUD. I also have global admins (who can see all activities) and regular users (who can only see their own activities). 

My next step is setting up the has-many-through for organizations and activities on the back end. An admin associated with an organization should only read and delete the activities for users in their own organization.

I'll close this issue until I'm done with the has-many relationship.
