### ISSUE TITLE
Confirming whether an ember service is the answer.

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/capstone-project#102]
Heyo. 

Implementing search of soundcloud. Fun. So I have 
- a song-search route
- a song-search-form component 
- a song-input component which just holds the value of the search bar (similair to e-mail or password for auth) 
- a search service 

Everything is flowing nicely and I'm grabbing the value of what the user searches and logging it in the console in both my song-search route and my search service. I think my issue is when I try to use AJAX and I wonder if I'm approaching it correctly. 

```
import Ember from 'ember';

export default Ember.Route.extend({
  search: Ember.inject.service(),
  flashMessages: Ember.inject.service(),

  actions: {
    songSearch(key) {
      console.log('here');
      console.log(key);

      this.get('search').songSearch(key)
      .then(() => {
        this.get('flashMessages')
        .success('You did something you freak');
      })
      .catch(() => {
        this.get('flashMessages')
        .danger('Try again dummy.');
      });
    }
  }
});
```

This is what my song-search route looks like. It console logs the 'here' and the 'key' as whatever I put in the search input. Great. I know it goes and hits my search service which looks like 

```
import Ember from 'ember';

export default Ember.Service.extend({
  ajax: Ember.inject.service(),

  songSearch(search) {
    console.log('here');
    console.log(search);
    return this.get('ajax').get('/songs', {
      data: {
        search
      },
    });
  },
});
```

And the console logs here work as well return both 'here' and whatever was in my search bar. So this is where I get tripped up because I don't think that the Ajax is working correctly. 

The console then says 

```
Uncaught TypeError: Cannot read property 'then' of undefined
```

which confirms that the Ajax isn't working correctly? Or something else?

I have a '/songs' route in my API that triggers the method search_songs in my songs controller which looks up specific songs in the Song model by interpolating the search key into the URL in the Soundcloud wrapper. Pretty schfifty if it would work. Any advice on where to turn for more info on setting up my AJAX service in ember to work with this new request? I'm a little but torn for how to debug next. Thanks!

**Comment by kpie89** [comment]
Haha sorry for the vulgar console log in my song-search route.

**Comment by kpie89** [comment]
Also worth noting that I want to search other things later on in the project...which in my mind further confirms the need for a a search service to be applied globally.

**Comment by jrhorn424** [comment]
> Uncaught TypeError: Cannot read property 'then' of undefined

What line and file does this occur in?

**Comment by jrhorn424** [comment]
> Also worth noting that I want to search other things later on in the project...which in my mind further confirms the need for a a search service to be applied globally.

Services are available anywhere in your application. You just need to inject them. So in that sense, they're already "global".

**Comment by kpie89** [comment]
Song-search route.js line 13 which is right after it comes back from the search service.

**Comment by jrhorn424** [comment]
The problem was this line.

``` diff
- return this.get('ajax').get('/songs', {
+ return this.get('ajax').request('/songs', {
```

There is not a `get` method on the ajax service.

**Comment by kpie89** [comment]
Thanks Jeff!
