### ISSUE TITLE
Rails: Attach foreign key to table

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/capstone-project#104]
When I try to create a new "product", hitting this controller:

``` ruby
  def create
    @product = current_user.products.build(product_params)
    # @product = Product.new(product_params)

    if @product.save
      render json: @product, status: :created, location: @product
    else
      render json: @product.errors, status: :unprocessable_entity
    end
  end
```

I get the following error from my server: 

```
Started POST "/products" for ::1 at 2016-04-05 12:31:06 -0400
Processing by ProductsController#create as */*
  Parameters: {"products"=>{"name"=>"Laundry Detergent", "price"=>"100"}}
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `products' for nil:NilClass):
  app/controllers/products_controller.rb:25:in `create'
```

I used a very similar controller on my 2nd project, and I don't understand why this one isn't working. Maybe I just haven't used Rails in too long? Any help would be appreciated.

**Comment by GA-MEB** [comment]
Have you 
1. actually added the necessary foreign keys to the underlying tables via a migration, and
2. created the necessary methods in the model?

**Comment by GA-MEB** [comment]
Based on the error message and your controller code, it looks like `current_user` may be nil/undefined.

**Comment by gaand** [comment]
Please post the controller class definition line.

**Comment by MFBrewster** [comment]
Welll...... it used to be ApplicationController, but now it's ProtectedController, and the problem is solved. Thank you!
