### ISSUE TITLE
using multer & formdata without a form

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/capstone-project#105]
I'm using a canvas HTML object to allow the user to draw things. I want to save the image they create on AWS without saving it locally first. I've turned the image into a dataurl, turned that into a blob, and turned the blob into a file. I want to send the file to my API so I can upload it to AWS.

I've tried using the multer app template, but that's set up to use multipart form data and I'm not using a form. Is it possible to create/send multipart form data if that data didn't originate in an HTML form?

**Comment by jrhorn424** [comment]
I don't believe sending formdata is possible without a form. Is there a clever way you could use a form, even if it is hidden?

@gaand Do you have thoughts?

**Comment by apalmer0** [comment]
The trouble is that the file is being created after the form is submitted using the data within the image... I suppose I could make the button actually create the file and then call the form submit event?  That felt kinda hacky though so I was hoping there'd be a more conventional way to do it

**Comment by apalmer0** [comment]
sorry, not "after the form is submitted" - there is no form, currently. 

I meant "after the 'save image' button is clicked"

**Comment by jrhorn424** [comment]
Where is the file created, on the server or on the client?

**Comment by jrhorn424** [comment]
Also, please link to the plugin, and if you have a reference for what the save button does in the documentation that would help me pinpoint a strategy.

**Comment by gaand** [comment]
Have you investigated the `append` method of `FormData` instances?  It is probably what you need.

**Comment by apalmer0** [comment]
Thanks! Ended up using a combination of things. 
- added a 'name' field in a hidden form element, 
- turned my 'save image' button into a form submit button
- Used the `.append` method to add the file I had created to the form data

The trick was some goofy shenanigans angular was pulling with the post request... I had to rewrite it to this:

```
$http.post( <api url>, <formdata>, {
          transformRequest: angular.identity,
          headers: {'Content-Type': undefined}
      })
```

That's because:

> Angular’s default transformRequest function will try to serialize our FormData object, so we override it with the identity function to leave the data intact. Angular’s default Content-Type header for POST and PUT requests is application/json, so we want to change this, too. By setting ‘Content-Type’: undefined, the browser sets the Content-Type to multipart/form-data for us and fills in the correct boundary. Manually setting ‘Content-Type’: multipart/form-data will fail to fill in the boundary parameter of the request.

More [here](https://uncorkedstudios.com/blog/multipartformdata-file-upload-with-angularjs) if you're interested.

So I definitely don't fully understand what's going on here, but this at least got me over this hurdle. On to the next one!

**Comment by jrhorn424** [comment]
Impressive. :+1:
