### ISSUE TITLE
(Resolved) Issue with displaying search results in Ember route

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/capstone-project#106]
Thanks to Matt for this great solution. 

I have a song-search route 

```
import Ember from 'ember';

export default Ember.Route.extend({
  search: Ember.inject.service(),
  flashMessages: Ember.inject.service(),

  actions: {
    songSearch(key) {
      this.get('search').songSearch(key);
    }
  }
});
```

which utilizes a search service 

```
import Ember from 'ember';

export default Ember.Service.extend({
  ajax: Ember.inject.service(),
  songResults: {},

  songSearch(key) {
    return this.get('ajax').request('/song', {
      data: {
        key
      },
    }).then((result) => {
      this.set('songResults', result);
    });
  },
});
```

The issue I was having was displaying the search results. Notice in the search service method where I have an empty songResults hash that I push the results of the search. Instead of worrying about a brand new results route or anything I simply created a new song-results component 

```
export default Ember.Component.extend({
  search: Ember.inject.service(),
  songResults: Ember.computed.alias('search.songResults'),
});
```

This also utilizes the search service and uses an Ember computed property to access the songResults from it. I then simply display the data in my song-search route  using 

```
{{song-results}}
```

the song-results component template looks like this. 

```
<ul>
{{#each songResults as |song|}}
  <li>{{song.title}} ({{song.id}}) <button {{action "playTrack" song.id}}>Play</button></li>
{{/each}}
</ul>
```

Matt FTW.

**Comment by jrhorn424** [comment]
Frickin' awesome.
