### ISSUE TITLE
Rails: Two-way association issues

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/capstone-project#109]
I am able to create one-way has_many and belongs_to associations without issue. The problem is that I have two tables (products and orders), each of which has_many of the other. Should I use has_and_belongs_to_many (which I am having trouble with so far), or should I use two separate has_many and belongs_to associations? Thank you.

**Comment by jrhorn424** [comment]
I need to see the ERD. If you could post the model code for the models in question, that would help, too.

**Comment by MFBrewster** [comment]
``` ruby
class Order < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :products
end
```

``` ruby
class Product < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :products
end
```

![image](https://cloud.githubusercontent.com/assets/8867447/14293364/51de9c66-fb3a-11e5-919e-60d5742d8e60.png)

**Comment by jrhorn424** [comment]
<img width="397" alt="rails__two-way_association_issues_ _issue__109_ _ga-wdi-boston_capstone-project" src="https://cloud.githubusercontent.com/assets/388761/14293475/baa6ff22-fb3a-11e5-9c18-883e54953fdd.png">

You need a join table right here, and a join model, then you can do a `has_many :through`, which was recommended over `has_and_belongs_to_many`.

**Comment by MFBrewster** [comment]
Does the join model need to make any kind of conceptual sense, or can it just be something like `ProductJoinOrder`?

**Comment by jrhorn424** [comment]
It doesn't have to, but it's a good idea. What about `LineItem`?

**Comment by MFBrewster** [comment]
LineItem has been good to the extent I pluralize correctly. All set.
