### ISSUE TITLE
New method added to Auth service isn't working correctly

### ISSUE THREAD

**Issue by jpfriedman18** [ga-wdi-boston/capstone-project#111]
On my /prompts route, I am trying to have different link-to buttons depending on the type of user logged in:

``` html
{{#if isTeacher}}
<h5>{{#link-to "teacher-landing"}}Back{{/link-to}}</h5>
{{else}}
<h5>{{#link-to "student-landing"}}Back{{/link-to}}</h5>

{{/if}}
```

I created isTeacher in the Auth service:

``` js
isTeacher: Ember.computed.equal('credentials.profileable_type', 'Teacher'),
```

and injected it into my /prompts route:

``` js
  auth: Ember.inject.service(),
  isTeacher: Ember.computed.alias('auth.isTeacher'),
```

However, regardless of what type of user is logged in, the Back button on the Prompts route always links to the student-landing route, meaning that isTeacher is falsey. Unsure of how to proceed.

**Comment by jpfriedman18** [comment]
SOLVED:
Routes cannot have services injected. Had to generate a return-button component/template and inject the auth service/isTeacher method into the component, then just include the return-button template in my Prompts template

**Comment by jrhorn424** [comment]
> Creates a property that lazily looks up a service in the container. There are no restrictions as to what objects a service can be injected into. 
> 
> – http://emberjs.com/api/classes/Ember.inject.html#method_service

Templates do not have access to any data in a route **except** through the model hook.

**Comment by jrhorn424** [comment]
@kpie89 Experienced a similar issue. You can return a custom object from a model hook with multiple keys. @kpie89 Can you share your final code? The code that started out in Evernote this morning?
