### ISSUE TITLE
Dynamic segment route not nested

### ISSUE THREAD

**Issue by dumplingpuff** [ga-wdi-boston/capstone-project#112]
First I have a trips template from there I want to link to the dynamic segment for trip/trip_id.  So far my trips template looks like this.  When I go to the trip/trip_id page the data doesn't get passed to it so it doesn't render anything.

```
<div class="container">
  <div class="row">
    {{#each model.trips as |trip|}}
    <div class="trip-box">
      <img src='../images/fire.png'>
      <p>{{#link-to 'trip' trip}}{{trip.title}}{{/link-to}}</p>
    </div>
    {{/each}}
  </div>
</div>
```

**Comment by GA-MEB** [comment]
>  the data doesn't get passed to it

What data doesn't get passed?

**Comment by GA-MEB** [comment]
Can you paste in the code from your `trip` route?

**Comment by dumplingpuff** [comment]
```
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return {
      trip: this.store.findRecord('trip', params.trip_id)
    };
  }
});
```

**Comment by dumplingpuff** [comment]
Data was coming through routes here is solution.

```
<h1>{{model.trip.title}}</h1>
```

**Comment by dumplingpuff** [comment]
Lies, it didn't work... when I tested it I never went back to home page and physically click on the link.

**Comment by jrhorn424** [comment]
@dumplingpuff I'm in the dugout. I'll have a look at this when you return.

**Comment by dumplingpuff** [comment]
Was async issue.
