### ISSUE TITLE
Posting "likes" error

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/capstone-project#113]
I'm currently working on creating likes for games on my webpage. Here is my post request:

```
let createLikes = function(e) {
  e.preventDefault();
  $.ajax({
    url: myApp + '/likes',
    method: 'POST',
    dataType: 'json',
  })
  .done(function() {
    console.log("New Like!");
  })
  .fail(function(jqxhr) {
    console.log(jqxhr);
  });
};
```

In the console inspector I'm getting this error:

```
POST http://localhost:3000/likes 401 (Unauthorized)
Object {readyState: 4, responseText: "HTTP Token: Access denied.↵", status: 401, statusText: "Unauthorized"}
```

and in the rails console:

```
Started POST "/likes" for 127.0.0.1 at 2016-04-05 16:49:25 -0400
Processing by LikesController#create as HTML
  Rendered text template (0.1ms)
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 4ms (Views: 3.0ms | ActiveRecord: 0.0ms)
```

Even though I am successfully signed in. I also noticed that myApp.user returns undefined, even though I get back a user object on sign in. Any idea what's going wrong?

@jrhorn424 @MattB-GA-Boston @faetea

**Comment by faetea** [comment]
Have you tried hitting the route with a curl request or any other type of testing?

**Comment by jdamiron** [comment]
@faetea 
Yes, I've already successfully created a like on the backend using a script. And then I went into the rails console and associated that like with a certain game using the shovel operator. I'm trying to get that same process to work on the front-end/web page.

**Comment by jdamiron** [comment]
If I change the inheritence in the contorller from open read to application, I get this error instead.

```
Started POST "/likes" for 127.0.0.1 at 2016-04-05 17:18:04 -0400
Processing by LikesController#create as HTML
Completed 400 Bad Request in 1ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: like):
  app/controllers/likes_controller.rb:54:in `like_params'
  app/controllers/likes_controller.rb:22:in `create'
```

and here are the like_params:

```
def like_params
    params.require(:like).permit(:id)
  end
```

The likes themselves only contain an id with no other information so I'm not sure what's missing.

**Comment by jdamiron** [comment]
I got rid of the params for now on the create action just for the sake of creating posting a like to the backend and it was successful, I'm now working on a way to associate a created like with a specific game on the web page. I did this using the shovel operator on the rails console. Ex:

```
Game.first << Like.first
```

**Comment by jdamiron** [comment]
```
Game.first.likes << Like.first
```

My mistake.

**Comment by GA-MEB** [comment]
@jdamiron 
Per your first posting, I have two (somewhat socratic) questions for you:
How do you know that you're successfully signed in? 
What does it really mean to be signed in?

**Comment by jdamiron** [comment]
@MattB-GA-Boston 
The sign in is successful because on .done the user object is logged. This user has an active token, could I still not be truly signed in?

**Comment by GA-MEB** [comment]
You haven't set any headers in your AJAX request, so even if you have a valid token, you aren't using it to authenticate your requests.
