### ISSUE TITLE
How to best sum records that belong to a user?

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/capstone-project#115]
I'm trying to figure out how to compute a user's score, for the user him/herself to view. A user has may activities, and each activity has an attribute storing its point value. An index request to the server returns only the activities that belong to that user. I see a few possible ways that this could possibly be approached, and I'm wondering which are possible/advisable:
1. Can I do something on the route? I have access to all the user's activities from the activities route, but not the model, since the model deals with an individual instance of the activity. So the way I see it, I can't use Ember computed properties. 

```
import Ember from 'ember';
export default Ember.Route.extend({
  model: function(){
    return {
    allActivities: this.store.findAll('activity'),
    pointsTotal: *****Something that adds up all the activity.pointvalue??? ******
    };
  },
  actions: {
      createActivity: function(properties){
        console.log('Route Action : createActivity');
        this.store.createRecord('activity', properties)
          .save().then(()=>console.log('record created'));
      },
      updateActivity: function(activity) {
        console.log('Route Action : updateActivity');
        activity.save();
      },
      destroyActivity: function(activity){
        console.log('Route Action : destroyActivity');
          activity.destroyRecord();
      }
    }
});
```
1. I could access all the activities through the user object, since a user has many activities. But I really don't want to mess with the user object anymore. It's painful.
2. I could add something to my ERD. A User has one ActivityLog. An ActivityLog has many activities. Then an authenticated server request would return the data I need, and it wouldn't be buried on the user object and mixed in with auth. But then the Organizations relationship would become complicated, since an organization would have many Activities through Users through ActivityLog.
3. Any other options?

**Comment by jrhorn424** [comment]
These are really thoughtful options. Adding this to the model hook is fine. Use http://emberjs.com/api/classes/Ember.computed.html#method_sum and make it dependent on all the activities.

>  So the way I see it, I can't use Ember computed properties.

Since everything in Ember is an Ember.Object, you can use computed properties anywhere.

**Comment by jrhorn424** [comment]
@jenweber Any updates?

**Comment by jenweber** [comment]
I was not able to get this to work. Am I missing something? It seems to me that .sum is intended to sum an array of numbers, as if value: [1, 5, 7]. When in reality value is a single integer found on each instance of activity (value: 1)

activity model:

```
export default DS.Model.extend({
  name: DS.attr('string'),
  category: DS.attr('string'),
  value: DS.attr('string')
  totalPoints: Ember.computed.sum('value')
});
```

in the activities template:

```
<div class="my-total-points">
  <h4>Total Points</h4>
  {{model.totalPoints}}
</div>
```

**Comment by GA-MEB** [comment]
Sum doesn't make sense on a single activity. Make a computed property that sums across all activities.

As you know, since you're doing this in the routed template, and not a component, you'll need to make the sum value available to the template through the model hook.

**Comment by jenweber** [comment]
Solved:

We created a helper called sum-values.js:

```
import Ember from 'ember';

export function sumValues(params) {
  return params[0].map((activity) => Number(activity.get('value'))).reduce((a,b)=> a + b);
}

export default Ember.Helper.helper(sumValues);
```

We called for it in the activities template like this:
`{{sumValues model}}`

**Comment by jrhorn424** [comment]
For future reference, best practice would have been to do your mapping and reducing with a custom computed property in the route's model hook.
