### ISSUE TITLE
Ember Error: Assertion Failed

### ISSUE THREAD

**Issue by seatuna** [ga-wdi-boston/capstone-project#116]
I get the following error when I go to localhost:3000/players

```
Passing classes to store methods has been removed. Please pass a dasherized string instead of undefined
```

players/route.js

``` js
import Ember from 'ember';

export default Ember.Route.extend({
  model: function(){
    return {
      players: this.store.findAll('player'),
      characters: this.store.findAll('character')
    };
  }
});
```

players/template.js

``` js
{{#each model.players as |player|}}
  {{player-row player=player}}
{{/each}}
```

player/model.js

``` js
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  rank: DS.attr('string'),

  characters: DS.hasMany('characters', {async: true})
});
```

components/player-row./template.js (nothing added to component.js)

``` js
{{player.name}}<br />
Rank: {{player.rank}}<br />
Characters: {{player.characters}}
```

I was able to display player.name and player.rank before I added routes and components for characters.  I googled this error and the things I've found say it's because the JSON response has embedded records, and the fix is to change the serializer.  Before I go down this scary path, I'd like to confirm if that is indeed the route I should be taking.

[The article I saw](http://discuss.emberjs.com/t/passing-classes-to-the-store-has-been-removed-with-ember-2-0-1-and-ember-data-2-0/8717/3)

**Comment by seatuna** [comment]
I've just discovered that clicking on the characters page, then going back to the players page will display data in players.  I checked the Ember Inspector, and the data for players and characters do load upon accessing the players page.

![screen shot 2016-04-06 at 12 50 58 am](https://cloud.githubusercontent.com/assets/16471076/14306106/c15e7744-fb91-11e5-9003-7420696f76f3.png)

**Comment by jrhorn424** [comment]
Make the following change here and elsewhere in your application.

``` diff
-      players: this.store.findAll('player'),
+      players: this.get('store').findAll('player'),
```

The linked article is correct. Change your serializer to only return `character_ids` instead of the entire character object. You can find an example in the serializers for listr-api.

**Comment by faetea** [comment]
What do your JSON objects for player and character look like?
What is returned when you curl to player or character?

player/model.js

```
  - characters: DS.hasMany('characters', {async: true})
  + characters: DS.hasMany('character', {async: true})
```

I think Ember wants you to sideload the relationship in the Rails serializer, something like this:

```
  has_many :characters, embed: :ids, include: true
```

So that the JSON will look more like this:

```
{
  "players": [
    { "id": 1, "name": "Sora", "rank": "3", "character_ids": [1, 2] }
  ],
  "characters": [
    { "id": 2, "name": "Kami"},
    { "id": 1, "name": "Tara"}
  ]
}
```

**Comment by seatuna** [comment]
The JSON looks like this:

![screen shot 2016-04-06 at 11 06 22 am](https://cloud.githubusercontent.com/assets/16471076/14321555/b1e6c3f6-fbe7-11e5-8ced-d34850368d4e.png)

So far, I've tried doing the following:

Change the rails Player serializer

``` ruby
class PlayerSerializer < ActiveModel::Serializer
  attributes :id, :name, :rank, :characters, :opponents

  def players
    object.player.id
  end
end
```

change the characters serializer

``` ruby
class CharacterSerializer < ActiveModel::Serializer
  attributes :id, :name

  def character
    object.characters.pluck(:id)
  end
end
```

I've also generated a serializer in ember per the internet's suggestion

``` js
import DS from 'ember-data';

export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    characters: { serialize: 'ids' }
  }
});
```

**Comment by seatuna** [comment]
I fixed the ember serializer

``` js
import DS from 'ember-data';

export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    characters: { embedded: 'always', serialize: 'ids' }
  }
});
```

So now I don't get the error anymore and my data shows immediately.  But I characters still displays as DS.PromiseManyArray:ember708

**Comment by jrhorn424** [comment]
``` diff
{{!-- in your template --}}
- Characters: {{player.characters}}
+ Characters: {{player.character.name}}
```

**Comment by jrhorn424** [comment]
Oops, should this be a single character or a collection on the screen you pasted?

**Comment by seatuna** [comment]
Collection

**Comment by seatuna** [comment]
Solution was to define attributes with relationships in my model using an empty DS.attr && changing my serializers in rails

player/model.js

``` js
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  rank: DS.attr('string'),
  characters: DS.attr(),
  opponents: DS.attr()

  // characters: DS.hasMany('characters', { async: true }),
  // opponent: DS.hasMany('opponents', { async: true})
});
```

backend player serializer

``` rb
class PlayerSerializer < ActiveModel::Serializer
  attributes :id, :name, :rank, :characters, :opponents

  def characters
    object.characters.pluck(:name)
  end

  def opponents
    object.opponents.pluck(:name)
  end
end
```

backend character serializer

``` rb
class CharacterSerializer < ActiveModel::Serializer
  attributes :id, :name

  def player
    object.player.id
  end
end
```

Hopefully this won't screw up anything else?

**Comment by jrhorn424** [comment]
Great work!
