### ISSUE TITLE
Having one button in template do two actions...

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/capstone-project#117]
I'm trying to create a playlist once a person searches for a song. There is a button on my song-results template labeled "use this song" and when a user clicks it it sends them to another route 'create playlist' where they are able to create a playlist using just a title and description for now. However, I need to attach a song_id with it as well so it knows what song is associated with it in my back end. I have a songs table in my back end as well so when a user clicks "use this song" in the template I need to "create" a new song that stores the playlist_id AND a property called soundcloud_id that I get from the soundcloud API so I can use this later to stream the music. I'm doing research and it seems you can't fire two actions with one button. Also, I don't know of a way to store the song_id in the playlists table without somehow attaching which song you choose when you "create" it with the "use this song" button on my template. I don't know how to create the song and still have the "create-playlist" route which the user sees next to know what song_id to push into the songs table once the playlist is created. 

I'm assuming this makes no sense. Please ask clarifying questions.

**Comment by jrhorn424** [comment]
> I'm doing research and it seems you can't fire two actions with one button.

That's true. However, if I have a button that I want to fire the actions `foo` and `bar`, I can have it instead fire an action `baz` that then fires both `foo` and `bar` using `sendAction`.

**Comment by kpie89** [comment]
Yeah I think I understand what you’re saying. Which makes me think that getting rid of the “create-playlist” route is for the best. Instead…on the “song-results” component template, have a form that pops up on “use this song” action that remembers the relevant song info and creates a playlist and song with a series of promises. Sorta what you’re getting at?

**Comment by jrhorn424** [comment]
Remember that in Ember, your routes are about pieces of UI and data. Having a route for creating a playlist makes sense from a UX perspective, I think.

You can have your button send an action that uses bound data in your component object to dispatch to the `create-playlist` route using `transitionTo` after you fire other actions. At least, I'm pretty sure that will address your goals.

@MattB-GA-Boston or I can sit down with you in a bit to look at this further.

**Comment by jrhorn424** [comment]
The plan is to have the following flow:
1. When a user clicks "use song" on the search results, it fires an action that:
2. First creates a empty playlist on the server, then
3. Creates a song on the server with the playlist id from the previous step (as well as title, etc), then
4. Transitions to the next route, which displays a form for adding a description to the playlist.

Promises should be used to coordinate these steps.
