### ISSUE TITLE
Trouble with Ember associations

### ISSUE THREAD

**Issue by jpfriedman18** [ga-wdi-boston/capstone-project#118]
I have prompt and prompt_response models both on the front and back ends. On the back end, there is a one-to-many association between prompts and prompt_responses. On the front end, I want to be able to show a prompt_response's associated prompt, and vice versa, however the Ember DS.has_many/belongs_to is causing problems. When I have:

```
export default DS.Model.extend({
  title: DS.attr('string'),
  text: DS.attr('string'),
  prompt_response: DS.has_many('prompt-responses')
});
```

and:

```
export default DS.Model.extend({
  text: DS.attr('string'),
  prompt: DS.belongs_to('prompt')
});
```

...Ember breaks (Ember inspector says Ember application not detected). I have tried adjusting my serializers on the back end so that the JSON rendered for a prompt_response includes the prompt object like so:

```
{
  "prompt_responses": [
    {
      "id": 2,
      "text": "another essay",
      "prompt_id": 1,
      "student_id": 1,
      "prompt": {
        "id": 1,
        "title": "Im authorized",
        "text": "yeah",
        "teacher_id": 1
      }
    },
```

however I am still unable to access the associated prompt object on the front end

**Comment by jpfriedman18** [comment]
Fixed the syntax in the Ember models (changed has_many to hasMany) but still not working

**Comment by jpfriedman18** [comment]
currently receiving this error:

```
ember.debug.js:32161 Error: Assertion Failed: Passing classes to store methods has been removed. Please pass a dasherized string instead of undefined
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:26689:21)
    at assert (http://localhost:4200/assets/vendor.js:16448:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:26453:34)
    at assert (http://localhost:4200/assets/vendor.js:71197:37)
    at modelFor (http://localhost:4200/assets/vendor.js:80316:41)
    at _internalModelForId (http://localhost:4200/assets/vendor.js:79694:28)
    at deserializeRecordId (http://localhost:4200/assets/vendor.js:80833:18)
    at normalizeRelationship (http://localhost:4200/assets/vendor.js:80948:28)
    at http://localhost:4200/assets/vendor.js:80927:7
```

**Comment by jrhorn424** [comment]
You need to serialize IDs for dependent objects in your API serializers. I suspect you have an association in the serializer. That embeds the entire object. You need to send an ID instead of an entire object.

**Comment by jrhorn424** [comment]
See #116

**Comment by faetea** [comment]
The main issue seemed to be that not all of the models were being referenced in all of the routes that needed them.  After James added the findAll's then it started working more.

James has also made these changes that Jeff suggested.

``` diff
-      prompts: this.store.findAll('prompts'),
+      prompts: this.get('store').findAll('prompts'),
```
