### ISSUE TITLE
Change password isn't changing password.

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/capstone-project#119]
I have gone through many different testing methods. Of debugging. I am spinning my wheels and not making any progress.

Currently I am unsure if what I have completed for the `signing` and `comparePassword` are actually correct. This may have a cascading effect into my change password functionality.

[CODE: current CONTROLLER for USER](https://gist.github.com/edesilets/bfd95fab84fa913df5b1a50c37d897a6)

[CODE: current MODEL for USER](https://gist.github.com/edesilets/4955d530b49578f0cac2b008db8482d8)

**Comment by jrhorn424** [comment]
> Currently I am unsure if what I have completed for the signing and comparePassword are actually correct. This may have a cascading effect into my change password functionality.

This may be true. Can you prove (through testing) that these two methods do what you expect? Once we eliminate that as a source of concern, we can proceed with other debugging.

**Comment by edesilets** [comment]
Post updated with code ^^

**Comment by jrhorn424** [comment]
You're updating the user right? Shouldn't you uncomment this line? https://gist.github.com/edesilets/4955d530b49578f0cac2b008db8482d8#file-user-js-L42

**Comment by gaand** [comment]
You don't appear to be calling `setPassword` when you create a new user.

**Comment by jrhorn424** [comment]
@gaand I'm not sure, but I believe it's happening here: https://gist.github.com/edesilets/4955d530b49578f0cac2b008db8482d8#file-user-js-L41

**Comment by gaand** [comment]
Ah, but that method, as defined, takes the password as an argument.

**Comment by edesilets** [comment]
@jrhorn424 I am unsure if that necessary to do. I was able to call the `comparePassword` function on `user` without an issue. I don't think I hit it as an create. I could be very wrong. See line [Line 68](https://gist.github.com/edesilets/bfd95fab84fa913df5b1a50c37d897a6#file-users-js-L68)

**Comment by gaand** [comment]
Does the way you've set things up send the password to `savePassword` when you save a new user?

**Comment by edesilets** [comment]
[CODE: Abridged express/app/controllers/users.js](https://gist.github.com/edesilets/7f34a886e0a3af47435eaf8061aaedcd)

[CODE: MODEL USERS](https://gist.github.com/edesilets/c0a26845cb05f8aa9e55f794ef2367e5)

I just need to save what is returned from [SETPASSWORD](https://gist.github.com/edesilets/7f34a886e0a3af47435eaf8061aaedcd#file-users-js-L14)  I am having a lot of trouble getting this to save. [The save docs](http://bookshelfjs.org/#Model-instance-save)...... I have tried .save() and .save(this, {patch: true}) and .save(this). No such luck. @jrhorn424 
@gaand

**Comment by gaand** [comment]
In the express-template, setPassword returns a promise chain that terminates with a save. This is so the bcrypt steps can run asynchronously.

**Comment by jrhorn424** [comment]
@edesilets Any updates?

**Comment by gaand** [comment]
@edesilets I believe we got his to work.  Please correct me if I'm wrong.

**Comment by jrhorn424** [comment]
@edesilets You still need to sendStatus at some point, most likely the end of the promise chain. https://github.com/ga-wdi-boston/express-api

**Comment by edesilets** [comment]
4/6/2016 5:20pm Antony was nice enough to help me get back on track by helping me save the current user model in the method on the model it's self. By doing this sign in broke and sign up was "fixed".

**Comment by edesilets** [comment]
### Captain's log, star date 69732

Our objective was to fix this broken signup. By doing so it destroyed the signing. In order to fix these errors @MattB-GA-Boston was kind enough to go through how promises work. I know have a very thorough understanding of promises even though the Romulans can't seem to keep theirs. These issues were resolved and now we can part are ways.

#### Model

##### bookshelf.Model

``` javascript
  setPassword: function (password) {

    console.log('\n Set Password to: ', password, '\n');
    var _this = this;
    return new Promise((resolve, reject) =>
      bcrypt.genSalt(null, (err, salt) =>
          err ? reject(err) : resolve(salt))
    )
    .then((salt) => {
      return new Promise((resolve, reject) =>
        bcrypt.hash(password, salt, (err, data) =>
          err ? reject(err) : resolve(data)))
    })
    .then((digest) => {
      _this.attributes.passwordDigest = digest;
      delete _this.attributes.password;
      return _this;
    });
  },
```

#### Controller

##### user

``` javascript
const signup = (req, res, next) => {
  let credentials = req.body.credentials;
  let user = {
                email: credentials.email,
                password: credentials.password,
              };
  getToken().then(token =>
    user.token = token
  )
  .then(() => {
    console.log('Create a user: \n', user, '\n');
    return new User(user).setPassword(user.password);
  })
  .then((user) => user.save())
  .then(newUser => {
    let user = newUser.attributes;
    delete user.passwordDigest;
    res.json({ user });
  })
  .catch(makeErrorHandler(res, next));
};
```

##### user

``` javascript
const changepw = (req, res, next) => {
  debug('Changing password');
  let credentials = req.body.passwords;
  let search = {
                id: req.params.id,
                token: req.currentUser.token,
              };
  new User(search).fetch()
  .then((searchResult) => {
    if (searchResult) {
      searchResult.comparePassword(req.body.passwords.old).then((user) => {
        console.log('user, with digest: \n',user);
        delete user.attributes.passwordDigest;
        console.log('user, without digest: \n',user);
        return user.setPassword(credentials.new);
      })
      .then((user)=> {
        console.log('user, with new passwordDigest: \n', user);
        return user.save();
      })
      .then((user) => {
        user ? res.sendStatus(200) : next(new HttpError(404));
      })
      .then(new HttpError(404));
    } else {
      Promise.reject(new HttpError(404));
    }
  })
  .then(console.log);
};
```

Matt and I spent 2hr going over this code.

**Comment by edesilets** [comment]
@MattB-GA-Boston I need help. I am so confused. Something went wrong.

**Comment by faetea** [comment]
@edesilets, Matt just went home.  You need to explain your issue.  
Also, can you write a fresh issue, or are you actually experiencing exactly the same issue as the previous one?

**Comment by GA-MEB** [comment]
@edesilets OK to mark closed?

**Comment by edesilets** [comment]
Yes thank you so much @MattB-GA-Boston !!!!!!

#### Controller (user)

``` javascript
const getToken = () => {
   return new Promise((resolve, reject) => {
     crypto.randomBytes(16, (err, data) => {
       err ? reject(err) : resolve(data.toString('base64'));
     });
   });
 };
```

``` javascript

const signin = (req, res, next) => {
  let credentials = req.body.credentials;
  let search = { email: credentials.email };
  new User(search).fetch()
  .then((user) => {
    return user? user.comparePassword(credentials.password) :
                 Promise.reject(new HttpError(404));
  })
  .then((user) => {
    return getToken().then((token) => {
      user.attributes.token = token;
      console.log('user attributes:\n', user.attributes);
      return user.save();
    });
  })
  .then((user) => {
    console.log('userModel:\n', user);
    let userAttributes = user.attributes;
    delete userAttributes.passwordDigest;
    res.json({ userAttributes });
  })
  .catch(makeErrorHandler(res, next));
};

```
