### ISSUE TITLE
Paperclip upload error

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/capstone-project#12]
I followed Matt's Repo, went to the thoughtbot Paperclip Github walk through, talked to Kayla about any changes from Matt's repo.  Tried looking it up online and hit a reasonable time box on it.

I have my Pets Controller pointing at Application Controller so I can route everything through the Authentication.  When trying to upload, I get a 401 Error.  

This is what I get in the console
`Object {credentials: Object}
clickhandlers.js:83 Uncaught TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.(anonymous function) @ clickhandlers.js:83m.event.dispatch @ jquery.js:3r.handle @ jquery.js:3
:3000/pets/undefined:1 PATCH http://localhost:3000/pets/undefined 401 (Unauthorized)
clickhandlers.js:78 Whoops!(anonymous function) @ clickhandlers.js:78j @ jquery.js:2k.fireWith @ jquery.js:2x @ jquery.js:4b @ jquery.js:4`

This is my Patch on PetsController

``````
class PetsController < ApplicationController
  before_action :set_pet, only: [:update, :destroy]
# PATCH /pets/1
  def update
    if @pet.update(pet_params)
      head :no_content
    else
      render json: @pet.errors, status: :unprocessable_entity
    end
  end```

This is what I get from the Rails Console

``````

Rendered text template (0.0ms)
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 0ms (Views: 0.2ms | ActiveRecord: 0.0ms)

Started OPTIONS "/pets/undefined" for ::1 at 2015-12-14 13:48:56 -0500

Started PATCH "/pets/undefined" for ::1 at 2015-12-14 13:48:56 -0500
Processing by PetsController#update as _/_```

This is my click handler   

``````
$('#submit').on('click', function(e){
    e.preventDefault();
    var reader = new FileReader();
    var token = $('.token').val();
    var id = $('.id').val();

    reader.onload = function(event){
      $.ajax({
        url: 'http://localhost:3000/pets/' + id,
        method: 'PATCH',
        data: { pet: {
          dog_pic: event.target.result
        } }
      }).done(function(response){

      }).fail(function(response){
        console.error("Whoops!");
      });
    };

    $fileInput = $('#dog-pic');
    reader.readAsDataURL($fileInput[0].files[0]);
  });```

This is the HTML form
``````

 <form>
                        <label> Poster
                            <input type="file" id="dog-pic"/>
                        </label>
                        <button id="submit">Upload Picture</button>
                    </form>```

**Comment by jrhorn424** [comment]
1. Your ID in your URL is undefined. This means its undefined in your frontend when you make the request. Where are you expecting it to be defined?
2. You need to make sure you are authenticated before trying to do that action.
3. The initial error is because paperclip isn't receiving a file when its upload method is called.

**Comment by jrhorn424** [comment]
`$fileInput[0].files[0]` this isn't a file. That's what `arameter 1 is not of type 'Blob'` is about.

**Comment by jcmeyer10** [comment]
The second comment makes sense.  That should not have been there.  I was using the sample code from the paperclip upload lesson to do some initial testing.  Using in an AJAX call I can pass the id and token in so that the PATCH knows where to go and it can check whether or not a user is allowed to do that to that id.

**Comment by jcmeyer10** [comment]
I usually have the AJAX and click handlers seperated but this sample code mushed em together.

**Comment by jrhorn424** [comment]
Timebox again and let me know if you hit another snag after time's up.

**Comment by jcmeyer10** [comment]
OK will do.

**Comment by srhoulam** [comment]
We fixed some issues on the front-end. This is now a matter of using paperclip to upload the picture, determine the uploaded image's URL, and insert the URL into the database.

**Comment by jcmeyer10** [comment]
Error is now, 

``````
(0.3ms)  ROLLBACK
Completed 500 Internal Server Error in 710ms (ActiveRecord: 1.5ms)

AWS::S3::Errors::AccessDenied (Access Denied):
  app/controllers/pets_controller.rb:35:in `update'```

Looking into this now
``````

**Comment by jcmeyer10** [comment]
Took a while but futzed with the AWS errors until I finally beat it into submission.  Last error was about Secret id not being recognized as valid.  Just made a new user, made a new bucket policy and then figured it out.

**Comment by jrhorn424** [comment]
Awesome!
