### ISSUE TITLE
Problem creating prompt_responses after adding Ember associations

### ISSUE THREAD

**Issue by jpfriedman18** [ga-wdi-boston/capstone-project#122]
On my front end I have associated prompts and prompt_responses:

```
export default DS.Model.extend({
  text: DS.attr('string'),
  prompt: DS.belongsTo('prompt', {async: true})
});
```

```
export default DS.Model.extend({
  title: DS.attr('string'),
  text: DS.attr('string'),
  promptResponses: DS.hasMany('prompt-response', {async: true})
});
```

However, now when I try to create a new prompt_response, the prompt_id is not being passed to the backend correctly, and in the server logs the parameters for the POST action are:

```
Parameters: {"prompt_response"=>{"text"=>"asdgdfgsdafasdfsdaf", "prompt_id"=>nil}}
```

However, I checked to see the values of the promptResponse object being passed into the createPromptResponse action and it includes the prompt_id:

```
createPromptResponse: function(promptResponse){
      console.log(promptResponse);
      this.store.createRecord('prompt_response', promptResponse)
        .save().then(()=>console.log('response created'))
        .then(()=> this.transitionTo('student-landing'));
    }
```

in console:

```
prompt_id: "10"
text: "asdgdfgsdafasdfsdaf"
```

Not sure of why prompt_id isn't being passed to backend. It was working before the Ember associations were added.

**Comment by jrhorn424** [comment]
@jpfriedman18 I need to inspect your network log. Please stop by when you get a chance.

**Comment by faetea** [comment]
Here are the notes I just showed ya'll
You need to get the parent object and then set the child object.

```
createPromptResponse(promptResponse) {
      const prompt = this.get('prompt');

      const promptResponse = this.store.createRecord('promptResponse', {
        prompt: prompt
      });

      promptResponse.save().then((response) => {
        <stuff and things?>
        this.set('prompt', '');
      });

    }
  }
```

based on an example from this page: http://yoember.com/#lesson-6

**Comment by jrhorn424** [comment]
Don't pass parent IDs to form components. Pass the entire parent object and then attach it to the form object in the component.
