### ISSUE TITLE
Ember: not allowing unauthenticated user to main app route

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/capstone-project#123]
I have a route called "main" which I would like to block unauthenticated users from accessing. In my main route I have the following code:

``` js
  activate () {
    if (Ember.computed.not('isAuthenticated')) {
      this.transitionTo('sign-in');
    }
  },
```

This redirects to sign-in if the user is not signed in, as I intended, but if the user IS signed in, nothing renders on the route.

**Comment by MFBrewster** [comment]
With Matt's help, I removed the code above from the main route, and inserted the following code into the application route:

``` js
  activate () {
    if (!this.get('isAuthenticated')) {
      this.transitionTo('sign-in');
    }
  },
```

The only issue with this is that there is one other route I want to be accessible to an unauthenticated user (sign-up), and if the user tries to access that route from a url, they get redirected to sign-in anyway (links to sign-up still work fine). Still working on a solution to this.

**Comment by jrhorn424** [comment]
Are you still pursuing this given #120? If so, has it been addressed?

**Comment by MFBrewster** [comment]
I'm sorry, I thought I closed this yesterday. The problem has been solved. This is the code I put in my main route:

``` js
  activate () {
    if (!this.get('isAuthenticated')) {
      this.transitionTo('sign-in');
    }
  },
```
