### ISSUE TITLE
Unexpected behavior of Rails Record.select in the controller

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/capstone-project#126]
Any user should be able to see a list of participating organizations, but they shouldn't be able to see the associated activities for all those organizations. I thought I had a solution using Select on my organizations controller in Rails, to limit what info a non-admin receives, but somehow Ember is still able to show the activities to an unauthenticated user. Not good.

```
    def index
      if current_user && current_user.admin?
        @organizations = Organization.find(current_user.organization_id)
        p "admin orgs called"
      else
        @organizations = Organization.select("id, name, contact, goal")
        p "non auth org GET"
      end
      render json: @organizations
    end 
```

If an admin is signed in, information is displayed as expected.

Example Organizations Object:

```
"organizations": [
{
"id": 1,
"name": "New Company",
"contact": "Brian",
"goal": "Goals are nice",
"activities": [
  {
  "id": 3,
  "name": "New 3 activity", 
  "category": "category",
  "value": 5,
  "challenge": null,
  "user_id": 2,
  "organization_id": null,
  "created_at": "2016-04-06T15:59:19.482Z",
  "updated_at": "2016-04-06T15:59:19.482Z"
}]},
```

**Comment by jrhorn424** [comment]
@faetea Was this resolved?

**Comment by jenweber** [comment]
Not resolved. Somehow the issue text disappeared, but it's back now

**Comment by GA-MEB** [comment]
@jenweber can you paste the contents of your OrganizationSerializer?

**Comment by jenweber** [comment]
```
class OrganizationSerializer < ActiveModel::Serializer
  attributes :id, :name, :contact, :goal, :activities
end
```

**Comment by jrhorn424** [comment]
Network inspector time. @jenweber Come join me when you get a moment.

**Comment by jrhorn424** [comment]
The current plan is to move this logic out of the `OrganizationsController` and into the `ActivitiesController`. Not only is this more semantic, it will avoid touching the `OrganizationSerializer` and allow us to scope the logic more cleanly in `activities#index`.

**Comment by jenweber** [comment]
Solved:

The main issue was memory cache- when a user signs out, the data they had access to is retained in the Ember store. This can be fixed by adding a .then to the application signOut action, which clears the store. http://emberigniter.com/clear-ember-data-store/

Additionally, the Organization has many Activities through Users relationship was unnecessary and causing issues with creating new records and associating them properly. Has Many Through is only for many to many relationships, and mine is one is one to many. A simple has many and belongs to are all that is needed.
