### ISSUE TITLE
Associating a like to a specific game on the front end

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/capstone-project#127]
I have successfully connected likes to games on the back end by using the shovel operator on the rails console. The process on the front end has not gone as smoothly. I have tried sending patch requests to the servers trying to add the new like object to a specific game's likes array by hitting that game's route specifically. I have tried manually setting the associated game_id on the like when initially creating it yet the likes in the database show null instead of the value that I'm assigning it. I've also tried pushing the like object into the game's likes array but that only changed the array on the front end and didn't update the back end. I am looking for a possible different approach to this problem as the ones I have tried haven't worked. The entire process is to make this rails console code work on the front end:

```
callOfDuty = Game.first
firstLike = Like.first
callOfDuty.likes << firstLike
```

@MattB-GA-Boston @jrhorn424 @faetea

**Comment by jrhorn424** [comment]
I need to know:
- What request you are making (your ajax)
- What is handling the request (your controller, and possibly your routes)

**Comment by jdamiron** [comment]
What I've tried most recently is assigning the correct id to the like when it's intially created. This is the ajax request:

```
  myApp.id = $(event.target).attr("data-id");

  $.ajax({
      url: myApp.baseUrl + '/likes',
      method: 'POST',
      dataType: 'json',
      headers: {
        Authorization: 'Token token=' + myApp.user.token
      },
      data: {
        "game_id": myApp.id
      }
    })
    .done(function() {
      console.log("New Like!");
    }).fail(function(jqxhr) {
      console.log(jqxhr);
    });
```

Here is the likes controller:

```
# An like OpenReadController
class LikesController < OpenReadController
  before_action :set_like, only: [:update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all

    render json: @likes
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
    render json: Like.find(params[:id])
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = current_user.likes.build

    if @like.save
      render json: @like, status: :created, location: @like
    else
      render json: @like.errors, status: :unprocessable_entity
    end
  end

  def update
    if @like.update
      head :no_content
    else
      render json: @like.errors, status: :unprocessable_entity
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy

    head :no_content
  end

  def set_like
    @like = current_user.likes.find(params[:id])
  end

  private :set_like
end
```

**Comment by jdamiron** [comment]
@jrhorn424 that error is not correct, please ignore that

**Comment by jdamiron** [comment]
This is really the error:

```
(param is missing or the value is empty: game):
  app/controllers/games_controller.rb:27:in `games_params'
  app/controllers/games_controller.rb:15:in `update'
```

But it's when I was trying to send the patch request rather than the post request.

**Comment by jdamiron** [comment]
I tried changing the data by reflecting what I see on the back end like this:

```
data: {
        "likes": [
          {
          "game_id": myApp.id
          }
        ]
      }
```

but still no luck.

**Comment by jrhorn424** [comment]
What is the patch request? It looks like you're hitting two different controllers.

**Comment by faetea** [comment]
for update to work you need to include an ID and attributes, then you need to render json.
something like this:

```
+  if @like.update(the ID you are updating, and then the params)
+      render json: @like, status: :ok
```

**Comment by jdamiron** [comment]
@jrhorn424 I may have confused you because I've tried to do this two different ways. The first was by sending a patch request to the route of the specific game (localhost:3000/game/3), then setting the like key for a certain game to the value of the like object. This was using the games controller. Here is the code:

```
  let addLikeToGame = function(like) {
    $.ajax({
      url: myApp.baseUrl + '/games/' + myApp.id,
      method: 'PATCH',
      headers: {
        Authorization: 'Token token=' + myApp.user.token
      },
      data: {
        "games": [
          {
            "likes": like
          },
        ]
      }
    }).done(function() {
      console.log("Successfully added like.");
    }).fail(function(jqxhr) {
      console.error(jqxhr);
    });
  };
```

I stopped working on this method and moved onto trying a post request because jen recommended that I can set the game_id associated with the like right when I create it rather than trying to post it. This used the likes controller and that is the last method that I tried before submitting the issue.

**Comment by jdamiron** [comment]
rather than trying to _patch_ it. My mistake on the grammer.

**Comment by GA-MEB** [comment]
Can you paste in the code for your post request?
Jen's advice was good - the Like will have a `game_id` property, so you can just create a new Like with a `game_id` property equal to the id of the current game.

**Comment by jdamiron** [comment]
I tried:

```
 myApp.id = $(event.target).attr("data-id");

  $.ajax({
      url: myApp.baseUrl + '/likes',
      method: 'POST',
      dataType: 'json',
      headers: {
        Authorization: 'Token token=' + myApp.user.token
      },
      data: {
        "game_id": myApp.id
      }
    })
    .done(function() {
      console.log("New Like!");
    }).fail(function(jqxhr) {
      console.log(jqxhr);
    });
```

and

```
 myApp.id = $(event.target).attr("data-id");

  $.ajax({
      url: myApp.baseUrl + '/likes',
      method: 'POST',
      dataType: 'json',
      headers: {
        Authorization: 'Token token=' + myApp.user.token
      },
      data: {
        "games": [
          {
            "likes": like
          },
        ]
      }
    })
    .done(function() {
      console.log("New Like!");
    }).fail(function(jqxhr) {
      console.log(jqxhr);
    });
```

Which they create successfully but the ID is not attached on the back end:

```
{
"likes": [
{
"id": 1,
"game_id": null
},
{
"id": 2,
"game_id": null
},
{
"id": 3,
"game_id": null
},
{
"id": 4,
"game_id": null
}
]
}
```

BTW, using debugger, myApp.id grabs the correct id that I need.

**Comment by jdamiron** [comment]
This

```
 data: {
        "games": [
          {
            "likes": like
          },
        ]
      }
```

is really this

```
 data: {
        "games": [
          {
            "likes":myApp.id
          },
        ]
      }
```

I'm on a typo frenzy.

**Comment by jrhorn424** [comment]
> I'm on a typo frenzy.

Slow. Down.

Take a break if you need one, get some air and then tackle it again.

**Comment by jdamiron** [comment]
@jrhorn424 It was errors while copying and pasting, I don't necessarily feel burnt out I just need a new angle to approach this problem.

**Comment by faetea** [comment]
```
def create
  current_game = Game.find_by(params[:id])
  current_game.id = @like.game_id

    if @like.create(@like.id, @like.game_id)
      render json: @like, status: :ok
    else
      render json: @like.errors, status: :unprocessable_entity
    end
end
```

never-mind this didn't work

**Comment by faetea** [comment]
It looks like there might be a CORS error, but I'm not sure why.

**Comment by faetea** [comment]
Jeff solved.  @jdamiron said he would close.

**Comment by jdamiron** [comment]
likes: should have been like: ---- Also, likes controller needed strong params

**Comment by jrhorn424** [comment]
And don't use JSON.stringify!
