### ISSUE TITLE
Ember AJAX: GET request coming back as unauthorized

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/capstone-project#128]
My `product-window` template has the following code:

``` htmlbars
{{#each model as |product|}}
  <div class="product-button">
    <p><strong>{{product.name}}</strong></p>
  </div>
{{/each}}
```

And my component has this code: 

``` js
export default Ember.Component.extend({
  tagName: 'div',
  classNames: ['product-half main-app-window'],
  ajax: Ember.inject.service(),

  model() {
    return this.get('ajax').request('/products');
  }
});
```

When I try to do the AJAX request, it hits the correct controller, but comes back as unauthorized

``` sh
Started GET "/products" for ::1 at 2016-04-06 13:19:34 -0400
Processing by ProductsController#index as HTML
  Rendered text template (0.0ms)
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 6ms (Views: 5.1ms | ActiveRecord: 0.0ms)
```

My AJAX service looks like this:

``` js
export default AjaxService.extend({
  auth: Ember.inject.service(),
  headers: Ember.computed('auth.credentials.token', {
    get() {
      let headers = {};
      const token = this.get('auth.credentials.token');
      if (token) {
        headers['Authorization'] = `Token token=${token}`;
      }
      return headers;
    }
  })
});
```

Which seems to take the token from the auth service. The auth service looks just like Jeff's in the ember-auth repo. Why isn't my token attaching in the header? Help would be appreciated.

**Comment by jrhorn424** [comment]
You also have to set headers in your application adapter. The headers you've posted are only attached when you're using Ember's ajax service.

**Comment by MFBrewster** [comment]
My adapter seems to have similar code:

``` js
// app/application/adapter.js
...
export default ActiveModelAdapter.extend({
  auth: Ember.inject.service(),

  headers: Ember.computed('auth.credentials.token', {
    get() {
      let headers = {};
      const token = this.get('auth.credentials.token');
      if (token) {
        headers['Authorization'] = `Token token=${token}`;
      }
      return headers;
    }
  })
});
```

**Comment by jrhorn424** [comment]
Then my guess is the token is incorrect. Are you sure you're signed in? If you are, use `binding.pry` somewhere in rails to pause the request and inspect the local running environment.

**Comment by jrhorn424** [comment]
Was this resolved? If so, how?

**Comment by MFBrewster** [comment]
This was resolved, I wasn't using models before because I am a jackass. Not sure why the original issue got deleted up there ^

Hat tip to Matt for telling me there are such things as front-end models, and telling me what they do.
