### ISSUE TITLE
Ember Authentication

### ISSUE THREAD

**Issue by kelvinma** [ga-wdi-boston/capstone-project#13]
Any instructors have any insight in to Ember Authentication? I'm reading the documentation for Ember Simple Auth, but not sure where to start with implementation: https://github.com/simplabs/ember-simple-auth

Just going to build a simple, non-authenticated tracker in the mean time, but would be curious if any instructors have managed to get an authenticated Ember app working.

**Comment by jrhorn424** [comment]
I haven't done it. If you want to use simple auth, try this: https://github.com/jpadilla/ember-cli-simple-auth-token

**Comment by gaand** [comment]
Are you using rails or express on the backend?

**Comment by kelvinma** [comment]
I built my backend using the November Express Generator. At the moment, just trying to get my ember app to talk to my Nov. backend, but having issues getting everything talking to each other. I wanted to start with login, but moved on to something I thought I could accomplish...

**Comment by jrhorn424** [comment]
Was this related to sideloading data so Ember can use the RESTSerializer?

**Comment by kelvinma** [comment]
Not really. I'm currently just trying to hook up passport and express sessions to the November back end so I can do authentication with cookies.

**Comment by gaand** [comment]
See: https://github.com/ga-wdi-boston/portfolio-capstone-project/issues/20
