### ISSUE TITLE
Problem displaying songs associated with playlists

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/capstone-project#131]
I am trying to display the songs associated with each playlist. I have 

```
<div id="playlist-list">
<hr>
<li>Title: {{playlist.title}}</li>
<li>Description: {{playlist.desc}}</li>
<li>Based on: {{playlist.song.title}}</li>

{{#if isAuthenticated}}
<button class="btn btn-default">Add a new song!</button>
{{/if}}
</div>

{{yield}}
```

Before, the playlist.song was return an Ember promise, so I though well I need to resolve that problem so when I create the song and shove it into it's corresponding playlist I use .finally to resolve the promise. This sort of works...now when I use the back button to go back to the /playlists route... the song associated with the playlist appears in the {{playlist-snippet}}. BUT when I reload the page entirely the songs are gone.

**Comment by kpie89** [comment]
```
ember.debug.js:32161 Error: Assertion Failed: Passing classes to store methods has been removed. Please pass a dasherized string instead of undefined
```

Don't understand this. Does it have something to do with it?

**Comment by GA-MEB** [comment]
@kpie89 I'm not clear on what you're trying to do here.
"Based on:" should show the song that started the playlist, right?

What template is that code block from?

**Comment by kpie89** [comment]
It's from the "playlist-snippet" component. 

I'm trying to, when loading the /playlists route...show the playlists and the songs associated with each playlist.

**Comment by kpie89** [comment]
So I'm still getting this error when I try to load my playlists page. The Ember data store HAS the data on page load but nothing is rendering on the screen. The error is the same as the one I posted above. My research this has something to do with the way Ember is serializing the data? 

Because if I remove the has_many relationships from the songs controller in the back end everything loads but of course it has no idea which song is associated with which playlist. 

Do I need to generate a serializer for songs in Ember and tell it how to render my data?

**Comment by kpie89** [comment]
@jrhorn424 This is still a problem for me. When a user creates a playlist it attaches the song ID and then renders it appropriately on the next page. BUT when I reload the page the playlist loads but the song does not. I have been over my hasMany and belongsTo relationships and there doesn't seem to be any problems there. Is this some sort of issue with eager vs. lazy loading? I was under the impression that the song would load on the playlists/playlist id page simply because the playlist belongsTo song. Any advice?

**Comment by jrhorn424** [comment]
See #116 and #118. Let me know how it goes.

**Comment by kpie89** [comment]
The problem was that my serializer in my back end wasn't formatting the song_id for my ember serializer to look at. In my playlists serializer in the back end I simply added song_id like so 

```
class PlaylistSerializer < ActiveModel::Serializer
  attributes :id, :title, :desc, :song_id
end
```

BOOM

**Comment by jrhorn424** [comment]
@kpie89 Closeable?
