### ISSUE TITLE
Loading related models issue

### ISSUE THREAD

**Issue by dumplingpuff** [ga-wdi-boston/capstone-project#132]
So far I have a dynamic segment view for each trip model, but I am trying to load items onto the trip template.

```
// trip model
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  location: DS.attr('string'),
  arrival: DS.attr('date'),
  departure: DS.attr('date'),
  description: DS.attr('string'),

  items: DS.hasMany('item', { async: true }),
  users: DS.hasMany('user', { async: true })
});
```

This is what the model in the Trip route looks like

```
  model (params) {
    return this.store.findRecord('trip', params.trip_id);
  },
```

The relationship in the backend has many items so I was expecting that if I called model.items I could at least access the items from each trip.  I am unsure if this is a back end issue or a data connection issue on ember.  Let me know if you need to have more information provided.  Thanks in advance.

**Comment by GA-MEB** [comment]
What did you put in your template?

**Comment by dumplingpuff** [comment]
I am calling .items in the template or component.  To keep it simple hypothetically template for trip would look like this:

```
  {{#each model.items as |item|}}
    <p>{{item.content}}</p>
  {{/each}}
```

**Comment by dumplingpuff** [comment]
Issue resolved.   Added items to serializer on backend for trips and assigned items: DS.attr() on the trip model on front end.
