### ISSUE TITLE
Trouble loading multiple models into single route

### ISSUE THREAD

**Issue by nwilcox11** [ga-wdi-boston/capstone-project#133]
```
export default Ember.Route.extend({
  model () {
    return {
      workouts: this.get('store').findAll('workout'),
      exercises: this.get('store').findAll('exercise'),
    };
  },
```

I am getting a 404 not found error when trying to load exercises.
User has many workouts, workouts have many exercises.
here is my exercises controller

```
class ExercisesController < ProtectedController
  before_action :set_workout, only: [:show, :create, :index, :update, :destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = @workout.exercises

    render json: @exercises
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
    @exercise = @workout.exercises.find(params[:id])
    render json: @exercise
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = @workout.exercises.build(exercise_params)

    if @exercise.save
      render json: @exercise, status: :created, location: @exercise
    else
      render json: @exercise.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    @exercise = @workout.exercises.find(params[:id])

    if @exercise.update(exercise_params)
      head :no_content
    else
      render json: @exercise.errors, status: :unprocessable_entity
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise = @workout.exercises.find(params[:id])
    @exercise.destroy

    head :no_content
  end

  private

    def set_workout
      @workout = current_user.workouts.find(params[:workout_id])
    end

    def exercise_params
      params.require(:exercise).permit(:name, :sets, :reps, :weight, :workout_id)
    end
end


```

**Comment by GA-MEB** [comment]
@nwilcox11 Unless the routes are nested, it's not possible to `set_workout` on an `#index` action - there's no `:workout_id` passed in through the URL. 

If they _are_ nested, you may need to make some modifications to the adapter for Workouts.

**Comment by nwilcox11** [comment]
shit ok, I thought I would be able to.  So how would I be able to get exercises that are associated with a specific workout?

**Comment by nwilcox11** [comment]
@MattB-GA-Boston workouts have many exercises

**Comment by GA-MEB** [comment]
Well, I think you have two options. Either (a) use nested routes, and pass in the id of the workout you want through the URL, or (b) query the back-end for _all_ of the current user's exercises, and filter those down by workout id.

**Comment by nwilcox11** [comment]
@MattB-GA-Boston 

```
Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('workouts');
  this.route('new-workout');
  this.route('workout', { path: '/workouts/:workout_id/'});

});
```

this is my router currently.  That last route gets me a single workout view.  So my trouble is getting the exercises associated with that workout.

I think I want to try the nested routes option.  But should I rewrite the exercise  controller?

**Comment by jrhorn424** [comment]
Make one change at a time. Work on nested routes. That may lead to errors, but they should guide you through the proper re-write of certain portions of the controller.

**Comment by faetea** [comment]
@nwilcox11  How are your nested routes going?
