### ISSUE TITLE
Rails: Associating two foreign keys on one record during Create

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/capstone-project#134]
An organization has may users, who have many activities. When an activity is created, how can I set both the organization_id and the user_id? The organization_id is a field that is available on the user.

```
  def create
    @activity = current_user.activities.build(activity_params) // this sets the user_id, but not org_id
    if @activity.save
      render json: @activity, status: :created, location: @activity
    else
      render json: @activity.errors, status: :unprocessable_entity
    end
  end
```

This only sets the organization id and not the user id:
`@activity = current_user.organization.activities.build(activity_params)`

**Comment by GA-MEB** [comment]
> `@activity = current_user.activities.build(activity_params) // this sets the user_id, but not org_id`

@jenweber Why should it set an organization id? An activity doesn't have an organization id. An activity belongs to a user, so it has a user id. A user belongs to an organization, so a user has an organization id.
Presumably, current_user already has an organization id, no?

**Comment by jenweber** [comment]
If the activity has an organization id, it lets me use the activities controller in Rails to determine who can see that activity. I want admins of an organization to be able to see only the activities that "belong to" their organization. And a regular user sees only activities that belong to themselves. You are correct that current_user has an organization_id.

The activities controller below works as desired for Index, but I am having trouble setting the organization_id on create, unless I use a curl script.

```
  def index
    if current_user && current_user.admin?
      @activities = current_user.organization.activities
    else
      @activities = current_user.activities
    end
    render json: @activities
  end
```

**Comment by GA-MEB** [comment]
@jenweber 
I just learned this yesterday, but you can apparently use `has_many ... through: ...` to create methods that reference grandchild records.

In other words, doing this: 

``` ruby
class Organization
   # ...
   has_many :activities, through: :users
end
```

will allow you to write this:

`organization.activities`

That might help to address your issue.

**Comment by jrhorn424** [comment]
@jenweber If you want, we can walk through your modeling with an up-to-date ERD and analyze whether we can simplify these relationships and still achieve what you want.

**Comment by jenweber** [comment]
@jrhorn424 that would be great

@MattB-GA-Boston I had something like that initially, but I was having too many difficulties with privacy. A non logged in user needed to be able to do an index, but not see the activities associated with every company. Unfortunately I was not able to prevent the join from being sent with the index. So we stripped away the has many.

**Comment by jenweber** [comment]
Solved, will comment shortly with how

**Comment by jenweber** [comment]
Solution: 
We established the has-many and belongs-to relationships in the Ember Front End.

For the back end, on the organization, we added the organization has_many activities through users back in. In the serializers, we removed the :activities and the :organization and left only the id reference.

In this way, who sees what activities is controlled entirely from the activities controller.
