### ISSUE TITLE
Including jQuery mobile?

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/capstone-project#136]
@jrhorn424 As far as I've come in understanding how webpack and your template work, I'm still confused about how I might go about including jQuery mobile so that its functions are available globally by using the $ syntax.

**Comment by faetea** [comment]
So. `artswipe-front-end/index.js` is where jQuery is being attached globally

```
require('expose?$!jquery');
require('expose?jQuery!jquery');
```

Are you looking to just add jQuery mobile?  
because you can add jQuery to the bottom of the index.html as long as it's inside the </html> tag.
I assume that jQuery mobile is only for mobile devices, or does it support computer browses as well?
I can see you already have a few JavaScripts at the top of your index.html.

**Comment by rchezrutt88** [comment]
This is exactly what I don't want to do, because it violates the whole point of using webpack. Will it work? Yeah.

What I'm asking is how to include jQuery mobile by same technique as regular jQuery has already been added to the template. 

It's part of my whole apparently idiotic obsession with doing things "the right way."

**Comment by faetea** [comment]
I can tell that jQuery was installed in the js-template via an npm package, because it is listed in the package.json as:

```
"dependencies": {
    "google-maps": "^3.2.1",
    "handlebars": "^4.0.5",
    "jquery": "^2.2.3"
  },
```

Also, it is located in the node_modules folder.

jQuery mobile is available for npm install as well.  [npm/jquery-mobile](https://www.npmjs.com/package/jquery-mobile)
Have you tried installing it into your project yet?

**Comment by jrhorn424** [comment]
> ... so that its functions are available globally by using the $ syntax.

jQuery mobile hooks into jQuery. You don't want to require it? `let $ = require('jquery')`? I really don't recommend making it available globally.

```
require('expose?$!jquery');
require('expose?jQuery!jquery');
```

This actually **does not** attach jquery globally. It injects it into the window object in the browser so you can use it in the web console.

What you want to do is install jquery-mobile from npm, then include it in the vendor bundle, as jquery is. https://github.com/ga-wdi-boston/js-template/blob/master/grunt/webpack.js#L11

**Comment by rchezrutt88** [comment]
Should I do this: https://www.npmjs.com/package/jquery-mobile#download-builder

…or just install the whole package with npm?

**Comment by rchezrutt88** [comment]
@jrhorn424 
I ran `npm install jquery-mobile --save` and then added it to entry->vendor in webpack.js...and now I get this when I run `grunt build`

```
ERROR in multi vendor
Module not found: Error: Cannot resolve module 'jquery' in /Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/front-end
 @ multi vendor

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'jquery-mobile' in /Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/front-end
 @ multi vendor

ERROR in ./index.js
Module not found: Error: Cannot resolve module 'jquery' in /Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/front-end
 @ ./index.js 15:0-26

ERROR in ./index.js
Module not found: Error: Cannot resolve module 'jquery' in /Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/front-end
 @ ./index.js 16:0-31

ERROR in ./~/bootstrap-sass/assets/javascripts/bootstrap.js
Module not found: Error: Cannot resolve module 'jquery' in /Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/front-end/node_modules/bootstrap-sass/assets/javascripts
 @ ./~/bootstrap-sass/assets/javascripts/bootstrap.js 1:0-17

ERROR in ./assets/scripts/index.js
Module not found: Error: Cannot resolve module 'jquery' in /Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/front-end/assets/scripts
 @ ./assets/scripts/index.js 1:0-17

ERROR in ./assets/scripts/map.js
Module not found: Error: Cannot resolve module 'jquery' in /Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/front-end/assets/scripts
 @ ./assets/scripts/map.js 1:0-17
Warning: Task "webpack:build" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by rchezrutt88** [comment]
Okay, really weird. Still getting these errors even after checking out a pre-jquery mobile install commit. Did installing jquery mobile alter the regular jquery module? Changes I wouldn't see because the node-modules folder isn't checked into version control?

**Comment by rchezrutt88** [comment]
Seems my hunch was correct. Reinstalled jquery and now it's able to build. So back to where I started, at least?

**Comment by rchezrutt88** [comment]
Used [hammer.js](http://hammerjs.github.io/), a much slimmer library that just includes touch gesture functionality without all of jQuery Mobile's extra garbage. Works great, I love it.
