### ISSUE TITLE
Accidentally cloned a repo inside another repo

### ISSUE THREAD

**Issue by LaurenGrant** [ga-wdi-boston/capstone-project#14]
When I created my back-end repo for project 4, I accidentally cloned the Antony's api repo into mine and not sure how to fix this. Hopefully it is still early enough to fix this without being too damaging to my work so far. 

Can this be fixed from either git or github or do I need to make a new back-end repo and start over?

**Comment by srhoulam** [comment]
Is any of your work inside the repo-within-a-repo?

**Comment by LaurenGrant** [comment]
All of it I think. It was only about an hours worth of work so I wasn't too far in my api.

**Comment by srhoulam** [comment]
I'll come around and help you extricate the two repos.

**Comment by LaurenGrant** [comment]
Thank you. I am in the dugout.
