### ISSUE TITLE
Creating a Profile

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/capstone-project#142]
I am trying to create profiles associated one to one with a user. I am sending a post request but I'm not sending the correct data. I was looking for a mirror server so I can see the JSON that I'm sending. Here is the post request for profiles.

```
let createProfile = function(event) {
  event.preventDefault();
  let submitData = new FormData(event.target);
  submitData.append("profile[user_id]", myApp.user.id );
  $.ajax({
      url: myApp.baseUrl + '/profiles',
      type: 'POST',
      // dataType: 'json',
      contentType: false,
      processData: false,
      headers: {
        Authorization: 'Token token=' + myApp.user.token
      },
      data: submitData
    })
    .done(function() {
      console.log("New Profile!");
      getProfile();
    }).fail(function(jqxhr) {
      console.log(jqxhr);
    });
};
```

**Comment by faetea** [comment]
What do you mean by a mirror server?

**Comment by jdamiron** [comment]
@faetea Jeff told me of a echo server in the node-api-promises repo. Basically a server that I can send requests to and get the JSON back so I can see exactly what I'm sending.

**Comment by faetea** [comment]
Okay, echo server makes more sense.  mirror server means a server that is a back-up/copy of another server.

**Comment by faetea** [comment]
was it this one https://www.npmjs.com/package/echo-server?

**Comment by faetea** [comment]
What does your Rails controller look like?  Have you sent a curl request to your Rails controller?

**Comment by jdamiron** [comment]
I have I was working on it with Matt but got lost in the shuffle, I'm temporarily working on another feature at the moment.

**Comment by jdamiron** [comment]
Here is my controller anyhow:

```
# An profile OpenReadController
class ProfilesController < OpenReadController
  # before_action :set_profile, only: [:update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    render :json => Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    render json: Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    binding.pry
    @profile = current_user.profile.build(profile_params)

    if @profile.save
      render json: @profile, status: :created, location: @profile
    else
      render json: @profile.errors, status: :unprocessable_entity
    end
  end

  def update
    if @profile.update(profile_params)
      head :no_content
    else
      render json: @profile.errors, status: :unprocessable_entity
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy

    head :no_content
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :location, :user_id)
  end
  private :profile_params
end

```

**Comment by faetea** [comment]
Based on your Rails controller it looks like your ajax should be sending something like:

```
"profile": {
  "name": "",
  "location": ""
}
```

I am not really sure about your `let submitData`.  I don't know what it is going to pass or how it is going to format it.  Other than `myApp.user.id` which I talked about with you yesterday.

```
let submitData = new FormData(event.target);
submitData.append("profile[user_id]", myApp.user.id );
```

Did you set up the echo server that you said Jeff had mentioned to you?

**Comment by jrhorn424** [comment]
@jdamiron Here's a good echo server http://httpbin.org

**Comment by jdamiron** [comment]
Change this line in the controller from

```
@profile = current_user.profile.build(profile_params)
```

to

```
@profile = Profile.create!(profile_params)
```
