### ISSUE TITLE
Can't get a one to many relationship to work when creating a child.

### ISSUE THREAD

**Issue by dumplingpuff** [ga-wdi-boston/capstone-project#143]
So I have a one to many relationship.  A trip has many items.  When creating an item I am trying to get the item associated with the trip it is in.  Problem is I have no way of pulling the trip id on ember to run the necessary functions like trip.items.pushObject(item) to get it associated.

**Comment by faetea** [comment]
Don't pass parent IDs to form components. Pass the entire parent object and then attach it to the form object in the component.

**Comment by dumplingpuff** [comment]
did that just have an issue with the pushobject method saying it is undefined.

**Comment by dumplingpuff** [comment]
```
    createItem(item, trip) {
      // console.log(model);
      // console.log(this.get('trip'));
      console.log('Route Action: create item');
      console.log('Gettting item');
      console.log(item);
      console.log('Gettting model');
      console.log(trip.get('items'));
      this.store.createRecord('item', item);
      // let oneTrip = this.store.findRecord('trip', trip.id);
      this.store.findRecord('trip', trip.id).get('items').pushObject(item);
      item.save().then(()  => console.log('record created'));
    }
  }
```

**Comment by faetea** [comment]
what file is this in?

**Comment by dumplingpuff** [comment]
the trip route file

**Comment by faetea** [comment]
user is undefined? trip is undefined? item is undefined?

**Comment by dumplingpuff** [comment]
so I know that item is defined because I have performed create on it before.

**Comment by dumplingpuff** [comment]
I am thinking it is the trip.get('items') is undefined.
I slightly remember we need a computed property to unlock elements to use.

**Comment by jrhorn424** [comment]
Around the line you are getting your error, try these steps:

``` js
// show trip is working
      console.log('trip is', this.store.findRecord('trip', trip.id));
// show that items is working
      console.log('items are', this.store.findRecord('trip', trip.id).get('items'));
// what is item?
      console.log('new item is', item);
```

**Comment by dumplingpuff** [comment]
This line isn't working.   

```
this.store.findRecord('trip', trip.id).get('items'));
```

**Comment by jrhorn424** [comment]
> This line isn't working.

What does that mean? What is the error?

**Comment by dumplingpuff** [comment]
It's coming in as undefined.

**Comment by jrhorn424** [comment]
Plan is to pass parent object into child component and set it on the component's form object. @faetea may be able to provide further support if @dumplingpuff gets blocked again.

**Comment by dumplingpuff** [comment]
Will continue to solve this later.... on my own.... all alone.   Soooo sad.
