### ISSUE TITLE
Rails create method not working

### ISSUE THREAD

**Issue by ajordon** [ga-wdi-boston/capstone-project#144]
My create action for my Assignments is not working correctly. I already have a binding.pry inside the create method and I am not getting paused.

For some reference:
![image](https://cloud.githubusercontent.com/assets/6088950/14365116/fc266708-fcd9-11e5-938e-3fcafbe98f8f.png)

``` ruby
def create
    ##Find all students for this classroom and give them the assignement
    # @students = set_students
    # @assignment = Assignment.new(assignment_params)
    binding.pry
    @assignment = Classroom.assignements.new(assignment_params)
    @assignment.user_id = current_user

    if @students
      @students.assignements.new(assignment_params)

      if @assignment.save && @students.save
        render json: @assignment, status: :created, location: @assignment
        render json: @students, status: :created, location: @students
      else
        render json: @assignment.errors, status: :unprocessable_entity
        render json: @students.errors, status: :unprocessable_entity
      end
    else
      if @assignment.save && @students.save
        render json: @assignment, status: :created, location: @assignment
      else
        render json: @assignment.errors, status: :unprocessable_entity
      end
    end
  end
```

**Comment by faetea** [comment]
My gut impulse is that you can't just have `if @students` without any method.
I might try `.present?`  An object is present if it's not blank.  It returns true/false

``` ruby
-    if @students
+    if @students.present?
```

**Comment by ajordon** [comment]
There seems to still be a query for students when there is a create firing. Also my binding.pry is still not pausing

**Comment by GA-MEB** [comment]
The `#create` action wasn't being hit because the action's "before-action" callback, `set_students`, was erroring out.
