### ISSUE TITLE
Load Data from Service to Component Model

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/capstone-project#148]
My `sale` service has the following action: 

``` js
  addProduct (product) {
    this.get('order').products.pushObject(product);
    console.log(this.get('order').products);
  },
```

It works as it should, and logs the data I expect in the console. I try to access this data in a component. Here's the relevant component template:

``` htmlbars
<ul>
  {{#each model as |product|}}
    <li>{{product.name}}</li>
  {{/each}}
</ul>
```

And here's the relevant component.js file:

``` js
export default Ember.Component.extend({
  tagName: 'div',
  classNames: ['sub-total'],

  sale: Ember.inject.service(),
  prodArray: Ember.computed('sale', function () {
    return this.get('sale').order.products;
  }),

  model () {
    return this.get('prodArray');
  },


});
```

Nothing is displaying when I push new data into the `this.get('sale').order.products` array, and it seems like the data is not being updated in the component model. I've tried a number of syntactic fixes which do not seem to be working. Any help would be greatly appreciated.

**Comment by GA-MEB** [comment]
@MFBrewster OK to mark closed?

**Comment by MFBrewster** [comment]
Yes, I'll write down the solution and close it. Thank you!

**Comment by MFBrewster** [comment]
``` js
// component
import Ember from 'ember';

export default Ember.Component.extend({
  tagName: 'div',
  classNames: ['sub-total'],

  sale: Ember.inject.service(),
});
```

``` htmlbars
{{!-- template --}}
<ul>
  {{#each sale.order.products as |product|}}
    <li>{{product.name}}</li>
  {{/each}}
</ul>
```
