### ISSUE TITLE
How to change default AJAX URL

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/capstone-project#149]
I deployed my front end app, and the front end looks fine, but it's not hitting the back end API. I'm certain that I just need to change the base URL for my requests, but nothing in my config/environment.js file is helping me to get to the right URL. Here is feedback from my Network tab when I try to sign up:

```
Request URL:http://mfbrewster.github.io/sign-up
Request Method:POST
Status Code:405 Method Not Allowed
Remote Address:199.27.76.133:80
```

It looks like this: 
![image](https://cloud.githubusercontent.com/assets/8867447/14371892/ea62ed2c-fd09-11e5-8ce0-14f6d31de314.png)

Anyone who helps will be in my eyes the most golden of gods and or heroes.

**Comment by RealWeeks** [comment]
@MFBrewster  I'm going to close this are we are giving this prompt to the next cohort.  Please reopen if this is still an ongoing issue.
