### ISSUE TITLE
Shhhh! It's a secret

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/capstone-project#15]
OK, so I want to keep my MapBox key a secret. I know how do this on the backend using a .env file, but my research into doing it in JavaScript is not coming up with much. I'd like to avoid doing this https://github.com/motdotla/dotenv, because it's not a node project, and I'm not sure how this would work deploying to gh-pages. 
Help?

**Comment by jrhorn424** [comment]
You can't keep keys a secret on the front-end. They're visible in the source and console.

**Comment by jrhorn424** [comment]
@kelvinma Can provide a bit of insight here.

**Comment by kelvinma** [comment]
Just seeing this now. Yes, you can store your token in your .env, write a route to access it and make a GET request for it via the front end.

**Comment by raq929** [comment]
Ah, OK. Thanks!

**Comment by gaand** [comment]
You could restrict access to the token to authenticated users for a small increase in the security of the token.  If your client can get the token, then others making the sane request can also get the token.

Please close this issue if you think you're all set.  Thanks.
