### ISSUE TITLE
Difficulty Deploying Rails API -- Secrets

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/capstone-project#150]
I'm getting this error when I try to deploy my Rails server to Heroku:

```
Internal Server Error

Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`
```

Could someone point me in the direction of the resources to solve this? I know I've dealt with this in the past but I'm having a hard time tracking down the solution. I've tried setting the secret variables in the environment using "heroku config:set SECRET_TOKEN=<TOKEN>" but it hasn't helped. The rails deployment guide doesn't address this issue.

Any help appreciated!

**Comment by soynog** [comment]
Okay, I got it working by removing secrets.yml from .gitignore and pushing it to Heroku. I don't know if that's okay--should I have removed my test and development secrets first? Seems like it gets the production secrets from the environment so I guess that's okay?

**Comment by gaand** [comment]
`git add --force` should also work.

You need the file and SECRET_TOKEN defined in the heroku app settings, and then you should be all set.  The development and test keys don't need to be secret if you created a new key for the `heroku config:set` command.

**Comment by gaand** [comment]
@soynog I think this has a resolution.  If you agree, please close the issue.  Thanks.

**Comment by soynog** [comment]
All set. I was able to solve the issue by generating secrets using Heroku commands and pushing my secrets.yml file to github.
