### ISSUE TITLE
TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by rdelvallej32** [ga-wdi-boston/capstone-project#152]
Hi,

I'm using Ember for the front end and I am doing basic testing to see if I can properly render my data before adding components. I have two resources 'Topics' and 'Ratings' and I have added both a route and a model hook for these resources. When I type http://localhost:4200/topics, I am able to see all of the topics being rendered on the template. However, when I type http://localhost:4200/ratings, I receive an error on the console saying:

ember.debug.js:32096TypeError: Cannot read property 'some' of undefined
    at error (route.js:21)
    at Object.triggerEvent (ember.debug.js:28580)
    at Object.trigger (ember.debug.js:53473)
    at Object.Transition.trigger (ember.debug.js:53287)
    at ember.debug.js:53107
    at tryCatch (ember.debug.js:53806)
    at invokeCallback (ember.debug.js:53821)
    at publish (ember.debug.js:53789)
    at publishRejection (ember.debug.js:53724)
    at ember.debug.js:32054

Which is strange because in my rails console, I am receiving a HTTP: 200 response. Is there some error within the code of my routes? I made sure to mirror ratings similar to topics. Or is this an association issue? Both a USER and a TOPIC have many ratings. I provided snippets of my code below:

Rating Model:

``` js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { belongsTo } from 'ember-data/relationships';

export default Model.extend({
  score: attr('number'),
  user: belongsTo('user'),
  topic: belongsTo('topic')
});

```

Rating Route:

``` js

import Ember from 'ember';

export default Ember.Route.extend({
  model(params) {
    return this.get('store').findRecord('rating', params.id);
  },
});

```

Ratings Route:

``` js

import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return this.get('store').findAll('rating');
  },
});

```

Router

``` js

import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
});

Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('topics');
  this.route('topic', { path: '/topics/:id'});
  this.route('ratings');
  this.route('rating', { path: '/ratings/:id'});
  // Custom route in topics controller that will call NYT API or generate random-show
  //topic. This is a GET request essentially
  this.route('random-show');
});

export default Router;

```

**Comment by gaand** [comment]
Are their topics that own ratings?  Are their users that own ratings?  I think it's probably related to the model relationships.

What does your topic model look like?

**Comment by rdelvallej32** [comment]
I guess how I was thinking was that any User can see a topic, but a user has the ability to rate that topic, so my understanding in the ERD was a User has many Ratings of Topics. How i connected that in my database was creating a rating schema that held the topic_id, and the user_id along with the score. Am I, making this more complicated?

``` js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { hasMany } from 'ember-data/relationships';

export default Model.extend({
  content: attr('string'),
  category: attr('string'),
  nyt_article: attr('boolean'),
  ratings: hasMany('rating'),

});

```

**Comment by rdelvallej32** [comment]
I console logged the error and this is what I receive 

EmberError {description: undefined, fileName: undefined, lineNumber: undefined, message: "Assertion Failed: You need to pass a model name to the store's modelFor method", name: "Error"…}

**Comment by gaand** [comment]
This looks like a file is missing or misnamed.

**Comment by rdelvallej32** [comment]
So, when I remove the belongsTo, I no longer receive the error, however I am concerned that its a relationship issue?

``` js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { belongsTo } from 'ember-data/relationships';

export default Model.extend({
  score: attr('number'),
  // user: belongsTo('user'),
  // topic: belongsTo('topic')
});

```

**Comment by rdelvallej32** [comment]
SOLVED! Read the DOCS, and used EXPLICIT INVERSNESS:

https://guides.emberjs.com/v2.5.0/models/relationships/

Apparently, Ember needs help understanding when you have multiple has Many or Belong to for the same type.

**Comment by jrhorn424** [comment]
Are you serializing out from your API an array of topic IDs?

**Comment by soynog** [comment]
My issue seems possibly related, but I've tried adding explicit inverses already and it doesn't seem to have helped. Should I move my comments over to this thread?

**Comment by gaand** [comment]
@soynog No.  Please keep them with your issue.
