### ISSUE TITLE
Error thrown when one-to-one relationship added in Ember models

### ISSUE THREAD

**Issue by olivia-leach** [ga-wdi-boston/capstone-project#153]
Hi there,

I'm having issues setting up a one-to-one relationship for 2 of my models in Ember. Each 'building' has one 'baseline'. My models are set up as follows:

Building model:

``` js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { belongsTo } from 'ember-data/relationships';

export default Model.extend({
  name: attr('string'),
  address: attr('string'),
  city: attr('string'),
  state: attr('string'),
  zip: attr('string'),
  lat: attr('number'),
  long: attr('number'),
  sq_ft: attr('number'),
  year_const: attr('date'),
  num_floors: attr('number'),
  notes: attr('string'),
  user: belongsTo('user'),
  baseline: belongsTo('baseline')
});
```

Baseline model:

``` js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { belongsTo } from 'ember-data/relationships';

export default Model.extend({
  certified: attr('boolean'),
  building: belongsTo('building'),
});
```

The relationship for buildings and users (`user: belongsTo('user')`) works fine, but when I add the `baseline: belongsTo('baseline')` line in the building model, I get the standard `ember.debug.js:32096TypeError: Cannot read property 'some' of undefined` in the chrome console.

I know the API is returning the baseline data because if I change `baseline: belongsTo('baseline')` to `baseline: attr()`, I can access the baseline object for a particular building (but I can't access any of the models below that, which I will have to do after I finish this part).

When I go to localhost:3000/buildings/1, I see:

``` json
{
"building": {
"id": 1,
"BID": 5,
"name": "Crescent VII C",
"address": "8390 East Crescent Parkway",
"city": "Greenwood Village",
"state": "CO",
"zip": "80111",
"lat": 39.622378,
"long": -104.890485,
"sq_ft": 135332,
"year_const": 1938,
"num_floors": 6,
"notes": "One building, partly renovated to green",
"user_id": 1,
"baseline": {
"id": 1,
"certified": false,
"building_id": 1,
"created_at": "2016-06-05T17:45:15.381Z",
"updated_at": "2016-06-05T17:45:15.381Z"
}
}
}
```

I also tried setting up this relationship with a hasMany/belongsTo relationship instead, just to see if that would work. I don't get an error in the console when I do that, but still the 'baseline' data isn't loading.

**Comment by gaand** [comment]
Did you search closed issue?  Roberto resolved a similar problem today.

**Comment by olivia-leach** [comment]
Yes, just spoke with him and his issue was slightly different. He wasn't dealing with one-to-one relationships.

**Comment by RealWeeks** [comment]
have you you tried the DS.belongsTo, i'm reffing the docs here https://guides.emberjs.com/v2.0.0/models/defining-models/

**Comment by olivia-leach** [comment]
Yes--that's how I had it set up (see the models above). I think I'm having some luck with editing my serializer using these docs: http://emberjs.com/api/data/classes/DS.EmbeddedRecordsMixin.html. I am now getting the baseline data to load through the buildings but am also receiving this warning in the chrome console:

`WARNING: There is no attribute or relationship with the name `baseline` on `baseline`. Check your serializers attrs hash.`

I've edited my app/application/serializer.js to be:

```
import { ActiveModelSerializer } from 'active-model-adapter';
import DS from 'ember-data';

export default ActiveModelSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    baseline: { embedded: 'always' }
  }
});
```

**Comment by olivia-leach** [comment]
Fixed! I created a serializer for building (`ember g serializer building`) and added this code:

```
import { ActiveModelSerializer } from 'active-model-adapter';
import DS from 'ember-data';

export default ActiveModelSerializer.extend(DS.EmbeddedRecordsMixin,{
  attrs: {
    baseline: {embedded: 'always'}
  }
});
```
