### ISSUE TITLE
XHR finished loading message in console

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/capstone-project#155]
`abstract-xhr.js:132 XHR finished loading: GET "http://localhost:8080/sockjs-node/info?t=1465232556817".AbstractXHRObject._start @ abstract-xhr.js:132(anonymous function) @ abstract-xhr.js:21`

I'm getting my user crud requests all working properly but I get this message in the console whenever I load my page, I just don't know what it is.

I am developing in private mode.

**Comment by RealWeeks** [comment]
Is this causing an error? or due to an error? If not leave it for now, and focus on other things. Looks like it's just telling you XHR finished.

**Comment by BenGitsCode** [comment]
Honestly I'm not even sure. Anytime I start fresh I see it. It's not necessarily an error, it looks like a successful GET request that I don't understand. It may not matter at all but I don't want it to be an issue I have to diagnose later.

**Comment by gaand** [comment]
Do other developers get the same message?

**Comment by BenGitsCode** [comment]
@gaand I can confirm at least Phil is as well.

**Comment by RealWeeks** [comment]
sidebar this for now then

**Comment by gaand** [comment]
Have you searches the web?

**Comment by BenGitsCode** [comment]
I've made it disappear but turning off the 'Log XMLHttpRequests' option in the console. I believe we turned it on during one of our tranings in the past couple weeks. Perhaps it's not an issue at all and I'm just not used to seeing it since we usually had that console setting turned off.

@gaand I have, but founding nothing of value—nor concern.

Will close issue for now. The above removes it from my console, and if I can't see it, not understanding it doesn't stress me out.

**Comment by jrhorn424** [comment]
That's the hot reloader working. Nothing to be concerned about.

**Comment by BenGitsCode** [comment]
@jrhorn424 Thanks Jeff. It was just taken aback by it, had never seen it before we changed that setting during our lesson. There's so much to know in the dev tools. Do you know of any solid resources on all of it's features? Or is it just more of a keep playing and learning forever type of thing?

**Comment by jrhorn424** [comment]
@Benjamski https://umaar.com/dev-tips/
