### ISSUE TITLE
Saving API responses in database

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/capstone-project#157]
So I have working responses from the third party PokeAPI, with the following code for the Pokemon model:

``` rb
class Pokemon < ActiveRecord::Base
  has_many :types, inverse_of: :pokemons
  has_many :moves, inverse_of: :pokemons

  def self.find(id)
    response = HTTParty.get("http://pokeapi.co/api/v2/pokemon/#{id}")
    h = JSON.parse(response.body)

    typeone = h['types'].find { |h1| h1['slot'] == 1 }['type']['name']
    typetwo = ''
    if h['types'].length > 1
      typetwo = h['types'].find { |h1| h1['slot'] == 2 }['type']['name']
    else
      typetwo = ''
    end



    {
      name: response['name'],
      type1: typeone,
      type2: typetwo,
      hp: h['stats'].find { |h1| h1['stat']['name'] == 'hp' }['base_stat'],
      attack: h['stats'].find { |h1| h1['stat']['name'] == 'attack' }['base_stat'],
      defense: h['stats'].find { |h1| h1['stat']['name'] == 'defense' }['base_stat'],
      spatk: h['stats'].find { |h1| h1['stat']['name'] == 'special-attack' }['base_stat'],
      spdef: h['stats'].find { |h1| h1['stat']['name'] == 'special-defense' }['base_stat'],
      speed: h['stats'].find { |h1| h1['stat']['name'] == 'speed' }['base_stat']
    }
  end
end
```

I'm struggling with where and how to put the code for saving API responses to the database once per day.  Does it go in the model?  How to make sure that it'll fire once a day to update the database, and that it fires upon database creation to seed the data?

**Comment by RDegnen** [comment]
Im not totally certain but you could probably run a transaction in your model much like we did with the csv file in the Activerecord lessons. You could iterate over the response, and save each object as you went over them. There is probably some way to tell rails to do that once a day

**Comment by RDegnen** [comment]
``` rb
Person.transaction do
  CSV.foreach(Rails.root + 'data/people.csv',
              headers: true) do |person_row|
    person = person_row.to_hash
    Person.create!(person) unless Person.exists?(person)
  end
end
```

Something like that

**Comment by sjf125** [comment]
ok cool - this definitely helps with the how, I just need a when.  Would it be something like, upon my API being called, check all records for updated_at - if they're more than a day old, then run transaction code?

**Comment by sjf125** [comment]
Also I don't have a CSV file, it's just a model, and an initially-empty database - how would I point it to my db?

**Comment by RDegnen** [comment]
`<Model>.transaction` is what points it to your database. You would replace the csv file with the api response, i was just using the csv code as an example. And yea looking at updated_at or created_at and checking if they are less than the current date is probably a good way to go about it.

**Comment by gaand** [comment]
We should chat about the data flow that makes sense for your app.

**Comment by sjf125** [comment]
Talked with Antony - going to move out the API calls from model into separate seeds script, will run rake db:seeds to populate database with info from PokeAPI.  Will reopen if I can't figure it out

**Comment by sjf125** [comment]
I'm using the following code in my seeds file, it runs ok, but it doesn't seem to actually create any new rows.  That or I don't know where to look for the new rows:

``` rb
poketotal = HTTParty.get("http://pokeapi.co/api/v2/pokemon/")
l = JSON.parse(poketotal.body)['results'].length



id = 1
until id == 3 do
  response = HTTParty.get("http://pokeapi.co/api/v2/pokemon/#{id}")


  Pokemon.transaction do
    response.body do
      typeone = h['types'].find { |h1| h1['slot'] == 1 }['type']['name']
      typetwo = ''
      if h['types'].length > 1
        typetwo = h['types'].find { |h1| h1['slot'] == 2 }['type']['name']
      else
        typetwo = ''
      end
      pokemon = {
        name: response['name'],
        type1: typeone,
        type2: typetwo,
        hp: h['stats'].find { |h1| h1['stat']['name'] == 'hp' }['base_stat'],
        attack: h['stats'].find { |h1| h1['stat']['name'] == 'attack' }['base_stat'],
        defense: h['stats'].find { |h1| h1['stat']['name'] == 'defense' }['base_stat'],
        spatk: h['stats'].find { |h1| h1['stat']['name'] == 'special-attack' }['base_stat'],
        spdef: h['stats'].find { |h1| h1['stat']['name'] == 'special-defense' }['base_stat'],
        speed: h['stats'].find { |h1| h1['stat']['name'] == 'speed' }['base_stat']
      }
      Pokemon.create!(pokemon) unless Pokemon.exists?(pokemon)
    end
  end
id += 1
end
```

I have to call the transaction under the until loop because there doesn't seem to be a way to get the details of more than 1 pokemon from the API, and I have the until loop set to 3 just for testing purposes.

**Comment by sjf125** [comment]
To clarify, running `rake db:seed` completes, but doesn't seem to actually make any new rows, at least on localhost:3000

**Comment by sjf125** [comment]
With more testing, it doesn't seem to be entering the `do` block after response.body

**Comment by RDegnen** [comment]
If you go into the rails console, do the pokemon exist in there?

**Comment by sjf125** [comment]
Got it working - I had defined `h` in my model, but didn't transfer it over to the seeds file.
