### ISSUE TITLE
Having trouble rendering ratings below topics

### ISSUE THREAD

**Issue by rdelvallej32** [ga-wdi-boston/capstone-project#158]
Hi, 

I'm having trouble rendering the rating below a topic. I followed the example that we did in class, but its only displaying the topic. I'm not getting an error, so I'm unsure if my binding is off?

Topic Model:

``` js

import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { hasMany } from 'ember-data/relationships';

export default Model.extend({
  content: attr('string'),
  category: attr('string'),
  nyt_article: attr('boolean'),
  ratings: hasMany('rating', {
    inverse: 'topicid'
  })
});

```

Topics Template:

``` hbs

<h2>Topics</h2>

{{#each model as |topic|}}
  {{topic-rating/card topic=topic}}
{{/each}}

```

Topic-Rating Card Component Template:

``` hbs

{{#link-to 'topic' topic}}
  <h2>{{topic.content}}</h2>
{{/link-to}}

```

Topic Template:

``` hbs

{{topic-rating topic=model createRating="createRating"}}

```

Topic-Rating Component Template:

``` hbs

<h2>{{topic.content}}</h2>

{{topic-rating/rating rating=rating}}

{{#link-to 'topics'}}Back to Topics{{/link-to}}


```

Topic-Rating Rating Component Template:

``` hbs

<ul>
{{#each topic.ratings as |rating|}}
  <li>{{rating.id}}</li>
  {{/each}}
</ul>

<button class="btn btn-xs btn-danger"
        {{action "deleteRating"}}>
    Delete
</button>

```

**Comment by rdelvallej32** [comment]
Also, I'm getting an Ember Promise Object when I check for the topic id and user id associated with the rating:

Topic Id:DS.PromiseObject:ember622
User Id:DS.PromiseObject:ember623
Rating:4

**Comment by RealWeeks** [comment]
looks like your doing rating as rating in your topic rating then topic.rating as rating, if I have the flow correct.

**Comment by rdelvallej32** [comment]
Yes? I'm using topic.ratings in order to access the ratings that are associate to topics?

**Comment by rdelvallej32** [comment]
Should I forget about ratings at this point and just change the purpose of my app to have users create topics?

**Comment by RealWeeks** [comment]
Keep at this, I'm questing your bindings, more specifically if you are binding the right thing.

**Comment by rdelvallej32** [comment]
So i reformatted it, and I'm still unsure where the binding is failing, closing this issue because I decided to not use Ember. Will work on Ember after presentations.
