### ISSUE TITLE
Many-to-many Through Relationships in Ember

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/capstone-project#159]
I have Users and Trips, and am associating them through Invitations on my rails back-end. When I try to build this relationship into Ember though it yells at me.

Specifically, I get this error: 

```
ember.debug.js:32096 TypeError: Cannot read property 'some' of undefined
```

I've created an Invitation model in Ember, which belongsTo the Trip model. The Trip model hasMany Invitations. My Trip objects in the store have a HasMany invitations property which I can inspect, but it doesn't seem to contain the data that is being sent back by my trips serializer on the back end.

The error arises if and only if I include the line `invitations: hasMany('invitation')` in my Trip model.js. If I remove that line, the app works but I get a warning that there is no hasMany property set for invitations (and of course I can't get any info about invitations).

I need to use a has-many-through relationship rather than just a many-to-many because I want to store information about the invitation itself (i.e. status (going, not going, maybe)).

If someone (@jrhorn424 ?) with better Ember chops than me wanted to give me a quick walkthrough on many-to-many relationships in Ember, that might go a long way.

Any help much appreciated. Thanks!

**Comment by RealWeeks** [comment]
is this related to Roberto's issue: https://github.com/ga-wdi-boston/capstone-project/issues/152

**Comment by soynog** [comment]
Seems related but I've put in all possible explicit inverses and it doesn't seem to have helped.

Also of note, the error goes away if there are no Trips in the database--it's only when trying to load a Trip object that it has problems.

Here are my models:

User:

```
import DS from 'ember-data';
import { hasMany } from 'ember-data/relationships';

export default DS.Model.extend({
  email: DS.attr('string'),
  invitations: hasMany('invitation', {
    inverse: 'user',
    async: true
  }),
  trips: hasMany('trip', {
    inverse: 'users',
    async: true
  })
});
```

Trip:

```
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { belongsTo } from 'ember-data/relationships';
import { hasMany } from 'ember-data/relationships';

export default Model.extend({
  name: attr('string'),
  description: attr('string'),
  startDate: attr('date'),
  endDate: attr('date'),
  location: attr('string'),
  // user: belongsTo('user', {
  //   inverse: 'trips'
  // }),
  users: hasMany('user', {
    inverse: 'trips',
    async: true
  }),
  invitations: hasMany('invitation', {
    inverse: 'trip',
    async: true
  }),
});
```

Invitation:

```
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { belongsTo } from 'ember-data/relationships';

export default Model.extend({
  user: belongsTo('user', {
    inverse: 'invitations',
    async: true
  }),
  trip: belongsTo('trip', {
    inverse: 'invitations',
    async: true
  }),
  status: attr('string'),
});
```

**Comment by soynog** [comment]
Seems like one possibility is that it's an Ember serializer issue.

[This article](http://stackoverflow.com/questions/25213719/emberjs-cannot-read-property-typekey-of-undefined) suggests writing a custom serializer--we just seem to have one serializer for the whole app though--how do I define a separate serializer for an object?

**Comment by soynog** [comment]
Oh and also I get this error:
`ember.debug.js:32096 Error: Assertion Failed: You need to pass a model name to the store's modelFor method`
When I make a post request, even though the request goes through successfully.

**Comment by RealWeeks** [comment]
@jrhorn424 any insight into this?

**Comment by soynog** [comment]
I'll be working on this issue starting now and I'd love some support. I'll post updates/clues as I find them.

**Comment by soynog** [comment]
So I've started back with a clean slate to try and isolate the problem. The error still occurs when I add in the a hasMany() relationship in my trip model.js file.

When I attempt to retrieve all trips (/trips), I get this error:

```
ember.debug.js:32096TypeError: Cannot read property 'some' of undefined
```

When trying to view a specific trip (/trips/:id) I get the above error, and ALSO:

```
ember.debug.js:32096Error: Assertion Failed: You need to pass a model name to the store's modelFor method
```

If I specify the trips' list of invitations using a non-transforming attr() call, `invitations: attr()`, the error goes away and I can retrieve data about the trip's invitations from the API.

Furthermore, this issue appears to be occurring ONLY for my trip model. If I specify a hasMany/belongsTo relationship between trips and users, it doesn't break.

**Comment by soynog** [comment]
I've been able to create an invitations route as well. I can view the list of invitations as long as I don't include the belongsTo trips relationship in the invitation model. If I do, it breaks in the standard way.

**Comment by RealWeeks** [comment]
I'm trying to see why trip is the only one that doesn't work here and I'm looking over docs on this.

**Comment by soynog** [comment]
Antony suggests that the issue may be that my API is sending back embedded data rather than just IDs. I'll try changing my serializer to send back just ids and see if that helps.

**Comment by soynog** [comment]
It's definitely a serializer issue on the back-end. I set my API to send back just the invitation IDs and it seems to have solved most of the problems. I'm going to leave this issue open for a bit as I'm still working things out and may have follow-up questions.

Thanks @gaand !

**Comment by soynog** [comment]
I'm going to go ahead and close this one out. Looking at the listr-api serializers was very helper, and I've mostly got it working like I want it to now.
