### ISSUE TITLE
rails c gives me the following error when I try to create entry

### ISSUE THREAD

**Issue by eshimel** [ga-wdi-boston/capstone-project#16]
I'm getting this error when I try to add an entry with pry:
NoMethodError: undefined method `password_digest' for #<Profile:0x007fe6c8caafb0>
from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-4.2.4/lib/active_model/attribute_methods.rb:433:in`method_missing'

I did try to look it up already.
Am I missing a gem that is not apparent to me?  If not that, what is my issue?

Thanks!

**Comment by gaand** [comment]
What command did you execute that generated that error?

**Comment by eshimel** [comment]
u.save

**Comment by gaand** [comment]
What did you pass to `u = User.new`, e.g., before calling `u.save`?

**Comment by eshimel** [comment]
pry(main)> u.username, u.studio, u.website, u.user_id, u.created_at, u.updated_at = "Lina", "Vernon St", "lin.com", 3, DateTime.now, DateTime.now

**Comment by eshimel** [comment]
this is what was printed after u = User.new
[15] pry(main)> u = Profile.new                                                 => #<Profile:0x007fe6c88994d0
 id: nil,
 username: nil,
 studio: nil,
 website: nil,
 user_id: nil,
 created_at: nil,
 updated_at: nil>
