### ISSUE TITLE
Storing 3rd party api key in back end

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/capstone-project#160]
I have a key for the Petfinder API that I have stored as `PETFINDER_KEY: blahblahblah` in secrets.yml.  I tried two ways of accessing this key when making the get request to Petfinder:

```
 KEY=Rails.application.secrets.PETFINDER_KEY;
```

```
KEY=ENV['PETFINDER_KEY'];
```

and neither work.  I'm getting that either 'ENV' or 'Rails' is not defined.
I'm wondering if I need to require/export something?

**Comment by RDegnen** [comment]
have you tried using the dotenv gem instead? I think that would work better for keeping secrets. I believe if you have secrets in secrets.yml you have to manually load them somewhere in your rails app.

**Comment by susandaiute** [comment]
Never heard of it, but I'll give it a shot.  Thanks!

**Comment by RealWeeks** [comment]
Hey Susan, have you checked previous lessons and guides. There should be a guide out there in one of the repos or your notes that covers this.  (hint: search guide in the GA repos)

**Comment by susandaiute** [comment]
I installed the figaro gem, which is like dotenv, but was built with heroku deployment in mind.  As far as I know, I'm doing it right, but ENV is still coming back undefined.
[figaro github](https://github.com/laserlemon/figaro)

Front End: 

```
KEY=ENV['PETFINDER_KEY'];
```

Back End:

```
PETFINDER_KEY: blahblahblah
```

It's almost like the front and back ends aren't communicating.

**Comment by gaand** [comment]
What files contain those lines?

**Comment by susandaiute** [comment]
```
KEY=ENV['PETFINDER_KEY'];
```

assets/scripts/petfinderAPI.js in the front end 

```
PETFINDER_KEY: blahblahblah
```

and config/application.yml in the back end

**Comment by gaand** [comment]
Clients and APIs don't share an environment, so this may be the root of your problem. 

Is `config/application.yml` stored in git?  Secrets should be in your repository.

**Comment by susandaiute** [comment]
config/application.yml is in .gitignore

**Comment by laurenfazah** [comment]
I can hop in and try to work through this with you.

**Comment by laurenfazah** [comment]
@gaand I'm blanking. What would you say is the best way for Susan to retrieve the key client-side?

**Comment by gaand** [comment]
Is it necessary to have the key in the client, or can the server invoke the pet finder API and return the results?

If the key does have to be used on the client, you can create a route to return it (more secure if only for logged in users).

**Comment by susandaiute** [comment]
Solution: We built a controller and corresponding route for Pets.  Then we put the Ajax call to the Petfinder API in an index method in the controller.  This is all working with the Figaro gem.  

```
class PetsController < ApplicationController
  require 'net/http'
  KEY = ENV['PETFINDER_KEY'];
  def index
    url = URI.parse('http://api.petfinder.com/pet.find?key=' + KEY + '&animal=dog&breed=Labrador+Retriever&output=full&location=02184&format=json&distance=100')
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) do |http|
      http.request(req)
    end
    render json: res.body
  end
end
```
