### ISSUE TITLE
Ember - Route Issue

### ISSUE THREAD

**Issue by natdjerf** [ga-wdi-boston/capstone-project#162]
I'm getting undefined & and Uncaught TypeError: Cannot read property 'findRecord' of undefined when trying to submit a patch request with a reservation id. 

I see this has been a popular issue, but I think this is related to data binding, as this reservation is a user owned model with no dependents, as opposed to relationship models, which is most of the issues I am seeing. I have been able to show & delete individual reservations with an id, which are rendered on the same template, but when I link to another component, I see to lose the individual reservation id. 

Delete/ view template:

``` hbs
<button {{action "deleteReservation"}} class="btn btn-danger">Cancel This Reservation</button>

{{#link-to 'update' reservation}}
<button class="btn btn-success">Modify This Reservation</button>s
{{/link-to}}
```

and the update template:

``` hbs
{{reservation-booking/reservation-modify reservation=reservation submit="modifyReservation"}}
```

I thought this was passing the reservation data. I realize on the show/display template, the reservation coming directly from the reservation route, which is passing model and therefore the ID. I assume I don't need the update route, but I'm not sure how I should be rendering this data.

**Comment by RealWeeks** [comment]
From the top down what does your binding look like?

**Comment by natdjerf** [comment]
Closing this... I removed the update route, which was unnecessary, and was able to access through the reservation model.

Sorry about that!

**Comment by laurenfazah** [comment]
Sorry to nitpick, but could you actually close @natdjerf? Thanks! :)
