### ISSUE TITLE
trouble assigning

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/capstone-project#164]
I'm trying to get the selected options in this dropdown assigned to a variable with jQuery

``` html
                   <form id="symptom-drop">
                   <select id="symptom-select">
                       <option value="" disabled="disabled" selected="selected">Please select a name</option>
                       <option value="1">I have Imposter Syndrome</option>
                       <option value="2">I'm having an anxiety attack</option>
                       <option value="3">I don't want to be a developer anymore</option>
                       <option value="4">I hate networking</option>
                       <option value="5">My code is breaking and I don't know why</option>
                       <option value="6">I just want a Sleepy-Roberto pep talk</option>
                   </select>
                   <button class="btn btn-success"type="submit">Get Solutions</button>
                  </form>
```

I originally tried this and the console log DOES log the correct text 

``` js
$('#symptom-drop').on('submit', function (event) {
    debugger;
    event.preventDefault();
    let title = $('#symptom-select option:selected').text();
    console.log(title);
  });
```

``` js
 $('.btn-symp-sel').on('click', function (event) {
    debugger;
    event.preventDefault();
    let title = $('#symptom-select :selected').text();
    console.log(title);
  });
```

The only thing I can think of is it being some sort of circular reference issue? I've had weird magic issues with the index.js of the js template in previous projects, so I'll try just moving this click handler around and see if works? Either way i'd like to know why that has been happening.

**Comment by RDegnen** [comment]
if it correctly console.log's than it is assigned. Is it coming back as undefined somewhere?

**Comment by BenGitsCode** [comment]
It's coming back as undefined in the down when i call title and in the debugger, as it's being assigned or logged, mousing over title says undefined.

**Comment by RDegnen** [comment]
well it would be undefined if your calling it when the debugger is above when you declare the variable. You have to step down in the debugger to where you define the variable and then it will be defined

**Comment by BenGitsCode** [comment]
Yeah I know, I've done that but that's the weird thing about it. When I step down in the debugger it will log title as the correct value, but calling title afterwards returns undefined.

**Comment by RDegnen** [comment]
hmm fishy.. I'll assign myself

**Comment by BenGitsCode** [comment]
Yeah maybe there's a way around this, but I'm scratching my head on this. I'm in 1A.

**Comment by jrhorn424** [comment]
What was the resolution for this?

**Comment by BenGitsCode** [comment]
Sorry. It turns out I was successfully assigning the data, wasn't wasn't freezing the runtime with a debugger when I tried to call it's definition in the console. (ಠ_ಠ)
