### ISSUE TITLE
3rd party API

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/capstone-project#165]
I want to incorporate the Google Font API to show images of different fonts but I'm not sure if that is possible. Looking for some help on how to tell if that's possible.

**Comment by laurenfazah** [comment]
So show a preview of fonts you could get from Google Fonts?

**Comment by Jcornmanhomonoff** [comment]
Yeah. I want to incorporate a few more APIs and I'm not entirely sure how to tell if they will return images.

**Comment by Jcornmanhomonoff** [comment]
Essentially I would like to show a preview for each individual font

**Comment by laurenfazah** [comment]
Looks very doable: https://developers.google.com/fonts/docs/getting_started#enabling_font_effects_beta

I'll self-assign to help get you started.

**Comment by Jcornmanhomonoff** [comment]
Decided to stick with Dribbble API. Worked thought getting ID of image and some slight pagination issues.
