### ISSUE TITLE
Bootstrap Glyphicons

### ISSUE THREAD

**Issue by natdjerf** [ga-wdi-boston/capstone-project#166]
I've received the below error when trying to import glyphicons:

Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:4200/fonts/bootstrap/glyphicons-halflings-regular.woff

I added the below to the ember-cli-build.js file:

``` js
  app.import('bower_components/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff');
```

Which I believe is the correct path, and it's building successfully, but when I use gylphicons in a template I have get the console error. Any idea?

Used this but updated the filepaths:
http://miguelcamba.com/blog/2014/08/10/import-bootstrap-glyphicons-in-ember-cli/

**Comment by laurenfazah** [comment]
Could you post your code that's loading glyphicons into your template and also the console error that's causing?

**Comment by jrhorn424** [comment]
I need to investigate since there may have been changes to the structure of imports since that post was published.

**Comment by natdjerf** [comment]
Just this:

``` js
<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
```

It's now displaying a variation of a pencil, but not the bootstrap one, and this is the error:
fonts/bootstrap/glyphicons-halflings-regular.woff:1 GET http://localhost:4200/fonts/bootstrap/glyphicons-halflings-regular.woff 
2016-06-07 13:44:27.937 fonts/bootstrap/glyphicons-halflings-regular.ttf:1 GET http://localhost:4200/fonts/bootstrap/glyphicons-halflings-regular.ttf 

Along with an ember debug error object

**Comment by gaand** [comment]
``` js
  app.import('bower_components/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2', { destDir: 'fonts/bootstrap' });
  app.import('bower_components/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff', { destDir: 'fonts/bootstrap' });
```

**Comment by gaand** [comment]
A careful reading of the error led me to this solution.

**Comment by natdjerf** [comment]
Ah, I don't think I added that part back in after revising the filepath. Thanks!
