### ISSUE TITLE
Adding a specific node_module for git NOT to ignore

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/capstone-project#169]
My .gitignore file has `/node_modules` as one of the things to ignore, however I have `ember install`'d [Ember Charts](https://github.com/Addepar/ember-charts), in which I did some customizing of the code there to display my stats charts the way I like.  However, the changes are being ignored by git.  Is there a way to not ignore specific files in `/node_modules`, or do I have to find a way to individually list each node module I have (there are many)?

**Comment by sjf125** [comment]
I've also been getting this deprecation warning since installing Ember Charts, not sure if it's serious or not, but everything works:

```
DEPRECATION: A property of <ga-wdi-boston.ember-auth@view:-outlet::ember513> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation. [deprecation id: ember-views.dispatching-modify-property]
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16458:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16366:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16458:7)
        at invoke (http://localhost:4200/assets/vendor.js:16474:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16427:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:26466:37)
        at exports.default._emberMetalMixin.Mixin.create._Mixin$create.scheduleRevalidate (http://localhost:4200/assets/vendor.js:53723:22)
        at http://localhost:4200/assets/vendor.js:23979:32
        at Object.BasicStream.notifySubscribers (http://localhost:4200/assets/vendor.js:32374:11)
```

**Comment by gaand** [comment]
Are you successfully using it?  The necessary parts should end up in dist when you serve or build.

**Comment by sjf125** [comment]
Yeah?  I'm just nervous because I made changes to coloring and styling in the files in node_modules, and they don't show up in git status.  So those saves will be reflected when I deploy?

**Comment by gaand** [comment]
The deprecation warning means that the people who wrote ember charts are doing something tht is no longer officially supported (and will eventually stop working).

**Comment by gaand** [comment]
You should change anything in node_modules.  Those changes may not be saved.

Depending on the customization you need, ember charts may have an alternate mechanism (or not - I haven't looked at in detail).

**Comment by sjf125** [comment]
OK, let's talk tomorrow - I'll keep the issue open

**Comment by sjf125** [comment]
Ember-Charts doesn't do enough, so I'll have to refactor with D3 exclusively
