### ISSUE TITLE
Want to make sure I have my data associations right in Rails

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/capstone-project#17]
I have three models
User (has_many :pets)

Pet (belongs_to :user)
      (has_many :documents)

Document (belongs_to :pet)

I want to the User to be able to delete and upload the Document but make sure they are still only associated and brought up when I am referencing the Pet that it is attached to.  I looked into the has_many_through and think that's the right option.  Just wanted to confirm.

**Comment by jrhorn424** [comment]
How would you use HMT?

**Comment by jcmeyer10** [comment]
Something like a User would have many Documents through Pets so that a User
could upload Documents while still maintaining its connection to Pet.  Also
finding that Document would be easier and could be done with a
User.document instead of User.pets.documents.  That's how I understand the
documentation at least.

**Comment by jrhorn424** [comment]
That's not a HMT. A HMT would imply that a Document has many Users through Pets. This relationship makes the most sense:

> User (has_many :pets)
> 
> Pet (belongs_to :user)
> (has_many :documents)
> 
> Document (belongs_to :pet)

**Comment by jrhorn424** [comment]
@jcmeyer10 Is this resolved for now?

**Comment by jcmeyer10** [comment]
Sorry for delay, that's the relationship I have right now.  Thanks for the
clarification!  Will close.

On Tue, Dec 15, 2015 at 9:55 AM, Jeffrey Horn notifications@github.com
wrote:

> @jcmeyer10 https://github.com/jcmeyer10 Is this resolved for now?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-wdi-boston/portfolio-capstone-project/issues/17#issuecomment-164787868
> .

## 

Regards,
Jeff Meyer

857-206-3572
