### ISSUE TITLE
require file

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/capstone-project#170]
Getting this error:
require is not defined

here's my jribbble JS file

``` js
'use strict'

const authApi = require('./auth/api');
// const app = require('./app-data.js');

$.jribbble.setToken('829e7b01d4f7bf4fae734bf7af259e228706a7f08abb66459fad663ed89e68db');
$.jribbble.shots({per_page: 100}).then(function(shots) {
  var html = [];

//for each shot on the page, give it a link and an image
  shots.forEach(function(shot) {
    html.push('<div class="shots--shot hovereffect" data-id="' + shot.id + '">');
    html.push('<a href="' + shot.html_url + '" target="_blank">');
    html.push('<img src="' + shot.images.normal + '">');
    html.push('<div class="overlay">');
    html.push('<h2>Effect 11</h2>');
    html.push('<p>')
    html.push('<a href="#" class="addFavorite">Add to favorites</a>')
    html.push('<p>')
    html.push('<a href="#">Dribbble</a>')
    // html.push('<i class="fa fa-twitter fa-facebook fa-instagram fa-dribbble">')
    html.push('</p></p></div></a></div>');
  });

  $('.shots').html(html.join(''));
});

//get id of image
$('.shots--shot').on('click', function(){
    let addFavoriteID = $(this).data('id');
    authApi.addFavorite(success, failure, addFavoriteID);
});
```

auth/api.js

``` js
'use strict';

const app = require('../app-data.js');


const signUp = (success, failure, data) => {
  console.log("Sign up request queued");
  $.ajax({
    method : 'POST',
      url : app.api + '/sign-up',
    data
  }).done(success).fail(failure);
};

const signIn = (success, failure, data) => {
  console.log("Sign in request queued");
  $.ajax({
    method : 'POST',
    url : app.api + '/sign-in',
    data
  }).done(success).fail(failure);
};

const signOut = (success, failure) => {
  console.log("Sign out request queued");
  $.ajax({
    method: 'DELETE',
    url: app.api + '/sign-out/' + app.id,
    headers: {
      Authorization: 'Token token=' + app.token,
    },
  }).done(success)
  .fail(failure);
};

const changePW = (success, failure, data) => {
  console.log("Change password request queued");
  $.ajax({
    method: 'PATCH',
    url: app.api + '/change-password/' + app.id,
    data,
    headers: {
      Authorization: 'Token token=' + app.token,
    },
  }).done(success)
  .fail(failure);
};

const addFavorite = (success, failure, data) => {
  // debugger;
  $.ajax({
    method:'POST',
    url: app.api + 'favorites',
    data,
  })
  .done(success)
  .fail(failure);
};


module.exports = {
  signUp,
  signIn,
  signOut,
  changePW,
  addFavorite,
};
```

**Comment by RealWeeks** [comment]
You were working with @laurenfazah earlier what did you change before you got this error?

**Comment by gaand** [comment]
Is that the complete error message?

**Comment by Jcornmanhomonoff** [comment]
Yes, that is the entire message. And I didn't change anything. We worked on storing an image to my favorites but I haven't changed anything. We ran out of time. We were talking about how maybe it's because I'm using a jQuery library that may not comply with the JS template

**Comment by RealWeeks** [comment]
what library are you using?

**Comment by Jcornmanhomonoff** [comment]
jribbble for Dribbble API

**Comment by RealWeeks** [comment]
jrdribble has a dependency on jQuery, so I don't think it's messing with it too much.  How did you install it into your project.  I see the instructions point you toward using bower.

**Comment by Jcornmanhomonoff** [comment]
bower install --save jribbble

**Comment by gaand** [comment]
Did you use js-template as the starting point for you client?  I don't think js-template integrates with bower by default.

**Comment by Jcornmanhomonoff** [comment]
I did. How do I fix that?

**Comment by RealWeeks** [comment]
@gaand looks like they have an npack (that's what the cool kids call it now) https://www.npmjs.com/package/jribbble but the instructions only say bower, but should be good with an npm install.

**Comment by RealWeeks** [comment]
@Jcornmanhomonoff I'd try uninstalling the bower package then try installing it with npm, if that doesnt work download the min and put in in the lib directory and require that file.

**Comment by Jcornmanhomonoff** [comment]
I don't know how to do that and I'm also scared to.....

**Comment by RealWeeks** [comment]
``` bash
bower uninstall --save jribbble
npm install jribbble --save
```

**Comment by RealWeeks** [comment]
I don't even think the first step is necessary but why not

**Comment by Jcornmanhomonoff** [comment]
What do you mean put it in the lib directory? And is that going to mess up all of my paths?

**Comment by Jcornmanhomonoff** [comment]
I have an entirely working project until I tried to store something. I would like someone to assign themselves to me first thing in the morning to help me with this so I can get moving please. I do not want to mess up my entire project.

**Comment by RealWeeks** [comment]
Remind me in the morning

**Comment by Jcornmanhomonoff** [comment]
👍

**Comment by RealWeeks** [comment]
@laurenfazah when you see this, any insight you have from working with Jessica today would be helpful.

**Comment by Jcornmanhomonoff** [comment]
Uninstalled bower, installed with npm. Required files in proper places.
