### ISSUE TITLE
Computed property

### ISSUE THREAD

**Issue by natdjerf** [ga-wdi-boston/capstone-project#172]
Hi, 

I'm having trouble finding the where to include a computed property. The property, total cost, is a calculation of user input fields when creating a reservation. I think it's an async issue- because it's calculated from user input, it loads initially as NaN. I used this in a helper and it calculates dynamically based on user input, but for some reason I can't access the variable after it's been calculated. 

When I tried to make the create a promise chain and including the test computed as a key, but get an error on the Ember.set, and as it's set up currently, I get a NaN error or  'Computed Object' on console log. 

I was under the impression this should not be in the model, and I was unsuccessful when storing it there as well, which is why i moved it to the component. Any idea?

``` js
export default Ember.Component.extend({
  form: {},

  test: Ember.computed('permit_quantity', 'lodging_quantity', 'permit_start_date', 'permit_end_date', function() {
    let date1 = new Date(this.get('permit_start_date'));
    let date2 = new Date(this.get('permit_end_date'));
    let numPermits = Math.abs(this.get('permit_quantity'));
    let numLodging = Math.abs(this.get('lodging_quantity'));

    let timeDiff = Math.abs(date2.getTime() - date1.getTime());
    let diffDays = Math.ceil(timeDiff / (1000 * 3600 * 24));

    let permitCost = (diffDays + 1) * numPermits * 15;
    let lodgingCost = 0;
    if (numLodging !== 0) {
      lodgingCost = (diffDays * numLodging * 35);
    }

    let calcualedTotalCost = permitCost + lodgingCost;

    return calcualedTotalCost;
  }),

  actions: {
    submit(reservation) {
      Ember.set(reservation,'reservation', this.get('form'));
      reservation.totalCost = (this.get('test'));
      this.sendAction('submit', this.get('form'));
```

**Comment by laurenfazah** [comment]
Few questions- which bits are user input? 
Where are `'permit_quantity', 'lodging_quantity', 'permit_start_date', 'permit_end_date'` coming from?
Have you debugged line by line to see what is null and what is not? Starting small with a computed value then building it out to this larger, multi-line computation? There are several variable declarations within the `test` computation, so there is a lot of room for potential error.

**Comment by gaand** [comment]
Did you start with this?  https://guides.emberjs.com/v2.5.0/object-model/computed-properties/

**Comment by natdjerf** [comment]
AH. Yes, I did use that. I initially used this in a helper to display the total cost, but realized I should be calculating it inside the controller, and didn't rename the both the input and the setters to match the form fields. It is setting the value correctly now, but it's not getting sent to the database.

**Comment by jrhorn424** [comment]
Lines like this:

``` js
    let date1 = new Date(this.get('permit_start_date'));
```

indicate that `permit_start_date` should be a property defined on `this`. `this` is the component. How do I know?

``` js
export default Ember.Component.extend({
// ----------------------^
  test: Ember.computed('permit_quantity', 'lodging_quantity', 'permit_start_date', 'permit_end_date', function() {
    let date1 = new Date(this.get('permit_start_date'));
// ...
```

How do you get `permit_start_date` bound to the component? By binding it in the rendering template. If instead you've done a binding like this: `{{blah-component reservation=reservation}}`, then you need:

``` diff
-    let date1 = new Date(this.get('permit_start_date'));
+    let date1 = new Date(this.get('reservation.permit_start_date'));
```

Can you elaborate on what `permit_start_date` (or another property you're using) is defined?

**Comment by natdjerf** [comment]
I'm not sure I fully understand. The way I have it now is:

``` js
  computedTotal: Ember.computed('form.permit_quantity', 'form.lodging_quantity', 'form.permit_start_date', 'form.permit_end_date', function() {
    let date1 = new Date(this.get('form.permit_start_date'));
    let date2 = new Date(this.get('form.permit_end_date'));
    let numPermits = Math.abs(this.get('form.permit_quantity'));
    let numLodging = Math.abs(this.get('form.lodging_quantity'));
```

where form.permit_start_date is the value of the form field on the template:

``` hbs
  {{bootstrap-datepicker autoclose=true date=mydate todayHighlight=true valueFormat='YYYY-MM-DD' placeholder="Permit Start Date" class="input-group form-control" value=form.permit_start_date}} 
```

When I console the data when it's sent to the route, it still shows the right value, so I think it's being bound from the component to route

**Comment by jrhorn424** [comment]
That looks correct. I'll have a look.

**Comment by natdjerf** [comment]
Update: this is working now, but it's a relatively janky solution, and I'll have to revisit it later:

``` js
export default Ember.Component.extend({
  reservation: {
    totalCost: Ember.computed('permitQuantity', 'lodgingQuantity', 'permitStartDate', 'permitEndDate', function() {
      let numPermits = Math.abs(Ember.get(this, 'permitQuantity'));
      let numLodging = Math.abs(Ember.get(this, 'lodgingQuantity'));
      let date1 = new Date(Ember.get(this, 'permitStartDate'));
      let date2 = new Date(Ember.get(this, 'permitEndDate'));

      let timeDiff = Math.abs(date2.getTime() - date1.getTime());
      let diffDays = Math.ceil(timeDiff / (1000 * 3600 * 24));

      let permitCost = (diffDays + 1) * numPermits * 15;
      let lodgingCost = 0;
      if (numLodging !== 0) {
        lodgingCost = (diffDays * numLodging * 35);
      }

      let calcualedTotalCost = (permitCost + lodgingCost);

      return calcualedTotalCost;
    }),
  },



  actions: {
    submit(reservation) {
      Ember.set(reservation, 'totalCost', this.get('reservation.totalCost'));
      console.log(this.get('reservation.totalCost'));
      this.sendAction('submit', reservation);
      console.log('New reservation:', reservation);
    },
  },
});
```

**Comment by natdjerf** [comment]
@gaand - Having a similar/strange problem with the same PATCH request on this. Would you have some time to help take a look this morning?

**Comment by gaand** [comment]
Let's see if we can find more janky.

**Comment by jrhorn424** [comment]
Any update here? I'm curious.

**Comment by gaand** [comment]
Hacks galore?

**Comment by jrhorn424** [comment]
It isn't a hack.

<img width="986" alt="slack" src="https://cloud.githubusercontent.com/assets/388761/15944728/f6c9ac52-2e5c-11e6-8abb-13e88e485990.png">

It's the way you do it.

I recall now that computed properties are like virtuals. I believe they're intended to be ephemeral. This is the sort of calculation that would be done on the API _and_ the client, with the computed property only serving as an artefact for UI.

Don't trust data from the client. **Especially when it has $ in front of it.**

**Comment by natdjerf** [comment]
After allllllllll that! Thanks for researching, Jeff. 
FWIW: I computed the total cost on the reservation model on back end, used the helper for displaying on front end

**Comment by jrhorn424** [comment]
> FWIW: I computed the total cost on the reservation model on back end, used the helper for displaying on front end

That's a win.
