### ISSUE TITLE
Filtering data (ember)

### ISSUE THREAD

**Issue by olivia-leach** [ga-wdi-boston/capstone-project#175]
I have set up a nested route situation, a la this tutorial: http://emberigniter.com/load-multiple-models-single-route/

So I have a building/sensors/route.js which contains:

``` js
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    console.log('test');
    const building = this.modelFor('building');
    return this.store.query('sensor', { filter: { building_id: building.get('id') }});
  }
});
```

When I go to localhost:4200/buildings/26/sensors, I want to load building 26's data (that's fine) and the sensor data for only that particular building (this part is not working). Right now when the page loads, I am getting ALL of the sensor data from the API, which is bad news because that also loads the hasMany relationship beneath that (which I'm trying to access, but only need a subset of)--which is ~21k objects. :(

I followed the format here https://guides.emberjs.com/v2.5.0/models/finding-records/ for querying for multiple records.

It seems like the filter request is going through correctly. In my console I see:

```
XHR finished loading: GET "http://localhost:4200/sensors?filter%5Bbuilding_id%5D=26".
```

And sensors definitely have a building_id attribute.

The page takes forever to render when all the data is loaded like this, so I definitely need to filter it. And will probably filter it more after I figure out this first part.

**Comment by laurenfazah** [comment]
What API are you using? Do they have endpoint documentation for filtering? The `%5` characters in the GET request look a little funky, but could be fine. Just want to compare to what they're expecting. It could be nullifying the request.

**Comment by olivia-leach** [comment]
It's my own Rails API that I seeded with data

**Comment by olivia-leach** [comment]
Do I need to set up the backend to receive filter requests?

**Comment by laurenfazah** [comment]
Ohh I see. Yes, I believe you'd have to set that up. Ember's filter builds the API query for you, but if your API isn't set to receive that, you'd run into issues. You can test that endpoint it's building with a cURL request...I have a feeling that's the issue.

**Comment by olivia-leach** [comment]
Hmmm okay. Might have to come up with a work-around since I probably won't have time to look into that.

**Comment by laurenfazah** [comment]
You could work to filter all data client-side, but that probably won't help with the lagtime you're experiencing.

**Comment by jrhorn424** [comment]
@olivia-leach You could use query params to do the filtering, and implement a simple case-insensitive search using SQL's `ILIKE`.

**Comment by gaand** [comment]
Pedantic: PostgreSQL's `ILIKE` :-).

Depending on the data, `LIKE` might suffice (`ILIKE` is PostgreSQL's case insensitive like operator).

**Comment by olivia-leach** [comment]
Thanks for the advice! I will try to tackle this next week when I'm making v2 of this project.
