### ISSUE TITLE
Deleting event returns 200 from server but I never hit my success/failure handler

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/capstone-project#176]
I can successfully delete an event, as indicated by a 200 from the server and by refreshing the page seeing the event has been removed, but I don't ever hit my success handler...

Here where I invoke the deleteEvent function:

```
 'use strict';

 const app = require('../app-data.js');
 const authApi = require('../auth/api.js');
 const authUi = require('../auth/ui.js')
 const appApi = require('./api.js');
 const appUi = require('./ui.js');
 const findEventById = require('../../lib/pull-event-from-array-by-id.js');

 const addHandlers = () => {
   $('.remove-event-btn').on('click', function(event){
     event.preventDefault();
     let eventToRemove = findEventById(app.user.events, this.dataset.eventid);
     appApi.removeEvent(appUi.deleteEventSuccess, appUi.deleteEventFailure, eventToRemove._id);
    });
  };

 };

 module.exports = {
 addHandlers,
 };

```

and these are my success/failure conditions:

```
'use strict';

const app = require('../app-data.js');
const authApi = require('../auth/api.js');
const authUi = require('../auth/ui.js')
const appApi = require('./api.js');
const loadSearchResults = require('../template/search-results.handlebars');
const templateHandlers = require('./template-handlers.js');
const displayUserEvents = require('../template/user-events.handlebars');

const deleteEventSuccess = (data) => {
  console.log(data, 'success event deleted');
  let token = app.user.token;
  console.log(token);
  // $('.user-events-div').html('');
  // $('.user-events-div').append(displayUserEvents({
  //   events: app.user.events
  // }));
  // templateHandlers.addHandlers();
};

const deleteEventFailure = (data) => {
  console.log('failure event not added')
  let token = app.user.token;
  console.log(token);
};

module.exports = {
  deleteEventFailure,
  deleteEventSuccess,
};
```

I'm not sure if it has to do with how I'm requiring files? I am not getting any errors. Just never hitting the success handler

**Comment by RDegnen** [comment]
Check to see if your deleteEventSuccess is defined in your click event

**Comment by louarnos** [comment]
I believe it is defined.

**Comment by louarnos** [comment]
When I console.log() in the .done() it shows up

**Comment by laurenfazah** [comment]
Can you post your `appApi.removeEvent()` function?

**Comment by louarnos** [comment]
```
const removeEvent = (success, failure, id) => {
  console.log('delete event queued');
  $.ajax({
    method : 'DELETE',
      url : app.api + '/events/' + id,
      headers: {
        Authorization: 'Token token=' + app.user.token,
      },
  }).done(success).fail(failure);
};
```

**Comment by louarnos** [comment]
I moved my success/failure handlers into another file and changed the required and it works fine... So I guess this issue is closed but I have no idea what was going wrong.

**Comment by laurenfazah** [comment]
I would think the issue probably lies somewhere in your file requirements. There's probably a circular dependency somewhere. I'd just parse through what's requiring what and make sure nothing's circular, because this could cause another issue down the road.

**Comment by louarnos** [comment]
@laurenfazah I had a feeling that was the case... I think this issue is rendering handlerbars templates in my UI. Is there any easy way to avoid this?

**Comment by laurenfazah** [comment]
I'd have to look into what you're doing more. Loading the template from the UI success function should be fine. You were saying the success functions weren't being hit at all before, right? Or was it hit and handlebars templates just weren't loading?

**Comment by louarnos** [comment]
They weren't being hit at all

**Comment by laurenfazah** [comment]
Yeah so I would think there was a circular dependency involving the UI file. I think loading your hbs templates there should be fine though.

**Comment by louarnos** [comment]
ok... I'll look into it.
