### ISSUE TITLE
Bootstrap accordions via handlebars issue 

### ISSUE THREAD

**Issue by philschoof** [ga-wdi-boston/capstone-project#177]
I'm pulling a list of definitions for a given word from an API. When the user selects the definition they want to add to their dictionary, a POST request is sent and the word and definition are added to the db. A GET request is then sent to get all of the users words, which are then loaded into bootstrap accordions via handlebars. 

It works great unless the word the user searched returns less than three definitions. The POST request works, and the GET request works. The word and definition are both loaded into the DOM successfully, however the bootstrap mechanism for opening and closing the accordion does not work. It works on words that return more than three definitions, but not words that returned less than three definitions. Which is really weird because by the time the words and definitions are passed to handlebars, they should be coming from the GET request anyway. More on this as it develops.

**Comment by laurenfazah** [comment]
Can you post your handlebars template with the accordion?

**Comment by gaand** [comment]
This might be an async timing issue.  < 3, too fast, > 3 slow enough to work?

**Comment by philschoof** [comment]
```

  {{#each words}}
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

  <div class="panel panel-default" }>
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href=".{{this.entry}}" aria-expanded="false" aria-controls=".{{this.entry}}">
          {{this.entry}}
        </a>
      </h4>
    </div>
    <div  class="panel-collapse collapse {{this.entry}}" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body " aria-expanded="false" >
        <p class="word-definition">{{this.definition}}</p>
        <button class="btn btn-info edit-word" data-id={{this.id}}>Edit</button><button class="btn btn-danger delete-word" data-id={{this.id}}>Delete</button>
      </div>
    </div>
  </div>
</div>


{{/each}}
```

**Comment by philschoof** [comment]
The number of definitions being returned was a coincidence - the problem was I was assigning the class names used for opening and closing the modals based on the searched word, so if the user searched "white space", the accordion would get the href and class name "white space" assigned, which obviously doesn't work. The solution was to use the word ID for the class and href instead. See below:

```
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  {{#each words}}
  <div class="panel panel-default" }>
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href=".{{this.id}}" aria-expanded="false" aria-controls=".{{this.entry}}">
          {{this.entry}}
        </a>
      </h4>
    </div>
    <div  class="panel-collapse collapse {{this.id}}" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body " aria-expanded="false" >
        <p class="word-definition">{{this.definition}}</p>
        <button class="btn btn-info edit-word" data-id={{this.id}}>Edit</button><button class="btn btn-danger delete-word" data-id={{this.id}}>Delete</button>
      </div>
    </div>
  </div>
  {{/each}}
</div>
```
