### ISSUE TITLE
Twitter OAuth, CORS issues

### ISSUE THREAD

**Issue by cuprous** [ga-wdi-boston/capstone-project#178]
**Front end**: HTML/CSS/JS

**Back end**: Rails
**Gem**: [omniauth-twitter](https://github.com/arunagw/omniauth-twitter)

Access http://localhost:3000/ (the Rails address) via Chrome correctly redirects to the Twitter OAuth authorization page. When making a JQuery Ajax request from http://localhost:8080 including authorization Token token= headers, receive the following:

**Error**: XMLHttpRequest cannot load http://localhost:3000/auth/twitter/. The request was redirected to 'https://api.twitter.com/oauth/authenticate?force_login=true&oauth_token=-1ZsmAAAAAAAvgjxAAABVTCg8lM', which is disallowed for cross-origin requests that require preflight.

Removing authorization headers from the aforementioned GET request results in a new error:

**Error**:  XMLHttpRequest cannot load https://api.twitter.com/oauth/authenticate?force_login=true&oauth_token=nb8j_wAAAAAAvgjxAAABVTCsNMk. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

**JS API function**

``` js
const addTwitterAccount = function() {
  console.log('Start twitter account add');
  $.ajax({
    method: 'GET',
    url: app.url + 'auth/twitter/',
  }).done((data) => console.log(data));
};
```

**Rack::Cors configuration**

``` rb
    config.middleware.use Rack::Cors do
      allow do
        origins '*'
        resource '*',
                 headers: :any,
                 methods: [:options, :get,
                           :post, :patch, :put, :delete]
      end
    end
```

Looking at the Network tab in the Chrome Inspector, I see the following when I trigger the JS API call:

``` md
Entry 1:
Name: twitter/
Request URL:http://localhost:3000/auth/twitter/
Request Method:GET
Status Code:302 Found
Remote Address:[::1]:3000

Entry 2:
Name: twitter/
Request URL:http://localhost:3000/auth/twitter/
Request Method:GET
Status Code:302 Found
Remote Address:[::1]:3000

Entry 3:
Name: authenticate?force_login=true&oauth_token=057nGgAAAAAAvgjxAAABVTCuQkE
Request URL:https://api.twitter.com/oauth/authenticate?force_login=true&oauth_token=057nGgAAAAAAvgjxAAABVTCuQkE
Request Method:GET
Status Code:200 
Remote Address:199.16.156.231:443
```

Not sure where to head next. Please let me know if you need further information.

**Comment by laurenfazah** [comment]
Hate to ask, but have you googled this? I personally don't know the solution, but googling the error showed a lot of similar issues, many of which spoke of CORS-related solutions.

**Comment by cuprous** [comment]
@laurenfazah 

I did google this issue, and also saw suggestions. I tried modifying the GET request to have a dataType: jsonp. 

``` js
const addTwitterAccount = function() {
  console.log('Start twitter account add');
  $.ajax({
    dataType: 'jsonp',
    method: 'GET',
    url: app.url + 'auth/twitter/',
  }).done((data) => console.log(data));
};
```

However, that just generates a new error.

**Error**

```
Refused to execute script from 'http://localhost:3000/auth/twitter/?callback=jQuery224031572374306925566_1465405772580&_=1465405772581' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

I'm going to search for that one now, but I think this may not be going anywhere.

**Comment by gaand** [comment]
CORS and Oauth does not crack easily.  And it requires an internet visible API.  

If you want to pursue this, you'll probably need a service like https://ngrok.com/

**Comment by gaand** [comment]
@cuprous is checking to see if loading the client from rails-api/public allows oauth to work

**Comment by cuprous** [comment]
@gaand 

I've placed all the files that normally go to gh-pages in the rails public folder. Rails server successfully serves the index.html at http://localhost:3000.

I'm running into a new error, however.

```
vendor.bundle.js:9285 GET https://localhost:3000/auth/twitter/ net::ERR_SSL_PROTOCOL_ERROR
```

The top of the stack trace points to the send action in vendor.bundle.js. I did not specify https://localhost:3000 in any of my ajax requests in the source.

Does this have to do with an ssl configuration on the server?

**Comment by cuprous** [comment]
Currently following the instructions here:

http://www.napcsweb.com/blog/2013/07/21/rails_ssl_simple_wa/

To see if I can get ssl in development working.

**Comment by cuprous** [comment]
The instructions that I followed did not work. Looking for another solution.

**Comment by cuprous** [comment]
@gaand 

The good news: I deployed to heroku. The application deployed successfully and is serving up a front end via the public folder. User CRUD is working, and I'm able to create an account. 

The bad new: now when I make the request for Twitter authorization on the Heroku deployment, I receive a 500 internal server error. Looking at the Heroku logs, I think that error is due to this: 

```
OAuth::Unauthorized (400 Bad Request)
```

Which I think might have to do with the way the environment variables are referred to. In development, I was accessing my API key and API secret using

```
Rails.application.secrets.twitter_api_key
```

I'm going to try 

```
ENV['twitter_api_key'] 
```

now instead and see if I get the same OAuth 400 error.

**Comment by cuprous** [comment]
@gaand 

Even more bad news: we're back to where we started!

```
XMLHttpRequest cannot load https://api.twitter.com/oauth/authenticate?force_login=true&oauth_token=nn9iyAAAAAAAvgjxAAABVTJgaa8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://damp-sea-95502.herokuapp.com' is therefore not allowed access.
```

**Comment by gaand** [comment]
Are you using `https` for all requests?

The Twitter API configuration ought to allow the request.

**Comment by cuprous** [comment]
I believe I am.

Pointing my browser at [https://damp-sea-95502.herokuapp.com/auth/twitter](https://damp-sea-95502.herokuapp.com/auth/twitter) redirects me to the Twitter authorization page successfully.

I was thinking I could just link to that, but then I lose my Rails authorization token when I switch to that window and back.

**Comment by cuprous** [comment]
This issue remains outstanding. I am not currently seeking help on it, however, since I am taking a different route for the project.

**Comment by jrhorn424** [comment]
@ga-wdi-boston/core Should this remain open?

**Comment by laurenfazah** [comment]
@jrhorn424 I vote we close since @cuprous is no longer working on the issue. Feel free to reopen if necessary @ga-wdi-boston/core
