### ISSUE TITLE
Authorization on POST

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/capstone-project#179]
Trying to make POST. Upon signing in and clicking "add to favorites" button, receiving this error in console:

<img width="1440" alt="screen shot 2016-06-08 at 12 18 49 pm" src="https://cloud.githubusercontent.com/assets/17557070/15901894/4709872c-2d73-11e6-81a3-54ca49907944.png">

In my rails server I'm receiving this response:

Started POST "/favorites" for ::1 at 2016-06-08 12:18:43 -0400
Processing by FavoritesController#create as _/_
  Parameters: {"favorite"=>{"name"=>"name", "tag"=>"tag"}}
  User Load (0.3ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "a5d53054bd918ea9ea34f12ae6090437"]]
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.3ms)

ActiveRecord::UnknownAttributeError (unknown attribute 'user_id' for Favorite.):
  app/controllers/favorites_controller.rb:21:in `create'

  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.2ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.7ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (38.1ms)

Here is my favorites controller:

``` ruby
class FavoritesController < ProtectedController
  before_action :set_favorite, only: [:show, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = current_user.favorites

    render json: @favorites
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
    render json: @favorite
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = current_user.favorites.build(favorite_params)

    if @favorite.save
      render json: @favorite, status: :created, location: @favorite
    else
      render json: @favorite.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    # @favorite = current_user.favorites.find(params[:id])

    if @favorite.update(favorite_params)
      render json: @favorite, status: :ok
    else
      render json: @favorite.errors, status: :unprocessable_entity
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy

    head :no_content
  end

  private

    def set_favorite
      @favorite = current_user.favorites.find(params[:id])
    end

    def favorite_params
      params.require(:favorite).permit(:tag, :name, :dribble)
    end

    private :set_favorite, :favorite_params, :current_user
end
```

**Comment by Jcornmanhomonoff** [comment]
this is my ajax function:

``` js
const addFavorite = (success, failure, id) => {
  // debugger;
  $.ajax({
    method:'POST',
    url: app.app.api + 'favorites',
    headers: {
      Authorization: 'Token token='+ app.token,
    },
    data: {
      "favorite": {
        "dribble": id,
        "name": "name",
        "tag": "tag",
      }
    },
  })
  .done(success)
  .fail(failure);
};
```

**Comment by RealWeeks** [comment]
have you tried using pry to debug?

**Comment by laurenfazah** [comment]
[For context] I was working with Jessica on this, but was blanking on what could be wrong here.

```
ActiveRecord::UnknownAttributeError (unknown attribute 'user_id' for Favorite.):
app/controllers/favorites_controller.rb:21:in `create'
```

Line 21 at the create method is `@favorite = current_user.favorites.build(favorite_params)`

With the controller inheriting from ProtectedController, and the rails server showing that it has received the user's token, we're confused about what this could be.

**Comment by RealWeeks** [comment]
Can you post the migration for favorite?

**Comment by Jcornmanhomonoff** [comment]
``` js
class AddDribbleToFavorites < ActiveRecord::Migration
  def change
    add_column :favorites, :dribble, :string
  end
end
```

**Comment by RealWeeks** [comment]
did you connect users to favorite in some sort to relationship?

**Comment by RDegnen** [comment]
is it because favorite_params doesn't have a :user_id in it?

**Comment by Jcornmanhomonoff** [comment]
why would it have that though?

**Comment by gaand** [comment]
What does `\d favorites` show when run in `bundle exec rails dbconsole`?

**Comment by Jcornmanhomonoff** [comment]
I needed a foreign key for favorites to reference user.
