### ISSUE TITLE
Register, Login, and create profile, all in one go.

### ISSUE THREAD

**Issue by TeoPaolucci** [ga-wdi-boston/capstone-project#18]
I plan on having profiles set up in my express application, and I would like it if I could add to my register/signup controller to also log the user in and/or create a blank profile associated with that user so that I can remove a lot of specific error handling elsewhere in my code regarding interacting with a nonexistent profile.
I know _where_ the code needs to be added to the register function in the controller...

``` javascript
signup : {
        post : function(req, res, next) {
            /* SNIP */
            pUser.then(function (user) {
                return user.setPassword(req.body.password);
            }).then(function() {
                // CODE GOES HERE!
                res.sendStatus(200);
            }).catch(function(err) {
                next(err);
            });
        }
    }
```

...but I'm not sure what I need to add there. I know that I can't use req.user immediately to create a profile because the user isn't logged in after they register, so that would be a bonus. Is this something I would handle in the front end by just making multiple ajax requests after registering or is there something I can do in the back end?

**Comment by jrhorn424** [comment]
If you pass credentials and a profile all in the same ajax request, you could have access to the profile data to use in your promise.

**Comment by TeoPaolucci** [comment]
Okay. So front-end ajax then. Makes sense. Thanks.
