### ISSUE TITLE
Storing data associated with a user in Ember

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/capstone-project#181]
I just made a `poketeam` route on the front and back-end.  My goal is to allow a user to see his/her own poketeam to which they can add/swap/remove pokemon to/from.  I have my back end schema for poketeam set up like this:

``` rb
class CreatePoketeams < ActiveRecord::Migration
  def change
    create_table :poketeams do |t|
      t.string :slot1
      t.string :slot2
      t.string :slot3
      t.string :slot4
      t.string :slot5
      t.string :slot6
      t.belongs_to :user

      t.timestamps null: false
    end
  end
end
```

What I'm thinking is that there would be a local Ember.store object that would be an array of the pokemon on the team, which is initially retrieved from the back end.  Each time the user does an action, Ember would check if there's enough room on the team (only 6 max), and if so, mutate the array, and then send that array as parameters for each of the 6 slots on the database ont he backend.  

That is the concept I have in my head, but I've spent the last couple of hours trying to figure out how to actually implement it in Ember without much luck - I'm just not sure where everything is supposed to live and how it's supposed to relate.

**Comment by gaand** [comment]
I think it's how auth does it.  Let's have a look.

**Comment by gaand** [comment]
Injecting local storage in the component (and elsewhere?).

**Comment by sjf125** [comment]
I now have a button set up to pass data to the local storage array, however I'm having trouble getting the data into the action handler in the component file.

My button:

```
<button type="button" class="btn btn-primary" data-id={{pokemon.pokedex_id}} {{action "addPokemon"}}>
  Add to poketeam
</button>
```

The button component:

```
import Ember from 'ember';
import { storageFor } from 'ember-local-storage';

export default Ember.Component.extend({
  poketeam: storageFor('poketeam'),

  actions: {
    addPokemon (pokemon) {
      let log = this.get(pokemon);
      console.log(log);
      // let poketeam = this.get('poketeam').get('id', result.user.id);
      // this.sendAction('addPokemon', pokemon);
    }
  },
});
```

What calls the button component (third one down):

```
{{pokedexter-entry/entry pokemon=pokemon}}
{{pokedexter-entry/entry/stats pokemon=pokemon}}
{{pokedexter-entry/add-pokemon-btn pokemon=pokemon}}
```

**Comment by sjf125** [comment]
I'm still having trouble adding to my local storage array.  The following code doesn't seem to add an object, it just changes the `isInitialContent` property to false.

```
import Ember from 'ember';
import { storageFor } from 'ember-local-storage';

export default Ember.Component.extend({
  store: Ember.inject.service(),
  poketeam: storageFor('poketeam'),

  actions: {
    addPokemon (pokemon) {
      let log = this.get('pokemon.name');
      console.log(this.get('poketeam'));
      this.get('poketeam').addObject(log);
      console.log(this.get('poketeam'));

      // let poketeam = this.get('poketeam').get('id', result.user.id);
      // this.sendAction('addPokemon', pokemon);
    }
  },
});
```

**Comment by RealWeeks** [comment]
@jrhorn424 thoughts on local storage for ember.  I looked into this but I'm still digging for something of use.

**Comment by sjf125** [comment]
I don't have to use LocalStorage, and just use the normal Ember store I suppose, but I thought it would be a good way to verify that the team is not larger than 6 by checking a Local Storage array length

**Comment by gaand** [comment]
Let's walk through this.

**Comment by gaand** [comment]
@sjf125  will put this on hold for a bit.

**Comment by sjf125** [comment]
Now I can't get any data returned from the server for the successful POSTs I made.  Been trying all kinds of changes to try and get data back, no luck after 2 hours.

**Comment by sjf125** [comment]
My code as it is right now:

``` js
import Ember from 'ember';
import { storageFor } from 'ember-local-storage';

export default Ember.Component.extend({
  store: Ember.inject.service(),
  auth: Ember.inject.service(),
  poketeam: storageFor('poketeam'),

  actions: {
    addPokemon () {
      let uid = this.get('auth.credentials.id').toString();
      let store = this.get('store');
      let poke = this.get('pokemon.pokedex_id');
      let newTeam = store.createRecord('poketeam', {
        slot1: 1,
        slot2: null,
        slot3: null,
        slot4: null,
        slot5: null,
        slot6: null,
      });
      // let findTeam = this.store.queryRecord('poketeam', { filter: {user_id: uid}});
      //   .then(function (data) {console.log(data);});

      let findTeam = store.queryRecord('poketeam', { filter: { user_id: uid } }).then(function(data) {
        data ? console.log('data: ' + data.content) : console.log('no data');
      });

      // newTeam.save().then(function(){console.log('saved');}/*success message */);

      // console.log(this.get('poketeam._initialContent'));
      // this.get('poketeam._initialContent')
      // this.get('poketeam').addObject(log);

      console.log('user_id: ' + uid);
      console.log('this pokemon:' + poke);
      console.log(findTeam);

      // let poketeam = this.get('poketeam').get('id', result.user.id);
      // this.sendAction('addPokemon', pokemon);
    }
  },
});
```

**Comment by sjf125** [comment]
Do I need to do anything with the adapter?

**Comment by gaand** [comment]
Should there be a call to `save` on `newTeam`.

**Comment by sjf125** [comment]
I am able to post, but I want to now test whether a user already has a poketeam on the backend.  To do that, I am trying to get the data of the poketeam that has the user's id in it, which so far I cannot figure out how to do.

**Comment by sjf125** [comment]
The problem right now is that newTeam can be created many times, but only the first one has a user_id associated with it, the rest are `nil` on the backend

**Comment by gaand** [comment]
Let's look it over.

**Comment by sjf125** [comment]
A bit of a thorny issue with the data being passed to the front end not in the format that I expected.  Changes made and getting data back now.
