### ISSUE TITLE
Trouble Importing Packages

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/capstone-project#182]
I'm trying to use the package Moment.js (http://momentjs.com/) to format date objects. I don't understand how require and import statements work, though, and I can't get it to link up with my scripts. I've installed it with npm and bower and tried `import "moment"` but no luck. What's the syntax for importing packages?

Thanks.

**Comment by laurenfazah** [comment]
You're using Ember, correct? I would look into [ember-moment](https://github.com/stefanpenner/ember-moment) to leverage as much Ember power as possible. There is no need then for importing - you should be able to follow their docs and get started with helpers right after installation.

**Comment by RDegnen** [comment]
you would do `const <variable name> = require('<npm package name>')` where npm package name is what appears in your `package.json` file

**Comment by soynog** [comment]
I'm getting "require is not defined" and it throws an error... :\

I'll look into the ember-moment package too.

**Comment by RDegnen** [comment]
Yea it might be different with ember

**Comment by soynog** [comment]
Ember-moment works like a charm. Just had to restart my server after installing. Thanks Lauren/Michael! (And Ross)

**Comment by gaand** [comment]
@soynog is this resolved?  If so, please close. Thanks.

**Comment by soynog** [comment]
Whoops, sorry! Meant to close it.
