### ISSUE TITLE
Nested for loop not updating data

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/capstone-project#183]
I tried this as a nested foreach and nested for loops. I reach the inside of the if statement but it only updates the data for one elements, not all... Here is the code:

```
  for(let i = 0; i< app.allUsers.length; i++){
    for(let j = 0; j <app.user.followee.length; j++){
      if(app.user.followee[j].followee_id === app.allUsers[i]._id){
        app.allUsers[i].followed = true;
        console.log('true', app.allUsers[i]);
      }else {
        app.allUsers[i].followed = false;
           }
    }
  }
```

And here are the console.logs showing that condition is met:

![screen shot 2016-06-08 at 3 39 29 pm](https://cloud.githubusercontent.com/assets/17519351/15908370/5b93d320-2d8f-11e6-8920-600cdfa96c75.png)

**Comment by laurenfazah** [comment]
I'm not sure this is related to the issue, but the two `followee` keys I'm seeing in the screenshot appear to be empty arrays, which would make sense that the inner if statement wouldn't be truthy.

**Comment by louarnos** [comment]
I dont think its related... I know the if statement condition is met because otherwise it wouldnt console log

**Comment by RDegnen** [comment]
if you remove the else, does it change anything?

**Comment by laurenfazah** [comment]
To piggyback on Ross's comment, does `app.allUsers[i].followed` have a default value? Is that `false`?

**Comment by louarnos** [comment]
Removing the else solved it. I dont know why. That key doesnt exist prior to the loop. It was being created at that point.
