### ISSUE TITLE
Build Error in my chrome console

### ISSUE THREAD

**Issue by V4Vince** [ga-wdi-boston/capstone-project#184]
I don't know how, but I keep getting `favicon.ico:1 GET http://localhost:4200/favicon.ico 500 (Internal Server Error)` in my console.

This is the error on the page.

```
Build error

The Broccoli Plugin: [Babel] failed with:
Error: ENOENT: no such file or directory, rmdir '/Users/vincentguo/wdi/projects/capStone/BioTrackr-client/tmp/babel-output_path-JV945jJr.tmp/ga-wdi-boston.ember-auth/tests/unit/profile'
    at Error (native)
```

I tried reverting my branch to my last commit but the issue persist.

**Comment by RDegnen** [comment]
Are you trying to display a favicon? otherwise don't worry about favicon errors

**Comment by laurenfazah** [comment]
Also is this locally or live on gh-pages?

**Comment by V4Vince** [comment]
@rdegnen @laurenfazah I'm not trying to use a favicon. My page won't load in my browser because of the error. 

This is local I haven't deployed yet

**Comment by laurenfazah** [comment]
Have you run `ember build`? If that doesn't fix things, does `grunt nag` raise any red flags?

**Comment by V4Vince** [comment]
I rebased from published master and everything is ok now. 

Thanks guys
