### ISSUE TITLE
CORS issue with my own server

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/capstone-project#185]
I'm trying to make a POST to my own server and I'm getting the error 

```
XMLHttpRequest cannot load http://localhost:3000/favorites. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
```

The front end is JS and the backend is just Rails and Postgres.  I haven't modified the Rails template and didn't have a problem with this before on the second project.  Googling this returned some things about middleware which I'm unsure of.

**Comment by susandaiute** [comment]
Solved my own issue...again.  I was posting to the wrong url.  Awkward.

**Comment by gaand** [comment]
Is that the only error?

**Comment by susandaiute** [comment]
I tried putting this in the controller, didn't help.

```
class FavoritesController < ApplicationController
  before_action :set_favorite
  before_action :set_access_control_headers

def set_access_control_headers
  headers['Access-Control-Allow-Origin'] = "*"
  headers['Access-Control-Request-Method'] = %w{GET POST OPTIONS}.join(",")
end
```

**Comment by susandaiute** [comment]
Yes

**Comment by gaand** [comment]
Does the server show anything?

**Comment by susandaiute** [comment]
```
NoMethodError (undefined method `favorites' for nil:NilClass):
  app/controllers/favorites_controller.rb:59:in `set_favorite'

```

**Comment by susandaiute** [comment]
There is a set_favorite method though.

```
def set_favorite
    @favorite = current_user.favorites.find(params[:id])
  end
```

**Comment by gaand** [comment]
You're using `current_user` but not inheriting from the right controller class.

**Comment by susandaiute** [comment]
Should I be using ProtectedController?

**Comment by gaand** [comment]
Or OpenReadController depending on the use case.

**Comment by susandaiute** [comment]
Do I have to drop the database and create + migrate after changing the controller?

**Comment by gaand** [comment]
No.

**Comment by susandaiute** [comment]
Switching to OpenRead worked. Thank you very much for taking the time to answer this so late!
