### ISSUE TITLE
3rd party API rails error (httparty gem)

### ISSUE THREAD

**Issue by MichaelB167** [ga-wdi-boston/capstone-project#186]
I'm working on interfacing my rails back-end with an API called Food2Fork to get recipes based on what plants a user has harvested.  I have a controller, model and route but a gem I installed for the model (httparty) is throwing an error when I make curl requests:

```
cannot load such file -- httparty
```

Many others have had the same error based on improperly requiring httparty but I tried several different ways and my syntax is similar to functional examples.  I did notice that the gem isn't listed in my gemfile despite having run `gem install httparty` and `bundle install`.  Am I missing another step in gem installation or is it possibly not meant to appear in the gemfile and something is still wrong with my model?  Also I realize that my key shouldn't go where it is currently but I'm planning on fixing it later.

full error:

```
Started GET "/recipes/index" for ::1 at 2016-06-08 18:52:46 -0400
Processing by RecipesController#index as */*
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)

LoadError (cannot load such file -- httparty):
  app/models/recipe.rb:2:in `<top (required)>'
  app/controllers/recipes_controller.rb:5:in `index'


  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.6ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.6ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (36.7ms)
```

model:

```
# Import httparty gem
require 'httparty'

# Model for Food2Fork API
class Recipe
  include HTTParty
  ENV['FOOD2FORK_KEY'] = 'this-was-my-key'
  base_uri 'http://food2fork.com/api'
  default_params key: ENV['FOOD2FORK_KEY']
  format :json

  def self.for(term)
    get('/search', query: { q: term })['recipes']
  end
end
```

curl:

```
curl --include --request GET http://localhost:3000/recipes/index \
    --header "Content-Type: application/json" \
```

**Comment by gaand** [comment]
You should add it to your Gemfile, but that doesn't seem like the cause.

**Comment by MichaelB167** [comment]
I thought gems were added to the Gemfile by default upon installation.  Am I maybe missing an equivalent of --save for npm that we've used with gems?

**Comment by MichaelB167** [comment]
Putting this on hold for now and working on the front end until tomorrow morning

**Comment by laurenfazah** [comment]
Oh, no, for gemfile (and this also works with a package.json file) you can add the dependency there, then run `bundle` and it will install anything that's in the gemfile.

**Comment by MichaelB167** [comment]
Thank you Lauren, that worked.  Still getting the same error though so that doesn't seem to have been the problem, working on reconfiguring my model now.

**Comment by RDegnen** [comment]
Im not sure if you need to require the gem in the top of your file.

**Comment by laurenfazah** [comment]
This similar stackoverflow question says to remove the `include HTTParty` line http://stackoverflow.com/questions/4625577/trouble-including-httparty-in-ruby-on-rails

**Comment by MichaelB167** [comment]
Yeah I've read that post like 5x haha, trying to get the environment.rb part to work currently but it's crashing my server when I restart.

Giving myself another hour to work on this but if I don't get it I'll leave it until after the presentation and work on UI stuff instead bc I have to get the Ember calls working too which will take me at least half a day.

**Comment by MichaelB167** [comment]
Thank you Ross, curl requests are now rendering recipes.  The first step was removing the HTTParty requirement which had fixed the initial error and was rendering successful yet empty responses which I hadn't realized because I was focused on changing environment.rb.  

The next step was going back through the HTTParty docs and Food2Fork docs to see how to get a JSON response to render instead of getting an empty body.  As per the HTTParty docs, we reconfigured the response variable in the controller to have a search term variable interpolated in it.  The final step was specifying the JSON to render via @response.body instead of just @response, again as specified by the docs.  The controller and model now look like this: 

Controller: 

```
# Controller for Food2Fork API
class RecipesController < ApplicationController
  def index
    @search_term = params[:looking_for] || 'broccoli'
    # @recipes = Recipe.for(@search_term)
    @response = HTTParty.get("http://food2fork.com/api/search?key=5b778f1043cebc3d2ef97301d9e0b8ca&q=#{@search_term}")
    render json: @response.body, status: 200
  end
end
```

Model: 

```
class Recipe
  include HTTParty
  ENV['FOOD2FORK_KEY'] = 'my-key'
  base_uri 'http://food2fork.com/api'
  default_params key: ENV['FOOD2FORK_KEY']
  format :json

  def self.for(term)
    get('/search', query: { q: term })['recipes']
  end
end
```
