### ISSUE TITLE
Handlebars click event not grabbing the correct data

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/capstone-project#187]
I have a click event for a button inside a handlebars template. 

```
  $('.petResultsTemplate').on('click', '#addPetButton', function(data) {
    console.log('add pet button clicked');
    console.log(data);
};
```

The click event had to be bound to a div outside of the template in order for the click event to fire.  I'm trying to make a post request of a pet's name and description and would usually do that with "data.petfinder.pets.pet", but when I console log data, I'm just getting the data of the button.  I've tried everything, including custom handlebars helpers, html attributes, and trying to bind the pet's name and description to the button, but nothing seems to work.  I also tried declaring the pet's data both globally and local to the function.  I can't seem to grab the data of the pet from handlebars rather than the button. 
[This](http://stackoverflow.com/questions/21418108/jquery-on-event-handler-event-delegation-and-passing-custom-data) was helpful, except it didn't work with handlebars' iteration.
 Anyone have any ideas?

**Comment by laurenfazah** [comment]
Are you trying to get data from a data attribute? If so you need to use `$(this).data("<hyphenated-data-tag-name>")` within the function passed into the click event.

**Comment by susandaiute** [comment]
I think for that to work, I'd have to bind data to the button which I haven't been able to do.  Not sure.  So far, whenever I use 'this' it just points to the button.

**Comment by laurenfazah** [comment]
What does your HTML button look like?

**Comment by susandaiute** [comment]
```
<div class="row bucket-row">
  <h1 class='pets-header'>PETS</h1>
  {{#each pets}}
    <div class="col-md-6">
      <div class=" view view-first ">
        <div class="image-container "><img src=" {{this.media}} "></div>
        <div class="mask">
          <div class="pet-name">
            <h3>{{this.name.$t}}</h3>
            <button type="button" id="addPetButton" class="pet-button"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></button>
            <span class="glyphicon glyphicon-remove" id="deletePetButton" data-id="{{id}}" aria-hidden="true"></span>
            <div class="pet-description">
              <p>{{this.description.$t}}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  {{/each}}
</div>
```

**Comment by susandaiute** [comment]
Solution: this all had to do with the bizarre structure of the response object Petfinder sends back.  Instead of looking like:

```
Petfinder:{
       Pet:{
           Name:Marvin
}}
```

It looks like:

```
Petfinder:{
       Pets: {
              Pet:{
                 Name: {
                        $t: Marvin
}}}}
```

So adding `$t` to the handlebars was the trick.

Final product:

```
  $('.petResultsTemplate').on('click', '#addPetButton', function() {
    console.log('add pet button clicked');
    console.log($(this).data("data-name"));
};
```

```
<button type="button" id="addPetButton" data-name="{{this.name.$t}}" class="pet-button"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></button>
```
