### ISSUE TITLE
Trying to write a promise... hitting my error/resolution handler before before async function is complete

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/capstone-project#188]
I am making a series of getOneUser calls to my api by iterating over an array of user Ids. As I do this I am pushing each returned user to a new array. When this is complete I want to render these users using handlebars. 

I have been writing a promise to accomplish this, but whenever I execute it I hit my resolution/error handler prior to the async calls finishing. Maybe I'm missing something basic. Here is my code:

```
app.followees = [];

    function getFollowees () {
      return new Promise(function(resolve, reject){

        app.user.followee.forEach(function(followee){
          appApi.getOneUser(appUi.getFolloweeSuccess,
                            appUi.getFolloweeFailure,
                            followee.followee_id);
                            });


          if(app.followees >= 1){
            resolve(console.log(app.followees, 'resolved'));
          }else {
            reject('oops');
          }
        });
      }

    getFollowees().then(() => {
      $('.user-followees-div').html('');
      console.log('after getting all users');
      $('.user-followees-div').append(displayUserFollowees({
        followees: app.followees
      }));
      }).catch((error) => console.log(error));
  });
};

```

The success handler for getOneUser pushes the user to the array. I know my if() resolve statement is not the best, but I just wanted to get something rendering. Where am I going wrong?

**Comment by louarnos** [comment]
I think I need another function wrapper somewhere?

**Comment by RDegnen** [comment]
in your return new Promise you don't need the `function(resolve, reject)` it should just be `return new Promise((resolve, reject => ...` . see if that solves anything

**Comment by louarnos** [comment]
I changed my handlebars template to handle one user at a time and then I just rendered each in the success handler for the api call
