### ISSUE TITLE
Rails/Heroku Redeployment Issue

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/capstone-project#189]
I'm having issues with deploying my api. Even though it works fine on the local server and it seems to be deploying fine, requests to the deployed API are failing with a 500 error.

Specifically, I'm getting an "ActiveRecord::UnknownAttributeError (unknown attribute 'first_name' for User.):"

This is an attribute I added in and permitted in the user controller. Again, it works fine on my local version, and I committed all changes for the redeploy. I can verify that it's got all the right changes in gh-pages.

I've tried making requests both from the front end and and through curl scripts, and both get the same error.

I'm pulling out my hair. Can someone please help?

**Comment by laurenfazah** [comment]
What errors do you see when you run `heroku logs`?

**Comment by soynog** [comment]
Solved! I had to drop and re-migrate my database on Heroku, since I made schema changes. Thank you @J-Weeks !

**Comment by laurenfazah** [comment]
Could you close @soynog ? Thanks
