### ISSUE TITLE
Images when deploying ember to github-pages

### ISSUE THREAD

**Issue by olivia-leach** [ga-wdi-boston/capstone-project#193]
Hi there!

I am testing deploying my ember app to github pages. All is fine, except that one image is not loading. Images that I have referenced from html bars load fine, but one image that I define in a class in an .scss file does not appear.

`olivia-leach.github.io/:1 GET http://olivia-leach.github.io/healthy-buildings-app/assets/images/backsplash-cdac383ea27c80fa98cd801fa1aa2209.png 404 (Not Found)`

I followed the guide [here](http://osxi.github.io/ember/github/git/2015/09/22/ember-cli-apps-on-github-pages.html) about removing the leading slash from image URLs, but am still having no luck.

**Comment by gaand** [comment]
Suggested the solution from #166.

**Comment by olivia-leach** [comment]
When I add: 

``` js
  app.import('public/images/backsplash.jpg', { destDirt: 'assets/images' });
```

to the ember-cli-build.js file, I get an error on ember build:

``` sh
Build failed.
The Broccoli Plugin: [Funnel: Funnel 
  public/images
  public/images
 include:1] failed with:
Error: ENOENT: no such file or directory, scandir '/Users/Olivia/wdi/projects/healthy-buildings-proj/healthy-buildings-app/tmp/funnel-input_base_path-t6ZwBiE7.tmp/0/public/images/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at _walkSync (/Users/Olivia/wdi/projects/healthy-buildings-proj/healthy-buildings-app/node_modules/walk-sync/index.js:66:20)
```

I also tried `'/images...` and `'images...` as the pathname in the ember-cli-build file and got a similar error.

**Comment by laurenfazah** [comment]
I'll take a look with you.

**Comment by olivia-leach** [comment]
Found a workaround by appending the body image in the index route instead of the css file:

```
import Ember from 'ember';

export default Ember.Route.extend({
  activate: function(){
        $('body').css('background', "url('images/backsplash.png') no-repeat center center fixed");
        $('body').css('background-size', 'cover');
        Ember.$('body').append()
      },
  deactivate: function(){
        $('body').css('background-image', "none");
        Ember.$('body').toggleClass("rest");
      }
});
```

**Comment by jrhorn424** [comment]
Based on your error, this might have fixed it:

``` diff
-  app.import('public/images/backsplash.jpg', { destDirt: 'assets/images' });
+  app.import('public/images/backsplash.jpg', { destDirt: 'public/images' });
```

**Comment by gaand** [comment]
@jrhorn424 The image name gets munged.  I'm not sure if it's to a determinate value.
