### ISSUE TITLE
OpenReadController in rails api template issur

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/capstone-project#194]
I've set my SymptomsController to inherit OpenReadController

``` ruby
class SymptomsController < OpenReadController
  before_action :set_symptom, only: [:show, :update, :destroy]
```

I thought this was the only change necessary to allow

``` ruby
  def getsolutions
    @title = symptom_params['title']
    @symptoms = Symptom.where title: @title
    render json: @symptoms
  end
```

this action to work without a user being logged in.

I get `jquery.js:9175 POST http://localhost:3000/get-solutions/ 401 (Unauthorized)` in the console when I try to use it.

I get 

```
Started OPTIONS "/get-solutions/" for ::1 at 2016-06-09 14:40:06 -0400


Started POST "/get-solutions/" for ::1 at 2016-06-09 14:40:06 -0400
Processing by SymptomsController#getsolutions as HTML
  Parameters: {"symptom"=>{"title"=>"I have Imposter Syndrome"}}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "f"]]
  Rendered text template (0.0ms)
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 8ms (Views: 2.4ms | ActiveRecord: 0.6ms)


Started POST "/get-solutions/" for ::1 at 2016-06-09 14:40:10 -0400
Processing by SymptomsController#getsolutions as HTML
  Parameters: {"symptom"=>{"title"=>"I have Imposter Syndrome"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "f"]]
  Rendered text template (0.0ms)
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 2ms (Views: 0.6ms | ActiveRecord: 0.3ms)

```

in the rails server. It looks like it's all good, and then halts at an auth fail. Where is it checking for auth? I'm not sure why it's referncing users at all in there. It should doing something more like 
`SELECT "solutions".*FROM"symptoms"WHERE"title"."title"`

**Comment by jrhorn424** [comment]
OpenRead only allows `:index` and `:show` to pass through without authorization. See: https://github.com/ga-wdi-boston/rails-api-template/blob/master/app/controllers/open_read_controller.rb#L3

Do you have a solutions controller? Does it make sense for something called `SymptomsController#getsymptoms` to instead be called `SolutionsController#{index|show}`, with a conventional URL `GET /solutions`?

**Comment by BenGitsCode** [comment]
I changed it back to Protected and found a bug where i was storing things in a data object but wasn't accessing the correct key.  Problem solved, should have used protected and sent the right data.
