### ISSUE TITLE
Throwing errors after deployment

### ISSUE THREAD

**Issue by V4Vince** [ga-wdi-boston/capstone-project#198]
I deployed my rails api to heroku and my ember front-end to gh-pages. I am able to load my front-end via `https://v4vince.github.io/BioTrackr-client/` but I can't sign in or sign up. 

It also doesn't look like my heroku server is sleeping and I copy and pasted the production script into `config > environment` as such 

```
 if (environment === 'production') {
    ENV.baseURL = '/mysterious-falls-32517.herokuapp.com/';
    ENV.locationType = 'hash';
  }
```

The error im getting is:
`https://v4vince.github.io/sign-up Failed to load resource: the server responded with a status of 405 (Method Not Allowed)`

**Comment by gaand** [comment]
I'll have a look.

**Comment by jrhorn424** [comment]
CORS?

**Comment by V4Vince** [comment]
I found the [solution here](https://github.com/ga-wdi-boston/capstone-project/issues/141), but I havent tried it yet. Will update in a little bit.

**Comment by gaand** [comment]
That's the issue I mentioned.

**Comment by V4Vince** [comment]
Thanks @gaand. I made the changes and its been about 10mins, but I'm still getting the same error. 

I'm going to give it another 15mins and I'll post an update.

**Comment by gaand** [comment]
Did you rebuild for production?

**Comment by V4Vince** [comment]
@gaand I ran `ember build` without the `--environment=production` the first time. I just built with `ember build --environment=production` how long should I give it?

**Comment by gaand** [comment]
After you build and push I'd wait at least a few minutes, say 5?

**Comment by V4Vince** [comment]
@gaand it is still giving me the same error.

Here are the steps I took:

ajax/services.js

``` js
import Ember from 'ember';
import AjaxService from 'ember-ajax/services/ajax'; 
import ENV from 'biotrackr-ember-client/config/environment'; // <-- added this line

export default AjaxService.extend({
  auth: Ember.inject.service(),
  host: ENV.API_HOST,    // <-- added this line
```

application/adapter.js

``` js
import Ember from 'ember';
import ActiveModelAdapter from 'active-model-adapter';
import ENV from 'biotrackr-ember-client/config/environment';   //<-- added this line

export default ActiveModelAdapter.extend({
  auth: Ember.inject.service(),
  host: ENV.API_HOST, // <-- added this line
```

config/environment.js

``` js
module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'biotrackr-ember-client',
    environment: environment,
    baseURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    }
  };

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.baseURL = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {
    ENV.API_HOST = 'https://mysterious-falls-32517.herokuapp.com';  //<-- added this line
    ENV.baseURL = '/';
    ENV.locationType = 'hash';
  }

  return ENV;
};
```

After that I ran `ember build --environment=production` then `git add` and `git commit` to gh-pages. Then I ran `git push origin gh-page`s`. While writing this I realized that I shouldve done `git subtree push --prefix dist origin gh-pages` instead. 

Now that I am trying to run `git subtree push --prefix dist origin gh-pages` its saying  

```
To git@github.com:V4Vince/BioTrackr-client.git
 ! [rejected]        bcbd21876e3c89dda50187e64565e9849c746307 -> gh-pages (non-fast-forward)
error: failed to push some refs to 'git@github.com:V4Vince/BioTrackr-client.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
```

I try to `git pull origin gh-pages` but its telling me that its already up to date.

**Comment by V4Vince** [comment]
Also, I should mention that there are always a bunch of `/dist` files that needs to be added even though I didn't change any thing

**Comment by gaand** [comment]
You can probably `--force` push the subtree.

**Comment by V4Vince** [comment]
should it be `git subtree --force push --prefix dist origin gh-pages` ?

**Comment by gaand** [comment]
I'm not sure.  I'd google.

Or (very carefully) move/delete the gh-pages branch on github then push the subtree.

**Comment by V4Vince** [comment]
I'm actuall not seeing anything about a `--force` but I do see a `--hard`.  Do you think its advisable to revert back to my commit right before I started to deploy and start the deployment on a clean slate?

**Comment by RealWeeks** [comment]
Natalie had a similar issue, we went on github and delete the gh-pages branch. Then followed all the directions in the ember-deployment-guide again, and it worked.

**Comment by RealWeeks** [comment]
We also pulled master then switch to gh-pages for a fresh start before doing that, not sure if it would make a different but we were mucking around on that gh-pages branch so didn't want any of that.

**Comment by natdjerf** [comment]
I've was able to deploy again but none of my files in the public folder are available.. I may need some help tomorrow morning again

**Comment by RealWeeks** [comment]
Hey @natdjerf not to be mean, but this sounds like a separate issues, possibly open another issues for it so if anyone in the future has the same problem we know where to go.

**Comment by RealWeeks** [comment]
@V4Vince Please follow up and let us know if it worked and what you did if anything different

**Comment by V4Vince** [comment]
@j-weeks Im on my way into Boston now. I should be in by 845ish.

currently I deleted my gh-pages branch in github. I readded the adapters, Ajax, and config/environment production script. And pushed my master to github.

All I have to do now is to do the steps in the ember deployment guide again.

**Comment by V4Vince** [comment]
After deleting gh-pages on Github, deployment was successful following the Ember deployment guide
