### ISSUE TITLE
Creating a User and Profile in sql with the submission of the same form

### ISSUE THREAD

**Issue by HoldenMills** [ga-wdi-boston/capstone-project#2]
I have successfully created a user and I'm now trying to create a profile as well when I submit the registration form.  The three fields are 'username', 'e-mail' and 'password'.  Ideally I would like the profile to contain just the username for security purposes.  Do I need the profile to contain a user id as well as a profile id?  I tried to separate the form into a class (with username) and an id (without the username), thinking that it would submit 'email', 'password' and 'username' to Profile, and just 'email' and 'password' to User, but that broke everything.

My index.html file is;

``` html
<h3>Register</h3>
        <form id="register">
          <input name="username" type="text" value="" size="15" placeholder="username">
          <input name="email" type="text" value="" size="15" placeholder="e-mail">
          <input name="password" type="password" size="10" value="" placeholder="password">
          <input id="register" type="submit" value="Register">
        </form>
```

My click handler is;

``` javascript
var url = 'http://www.localhost:3000';

  var form2object = function(form) {
    var data = {};
    $(form).children().each(function(index, element) {
      var type = $(this).attr('type');
      if ($(this).attr('name') && type !== 'submit' && type !== 'hidden') {
        data[$(this).attr('name')] = $(this).val();
      }
    });
    return data;
  };

  var wrap = function wrap(root, formData) {
    var wrapper = {};
    wrapper[root] = formData;
    return wrapper;
  };

$(document).ready (function() {

  $('#register').on('submit', function(e) {
    var credentials = wrap('credentials', form2object(this));
    api.register(credentials, cb.registerCB);
    e.preventDefault();
  });

   $('#profile').on('click', function(e){
    var username = wrap('username', form2object(this));
    api.newProfile(username, cb.newProfileCB);
    e.preventDefault();
  });
```

My ajax api calls;

``` javascript
var api = {

url: 'http://www.localhost:3000',

url: 'http://httpbin.org/post',

  ajax: function(config, cb) {
    $.ajaxSetup({
      xhrFields: {
        withCredentials: true
      }
    });
  },

  ajax: function(config, cb) {
    $.ajax(config).done(function(data, textStatus, jqxhr) {
      cb(null, data);
    }).fail(function(jqxhr, status, error) {
      cb({jqxher: jqxhr, status: status, error: error});
    });
  },

 register: function register(credentials, callback) {
    this.ajax({
      method: 'POST',
      // url: ,
      url: this.url + '/register',
      contentType: 'application/json; charset=utf-8',
      data: JSON.stringify(credentials),
      dataType: 'json'
   }, callback);
 },

newProfile: function newProfile(username, callback) {
    this.ajax({
      method: 'POST',
      url: this.url + '/profile',
      contentType: 'application/json; charset=utf-8',
      // data: JSON.stringify({}),
      dataType: 'json'
    }, callback);
  },
};
```

and my callback;

``` javascript
var cb = {
registerCB: function(err, data){
    if (err) {
      console.log(err);
    } else {
      api.newProfile(cb.newProfileCB);
      console.log(data);
    }
  },

newProfileCB: function(err, data) {
    if (err) {
      console.error(err);
    } else {
      console.log("success:", data);
    }
  },
};
```

**Comment by jrhorn424** [comment]
Thanks for the code and explanation! Can you explain again why you need the username in the profile? If the username is in the User store, you should be able to access the User store from the Profile store if you've set up relationships appropriately.

**Comment by srhoulam** [comment]
Yes, your profile model needs to have both a user id for the owning user and its own id within its table.

Your front-end API has duplicate keys for `url` and `ajax`. Only the latter value you set counts here; it overwrites the previous key-value pair. This is a low-priority thing; it won't solve the issue at hand.

**Comment by HoldenMills** [comment]
@jrhorn424 - I was basing my model off of Antony's api and he said that authenticating a user and implementing a separate profile off of that would be more secure (at least that was my understanding).  My thinking is that the profile only needs to store a username instead of all three for security reasons.  I need the profile to be able to post a list, it could be easier to just use the User, but I though including a Profile would be a "better" practice.

@srhoulam - The duplicate key was originally commented out.  Thanks for pointing that out.

**Comment by gaand** [comment]
Added profile data to registration.

Added `autosave: true`, to `has_one profile` in user model.

Added `@user.build_profile` to `auth#register`

**Comment by HoldenMills** [comment]
Registering a new user is working but creating a new profile is not.  
My auth controller;

``` ruby
def register
    @user = User.new(credentials)
    @user.build_profile()
    if @user.save
      render json: @user, status: :created, location: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

def credentials
    params.require(:credentials).permit(:email,
                                        :password
    )
  end

  def profile
    params.require(:profile).permit(:username)
  end
```

My click handler:

``` javascript
$('#register').on('submit', function(e) {
    var registrationInfo = {
      credentials: {},
      profile: {}
    };
    registrationInfo.credentials.email = $('#register').children('input[name="email"]').val();
    registrationInfo.credentials.password = $('#register').children('input[name="password"]').val();
    api.register(wrap('credentials', registrationInfo.credentials), cb.registerCB);
    registrationInfo.profile = $('#register').children('input[name="username"]').val();
    console.log(registrationInfo.credentials);
    e.preventDefault();
  });
```

My ajax api calls;

``` javascript
register: function register(credentials, callback) {
    this.ajax({
      method: 'POST',
      // url: ,
      url: this.url + '/register',
      contentType: 'application/json; charset=utf-8',
      data: JSON.stringify(credentials),
      dataType: 'json'
   }, callback);
 },

newProfile: function newProfile(profile, callback) {
    this.ajax({
      method: 'POST',
      url: this.url + '/profile',
      contentType: 'application/json; charset=utf-8',
      // data: JSON.stringify({}),
      dataType: 'json'
    }, callback);
  },
```

and my callback;

``` javascript
newProfileCB: function(err, data) {
    if (err) {
      console.error(err);
    } else {
      console.log("success:", data);
    }
  },

  registerCB: function(err, data){
    if (err) {
      console.log(err);
    } else {
      api.newProfile(cb.newProfileCB);
      console.log(data);
    }
  },
```

When I run a register command it successfully creates and saves a user, then gives me this error; ActionController::ParameterMissing (param is missing or the value is empty: credentials):
  app/controllers/auth_controller.rb:37:in `credentials'
  app/controllers/auth_controller.rb:17:in`register'.

**Comment by jrhorn424** [comment]
What do you see when you log the (JSON) object you're sending to the auth controller on profile creation?

**Comment by gaand** [comment]
You need to pass the profile data to `build_profile`, i.e. `@user.build_profile(profile)`.

**Comment by HoldenMills** [comment]
Still getting a bad request after passing profile to build_profile

**Comment by HoldenMills** [comment]
@jrhorn424 I'm seeing Object {email: "bears@bears.com", password: "bears"} 
                                        cb.js:34 Object {user: Object} 
    (or whatever the email is supposed to be)

**Comment by gaand** [comment]
What errors do you get from rails?

**Comment by HoldenMills** [comment]
ActionController::ParameterMissing (param is missing or the value is empty: profile):
  app/controllers/auth_controller.rb:43:in `profile'
  app/controllers/auth_controller.rb:18:in`register'

or in the console
POST http://www.localhost:3000/register 400 (Bad Request)
cb.js:31 Object {jqxher: Object, status: "error", error: "Bad Request"}

**Comment by jrhorn424** [comment]
The JSON you're sending to your server needs to look like this:

```
{
  "credentials": { "username": "whatever" /* etc. */ },
  "profile": { /* your profile data */ }
}
```

**Comment by jrhorn424** [comment]
Is your earlier paste the entire object you're sending?

**Comment by HoldenMills** [comment]
no I'm sending in the email, username, and password.  The User is pulling out the email and password while the Profile takes just the username.  I tried changing 

`````` javascript```
$('#register').on('submit', function(e) {
    var registrationInfo = {
      credentials: {},
      profile: {}
    };
to
```javascript
$('#register').on('submit', function(e) {
    var registrationInfo = {
      "credentials": {},
      "profile": {}
``````

That did not stringify the array object (I think that's what credentials and profile are in this case).  I'm running JSON.stringify(credentials) and JSON.stringify(profile) on their respective api calls so shouldn't that take care of making it a string?

**Comment by gaand** [comment]
The code doesn't seem to have pasted correctly.

You need to make one call to register with an object that contains both `credentials`, and `profile`, i.e. registrationInfo..

**Comment by jrhorn424** [comment]
The error message(s) is:

```
param is missing or the value is empty: credentials
...
param is missing or the value is empty: profile
```

The JSON is:

```
 var registrationInfo = {
      "credentials": {},
      "profile": {}
```

You have an empty object assigned to credentials. ("param is missing **or the value is empty**")

**Comment by jrhorn424** [comment]
You should be grabbing the data from a form somewhere using jQuery.

**Comment by HoldenMills** [comment]
I understand that I need to pass 

``` javascript
registrationInfo.credentials.email = $('#register').children('input[name="email"]').val();
```

and

``` javascript
    registrationInfo.credentials.password = $('#register').children('input[name="password"]').val();
```

to var registrationInfo = {"credentials"}

followed by the invocation of 

``` javascript
api.register(wrap('credentials', registrationInfo.credentials), cb.registerCB);
```

and then

``` javascript
registrationInfo.profile.username = $('#register').children('input[name="username"]').val();
```

to var registrationInfo = {"credentials"}

but I cannot figure out the right syntax.

**Comment by jrhorn424** [comment]
Are you doing { "credentials" } without a colon? The object literal is a key-value pair and you've only got a key if that's the case. I'm happy to take a look in the morning.

**Comment by jrhorn424** [comment]
Please run linter and fix any errors before we meet.

**Comment by gaand** [comment]
You should not call `wrap` .  The object literal serves that purpose.  Then pass the registrationInfo (credentials and profile) in the ajax request to the register action of the AuthController.

**Comment by jrhorn424** [comment]
The JSON is coming along.

@gaand Would you mind having a look? I can't figure out why his front-end is convinced `POST http://localhost:3000/register - 404 Not Found` when I'm staring at the route in rails.
