### ISSUE TITLE
Readme -- What Goes in "Installation Instructions"?

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/capstone-project#200]
The readme is supposed to include `Installation instructions for any dependencies`

What does this mean? Just npm install and bower install? Or a list of additional add-ons we included?

**Comment by RDegnen** [comment]
yea, like if someone was to fork and clone your repo, how would they install the dependencies

**Comment by soynog** [comment]
Gosh I have no idea...

I'll do my best.

**Comment by jrhorn424** [comment]
It's the thing you do every time you fork and clone... 😉
