### ISSUE TITLE
Heroku, 3rd Party API Get request, CORS issue

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/capstone-project#201]
I'm making a GET request to the petfinder API.  I deployed to heroku and am now getting the error 

```
XMLHttpRequest cannot load https://aqueous-tor-31019.herokuapp.com/pets. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://susandaiute.github.io' is therefore not allowed access. The response had HTTP status code 500.
```

This was working earlier, not sure what changed.

I haven't touched the backend at all.

**Comment by gaand** [comment]
http versus https?

**Comment by susandaiute** [comment]
I think maybe it might be something else, because it worked after deploying earlier and I haven't edited the back end which is where the get request is happening from.

**Comment by susandaiute** [comment]
The only thing I can think of that changed is that, on the frontend, I moved where I call the getPets function from a button to being called on sign in.  Then I noticed the error and moved everything right back how it was.

**Comment by gaand** [comment]
You're loading the client from `http` but hitting the server over `https`.  Change the line in your repository to start with `https`.

**Comment by susandaiute** [comment]
In the back end?

**Comment by gaand** [comment]
No, on your repository home page.

There's still a problem.  You'll need to check `heroku logs` for the API to see if it shows the error.  Your getting an error preceding the CORS error.

**Comment by gaand** [comment]
Did you run migrations on heroku?

**Comment by susandaiute** [comment]
When I was deploying, yes.
And by in my repository, do you mean where it links to the deployed site?

**Comment by gaand** [comment]
Yes, the link to the deployed site should start with `https`.

Did you run `heroku logs` from your API?

**Comment by susandaiute** [comment]
Yes, I'm having trouble figuring out what I'm reading.

**Comment by gaand** [comment]
Please post the last few lines.

**Comment by susandaiute** [comment]
```
016-06-10T02:02:54.277680+00:00 heroku[router]: at=info method=GET path="/pets" host=aqueous-tor-31019.herokuapp.com request_id=daeae324-3400-4ca7-ae0c-d3b814d8324e fwd="24.233.84.213" dyno=web.1 connect=0ms service=5ms status=500 bytes=330
2016-06-10T02:02:54.268345+00:00 app[web.1]: Started GET "/pets" for 24.233.84.213 at 2016-06-10 02:02:54 +0000
2016-06-10T02:02:54.269944+00:00 app[web.1]: Processing by PetsController#index as */*
2016-06-10T02:02:54.270383+00:00 app[web.1]: Completed 500 Internal Server Error in 0ms (ActiveRecord: 0.0ms)
2016-06-10T02:02:54.271095+00:00 app[web.1]: 
2016-06-10T02:02:54.271104+00:00 app[web.1]: TypeError (no implicit conversion of nil into String):
2016-06-10T02:02:54.271117+00:00 app[web.1]:   app/controllers/pets_controller.rb:5:in `+'
2016-06-10T02:02:54.271118+00:00 app[web.1]:   app/controllers/pets_controller.rb:5:in `index'
```

**Comment by susandaiute** [comment]
```
016-06-10T02:02:54.277680+00:00 heroku[router]: at=info method=GET path="/pets" host=aqueous-tor-31019.herokuapp.com request_id=daeae324-3400-4ca7-ae0c-d3b814d8324e fwd="24.233.84.213" dyno=web.1 connect=0ms service=5ms status=500 bytes=330
2016-06-10T02:02:54.268345+00:00 app[web.1]: Started GET "/pets" for 24.233.84.213 at 2016-06-10 02:02:54 +0000
2016-06-10T02:02:54.269944+00:00 app[web.1]: Processing by PetsController#index as */*
2016-06-10T02:02:54.270383+00:00 app[web.1]: Completed 500 Internal Server Error in 0ms (ActiveRecord: 0.0ms)
2016-06-10T02:02:54.271095+00:00 app[web.1]: 
2016-06-10T02:02:54.271104+00:00 app[web.1]: TypeError (no implicit conversion of nil into String):
2016-06-10T02:02:54.271117+00:00 app[web.1]:   app/controllers/pets_controller.rb:5:in `+'
2016-06-10T02:02:54.271118+00:00 app[web.1]:   app/controllers/pets_controller.rb:5:in `index'
```

**Comment by gaand** [comment]
It says you're using a `nil` on line 5 of the pets controller.

Please post the index action.

**Comment by susandaiute** [comment]
```
class PetsController < ApplicationController
  require 'net/http'
  KEY = ENV['PETFINDER_KEY'];
  def index
    url = URI.parse('http://api.petfinder.com/pet.find?key=' + KEY + '&animal=dog&breed=Labrador+Retriever&output=full&location=02184&format=json&distance=100')
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) do |http|
      http.request(req)
    end
    render json: res.body
  end
end
```

That's the entire controller.  It was created just for the get request.

**Comment by gaand** [comment]
KEY is `nil`, so you can't add it to a string.

Did you set PETFINDER_KEY in the heroku app (web console or command line)?

**Comment by susandaiute** [comment]
No, how do I do that?

**Comment by susandaiute** [comment]
I think you mentioned this earlier in the week and I completely forgot about it!

**Comment by susandaiute** [comment]
I'm guessing it would be like 
`heroku config:set GITHUB_USERNAME=joesmith`
except it would be KEY=blahblahblah ?

**Comment by gaand** [comment]
Yes!

**Comment by gaand** [comment]
Well, PETFINDER_KEY.

**Comment by susandaiute** [comment]
Great! Thank you!! Do I have to redeploy?  The terminal said it was restarting my app.

**Comment by gaand** [comment]
You shouldn't. Try it. If it works, then no.

**Comment by susandaiute** [comment]
It works.  Thank you for answering my questions so late at night!  I really appreciate it.
