### ISSUE TITLE
 No 'Access-Control-Allow-Origin' error when making a POST request to join table

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/capstone-project#206]
I am trying to make a POST request to a join table, joining my users table and my questions table using the following code:

``` javascript
const createQuestionInJointTable = (status, user_id, question_id, notes) => {
  return $.ajax({
  method: 'POST',
  url: app.host + '/user_questions',
  headers: {
    Authorization: 'Token token=' + app.user.token,
  },
  data:
    { "status":status,
      "user_id":user_id,
      "question_id":question_id,
      "notes":notes,
    }
});
};
```

I however get the error when calling this API:

`XMLHttpRequest cannot load http://localhost:3000/user_questions. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.`. 

Even though when I post to either my user table or my questions table I get no error. 

I was able to hard code data into the join table, and make a get request to `/user_questions`, using the following code:

``` javascript
const createQuestionInJointTable = (status, user_id, question_id, notes) => {
  return $.ajax({
  method: 'GET',
  url: app.host + '/user_questions',
  headers: {
    Authorization: 'Token token=' + app.user.token,
  },
});
};
```

And this works without any errors. 

How do I post to the join table without getting the error:

`XMLHttpRequest cannot load http://localhost:3000/user_questions. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.`? 

I realize it has to do with authorization, the fact that there is no 'Access-Control-Allow-Origin' and so the browser is blocking the request. 

I have also checked out: 

[link 1](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjt7b6L2Z7OAhUJgx4KHSQHCBcQFggcMAA&url=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F9310112%2Fwhy-am-i-seeing-an-origin-is-not-allowed-by-access-control-allow-origin-error&usg=AFQjCNEBBKIMBCq-IkwZph5jekcuv5lWpw&sig2=LnbdTCGPSa0_SIBqHJANZQ)
[link 2](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjt7b6L2Z7OAhUJgx4KHSQHCBcQFggjMAE&url=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F20035101%2Fno-access-control-allow-origin-header-is-present-on-the-requested-resource&usg=AFQjCNGO3wQ6xHGNsN3PVVq96zRqauJuig&sig2=CvG3eStQk54VYlzW7LAhpA)
[link 3](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwjt7b6L2Z7OAhUJgx4KHSQHCBcQFggqMAI&url=https%3A%2F%2Fgithub.com%2Fsocketio%2Fsocket.io-client%2Fissues%2F641&usg=AFQjCNEB-i40C38gaI7p03PIOkFcnVeGEg&sig2=0glgg_NYR-eOpI73bQMrSA)
[link 4](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwjt7b6L2Z7OAhUJgx4KHSQHCBcQFggwMAM&url=https%3A%2F%2Fjvaneyck.wordpress.com%2F2014%2F01%2F07%2Fcross-domain-requests-in-javascript%2F&usg=AFQjCNHkqdx_7E78U-vxlIn-Rdx-Tm-sNA&sig2=CxwEO9ogInSBUy7RBtoE5w)

Any more links, and exhaustive google searches, with no solutions present.

Thanks so much!

Esther

**Comment by berziiii** [comment]
What is the route in your API from your routes file for `users_questions`?

**Comment by berziiii** [comment]
It doesn't appear you're passing in the right `data` set:

```
data: {
    "user_question": {
        "status":status,
        "user_id":user_id,
        "question_id":question_id,
        "notes":notes
    }
}
```

you may need to tell your api that you're sending a user_question.

**Comment by esthercordova** [comment]
I changed the object I passed to data:

``` ruby
const createQuestionInJointTable = (status, user_id, question_id, notes) => {
  return $.ajax({
  method: 'POST',
  url: app.host + '/user_questions',
  headers: {
    Authorization: 'Token token=' + app.user.token,
  },
  data:
    {"user_question":{ "status":status,
                        "user_id":user_id,
                        "question_id":question_id,
                        "notes":notes,
                      }
    }
});
};
```

And that fixed it! Thanks so much.
