### ISSUE TITLE
current user issues, need to restrict access to data

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/capstone-project#208]
My joint table controller was inheriting from < ApplicationController instead of < OpenReadController which allowed my client to access all information on instead of just the current user information.

In addition I added @user_questions = UserQuestion.where(user: current_user) t the index function in the controller.

Now my app has only access to the data that is owned by an user.

Jeff helped.

**Comment by jrhorn424** [comment]
For anyone else running into this issue, the problem with using `current_user` when you're not inheriting from `OpenReadController` is that the `set_current_user` method never gets run for `index` or `show` actions.

**Comment by jrhorn424** [comment]
We also discussed using query parameters for requesting questions of a certain difficulty status instead of requesting all of the user questions and filtering on the client using a loop.
