### ISSUE TITLE
Ember won't navigate to route if model returns undefined

### ISSUE THREAD

**Issue by erinsul** [ga-wdi-boston/capstone-project#209]
I'm probably trying to set this up wrong, but basically, my idea was to have a route `/profiles` that shows a user's profile if it exists, and if it doesn't, shows a form to create a profile.

Yeah, this isn't working. It works just fine to render an already-created profile (created via curl request), but when a profile hasn't yet been created, it errors out and won't even go to the route, and definitely isn't showing my form to create one.

The error I'm actually receiving is `ember.debug.js:32096 TypeError: Cannot read property 'some' of undefined` but the problem appears to be that the get request is returning with nothing when there is no profile on the back end. At least I think, because when the model code is commented out, it shows the form.

The code in the model looks like this: 

``` js
// edited by @jrhorn424 - please use "preview" to ensure correct format of your issue
export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('profile');
  },

  actions: {
      create(data) {
        console.log(data);
        let profile = this.get('store').createRecord('profile', data);
        profile.save();
      }
    }
});
```

the template: 

``` hbs
{{! edited by @jrhorn424 - please use "preview" to ensure correct format of your issue }}
{{#if model}}
{{#each model as |profile| }}
{{user-profile profile=profile}}
{{/each}}
{{else}}
{{user-profile/new submit='create'}}
{{/if}}
```

And let me know if you need to see any other code! I feel like there's something really obvious that I'm just missing. Thanks.

**Comment by payne-chris-r** [comment]
What if you look inside the model for the `if` statement? 
For ex) `{{#if model.profile}}` or `{{#if model.first_name}}` not sure exactly how your data is set up, but it sounds like model is being loaded even if it's blank...

**Comment by berziiii** [comment]
@erinsul, did you get this figured out? If not, please share additional information. If so, please close. Thank you.

**Comment by jrhorn424** [comment]
Also, please format code blocks using backticks.

**Comment by jrhorn424** [comment]
In order to debug this further, you'll need to use the Data tab in the Ember Inspector. Let me know if you'd like to sit down and work through it.

**Comment by erinsul** [comment]
Sorry, kinda gave up and moved on from this one. I didn't really fix it, just changed the routing so that I have a separate create-profile route instead of trying to use the /profiles route for creation.
