### ISSUE TITLE
Ember - data won't load from localhost:3000

### ISSUE THREAD

**Issue by cwcrane** [ga-wdi-boston/capstone-project#21]
I have a games tables in a rails backend, sitting on localhost:3000. I am unable to hit this server with any requests from ember however. No idea why. Here is my games route in ember:

```
export default Ember.Route.extend({
    model: function(){
        return this.store.findAll('game');
    }
});
```

Games template:

```
<h1>Games</h1>
{{#each model as |game|}}
<p>{{game}}</p>
{{/each}}
{{outlet}}
```

Games model:

```
export default DS.Model.extend({
  home_team_id: DS.attr('number'),
  away_team_id: DS.attr('number'),
  home_team_goals: DS.attr('number'),
  away_team_goals: DS.attr('number')
});
```

Games adapter inherits from the application adapter. The application adapter looks like this:

```
export default DS.RESTAdapter.extend({
    host: 'http://localhost:3000',
    headers: {
    'Content-Type': 'application/json'
  }
});
```

Any help would be appreciated!

**Comment by jrhorn424** [comment]
What errors are you receiving?

**Comment by cwcrane** [comment]
No errors that I can see. But the model method in route is not hitting my server, and it's not pulling in games data

**Comment by gaand** [comment]
Any errors from chrome?  What does the network tab show when you make the request?

**Comment by jrhorn424** [comment]
Also try debugging by inspecting bound values in your templates and triggering actions in your controllers/components with debugging statements in them.

**Comment by cwcrane** [comment]
Sorry, correction, I am geting this error in chrome console: Error while processing route: games No model was found for 'game' Error: No model was found for 'game'

Will try jeff's suggestion

**Comment by jrhorn424** [comment]
That's telling you that you're missing `app/game/model.js`.

**Comment by jrhorn424** [comment]
Where is this stored?

```
export default DS.Model.extend({
  home_team_id: DS.attr('number'),
  away_team_id: DS.attr('number'),
  home_team_goals: DS.attr('number'),
  away_team_goals: DS.attr('number')
});
```

**Comment by cwcrane** [comment]
That is stored in my game model. So I fixed it with Kelvin's help:
I changed the name of my pod from 'games' to 'game', updated the router to 'game', and updated the game route to findAll('game') 

Thanks, I'll close the issue
