### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/capstone-project#210]
Getting this error:  

![image](https://cloud.githubusercontent.com/assets/13932794/17300365/1788cc6e-57e0-11e6-9b92-0c203c3e6373.png)

I want to sort my data on the api side and request data depending on the values of the columns. I'm getting this error. My path maybe wrong. I need to change the route file in my api.

**Comment by berziiii** [comment]
You could do a request for all `user_questions` associated with a user and then in handlebars you would render the data according to it's status. 

``` js
{{#if user_questions.status === 'easy'}}
      ....
{{ else if user_questions.status === 'medium'}}
      .....
{{ else }}
      ...
{{/if}}
```

Try that.

**Comment by esthercordova** [comment]
I don't want to display the questions on the webpage. I will just count them and have a statistic table.

Jeff suggested to do the sorting on the backend, peusdo code:

  // if hard then endpoint = /user_questions?status=hard
  // else if medium endpoint = /user_questions?status=medium
  //
  // maybe in another function?
  // Promise.all[apiRequestForHard, apiRequestForMedium...]

**Comment by payne-chris-r** [comment]
Is your backend handling the query parameter your'e passing in?

**Comment by payne-chris-r** [comment]
Just talked to Esther in person. I think she better understands query params and is moving forward trying to get the status to be sent via query params. Esther, let us know if you run into further issues!

**Comment by payne-chris-r** [comment]
How we doin' Esther?

**Comment by esthercordova** [comment]
I think I'm going in a different direction right now. Coming back to this.

**Comment by berziiii** [comment]
@esthercordova, any updates on this issue? If still having trouble, please provide more information on what you've done since chatting with Chris, if resolved, please provide solution and close. Thank you!

**Comment by esthercordova** [comment]
I didnt touch it. Working on other things.

**Comment by jrhorn424** [comment]
Thanks for the update. :smile:

**Comment by jrhorn424** [comment]
@esthercordova Can this be closed?

**Comment by payne-chris-r** [comment]
Just talked to Esther. She's still working on this.

**Comment by berziiii** [comment]
@esthercordova please close with solution if resolved. Thanks!
