### ISSUE TITLE
getFormFields not working with Handlebars form

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/capstone-project#211]
When a user clicks "update profile", it displays a handlebars within an HTML form that contains all of the previous user data in editable fields.  I have an event handler attached to a click event to update the profile, but it does not appear that the data is getting pulled by getFormFields. 

HTML

<div id="edit-profile-section">
    <form class="profile-display" id="edit-my-profile-form">
      <fieldset class="form-group">
        <div class="row">
          <div id="edit-profile"></div>

```
    </div>
    <div class="profileEditButton">
      <input type="submit"  id="save-profile-button"  class="edit-profile btn btn-default" value="Update">
    </div>
  </fieldset>
</form>
```

  </div>

Events
const onUpdateMyProfile = (event) => {
  debugger;
  event.preventDefault();
  let data = getFormFields(event.target);
  console.log(data);
  api.updateMyProfile(data)
  .then(ui.updateMyProfileSuccess)
  .catch(error => console.error(error));
};

**Comment by payne-chris-r** [comment]
Wut duh error message?

**Comment by andreasantarl** [comment]
No error message.  I consolelog the data, and it's an empty object

**Comment by berziiii** [comment]
Fixed, please provide your solution @andreasantarl

**Comment by andreasantarl** [comment]
GetFormFields only pulls data on 'submit' events and not 'click' events

**Comment by payne-chris-r** [comment]
Please close @andreasantarl !
