### ISSUE TITLE
Query route updates, but redering doesnt

### ISSUE THREAD

**Issue by shireen-bean** [ga-wdi-boston/capstone-project#214]
I am querying profiles to return the profile of the current user in the model like this:

```
export default Ember.Route.extend({
  auth: Ember.inject.service(),
  model () {
    return this.get('store').queryRecord('profile', { user_id: this.get('auth.credentials.id')});
  },
});
```

Note this is my backend with two profiles, one belonging to user 1, other to user 2;

```
{
profiles: [
{
id: 1,
given_name: "Shireen",
level: 1,
user_id: 1,
favorites: [
{
id: 1,
created_at: "2016-08-01T16:26:20.293Z",
updated_at: "2016-08-01T16:26:20.293Z",
recipe_id: 2,
profile_id: 1
}
],
schedules: [
{
id: 1,
created_at: "2016-08-01T16:36:23.272Z",
updated_at: "2016-08-01T16:36:23.272Z",
eat_on: "2016-08-01",
recipe_id: 2,
profile_id: 1
}
]
},
{
id: 2,
given_name: "Jason Frishman",
level: 1,
user_id: 2,
favorites: [ ],
schedules: [ ]
}
]
}
```

When I am logged in as Shireen, and i click profiles, it routes to:

`"http://localhost:4200/profiles?user_id=1".`
and displays the correct information.

And when I am logged in as "jason" with user id =2, it routes to
`"http://localhost:4200/profiles?user_id=2".`
But renders the information for shireen...

**Comment by shireen-bean** [comment]
`DEPRECATION: The adapter returned an array for the primary data of a`queryRecord`response. This is deprecated as`queryRecord`should return a single record. [deprecation id: ds.serializer.rest.queryRecord-array-response]`

This is the issue I get back. It looks like its returning an array but, there should and there is only 1 object that fits the specification as a single profile belongs to a user. so each user_id only corresponds with one profile

**Comment by berziiii** [comment]
Issue partially references Lindsey's  #219  but she was also missing current_user in her api. If current_user was present in the controller, any get request to #index action would only return the current users profile. Thus no need for the query of user_id. @shkherad please add anything else that I missed or done to correct this issue.

**Comment by shireen-bean** [comment]
SOLUTION:

Just went back to convention:

BACKEND Profile Controller:

```
  def index
    @profiles = @current_user.profile

    render json: @profiles
  end
```

Profiles Route:

```
import Ember from 'ember';

export default Ember.Route.extend({
  auth: Ember.inject.service(),
  model () {
    return this.get('store').findAll('profile');
  },
});
```

And out pops the correct profile and only that profile.
