### ISSUE TITLE
jQuery preventing CRUD actions

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/capstone-project#215]
It all works when I don't hide and show elements.

It breaks when I do.

**Comment by berziiii** [comment]
@andreasantarl, did you get this figured out? If so, please post solution and close or provide more information. Thank you!

**Comment by jrhorn424** [comment]
Are you using `$.show` and `$.hide`? If so, I believe it removes and adds elements to the DOM. You'll need to use event delegation to attach handlers if that's the case.

**Comment by andreasantarl** [comment]
Using handlebars instead.
