### ISSUE TITLE
img tag failing in ember component

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/capstone-project#217]
Not sure why this won't work. I am not passing in a variable or anything, I just want to show a logo and I am having trouble with it.

**Comment by MishaHerscu** [comment]
Favicons also aren't working.

**Comment by berziiii** [comment]
Does it have an error or just render?

**Comment by jrhorn424** [comment]
I'm guessing there's a missing closing tag somewhere. Can you provide the template code for us to look at?

**Comment by MishaHerscu** [comment]
```
{{hamburger-menu}}
{{#link-to "application" class="navbar-brand"}}
  <img class="website-logo" src="airplane_logo.png" alt="Logo">
  <!-- Home -->
{{/link-to}}

```

airplane_logo.png is in the same directory as this component template.

It is showing the alt text.

**Comment by MishaHerscu** [comment]
`    {{content-for "head"}}

```
<link rel="stylesheet" href="assets/vendor.css">
<link rel="stylesheet" href="assets/togetherness-ember-client.css">
<link rel="icon" href="img/favicons/airplane-favicon.ico">

{{content-for "head-footer"}}`
```

This is the failing section of index.html. It links to a favicon, but to no avail.

Also - I am not sure I really understand this index.html. It would be great if someone could spend a couple minutes and explain it to me.

**Comment by jrhorn424** [comment]
> airplane_logo.png is in the same directory as this component template.

That's your problem. Ember has a build pipeline. You need to search through some of the old issues to see how to link to static assets like images using Ember.

**Comment by MishaHerscu** [comment]
Great! Thanks, I'll take a look.

**Comment by payne-chris-r** [comment]
If you get here and are looking at how to use images in Ember-build, take a look at this: http://stackoverflow.com/questions/32629787/ember-cli-where-to-put-images
