### ISSUE TITLE
Profile found by ID properly in one place, but not in another.

### ISSUE THREAD

**Issue by TeoPaolucci** [ga-wdi-boston/capstone-project#22]
I'm testing the final functionality of my profile system in Postman and I'm running into a strange error.

While logged in as a user when you use a GET request to the route `/profile`, it uses the following line to find the current user's profile by id:
`Profile.findOne({userID: req.user._id.toString()}).exec()`
And it works as expected, if there is no profile, this...

``` javascript
.then(function (profile) {
          if(!profile) {
            var err = new Error("No Profile found");
            return next(err);
          }
```

...happens, and if there is a profile: `res.json(profile);`
Those lines of code all work as they are intended to.
Later on, with a GET request to `/profile/trust` I have _identical_ code performing the same task, finding a profile by ID and throwing an error if it can't find anything,

``` javascript
Profile.findOne({userID: req.user._id.toString()}).exec()
        .then(function (profile) {
          if(!profile) {
            var err = new Error("Profile not created yet");
            return next(err);
          }
```

but when I tested this on a user of which I already created a profile for (and the profile does get returned properly when I use GET at `/profile`), when I use GET at `/profile/trust`, no profile is found, instead I receive `null`.

Is this a scope issue? The routing that I have seems fine and the intended function is firing, but using a search method identical to one I have elsewhere is yielding different results?

**Comment by jrhorn424** [comment]
In `/profile/trust`, `trust` is being interpreted as the `_id`. (Dis)prove it using a console log before you `findOne`.

**Comment by gaand** [comment]
What do your routes starting from '/profile' look like?

**Comment by TeoPaolucci** [comment]
Saad helped me here, I had my `/profile/:id` routes before my `/profile/trust` route and it was calling `trust` as the contents of `:id`. Switched them around and it all works fine.

**Comment by srhoulam** [comment]
We resolved this by switching the order the routes are mounted on the router. Route `/profile/:id` was catching requests sent to `/profile/trust` as false positives. Now, `/profile/trust` gets first dibs on requests aimed at it, and `/profile/:id` grabs the rest.
