### ISSUE TITLE
Cannot access beers object on user object

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/capstone-project#220]
I'm trying to edit a beer but I can't access the beer object when I console.log(app).  

Here's what I want to do:
- click the edit button on a beer
- get request to get data for that one beer
- open the modal to edit the beer
- make edits, on submit, make PATCH request

I'm not sure what I'm doing wrong.  Thrashing right now!!

**Comment by jrhorn424** [comment]
You shouldn't need to use your `app` store object for this. Are you using a promise? This is how I would coordinate it at a high level:
- click the edit button on a beer (this starts the ajax on the next step)
- get request to get data for that one beer (the ajax on this step returns a promise)
- open the modal to edit the beer (the model opening is triggered in a then chained on to the first step, pass the result through and render the modal)
- make edits, on submit, make PATCH request (start a new ajax promise here)

**Comment by jrhorn424** [comment]
@andreasantarl Can this be closed?
