### ISSUE TITLE
Trying to PATCH to a not existing row in joint-table

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/capstone-project#221]
I am having the issue that I need to PATCH to my joint -table, that is empty when signedUp. So i need to POST first on SignUp then PATCH afterwards.

**Comment by jrhorn424** [comment]
I spoke with @esthercordova about this and she decided that for her feature, it would be best to create blank rows after user sign up.

A better solution would be to re-think the modeling, but we decided not to pursue that for now.

**Comment by esthercordova** [comment]
Since I got the error:
![image](https://cloud.githubusercontent.com/assets/13932794/17336717/6a7825aa-58ad-11e6-9bd4-a71237609efe.png)

when I tried to do a POST request directly after the SignUp I refactored my code to automatically signIn after signUp so that I have access to the data that holds the user token information? Taht's what I thought. I'm getting this data object and pass with .then to a api call that is supposed to make a POST request to my joint table:

![image](https://cloud.githubusercontent.com/assets/13932794/17336661/2fe200dc-58ad-11e6-9368-e2a83379fda3.png)

Unfortunately that seems still not to be the right data. This also doesnt give me the right data to be able to to pass the user token, so that I can make a POST request.

Thats my SignUp function:

![image](https://cloud.githubusercontent.com/assets/13932794/17336778/af26a4a6-58ad-11e6-8707-fd2d5537e636.png)

**Comment by jrhorn424** [comment]
@esthercordova @payne-chris-r Where did we leave off on this?

**Comment by esthercordova** [comment]
This is the working code, that signsUp, then SignIn, then loops over to create POST requests to create instance in the joint table for each question.

![image](https://cloud.githubusercontent.com/assets/13932794/17342493/950bc62c-58c7-11e6-9271-40d5b2317c3c.png)

Issue was that I didnt provide the needed data to the next .then(), so I coudnt access the token, since I didnt pass the token.
