### ISSUE TITLE
GetFormFields returning Empty Object

### ISSUE THREAD

**Issue by computingbets** [ga-wdi-boston/capstone-project#225]
I am trying to pass field data to my api. My set-up is correct b/c i see console.logs in the event function. However, the input data is logged as an empty object and does not get passed to the api.
         errors - 

```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400. 

ActionController::ParameterMissing (param is missing or the value is empty: channel):
```

HTML -

```
  <form id="channel-input">
      <fieldset>
        <input type="text" name="channel[name]" placeholder="enter channel">
        <input type="submit" value="submit">
      </fieldset>
    </form>
```

Event handler

```
 $('#channel-input').on('click', onChannelInput);
```

Event function -

```
const onChannelInput = function (event) {
  // console.log("channel input");
  event.preventDefault();
  let data = getFormFields(event.target);
  console.log(data);
  api.channelInput(data)
  .done(ui.success)
  .fail(ui.failure);
};
```

Also, a clue may be that when I click the form (w/o input) it calls the function. Then, I put in data(integer) and it kicks the same error. 

ty

**Comment by computingbets** [comment]
Roobs Scoobs helped me. We changed the event handler from .on('click') to .on('submit'). I now nominate Ruben as lead WDI instructor.

**Comment by jrhorn424** [comment]
Lead, huh?

**Comment by computingbets** [comment]
Haha, co-lead?
