### ISSUE TITLE
Ember: Link-to dynamic route is undefined when param is from user.credentials store

### ISSUE THREAD

**Issue by lcurran** [ga-wdi-boston/capstone-project#226]
If I navigate manually to the current user's url route `'users', { path: '/users/:id' }`, I can access the data that belongs to the user.

However when I click my `{{#link-to "user"}}` from my application, the path is undefined.
Tried a bunch of different things with @berziiii and we couldn't figure out how to set it up so the route could access the user id.

**Comment by jrhorn424** [comment]
``` diff
- 'users', { path: '/users/:id' }
+ 'user', { path: '/users/:id' }
```

**Comment by jrhorn424** [comment]
The plural client route `users` should be reserved for the URL `/users`, not `/users/:id`.

**Comment by lcurran** [comment]
My bad that was a typo in the ticket not in my app. Copypasta:

```
  this.route('user', { path: '/users/:id' });
```

**Comment by jrhorn424** [comment]
Got it. Can have a look in a moment.

**Comment by jrhorn424** [comment]
A single resource link-to requires an ID or an object to passed as the second argument to the helper. 

``` diff
- {{#link-to "user"}}
+ {{#link-to "user" something_goes_here}}
```

**Comment by jrhorn424** [comment]
Mind closing @lcurran? Thanks.
