### ISSUE TITLE
hasMany / belongsTo ember error

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/capstone-project#227]
Hey guys,

this is the situation:

I am getting the following error in my console and there is nothing rendered in the relevant div on my page when I navigate to the route in question.

`TypeError: Cannot read property 'some' of undefined`

I am not really sure where to go from with that error.

My code:

I have cities which have attractions.

In my rails back end, the relationship looks like this:

models:

```
# Attraction Model
class Attraction < ActiveRecord::Base
  has_many :attraction_tags, inverse_of: :attraction, dependent: :destroy
  has_many :attraction_suggestions, inverse_of: :attraction, dependent: :destroy
  has_many :user_attractions, inverse_of: :attraction, dependent: :destroy
  belongs_to :city, inverse_of: :attractions
end
```

```
# City Model
class City < ActiveRecord::Base
  has_many :attractions, inverse_of: :city, dependent: :destroy
  has_many :trips, inverse_of: :city, dependent: :destroy
end
```

**Comment by MishaHerscu** [comment]
Front end Attraction Model:

```
import DS from 'ember-data';

export default DS.Model.extend({
  eventful_id: DS.attr('string'),
  city_id: DS.attr('string'),
  city_name: DS.attr('string'),
  country_name: DS.attr('string'),
  title: DS.attr('string'),
  description: DS.attr('string'),
  owner: DS.attr('string'),
  db_start_time: DS.attr('string'),
  db_stop_time: DS.attr('string'),
  event_date: DS.attr('string'),
  event_time: DS.attr('string'),
  event_time_zone: DS.attr('string'),
  all_day: DS.attr('string'),
  venue_id: DS.attr('string'),
  venue_name: DS.attr('string'),
  venue_address: DS.attr('string'),
  postal_code: DS.attr('string'),
  venue_url: DS.attr('string'),
  geocode_type: DS.attr('string'),
  latitude: DS.attr('string'),
  longitude: DS.attr('string'),
  image_information: DS.attr('string'),
  medium_image_url: DS.attr('string'),

  city: DS.belongsTo('city', {
    inverse: 'attraction',
  }),
});
```

Front end City Model:

```
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),

  attractions: DS.hasMany('attraction', {
    inverse: 'city'
  }),
});
```

**Comment by MishaHerscu** [comment]
In the listr-list API from class we have:

```
#
class Item < ActiveRecord::Base
  belongs_to :list
end
```

and

```
#
class List < ActiveRecord::Base
  has_many :items, dependent: :destroy
end
```

which looks like my back end (i am assuming my inverses aren't the problem, but should test that later

**Comment by MishaHerscu** [comment]
the listr-list client doesn't have the relationships I have:

```
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  hidden: DS.attr('boolean'),
  items: DS.hasMany('item'),
});
```

```
import DS from 'ember-data';

export default DS.Model.extend({
  content: DS.attr('string'),
  done: DS.attr('boolean'),
  list: DS.belongsTo('list'),
});
```

**Comment by MishaHerscu** [comment]
I got rid of my front-end relationships, and the error is gone, but I still am not rendering data from the back end

**Comment by MishaHerscu** [comment]
I checked my back end and data IS coming the way I expect i.e. when I go to localhost:3000/cities I do see an array of attractions

**Comment by MishaHerscu** [comment]
ah this may be it: i see in the listr-api there is some unfamiliar code in the serializers. im looking into it now and will try to generalize:

```
#
class ItemSerializer < ActiveModel::Serializer
  attributes :id, :content, :done, :list

  def list
    object.list.id
  end
end
```

```
#
class ListSerializer < ActiveModel::Serializer
  attributes :id, :title, :hidden, :items

  def items
    object.items.pluck(:id)
  end
end
```

**Comment by MishaHerscu** [comment]
Those weren't the answer. They make the content of the request smaller, by only sending the ID of the nested object, but it is useless if I can't then join back to the nested model on the front end.

**Comment by MishaHerscu** [comment]
```
console.log(city.get('name'));
console.log(city.get('attractions'));
```

The first one gives me "Chicago". The second is undefined. So there is no actual attractions attribute for cities on my front end. I feel like I'm getting closer, but I am missing the key piece of how to actually add that to the cities. 

If I want to make it work, I can use a promise chain, and just get all of the attractions that happen to have this city ID with another call to the store, but that seems like the inelegant way. I think having a store and references on the front end is a thing specifically to not have to do that.

**Comment by lcurran** [comment]
If you comment out Jeff's error handling in the application route.js file, you'll get the actual ember error and not the some of undefined one!

**Comment by jrhorn424** [comment]
@MishaHerscu Follow @lcurran's advice and let me know if you get a more helpful error message. If you debug the issue, please let us know how you resolved it and close the issue.

**Comment by jrhorn424** [comment]
Also see #214, #218, #219 and especially #212.

**Comment by MishaHerscu** [comment]
Okay thanks guys. I actually got it to work this morning by doing that on @SarahHartwick's suggestion and then removing the belongsTos.
