### ISSUE TITLE
I Love the Smell of Issues in the Morning - Curl PATCH

### ISSUE THREAD

**Issue by computingbets** [ga-wdi-boston/capstone-project#228]
I am getting a parsing error and an unexpected token in my curl req.

```
 curl --include --request PATCH http://localhost:3000/channels/1 \
--header "Content-Type: application/json" \
--data '{
   “channel": {
     “name": 1,
    “ads”: “true”,
   }
}'
```

Ads is a boolean and I have tried it with and without quotes and commas.
I need this curl to work because I'm trying to patch a "channel" using it's name but I also need the ID so this is a related issue.

**Comment by jrhorn424** [comment]
You have a trailing comma after "ads". Also, I can tell those quotes are curly quotes instead of straight quotes. That comes from copypasta usually. Please delete them and re-type them.

<img width="226" alt="i_love_the_smell_of_issues_in_the_morning_-_curl_patch_ _issue__228_ _ga-wdi-boston_capstone-project" src="https://cloud.githubusercontent.com/assets/388761/17373551/b20cf2aa-5976-11e6-8781-5167f3fce5ee.png">

**Comment by computingbets** [comment]
It worked after changing syntax. I had to go to my Rails and change the show from 

```
def show
    render json: @channel.find(params[:id])
  end
```

to

```
def show
    render json: @channel
  end
```

Is this a concern for my other methods? ie a custom route?

**Comment by jrhorn424** [comment]
I don't think so. Check out the `set_channel` method in that controller. That's why you couldn't do `@channel.find...`: it was already being done for you.

**Comment by computingbets** [comment]
Cool. Checks out. I put what I had in etc in Slack at the bottom of my initial issue. I am trying to find a "channel" by a seperate column in that channels table. Sarah helped me write a custom route which looks like 

```
route - get '/channels/:number' => 'channels#search'

controller - 

def search
    @channels = Channel.all
      @channel = @channels.select {|c| c.name==params[:number]}
    render json: @channel
  end
```

I tried using this route but I get a 404 in both the console and Rails Server.
Should this be a separate issue?

**Comment by computingbets** [comment]
error - jquery.js:9175 GET http://localhost:3000/channels/%20%20%20%20%20%20453 404 (Not Found)

**Comment by jrhorn424** [comment]
Yes, this should be a separate issue.

For now, look at the URL: `http://localhost:3000/channels/%20%20%20%20%20%20453`

See all thos `%20`s? Those are spaces. Do you have spaces somewhere they shouldn't be?

**Comment by jrhorn424** [comment]
@logicmyth Did this help?

**Comment by computingbets** [comment]
The separate issues thing was helpful. %20 was baffling but I switched a div that I was getting the id from and it was ECT for my code.
