### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. 

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/capstone-project#229]
When trying to do a PATCH request I run into:

![image](https://cloud.githubusercontent.com/assets/13932794/17368586/becbccaa-5962-11e6-978c-996422771ac6.png)

My rails server says: param is missing or the value is empty: user_question
![image](https://cloud.githubusercontent.com/assets/13932794/17368621/db719114-5962-11e6-9719-61d94d31d73d.png)

I thought I pass the right information but I guess I don't.

Passing following:
![image](https://cloud.githubusercontent.com/assets/13932794/17368653/00634fb2-5963-11e6-89d5-b902bb6aec09.png)
![image](https://cloud.githubusercontent.com/assets/13932794/17368671/0a9d5d24-5963-11e6-8ca1-6523e71389e3.png)

I checked with my Back-end and it requires following: 

![image](https://cloud.githubusercontent.com/assets/13932794/17368705/25b2ae02-5963-11e6-8811-b96010dea0d7.png)

I checked how I did it in my second project and I just can't figure out why I'm not sending the right data for the PATCH request.

**Comment by jrhorn424** [comment]
`require(:user_question)` means you need rooted JSON in your AJAX `data` property.

**Comment by esthercordova** [comment]
![image](https://cloud.githubusercontent.com/assets/13932794/17374678/c113eb3c-597b-11e6-9e71-e46e22861ecf.png)
 thanks
