### ISSUE TITLE
Need Help Reading Error Message

### ISSUE THREAD

**Issue by LaurenGrant** [ga-wdi-boston/capstone-project#23]
I am getting an error when trying to register from my webapp and the error messages are something I have never seen before and hard to read. 

Can you help me read what the messages are saying is wrong? Google was no help.

Terminal server log - 

"[2015-12-15 10:18:56] ERROR bad URI `u?R?$?3A??F?\x1F?4D?o'=??\x12ԍ?wd\x7F\x00\x00\x1E?+?/\x00??\x14?\x13?'.
[2015-12-15 10:18:56] ERROR bad Request-Line`\x16\x03\x01\x00?\x01\x00\x00?\x03\x028F?",YB/}?7??o???;??j???u??-z?^?\x00\x00\x14?'.
[2015-12-15 10:18:56] ERROR bad URI `?aſA\x048'."

Front end console -

"OPTIONS https://localhost:3000/register net::ERR_SSL_PROTOCOL_ERRORsend @ jquery-2.1.4.js:8630jQuery.extend.ajax @ jquery-2.1.4.js:8166api.ajax @ ajax.js:13register @ ajax.js:23(anonymous function) @ ajax.js:127jQuery.event.dispatch @ jquery-2.1.4.js:4435elemData.handle @ jquery-2.1.4.js:4121

ajax.js:114 Object {jqxhr: Object, status: "error", error: ""}callback @ ajax.js:114(anonymous function) @ ajax.js:16fire @ jquery-2.1.4.js:3099self.fireWith @ jquery-2.1.4.js:3211done @ jquery-2.1.4.js:8266(anonymous function) @ jquery-2.1.4.js:8599"

**Comment by gaand** [comment]
Your using `https` as the protocol to localhost(not the trailing `s`),  but you probably want `http` while developing.  The jumble is the browser encrypting data.

**Comment by LaurenGrant** [comment]
That helped! I have a different error now but I think I can figure that one out.

**Comment by gaand** [comment]
:-).

**Comment by gaand** [comment]
http versus https (https only for deployed apps).
