### ISSUE TITLE
Unable to update albums

### ISSUE THREAD

**Issue by RoobScoobs** [ga-wdi-boston/capstone-project#230]
Hey guys, 

The lack of any errors makes this a bit difficult to figure out.

I defined my update function in the edit-album route 

``` js
actions: {
    editAlbum (data) {
      this.get('store').findRecord('album', data.id)
           .then(function(album) {
             album.title = data.title;
             album.artist = data.artist;
             album.description = data.description;
             console.log(album);
             return album.save();
           })
           .then(() => this.transitionTo('albums'));
         },
```

Only the `this.transitionTo('albums')` actually fires. I console logged the data being passed and it includes all the attributes, so I know the binding is correct, but the changes are not showing in the browser and in the back-end.

**Comment by RoobScoobs** [comment]
The template in edit-album is written as the following: 

``` hbs
{{edit-album-form album=model editAlbum="editAlbum" goToAlbums="goToAlbums"}}
```

The edit-album-form component includes the action edit which corresponds to the template in edit-album. 

``` js
export default Ember.Component.extend({
  tagName: ['form'],

  album: {},

  actions: {
    edit () {
      this.sendAction('editAlbum', this.get('album'));
    },

    reset () {
      this.sendAction('goToAlbums');
    },
  },
});
```

**Comment by berziiii** [comment]
it doesn't appear you're declaring alum as a variable in the action.

i.e: 

``` js
let album = this.get('store').findRecord('album', data.id);
...
return album.save();
```

see if that helps

**Comment by RoobScoobs** [comment]
Doesn't seem to make a difference, although an error does appear in the linter, which says 'album' is defined but never used.

But I'm using it in the rest of the function!

**Comment by jrhorn424** [comment]
Try the following. If it helps, see if you can tell me why. If it doesn't help, tell me why. :smile:

``` diff
actions: {
    editAlbum (data) {
      this.get('store').findRecord('album', data.id)
           .then(function(album) {
-             album.title = data.title;
+            album.set('title', data.title);
+           // then do the same for the rest ...
-             return album;
           })
+         .then((album) => album.save())
           .then(() => this.transitionTo('albums'));
         },
```

**Comment by RoobScoobs** [comment]
New error shows that it cannot read property '_attributes' of undefined, so album is still undefined in this case. 

So it made sense to follow the approach you mentioned because we want to set the attributes of the data object passed from the component to a specific album

**Comment by jrhorn424** [comment]
Is what you are calling `data` already an album in the store? If so you can just follow the example of Update from listr.

**Comment by jrhorn424** [comment]
https://github.com/ga-wdi-boston/ember-resources/commit/63ac6698edd05df29f2c2aaa7270d847db328fa1

**Comment by RoobScoobs** [comment]
Hmm... still unable to figure it out 

Data is the album object containing the keys and values from the form which is being passed from the component up to the route

**Comment by jrhorn424** [comment]
@RoobScoobs Solution?

**Comment by RoobScoobs** [comment]
Everything was initially right on the front-end, and we could see how it momentarily shows the updated values and then it reverts back to what is stored in the back-end. The reason is tied to the albums controller in which the show method was not rendering the json, so the show method in this line `before_action :find_album, only: [:show, :update, :destroy]` wasn't doing anything.  

``` ruby
def show
    #render json: @album
  end
```

I had a separate method defined as `find_album` which was rendering json, however, this was causing the issue.  

``` ruby
def find_album
    @album = Album.find(params[:id])
     render json: @album
  end
```

The solution was simply removing the comment from `def show`

**Comment by jrhorn424** [comment]
Thanks @RoobScoobs! A few more notes:

We ensured all filter methods were uncommented and activated at the top of the class.

Actual changes: 

``` diff
def show
-    #render json: @album
+    render json: @album
end
```

``` diff
def find_album
    @album = Album.find(params[:id])
-     render json: @album
end
```
