### ISSUE TITLE
Getting Data from route that links to another model

### ISSUE THREAD

**Issue by shireen-bean** [ga-wdi-boston/capstone-project#231]
I am trying to make a post to a join table so i need my profile_id and my recipe id. The action happens on a component that is linked to the recipe model, but how do i grab my profile ID to also pass that parameter.

I tried 2 things: trying to save profile ID to credentials, but that is a whole  other issue. and this:

```
    add (recipe) {
      let profile_object= this.get('store').findAll('profile');
      let profile_id = this.get('profile_object.id')
      console.log("The profile id is" + profile_id)
      return this.get('ajax').post('/schedules', {
        data: {
          schedule: {
            profile_id: 15,
            recipe_id: 4,
          },
        },
      }
    );
    }
```

profile_object comes back as a DS.promise array
and profile_id comes back undefined no matter how hard I try to extract data from it

My post request works when i try to hard code it as seen above but the end goal is to have it be more like:

```
return this.get('ajax').post('/schedules', {
        data: {
          schedule: {
            profile_id: profileID,
            recipe_id: recipe,
          },
        },
      }
```

**Comment by shireen-bean** [comment]
I even tried passing the data to it from the other model and it still only properly reads recipe as recipe ID but it can't get the profile id.

profile=profile goes all the way up to my profiles template so the component appears there too for this test. I was just trying to see if I could pass the data.

Template

```
<button type="submit" profile=profile recipe=recipe class="btn btn-primary" {{action "add"}}>
  Cook This
</button>

```

Component:

```
  actions: {
    add () {
      this.sendAction('add',this.get('recipe.id'), this.get('profile.id'));
    }
  }
```

**Comment by jrhorn424** [comment]
Make sure you fetch the profile in the application route and then bind it to any components that need it. Something like:

``` js
// app/application/route.js

...
model () {
  return {
    recipes: this.get('store').findAll('recipe'),
    profile: this.get('store').findRecord('profile', ...)
  };
},
```

In order to find a profile from the user, you'll need to first get the user and serialize out from the API the profile ID.

**Comment by jrhorn424** [comment]
Since not everyone is logged in on the application route, try instead to access the profile from a computed property inside the `my-application` component.

**Comment by jrhorn424** [comment]
Chris and I worked with Shireen. @shkherad Please add notes when you get to a stopping point.

**Comment by shireen-bean** [comment]
SOLUTION:

On the component:
1. Define an Ember computed property
(since computed properties return a promise and may not reseolve before the action is sent)
2. Action: {
get computed property
.then( sendAction with the computed property) 
}

Here is the code:

**Component.js:**

define computed property:

```
profile: Ember.computed('user.id', function () {
    return this.get('store').queryRecord('profile', { user: this.get('user.id')});
  }),
```

^Ember computed property queries for the correct profile by using the user id.

action:

```
add () {
      this.get('profile').then((profile) => {
        this.sendAction('add', this.get('recipe.id'), profile.id);
      });
    }
```

And now both parameters are passed up a level with the action 'add'

Thanks @jrhorn424  and @payne-chris-r
