### ISSUE TITLE
Ruby method returning nil

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/capstone-project#233]
I created a custom route to display all beers that do not belong to the user (see everyone else's beers!), and I'm trying to create a method for that route.  To look up a user, you will need to go to the tried_beers join table to access the profiles who have tried x beers.  My method is returning nil, though.  

My thought process is 
Find all of the profile_ids through the tried_beers join table
If the profile_id != current_user.profile.id, then select all of the beers

Here's what I have:

```
other_beers = @tried_beers.where(TriedBeer.find(params[:profile_id]) != current_user.id)
@beers = Beer.select(other_beers)

render json: @beers
```

This keeps returning nil, though.

**Comment by jrhorn424** [comment]
```
other_beers = @tried_beers.where(TriedBeer.find(params[:profile_id]) != current_user.id)
```

I'm not sure this (`.find(params[:profile_id]) != current_user.id`) works in ActiveRecord. Can you show me the SQL this generates? It should in the log.

**Comment by andreasantarl** [comment]
AUTH token was not being sent with request- required because current_user needed to get set as query params.  Need to add custom route to controller actions.  Needed to add filter to before_action :authenticate

``` ruby
# edited by @jrhorn424 - please use "preview" to ensure correct format of your issue
  def allbeers # rename me
    @beers = Beer.where(id: TriedBeer.where.not(profile: current_user.profile))
    render json: @beers
  end
```
