### ISSUE TITLE
Data wont render in nested template

### ISSUE THREAD

**Issue by lcurran** [ga-wdi-boston/capstone-project#234]
Route is search/results, where I want the result data to render inside the search template. The data is visible in the store.

Search template:

```
<h3>Search for games</h3>

{{search-input keyword=keyword}}

{{#link-to "search.results" (query-params search=keyword)}}
<button type="submit" class="btn btn-primary">
  Search
</button>{{/link-to}}

<h4>Search Results</h4>
{{outlet}}
```

Search.results template:

```
{{all-games games=model}}
```

all-games component:

```
{{#each games as |game|}}
    {{game-thumbnail game=game}}
 {{/each}}
```

**Comment by jrhorn424** [comment]
Can I see the route for `search.results`?

Also, I wonder whether you need a `type` on your button.

``` diff
{{#link-to "search.results" (query-params search=keyword)}}
- <button type="submit" class="btn btn-primary">
+ <button class="btn btn-primary">
  Search
</button>{{/link-to}}
```

**Comment by jrhorn424** [comment]
Also, does this help? https://www.foraker.com/blog/creating-a-better-search-experience-with-ember

**Comment by lcurran** [comment]
search.results route

```
export default Ember.Route.extend({

  model (params) {
    this.get('store').query('catalog', params);
  }
});
```

search.results controller:

```

export default Ember.Controller.extend({
  queryParams: ['search'],
  search: null
});
```

I found that article in my googling, and I think my route is essentially set up in the same way now. The request is working, its just the rendering the data in the template that isn't working right now.

**Comment by jrhorn424** [comment]
Solution:

``` diff
  model (params) {
-    this.get('store').query('catalog', params);
+    return this.get('store').query('catalog', params);
  }
```
