### ISSUE TITLE
get.('store').query() seems to be returning every single item instead of properly filtering

### ISSUE THREAD

**Issue by erinsul** [ga-wdi-boston/capstone-project#235]
I may be passing it the wrong things, or I just might not be able to use it.

Anyway, I was trying to institute a "search" function in which a user can enter the name of a place, and that place alone will be returned. I have a form in a component:

<form {{action "search" on="submit"}}>
  <label for="name">Name of Place:</label>
  {{input type="text"
        placeholder="Place name"
        value=name}}
  <input type="submit" value="Search">
</form>

that passes an action to pass the name up to a route
export default Ember.Component.extend({
  actions: {
    search() {
      console.log(this.get('name'));
      this.sendAction('search', this.get('name'));
    }
  }
});

where it transitions to another route
export default Ember.Route.extend({
  actions: {
    search(name) {
        this.transitionTo('search.search', name);
    }
  }
});

that is supposed to take the name that's passed and return objects that match that name

export default Ember.Route.extend({
  model(name) {
    console.log(name.id);
    this.get('store').query('place', {
  filter: {
    name: name.id
  }
}).then(function(result) {
    console.log(result);
    console.log(result.objectAt(0));
    console.log(result.objectAt(4).get('data'))
    return result.objectAt(0);
    });
  },
});

However, the "result" that get.('store).query returns appears to be an array of every single "place" instead of ones whose name matches.

I'm not sure if I'm using get.('store').query wrong, or what. Or maybe there's just a better way to institute a search function that I haven't thought of.

**Comment by jrhorn424** [comment]
@erinsul I mentioned this in one of your previous issues. Please format your code correctly using github-flavored markdown fenced code blocks. I'll continue debugging once you've done so.

**Comment by jrhorn424** [comment]
@lcurran May be able to provide some insight into search functionality.

**Comment by lcurran** [comment]
I'm not sure but I think unless your index in rails is set up to handle a query if there is one, it will automatically return all of the results for place.  

I believe ember might be able to handle filtering on the front end for you if you make a controller, see https://guides.emberjs.com/v2.7.0/routing/query-params/

otherwise my suggestion would be to alter your index in rails to fetch results by param if there is one.

**Comment by jrhorn424** [comment]
#234 and #231 deal with using the `query` and `queryRecord` methods.

**Comment by erinsul** [comment]
I had seen #234, but couldn't interpret the code based on what I was doing.

I'll check out the back end, though, because I doubt I have it set up correctly. Thanks, Lindsey!

**Comment by jrhorn424** [comment]
@erinsul Any news?

**Comment by erinsul** [comment]
I fixed it. I refactored the code based on the article linked on #234 https://www.foraker.com/blog/creating-a-better-search-experience-with-ember. This still didn't fix it, on its own, though. The largest problem was the lack of route to deal with it on the back end, so after I fixed that, it worked.

`  def index
    if params[:name]
      @places = Place.where(name: params[:name].capitalize)
    else
      @places=Place.all
    end

```
render json: @places
```

  end`
