### ISSUE TITLE
using ember pikaday

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/capstone-project#236]
I am trying to use an ember addon for selecting a date: 

https://github.com/edgycircle/ember-pikaday

I did: `ember install ember-pikaday` in my ember client directory.

I am not sure how to actually import it.

Once it is imported, I can use their documentation to use the component in my templates e.g.

   `{{pikaday-input onSelection=(action 'doSomethingWithSelectedValue')}}`

**Comment by MishaHerscu** [comment]
I tried this in the component file but it fails:

```
import Ember from 'ember';
import pikaday from 'ember-pikaday'

export default Ember.Component.extend({


  actions: {
    submit () {
      console.log('submitting');
  },
    cancel () {
      console.log('cancelling');
  },
});
```

**Comment by jrhorn424** [comment]
Did you try just doing it in the template as the readme suggested?

<img width="855" alt="edgycircle_ember-pikaday__a_datepicker_component_for_ember_cli_projects_" src="https://cloud.githubusercontent.com/assets/388761/17380392/f2d171e4-5994-11e6-900b-7f763a6f372a.png">

**Comment by MishaHerscu** [comment]
okay thanks, i am now seeing an error:

```
ember.debug.js:16591Uncaught Error: Assertion Failed: A helper named 'pikaday-input' could not be found
```

Do I have to import/include it somewhere? It is already installed

**Comment by MishaHerscu** [comment]
may have something to do with bound helpers

**Comment by jrhorn424** [comment]
I'll dig into their docs and code for a few minutes.

**Comment by MishaHerscu** [comment]
Actually nvm, this isn't worth obsessing over. I'm just using regular date inputs. Thanks for spending some time looking at this though.
