### ISSUE TITLE
Access  id on joint table

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/capstone-project#237]
I need to access the id that rails creates on my joint table. After talking to Brian, We created a custom method in my controller of my joint table:

![image](https://cloud.githubusercontent.com/assets/13932794/17380372/df96e1a4-5994-11e6-94d1-cfa2a4e22922.png)

and added the route 

![image](https://cloud.githubusercontent.com/assets/13932794/17380390/eeb43de4-5994-11e6-84e9-eff1bb7bc6ed.png)

Now I will do an ajax GET request to that route to get the id back. After that I will PATCH.

**Comment by jrhorn424** [comment]
@esthercordova Is this a report or a request for help? Thanks.

**Comment by esthercordova** [comment]
How will the full route be?

![image](https://cloud.githubusercontent.com/assets/13932794/17380902/50268ad0-5997-11e6-874a-5e3eda573925.png)

Do I pass the question id or user id after: '/user_questions/find/' ?

**Comment by esthercordova** [comment]
![image](https://cloud.githubusercontent.com/assets/13932794/17380677/5004679e-5996-11e6-8302-693a9c80c2e4.png)

**Comment by payne-chris-r** [comment]
Esther, did you find a solution to this? Please post and close if you have!

**Comment by esthercordova** [comment]
You have to pass the user_question table id that was created by rails. Managed to access it:

![image](https://cloud.githubusercontent.com/assets/13932794/17403760/21f5eac6-5a27-11e6-9403-6ce8dbeaa573.png)
