### ISSUE TITLE
Trouble deploying Ember app to gh-pages

### ISSUE THREAD

**Issue by RoobScoobs** [ga-wdi-boston/capstone-project#238]
After following the steps in the deployment guide, I ended up with a blank client page. The console returns a "failed to load resource: the server responded with a status of 404 (Not Found)" error

You can visit the url:  https://roobscoobs.github.io/coverart-client/

I successfully deployed the api to heroku, and in the ember client I pointed it to the corresponding url. I imported the api host link in both the application/adapter and ajax/service file. Everything was committed on master. I created a local gh-pages branch and from there I removed the /dist from the gitignore file. I added and committed this change followed by running the ember build command. After that was completed I added all the dist files, and finally used the subtree push command.

**Comment by berziiii** [comment]
In the config file, under ENV=production, what is the ENV.location set as? Supposed to be "hash". Also, did you replace all instances of 'ga-wdi-boston.ember-auth' with your name 'coverart-client'?

**Comment by RoobScoobs** [comment]
Cool, I'm going to force delete the local and remote Gh-pages branch and run through the steps again

**Comment by RoobScoobs** [comment]
So went through the process again and the result is the same. I'm not changing the location type in the test environment to "hash" am I?

**Comment by payne-chris-r** [comment]
Just talked to Ruben, and he thinks he's back on track.

**Comment by RoobScoobs** [comment]
Carefully re-read the directions and resolved the issue. I was putting 

``` js
 ENV.baseURL = '/';
 ENV.locationType = 'hash';
 ENV.apiHost = '<% replace with the URL to your deployed API %>'
```

in the development rather than the production environment
