### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by tina513** [ga-wdi-boston/capstone-project#239]
Hey, I keep getting weird error message about module not found, please help~ Thanks~
I have already "npm install paper" ~

![screen shot 2016-08-04 at 12 16 11 am](https://cloud.githubusercontent.com/assets/19153756/17390195/bfb4c9de-59d8-11e6-85d4-fc8286230bc9.png)

**Comment by tina513** [comment]
Ok~ I closed server and npm install, and every thing works~

**Comment by jrhorn424** [comment]
For anyone referencing this in the future, you have to restart ember to pick up new modules. So if you `npm install`, `bower install`, or `ember install`, restart the server.
