### ISSUE TITLE
Having trouble getting Web sockets to work when client and server are separated

### ISSUE THREAD

**Issue by mkutter72** [ga-wdi-boston/capstone-project#24]
I am using http://socket.io/ to implement chat in my project 4.    The demo is working it is implemented by the server serving up the index.html back to the client:
app.get('/', function(req, res){
  res.sendfile('index.html');
});

This is not the model I want to use.   I've chaning  the implementation of the index.html file so that will the client can be separate from the server:
      var socket = io();

```
  socket.connect('http://localhost:3000');
```

I have status message printed when a client connects to the server.  I don't see that and
I am getting error messages with client is polling:
GET http://file/socket.io/?EIO=3&transport=polling&t=1450194190760-3 net::ERR_NAME_NOT_RESOLVED

**Comment by gaand** [comment]
The URL in your GET request appears malformed.  The hint is ERR_NAME_NOT_RESOLVED
