### ISSUE TITLE
Reload page in component doesn't maintain data

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/capstone-project#240]
This should be a quick thing. I am just missing something about Ember.

When I pass data to a component, it renders fine. BUT if I then refresh the page the data is gone, even though the URL has the id still. I think the reason is that I am just using data passed in, I don't have any query to the store when the component is rendered. Where does that code go? Is it something in the component.js for the component?

Thanks

**Comment by jrhorn424** [comment]
You're missing a `return` in a `model` hook somewhere.

**Comment by MishaHerscu** [comment]
How sure are you of that? I can't find a missing one. I think it may be because the component doesn't have a way of getting data when I refresh the page rather than getting to the component through a route. Can I show you the code?

**Comment by jrhorn424** [comment]
Yes, you can show me. The component should not need to fetch data as long as you're binding it correctly from the route down to the target component. That's what the bindings are for.

**Comment by MishaHerscu** [comment]
Okay, thanks. Yeah, it is what I thought, I must be messing up the binding somehow. I'll come find you.

**Comment by MishaHerscu** [comment]
Solution: I was in a route that was for an individual item rather than items, but I had been using findAll instead of findRecord in the model hook.
