### ISSUE TITLE
PATCH request doesn't go through

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/capstone-project#241]
![image](https://cloud.githubusercontent.com/assets/13932794/17403815/5410940c-5a27-11e6-805d-89ede119df2e.png)

I am trying to update a variable on my joint table with the following ajax request:

![image](https://cloud.githubusercontent.com/assets/13932794/17403868/8ed1423a-5a27-11e6-847d-582933ff7ea7.png)

I think I have all the necessary variables to make a patch request but it doesnt  go through.
This is my function that invokes the ajax request:

![image](https://cloud.githubusercontent.com/assets/13932794/17403901/bd1c367c-5a27-11e6-8707-39b424578742.png)

I console.log everything and it seems to be correct. I also checked with the with rails db and I think I have everything I need. What am I missing?

**Comment by jrhorn424** [comment]
What is the output in the rails log when you try this request? The error you see in your web console is a general error and it could mean a bunch of different things.

**Comment by jrhorn424** [comment]
Your promise never uses resolve. You also misspelled `resolve`.

**Comment by esthercordova** [comment]
![image](https://cloud.githubusercontent.com/assets/13932794/17404091/89a4f594-5a28-11e6-9b44-04be39714c72.png)

**Comment by jrhorn424** [comment]
`question_id` and `user_id` are out of scope. @payne-chris-r can you confirm?

**Comment by jrhorn424** [comment]
Question 15 is not available according to your error message.

**Comment by jrhorn424** [comment]
The foreign key constraint violation is telling you that you're trying to insert a row into the join table with a value for `question_id` of 15, but Postgres can't find a row in the `questions` table with an `id` of 15.

**Comment by esthercordova** [comment]
I don't know why its looking for id 15. It's switched it's user 15 question id 1. When I console.log its saved right.

**Comment by jrhorn424** [comment]
They appear to be exactly switched in the error output.

**Comment by jrhorn424** [comment]
Your signature is wrong when you define `changeQuestionStatus`. Count the argument positions, specifically arguments index 1 and index 2.

**Comment by esthercordova** [comment]
Thanks Jeff, I'm looking at it so much... Don't know why I missed it for so long.
