### ISSUE TITLE
Created albums missing ID until page is refreshed

### ISSUE THREAD

**Issue by RoobScoobs** [ga-wdi-boston/capstone-project#242]
Hey guys, 

Upon creating a new album the id is absent, but once you refresh the page the id magically appears!

<img width="512" alt="screen shot 2016-08-04 at 10 52 15 am" src="https://cloud.githubusercontent.com/assets/16338632/17406482/8d23121a-5a31-11e6-8630-b55da65d7cf2.png">

But then... after a refresh, it's indexed properly and given the ID

<img width="526" alt="screen shot 2016-08-04 at 10 52 51 am" src="https://cloud.githubusercontent.com/assets/16338632/17406505/a1a6977a-5a31-11e6-85c5-01ff3645771b.png">

**Comment by payne-chris-r** [comment]
Resolved, right scoops?

**Comment by RoobScoobs** [comment]
Yup, so the submit action in the new album form was sending a duplicate transitionTo that prevented the ID from being bounded to the data object. TransitionTo was already defined at the route level.
