### ISSUE TITLE
Heroku error- AWS region needs to be set

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/capstone-project#243]
I have no idea how to debug this.  When I am in my deployed app and try to upload a photo, I get a heroku error:

Aws::Errors::MissingRegionError (missing region; use :region option or export region name to ENV['AWS_REGION']):

Here's my production and dev.rb file code: 
  config.paperclip_defaults = {
  :storage => :s3,
  s3_region: ENV['AWS_REGION'],
  s3_credentials: {
    bucket: ENV['S3_BUCKET_NAME'],
    access_key_id: ENV['AWS_ACCESS_KEY_ID'],
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  }
}

Here's my .env info (with real info not included):

export S3_BUCKET_NAME='stuff'
export AWS_ACCESS_KEY_ID=workds
export AWS_SECRET_ACCESS_KEY=codes
export AWS_REGION='us-east-1'

Everything looks good to me, and I've checked StackOverflow for any similar issues, and it looks like my config is correct.  Help!

**Comment by berziiii** [comment]
Are you storing these variables in your heroku config set? If so, make sure you have a variable called AWS_REGION='us-east-1'

**Comment by andreasantarl** [comment]
I needed to add all of the AWS creds to the Heroku config dashboard.  Works now!  Thanks, Brian!
