### ISSUE TITLE
Ember request parameters for createRecord sending [Object object]

### ISSUE THREAD

**Issue by lcurran** [ga-wdi-boston/capstone-project#245]
for some reason ember is parsing the id correctly, but when it comes to any strings that I am accessing in my parameters, it sends an object with the post request.

params from error:

```
Request parameters
{"game"=>{"igdb_id"=>73,
 "name"=>"[object Object]",
 "summary"=>"[object Object]",
 "videos"=>nil,
 "cover"=>"[object Object]"},
 "format"=>"json"}
```

My createRecord action: 

```
addGame (game) {
      let newGame = this.get('store').createRecord('game', {
        igdb_id: game.id,
        name: game.name,
        summary: game.summary,
        cover: game.cover,
        video: game.video
      });
      newGame.save()
      .then((response) => {
        let lib = this.get('store').createRecord('library', {
          user_id: this.get('auth.credentials.id'),
          game_id: response.id,
        });
        lib.save();
      });
    }
```

**Comment by payne-chris-r** [comment]
Have you tried to add strings together at all? Usually when I see [object Object] I've tried to add a string and an object. `"sample string " + sampleObj` => `"sample string [object Object]"`

**Comment by lcurran** [comment]
Nope, I'm accessing data from the model that has been passed up with the action from the component. I didn't manipulate the data at all until I assigned it in the createRecord request.

**Comment by lcurran** [comment]
bumping because google isn't helping, and this one issue is kinda the one thing preventing me from being feature complete. Sorry cause I know you guys are busy but halp. @payne-chris-r  @jrhorn424 @berziiii

**Comment by payne-chris-r** [comment]
^ Needed to be using `.get` instead of dot-notation for `game.name`
