### ISSUE TITLE
Trouble deploying to gh-pages after heroku deployment

### ISSUE THREAD

**Issue by modularjon** [ga-wdi-boston/capstone-project#247]
I deployed to heroku and was able to have my front end, running from localhost:8080, speak to heroku fine. After deploying to gh-pages, I now get this error:

Console error is: XMLHttpRequest cannot load https://dot-matrix.herokuapp.com/sign-in. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://modularjon.github.io' is therefore not allowed access.
2016-08-04 13:36:27.190 vendor.

I changed my CLIENT_URL variable in the .env file, but since it is .gitignored, how do I get heroku to recognize it?

**Comment by payne-chris-r** [comment]
Had you pushed to github pages previously?

**Comment by modularjon** [comment]
Not before deploying to heroku. I did delete the gh-pages remote once and then push my local gh-pages.

**Comment by modularjon** [comment]
The solution to this issue was altering CLIENT_URL in heroku to only the root of the client url.
So for example https://modularjon.github.io, not https://modularjon.github.io/my-repository-name.
That is the 'origin' manifesting in the error message.

**Comment by modularjon** [comment]
I need to qualify who this applies to. This issue is relevant only to the newest rails template. If you are using a previous template that doesn't include this origins code for config/appilcation.rb:

```
config.middleware.use Rack::Cors do
  allow do
    origins ENV['CLIENT_URL'] || 'http://localhost:8080'
```

you need not worry about it.
