### ISSUE TITLE
Can't access user controller

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/capstone-project#248]
In order to delete my profile I need the profile Id. Therefor I am making a get request in a promise followed by the api. delete. I need to pass the profile Id for the delete action but I am not able to access the information.

When I console.log  app I am getting this data:

![image](https://cloud.githubusercontent.com/assets/13932794/17416505/6a204640-5a5c-11e6-920a-804b80274cdc.png)

**Comment by berziiii** [comment]
@esthercordova please provide the solution to how we were able to access profile through user and the result. Thanks.
