### ISSUE TITLE
Issue trying to upload image to S3 using paperclip

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/capstone-project#249]
I followed the Heroku docs to set up the API and an input for the file.

The error I am seeing is that instead of a file getting to my Rails API, I am just getting a string:

`"C:\\fakepath\\profile_picture.jpg"}}`

This results in an error on the server:

`Paperclip::AdapterRegistry::NoHandlerError (No handler found for "C:\\fakepath\\profile_picture.jpg"):
`

and an error in the console:

```
XMLHttpRequest cannot load http://localhost:3000//sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 
```

**Comment by MishaHerscu** [comment]
My input is all inside of a form and it is submitting because I see the other fields in the server console.

I think the problem is that I am not using FormData properly, but I haven't been able to figure out where it goes in Ember for a while.

Also,

the form has the right attributes I think:

`<form enctype='multipart/form-data'>`

**Comment by MishaHerscu** [comment]
btw this is my user model. the attachment is owned by a user:

```
import DS from 'ember-data';

export default DS.Model.extend({
  email: DS.attr('string'),
  trips: DS.hasMany('trip'),
  attendances: DS.hasMany('attendance'),
  givenName: DS.attr('string'),
  surname: DS.attr('string'),
  avatar: DS.attr('file'),
});

```

**Comment by MishaHerscu** [comment]
back end:

my create_users migration:

```
#
class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :email, null: false, index: { unique: true }
      t.string :token, null: false, index: { unique: true }
      t.string :password_digest, null: false
      t.boolean :admin, null: false
      t.string :given_name
      t.string :surname
      t.attachment :avatar

      t.timestamps null: false
    end
  end
end

```

resulting user schema:

```
  create_table "users", force: :cascade do |t|
    t.string   "email",               null: false
    t.string   "token",               null: false
    t.string   "password_digest",     null: false
    t.boolean  "admin",               null: false
    t.string   "given_name"
    t.string   "surname"
    t.string   "avatar_file_name"
    t.string   "avatar_content_type"
    t.integer  "avatar_file_size"
    t.datetime "avatar_updated_at"
    t.datetime "created_at",          null: false
    t.datetime "updated_at",          null: false
  end
```

**Comment by MishaHerscu** [comment]
config/environments for prod and dev have:

```
  config.paperclip_defaults = {
    storage: :s3,
    s3_credentials: {
      bucket: ENV.fetch('S3_BUCKET_NAME'),
      access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
      secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'),
      s3_region: ENV.fetch('AWS_REGION')
    }
  }
```

**Comment by MishaHerscu** [comment]
note: i do have .env with the correct things, and heroku with the correct things (i think)

**Comment by MishaHerscu** [comment]
user controller has:

```

  def user_creds
    params.require(:credentials)
          .permit(:email, :password, :password_confirmation, :given_name,
                  :surname, :avatar)
  end
```

**Comment by MishaHerscu** [comment]
back end user model:

```
#
class User < ActiveRecord::Base
  include Authentication
  has_many :examples, inverse_of: :user, dependent: :destroy
  has_many :attraction_suggestions, inverse_of: :user, dependent: :destroy
  has_many :user_tags, inverse_of: :user, dependent: :destroy
  has_many :user_attractions, inverse_of: :user, dependent: :destroy
  has_many :trips, inverse_of: :user, dependent: :destroy
  has_many :attendances, inverse_of: :user, dependent: :destroy

  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  validates_attachment_content_type :avatar, content_type: %r{/\Aimage\/.*\Z/}
end

```

**Comment by MishaHerscu** [comment]
anyway - let me know if there is something in the back end that looks like it doesn't match the front end. I am pretty confident though that the issue is that I am not successfully using FormData on the front end. 

Do I need to use something like this?
https://www.npmjs.com/package/ember-cli-form-data

**Comment by MishaHerscu** [comment]
Misha Herscu [7:58 PM]  
i think i am very close to getting the paperclip to work with ember

[7:58]  
can i ask you something for like 30 seconds?

[7:58]  
i’m sorry, i know you have been trying to help jacob for a long time and are probably frustrated

[7:59]  
i put a form into another form, and when you submit the outer form, with text fields, it actually submits the inner FormData file form, saves that to the outer form object and then submits the whole thing

[7:59]  
so i have everything i want in an object

[8:00]  
console logged in auth

[8:00]  
but it just doesn’t send the POST request when the image is in the object (edited)

[8:00]  
the server shows nothing

**Comment by jrhorn424** [comment]
Did you ever work on this further?

**Comment by MishaHerscu** [comment]
No - I may revisit this later, but I'll probably use the plugin Sarah used which let her upload images in the same tech stack (Ember, Rails, Postgres)

**Comment by MishaHerscu** [comment]
I removed everything about image uploads from the project for now. Once I have everything else working I'll try to give users profile pictures.

**Comment by RealWeeks** [comment]
Closed for cohort 013
