### ISSUE TITLE
Help with third party api

### ISSUE THREAD

**Issue by atsundwn** [ga-wdi-boston/capstone-project#25]
I am trying to use third-party api, "Authy" to have 2-factor authentication.  However, my smaller problem is making an xhr request within the back-end.  I am using Rails as a backend.

**Comment by gaand** [comment]
You can use HTTParty (or similar - depending on specific needs) to make HTTP requests from rails.

**Comment by srhoulam** [comment]
You don't make XHRs (AJAX requests) from the back-end. You make ordinary HTTP requests. See above ^

**Comment by atsundwn** [comment]
OK Will try.
