### ISSUE TITLE
Minor edit: suggestions are copied from group project, see here:

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/capstone-project#250]
Be consistent with your code style. You're working in teams, but you're only making one app per team. Make sure it looks like a unified effort.

**Comment by jrhorn424** [comment]
@MishaHerscu I'm confused. Should this be tracked over at group project?

**Comment by MishaHerscu** [comment]
Sorry, I should have been more clear. Search the README.md file for the capstone project for the text I put above:

"Be consistent with your code style. You're working in teams, but you're only making one app per team. Make sure it looks like a unified effort."

It is there under "Suggested ways to get started".

I think it is from copying and pasting from the group project readme, since the capstone is not a group project.

Does that make sense?

**Comment by laurenfazah** [comment]
Thanks for this catch @MishaHerscu. Fixed and updated.
