### ISSUE TITLE
Access-Control-Allow-Origin error

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/capstone-project#254]
I'm getting this error in my dev tools when trying to sign up with the ember auth template.  
My back-end server is saying 200 ok. 
I don't have "https" in my localhost links.
I can't seem to figure out what it is that's causing it. 
I'm aware that this error can mean multiple different things, but I'm not sure where to go even after looking things up.

```
XMLHttpRequest cannot load http://localhost:3000/sign-in. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.
```

**Comment by laurenfazah** [comment]
Did you start your client server with a proxy or configure your API host on Ember's end?

**Comment by jlmitch1989** [comment]
The latter. 

for the back end:

```
origins ENV['CLIENT_ORIGIN'] || 'http://localhost:4200'
```

for ember:

environment.js

```
    apiHost: 'http://localhost:3000',
```

ajax/service.js

```
import ENV from '../config/environment';

&

 host: ENV.apiHost,

```

**Comment by RealWeeks** [comment]
are you sending the data in the correct format?

**Comment by RealWeeks** [comment]
Have you check other closed issues? there seem to be a number pertaining to this issue.

**Comment by jlmitch1989** [comment]
I mean I haven't touched any of the user stuff on the front end or the back end.  I'll take a better look at the closed issues.

**Comment by jlmitch1989** [comment]
After looking through the issues, I didn't find anything which helped me figure out my issue.  I made sure that all the data for users being passed on the front to the backend was the same and it is.  Again, I didn't touch anything dealing with user data.   So I am not sure where to look next.

**Comment by gaand** [comment]
Is there an error before the CORS error in your console?

**Comment by jlmitch1989** [comment]
No, this is all that is in my console.  

```
XMLHttpRequest cannot load http://localhost:3000/sign-in. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.
jquery.js:9175 XHR failed loading: POST "http://localhost:3000/sign-in".send @ jquery.js:9175ajax @ jquery.js:8656(anonymous function) @ ajax.js:114initializePromise @ ember.debug.js:53856Promise @ ember.debug.js:55708request @ ajax.js:89post @ ajax.js:120signIn @ service.js:22signIn @ route.js:10triggerEvent @ ember.debug.js:28580trigger @ ember.debug.js:53473trigger @ ember.debug.js:52232send @ ember.debug.js:28045send @ ember.debug.js:32723triggerAction @ ember.debug.js:36297sendAction @ ember.debug.js:41731submit @ component.js:10send @ ember.debug.js:41747superWrapper @ ember.debug.js:23110runRegisteredAction @ ember.debug.js:29633run @ ember.debug.js:678run @ ember.debug.js:21139handler @ ember.debug.js:29627(anonymous function) @ ember.debug.js:44705dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
VM847:87 Ember Inspector Active
VM847:282 'window.postMessage(message, transferables, targetOrigin)' is deprecated and will be removed in M54, around October 2016. Please use 'window.postMessage(message, targetOrigin, transferables)' instead. See https://www.chromestatus.com/features/5719033043222528 for more details.
```

**Comment by jlmitch1989** [comment]
Apparently, Gabe is also having this issue.

**Comment by jlmitch1989** [comment]
When we use a proxy it works it works.

**Comment by gaand** [comment]
What do you mean by "use a proxy"?

**Comment by jlmitch1989** [comment]
when I run 

```
ember serve --proxy http://localhost:3000
```

instead of telling the front end and back end which ports they are running on.

**Comment by RealWeeks** [comment]
@jlmitch1989 I think that's what @laurenfazah was telling you to do.  This is the correct solution.

**Comment by gaand** [comment]
Is apiHost set in ENV at the start, or one of the environment if statements?

**Comment by jlmitch1989** [comment]
On my frontend, this is how I had it set up.  I commented them out to run the proxy.  But when they weren't commented out nothing was working. 

service.js file:

``` js
import Ember from 'ember';
import AjaxService from 'ember-ajax/services/ajax';
// import ENV from '../config/environment';

export default AjaxService.extend({
  // host: ENV.apiHost,
  auth: Ember.inject.service(),
  headers: Ember.computed('auth.credentials.token', {
    get () {
      let headers = {};
      const token = this.get('auth.credentials.token');
      if (token) {
        headers.Authorization = `Token token=${token}`;
      }

      return headers;
    },
  }),
});

```

config/enviroment.js

``` js
module.exports = function(environment) {
  var ENV = {
    // apiHost: 'http://localhost:3000',
    modulePrefix: 'ember-typeone',
    environment: environment,
    baseURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },
```

**Comment by gaand** [comment]
I'd like to look this over in a few.

**Comment by jlmitch1989** [comment]
alrigthy.

**Comment by jlmitch1989** [comment]
I was missing things in my application/adapter.js file.
Added this:

``` js
import ENV from 'ember-typeone/config/environment';

host: ENV.apiHost,
```

then I restarted all my servers. And it was fixed!  Thanks!
