### ISSUE TITLE
Github issue

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/capstone-project#255]
I can't seem to push my commits up to Github. I have made changes that I don't have locally. Now that is causing conflict. There is a lot of going on. 

Can anyone please take a look?

**Comment by gaand** [comment]
@NatasaPeic would you please post a solution?  Thanks!

**Comment by NatasaPeic** [comment]
Force push was solution in my case since my local version was up to date.

Thank you.
