### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by dvdpwll** [ga-wdi-boston/capstone-project#256]
I've been getting this error after I finished deploying my ember front end.

```
XMLHttpRequest cannot load http://localhost:3000/sign-in. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.
```

I talked with josh and I have all of the changes that he said I should have.
application/adapter.js

``` js
import ActiveModelAdapter from 'active-model-adapter';
import ENV from 'dvdpwll.FreeTime-Front-End/config/environment';

export default ActiveModelAdapter.extend({
  host: ENV.apiHost,
```

ajax/service.js

``` js
import AjaxService from 'ember-ajax/services/ajax';
import ENV from 'dvdpwll.FreeTime-Front-End/config/environment';

export default AjaxService.extend({
  host: ENV.apiHost,
```

config/environment.js

``` js
  var ENV = {
    modulePrefix: 'dvdpwll.FreeTime-Front-End',
    environment: environment,
    baseURL: '/',
    locationType: 'auto',
    apiHost: 'http://localhost:3000',
    // apiHost: 'https://fathomless-coast-53196.herokuapp.com/',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },
```

rails - config/application.rb

``` rb
        origins ENV['CLIENT_ORIGIN'] || 'http://localhost:4200'
```

**Comment by RealWeeks** [comment]
Before we get started have you checked closed issues for a solution?

**Comment by dvdpwll** [comment]
i checked josh's

**Comment by RealWeeks** [comment]
Check others and see if there are solutions from previous classes. I haven't gone through all of them but there are a lot of closed issues with this same problem.

**Comment by dvdpwll** [comment]
hmm, I've only found three
[Access-Control-Allow-Origin error](https://github.com/ga-wdi-boston/capstone-project/issues/254)
[No 'Access-Control-Allow-Origin' header is present on the requested resource](https://github.com/ga-wdi-boston/capstone-project/issues/229)
[No 'Access-Control-Allow-Origin' error when making a POST request to join table](https://github.com/ga-wdi-boston/capstone-project/issues/206)

**Comment by dvdpwll** [comment]
and josh's was the only one relevent

**Comment by RealWeeks** [comment]
@laurenfazah and @gaand any quick hits from looking at the code here?

**Comment by laurenfazah** [comment]
This is an issue when deployed? Your production environment config is different from what's shown above (you correctly posted code for your local API configuration). Did you follow those instructions from the deployment steps?

**Comment by laurenfazah** [comment]
Specifically for this section of config/environment.js:

``` js
if (environment === 'production') {
  ENV.baseURL = '/';
  ENV.locationType = 'hash';
  ENV.apiHost = '<% replace with the URL to your deployed API %>'
}
```

**Comment by dvdpwll** [comment]
i have successfully deployed and it works. Now I want to go back and work locally but I'm getting the no access error

**Comment by laurenfazah** [comment]
Ah, I see. Have you started your ember server with a proxy?

**Comment by dvdpwll** [comment]
well, i was trying to do it w/o proxy cuz antony said to.
But I commented out all of the changes I made and went back to using proxy.
It works now, so I guess it's fine.

**Comment by dvdpwll** [comment]
closing issue?

**Comment by laurenfazah** [comment]
Oh my question wasn't leading you to use it. If you want to troubleshoot still, feel free to reopen. Otherwise, go forth and code.

**Comment by dvdpwll** [comment]
I think it's fine for now, I'll reopen if it becomes an issue.
