### ISSUE TITLE
LoadError: cannot load such file after requiring a gem.

### ISSUE THREAD

**Issue by alex-braun** [ga-wdi-boston/capstone-project#257]
I am trying to use a gem, httparty, in order to send GET requests to a 3rd party API.  I'm trying to do this from my rails backend.  This is the error in the command line when I try to make any calls to my backend:

```
LoadError: cannot load such file -- /Users/Alex/wdi/projects/ShowHock-Api/app/lib/httparty
from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
```

running `gem which httparty` tells me where my gem is installed:

```
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty.rb
```

My error is NOT saying that it cannot find the file, so I assume it is finding it but is not loading for some reason.

I'm requiring it at the top of my models file, per usual.

```
require 'httparty'
```

Some advice would be very nice.  Thank you.

**Comment by RealWeeks** [comment]
is this the gem you're using? https://github.com/jnunemaker/httparty

are you requiring it the right way?

**Comment by laurenfazah** [comment]
At first glance, I don't have an idea of what could be going on, but making a GET request to a 3rd party API is actually pretty easy if you require the `net/http` Class in Ruby.

http://ruby-doc.org/stdlib-2.3.1/libdoc/net/http/rdoc/Net/HTTP.html

Their docs have a bunch of examples, too.

**Comment by alex-braun** [comment]
Jason, I see that they include HTTParty, but I tried that and it didn't work for me either.  I tried using net/http earlier and I couldn't quite understand where these commands should be called.  It sounds like within the model is best. Would that be better than making calls from the controller?

**Comment by laurenfazah** [comment]
That should all be in controller. Something like:

```
class StrainsController < OpenReadController
  require 'net/http'
  before_action :set_strain, only: [:update, :destroy]

  # GET /strains
  # GET /strains.json
  def index
      @strains = current_user.strains
    render json: @strains
  end

**Comment by laurenfazah** [comment]
`net/http` stuff should go in a controller. Something like:

```
class ExamplesController < OpenReadController
  require 'net/http'
  before_action :set_example, only: [:update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
    uri = URI('https://example.com/examples')
    res = Net::HTTP.get_response(uri)

    @examples = res.body

    render json: @examples
  end
end
```

**Comment by alex-braun** [comment]
OK!  I created that request as Lauren suggested from the controller and not the model, and I am successfully making requests.  Thank you! 

This is using Ruby's net/http library.  I abandoned my attempt at using httparty.

**Comment by laurenfazah** [comment]
Cool! If solved, could you close? If you have follow up questions, please feel free to post.
