### ISSUE TITLE
Ember action handlers

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/capstone-project#258]
I have incorrectly set up my action handlers for editing/creating a user profile.
I have it set up so that on Sign-up that the profile form loads with a promise and used transitionTo to load the profile form.
I have traced up and down the ember tree, and feel like I would benefit from some help with where I crossed my wires, I feel like this might be something better to do in person, but on the off-chance I am mistaken I am submitting an issue. When I navigate to profiles/:profile_id I am able to see all the information that I entered using a curl request but I am unable to interact on the front end to provide the same information and this issue is keeping me from moving forward.

**Comment by laurenfazah** [comment]
Are you saying you cannot POST profile information? 

If so, could you provide (in code) what you've done to post that info and also how you've modified your API to receive that info?

**Comment by natGalynker** [comment]
Yes that is correct. I am successful with GET but the action is not firing for post.

here is the component template for the action I am trying to fire:

```
<h1>Tweak Your Profile</h1>

<h4>Tell us About what brought you here</h4>

<div class="form-group">
  <label for="username">Name You Go By</label>
  {{input placeholder="Put the name you prefer to be called"
          type="text"
          id="username"
          value=profile.username}}
</div>

<div class="form-group">
  <label for="location">Location</label>
  {{input placeholder="Boston, MA etc"
          type="text"
          id="location"
          value=profile.location}}
</div>

<div class="form-group">
  <label for="motivation">Motivation</label>
  {{input placeholder="Tell us about what drives you"
          type="text"
          id="motivation"
          value=profile.motivation}}
</div>
<div class="form-group">
  <label for="favorite">Favorite Exercise Method</label>
  {{input placeholder="Tell us what is your go-to Exercise"
          type="text"
          id="favorite"
          value=profile.favorite}}
</div>
<button type="submit" class="btn btn-primary" {{action "submitProfile"}}>
Update Profile
</button>

<button class="btn btn-default" {{action "cancel"}}>
  Cancel
</button>
```

I have an submitProfile action here:

```
    submitProfile () {
      let profile = this.get('profile');
      this.sendAction('submitProfile', profile);
    },
  }
});
```

and inside of my profiles edit route I have a submit action which is saving the profile and transitioning to that users profile here:

```
  actions: {
    submit (profile) {
      profile.save();
      this.transitionTo('profile', profile);
    },
```

The POST requests aren't even hitting the api. It seems to be a wiring with the components. My guess would be incorrect naming conventions for the names of the different actions in the templates and the routes

here is the model from the ember data store it is expecting:

```
export default DS.Model.extend({
  location: DS.attr('string'),
  motivation: DS.attr('string'),
  favorite: DS.attr('string'),
  user_id: DS.attr(),
  username: DS.attr('string'),
  exercises: DS.hasMany('exercise')
});
```

I have attempted following the ember tree and its actions up the tree. I have tried changing the name of the form's actions to the name of the actions. When I interact with the API on its own through curl I am able to see that data associated with said users profile. Maybe I am misunderstanding what you mean  by modifying my API. 

I created a profiles table which has the following columns:

location
motivation
username
favorite exercise
user_id

**Comment by natGalynker** [comment]
The error I am getting when I click on either the reset or the submitProfile button

is respectively:

cannot read property id/save of undefined

I have changed these lines of code to produce this result:

in the create-profile's component

```
  actions: {
    submitProfile () {
      let profile = this.get('profile');
      this.sendAction('submitProfile', profile);
    },
  }
});
```

in the create profile template

```
<button type="submit" class="btn btn-primary" {{action "submitProfile"}}>
Update Profile
</button>

<button class="btn btn-default" {{action "reset"}}>
  Cancel
</button>
```

and in the 
route of the create:

```
  actions: {
    submitProfile (profile) {
      profile.save();
      this.transitionTo('profile', profile);
    },
```

inserted this line in the template of the create:

{profile-update submitProfile="submitProfile" reset="reset"}}

**Comment by laurenfazah** [comment]
Could you post your entire component.js?

A hint at what I'm getting at by asking for that: In your forms, your values all seem to be building a `profile` object, yes? Does that object exist? Then we can work towards figuring out the actual POSTing.

**Comment by natGalynker** [comment]
```
import Ember from 'ember';

export default Ember.Component.extend({
  tagName: 'div',
  classNames: ['form-group'],

  actions: {
    reset () {
      let profile = this.get('profile');
      this.sendAction('reset', profile);
    },

    submitProfile () {
      let profile = this.get('profile');
      this.sendAction('submitProfile', profile);
    },
  }
});
```

**Comment by natGalynker** [comment]
I created an object inside of component.js:

```
import Ember from 'ember';

export default Ember.Component.extend({
  tagName: 'div',
  classNames: ['form-group'],

  profile: {
    location: null,
    motivation: null,
    favorite: null,
    username: null,

},
```

**Comment by natGalynker** [comment]
Inside of the model.js of the profile I have listed those as the data to get. I am doing that successfully. Those display as a GET on the screen.

**Comment by laurenfazah** [comment]
Are your first two codeblocks from the same file?

**Comment by laurenfazah** [comment]
If so, do you remember what `sendAction` does in a component? Specifically in reference to these two actions:

```
    reset () {
      let profile = this.get('profile');
      this.sendAction('reset', profile);
    },

    submitProfile () {
      let profile = this.get('profile');
      this.sendAction('submitProfile', profile);
    },
  }
```

**Comment by natGalynker** [comment]
Yes, they are in the components.js

The sendAction is the action that triggers the component being loaded and which then bubbles up and allows that component to to do a specific action ie, a button that creates a new user

**Comment by laurenfazah** [comment]
Okay cool. So your component.js file looks okay here. Have you verified that the `submitProfile` action is sending the `submitProfile` action up to the route calling it?

**Comment by natGalynker** [comment]
Yes I have, I have verified this several times. This is the point that I keep getting stuck on and I am not sure what I am misunderstanding or doing wrong. I have double checked my notes, and my code. I have broken my code to test out the submitProfile action

**Comment by laurenfazah** [comment]
Can you show me both the route.js and template code for the route that loads the `create-profile` component? I want to see how the component is loaded and how the actions being sent up from the component are being handled.

**Comment by natGalynker** [comment]
```
import Ember from 'ember';
export default Ember.Route.extend({
  auth: Ember.inject.service(),

  actions: {
    submitProfile (profile) {
      profile.save();
      this.transitionTo('profile', profile);
    },

    cancel (profile) {
      this.get('store').unloadAll('profile');
      this.get('store').findRecord('profile', profile.id)
      .then((test) => {
        //this.get('store').unloadAll('profile');
        this.transitionTo('profile', test);
        console.log(test.id);
      });
    }
  }
});
```

{{create-profile submit="submit" reset="reset"}}

```
```

**Comment by laurenfazah** [comment]
Does this `{{create-profile submit="submit" reset="reset"}}` line up with the names of the actions you're sending up from the component?

**Comment by natGalynker** [comment]
I ended up going backwards, and have been able to communicate to the backend on the front end.
But now All the values are being send through as null/Nil

I changed the object from being set with null values to being set with implicit values. This changed the data tab only to have one entry to two and the only one holding valid data was the one which was preset but me in the component.js

**Comment by laurenfazah** [comment]
Could you post code at the point where the object you're trying to send via a POST request is null before going to your API?

**Comment by natGalynker** [comment]
I think it is here : that its being held up. I put a console log in to see what it was being passed through as and it is there that the null value is happening

```
        submitProfile(data) {
          let profile = this.get('store').createRecord('profile', data);
          console.log('batman');
          console.log(data);
           profile.save();

            },
```

**Comment by laurenfazah** [comment]
What do your console logs show?

**Comment by natGalynker** [comment]
```
 profile: {
      location: 'enter location',
      motivation: 'getting strong',
      favorite: 'yoga all day every day',
      username: 'thisExample',
    },


  actions: {
    cancel () {
      let profile = this.get('profile');
      this.sendAction('reset', profile);
    },
      submitProfile () {
        console.log('form sbmitted');
        this.sendAction('submitProfile', this.get('profile'));
  },
}
});

```

that is my component.js would them both be named submitProfile be an issue that didn't occur to me earlier.

and my console is logging batman and null

**Comment by laurenfazah** [comment]
Can you console log `this.get('profile')` in the component's `submitProfile` under `"form submitted"`

**Comment by natGalynker** [comment]
@laurenfazah  I was in the middle of testing it, when I realized I was in a detached head state, I have gotten out of that state, but now I am getting a favicon error. This might be an in person thing

**Comment by natGalynker** [comment]
we are good!

**Comment by natGalynker** [comment]
That log didn't hit

**Comment by natGalynker** [comment]
actually, it is it is just coming back null. So that is where the problem lies      

```
submitProfile () {
        console.log('form submitted');
        let message = this.get('profile');
        console.log(message);
          // this.sendAction('profile', params);
        this.sendAction('submitProfile', this.get('profile'));
```

**Comment by laurenfazah** [comment]
Favicon error is standard for our ember apps.

So logging `message` shows that it is null? But you are also seeing the log for `"form submitted"`, yes?

**Comment by natGalynker** [comment]
Correct, so that means that function is hitting but it doesn't know what profile is. So its not grabbing the data

**Comment by natGalynker** [comment]
I just followed listr-list actions up, and the data down from
and everything seems to be lining up. I had other people look at my code and they haven't said that there is anything wrong with it. I am so confused by this!!!

**Comment by laurenfazah** [comment]
Are you posting values into your text fields on submit?

**Comment by natGalynker** [comment]
Yes I am entering strings in as values

**Comment by laurenfazah** [comment]
Perhaps compare again with how Antony executed form submit with listr-list https://github.com/gaand/ember-resources/blob/013/training/app/components/listr-list/edit/template.hbs

**Comment by natGalynker** [comment]
I went through it again.

I removed all of the individual forms and since we defined the class type as a form nothing broke, but when I but on submit in the top form tag along with the button type being submit, it acts as though I need a prevent default. When I change the button type to a button it acts the same way as it has been working up until this point

**Comment by laurenfazah** [comment]
Please post entire template.hbs and component.js for this component.

**Comment by natGalynker** [comment]
```
<form {{action 'submitProfile' on='submit'}}>
  <label for="username">Name You Go By</label>
  {{input placeholder="Put the name you prefer to be called"
          type="text"
          id="username"
          value=profile.username}}
  <label for="location">Location</label>
  {{input placeholder="Boston, MA etc"
          type="text"
          id="location"
          value=profile.location}}
  <label for="motivation">Motivation</label>
  {{input placeholder="Tell us about what drives you"
          type="text"
          id="motivation"
          value=profile.motivation}}
  <label for="favorite">Favorite Exercise Method</label>
  {{input placeholder="Tell us what is your go-to Exercise"
          type="text"
          id="favorite"
          value=profile.favorite}}
<button type="button" class="btn btn-primary">
Update Profile
</button>

<button class="btn btn-default" {{action "cancel"}}>
  Cancel
</button>
</form>
```

**Comment by natGalynker** [comment]
```
import Ember from 'ember';

  export default Ember.Component.extend({
    tagName: 'form',
    classNames: ['form-group'],

    profile: {
      location: 'enter location',
      motivation: 'getting strong',
      favorite: 'yoga all day every day',
      username: 'thisExample',
    },
  actions: {
    cancel () {
      let profile = this.get('profile');
      this.sendAction('reset', profile);
    },
      submitProfile () {
        console.log('form submitted');
        this.sendAction('submitProfile', this.get('profile'));

        this.sendAction('saveProfile', this.get('profile'));
},
  },
});
```

**Comment by natGalynker** [comment]
```
import Ember from 'ember';
// import { storageFor } from 'ember-local-storage';
export default Ember.Route.extend({
      auth: Ember.inject.service(),
      actions: {
        submitProfile(data) {
          let profile = this.get('store').createRecord('profile', data);
          console.log(data);
           return profile.save();

            },
        cancel(profile) {
          this.get('store').unloadAll('profile');
          this.get('store').findRecord('profile', profile.id)
            .then((test) => {
                //this.get('store').unloadAll('profile');
                this.transitionTo('profile', test);
                console.log(test.id);
              });
            }
          }
});
```

**Comment by natGalynker** [comment]
Had a 1:1 with lauren. 
changed the submitProfile component.js profile object to empty
moved the sendAction to the button at the bottom of the form
