### ISSUE TITLE
Getting very confused with ember.

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/capstone-project#260]
I'm beginning to get very confused with accessing certain data and when to use the components.  I have my posts titles showing. I can click each title and it routes me to that specific post.  At that point, I need to have the post title, content , and comments to that post be displayed.  

I know that I need to be methodical.  I'm trying to be by displaying the title and content when clicking each post.  But I'm getting very confused when trying to access that information. 

Any help would be good.

**Comment by laurenfazah** [comment]
Is the issue that this is not working?

> I need to have the post title, content , and comments to that post be displayed.

**Comment by jlmitch1989** [comment]
Right.  Currently I'm just trying to get the title and content to show.  The title shows once clicking a post, but the content to that post is not showing.

I have a "post-structure" component that should be accessing that information and displaying it in my post.

**Comment by RealWeeks** [comment]
can you paste in the appropriate code?

**Comment by jlmitch1989** [comment]
So I was able to figure out How to display the needed data.  I just referenced the template incorrectly.  

I guess my question is now how to display comments on a post?  Do I just create a model in ember which references the comments table on the backend?  Or do I have to create a comments route and nest it within the post/:id route somehow?

**Comment by gaand** [comment]
Are the comments limited by the post?  If so, it's probably a nested route.

**Comment by jlmitch1989** [comment]
What do you mean exactly?

**Comment by jlmitch1989** [comment]
Couldn't I just create a comment model and grab the data from that, throw it in a component and then invoke that component within my post/:d route template?

**Comment by gaand** [comment]
I mean, do you want to show all the comments for a given post?  So with a path something like `/post/7/comment` to show all comments for post with id 7?

**Comment by jlmitch1989** [comment]
yes I want all comments to show on that post.  So I guess the best "route" is to make a comment route... 😂

**Comment by jlmitch1989** [comment]
Does this look correct?

```
  this.route('post/comments', { path: '/posts/:post_id/comments' });

```

**Comment by gaand** [comment]
Display comments inline on post detail page a la ListR items

**Comment by jlmitch1989** [comment]
I still cannot get my comments to display with posts.  I must of gone over it 100 times, comparing to the Listr-List example. 

With using the Listr-List structure in my project, I'm able to display something like <p>hello</p> perfectly fine.  But when I try and grab the actual data with <p>{{comment.body}}</p>, I get nothing back.

**Comment by gaand** [comment]
Let's nail this down.

**Comment by gaand** [comment]
Partly a pluralization issue.  Josh will write it up.

**Comment by jlmitch1989** [comment]
I had an association and inverse_of discrepancy. 

On my frontend:
Added associations in my post/model.js file

``` js
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  content: DS.attr('string'),
  // userId: DS.attr('string'),
  // added this to add relationship
  comments: DS.hasMany('comment')
});
```

and in my comment/model.js file

``` js
import DS from 'ember-data';

export default DS.Model.extend({
  body: DS.attr('string'),
  post: DS.belongsTo('post')
});
```

On my backend:
Took off  's' on :post in my post model.

``` rb
class Post < ActiveRecord::Base
  belongs_to :user, inverse_of: :posts
  has_many :comments, inverse_of: :post
end
```
