### ISSUE TITLE
Showing users not working for Ember

### ISSUE THREAD

**Issue by gabescarbrough** [ga-wdi-boston/capstone-project#262]
I started my front-end from Ember Auth (back-end from Rails template) and sign-up, sign-in, change password are all working.

When I click users on the navbar (which came from the Ember Auth repo, didn't change anything there) it gives me the follow error and doesn't appear to hit my Rails back-end which makes me think it's a router issue.

`GET http://localhost:4200/users 404 (Not Found)`

I checked and user is in the router.js and the route.js and template.hbs appear to be the same as David's (whose is working). Confused as to why this isn't working since everyone else I've talked to had it work without tweaking the code.

**Comment by gaand** [comment]
Would you please post `ajax/service.js` and `application/adapter.js`?

Thanks.

**Comment by gaand** [comment]
Oh, and the command you use to start the client.

**Comment by gabescarbrough** [comment]
## ajax/service.js

``` js
import Ember from 'ember';
import AjaxService from 'ember-ajax/services/ajax';
import ENV from 'capstone-project/config/environment';

export default AjaxService.extend({
  host: ENV.apiHost,
  auth: Ember.inject.service(),
  headers: Ember.computed('auth.credentials.token', {
    get () {
      let headers = {};
      const token = this.get('auth.credentials.token');
      if (token) {
        headers.Authorization = `Token token=${token}`;
      }

      return headers;
    },
  }),
});
```

## application/adapter.js

``` js
import Ember from 'ember';
import ActiveModelAdapter from 'active-model-adapter';

export default ActiveModelAdapter.extend({
  auth: Ember.inject.service(),

  headers: Ember.computed('auth.credentials.token', {
    get () {
      let headers = {};
      const token = this.get('auth.credentials.token');
      if (token) {
        headers.Authorization = `Token token=${token}`;
      }

      return headers;
    },
  }),
});
```

**Comment by gabescarbrough** [comment]
ember s

**Comment by gaand** [comment]
Are you able to retrieve other models?

**Comment by gabescarbrough** [comment]
Haven't gotten to that point yet. Was just about to start on that then got confused when this didn't work.

Just added 

``` diff
import Ember from 'ember';
import ActiveModelAdapter from 'active-model-adapter';
+ import ENV from 'capstone-project/config/environment';

export default ActiveModelAdapter.extend({
+ host: ENV.apiHost,
  auth: Ember.inject.service(),

  headers: Ember.computed('auth.credentials.token', {
    get () {
      let headers = {};
      const token = this.get('auth.credentials.token');
      if (token) {
        headers.Authorization = `Token token=${token}`;
      }

      return headers;
    },
  }),
});
```

**Comment by gabescarbrough** [comment]
Now it works. The adapter needed the ENV and apiHost info.
