### ISSUE TITLE
App breaks when DS.hasMany association is added to trip model

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/capstone-project#263]
So I've been trying to follow along with the listr-list lesson and I feel that my code matches with the lesson up to this point. When I attempt to add the association between Trip  and Plans my app breaks.

plan/model.js

```
import DS from 'ember-data';

export default DS.Model.extend({
  what: DS.attr('string'),
  location: DS.attr('string'),
  trip: DS.belongsTo('trip'),
});

```

trip/model.js

```
import DS from 'ember-data';

export default DS.Model.extend({
  location: DS.attr('string'),
  start_date: DS.attr('date'),
  end_date: DS.attr('date'),
  who: DS.attr('string'),
  plans: DS.hasMany('plan'),
});
```

I don't have any errors when I add `trip: DS.belongsTo('trip'),` but I do when `plans: DS.hasMany('plan'),`

**Comment by cdelsoin** [comment]
This may or may not be of help

When I was trying things to fix it I was getting `You need to pass a model name to the store's modelFor method` as an error in the chrome console sometimes.

**Comment by laurenfazah** [comment]
Hmm that looks like a correct setup. Are there any other associations you have going on in your app?

Not sure thiis is helpful, but I googled the issue and found this http://stackoverflow.com/questions/37927705/getting-error-you-need-to-pass-a-model-name-to-the-stores-modelfor-method

**Comment by gaand** [comment]
What's in your serializers and models in your API?

**Comment by cdelsoin** [comment]
trip serializer

```
class TripSerializer < ActiveModel::Serializer
  attributes :id, :location, :start_date, :end_date, :who, :url, :more_info, :user_id, :plans
  has_one :user

  def editable
    scope == object.user
  end
end
```

trip model

```
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :plans
end
```

plan serializer

```
class PlanSerializer < ActiveModel::Serializer
  attributes :id, :who, :what, :date, :time, :location, :more_details, :url, :important, :strict_time, :trip_id, :trip
end

```

plan model

```
class Plan < ActiveRecord::Base
  belongs_to :trip
end

```

**Comment by gaand** [comment]
Have a look at the list-api serializers. I think that's likely the problem.

**Comment by cdelsoin** [comment]
added to my plan serializer

```
  def trip
    object.trip.id
  end
```

added to my trip serializer

```
  def plans
    object.plans.pluck(:id)
  end
```
