### ISSUE TITLE
Approaching Components

### ISSUE THREAD

**Issue by jordanallain** [ga-wdi-boston/capstone-project#264]
I had more of a question regarding my approach to using ember's components and actions.

right now i have a users table and an instruments table and a join table (user_instruments).

I can display users, instruments, and the join table entries.

I'm about to start adding the crud actions to the front end but at the moment I haven't made any new components to handle displaying the user or instrument or join table information. Would it be better to break the app down into components before adding the actions or should I worry about getting the actions to work first? Or maybe there isn't a best approach and I should just pick one, I think we had the actions first in class then we generated components and moved the information around. If I should just follow the code from class I can try that just wanna make sure I'm approaching it intelligently.

**Comment by gaand** [comment]
Any approach that takes small steps, which all end with working code, should be fine.

I'm happy to chat about trade-offs if you think that would help.

**Comment by jordanallain** [comment]
YES

**Comment by gaand** [comment]
Let's meet about it at 10:30.  In here, the dugout, or would you prefer to meet in a conference room?

**Comment by jordanallain** [comment]
classroom or conference room would be better than the dugout

**Comment by gaand** [comment]
Okay.  Let's just meet in here since to leave conference rooms available to others.

**Comment by gaand** [comment]
@jordanallain May this be closed?  If so, please do so with an explanation.  Thanks.

If not, please elaborate.

**Comment by jordanallain** [comment]
was able to break my instruments and my user-instruments down into separate components.

about to move on to buttons. trying to remember which way you said was best.

i have a template that renders the user-instrument component. should that template also render the button associated with the user-instrument? or is it better to have the template render user-instrument component, and have that component render the button component?

**Comment by gaand** [comment]
You want a component that renders the instrument, then two different components, one that invokes the instrument component and renders an add instrument button, and another that invokes the instrument component but then renders an update and delete.

**Comment by gaand** [comment]
@jordanallain Is this still outstanding?

**Comment by jordanallain** [comment]
well i don't think i'm going to be able to break things down into as many components as i want by submission time. so i guess i can close this.
