### ISSUE TITLE
data going down but no actions going up :(

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/capstone-project#266]
Trip has many Plans 

In my plan model I have the following line `important: DS.attr('boolean'),` which I was trying to toggle true/false by following our Listr example. It seems I've got the correct code and passing the actions up properly but nothing is happening. I have double checked for spelling errors/ naming errors and will triple check in a moment. What information do you need from me?

**Comment by RealWeeks** [comment]
all instances of passing the action up, so we can look at what is being passed and to where.

**Comment by cdelsoin** [comment]
trips-list/plan template

```
<span class="trip-plan">
  <div style="border: 1px dashed red" {{action 'toggleImportant'}}>


    <ul>
      <li>{{plan.who}}</li>
      <li>{{plan.what}}</li>
      <li>{{plan.location}}</li>
      <li>{{plan.date}}</li>
      <li>{{plan.time}}</li>
    </ul>
  </div>
</span>
```

trips-list/plan component

```
import Ember from 'ember';

export default Ember.Component.extend({
  classNameBindings: ['tripPlanImportant'],
  tripPlanImportant: Ember.computed.alias('plan.important'),
  actions: {
    toggleImportant () {
      return this.sendAction('toggleImportant', this.get('plan'));
    },
  },
});
```

trips-list template

```
<h3 class="trip-header">{{trip.location}}</h3>
<h4>{{trip.who}}</h4>
<h4 class="trip-subheader">{{trip.more_info}}</h4>
<ul>
  {{#each trip.plans as |plan|}}
    {{trips-list/plan plan=plan toggleImportant='togglePlanImportant'}}
  {{/each}}
</ul>

{{#link-to 'trips'}}Back{{/link-to}}
```

trips-list component

```
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    togglePlanImportant (plan) {
      return this.sendAction('togglePlanImportant', plan);
    },
  },
});
```

trip template

```
{{trips-list trip=model toggleImportant='togglePlanImportant'}}
```

trip route

```
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('trip', params.trip_id);
  },

  actions: {
    togglePlanImportant (plan) {
      plan.toggleProperty('important');
      plan.save();
    },
  },
});
```

**Comment by gaand** [comment]
Do you have a CSS class named `trip-plan-important`?

**Comment by cdelsoin** [comment]
no

**Comment by gaand** [comment]
That's what these lines are about:

``` js
  classNameBindings: ['tripPlanImportant'],
  tripPlanImportant: Ember.computed.alias('plan.important'),
```

They toggle a class on the component when `plan.important` toggles.

**Comment by cdelsoin** [comment]
Do I need to worry about that in order to update my api? I can make it look nice after it works.

**Comment by gaand** [comment]
Unless you are displaying this boolean in some other way, this is how listr displayed the state change.

**Comment by cdelsoin** [comment]
The boolean isnt changing from `false` to `true`

**Comment by gaand** [comment]
How are you determining that?  In the ember inspector?

**Comment by cdelsoin** [comment]
yes

**Comment by gaand** [comment]
I suggest you put a console.error in the inner most component to ensure the action is firing. Then you can move it further out as you verify each layer.

**Comment by cdelsoin** [comment]
please confirm a couple of things for me 
1) {{action}} defaults to clicks
2) if an action is applied to a div then clicking anywhere on the div/contents should fire the action

**Comment by gaand** [comment]
`action` defaults to click.
a click in the div should fire the action.

**Comment by cdelsoin** [comment]
https://guides.emberjs.com/v1.10.0/templates/development-helpers/

**Comment by cdelsoin** [comment]
I read this but I've having trouble understanding how to use {{log}} & {{debugger}} to solve this problem

**Comment by cdelsoin** [comment]
or some guidence with console.error

**Comment by gaand** [comment]
@cdelsoin would you please post the fix when you get a chance?  Thanks.
