### ISSUE TITLE
Understanding adapter.js

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/capstone-project#267]
I am trying to understand what adapter.js is doing

I am referencing the listr-list and using antony's solution branch with his commits.
But specifically for that commit in that file the only information in the commit is that there is an extension of the adapter for item.

I can tell that there is some AJAX happening and that a post request is happening, but I don't quite understand how that is happening.

I would really like some help understanding this

```
import ApplicationAdapter from 'ga-wdi-boston.ember-resources/application/adapter';

export default ApplicationAdapter.extend({
  createRecord (store, type, record) {
    let api = this.get('host');
    let serialized = this.serialize(record, { includeId: true });

    // let listId = serialized.list_id;
    let listId = 2;
    let url = `${api}/lists/${listId}/items`;
    let data = { item: serialized };
    return this.ajax(url, 'POST', { data });
  },
});
```

**Comment by gaand** [comment]
This is a specialization to handle nested routes, something you can probably avoid since you have control of the API.

**Comment by natGalynker** [comment]
Thank you. That makes sense. Thank you for clarifying
