### ISSUE TITLE
issue deploying api

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/capstone-project#268]
Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`

I entered the secret in the config var on heroku but I'm still getting that error. When I went to go set the secrets I noticed that there was a secret field already there. I just added my secrets after it

**Comment by RealWeeks** [comment]
What's the issue?

**Comment by cdelsoin** [comment]
![screen shot 2016-09-28 at 1 34 13 pm](https://cloud.githubusercontent.com/assets/20059077/18925042/5088c816-8580-11e6-9471-a3811d4e7637.png)

**Comment by cdelsoin** [comment]
secret_key_base was already there and i added secret_key_base_developmnent and secret_key_base_test

**Comment by gaand** [comment]
What's in your `config/secrets.yml` file in your rails api?

**Comment by cdelsoin** [comment]
nothing
