### ISSUE TITLE
rails mad about secrets after deployment

### ISSUE THREAD

**Issue by jordanallain** [ga-wdi-boston/capstone-project#270]
i was able to deploy my front and back end successfully, yay!

now that i'm trying to go back to working locally rails is saying i need to add secrets to my config/secrets.yml file. i am pretty sure i only ever had them in my .env file though not in secrets.yml . i believe i changed everything back to how it was pre-deployment but chances are i am missing something obvious. does something jump out to you about this? i asked a few other developers in the cohort and they weren't sure.

**Comment by laurenfazah** [comment]
What does your secrets.yml file look like? It's it interpolating ENV variables from .env?

**Comment by jordanallain** [comment]
that did the trick. my secrets.yml file was completely empty, so i'm not sure how it worked when i force pushed it to heroku or when it became barren. i just put the typical stuff back in there and it was able to grab the secrets from .env
