### ISSUE TITLE
app and api deployed - No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/capstone-project#271]
XMLHttpRequest cannot load https://trip-planner-api.herokuapp.com/sign-in. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cdelsoin.github.io' is therefore not allowed access.

I get this error when I load my deployed app. Therese nothing on either deployment guide about how to solve this.

**Comment by gaand** [comment]
Have you set `CLIENT_ORIGIN`?

**Comment by cdelsoin** [comment]
this is what i have per rails template issues

![screen shot 2016-09-28 at 3 23 05 pm](https://cloud.githubusercontent.com/assets/20059077/18928761/82018cca-858f-11e6-8f75-f9517361b350.png)

**Comment by cdelsoin** [comment]
https://github.com/ga-wdi-boston/rails-api-template/issues/20

**Comment by RealWeeks** [comment]
I think you should compare what you have to what @gaand wrote.

**Comment by cdelsoin** [comment]
thank you.
