### ISSUE TITLE
Ember deployment to gh-pages

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/capstone-project#273]
After I've deployed the app multiple times, I keep getting the same error in my dev-tools when I go to my page.

```
ember-typeone:1 Refused to load the image 'http://jlmitch1989.github.io/favicon.ico' because it violates the following Content Security Policy directive: "img-src data:".

```

Where should I go next? I've gone through the steps very carefully 6 times. 
I also did what Lauren told us to do last week `atom ~/dist` (deleting the global /dist).

**Comment by gaand** [comment]
Is a problem of http versus https. It has to be https. 

Are you using a favicon?

**Comment by jlmitch1989** [comment]
I am using an s on https

``` js
ENV.apiHost = 'https://blooming-woodland-68349.herokuapp.com/';
```

I don't even know what favicon is.

**Comment by gaand** [comment]
But the error doesn't have the `s`:

`http://jlmitch1989.github.io/favicon.ico`

Does your app work correctly when deployed, or is it more than this console error?

**Comment by jlmitch1989** [comment]
My app doesn't even show up.  I just get a 404 page and that favicon error in my dev tools.

**Comment by jlmitch1989** [comment]
Is the `http://jlmitch1989.github.io/favicon.ico` something I should be fixing on the back end?

**Comment by gaand** [comment]
Please post the production section of your config/environment.

**Comment by laurenfazah** [comment]
@gaand walking through it with him now - everything looks good so far, though

**Comment by gaand** [comment]
But it's not in the issue so I can't look at it. :-).

**Comment by jlmitch1989** [comment]
Ok so obviously this issue had everything to do with me.  I was going to the wrong url to see my application 😐. 

``` diff
- http://jlmitch1989.github.io/ember-frontend
+ http://jlmitch1989.github.io/frontend-typeone
```
