### ISSUE TITLE
Migration issue 

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/capstone-project#274]
I'm trying to create another feature for my app. I ran into migration issues. 

Steps I followed:
1. Created new branches for front and back. Tested and made my feature work.
2. Added and committed it on the new branch. 
3. Checkout master and started working on the feature on master branch.

Feature I tried to incorporate is date for the each memory. I altered my database on new branch, and did the same thing on master. That was mistake. It created conflict around migration because it already existed.

Rails error told me to run:

`
Migrations are pending. To resolve this issue, run:

```
bin/rake db:migrate RAILS_ENV=development
```

):
`

So, now is all gone. No functionality on the front end whatsoever.

This is what `rake db:migrate:status` gives me:
## Status   Migration ID    Migration Name

   up     20150724141255  Create users
   up     20160327214720  Create examples
   up     20160918123053  Create memories
   up     20160918124721  Add user to memories
   up     20160923194123  Add admin to user
   up     20160927232139  *********\* NO FILE **********
   up     20160928003429  *********\* NO FILE **********
   up     20160928004103  *********\* NO FILE **********
   up     20160928225310  *********\* NO FILE **********
  down    20160928230131  Add date to memories

Can this issue be resolved?

**Comment by gaand** [comment]
Absolutely, but it may take some work.  

Please post the output of running `ls db` in your API repository.

**Comment by RealWeeks** [comment]
Did you do any rollbacks?

**Comment by NatasaPeic** [comment]
Yes. I did rollbacks. Some of them succeeded, I deleted migration file, but some of them failed. I guess there is a lot of things going on.

This would be the output:

`~/wdi/projects/project4-back/project4 (master)$ ls db
`
`
examples.rb migrate     schema.rb   seeds.rb
`

**Comment by NatasaPeic** [comment]
Since I just added that column and tried to migrate (it isn't that important and I can always alter my database if I fix this), would `rake db:rollback version = version_number` do any good?

**Comment by gaand** [comment]
Sorry, I meant to ask you to list the contents of `db/migrate`.

**Comment by NatasaPeic** [comment]
No problem.

`
~/wdi/projects/project4-back/project4/db/migrate (master)$ ls
`
`
20150724141255_create_users.rb
`  
`20160918123053_create_memories.rb
`  
`20160923194123_add_admin_to_user.rb
`
`
20160327214720_create_examples.rb
`  
`
20160918124721_add_user_to_memories.rb
`  
`
20160928230131_add_date_to_memories.rb
`
~/wdi/projects/project4-back/project4/db/migrate (master)$

**Comment by NatasaPeic** [comment]
Everything shows as it should... Even in schema. But running rails server after running 

`
bin/rake db:migrate RAILS_ENV=development
`
makes all of my functionality gone on  the front end (locally).

**Comment by gaand** [comment]
You could reset your local database, with `bin/rake db:migrate VERSION=0` then migrate again. This will remove all your data, but may fix the issue. 

Deleting migrations can cause odd problems.

**Comment by NatasaPeic** [comment]
WOW!! Again, wow! This worked and solved my issue! Thank you so so much!!!
