### ISSUE TITLE
Trying to post to join table "Ember.Object that does not implement Ember.Copyable"

### ISSUE THREAD

**Issue by jordanallain** [ga-wdi-boston/capstone-project#276]
Inside my display-instrument component template

``` js
<button {{action 'addUserInstrument'}}>Add {{instrument.name}} to My Instruments</button>
```

in the component itself

``` js
    addUserInstrument() {
      this.sendAction('addUserInstrument', this.get('instrument'));
    }
```

the action and the instrument object get sent up to the instruments route
in the template

``` js
{{#each model as |instrument|}}
  {{display-instrument instrument=instrument addUserInstrument='addUserInstrument'}}
{{/each}}
```

in the route

``` js
    addUserInstrument (instrument) {
      let newInstrument = this.get('store').createRecord('user-instrument', instrument);
      newInstrument.save();
    }
```

when i hit the button this is the error i get in my console.

```
ember.debug.js:6421 Uncaught Error: Assertion Failed: Cannot clone an Ember.Object that does not implement Ember.Copyable
```

I'm not sure why it thinks I am trying to copy an ember object. what i'm trying to do is send the instrument ID to the back end so that in the back end I can post to the join table with the instrument ID and the current user's ID.

Confused as to whether I need a transition to or a path or if I just need to fix something in Rails about the create user_instrument's method.

**Comment by gaand** [comment]
Please post the 'user-instrument' model.

**Comment by jordanallain** [comment]
``` js
import DS from 'ember-data';

export default DS.Model.extend({
  user: DS.belongsTo('user'),
  instrument: DS.belongsTo('instrument'),
  styles: DS.attr('string')
});
```

**Comment by gaand** [comment]
You're handing createRecord an `ember-data` model.  But I think you want to hand it key/value pairs:

``` diff
     addUserInstrument (instrument) {
-     let newInstrument = this.get('store').createRecord('user-instrument', instrument);
+     let newInstrument = this.get('store').createRecord('user-instrument', { instrument });
      newInstrument.save();
    }
```

**Comment by jordanallain** [comment]
ah okay that seems to have reached the correct index action with the instrument id but it isn't getting the user id. i was thinking that i should wait until it hits rails and then rails would have the current_user id already.

tried modifying my controller with these lines

``` js
@user_instrument = current_user.user_instruments.build(user_instrument_params)
```

``` js
@user_instrument = current_user.user_instruments.build(user_params)
```

should i explicitly state user_instrument.id = current_user.id somewhere instead? not sure exactly how to place it inside my controller.

**Comment by gaand** [comment]
No, `build` should attach `user_id`.

I don't understand what the second line is for.  Are both of those in the same controller and what controller is that?

**Comment by jordanallain** [comment]
Changed my user instruments controller create method to

``` js
  def create
    @user_instrument = current_user.user_instruments.build(user_instrument_params)

    if @user_instrument.save
      render json: @user_instrument, status: :created, location: @user_instrument
    else
      render json: @user_instrument.errors, status: :unprocessable_entity
    end
  end
```

also had to include user_id in my user instrument serializer

``` js
class UserInstrumentSerializer < ActiveModel::Serializer
  attributes :id, :user, :instrument, :styles, :user_id
  has_one :user
  has_one :instrument

  def user
    object.user.id
  end

  def instrument
    object.instrument.id
  end
end
```

now it appears to be working.

**Comment by antleo1995** [comment]
I am happy to have found this post:
```
     addUserInstrument (instrument) {
-     let newInstrument = this.get('store').createRecord('user-instrument', instrument);
+     let newInstrument = this.get('store').createRecord('user-instrument', { instrument });
      newInstrument.save();
    } 
```
was also my fix

**Comment by jordanallain** [comment]
@antleo1995 past antony saving the day!
