### ISSUE TITLE
No action handler error on delete

### ISSUE THREAD

**Issue by gabescarbrough** [ga-wdi-boston/capstone-project#277]
I am receiving a `Uncaught Error: <capstone-project@component:collection-card::ember612> had no action handler for: delete` when I try to delete collections (which are displayed using the collection-card component.)

This is confusing as I do have a delete action being passed up from a button.

And as far as I can tell it is being passed up to each layer that it needs to.
### collection-card/template.hbs

``` hbs
{{#link-to 'collection' collection}}<h2>{{collection.name}}</h2>{{/link-to}}
<h4>By {{collection.user.email}}</h4>
<p>{{collection.description}}</p>

<button class="btn btn-xs btn-danger" {{action 'delete'}}>
   Delete
</button>
```
### collection-card/component.js

``` js
import Ember from 'ember';

export default Ember.Component.extend({
  delete () {
    this.sendAction('delete', this.get('collection'));
  },
});
```
### collections/template.hbs

``` hbs
{{#each model as |collection|}}
  {{collection-card collection=collection delete='deleteCollection'}}
{{/each}}
```
### collections/route.js

``` js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
     return this.get('store').findAll('collection');
  },
  actions: {
    deleteCollection(collection) {
      collection.destroyRecord();
    },
  },
});
```

**Comment by RealWeeks** [comment]
looks like the actions is missing

``` javascript
actions: {
    someAction: function(){
        this.sendAction("someAction");
    }
}
```

**Comment by RealWeeks** [comment]
Not paying attention, apologies.

**Comment by RealWeeks** [comment]
This looks like it should work the `had no action handler for: delete` makes me think it's something in the component. I'm going to keep looking at this.

**Comment by RealWeeks** [comment]
@laurenfazah thought on this seems correct.

**Comment by laurenfazah** [comment]
Let's look at this together.

**Comment by RealWeeks** [comment]
@gabescarbrough when you wrapped it in actions what errors occurred?

**Comment by gabescarbrough** [comment]
I was getting a `Error: Ember Data Request DELETE http://localhost:3000/collections/4 returned a 0 Payload (Empty Content-Type)` error.

I had to add `dependent: :destroy` to my collections model on the backend.

Delete now works.
