### ISSUE TITLE
404 on Put action

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/capstone-project#278]
when I send a put action to edit my Trip name I get this error

![screen shot 2016-09-29 at 2 53 47 pm](https://cloud.githubusercontent.com/assets/20059077/18967788/96fe2230-8654-11e6-9346-cfe8c5b4660a.png)

I double checked and that url leads me to an active trip. I looked it up and the internet told me I should be setting up some error handling and a new route to work around the error. I just want to confirm with you before I do anything stupid. 

one of the resources I found
http://discuss.emberjs.com/t/how-to-deal-with-route-when-model-gets-a-404/5283/2

**Comment by gaand** [comment]
What does your rails server log when you make the request?

**Comment by cdelsoin** [comment]
Nothing happens in the log

**Comment by cdelsoin** [comment]
```
Started PUT "/trips/1" for ::1 at 2016-09-29 15:11:53 -0400
Processing by TripsController#update as HTML
  Parameters: {"trip"=>{"location"=>"Boston, MA", "start_date"=>"2016-01-10T00:00:00.000Z", "end_date"=>"2016-03-10T00:00:00.000Z", "who"=>"All, Jim, Susan, Timmy, Sally", "more_info"=>"woooo, our first time in Boston! PAHK DA CAHHH!"}, "id"=>"1"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "9ff79b899e466c46e6b89f708f2d64bb"]]
  Trip Load (0.2ms)  SELECT  "trips".* FROM "trips" WHERE "trips"."user_id" = $1 AND "trips"."id" = $2 LIMIT 1  [["user_id", 2], ["id", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.09ms)
Completed 404 Not Found in 3ms (Views: 0.5ms | ActiveRecord: 0.4ms)


```

**Comment by cdelsoin** [comment]
![screen shot 2016-09-29 at 3 13 14 pm](https://cloud.githubusercontent.com/assets/20059077/18968500/48effcd2-8657-11e6-8971-3b91a375cb7a.png)

**Comment by gaand** [comment]
See `["user_id", 2]` above.

**Comment by cdelsoin** [comment]
_facepalm_

I must've signed in under a different user and forgot to go back
