### ISSUE TITLE
Heroku issue: fatal  repository 'my app' not found

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/capstone-project#280]
I deleted my app on heroku previously and it seems like now my local and my remote heroku aren't lining up. I am trying to google. But the destroy command that I found is not working.

**Comment by laurenfazah** [comment]
Are you trying to remove the `heroku` remote?

**Comment by natGalynker** [comment]
I think the opposite, I went to the heroku site and deleted it manually, so that would mean that the local version doesn't have something to push to, which is why the error is being thrown

**Comment by laurenfazah** [comment]
I think you'd have to delete your local `heroku` remote and start fresh. There might be another way to go about it but I don't know of it.

**Comment by natGalynker** [comment]
Looks like the trouble shooting on my own did it:

I closed that terminal,
updated heroku
ran remote -v 
heroku apps:destroy –app appname
after that I ran heroku apps:info and heroku config. Since nothing was outputting with that appname I decided to try creating again!
