### ISSUE TITLE
App not working after deployment

### ISSUE THREAD

**Issue by jordanallain** [ga-wdi-boston/capstone-project#281]
The app is now deployed and the functionality is working on the front end but the data doesn't persist to the back end. When I try to post to the join table i get a few errors.

in the console it says this.

```
XMLHttpRequest cannot load https://rocky-falls-32123.herokuapp.com//user_instruments. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://jordanallain.github.io' is therefore not allowed access. The response had HTTP status code 500.
```

```
vendor-efedb14….js:3 XHR failed loading: POST "https://rocky-falls-32123.herokuapp.com//user_instruments".send 
...
12 Error: Ember Data Request POST https://rocky-falls-32123.herokuapp.com//user_instruments returned a 0 Payload (Empty Content-Type)
```

when i run heroku logs i can see this error pointing to my create action in the user instruments controller.

``` sh
2016-09-29T21:22:59.596193+00:00 app[web.1]: Completed 500 Internal Server Error in 145ms (ActiveRecord: 42.5ms)
2016-09-29T21:22:59.598052+00:00 app[web.1]: 
2016-09-29T21:22:59.598058+00:00 app[web.1]: NoMethodError (undefined method `styles' for #<UserInstrument:0x007f8d23120bf8>):
2016-09-29T21:22:59.598059+00:00 app[web.1]:   app/controllers/user_instruments_controller.rb:25:in `create'
```

in my user instrument controller i have :styles as permitted but not required so i didn't think i would need to post to the join table with any information under styles.

``` js
    def user_instrument_params
      params.require(:user_instrument).permit(:instrument_id, :user_id, :user, :instrument, :styles)
    end
```

i am able to sign up and sign in with curl requests but when i try to post to the deployed join table with a curl request i get a 500 internal server error.

i see that there is two slashes in the back end url

```
https://rocky-falls-32123.herokuapp.com//user_instruments
```

but i didn't think that would cause the app not to function. if it is as simple as that i can fix that but didn't want to go through all the steps of redeployment if that didn't make a difference.

**Comment by RealWeeks** [comment]
You don't need to post with styles if it's permitted. Do styles still exist or we're they removed?

Are you doing any funky stuff with styles elsewhere in the model or serializer?

Try removing the extra slash first.  I know it's a pain but ruling out all other possible bugs is part of the debugging process.

**Comment by RealWeeks** [comment]
If that doesn't work (I heard from a good source it doesn't) remove styles and try posting again, tell me what happens then.  I'm curious if the error is still there.

**Comment by RealWeeks** [comment]
wait, what is create line 25?

**Comment by jordanallain** [comment]
it seems to be pointing to my create function

``` rb
  def create
    @user_instrument = current_user.user_instruments.build(user_instrument_params)

    if @user_instrument.save
      render json: @user_instrument, status: :created, location: @user_instrument
    else
      render json: @user_instrument.errors, status: :unprocessable_entity
    end
  end
```

**Comment by jordanallain** [comment]
should i post all of the heroku logs?

**Comment by RealWeeks** [comment]
Is there other relevant error reporting or is it just noise? Couldn't hurt

**Comment by RealWeeks** [comment]
Did you migrate?... just getting these questions out of the way

**Comment by jordanallain** [comment]
dear god....i think it was just that i didn't run heroku migrate

**Comment by jordanallain** [comment]
HEROKU RUN RAKE DB:MIGRATE !!!!!!!!!!!

except not in all caps
