### ISSUE TITLE
Creating posts on my frontend

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/capstone-project#283]
I can successfully create posts on my front end.  But, when I do create a post, it isn't showing a user attached to he post on the back end.  I just says user: null

```
"posts": [
{
"id": 4,
"title": "I got the diabetes",
"content": "HALP",
"comments": [
3,
8
],
"user": {
"id": 3,
"email": "me123"
}
},
{
"id": 47,
"title": "pooooopy",
"content": "apasodfa",
"comments": [],
"user": null
},
```

When I send curl request it gives the user with the post.  
My guess is that my post request isn't sending all the info on the frontend.
My question is how do I fix that? I'm not really sure how that works with ember.

**Comment by RealWeeks** [comment]
when you say "When I send curl request" does that mean a GET or a POST? Try POSTing with curl if you haven't. What is the result?

**Comment by jlmitch1989** [comment]
a POST. I have, that works.  It gives me the user and then it actually goes into the `my threads` which is current user.

**Comment by RealWeeks** [comment]
No console errors right? Can you post the relevant component and template.

**Comment by jlmitch1989** [comment]
No the post will POST but it doesn't show in the current_user route.
I don't know what relevant component and template you are referring to. That's why I was asking for help, because I don't know what or where I need to fix on front end to send the right information.

**Comment by RealWeeks** [comment]
The component where you POST information, the lowest level component that has to do with this post

**Comment by jlmitch1989** [comment]
``` js
import Ember from 'ember';

export default Ember.Route.extend({
  actions: {
    createNewPost (data) {
      // console.log(data);
      let post = this.get('store').createRecord('post', data);
      post.save()
        .then(()=>this.transitionTo('posts'));
    },

  },
});
```

**Comment by RealWeeks** [comment]
can you show me this components parent?

**Comment by jlmitch1989** [comment]
Create route template

``` js
{{typeone-forum/create post=model createNewPost='createNewPost'}}
```

Create route.js

``` js
import Ember from 'ember';

export default Ember.Route.extend({
  actions: {
    createNewPost (data) {
      // console.log(data);
      let post = this.get('store').createRecord('post', data);
      post.save()
        .then(()=>this.transitionTo('posts'));
    },

  },
});

```

typeone-forum/create component template

``` js
<section>
  <form {{action "createNewPost" on="submit"}}>
    {{input value=newPost.title placeholder="Title..." type="text" cols=25 rows=10}}

    {{textarea value=newPost.content placeholder="Description..." cols="137" rows="6"}}

    <button type="submit" class="btn btn-success">Create</button>
  </form>
</section>
```

typeone-forum/create component.js

``` js
import Ember from 'ember';

export default Ember.Component.extend({
  newPost: {
    title: null,
    content: null,
  },

  actions: {
    createNewPost () {
      let data = this.get('newPost');
      data.post = this.get('post');
      this.sendAction('createNewPost', data);
      // this clears the form field
      this.set('newPost.title', null);
      this.set('newPost.content', null);
    },
  },
});


```

**Comment by jlmitch1989** [comment]
This is the whole shabang.

**Comment by RealWeeks** [comment]
That first thing you posted on this thread was that the result of posting using this?

**Comment by RealWeeks** [comment]
I'm guessing its just this one

``` js
{
"id": 47,
"title": "pooooopy",
"content": "apasodfa",
"comments": [],
"user": null
},
```

is this user tied into that at all?

``` js
"user": {
"id": 3,
"email": "me123"
}
```

**Comment by jlmitch1989** [comment]
What?
I was saying that POST is successful on the frontend, but it is not showing current_user stuff like Antony and I had set up earlier.  But earlier I was only ale to get current_user stuff using curl request on the back end because I hadn't set up POST on the front end.

**Comment by jlmitch1989** [comment]
No It's all POST that I make from the front end.  It doesn't send it to the route I have set up to current_user.

**Comment by RealWeeks** [comment]
Hmm, so I think I misunderstood your question at first, thanks for explaining just now.

**Comment by J-Weeks** [comment]
Did you send any user data?

**Comment by jlmitch1989** [comment]
From the front end?

**Comment by jlmitch1989** [comment]
I'm not sure what you mean exactly?

**Comment by RealWeeks** [comment]
Sorry, didn't mean to hit enter

**Comment by RealWeeks** [comment]
Comparing against my ember app, I return the save so `return post.save()`. But I'm still looking at this. Then again I also didn't transition.

**Comment by gaand** [comment]
`post.save()` returns a promise, and so is thenable. 

In the API use `current_user.posts.build`. 

Edited @jlmitch1989

**Comment by jlmitch1989** [comment]
xurent? or current?

**Comment by gaand** [comment]
Sorry.  Comment from my phone.

Please post the create action in rails, the strong params, and the model in ember.

Edited @jlmitch1989

**Comment by jlmitch1989** [comment]
Jordan helped me out.  I added this to my create method in my Posts Controller

``` rb
def create
    @post = current_user.posts.build(post_params)
    # @post = Post.new(post_params)
```
