### ISSUE TITLE
Links without http:// treated as relative links

### ISSUE THREAD

**Issue by gabescarbrough** [ga-wdi-boston/capstone-project#284]
When users submit links to my application they are included as links to the site of the URL provided.

If they submit a link with 'http://' at the beginning they work fine.

If they don't include 'http://', ex. www.google.com, the link is treated as  a relative link.

**Comment by gaand** [comment]
This is expected. I suggest testing for a leading 'http://` and prepending if not present (also with an s). 

This is an excellent place to use regular expressions.

**Comment by gaand** [comment]
Or use this, https://ruby-doc.org/core-2.3.1/String.html#method-i-start_with-3F

**Comment by gaand** [comment]
@gabescarbrough  Would you please close this if resolved?  Thanks.

If you need more assistance, please elaborate.  Thanks again.
