### ISSUE TITLE
destroyRecord is not a function

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/capstone-project#285]
I am trying to get my delete action is working.
I have created a delete-profile component and have invoked that component inside my template which is rendering said  profile information. :

**Comment by natGalynker** [comment]
```
<button {{action 'delete'}}>delete</button>
```

```
import Ember from 'ember';

export default Ember.Component.extend({
  actions : {
  delete () {
  this.sendAction('delete', console.log(this.get('profile')));
},
```

```
import Ember from 'ember';

export default Ember.Route.extend({
  auth: Ember.inject.service(),
  credentials: ('auth'),
  actions: {
    editAction () {
      this.transitionTo('profiles/edit');
    },
    delete(profile) {
    profile.destroyRecord();
  },
```

**Comment by natGalynker** [comment]
The function is hitting in component.js
I console.log('this message') and that was hitting

**Comment by gaand** [comment]
You're passing the return value of `console.log` as the argument to `sendAction`. `console.log` returns undefined.

**Comment by natGalynker** [comment]
I removed that console log, I did created one each in route.js and the component.js  after the 

```
delete(){ 
}
and delete(profile){
}
```

**Comment by natGalynker** [comment]
I think the issue may be on the back end, the data I am getting back from POST is not assigning a user ID. I have passed user in both in the profiles serializer and the Profile controller. I don't think that setting user ID to null false would help

**Comment by gaand** [comment]
`this.get('profile')`, the argument you sent to `console.log` was likely the argument you wanted to send to `sendAction`. 

I'm basing my comments on the code you posted.

If a user id isn't getting set in your API, you might want to look at one of the more recently closed issues.

**Comment by natGalynker** [comment]
When I console.log that, it comes back as undefined

**Comment by gaand** [comment]
Are you passing in a profile to the component when you invoke it?

**Comment by natGalynker** [comment]
here is how I am invoking the component:

```
{{delete-profile model=profile delete='delete'}}
```

**Comment by natGalynker** [comment]
I was able to get the data associated with the said user back to.
I changed the relationship between user and profiles and that seems to have worked. The button does not seem to be grabbing the data associated though, will keep working on it

**Comment by natGalynker** [comment]
Worked through methodically. Was able to follow the errors and find where the issue was.
in the process of being tired. and taking out the console log delete () { I changed the destroy action to something else, then had it reference the delete send action where the component got invoked.
