### ISSUE TITLE
Login is hijacking my profiles model

### ISSUE THREAD

**Issue by eshimel** [ga-wdi-boston/capstone-project#29]
Registration and login are still working fine, and I've been able to create profiles and requests for them on the backend.  For reasons that I am not able to determine on my own or with internet searches, login and registration are now linking to the profiles model and returning this error POST http://localhost:3000/profiles 401 (Unauthorized).   What I am unable to figure out if why the login or registration event handlers are even triggering profiles.  Profiles is a separate form, in a separate div, in a separate section of the web page.

I'd like some assistance/advice on how to fix the issue, so that I can actually create a profile, with the profile form.

**Comment by gaand** [comment]
Click handler code for login/register/profiles?

**Comment by eshimel** [comment]
good news...that error is gone, but there is still a profiles error. 

 $('#register').on('submit', function(e) {
        e.preventDefault();
        var credentials = wrap('credentials', form2object(this));
        swap_api.register(credentials, callback);
      });

```
  $('#login').on('submit', function(e) {
    var credentials = wrap('credentials', form2object(this));
    var cb = function cb(error, data) {
      if (error) {
        callback(error);
        return;
      }
      callback(null, data);
      $('.token').val(data.user.token);
      $('.id').val(data.user.id);
      console.log(data.user.token);
      $('#login').each(function(){
        this.reset();

      });

    };
    e.preventDefault();
    swap_api.login(credentials, cb);

  });

  $('#logout').on('click', function(e) {
    var token = $('.token').val();
    var id = $('.id').val();
    var cb = function cb(error, data) {
      if (error) {
        callback(error);
        return;
      }
    };
    swap_api.logout(token, id, cb
      );

});

  // Submitting new entries function
  $('#profiles').on('submit', function(e) {
    e.preventDefault();
    var token = $('.token').val();
    var new_profile = wrap('profile', form2object(this));
    swap_api.new_profile(token, new_profile, function(err, profileData) {
      if (err) {
        // do something with the error
        return;
      } else {
        $('#profiles').each(function(){
        this.reset();

      });
        console.log(profileData);
      }
    });
  });
```

});

**Comment by gaand** [comment]
Please add  `console.error(err)` inside the profiles click handler's if and paste the output.  Also, is your API producing any errors?

**Comment by eshimel** [comment]
yes, its producing this error NoMethodError (undefined method `profiles' for #<User:0x007fdf5c119458>):
  app/controllers/profiles_controller.rb:22:in`create'

console.error gave me this POST http://localhost:3000/profiles 500 (Internal Server Error)
script.js:83 Object {jqxher: Object, status: "error", error: "Internal Server Error"}

**Comment by eshimel** [comment]
I tried changing profiles to profile on line 22 in the controller...it then threw the NoMethodError on 'new'

 def create
    @profile = current_user.profiles.new(profile_params) #makes this, this user's profile.
    @profile.save
    if @profile.save
      render json: @profile, status: :created, location: @profile
    else
      render json: @profile.errors, status: :unprocessable_entity
    end
  end

**Comment by gaand** [comment]
User `has_one: :profile`?  I think you need to use `current_user.build_profile(profile_params)`

**Comment by eshimel** [comment]
User does have one :profile, I'll it...standby

**Comment by eshimel** [comment]
Whoa!  It worked!  I'd love to know why...but I suppose I'll hold off on the why right now and just make the model work the rest of the way.  Thanks!
