### ISSUE TITLE
1on1 Request - Data not rendering on template

### ISSUE THREAD

**Issue by chrxtina** [ga-wdi-boston/capstone-project#291]
I am receiving a front-end `Error while processing route: category Cannot read property '_internalModel' of null TypeError: Cannot read property '_internalModel' of null` when I make a GET request but do not really understand it. However, I do see the expected data inside of the Ember Inspector after making the request, so I'm just not sure what I'm missing to render the data to the template. 

The request starts from app/categories/template.hbs:
`{{#link-to "category" "office"}}Office{{/link-to}}`

**router.js:**
```javascript
Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('categories');
  this.route('category', { path: 'categories/:category' });
});
```

**app/category/route.js:**
```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('category', params.category);
  }
});
```

**app/category/template.hbs:**
```
{{#each model as |item|}}
  {{item}}
{{/each}}
```

**app/category/model.js:**
```javascript
import DS from 'ember-data';

export default DS.Model.extend({
    item: DS.hasMany('item'),
});
```

**app/item/model.js:**
```javascript
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  location: DS.attr('string'),
  body: DS.attr('string'),
  address: DS.attr('string'),
  category: DS.belongsTo('category'),
});
```

I believe that these are all of the relevant files, but please let me know if I'm missing anything. Thanks for any help!

**Comment by jrhorn424** [comment]
If you want to hard-code to look up a particular category, you shouldn't have the model hook for category set-up to look for a category ID.

``` diff
-     return this.get('store').findRecord('category', params.category); // this is expecting an ID here, not a string with the value "office"
+     return this.get('store').findAll('category').then(/* fitler it somehow */); // OR
+     return this.get('store').queryRecord('category', { name: params.category }) // but this requires editing your API
```

Your modeling may be incomplete. I can't know that without seeing some ERDs, wireframes, and user stories.

If you had a category name, I suspect it'd be better to actually have Ember fetch the categories and build up the links for you programmatically, so you can have idiosyncratic route handlers and model hooks.

``` diff
- {{#link-to "category" "office"}}Office{{/link-to}}

+ {{#each model as |category|}}
+  {{#link-to "category" category}} // goes to /categories/:id instead of /categories/:name
+    {{category.name}} // or something similar
+  {{/link-to}}
+ {{/each}}
```

**Comment by chrxtina** [comment]
Hi @jrhorn424 , I think that I may have structured things inefficiently for Ember to not be happy. Can I have a 1on1 to discuss re-doing my approach?

**Comment by jrhorn424** [comment]
Thanks @chrxtina had a great discussion! Similar to @tuckyeah, she was trying to simplify her problem in a way that actually made it harder for Ember.

@chrxtina did not have a category table, but she had need of a category table upon review of her wireframes and user stories. If you're wondering whether or not you need a table, the answer is probably yes. Here's some questions I sometimes use to decide whether or not I need a table:
-   Are there repeated values in a column?
-   Do I have numbers in my column names?
-   Do I need to show a list of categories, or will the categories be free-form text?
-   Is there a need to filter by value on the front-end?

All of these boil down to, "What does my use case resemble more: putting things into buckets, or labeling things with a label machine?" If it's the former, you need a category table.

I've advised @chrxtina to create a category table and set up relationships in the API, noting how these relationships are serialized in the API serializer. She'll also create an appropriate front-end model and relationships, and use the Ember patterns of RESTful routes and linking patterns:

``` diff
- {{#link-to "category" "office"}}Office{{/link-to}}

+ {{#each model as |category|}}
+  {{#link-to "category" category}} // goes to /categories/:id instead of /categories/:name
+    {{category.name}} // or something similar
+  {{/link-to}}
+ {{/each}}
```
