### ISSUE TITLE
[CURL] Uploading files to AWS using Paperclip

### ISSUE THREAD

**Issue by styletabtech** [ga-wdi-boston/capstone-project#292]
Hi! Yesterday I set up my AWS IAM and bucket for my app and began testing this with curl, using the script that Rebekah used [here](https://github.com/ga-wdi-boston/rails-paperclip/issues/15). 

Doing so resulted in the file being uploaded, but I wasn't seeing the expected AWS url. This is the JSON I got back: 
```
{"photo":{"id":5,
"file_name":"otter",
"photo_upload_url":"/system/photos/photo_uploads/000/000/005/original/1478403611.png?1478403611",
"user":null}
```

After a lot of failed Googling I decided to cut my losses for the evening and tackle it today. 
When I spun up my server this morning all of the photo uploads were now showing the AWS url I was expecting: 

```
{"photo":{"id":7,
"file_name":"otter 2",
"photo_upload_url":"http://s3.amazonaws.com/photoapp-bucket/photos/photo_uploads/000/000/007/original/1478403841.png?1478403841",
"user":null}}
```
However, my s3 bucket was still empty when viewing it in the AWS console. I then attempted to run my same curl script that I had been using yesterday:

```
  curl -v http://localhost:3000/photos \
    -H 'Content-Type: multipart/form-data' \
    -H 'Accept: application/json' \
    -F "photo[file_name]=new photo" \
    -F "photo[photo_upload]=@otter.jpg;type=image/jpg"
```

But now I get the following error when trying to upload: 
```
Aws::S3::Errors::PermanentRedirect (The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.):
  app/controllers/photos_controller.rb:23:in `create'
```
I'm a really lost about what I should be putting in the create method. When googling this error almost all solutions involve making sure that AWS_REGION is correct. I've triple checked my region and it is correct. Here's what's in my .env:

```
S3_BUCKET_NAME=photoapp-bucket
AWS_ACCESS_KEY_ID=my access key
AWS_SECRET_ACCESS_KEY=my secret key
AWS_REGION=us-west-2
```

I've included the following in my production.rb and development.rb files:
```
  config.paperclip_defaults = {
      storage: :s3,
      s3_region: ENV['AWS_REGION'],
      s3_credentials: {
        bucket: ENV['S3_BUCKET_NAME'],
        access_key_id: ENV['AWS_ACCESS_KEY_ID'],
        secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
      }
    }
```
Photos controller: 
```
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    render json: @photos
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    render json: @photo
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    if @photo.save
      render json: @photo, status: :created, location: @photo
    else
      render json: @photo.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    if @photo.update(photo_params)
      head :no_content
    else
      render json: @photo.errors, status: :unprocessable_entity
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy

    head :no_content
  end

  private

    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:file_name, :user_id, :photo_upload)
    end
end
```
@rhjones did you run into this error at all?

**Comment by berziiii** [comment]
I ran into this. You should follow the aww-setup-guide and create a new bucket. Make sure the bucket is 'US Standard' for the region and then when you set your region in your .env, make sure it's us-east-1. 

Happy to provide more guidance tomorrow but I had this error

My guess is that the bucket

**Comment by berziiii** [comment]
Also try and creating a new ID and secret key for Your S3 account and use those.

**Comment by styletabtech** [comment]
Thanks @berziiii I realized my AWS account was set to Oregon for the region so I changed that to N.Virginia so that 'US Standard' defaults to us-east-1. I created a new bucket with the updated region and a new user/keys, but I'm getting the same error. Could I meet with you tomorrow morning to take a look?

**Comment by berziiii** [comment]
So when you created the bucket you chose 'US Standard' or 'N. Virginia'? Yes we can.

**Comment by styletabtech** [comment]
I used 'US Standard' for creating the bucket
URL for the bucket is: https://console.aws.amazon.com/s3/home?region=us-east-1&bucket=myphotoapp-bucket&prefix= 

![screen shot 2016-11-06 at 11 41 22 am](https://cloud.githubusercontent.com/assets/20650779/20039692/2a445454-a416-11e6-96b0-beca84258bdb.png)

**Comment by styletabtech** [comment]
SOLUTION: Restart rails server after creating new bucket and keys 

(#classic)
