### ISSUE TITLE
Renaming routes in Ember? Or components?

### ISSUE THREAD

**Issue by DanielJRaine** [ga-wdi-boston/capstone-project#294]
Is there a convenient way to rename a route without destroying the old one and making a new one?  What about for components?

I'm afraid of just going into my router and changing it there, as well as manually renaming the directories, because I don't know if Ember has saved the old name elsewhere.

**Comment by jrhorn424** [comment]
Does a project-wide search and replace give any additional confidence? How about trying it and noting where it fails?

**Comment by jrhorn424** [comment]
Another clue would be to start with a clean working directory, then to generate and delete a dummy component or route and look at the `git diff`. Then you'll see exactly what the generator does.

**Comment by DanielJRaine** [comment]
Closing for now because I just restarted from scratch and made all new routes.  I can try this later if I have time.  I did however find an add-on ember-cli tool that allows you to rename blueprints, but I have not found any such tool for renaming routes.
