### ISSUE TITLE
[Ember] Creating Records through a join table?

### ISSUE THREAD

**Issue by tuckyeah** [ga-wdi-boston/capstone-project#295]
So the way my data is current set up, a category belongs to a user, and a category has many things _through_ the category_contents table (and vice versa)

I'm working on currently allowing a user to add a new thing to a category list. So first, the Thing has to be created (which I can do successfully) and then I'd like to chain a second AJAX call to the API to create the a new category_contents object joining the Thing and the Category... but I can't figure out how best to serialize this? To be honest, I'm not even really sure how to ask this question haha.

Here's what I have so far.

My createThing action in my category route looks like this, and behaves as expected:
```
    createThing (newThing) {
      let thing = this.get('store').createRecord('thing', newThing);
      thing.save();
    }
```

My Thing model looks like this:
```
export default DS.Model.extend(Copyable, {
  name: DS.attr('string'),
  categories: hasMany('category')
});
```

And my join table, category_contents, model looks like:
```
export default DS.Model.extend(Copyable, {
  done: DS.attr('boolean'),
  notes: DS.attr('string'),
  category: belongsTo('category', {
    inverse: 'category-contents'
  }),
  thing: belongsTo('thing', {
    inverse: 'category-contents'
  })
});

```

Then, in my Thing adapter, I'm trying something like this:
```
  createRecord(store, type, record) {
    let api = this.get('host');

    let serialized = this.serialize(record, {includeId: true});

    let categoryId = record.record.category_id;

    let url = `${api}/things`;

    let data = { thing: serialized };

    this.ajax(url, 'POST', {data})
    .then((obj) => {
      let thingId = obj.thing.id;

      url = `${api}/category_contents`;

      // something here - How to get 'data' to look like a JSON object
      // that just contains the thing_id and the category_id?

      return this.ajax(url, 'POST', data);

    });
```

But i can't figure out how best to do that - Ember doesn't seem pleased when I try to just hardcode the data object, and I'm not sure how to bypass the Thing serializer, or if I'm even on the right track at all...... any advice would be greatly appreciated! Let me know if you need to see more code too.

Thanks!

**Comment by tuckyeah** [comment]
Okay so I've made some adjustments to how I'm tackling this, but I'm still having this (or at least a similar) issue.

I'm now trying to add a new Thing through the category_contents route directly (I've adjusted my backend to make a new thing / find the existing thing when a category_contents instance is created)

So in my Category template (category has its own route), I have the following code:

```
<div style="border: 1px solid black;">{{outlet}}</div>
{{category-contents category=model createThing='createThing'}}
```

The category-contents template makes a call to the 'add-item' component:

```
{{add-item category=category
           createThing='createThing'}}
```

But now I'm getting a weird error that there is no action handler on an unnamed component:

```
"Assertion Failed: <keepr-ember-client@component:-default-0/0185295548862673961478487249891::ember752> had no action handler for: createThing"
```

The component.js for add-item looks like this, and the console log runs, but it won't send the action:

```
export default Ember.Component.extend({
  form: {
    name: null,
  },

  actions: {
    createThing () {
      let newThing = this.get('form');
      newThing.category_id = this.get('category.id');

      console.log("I'm inside the component and newThing is", newThing);
      this.sendAction('createThing', newThing);
      this.set('form.name', null);
    }
  }
});
```

Currently in the category-contents route, my createThing action just has a console log, but it's never even getting that far..... I just have no idea what this mysterious component in between the two is, and why it's stopping my action from 'bubbling up'!

Any suggestions would be helpful - I know this issue is a little convoluted, so let me know if you need further code / examples too :) 

Thank you!!!

**Comment by jrhorn424** [comment]
Hey Tucker! I think we need sit down and unwind this. I suspect some modeling changes will get you what you want.

**Comment by payne-chris-r** [comment]
Did this get resolved @tuckyeah? I'm happy to sit and talk through ti as well.

**Comment by payne-chris-r** [comment]
So typically the way I've done this in Ember is this:

``` js
let thing = this.get('store').createRecord('thing', {});
thing.set('category', this.get('category')) // where `this.get('category')` is the object you want to associate your thing with. Then:
thing.save()
  .catch(errHandler);
```

**Comment by jrhorn424** [comment]
This is a bit of an anti-pattern. If you're passing an object up from a component, it should have its parent attached at by the time it arrives at the router.

``` diff
+ create (thing) {
  let thing = this.get('store').createRecord('thing', thing);
-    thing.set('category', this.get('category')) // do this elsewhere, say on passing a record up through a category
    thing.save()
-    .catch(errHandler); // only catch specific errors related to the record itself here, otherwise let Ember blow up.
```

**Comment by payne-chris-r** [comment]
Step 1: Make it work
Step 2: Make it work correctly
Step 3: Make it work the best way

@tuckyeah I'm somewhere between 1-2...

**Comment by jrhorn424** [comment]
@tuckyeah Any updates since we chatted?

**Comment by tuckyeah** [comment]
Sorry for the delay in finishing up this issue - I ended up refactoring a lot of things, including my API, but it now seems to be working. Thank you all for talking me through this and your help! I'll do my best to write what I have now.

I think the crux of the issue was _where_ I was calling / implementing the add-item (renamed to add-thing) component. I updated my code to put it in in the Category Index template, below the list of a category's items:

```
{{category-list category=model
                edit='edit'
                deleteThing='deleteThing'
                showDetails='showDetails'
                back='back'}}
{{add-thing category=model createThing='createThing'}}
```

And updated the add-thing component.js to look like:

```
export default Ember.Component.extend({
  form: {
    name: null
  },

  actions: {
    createThing() {
      let newThing = this.get('form');
      newThing.category = this.get('category');
      this.sendAction('createThing', newThing);
      this.set('form.name', null);
    }
  }
});
```

In my Category route (where I called the add-thing component), I updated the action for createThing to read:

```
    createThing (newThing) {
      let thing = this.get('store').createRecord('thing', newThing);
      thing.save()
      .then(()=> {
        this.refresh();
      });
    },
```

This will make a POST to the thing/ route, and in my API, I set up a 'build' on Thing to create a new instance of category_contents as well. In the API, in the Thing controller:

```
  def create
    @thing = Thing.new(thing_params)
    @category = Category.find(params[:category_id])

    if @thing.save
      @category.category_contents.create(thing_id: @thing.id, category_id: params[:category_id]);
      render json: @thing, status: :created, location: @thing
    else
      render json: @thing.errors, status: :unprocessable_entity
    end
  end
```

This likely still needs some refactoring, and may change as I'm hoping to work on validating uniqueness of a thing right now / today, but this solution did work so I wanted to post my code and close it out.

Thank you again for your help!
