### ISSUE TITLE
[Ember] Can't get Delete action to fire

### ISSUE THREAD

**Issue by styletabtech** [ga-wdi-boston/capstone-project#298]
Hi! I'm having trouble with my delete action. I've looked through some old issues and even copied over the solution code from the ember resources lesson, but the action doesn't get any further than my first component after the button is clicked. 

How I want this to work: A user can upload photos to their photo library and delete an upload. Currently on the backend I just have a Photos table that includes the attachment settings needed for Paperclip to work with S3. 

To be honest I'm unsure if my current file setup is correct in Ember and/or if I need to rethink the way I'm handling uploads in the backend.. i.e. should an upload be it's own table?

**photo-lib/my-photo component:**
```
export default Ember.Component.extend({
  tagName: 'li',
  actions: {
    delete () {
      console.log('getting to the delete action in my-photo component');
      this.sendAction('deletePhoto', this.get('photo'));
    },
  },
});
```
**photo-lib/my-photo template:** 
```
{{photo.file_name}}
<a href="{{photo.photo_upload_url}}">{{photo.photo_upload_url}}</a>
<button class="btn btn-xs btn-fancy" {{action 'delete'}}>
  Delete
</button>
```
**photo-lib component:** 
```
export default Ember.Component.extend({
  actions: {
  deletePhoto (photo) {
    this.sendAction('deletePhoto', photo);
    console.log('getting to deletePhoto in lib component');
  },
},
});
```
**photo-lib template:** 
```
<ul>
  {{#each photos.photo as |photo|}}
    {{photo-lib/my-photo photo=photo
                         deletePhoto='deletePhoto'}}
  {{/each}}
</ul>
```
**photo route:**
```
export default Ember.Route.extend({
  model (params) {
  return this.get('store').findRecord('photo', params.photo_id);
},

  actions: {
  deletePhoto (photo) {
    console.log('getting to destroyRecord');
    photo.destroyRecord();
  },
},
});
```
**photo template:** 
```
{{photo-lib photo=model
            deletePhoto='deletePhoto'}}
```

**photos template:** 
```
<ul>
{{#each model as |photo|}}
{{photo-lib/my-photo photo=photo}}
{{/each}}
</ul>
```

**Comment by berziiii** [comment]
Check to make sure the action you're passing down matches the action name on the component. Remember the one on the left should exist in the component file in the next level down and the action on the right is on the current levels component. :)

**Comment by styletabtech** [comment]
**Solution:** 
I was calling the same component in multiple files. The current view state I'm rendering shows all photos with the delete button, but I had an additional /photo route that was trying to do the same thing. Since I'd rather have a view that shows all photos with a corresponding delete button, rather than clicking on an image and showing the delete button, I only need the following files:

**my-photo template:**

```
{{photo.file_name}}
<img src="{{photo.photo_upload_url}}">
<button class="btn btn-xs btn-fancy" {{action 'delete'}}>
  Delete
</button>
```

**my-photo component:** 

```
export default Ember.Component.extend({
  tagName: 'li',

  photo: {},
  actions: {
    delete () {
      console.log('getting to the delete action in my-photo component');
      console.log(this.get('photo'));
      this.sendAction('delete', this.get('photo'));
    },
  },
});
```

**photos template:** 

```
<ul>
{{#each model as |photo|}}
  {{photo-lib/my-photo photo=photo delete='deletePhoto'}}
{{/each}}
</ul>
```

**photos route:** 

```
export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('photo');
  },

  actions: {
    deletePhoto (data) {
      let photo = data;
      console.log('getting to destroyRecord');
      console.log(photo);
      photo.destroyRecord();
      this.transitionTo('photos');
  },
},
});
```

**photo model**

```
export default DS.Model.extend({
  file_name: DS.attr('string'),
  photo_upload_url: DS.attr('string'),
});
```

Thanks for the help @berziiii!
