### ISSUE TITLE
One on one request: Ember: to do or not do do

### ISSUE THREAD

**Issue by knoddin** [ga-wdi-boston/capstone-project#299]
Hi, I am having several problems with ember and I am fearing that at this rate, either my approach to ember and my project needs to change, or I need to bail on ember. Could I meet with someone to discuss this soon? Thank you!

ERD: https://www.lucidchart.com/invitations/accept/2628471b-f19f-473d-8172-6c77bb5f683d

I have wireframes drawn out.

**Comment by jrhorn424** [comment]
Yes, I think you're right. I can tell you from past experience that every person that abandons Ember regrets it. Every person I've spoken to this morning that was feeling pain with Ember was feeling pain because their modeling wasn't quite right.

@berziiii or I can meet with you, but I'm unavailable until this afternoon.

**Comment by knoddin** [comment]
Either would be great  - thank you.

**Comment by knoddin** [comment]
Think I am going to re-evaluate my project.

**Comment by payne-chris-r** [comment]
@knoddin did you have a 1-1? I am free this afternoon to chat if you would like.

**Comment by knoddin** [comment]
@payne-chris-r no not yet! that would be great - thank you!

**Comment by knoddin** [comment]
@payne-chris-r actually going to try something out. i'll let you know how it goes and close this for now. thanks.

**Comment by laurenallegra** [comment]
@jrhorn424 @berziiii @payne-chris-r @knoddin 

I have been "feeling the ember pain," too, and after lots of reading and googling, I feel my comfort level with this technology is just not up to par to get a working app that is also even remotely visually impressive. After wrestling with this decision, and thinking about my career goals and my own personal job-hunting timeline, I've decided to go ahead and use the regular front-end "browser-template" instead (along with my Rails-API for the backend). I just wanted to confirm that this was indeed an OK decision: Jeff, I know you mentioned that people regret not using Ember for their capstone projects, but I think for me the benefits of using technologies I'm comfortable with outweigh the downside of not having an Ember app ready for the meet-and-hire. Wondering if there is anything I am missing here in terms of downsides, or do you think my reasoning is sound? 

Thanks for your input!

**Comment by jrhorn424** [comment]
@laurenallegra You _must_ scope well if you're going to do `browser-template`. Keep things simple, prioritize simple features that follow the patterns we've used thus far, try to resist the urge to be extra ambitious since you're making a client switch with about two days left to complete it.
