### ISSUE TITLE
1-on-1 request: Using query, filterby, or filter with DS.store (Ember). Returning all data rather than filtering, or returns nothing at all.

### ISSUE THREAD

**Issue by DanielJRaine** [ga-wdi-boston/capstone-project#300]
I have been trying to filter through all instances of a model by a particular key, but using either store.query, store.filterby, or store.filter is not working correctly.  

top-level route.js.
My models follow the form (written in short-hand with simplifications):

```
artform has-many portfolios has-many sections has-many items
```

An example of my models, which map onto my routes looks like

```
visual (artform)  / fine-art (portfolio)  / portraits (section)  / portrait-1 (item)
```

I am trying to populate my navbar with only links to the relevant portfolios for that artform
My Visual (artform) route.js looks like the following:
```js
// Visual route
export default Ember.Route.extend({
  model() {
     return this.get('store').findAll('portfolio')
  },
});
```

I have a component that takes the models from the store and links to their respect routes by name
```html
{{yield}}
{{!-- models-navbar --}}
{{#each model as |model|}}
  <li>
      {{#link-to (concat parent "." model.name)}}
        {{model.name}}
      {{/link-to}}
  </li>
{{/each}}
```
I am reusing this component at each level of my nested routes so I only have to pass in a model, and it will populate that navbar with its child (hasMany) routes.

In it's current form, this populates the Visual (artform) navbar with links to every portfolio, even ones that do not belong to the Visual artform.  I have been trying to filter out the irrelevant portfolios with the following attempts at my route.js file for the Visual route.
```js
  return this.get('store')
     .then((results) => results.query('portfolio', {artform: 'visual'}));
```
```js
  return this.get('store').query('portfolio', {artform: 'visual'});
```
```js
return Ember.computed('portfolios.@each.visual', function() {
       this.get('store').findAll('portfolio')
       .then(portfolios => {
         return portfolios.filterBy('visual');
       });
     });
```
Either I get all results, unfiltered, or I get nothing at all.

I have found two similar closed issues, through which I found strategies which I used for my methods above, but it's still not working.

**Comment by DanielJRaine** [comment]
I tried using RSVP.filter, didn't work.
I tried using computed properties, didn't work.
I tried using query params.  It didn't work.
I have run out of things to search and to try.
I'm starting to think my entire approach is fundamentally flawed, and I don't know where to go from here.

**Comment by jrhorn424** [comment]
The docs for `filterBy` suggest the signature is for two arguments, key and value. So I suggest the following edit:

``` diff
return Ember.computed('portfolios.@each.visual', function() {
       this.get('store').findAll('portfolio')
       .then(portfolios => {
-          return portfolios.filterBy('visual');
+          return portfolios.filterBy('section', 'visual'); // or wherever 'visual' is stored
       });
     });
```
