### ISSUE TITLE
Delete button not working

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/capstone-project#302]
I looked at issue 298, and it was helpful. I am further than I was before I looked at it. 
I don't think I am targeting what I want with the delete button.
Error message
```
route.js:14 Uncaught TypeError: this.sendAction is not a function(…)
```
bike route.js I am not seeing this console log
```.js
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('bike', params.bike_id);
  },

  actions: {
    edit (bike) {
      this.transitionTo('bike.edit', bike);
    },
        deleteBike (bike, params) {
          console.log('getting to destroyBike');
          console.log(bike);
          bike.destroyRecord('bike', params.bike_id);
          this.transitionTo('bikes');
      },
},
});
```
bike template
```.hbs
{{my-bike bike=model deleteBike='deleteBike' edit='edit'}}
```
bikes route.js I do see this console log. The error points to line 14 here.
```.js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
return this.get('store').findAll('bike');
},

tagName: 'li',

bike: {},
actions: {
  delete () {
    console.log('getting to the delete action in bikes component');
    console.log(this.get('bike'));
    this.sendAction('delete', this.get('bike'));
  },
},

});
```
bikes template The delete button is right next to the bike link. This is how I want to delete a bike
```.hbs
<h2>Bikes</h2>

<ul>
{{#each model as |bike|}}
  <li>{{#link-to 'bike' bike}}{{bike.name}}{{/link-to}}
  {{bike/my-bike bike=bike delete='deleteBike'}}
    Delete
  </button>
  </li>
{{/each}}
```
my-bike component.js file 
```.js
import Ember from 'ember';

export default Ember.Component.extend({
  delete () {
  return this.sendAction('deleteBike', this.get('bike'));
},
});
```

**Comment by berziiii** [comment]
You're actions need to match in the level that you use them. ie, in your `my-bike` component.js file, your action is `delete` but your sending `deleteBike`; This should be `delete`. 

You also have syntax issues, if an closing `</button>` tag with no opening one in the bike template. I also cannot tell where you want the top handler of delete bike. you have it destroying the record on bike.js but you also have an action in `bikes/template.hbs.` 

Can you please reorder your code snippets from bottom level component/template to top route where the action is interacting with the data store?

Thanks

**Comment by rosmith76** [comment]
@berziiii I fixed the two issues you pointed out. I also reworked the code the closer match issue 298. The delete button works, but I am still getting an error??
my-bike template

``` .hbs

<h2>{{bike.name}}</h2>
<h4>Date of Purchase: {{bike.date_of_purchase}}</h4>
<h4>Make: {{bike.make}}</h4>
<h4>Frame: {{bike.frame}}</h4>
<h4>Fork: {{bike.fork}}</h4>
<h4>Fork Last Serivced: {{bike.fork_service}}</h4>
<h4>Brakes: {{bike.brakes}}</h4>
<h4>Brakes Last Bled: {{bike.brake_bleed}}</h4>
<h4>Brake Pads Last Replaced: {{bike.pad_replaced}}</h4>
<h4>Brake Rotors: {{bike.rotors}}</h4>
<h4>Wheels: {{bike.wheels}}</h4>
<h4>Tires: {{bike.tires}}</h4>
<h4>Tubelss Sealant Last Added: {{bike.sealant}}</h4>
<h4>Shifters: {{bike.shifters}}</h4>
<h4>Front Derailleur: {{bike.front_derailleur}}</h4>
<h4>Rear Derailleur: {{bike.rear_derailleur}}</h4>
<h4>Cassette: {{bike.cassette}}</h4>
<h4>Chain: {{bike.chain}}</h4>
<h4>Cranks: {{bike.cranks}}</h4>
<h4>Bottom Bracket: {{bike.bottom_bracket}}</h4>
<h4>Saddle: {{bike.saddle}}</h4>
<h4>Seatpost: {{bike.seatpost}}</h4>
<h4>Stem: {{bike.stem}}</h4>
<h4>Handlebars: {{bike.handlebars}}</h4>
<h4>Grips: {{bike.grips}}</h4>
<h4>Headset: {{bike.headset}}</h4>
<h5>Notes: {{bike.notes}}</h5>
<button class="btn btn-xs btn-fancy" {{action 'delete'}}>
  Delete
</button>
```

my-bike component

``` .js
import Ember from 'ember';

export default Ember.Component.extend({
  delete () {
  return this.sendAction('delete', this.get('bike'));
},
tagName: 'li',

  bike: {},
  actions: {
    delete () {
      console.log('getting to the delete action in my-bike component');
      console.log(this.get('bike'));
      this.sendAction('delete', this.get('bike'));
    },
  },
});
```

bike template

``` .hbs
{{my-bike bike=model delete='deleteBike' edit='edit'}}
```

bike route.js

``` .js
export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('bike');
  },

  actions: {
    deleteBike (data) {
      let bike = data;
      console.log('getting to destroyRecord');
      console.log(bike);
      bike.destroyRecord();
      this.transitionTo('bikes');
  },
},

});
```

bike model.js

``` .js
export default DS.Model.extend({
  name: DS.attr('string'),
  date_of_purchase: DS.attr('string'),
  make: DS.attr('string'),
  frame: DS.attr('string'),
  fork: DS.attr('string'),
  fork_service: DS.attr('string'),
  brakes: DS.attr('string'),
  brake_bleed: DS.attr('string'),
  pad_replaced: DS.attr('string'),
  rotors: DS.attr('string'),
  wheels: DS.attr('string'),
  tires: DS.attr('string'),
  sealant: DS.attr('string'),
  shifters: DS.attr('string'),
  front_derailleur: DS.attr('string'),
  rear_derailleur: DS.attr('string'),
  cassette: DS.attr('string'),
  chain: DS.attr('string'),
  cranks: DS.attr('string'),
  bottom_bracket: DS.attr('string'),
  saddle: DS.attr('string'),
  seatpost: DS.attr('string'),
  stem: DS.attr('string'),
  handlebars: DS.attr('string'),
  grips: DS.attr('string'),
  headset: DS.attr('string'),
  notes: DS.attr('string')

});
```

error message this fires before the delete is complete.

```
ember.debug.js:19160 Error: Attempted to handle event `pushedData` on <client-bmt@model:bike::ember607:7> while in state root.deleted.inFlight.
```

**Comment by berziiii** [comment]
Are you rendering a list of all bikes or a single bike when you see the delete button?

**Comment by berziiii** [comment]
You also may need to make:

``` js
return bike.destroyRecord()
            .then(() => this.transitionTo('bikes'))
            .catch((error) => console.error(error));
```

**Comment by rosmith76** [comment]
Single bike. I will try the code above

**Comment by rosmith76** [comment]
@berziiii that did is. I am able to delete bikes without any errors. 
bike route.js code below

``` .js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('bike');
  },

  actions: {
    deleteBike (data) {
      let bike = data;

      return bike.destroyRecord()
            .then(() => this.transitionTo('bikes'))
            .catch((error) => console.error(error));

  },
},

});
```

**Comment by jrhorn424** [comment]
Great catch on the in-flight error, @berziiii

**Comment by DanielJRaine** [comment]
I had this same problem and found this issue very helpful.  However, I have a nagging sense that we are sending data up when we do `this.get('bike')` within our sendAction.  Thoughts?

**Comment by jrhorn424** [comment]
> sending data up when we do this.get('bike')

Thanks, @DanielJRaine, that's correct. However, that same data was bound down. So it doesn't violate DDAU.

You've got completely isolated layers in your routes and components. They can't talk to each other except through the interface of bindings.

If I send something down, and I don't send it back up, how do I get a reference to it when needed, say for an update action? I query the store. What do I need for that? An id. So I have to send something up. Since I have to send the id up, I might as well send the who object, since that obviates the need to re-query for it.

For a create action, what if I don't send any data up at all, even a POJO? How do I create it? How do I get data from the form into my router? There's no mechanism except by passing a second argument to `sendAction`.

See #310 for a code example that might help illustrate.

**Comment by DanielJRaine** [comment]
Thank you for the explanation.  I think this is an illustration of an overly-simplified catchphrase that obscures what is actually going on.

**Comment by jrhorn424** [comment]
> I think this is an illustration of an overly-simplified catchphrase that obscures what is actually going on.

I value this insight. Thanks.
