### ISSUE TITLE
[EMBER] Create function not working, not passing id in URL

### ISSUE THREAD

**Issue by jenboyd** [ga-wdi-boston/capstone-project#303]
My app is currently set up similarly to Lister-List.

Parties that have many lists. I am trying to create a list. 

I initially was able to create a list that showed up in my API without adding an adapter to the list.

The issue is that it wasn't attaching the party ID and therefore wasn't showing up as associated with that party. 

I then tried to mimic the way lister listr-list is set up and added the adapter to list. It looks the same as the code for item in listr-list.

I get a 404 Error saying :

![screen shot 2016-11-07 at 3 05 39 pm](https://cloud.githubusercontent.com/assets/19177290/20073829/cd21d49a-a4fb-11e6-830e-4867d59c1327.png)

 ```No 'Access-Control-Allow-Origin' header is present on the requested resource.```

So it looks like it's not passing the Party ID to the back end. I'm not sure where I missed a step. I also get the error below when I load all lists. They still load, not sure if this has something to do with it
![screen shot 2016-11-07 at 3 11 11 pm](https://cloud.githubusercontent.com/assets/19177290/20073995/74dc6560-a4fc-11e6-943f-e79f38fd98c9.png)

Any pointers in the right direction would be helpful! I'm a little unclear on how adapters communicate with the back end. 

Here's My Code Relating to Creation of Lists:

List Adapter

```
import ApplicationAdapter from 'capstone-ember/application/adapter';

export default ApplicationAdapter.extend({
  createRecord (store, type, record) {
    let api = this.get('host');
    let serialized = this.serialize(record, { includeId: true });
    let partyId = serialized.party_id;
    let url = `${api}/parties/${partyId}/lists`;

    let data = { list: serialized };

    return this.ajax(url, 'POST', { data });
  },

});
```

List Serializer 

```
import ApplicationSerializer from 'capstone-ember/application/serializer';

export default ApplicationSerializer.extend({
  serialize () {
    let serialized = this._super(...arguments);

    serialized.content = serialized.text;
    delete serialized.text;

    return serialized;
  },

  normalize (model, response) {
    response.text = response.content;
    delete response.content;

    return this._super(model, response);
  },
});
```

List Model
```
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  item: DS.hasMany('item'),
  party: DS.belongsTo('party'),
});

```

Party Model 
```
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  date: DS.attr('date'),
  location: DS.attr('string'),
  lists: DS.hasMany('list'),
});

```

Party Route 
```
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('party', params.party_id);
  },

  actions: {
    createList (newList) {
      let list = this.get('store').createRecord('list', newList);
      list.save();
    },
   },
});

```

Party Template
```
{{party-view party=model
             createList='createList'
             deleteList='deleteList'
             editParty='editParty'
             deleteParty='deleteParty'}}

```

## **Components**

Party-View Component 
```
import Ember from 'ember';

export default Ember.Component.extend({

 form: {
   name: null,

 },

 actions: {

   delete() {
     return this.sendAction('deleteParty', this.get('party'));

   },

   deleteList (list) {
     this.sendAction('deleteList', list);
   },

   edit () {
     this.sendAction('editParty', this.get('party'));
   },

   createList () {
     let newList = this.get('form');
     newList.list = this.get('list');

     this.sendAction('createList', newList);

     this.set('form.name', null);

   },
 },
});
```

Party-View Component Template (Shows all lists associated with a party)
```
<h3 class="party-name">
  {{party.name}}
  <button class="btn btn-xs btn-primary" {{action 'edit'}}>
    Edit
  </button>
  <button class="btn btn-xs btn-danger" {{action 'delete'}}>
    X
  </button>
</h3>

<p>{{party.date}}</p>

<div class="lists">
  {{#each party.lists as |list|}}
    {{party-view/party-list list=list
                            deleteList='deleteList'
                            editList='editList'}}
  {{/each}}
  <form {{action 'createList' on='submit'}}>
    {{input placeholder='Add list'
            class='input-group form-control'
            value=form.name}}

  </form>
</div>
```

**Comment by payne-chris-r** [comment]
@jenboyd see the `014-etc` channel in slack.

**Comment by jenboyd** [comment]
@payne-chris-r Updated issue. Hopefully this is more clear!

**Comment by jenboyd** [comment]
The issue first issue was that my createList function in my component was not attaching the party id properly.

**This :**

```
newList.list = this.get('list');
```

**Should be This :**

```
newList.party = this.get('party');
```

List posts to the front end, but still getting a 404 from the server.

The adapter is sending a URL that looks like this:

```
let url = `${api}/parties/${partyId}/lists`;
```

The API does not expect a nested route.  It expects the line below and to be passed the party ID as a param. Still working on how to pass the Party ID as a param. Removing my adapter file.

```
let url = `${api}/lists`;
```

**Comment by jrhorn424** [comment]
> Still working on how to pass the Party ID as a param

If you're doing this: `newList.party = this.get('party');` then as you pass the `newList` up to the route to be created, it should have an associated party. Ember will add it to the request body, and it will arrive to the backend as part of the request body. Be sure to allow it through strong params.
