### ISSUE TITLE
Relationships in rails

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/capstone-project#304]
My project: People can search for _Simpsons_ episodes and add them to a playlist.

I have already made episodes (route, controller, and a master episodes list from one season of the show).

When I talked to Jeff about this idea, he suggested this particular chart of relationships:
![tables](https://cloud.githubusercontent.com/assets/14143334/20074609/f15b9f46-a4fe-11e6-8db4-a28f6d5ca15e.jpg)

User has one```playlist``` (that was what I had in mind, anyway), and ```playlist```  has many```episodes``` , with a join table called ```queuings```. But what about ```playlist```? Should that be a join table to? A join table to a join table? Sounds weird, but I'm not sure exactly what ```playlists``` role should be, when I think about it.

**Comment by berziiii** [comment]
The way the ERD is drawn, 
a User has many Playlists. 
A Playlist belongs to a User. 
A Playlist has many Episodes through Queings.
A Episode has many Playlists through Queings. 

The way you describe it though, doesn't match your ERD. To be clear, IF you want your relationships to match your ERD drawn, the only join table is Queings.

**Comment by julie1013** [comment]
Yeah, I'd originally thought of the user having many playlists, but I don't see any reason for it. I want to do it as just one playlist. 
So can I have it this way?:

A user has one Playlist
A Playlist belongs to a User
A Playlist has many Episodes through Queuings.
An Episode has many Playlists through Queuings. 

Queuings as the only join table. Does that work?

**Comment by berziiii** [comment]
Yep. That works.

**Comment by julie1013** [comment]
Cool, thanks!

**Comment by jrhorn424** [comment]
This would have also worked:
- User has many playlists.
- Playlist belongs to user.
- Playlist has many episodes through queueings, since:
  - Playlist has many queueings.
  - Episode has many queueings.
  - Queueing belongs to a playlist.
  - Queueing belongs to an episode.

Your ERD has Queueings having many Episodes. That doesn't make sense. The above description supports what you described, only has one join table, and allows a user to have multiple playlists.

**Comment by jrhorn424** [comment]
I am not suggesting you have many playlists for each user. I'm saying its possible using the entity relationships I described above.
