### ISSUE TITLE
[Rails] Playlist is throwing me off

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/capstone-project#307]
A user has one Playlist. Playlists have many episodes (and vice versa).

But going to generate the model for Playlist... what? Playlist. Singular. What should it have?

An episode has a title. What then would a playlist have?? Just title or episode?

**Comment by payne-chris-r** [comment]
Please post your ERD.

**Comment by payne-chris-r** [comment]
Are we talking rails or ember? Please post the framework/language in the title (i.e. `[Ember] Playlist is...`

**Comment by julie1013** [comment]
It's in Rails. Here's the ERD:

![fullsizerender](https://cloud.githubusercontent.com/assets/14143334/20077234/990c88d6-a509-11e6-8d68-1045a002e87e.jpg)

**Comment by berziiii** [comment]
Your ERD needs to have the attributes that a entity in the Playlist table would have; same with an Episode.

**Comment by julie1013** [comment]
OK, but what WOULD a playlist have? FWIW, Episodes has `title`

**Comment by berziiii** [comment]
I don't know, what should it have? This is YOUR passion project so whatever you think a Playlist should have.

**Comment by julie1013** [comment]
OK, I just wanted to make sure I wasn't doing something stupid!
