### ISSUE TITLE
Error: Assertion Failed: You need to pass a model name to the store's modelFor method

### ISSUE THREAD

**Issue by knoddin** [ga-wdi-boston/capstone-project#309]
I am receiving the above error when I post a new. I know that I need to store the data in a model, but when I do that, my template completely disappears and I receive an error 'cannot read property some', which I have learned lives in the application(and I found it). I just tried changing that function per Jeff's instructions in another issue, but haven't yet been able to fix it. I have read several other similar errors, but I am not quite sure how my problem fits in. Currently, my new-park route looks like this (with the return commented out) - 

```js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    //  return this.get('store').findAll('park');
   },

  actions: {

    createPark (data) {
      let park = this.get('store').createRecord('park', data);
      console.log(data);
      return park.save()
      .then(() => this.transitionTo('index'));
    },
  },
});
```

Here is my park model 

```js
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  location: DS.attr('string'),
  description: DS.attr('string'),
  user: DS.belongsTo('user')
});
```
here is my park adapter

```js
import ApplicationAdapter from 'npTracker.knoddin/application/adapter';

export default ApplicationAdapter.extend({
  createRecord (store, type, record) {
    let api = this.get('host');
    let serialized = this.serialize(record, { includeId: true });
    // let parkId = serialized.park_id;
    let url = `${api}/parks`;

    let data = { park: serialized };

    return this.ajax(url, 'POST', { data });
  },

});
```

Please let me know if you need to see anything else.

**Comment by abeers** [comment]
I've had the modelFor error come up a few times, and every time it has been fixed by altering the serializer. I don't know the exact reason, but it has to do with relationships (which you have with your belongsTo). Issue #219 (not sure if that links as I'm on a phone) talks about altering API serializers, which I know some people are doing. I altered the client serializers with an EmbeddedRecordsMixin.

 I'm happy to help tomorrow if that explanation wasn't enough ☺

**Comment by knoddin** [comment]
@abeers you are seriously amazing. Thank you! I was focusing lots on the client, but changed my api park serializer to include this:

``` rb
  def user
    object.user.id
  end
```

it worked! thank you so much!

**Comment by jrhorn424** [comment]
To anyone finding this issue, please look at `listr-api`'s serializers to discover how we produce that magical format that Ember understands... :smile:

**Comment by jrhorn424** [comment]
The technique used in the API serializers is called "side-loading" and for the _client_ serializer and adapter, the expectation is that Ember receives an array of child IDs for hasMany relationships, and a single parent ID for belongsTo relationships in each respective API response.

**Comment by ctripti** [comment]
@knoddin 
@abeers i am also getting error this in my model - product.js  i have belongsTo relation
deviceShareCapability:DS.belongsTo('product-deviceSharing'),
and in my product.js serializer i have this code 
export default JSONSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    
    icons: {embedded: 'always'},
    hardware: {embedded: 'always'},
    countries: {embedded: 'always'},
    deviceShareCapability: {embedded: 'always'}
  }
, now as per your suggestion    def user
    object.user.id
  end

we should include something like this so ember get the id in case of belongsTo 
can you please suggest me in my serializer where i can add this n how ???
Please its urgent , i will be very grateful
