### ISSUE TITLE
[Ember] Delete resource works, but an error is thrown

### ISSUE THREAD

**Issue by abeers** [ga-wdi-boston/capstone-project#310]
Here is my route that resolves the delete action from the component.

```js
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('team-member', params.member_id);
  },
  actions: {
    deletePokemon(member) {
      return this.get('store').findRecord('team-member', member.get('id'))
      .then((record) => {
        record.destroyRecord();
      })
      .then(() => {
        this.transitionTo('team.breakdown');
      })
      .catch(() => {
        this.get('flashMessages')
        .danger('There was a problem. Please try again.');
      });
    }
  }
});
```

When I use it, it works. The record is deleted on the front end and persists to the back end, and it transitions to the new route, all while updating the data shown on the page. However, the console shows this error: 
```
ember.debug.js:19160 Error: Attempted to handle event `pushedData` on <destiny-knot@model:team-member::ember1523:41> while in state root.deleted.inFlight. 
```
I don't know how to fix it or what the problem is. I've tried `unload record` (http://emberjs.com/api/data/classes/DS.Store.html#method_unloadRecord), my backend is giving me a 204 (http://stackoverflow.com/questions/28387693/ember-promise-destroyrecord-then-failing-on-successful-request), and I tried removing a reference to one of the table relationships (team-member is a join between team and pokemon).

Like I said, everything works as far as I can tell. I just don't like that the error is popping up.

**Comment by berziiii** [comment]
Thoughts that this might be a race condition somewhere? @jeffh?

**Comment by berziiii** [comment]
@jrhorn424^

**Comment by abeers** [comment]
If it's a race condition, it's a very consistent one. The record is always deleted successfully and the error always pops up. It also doesn't trigger the .catch statement unless I mess with the code enough. I tried grouping statements into the same .then, separating them out as much as I could, and everything in between.

The one thing that appeared to work was 

``` js
record.deleteRecord();
record.unloadRecord();
record.save();
```

Somewhat obviously though, that did not persist to the database. It did remove the error though, so I'm guessing it has something to do with the save function.

**Comment by payne-chris-r** [comment]
I'm not sure, but I think you're gobbling your error here:

``` js
.then((record) => {
        record.destroyRecord();
      })
```

you man need to 

``` js
.then((record) => {
      return record.destroyRecord();
      })
```

OR

``` js
.then((record) => {
  record.destroyRecord()
    .then(() => {
      this.transitionTo('team.breakdown');
    })
    .catch...
  })
  .catch...
})
```

I can't remember if the nested promise will spit out into the final catch or not. I also know there's a better way to do this, but at this point I'd like to see it work, then see it work the right way. Either way, I think `destroyRecord()` is returning a promise that isn't getting fulfilled before the next `.then()` runs...

**Comment by rosmith76** [comment]
@abeers I was getting the same/similar error in issue 302.
https://github.com/ga-wdi-boston/capstone-project/issues/302

**Comment by jrhorn424** [comment]
Yep, deleting is a network operation, so anything after it needs to happen in `.then`.

**Comment by jrhorn424** [comment]
`destroyRecord` returns a Promise so making the change @payne-chris-r suggested should do the trick.

http://emberjs.com/api/data/classes/DS.Model.html#method_destroyRecord

**Comment by jrhorn424** [comment]
(FWIW, `destroyRecord` returns a promise since it's just a `deleteRecord` followed by a `save`, and `save` returns a Promise.)

**Comment by abeers** [comment]
Found it. It wasn't really any of the above, but it kind of was?

``` js
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('team-member', params.member_id);
  },
  actions: {
    deletePokemon(member) {
      return this.get('store').findRecord('team-member', member.get('id')) // This line is the problem
      .then((record) => {
        record.destroyRecord();
      })
      .then(() => {
        this.transitionTo('team.breakdown');
      })
      .catch(() => {
        this.get('flashMessages')
        .danger('There was a problem. Please try again.');
      });
    }
  }
});
```

I don't think it liked that member was already a team-member record, then I went to the store to get the same record, and I deleted the "new" record. I honestly don't know if member or record was the cause of the error, but removing the step in which I send the get request resolved the error.

Working code:

``` js
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('team-member', params.member_id);
  },
  actions: {
    deletePokemon(member) {
      return member.destroyRecord()
      .then(() => {
        this.transitionTo('team.breakdown');
      })
      .catch(() => {
        this.get('flashMessages')
        .danger('There was a problem. Please try again.');
      });
    }
  }
});
```

Thanks!

**Comment by jrhorn424** [comment]
Oh, great catch! There's no reason to query the store if you're passing an instance of an object in the store to a method. I think this may make that clearer:

``` diff
// you've got an instace of `member`, and you're using it's id to get... itself?
- return this.get('store').findRecord('team-member', member.get('id'))
+ return member.destroyRecord()
// Yeah, don't query for it, use it!
```
