### ISSUE TITLE
One on one tomorrow?

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/capstone-project#311]
I'd like to have a one-on-one tomorrow if possible. There isn't a particular pressing issue, but I think it would help to check in with someone to make sure I'm on the right track.

**Comment by berziiii** [comment]
Please provide more context. What would you like to discuss? What do you want clarification on? What are you working on? We need information like this to help, Julie.

**Comment by julie1013** [comment]
Fair enough. I just wanted to show one of you what I've been doing so far and get some feedback.

What I have now: 

Components and routes and models on the front end.

On the backend I'm setting up tables and have already made seeds for the episodes table.

**Comment by jrhorn424** [comment]
@berziiii @julie1013 Any updates?

**Comment by julie1013** [comment]
Yes, Brian is awesome and did a 90-minute one-on-one with me. There's actually an issue on the front end that even Brian hasn't figured out. I'm going to go to lunch and look at it after, and he's going to think about it.

**Comment by jrhorn424** [comment]
Great. If you can describe the issue, I can give my 2 cents remotely and help you, along with @berziiii.

**Comment by julie1013** [comment]
Thanks! Here is the issue, which I've just opened: https://github.com/ga-wdi-boston/capstone-project/issues/320
