### ISSUE TITLE
[Ember] Accessing data through join table

### ISSUE THREAD

**Issue by jenboyd** [ga-wdi-boston/capstone-project#312]
I am having trouble accessing my items table from the party route using ember.  When users go to a specific party route they should be able to see all lists and all items associated with those lists. 

![screen shot 2016-11-07 at 9 04 12 pm](https://cloud.githubusercontent.com/assets/19177290/20084019/c4e8b6fe-a52d-11e6-82c0-e9ce7c548baa.png)

I have my relationships set up in the back end so that the list route looks as shown below (Note that i changed Items-Used to Item-Instances):

![screen shot 2016-11-07 at 9 07 38 pm](https://cloud.githubusercontent.com/assets/19177290/20084090/4b0155c0-a52e-11e6-82bd-095f314b2db5.png)

The route to parties on the back end looks like this:
![screen shot 2016-11-07 at 9 09 52 pm](https://cloud.githubusercontent.com/assets/19177290/20084143/8c77640e-a52e-11e6-830c-384635def78c.png)

I have tried making the entire item object available to the lists route (instead of just the id), still no ember objects for items showing in the inspector.

I have the relationships defined in each of the models. 

Questions:

1. Am I able to access the nested items through the party route? 

2. Do I need to be a able to see the item object when looking at the party route?

3. Do I need a model for item_instances on the front end? I don't currently have one.

**Comment by jrhorn424** [comment]
> Am I able to access the nested items through the party route?

Assuming the relationships are correct, I believe so. We might need to specify an asynchronous option (false) to force eager loading of the intermediary model (list). Also, it's a bit tricky, since you're traversing a hierarchy. You'll need to likely use nested `each` in your handlebars (this may be unavoidable).

Will you post your client models, or link to them?

> Do I need to be a able to see the item object when looking at the party route?

I don't know. That's up to you. Got links to your wireframes or user stories? Can you describe what you'd like to see on the party route?

> Do I need a model for item_instances on the front end? I don't currently have one.

Probably, if that's where you're going to write to. I imagine someone is on a screen somewhere for a particular list, clicks an item (dropdown maybe?), and that adds to list through `item_instances`.

**Comment by jrhorn424** [comment]
@jenboyd Please update when you get a moment. I know you told me this morning you had made progress, but if you have anymore questions I'd like to help remotely from Providence this afternoon if I can.

**Comment by jenboyd** [comment]
@jrhorn424 , I figured out how to access the item_instance id with ember and display it in the view. I wasn't able to figure out how to get the item data to show up. I had initially decided to use a join table between items and lists so that users would be able to view past items they had created and possibly add that to another list. I decided to go ahead and leave that as a phase 2 feature. I removed the join table on my back end and made the relationship between lists and items one to many. I'll be able to retrieve the item information similar to how I was getting item_instances. 

I was able to used nested `each` statement as you suggested and this piece of code `{async: true}),`

This JS Bin link was helpful in understanding how to get data from nested one to many relationships:
[http://emberjs.jsbin.com/wuhag/1/edit?html,css,js,output](url)

Here's what my models look like. I still don't have it working because I made the changes in my back end. I can post my final working code when I get there.

**My Models:**

Lists

```
export default DS.Model.extend({
  name: DS.attr('string'),
  item: DS.hasMany('item', {async: true}),
  party: DS.belongsTo('party')
});
```

Items

```
export default DS.Model.extend({
  content: DS.attr('content'),
  list: DS.belongsTo('list', {async: true}),
  party: DS.belongsTo('party', {async: true})
});
```

**Comment by jrhorn424** [comment]
Great! I think async is true by default. You don't have to specify it. You would need to specify it as false in order to eager load intermediary models so that they exist when you're trying to reach through them in a nested fashion.

I'm wondering whether `{async: false}` would have helped your issue before you got rid of the join table...

I still think descoping a bit was wise. Good call. :+1:

**Comment by jenboyd** [comment]
@jrhorn424, I'm back at the point I was before..That is trying to display items on lists. I removed the join table so I just have Parties that have many lists, which have many items.  I can access the item id, but not it's content. (The item table does have a "content" column, could naming be the issue?)
- My models show the correct relationships (turns out I didn't need to add async = true, and I can't get the item id when I set it to false)
- The ember inspector shows the id and the content as "undefined"
- My serializers are set up on  my back end as shown below:

Party Serializer

```
class PartySerializer < ActiveModel::Serializer
  attributes :id, :name, :date, :location, :lists, :user
  belongs_to :user

  def lists
    object.lists.pluck(:id)
  end

  def user
    object.user_id
  end
end
```

List Serializer

```
class ListSerializer < ActiveModel::Serializer
  attributes :id, :name, :party, :user, :items

  def items
    object.items.pluck(:id)
  end

  def party
    object.party_id
  end

  def user
    object.user_id
  end
end
```

Item Serializer

```
class ItemSerializer < ActiveModel::Serializer
  attributes :id, :content, :list

  def list
    object.list_id
  end

end
```
- I tried removing the `.pluck(:id)` from the item method definition, but I don't think ember can read that.

Any advice on what to try next? Let me know if you need to see other code. Thanks!

**Comment by jrhorn424** [comment]
Can you tell me again precisely what isn't working? Error messages or bad view state maybe?

**Comment by jenboyd** [comment]
No error messages. I have the components set up to show the items, but I'm not seeing any in the view. In the ember inspector I can see that number of items and the item id, but no content.

**Comment by jrhorn424** [comment]
Thanks @jenboyd. Come find me in about 15 minutes in the classroom and I'll see what we can do.

**Comment by raq929** [comment]
@jenboyd was this issue resolved? If so, please comment with how you resolved it and close the issue. Thanks!

**Comment by jrhorn424** [comment]
@jenboyd Please close.

Our work is here, please review commit messages for insights.
- api: https://github.com/jenboyd/capstone-api/commit/81a764ca356ffc1d1db622a44a7ed929250a80e5
- client: https://github.com/jenboyd/capstone-ember/commit/fee05e510836acc2371b8556e77622edd767439b
