### ISSUE TITLE
Review Request for a refactored ERD

### ISSUE THREAD

**Issue by styletabtech** [ga-wdi-boston/capstone-project#313]
Hi! I'm having trouble wrapping my head around my original ERD I had below: 

![screen shot 2016-11-07 at 9 51 34 pm](https://cloud.githubusercontent.com/assets/20650779/20085102/8c973bb6-a534-11e6-8939-ccfcae7d6ee3.png)

A User has many photos. A Photo belongs to a Gallery. A Gallery has many Photos and Spots. A Spot belongs to a Gallery. However I'm just having trouble visualizing how this will work with the gallery (the name might also be whats throwing me off). I first set it up this way because I wanted a user to only upload one photo with one tag (patch) to one spot, but I don't think that's great user experience.

Here's how I've refactored instead, so that the Photos table joins Users and Spots with the tag being a boolean on the Spots table, though I'm still a little unsure how I'll attach the spot_id to the photo.  I'd like to get feedback on whether this is a more suitable setup to allow users to upload more than one photo to a spot. If it easier to chat in person I can do that too. Thank you!

![screen shot 2016-11-07 at 9 51 40 pm](https://cloud.githubusercontent.com/assets/20650779/20085110/92b799aa-a534-11e6-954f-61de7eee882a.png)

**Comment by jrhorn424** [comment]
> Here's how I've refactored instead, so that the Photos table joins Users and Spots

I like this!

> with the tag being a boolean on the Spots table,

Why a boolean? When I hear "tag" I think a string description like "sunset".

> though I'm still a little unsure how I'll attach the spot_id to the photo. 

The user would need to create a spot first if it didn't already exist. Once the spot is there, whatever viewstate shows the spot is where I'd but the upload button for the photo. Then, you'll always be in the right context to grab a spot object using the patterns we looked at with Listr.

> I'd like to get feedback on whether this is a more suitable setup to allow users to upload more than one photo to a spot.

This accomplishes that. Simple is better. You should have a user story that requires you to break this modeling in order to "search for alternatives". Don't look for them just to look for them. The use cases define the model, not the other way around.

> If it easier to chat in person I can do that too. Thank you!

I don't mind chatting, but I'd like to hear your thoughts first.

**Comment by styletabtech** [comment]
Thanks @jrhorn424! Here are some more thoughts on my approach for this:
- The main reason for refactoring was that I initially had a user story that was: 'As a user I want to create a spot and upload my photo to it' in addition this one: 'As a user I want to view an existing spot and upload my photo to it'. After having my 1:1 with Brian he suggested for phase 1 to stick with the second story and seed the db with a some spots in a few major cities and then have users be able to upload their photos to a specific spot. As I was building out my Spots table today I realized having a simpler ERD might be better, plus I really wanted to be able to let users create a spot. 
- Tags: At first I was thinking of hardcoding in the tag names and then setting them to true/false in my seed data, but I think it might be better to just have a dropdown for a user to select one tag or a string description as you mentioned. 
- For creating a spot, do you think it would be best that that form not include the option to upload? I was already planning to have an 'add your photo' button on the view state that shows a single existing spot, but just curious if it might get too tricky having two forms w/ uploads - one for creating a spot and one for adding a photo to an existing spot. 
- Lastly, Is it correct to say that the proper relationship establishment for my new ERD be: a user has many spots through photos?

Appreciate this feedback and the advice not just to look for alternatives, I will keep that in mind moving forward! I think part of me just couldn't let that create a spot user story go which prompted me to revisit this.

**Comment by jrhorn424** [comment]
> The main reason for refactoring was that I initially had a user story that was: ...

Your second ERD is better, but I think it's actually a good idea to have users create spots.

> ... dropdown for a user to select one tag or a string description as you mentioned.

Either is superior to a bunch of boolean columns.

> For creating a spot, do you think it would be best that that form not include the option to upload? I was already planning to have an 'add your photo' button on the view state that shows a single existing spot, but just curious if it might get too tricky having two forms w/ uploads - one for creating a spot and one for adding a photo to an existing spot.

That's the beauty of SPAs. If you structure and style your viewstates appropriately, it won't look like two different forms. I create a spot, I see the spot immediately with a form to upload below it. Seamless.

> Lastly, Is it correct to say that the proper relationship establishment for my new ERD be: a user has many spots through photos?

Yes.

**Comment by styletabtech** [comment]
Thanks @jrhorn424! All makes sense. Feeling much better with this refactored approach.
