### ISSUE TITLE
reordering columns in Rails table

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/capstone-project#314]
Seems like it ought to be a straightforward task, but hey, it's Rails... how do reorder a column in a Rails table? For example, the column in question might be 3rd but I want it to be 1st instead?

**Comment by jrhorn424** [comment]
Columns don't get sorted until you ask for them that way. We did some of that in the SQL lesson. And it isn't like sorting a spreadsheet. It isn't permanent, it's only a "view" of your data that is sorted.

Search for "sort rails activerecord collection".

**Comment by julie1013** [comment]
OK, thanks!
