### ISSUE TITLE
Current user setup issues

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/capstone-project#315]
Prior to setting up current user, delete worked in the browser and via curl requests. I set up current user the same way I did with project two, and I am getting a 500 error. 
```
NoMethodError (undefined method `bikes' for #<User:0x007fa273ca1a30>):
```
I get the same error on create as well. I can only test that via curl requests at this point
```.rb
  def create
    @bike = current_user.bikes.build(bike_params)

    if @bike.save
      render json: @bike, status: :created, location: @bike
    else
      render json: @bike.errors, status: :unprocessable_entity
    end
  end
```

```.rb
  def set_bike
    @bike = current_user.bikes.find(params[:id])
  end
```

**Comment by jrhorn424** [comment]
What defines methods on your user? If a user has bikes, what creates the `bikes` method?

**Comment by jrhorn424** [comment]
Are you stuck? What have you tried?

**Comment by rosmith76** [comment]
I am stuck. If I remove current user it works. I have also tried using bike without the s. I got the same error.

**Comment by jrhorn424** [comment]
> What defines methods on your user? If a user has bikes, what creates the bikes method?

**Comment by rosmith76** [comment]
A user creates bikes. When I first set it up I was not passing a user ref to the bikes table. I added that in last night. I think that might be where the issue is. I have two users set up so far. I removed current user code, and created several bike for each user with curl requests. Then I implemented code to only show current users bike when I fire an index request. I get a 200 OK, but I don't see any bikes??

``` .rb
  def index
    @bikes = Bike.where("user_id=#{current_user.id}")
    render json: @bikes

  end
```

**Comment by jrhorn424** [comment]
Please show me your model for User and Bike.

**Comment by rosmith76** [comment]
My model for bike and user were not set up correctly. They are now, and index, delete etc work as expected via curl requests and through the front end. 
bikes model

``` .rb
class Bike < ActiveRecord::Base
  belongs_to :user
end
```

user model

``` .rb
class User < ActiveRecord::Base
  include Authentication
  has_many :examples
  has_many :bikes
end
```
