### ISSUE TITLE
Issue deploying ember client to gh-pages

### ISSUE THREAD

**Issue by wmcb91** [ga-wdi-boston/capstone-project#317]
I just went through the deployment guide for an ember client and ran into an issue somewhere between the build and push to gh-pages.  I made sure all instances of the 'ga-wdi-boston.ember-auth' were replaced with my app name.  I also added the production environment that looks like this 
```js
  if (environment === 'production') {
    ENV.baseURL = '/';
    ENV.locationType = 'hash';
    ENV.apiHost = 'https://flix-with-friends.herokuapp.com';
  }
```

I committed these changes to my master branch then created a gh-pages branch with `git checkout -b gh-pages` as usual.  Then, in the .gitignore file, I changed line 260 so now the file looks like this.
```
257  ### Ember ###
258  # see https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/gitignore
259  # compiled output
260  # /dist 
270  /tmp
```

I checked `git status`, saw only .gitignore had been modified, then added and committed the change.  After committing, I ran `ember build --environment=production` then git status when the build was complete.  The output in my console was 
```sh
~/wdi/projects/capstone-client (gh-pages)$ ember build --environment=production
Built project successfully. Stored in "dist/".
File sizes:
 - flix-with-friends-5aa9bfcffad11415d15ce3349cd996b0.css: 131.57 KB (21.53 KB gzipped)
 - flix-with-friends-e620a20b6833ba90f2dd1c9691f7552a.js: 50.57 KB (6.6 KB gzipped)
 - vendor-a7265848c9271d9ec51814d9e4121337.js: 719.06 KB (191.56 KB gzipped)
 - vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
~/wdi/projects/capstone-client (gh-pages)$ git status
On branch gh-pages
nothing to commit, working tree clean
```
which looked strange since step 7 in the deployment guide implied there would be file changes.  I didn't particularly expect the next step to work but ran it anyway and got this output
```sh
~/wdi/projects/capstone-client (gh-pages)$ git subtree push --prefix dist origin gh-pages
git push using:  origin gh-pages
No new revisions were found
```

Have any suggestions for working through this issue?  Thanks.

**Comment by wmcb91** [comment]
Solution found: 

If you run into this issue type `less ~/.gitignore` in your console and look at the top lines of the output.  If they look like this

```
### Ember ###
# see https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/gitignore
# compiled output
/dist
/tmp
```

/dist is being ignored globally so you have to type `atom ~/.gitignore` and put a # in front of /dist on line 7 then save the file.  Things should work after that.

**Comment by jrhorn424** [comment]
Thanks @wmcb91!
