### ISSUE TITLE
Cannot patch number in database using ember.

### ISSUE THREAD

**Issue by Nishkixs** [ga-wdi-boston/capstone-project#318]
I am using ember try and patch a number in rails. The patch seems to go through but it is not actually updating. I am able to patch strings/text which do update. 

I have tried parseInt() within my component.js and getting parseInt is not a function as an error.

Below is my component template code as well is my component.js
```

<form {{action 'buyfund' on='submit' }}>
  {{input placeholder='#Amount' type='number'
          class='input-group form-control'
          value=fund.fundbalance
        }}
  <button type="submit" class="btn btn-xs btn-primary">Buy</button>
</form>

```

```

import Ember from 'ember';

export default Ember.Component.extend({

  actions: {
    buyfund () {
      let fund = this.get('fund');
      this.sendAction('save', fund);

    },

  },
});

```
Below is what I have tried.
```

import Ember from 'ember';

export default Ember.Component.extend({

  actions: {
    buyfund () {
      let fund = this.get('fund').parseInt();
      this.sendAction('save', fund);

    },

  },
});

```

**Comment by jrhorn424** [comment]
What is rails saying about it?

**Comment by jrhorn424** [comment]
Also, you probably don't want to pass up a number. That doesn't make much sense. You want to pass up the whole object. I can't know what's failing until we look at your API. Look specifically for incoming parameters. Do they match your strong parameters? Do they have the right format (rooted)? Are validations or something preventing the save? etc.

**Comment by Nishkixs** [comment]
Issue Solved: 
I added a column to my funds table through the command line and forgot to permit it in my funds controller.
