### ISSUE TITLE
1:1 Request to discuss patching with a file upload

### ISSUE THREAD

**Issue by styletabtech** [ga-wdi-boston/capstone-project#321]
I'd like to discuss how to approach updating a spot by adding a photo upload to the spot. 

Currently, my photo upload service is
```
export default Ember.Service.extend({
  ajax: Ember.inject.service(),

    newPhotoUpload (newPhoto) {
      console.log('newPhoto in service is', newPhoto);
      return this.get('ajax').post('/photos', { 
        data: newPhoto, // The FormData object which we have called `newPhoto`
        contentType: false,
        processData: false,
      });
     },
});
```

My new-photo route is 
```
export default Ember.Route.extend({
  uploads: Ember.inject.service(),

  actions: {
    createPhoto(newPhoto) {
        return this.get('uploads').newPhotoUpload(newPhoto) 
       .then(() => this.transitionTo('photos')) 
       .catch((error) => console.error(error));
    },
  },
});
```

I'm not entirely sure how:
- to bundle up posting a new photo with patching a spot
- how to route a successful upload back single spot view state with a new photo on it
- how to pass down the spot id so that it gets associated with that photo upload

**Comment by jrhorn424** [comment]
Pass the photo up to route along with the spot, create the new photo using the upload service, then (literally, in a `then`) use the store  to patch the spot.

**Comment by styletabtech** [comment]
Spoke with Brian about this and I think I have a handle on it now. Thanks @jrhorn424!

**Comment by jrhorn424** [comment]
@styletabtech You've prompted a great discussion on modeling. You may have even created a study or a challenge in the process.

Let's talk about naming at some point. It's a low priority right now.

Here's our notes: https://www.evernote.com/l/AAFGzX5zy6NDsJAL_W4JeXPRMdJuCX2ETa4

**Comment by styletabtech** [comment]
Sounds good @jrhorn424 definitely want to continue the convo at some point. Opening this back up because I'm having trouble understanding how my form data should be set up and how to pass the spot id with that form data, as well as how to transition back to the single spot view state with a successful upload. My join table is photos  and my uploads table houses the upload url from S3. cc: @berziiii 

this is my current setup in ember: 

when a user clicks on the button in a single spot view, the view state changes to the **new-upload route:**

```
export default Ember.Route.extend({
  uploadImage: Ember.inject.service(),

  actions: {
    createUpload(newUpload) {
       console.log(newUpload); 
       return this.get('uploadImage').newUploadService(newUpload) 
      .then(() => this.get('uploadImage').newPhotoService(newUpload))
      .then(() => this.transitionTo('spot')) 
      .catch((error) => console.error(error));
    },
  },
});
```

**new-upload component:** 

```
{{new-upload-form create='createUpload'}}
```

**new-upload form template:** 

```
<form enctype="multipart/form-data" id="new-upload-form" {{ action 'create' on='submit' }}>
  <fieldset>
    <legend>Add A Photo</legend>
    <!-- <input type="text" class="form-control" name="photo[file_name]" placeholder="Image Name"> -->
    <input type="file" name="upload[image]" value="Upload Photo">
    <input type="hidden" name="upload[spot_id]" value="{{spot.id}}">
    <input type="submit" class="btn btn-success" name="submit" value="Add Photo">
  </fieldset>
</form>
```

**new-upload-form component:** 

```
export default Ember.Component.extend({

  newUpload: {}, // New movie object being constructed from the form

  actions: {
    create() {
      let newUpload = new FormData(document.getElementById('new-upload-form')); 
      this.sendAction('create', newUpload); 
      this.set('newUpload', null); 
    }
  }

});
```

**my upload service:** 

```
export default Ember.Service.extend({
  ajax: Ember.inject.service(),

  newUploadService (newUpload) {
    return this.get('ajax').post('/uploads', { 
      data: newUpload,
      contentType: false,
      processData: false,
    });
  },

newPhotoService (newUpload) {
    return this.get('ajax').post('/photos', { 
      data: newUpload, 
      contentType: false,
      processData: false,
    });
  },
});
```

**Comment by raq929** [comment]
@styletabtech Are you getting an error? What happens when you run this code?

**Comment by styletabtech** [comment]
@raq929  in the console I get:

```
Ember AJAX Request POST http://localhost:4741/uploads returned a 0↵Payload (Empty Content-Type)↵"""
```

and in rails I get: 

```
NoMethodError (undefined method `id' for nil:NilClass):
  app/serializers/upload_serializer.rb:6:in `user'
  app/controllers/uploads_controller.rb:24:in `create'

```

upload serializer is:

```
class UploadSerializer < ActiveModel::Serializer
  attributes :id, :image_url, :photos, :spots
  has_one :user

  def user
    object.user.id
  end

  # def spots
  #   object.spot.id
  # end
end
```

uploads controller is:

```
  def create
    @upload = Upload.new(upload_params)

    if @upload.save
      render json: @upload, status: :created, location: @upload
    else
      render json: @upload.errors, status: :unprocessable_entity
    end
  end
```

params in the controller:

```
    def upload_params
      params.require(:upload).permit(:user_id, :image)
    end
```

**Comment by jrhorn424** [comment]
@styletabtech Assuming the relationship is setup such that Upload `belongs_to :user` in the model layer, and you have a `user_id` foreign key on the `uploads` table:

``` diff
class UploadSerializer < ActiveModel::Serializer
-  attributes :id, :image_url, :photos, :spots
+  attributes :id, :image_url, :photos, :spots, :user
-  has_one :user

  def user
-    object.user.id
+    object.user_id
  end

  # def spots
  #   object.spot.id
  # end
end
```

**Comment by styletabtech** [comment]
Hi @jrhorn424 Brian helped me get the new upload to render on the spot. However, after I nuke paved, I'm still getting the following error:

```
Assertion Failed: You need to pass a model name to the store's modelFor method
```

My serializers are using  `user_id` and I'm not entirely sure how to debug this. Additionally, my view state for a single spot only renders the first image that gets upload, when an additionally uploads are made, they are showing up in the backend but they don't render unless I refresh the page. Here's my route for uploading a new photo to a spot:

```
export default Ember.Route.extend({
  uploadImage: Ember.inject.service(),

  actions: {
    createPhoto(newPhoto) {
        return this.get('uploadImage').newPhotoUpload(newPhoto) 
       .then(() => this.transitionTo('spot')) 
       .catch((error) => console.error(error));
    },
  },
});
```

Here's the code for rendering the images: 

spots-gallery/single-post template: 

```
 <img src={{upload.image_url}}>
 <button class="btn btn-xs btn-fancy" {{action 'delete'}}>
   Delete
 </button>
```

spot template:

```
<ul>
{{#each model.uploads as |upload|}}
  {{spots-gallery/single-spot upload=upload delete='deleteUpload'}}
{{/each}}
</ul>
```

upload template: 

```
{{spot spot=model delete='deleteUpload'}}
```

I've tried adding .then (() => this.refresh('spot')) after the transitionTo but that didn't help. The images were initially all rendering under a single spot before I implemented the user file upload. Thoughts?

**Comment by payne-chris-r** [comment]
Update? I think this had to do with the serializer not returning the data Ember was expecting other times I've seen that error. Wast that the case with this one?

**Comment by styletabtech** [comment]
@payne-chris-r about to tackle this with Jeff! But yea he thinks it has do with the way my join is set up as well as the serializer. I'll report back soon with an update.

**Comment by jrhorn424** [comment]
@styletabtech Would you mind linking directly to the commit(s) we worked on together? Thanks.
