### ISSUE TITLE
Delete button does not have access to data passed down. (Ember)

### ISSUE THREAD

**Issue by DanielJRaine** [ga-wdi-boston/capstone-project#322]
I am trying to delete a photo by making a button with the 'delete' action right next to each photo I render.  When I `console.log(this.get('item'))` within my component's delete action, I get undefined as the value.  How do I pass this data down?

P.S.: I have gone through every other issue regarding delete buttons failing and have not been able to solve my issue by following their advice.  The only difference I have noticed is that I have an #each loop when making my delete buttons next to the items that they are supposed to be deleting.

**route.js** musician-portraits route
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return this.get('store').query('item', {portfolio: 'fine-arts'});
    // return this.get('store').findAll('item');
  },
  item: {},
  actions: {
    destroyItem (data) {
      let item = data;
      console.log('item: ',item);
      return item.destroyRecord()
      .catch((error) => console.error(error));
    },
  }
});
```

**template.hbs** : musician-portraits template which renders item-gallery-frame template
```hbs
{{outlet}}
{{#link-to 'new-item'}}Upload Item{{/link-to}}

<ul style="list-style: none">
  {{item-gallery-frame items=model delete='destroyItem'}}
</ul>
```

**template.hbs** : item-gallery-frame template
```hbs
{{yield}}
{{#each items as |item|}}
<button {{action "delete"}}>Delete</button>
  <li><img src={{item.body}}/></li>
{{/each}}
```

**component.js** : item-gallery-frame component
```js
import Ember from 'ember';

export default Ember.Component.extend({
  tagName: 'div',
  actions: {
    delete() {
      console.log("in destroy item component: ", this.get('item'));
      this.sendAction('delete', this.get('item'));
    },
  },
});

```

**Comment by DanielJRaine** [comment]
Solved.  I moved my {{#each}} loop outside the component and put it in the route template.  This allowed me to pass single items down to the component rather than my entire array of items, which is what was happening before.

**new route template**

``` hbs
{{#link-to 'new-item'}}Upload Item{{/link-to}}
{{#each model as |item|}}
  <ul style="list-style: none">
    {{item-gallery-frame item=item delete='destroyItem'}}
  </ul>
{{/each}}
```

**new component**

``` hbs
<button {{action "delete"}}>Delete</button>
  <li><img src={{item.body}}/></li>
```

**Comment by knoddin** [comment]
Hmmm...not so far, unfortunately! My {{#each}} loop is already in my template. I tried moving my buttons for into the component template, but now they do not show up.
