### ISSUE TITLE
[Ember] storing & retrying transitions w/o using a controller?

### ISSUE THREAD

**Issue by rhjones** [ga-wdi-boston/capstone-project#323]
I'd like to build functionality that will prevent a user from accessing a specific route if they're not authenticated, redirect them to the sign in page, then, after they've signed in, transition to the original page they tried to access.

This is possible in Ember, but according to the [documentation on transitions](https://guides.emberjs.com/v2.9.0/routing/preventing-and-retrying-transitions/) (looking specifically at the "Storing and Retrying a Transition" section), it requires the use of a Controller.

My understanding is that Ember 2.0 is moving away from controllers. I've been googling, but I can't find an example of how to do this without using one. Before I spend too much more time on this, I'd like to know:

- whether it's definitely possible to do this without controllers
- if not, if it's acceptable to experiment with using a controller for this purpose

(If there's a good guide to this out there that I haven't managed to find yet, I'd appreciate a pointer in that direction, too!)

**Comment by jrhorn424** [comment]
This is one example of still needing a controller in Ember. Another example is processing query params.

**Comment by rhjones** [comment]
Great; thanks. Not sure if I'll get to this before tomorrow, but glad to have a direction to go in the future.
