### ISSUE TITLE
Need a one-on-one

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/capstone-project#324]
I am completely stuck and need a one-on-one. I cannot wrap my head around Ember. I'd ask a specific question, but I am not sure WHAT to ask.

**Comment by julie1013** [comment]
Chris met with me.

**Comment by jrhorn424** [comment]
What was the discussion about? @payne-chris-r @julie1013

**Comment by julie1013** [comment]
The long and the short of it is that I feel stuck and am confused about how Ember works and, as a result, I haven't been able to do any CRUD actions yet. I opened this issue last night: https://github.com/ga-wdi-boston/capstone-project/issues/326
