### ISSUE TITLE
[Rails] PG::ConnectionBad Error when trying to spin up server

### ISSUE THREAD

**Issue by styletabtech** [ga-wdi-boston/capstone-project#325]
I had to restart my computer about an hour ago and I'm 95% sure I shutdown my servers before doing so, however now when I try to spin up rails I get the following error:
```
PG::ConnectionBad (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```
I referenced [issue #91](https://github.com/ga-wdi-boston/capstone-project/issues/91) about this and when I run `brew services list` postgresql is started...

```
Name       Status  User Plist
mongodb    started ktab /Users/ktab/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
postgresql started ktab /Users/ktab/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
```

I'm unsure if there's a way to manually shut down all servers in case something is hanging? Any step-by-step instructions to triage and resolve would be much appreciated. Thank you!

**Comment by berziiii** [comment]
Do `brew services restart postgresql` and if that doesn't work well try the next thing.

**Comment by styletabtech** [comment]
Thanks @berziiii! I ran that and got this...

```
Stopping `postgresql`... (might take a while)
==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)
```

but still seeing the same error for rails

**Comment by berziiii** [comment]
Now do `ps aux | grep postgres`

**Comment by styletabtech** [comment]
ok got this 

```
ktab              4369   1.5  0.0  2434840    804 s002  S+    7:11PM   0:00.01 grep postgres
```

**Comment by berziiii** [comment]
Solution:

Tried `brew services restart postgresql` with no luck.
Tried `ps aux | grep postgres` with no luck.
Tried `ls -ls | grep post` with no results

SO removed the postgres lock file by executing from root:

`rm /usr/local/var/postgres/postmaster.pid` and then ran `brew services restart postgresql` and success!

**Comment by styletabtech** [comment]
thanks again @berziiii!

**Comment by jrhorn424** [comment]
Anyone else finding this, you can check out why postgres isn't starting by inspecting the server log:

```
tail /usr/local/var/log/postgres.log
```

**Comment by Lucbarika100B** [comment]
hey guys, thanks for the helpful article, but this  Solution below  did not work for me. I am on  macbook.  Any step-by-step instructions to triage and resolve would be much appreciated. Thank you!

Tried brew services restart postgresql with no luck.
Tried ps aux | grep postgres with no luck.
Tried ls -ls | grep post with no results

SO removed the postgres lock file by executing from root:

rm /usr/local/var/postgres/postmaster.pid and then ran brew services restart postgresql and success!
