### ISSUE TITLE
Need some direction on my create form

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/capstone-project#327]
I want to launch a form similar to sign in etc from the nav bar. The for will be how the user creates a new bike. I have been modeling it after the sign in form. I am having trouble getting the form to render. In addition I am not sure if I need a service.js file that auth uses to give a value to each input. 
```.js
  signIn (credentials) {
    return this.get('ajax').post('/sign-in', {
      data: {
        credentials: {
          email: credentials.email,
          password: credentials.password,
        },
      },
    })
```
Like this one, but for the 27 fields I need to create a bike. Is this overkill since the user will already be signed in? 
Here is what I have so far.
This is in the if authenticated chunk of navbar code
```.hbs
        <li>{{#link-to 'createbike'}}Create a new bike{{/link-to}}</li>
```

create-bike component template file
```.hbs

   {{name-input name=bike.name}}
   {{date-of-purchase-input bike.date_of_purchase}}

   <button type="submit" class="btn btn-primary" {{action "submit"}}>
     Create new bike
   </button>

   <button class="btn btn-default" {{action "reset"}}>
     Cancel
   </button>
```
If I need to create a service.js file I will pull the values in here. If I don't need it I will need some direction on this bit of code. I am thinking it need to be something like this for each input
```.hbs
<h4>Date of Purchase: {{input.bike.date_of_purchase}}</h4>
```
create-bike component.js file
```.js
import Ember from 'ember';

export default Ember.Component.extend({
  classNames: ['bikes'],

   form: {
    text: null,
    done: false,
  },
  actions: {
    createBike () {
       let newBike = this.get('form');
       newBike.bike = this.get('bike');

      this.sendAction('createBike', newBike);

       this.set('form.text', null);
     },
  }
});
```
createbike route.js file
```.js
import Ember from 'ember';

export default Ember.Route.extend({
  auth: Ember.inject.service(),
  flashMessages: Ember.inject.service(),

  actions: {
    createBike (bikes) {
      return this.get('auth').createBike(bikes)
      .then(() => this.transitionTo('bikes'))
      .then(() => this.get('flashMessages').success('New bike created'))
      .catch(() => {
        this.get('flashMessages')
        .danger('There was a problem. Please try again.');
      });
    },
  },
});
```
createbike template.hbs
```.hbs
<h2>Create New Bike</h2>

{{create-bike submit="createBike" reset="reset"}}
```

router.js
```.js
  this.route('createbike');
```

**Comment by berziiii** [comment]
If `bike` is a resource route, which to my understanding of your modeling it is, you do not need to bypass ember data to fire the request through a custom Ajax function.Let ember help you here.

Your {{#link-to 'createbike'}} should be in your nav bar, which appears once a user is authenticated and that sounds like it's working. Make sure you have a route in your router that renders the createbike template. In your create-bike component, where you will have your form, and have every input represent bike attributes. I.e. `{{input type="text" value=bike.model}}`

Then in the create-bike component/component.js file, you'll build out the `bike: {},` object. Then in create the create action, in that component you will need to do a `this.sendAction('create', this.get('bike')` and it will get the bike object that was just constructed from the create bike form and Pass this object back up through the data binding chain. At the `createbike` Route.js file you'll fire a `this.get('store').createRecord('bike')` followed by a promise chain to save the request.

Again, let ember do it's thing for resource routes.

**Comment by rosmith76** [comment]
Thanks. Can we meet 1 on 1 asap to discuss? I need to be sure I full understand what is needed.

**Comment by berziiii** [comment]
We were able to discuss and filter out the difference of ajax requests and using ember data for our resource routes.

**Comment by rosmith76** [comment]
Create bike form is working as expected.

**Comment by jrhorn424** [comment]
@berziiii Any specific insights or feedback so that we can clarify ahead of time during future trainings?
