### ISSUE TITLE
1-on-1 request!

### ISSUE THREAD

**Issue by BMorse09** [ga-wdi-boston/capstone-project#328]
Requesting a 1-on-1 regarding my modeling and creating a join table (insert prayer-hands emoji)

**Comment by jrhorn424** [comment]
ERDs, wireframes, and user stories please. Also do you have a specific ask or are you looking for approval?

**Comment by BMorse09** [comment]
I have specific questions. Basically I have an app where users can post reviews. I need some guidance in creating a reviews table and a join table.

**Comment by BMorse09** [comment]
My project is an app where users can post reviews to public bathrooms in Boston. Users should be able to post/edit/delete their reviews as well as add a new location. My ERD is attached although I'm not positive it's correct. 
![image 11](https://cloud.githubusercontent.com/assets/20890108/20143750/28c06d30-a668-11e6-93d4-e8661614578b.jpeg)

**Comment by payne-chris-r** [comment]
Please fix your photo. Also, it's not. You need a join table between Locations and Reviews. Do you have that join?

**Comment by BMorse09** [comment]
No, that's why im requesting a 1-on-1

**Comment by payne-chris-r** [comment]
Fix your photo.

**Comment by payne-chris-r** [comment]
I'll come holler when you post a photo. I'm gonna go grab lunch first though.

**Comment by BMorse09** [comment]
![image 11](https://cloud.githubusercontent.com/assets/20890108/20147077/91abf0b0-a674-11e6-980f-9600bb722681.jpeg)

**Comment by BMorse09** [comment]
![image 11](https://cloud.githubusercontent.com/assets/20890108/20147108/c5d7f244-a674-11e6-8ca6-0fc16bba6c6c.jpeg)

**Comment by BMorse09** [comment]
Had an illuminating meeting with Brian

**Comment by jrhorn424** [comment]
@BMorse09 Would you mind sharing details when you're less busy? I suspect this is related to a conversation Brian and I had earlier, but I want to record anything here that might help us train folks in the future.

@berziiii Any notes to add?
