### ISSUE TITLE
[gh-pages] Question about the dist/ files for redeployment

### ISSUE THREAD

**Issue by styletabtech** [ga-wdi-boston/capstone-project#329]
I successfully deployed my ember template the other day, and after doing so I started to notice that multiple dist/ files were being modified on my master branch as I was checking out new branches to work. This has been causing merge confilcts when I've been trying to merge a remote branch into master. I've just been adding and commit the dist/ files on master to resolve the conflicts, but I wanted to find out:

a) why this is happening since I have my dist/ files commented out in both my global and local gitignore files 
b) should I just continue to commit those modified files on master?

I'm trying to redeploy this morning but when I try to move to gh-pages it doesn't let me since those files were 'modified' on master and need to be committed. 

```
~/wdi/projects/snapspot (master)$ git checkout gh-pages
error: Your local changes to the following files would be overwritten by checkout:
	dist/assets/snapspot.css.map
	dist/assets/snapspot.js
	dist/assets/snapspot.map
	dist/index.html
	dist/tests/index.html
Please commit your changes or stash them before you can switch branches.
Aborting
```

Thanks!

**Comment by raq929** [comment]
If you accidentally committed the files before adding them to the .gitignore, then they will continue to be tracked. I would make sure you `git rm` any files you don't want tracked, and make a commit removing those files, on both `master` and any other branches that have them.

**Comment by styletabtech** [comment]
thanks @raq929! I'll give that a try later today. Closing this for now but will post a solution once I've successfully done this.

**Comment by jrhorn424** [comment]
Looks like a stray `git add .`?
