### ISSUE TITLE
Got any more of those fancy controller fixes?

### ISSUE THREAD

**Issue by eshimel** [ga-wdi-boston/capstone-project#33]
I'm getting a similar angry message relating to my update profile plans.

On the backend, I either get undefined method 'find' or 'profiles' depending on whether I have 'profiles' or 'profile'.
NoMethodError (undefined method `find' for #<Profile:0x007ff63d878670>):
  app/controllers/profiles_controller.rb:49:in`set_profile', 

Here's the frontend error

PATCH http://localhost:3000/profiles/undefined 500 (Internal Server Error)
script.js:144 Object {jqxher: Object, status: "error", error: "Internal Server Error"}

**Comment by eshimel** [comment]
build_profile doesn't work, though I figured it was a long shot

**Comment by tdyer** [comment]
Looks like your trying to update a profile without given the id of the profile,  http://localhost:3000/profiles/undefined

Above should have and id of the profile to update such as:
 http://localhost:3000/profiles/5

**Comment by eshimel** [comment]
I tried adding the profile in, but its not reading it.  I'll try tinkering with it some and see if I can't get something to work.  I'll let you know if I can close the issue in a few.

**Comment by eshimel** [comment]
I think the issue is a little bigger than the update.  I'll get back to you guys when I can narrow down the problem.

**Comment by eshimel** [comment]
Here's what the backend says...I am pasting in id

NoMethodError (undefined method `find' for #<User:0x007fd8faabec78>):
  app/controllers/profiles_controller.rb:49:in`set_profile'  ...this is why I think its a controller issue, but I can figure out what's wrong with the controller

**Comment by eshimel** [comment]
Have Id showing up through front end...so that part is fixed by the Profile Controller is still giving me the same error.

NoMethodError (undefined method `find' for #<Profile:0x007fc554ba2f90>):
  app/controllers/profiles_controller.rb:49:in`set_profile'

**Comment by eshimel** [comment]
def set_profile
    @profile = current_user.profile
  end
 one to one relationships don't need the if current.user stuff because you either have a profile or not.
