### ISSUE TITLE
Deploying Ember to GH Pages / Rails to Heroku: my notes

### ISSUE THREAD

**Issue by rhjones** [ga-wdi-boston/capstone-project#330]
Hi all,

I've shared these with a handful of people, but in case it helps anyone else—here's how I deployed Ember to GH pages & Rails to Heroku:

First, watch out for three issues w/the Ember deployment guide:

- https://github.com/ga-wdi-boston/ember-deployment-guide/issues/5
- based on how the current Ember template is set up, you need to set `ENV.rootURL`, `not ENV.baseURL`, in your config settings
- `ENV.rootURL` for production environment should point to `/repo-name`, not to `/`

Heroku/Rails:

- `heroku create`
- `git push heroku master`
- `heroku run rake db:migrate`
- `heroku run rake db:seed`
- `heroku config:set SECRET_KEY_BASE=$(rake secret)`
- `heroku config:set SECRET_TOKEN=$(rake secret)`
- `heroku config:set CLIENT_ORIGIN=https://yourgithubname.github.io`
- `heroku apps:rename newname` (optional)
- `heroku restart`
- `heroku open`

GH pages/Ember:

- update `config/environment.js` according to deployment guide
    - make sure the name of the root/base url variable matches across dev & prod environments
    - add rootURL to production
    - add apiHost to production
    - sample:
        - `ENV.rootURL = '/quiltr';`
        - `ENV.apiHost = 'https://quiltr.herokuapp.com';`
- update application/adapter and ajax files according to deployment guide
- `git checkout -b gh-pages`
- Remove `/dist` from `.gitignore` by adding a '#' before it. (do the same for `~/.gitignore`)
- Add & commit `.gitignore`
- `ember build --environment=production`
- `git status`
- add changed files (should be what's in `dist/`) and commit
- `git subtree push --prefix dist origin gh-pages`

**Comment by jrhorn424** [comment]
Please leave this open for now. Where these notes identify issues that should be addressed, they need to be filed in their appropriate repos.

If you'd like to talk about this issue with respect to your own deployment, please open another issue and reference this one.

**Comment by raq929** [comment]
I believe these have mostly been addressed by https://github.com/ga-wdi-boston/ember-deployment-guide

**Comment by jrhorn424** [comment]
Agreed! Thanks so much @rhjones.
