### ISSUE TITLE
CRUD Actions for game

### ISSUE THREAD

**Issue by viohlet** [ga-wdi-boston/capstone-project#331]
Hello,

I am using the Phaser game engine and I would like some guidance on how to implement the CRUD list actions in my game. I am thinking they are not really needed, since my canvas can show the player the time left and score. But I also understand I need to fulfill requirements.

The game plays as soon as the page loads so it is hard for me to grab the score and time objects to display them in show/index. Same with destroy and update. I can 'create' a game but it is so far a shell.

Guidance is appreciated!
V
https://docs.google.com/document/d/1nSy7w2vs47iIfxVnmcTnxFRsi0RS_MawEy83Z_hd8x4/edit

**Comment by payne-chris-r** [comment]
You should be CRUDing on game-history (or game if you keep it the way it is). After a game is played, you store the score, and a "ranking (maybe 1/5 stars of your feeling of how the game went?)". You create a game record when the game is completed which stores your score, and your ranking (you can pick anything trivial here, I just picked ranking 'cause I think it's probably easiest, but feel free to make it comments, or think of something else to PATCH). You are then able to delete games from the game history and update your ranking (or whatever you choose) on that game record.

**Comment by payne-chris-r** [comment]
Create - game record
Read One - specific game from history
Read All - all games played by a user
Update - edit the rating of a game
Delete - delete the entire record of a game

**Comment by viohlet** [comment]
Hi Chris,

Thank you for your reply - I am mainly having trouble accessing the score object from Phaser. Will keep trying.

I can't 'require' any api/ui files to my phaser documents for some reason, and had to create a separate events.js for the game folder too. The error I get is from Phaser and from the console 'require is not defined,' another one is 'require is not a function.'

Thanks,
V

**Comment by payne-chris-r** [comment]
You may have circular dependencies!

**Comment by raq929** [comment]
@viohlet Was this issue resolved? If yes, please comment with what you did and close.
If not, please comment with what you've tried so we can continue to debug. 
Thanks!

**Comment by payne-chris-r** [comment]
It's not resolved.

**Comment by payne-chris-r** [comment]
The issue is the game is loading on page load. So we need to gobble her code into an `on a 'click' of 'start a new game' button`. I just spent 20 minutes moving code around, but I was unsuccessful. I doubt anyone is familiar with Phaser, but maybe fresh eyes might have a solution?
