### ISSUE TITLE
problems with delete structure in Ember

### ISSUE THREAD

**Issue by knoddin** [ga-wdi-boston/capstone-project#333]
I am trying to delete individual parks from a rendered list of "my-parks". I know that this is an action up situation, but I am a bit stuck on how to place a button on a rendered list that then fires to the correct place and works from the bottom up. 

This is the "my-parks" template:

```
<h2>My Parks</h2>


  {{#each model as |park|}}
  {{#if park.editable}}
    <div>
      <h3 id="park-titles" class="my-parks">{{park.name}}, {{park.location}} </h3>
      <h4 id="park-description" class="my-parks">{{park.description}}</h4>

      {{#link-to "update-park" park}}
      <button class="btn btn-default btn-sm">
        Edit Park
      </button>
        {{/link-to}}

      {{#link-to 'delete-park' park}}
      <button id="delete" class="btn btn-default btn-sm">
        Delete
      </button>
      {{/link-to}}

    </div>

    {{/if}}
  {{/each}}
```

Is it best to click the button and re-route to the delete-park route?

```
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('park', params.park_id);
  },


  actions: {

    deletePark (park) {
      park.destroyRecord()
      .then(() => this.transitionTo('my-parks'));
    },

  },
});
```

I am a bit lost on how to fire an action where the button lives at the top!

**Comment by knoddin** [comment]
Also, I think (from reading the docs) that part of my problem may be that when I click delete, it fires to the associated component, which in this case is the my-parks component. In that component, I only want all parks, not a specific one by id. How do I get around that?

**Comment by raq929** [comment]
Does #322 help?

**Comment by knoddin** [comment]
Hmmm...not so far, unfortunately! My {{#each}} loop is already in my template. I tried moving my buttons for edit/delete into the component template, but now they do not show up.

**Comment by payne-chris-r** [comment]
Where are you? Come home to Classroom 5 and I'll take a look!

**Comment by knoddin** [comment]
ok!

**Comment by payne-chris-r** [comment]
@knoddin will close with solution shortly. Spoiler alert: "Don't forget your `actions: {}` ;-)

**Comment by knoddin** [comment]
thanks @payne-chris-r ! We changed the delete button in the "my-parks" template to unlinked. The delete button fires to the "my-parks" route, but it was not working because I was missing the "actions" object around my deletePark function. Corrected template:

``` js
<h2>My Parks</h2>

{{#each model as |park|}}
  {{#if park.editable}}
    <div>
      <h3 id="park-titles" class="my-parks">{{park.name}}, {{park.location}} </h3>
      <h4 id="park-description" class="my-parks">{{park.description}}</h4>

      {{#link-to "update-park" park}}
        <button class="btn btn-default btn-sm">
          Edit Park
        </button>
      {{/link-to}}

      <button type="submit" class="btn btn-default btn-sm" {{action "deletePark"}}>
        Delete
      </button>
    </div>
  {{/if}}
{{/each}}
```

corrected route:

``` js
  actions: {
    deletePark () {
      console.log("delete park in my-parks route");
    },
  },
```
