### ISSUE TITLE
Problems with CURL requests

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/capstone-project#334]
When I do all my CURL requests, except for GET, I get this error:

```curl: (35) Unknown SSL protocol error in connection to localhost:-9847```

And yep, controllers etc are set up...

**Comment by julie1013** [comment]
OK, that problem is fixed (I had "https" instead of "http") but now I get a 404 error. Here's an example curl request:

```
curl --include --request POST http://localhost:4741/episodes \
--header "Content-Type: application/json" \
  --data '{
    "episode": {
      "title": "Some episode"
    }
  }'
```

**Comment by julie1013** [comment]
The issue was that I had `set_episode` (which requires finding an episode) running before create and patch.

**Comment by jrhorn424** [comment]
> The issue was that I had set_episode (which requires finding an episode) running before create and patch.

That shouldn't run before `create`, but most likely it should be run before a `patch`. If someone else has more context, I'm all ears.

I'm not interested in derailing @julie1013 from progress. Just wanted to state a general rule that might have an exception, given a good reason.
