### ISSUE TITLE
Models in Ember

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/capstone-project#336]
I am confused about modeling in Ember, and Brian has indicated that he thinks my models are not set up properly. I am in dire need of assistance with this, in another one on one to get me going.

Thanks!

**Comment by wmcb91** [comment]
Can you post some code?

**Comment by jrhorn424** [comment]
Duplicate of #326 because modeling and CRUD are conceptually tied together in Ember. Thanks for looking, @wmcb91.
