### ISSUE TITLE
delete park data not being passed

### ISSUE THREAD

**Issue by knoddin** [ga-wdi-boston/capstone-project#337]
I am referencing my previous issue  #333  because it's related. While I resolved the way in which my deletePark function was firing and the template was loading (thanks again @payne-chris-r ), I am having trouble passing the correct data, I THINK because I'm in a route that is not storing the correct params for deletePark. I have been looking through other similar issues, but they don't seem to be setup quite like I am (perhaps because I am wrong). I also looked at the [Ember docs on using an afterModel hook](http://emberjs.com/api/classes/Ember.Route.html#method_afterModel) as a way to implement two different model hooks, but that didn't seem to be the right option. Is it?

my-parks template 
```js
<h2>My Parks</h2>

{{#each model as |park|}}
  {{#if park.editable}}
    <div>
      <h3 id="park-titles" class="my-parks">{{park.name}}, {{park.location}} </h3>
      <h4 id="park-description" class="my-parks">{{park.description}}</h4>

      {{#link-to "update-park" park}}
        <button class="btn btn-default btn-sm">
          Edit Park
        </button>
      {{/link-to}}

      <button type="submit" class="btn btn-default btn-sm" {{action "deletePark"}}>
        Delete
      </button>
    </div>
  {{/if}}
{{/each}}
```

my-parks route
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    console.log("i am in my-parks route");
    return this.get('store').findAll('park');
  },
  actions: {
    deletePark (park) {
      return park.destroyRecord();
    },
  },
```

It is in the route where I know I am not capturing the right params, since I am finding all parks instead of just the one that I want to delete. However, this particular model is what allows all parks to be rendered via the my-parks template. Basically, I want two models (?!?!) but am not sure how to go about that or if that's best practice. 

my-parks component
```js
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    deletePark () {
      this.sendAction('deletePark', this.get('park'));
      // console.log(this.get('park'));
    },
  },
});
```

As it stands now, I am getting this error: Cannot read property 'destroyRecord' of undefined

Help is much appreciated. Thank you!

**Comment by raq929** [comment]
It looks like you tried console.logging `this.get('park')`. Was it undefined there in the component?

**Comment by knoddin** [comment]
Yes, it was.

**Comment by raq929** [comment]
And the template is displaying park information as expected?

**Comment by knoddin** [comment]
Yes it is.

**Comment by raq929** [comment]
From looking quickly at the docs (and I'm not an Ember expert, so take it with a grain of salt), I'd try modifying your button to say `{{action "deletePark" park}}` in order to pass in the park data.
https://guides.emberjs.com/v2.3.0/templates/actions/

**Comment by knoddin** [comment]
Wow...that worked! For having spent a bunch of time in there I am sorry I didn't see it. THANK YOU @raq929 !

**Comment by jrhorn424** [comment]
FWIW, I don't like this approach: `{{action "deletePark" park}}`. That's why I didn't show it to you. :smile:

Instead, I prefer `{{action "deletePark"}`, then inside the component:

``` js
actions: {
  deletePark () {
    this.sendAction('deletePark', this.get('park'));
  },
},
```

Then, in parent contexts, this:

``` js
actions: {
  deletePark (park) {
    // this.sendAction('deletePark', park);
    //
    // OR, as the case may be:
    //
    // park.destroyRecord()
    // .then(whatever)
   // ;
  },
},
```

**Comment by raq929** [comment]
It looks like that's what @knoddin was doing, but it was not working. Not sure exactly what was going on there.

**Comment by jrhorn424** [comment]
> As it stands now, I am getting this error: Cannot read property 'destroyRecord' of undefined

This indicates that somewhere, a `sendAction` did not receive a parameter, or pass it along as it should have (second argument).

**Comment by jrhorn424** [comment]
I really doubt there's only one route with a component. Lots of folks have nested components because they make sense, but you have to manage bindings and sendAction all the way through.
