### ISSUE TITLE
[AWS] permissions errors in production

### ISSUE THREAD

**Issue by rhjones** [ga-wdi-boston/capstone-project#338]
I have uploads working locally through Ember to Rails to AWS S3.

In production, I initially got this error:

`Aws::Errors::MissingRegionError (missing region; use :region option or export region name to ENV['AWS_REGION']):`

I followed these steps to address it:

- create a new user in AWS
- create a new `US Standard` bucket in S3
- follow the [AWS setup guide](https://github.com/ga-wdi-boston/aws-s3-setup-guide) to create a bucket policy with the new user information
- rerun the following commands:
  - `heroku config:set S3_BUCKET_NAME=newname`
  - `heroku config:set AWS_ACCESS_KEY_ID=newkey`
  - `heroku config:set AWS_SECRET_ACCESS_KEY=newkey`

Now I'm getting this error:

`Aws::S3::Errors::AccessDenied (Access Denied):`

Would appreciate a second set of eyes on my setup if anyone has a few minutes.

**Comment by raq929** [comment]
Come find me in classroom 4 and I'll take a look. (I'm Rachel)

**Comment by rhjones** [comment]
So this was fun:

I reset all of my original AWS config vars to what they were before I got the region error, and now everything is working.

¯_(ツ)_/¯
