### ISSUE TITLE
1:1 request: Randomizer (_.shuffle) function not working

### ISSUE THREAD

**Issue by laurenallegra** [ga-wdi-boston/capstone-project#339]
I have added a feature to my app that would (if this function was working!) allow users to create a random sequence of their favorite yoga poses. I used the command

`npm install underscore --save`

in my terminal to get access to the underscore.js library, which has a nice `_.shuffle` function that would be ideal for my purposes. `underscore` is showing up in my `package.json` file, so I believe the issue is not access to the library. I think the problem is that the according to the documentation (http://underscorejs.org/#shuffle), the `_.shuffle` function needs to be passed an array, and I am passing it an object (`user_poses`). I have tried some console.logs, and can't seem to figure this out. I don't know how to get the array out of the object I am attempting to pass, and would really appreciate if someone could sit down with me for a few minutes to help me figure out what I am missing here.

Thanks so much!

Relevant code below: 

This is what I am attempting in the file user-poses/ui.js:

```
const shuffleUserPose = (user_poses) => {
  user_poses = _.shuffle(user_poses);
  $('.display-content').html(indexUserPosesTemplate(user_poses));
};
```

in the file templates/index-user-poses.handlbars, which uses handlebars to render a user's favorite poses:

```
<h2>My Favorite Poses</h2>
<table>
  <thead>
    <tr>
      <th>User Pose Id</th>
      <th>English Name</th>
      <th>Sanskrit Name</th>
    </tr>
  </thead>
  <tbody>
    {{#user_poses}}
      <tr>
        <td>{{id}}</td>
        <td>{{pose.english_name}}</td>
        <td>{{pose.sanskrit_name}}</td>
      </tr>
    {{/user_poses}}
  </tbody>
</table>
```

**Comment by laurenallegra** [comment]
Actually, I just realized user_poses might be an array after all, so the problem is just that it's not rendering with handlebars, in which case I have no idea what is not working.

**Comment by jrhorn424** [comment]
The problem was `_.shuffle(user_poses)` was receiving a _single_ object. That is, an object that looks like:

``` js
{
  user_poses: [
    { ... },
    { ... },
  ],
}
```

`_.shuffle` expects an array-like object (check the source, Luke). Passing it an object might work. Passing it a _single_ object has to work, since there's nothing to shuffle, logically.

Changing what the method received to an array (instead of passing `data` straight down from jQuery) solved the problem.

Additionally, however, before the array is passed to handlebars, since handlebars is expecting an object, we have to attach the array back into an object.

@laurenallegra Please both post the function definition and the function invocation (`onWhatever`).

**Comment by laurenallegra** [comment]
@jrhorn424 figured it out! As he explained above, `._shuffle` wasn't being passed an array-like object. Thanks so much for your help on this, Jeff.

For additional clarity, Jeff also renamed the shuffling function, making it the plural `shuffleUserPoses` as opposed to `shuffleUserPose`. The solution code looks like this:

in user-poses/ui.js:

```
const shuffleUserPoses = (posesArray) => {
  let user_poses = _.shuffle(posesArray);
  $('.display-content').html(indexUserPosesTemplate({ user_poses }));
};
```

in user-poses/events.js:

```
const onShuffleUserPoses = function (event) {
  event.preventDefault();
  api.indexUserPoses()
    .done((data) => {
      ui.shuffleUserPoses(data.user_poses);
    })
    .fail(ui.failure);
};
```

and this line in my addHandlers function:

```
$('#index-user-poses').on('submit', onShuffleUserPoses);
```

I apologize for the confusing class names, this function/issue is time-sensitive and I haven't had time to update them to more semantic names in my `index.html` yet.

I'd like to also thank @berziiii and @payne-chris-r for getting eyes on this issue, they are both very busy at the moment with many capstone-related issues and I really appreciate everyone's help!

**Comment by jrhorn424** [comment]
Thanks, @laurenallegra, great explanation!

**Comment by laurenallegra** [comment]
Also thanks to @DanielJRaine for helping me install the underscore library so I had access to the `_.shuffle` function for my project (yay for not having to hand-code a randomizer function!)
