### ISSUE TITLE
Ember: createRecord not adding hasMany/belongsTo association

### ISSUE THREAD

**Issue by kelvinma** [ga-wdi-boston/capstone-project#34]
Currently working with the following for my ember data create action:

```
actions: {
    createWorkout: function(workoutData, athleteID){
      var newWorkout = this.store.createRecord('workout', workoutData);
      this.store.findRecord('athlete', athleteID).then(function(athlete){
        athlete.get('workouts').pushObject(newWorkout);
        newWorkout.save();
      });
    } 
```

Bubbling up the action from 2 components down (nearly identical to how I refactored the Pokemon example to avoid Ember Views. Code is close to what Matt B came up with, but I'm using pushObject instead since I'm adding to an array). I can create workouts til the cows come home, but assigning the belongsTo relationship to the workout itself does not persist on the back end. 

I've added a restriction on sequelize to not allow athlete_id to be null as a check to not inadvertently flood my DB with orphan workouts. On the back end, the parent entry, athlete, is not sideloading the workouts upon render, which November says is something that should be happening by default. Wondering if the two issues -- no sideloading and not assigning "belongsTo" IDs -- are related.

**Comment by kelvinma** [comment]
Ha! Just like this! 

https://github.com/t4t5/november-cli/issues/5

**Comment by jrhorn424** [comment]
Imagine. 😄

**Comment by jrhorn424** [comment]
Any update? I'm curious about this.

**Comment by kelvinma** [comment]
If I had to guess, I think it's got something to do with the ember serializer. Possibly some a disagreement between the camelCasing I'm using in Ember not playing nicely with the split_casing in Sequelize. My tests in Postman/curl, which forces me to explicitly define the athlete_id association in my crud, works just fine, and Ember is able to interpret the association on the front end without issue. Doing it in the opposite direction is the problem.

Another thing I noticed... When I console log the workouts for the athlete, I'm able to iterate through it like an array, however there is no explicit collection in the DB, ie no sideloading, ember just interprets it like one. 

Doing a pushObject or addObject to something that doesn't exist seems like it might cause some errors. Chris is having the same issue with Rails, I believe (though he's still working through some issues with bubbling actions, which may be causing his problems). 

In other news, all my other (C)RUD is working, so there's that. Can't get auth until I get associations set up, though.

**Comment by jrhorn424** [comment]
Thanks for the update. I'll want to check in again this afternoon.

**Comment by kelvinma** [comment]
Googled 'Ember createRecord serializer', and this seems like a very common bug, with serializers being part of the solution (maybe?). I'll keep on digging...

**Comment by jrhorn424** [comment]
Stopping by for an update.

**Comment by jrhorn424** [comment]
The way we've demoed creating related objects is leading to orphaned records in the child table.

We tried nesting promises (bad, I know) to ensure network requests were resolving before objects were used again. I'm going to investigate further.

**Comment by gaand** [comment]
I'd like to look over how promises are being used. I might have something to add.

**Comment by kelvinma** [comment]
Matt helped me out with working through the RESTAdapter to get the save() working properly. While looking at the server logs, the front end was not sending the put/patch request to the server. That has since been resolved, and the association is now being added after the child object gets created, though there's a minor (or at last what looks to be minor) data store issue that I need to fix in the morning.

**Comment by gaand** [comment]
`this.serialize` the current problem.

**Comment by jrhorn424** [comment]
@kelvinma Could you explain what you did to get the front-end to send the PATCH it wasn't sending? Did we forget to configure something in the lesson?

**Comment by kelvinma** [comment]
Sure. 

Ember wasn't allowing me to add the parent association to the child object upon creation in the canonical state on the datastore, though it was making that association on the front end. That association had to be added via update in order to persist in the back end, however the createRecord action in the route did not send the put request.

Matt took care of that with a custom RESTAdapter:

```
import ApplicationAdapter from '../application/adapter';
import Ember from 'ember';

export default ApplicationAdapter.extend({
  host: 'http://localhost:9000',
  updateRecord: function(store, type, snapshot){
    console.log('HIT THE WORKOUT ADAPTER');
    console.log(snapshot);
    console.log(this.host);

    var data = this.serialize(snapshot, {includeId: true});
    var id= snapshot.id;
    var url = [this.host, type.modelName+ 's', id].join("/");

    console.log(data);

    return new Ember.RSVP.Promise(function(resolve, reject){
      Ember.$.ajax({
        type: 'PUT',
        url: url,
        dataType: 'json',
        data: data
      }).then(function(data){
        Ember.run(null, resolve, data);
      }, function(jqXHR){
        jqXHR.then = null;
        Ember.run(null, reject, jqXHR);
      });
    });
  }
});
```

**Comment by cwcrane** [comment]
So I've been following along here but don't have a working createRecord yet. I am hitting the back-end with an initial Post request (with foreign key missing), and then a subsequent PUT request to update the foreign key field. However, the PUT request ember generates for me is missing the /:id at the end of the url, so the request is getting a 404 error. My backend does not know what record I'm trying to update. 

I have Kelvin's adapter in place. It seems the problem lies in my front end process for how I am pulling my associated record id before making the PUT request.
