### ISSUE TITLE
Roll assignment in the context of our auth scheme

### ISSUE THREAD

**Issue by Naki21** [ga-wdi-boston/capstone-project#349]
So I am hoping to assign users rolls depending on what kind of user they are (client, artist). I have read a bit about different ways of going about this and they tend to vary based on what kind of auth scheme you use. I'm wondering what may be the best way to do this based on how our rails template implements authentication. I was planning on doing it similar to this 
```ruby

#migration
class AddRoleToUsers < ActiveRecord::Migration
  def change
    add_column :users, :role, :integer
  end
end

#model
class User < ActiveRecord::Base
  enum role: [:client, :artist]

end
```

I them can pass roll as an int in params

This seems to work but I'm wondering if I will adequately be able to restrict/assign functionality  to the different users. Thoughts?

**Comment by gaand** [comment]
Do you want to restrict user access based on role?  Or some other role based difference in what the API allows/provides?

**Comment by Naki21** [comment]
Yes. I would like for clients and artists to have crud capabilities on different things. I want clients to be able to create contests and for artists to be able to make submissions to those contests. I want both to be able to comment on said submissions but only artist can make edits to the image (the submissions would be design images) and only clients can rate the images.

**Comment by gaand** [comment]
You'll want to add checks for the user type to your controllers to restrict access.  It may make sense to create base controllers that perform that check in a before_action.

**Comment by Naki21** [comment]
Will update when I get around to testing restricting actions

**Comment by Naki21** [comment]
Closing this issue until I get around to even trying to see if I can do this. Not sure if ill even get here.
