### ISSUE TITLE
have to ask -- any way to target the audio of an iframe element?

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/capstone-project#350]
My project idea involves using a youtube player element and sending it to an equalizer built with web audio api. I've gotten a youtube player to work in ember, and I've seen implementations of web audio api that target <video> tags, and seen it used to make equalizers, but I can't get it to target youtube's <iframe> element. After much research, it seems that the consensus on stackoverflow is that it's impossible because youtube intentionally makes its raw video elements inaccessible.

But then I found this guy, who already did my idea!

http://you.dj/

so I have to ask before I abandon this idea... anyone have an idea how to do it?

**Comment by gaand** [comment]
I have no idea how to do it, but if you want we can find a time to explore the possibilities and see where we get.

**Comment by ioncrash** [comment]
That would be great! Should we schedule a one-on-one?

**Comment by gaand** [comment]
I'm not available this afternoon, but we should be able to find time Friday.

**Comment by ioncrash** [comment]
hrm, so I found a package that will allow you to use only the audio from a youtube file, but I'm almost certain that it violates their terms of service, given that it basically downloads the video and then exports the audio to an audio tag...

Should... I do it anyway? (no, probably?)

Having trouble letting go of this idea, tbh

**Comment by gaand** [comment]
Let's meet tomorrow and examine the options.

Please do not knowingly violate any terms of service.

**Comment by ioncrash** [comment]
That would be helpful, thanks.

**Comment by gaand** [comment]
Almost there.

**Comment by ioncrash** [comment]
After considering this further, I think it's too large a project for the time I have. I've decided instead to do an app which provides SoundCloud-like timestamped annotations on YouTube videos. At some point in the future, when I have infinite time I'll try the DJ idea
