### ISSUE TITLE
FileSaver.js  NPM Install

### ISSUE THREAD

**Issue by rickdean** [ga-wdi-boston/capstone-project#351]
I npm installed a solution for a file save called filesaver.  I thought I would be able to install it and 'invoke' it via updating index.js.  When I attempt to do so I receive the error 'saveAs is not a function'.   What I am doing is this....

index.js
```  
// save form as text file
require('expose?$!file-saver');
```
And in my events file I have the following:
```
'use strict';

const getFormFields = require('../../../lib/get-form-fields');
const api = require('./api.js');
const ui = require('./ui.js');
const saveAs = require('expose?$!file-saver');
``` 
as well as...
```
const onSave =  function (){
    console.log('save click');
  let text = $(".listTable").val();
  let filename = $("#input-fileName").val();
  let blob = new Blob([text], {type: "text/plain;charset=utf-8"});
  saveAs(blob, filename+".txt");
};

  const onGetList = function (event) {
    //event.preventDefault();
    // console.log('click get list button');
    api.getList()
      .then(ui.getListSuccess)
      .then(function(){
        $('.delete-list-item').on('click', onDeleteItem);
      })
      .then(function() {
        $('.update').on('click', onUpdateItem);
      })
      .then(function() {
        $('#btn-save').on('click', onSave);
      })
      .catch(ui.failure);
  };
```

Any ideas?

**Comment by gaand** [comment]
Please post a link to the documentation for file saver.

Saving files from the browser is basically not allowed (other than local storage, but that's not identical.

What are you trying to accomplish?  Is this saving the file to your API?

**Comment by rickdean** [comment]
Thank you Antony.  The documentation is at https://github.com/eligrey/FileSaver.js     

Basically I want to allow a User to save a list they have created to their desktop (think wishlist of items they want to purchase). I also have a use case where they share said list via social media.

**Comment by gaand** [comment]
Is there a stack trace when you get "saveAs is not a function"?

**Comment by rickdean** [comment]
Yes.  It homes in on the line in my event.js.  

```

events.js:76 save click
events.js:80 Uncaught TypeError: saveAs is not a function
    at HTMLButtonElement.onSave (events.js:80)
    at HTMLButtonElement.dispatch (jquery.js:5201)
    at HTMLButtonElement.elemData.handle (jquery.js:5009)
onSave @ events.js:80
dispatch @ jquery.js:5201
elemData.handle @ jquery.js:5009

```

**Comment by gaand** [comment]
I think it's how you're using it.

https://github.com/eligrey/FileSaver.js#saving-text-using-with-require

I think this `const saveAs = require('expose?$!file-saver');` probably makes just `FileSaver` available globally.  But, you could probably use the syntax at that link

**Comment by rickdean** [comment]
Thank you Antony.  I'm going to give that a shot and close the issue for now.  If I run into more problems down the road I'll open a new one.
