### ISSUE TITLE
Index Controller returning no result with boolean search params

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/capstone-project#352]
**Summary**
- I'm using the Express API template with MongoDB. 
- I have a working controller index method that I'm trying to add additional parameters to filter the result. 
- This works fine with strings but returns an empty result when I try to filter with boolean fields.
- There are records in the data set that should be returning. There are no errors in console.

**Expected Behavior**
Returns records matching the boolean search condition.

**Actual Behavior**
Empty response is returned.

**controllers/shops.js**
_This works fine - checking against a non-boolean field._
```js
const index = (req, res, next) => {
  let search = { description: 'shop4 description' };
  Shop.find(search)
    .then(shops => res.json({ shops }))
    .catch(err => next(err));
};
```
_This returns an empty response._
```js
const index = (req, res, next) => {
  let search = { has_wifi: false };
  Shop.find(search)
    .then(shops => res.json({ shops }))
    .catch(err => next(err));
};
```

**models/shop.js**
```js
'use strict';

const mongoose = require('mongoose');

const shopSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
  is_good_for_working: {
    type: Boolean,
    required: true,
  },
  accepts_credit_cards: {
    type: Boolean,
    required: true,
  },
  has_parking: {
    type: Boolean,
    required: true,
  },
  is_accessible: {
    type: Boolean,
    required: true,
  },
  has_outdoor_seating: {
    type: Boolean,
    required: true,
  },
  has_wifi: {
    type: Boolean,
    required: true,
  },
  neighborhood: {
    type: String,
    required: true,
  },
  yelp_id: {
    type: Number,
  },
  is_closed: {
    type: Boolean,
  },
  url: {
    type: String,
  },
  image_url: {
    type: String,
  },
  location_address: {
    type: String,
  },
  location_longitude: {
    type: Number,
  },
  location_latitude: {
    type: Number,
  },
  open_time: {
    type: Date,
  },
  close_time: {
    type: Date,
  },
}, {
  timestamps: true,
  toJSON: { virtuals: true },
});

const Shop = mongoose.model('Shop', shopSchema);

module.exports = Shop;
```

**Response**
```bash
{
"shops": []
}
```

**Server Log**
```bash
GET /shops 304 2.577 ms - -
```

**Comment by gaand** [comment]
What do you get if you try that search from the mongo CLI?

What do you get if you search for `true`?

**Comment by coffeeisamazing** [comment]
Works in mongo CLI.
> db.shops.find({"has_wifi": "true"}).count()
9
> db.shops.find({"has_wifi": "false"}).count()
11

Same result if search with true.
```bash
{
"shops": []
}
```

**Comment by gaand** [comment]
`"true" !== true`.

**Comment by raq929** [comment]
@coffeeisamazing is this resolved?

**Comment by coffeeisamazing** [comment]
Finished building out the other routes to make troubleshooting a bit easier. Looking again now.

**Comment by coffeeisamazing** [comment]
I ended up shifting direction slightly in my design and no longer needed the filter. However, for future folks coming here....per Antony's note above, appears that my data was being saved as the string "true" rather than the boolean value true. This would mean that my controller wasn't returning anything as only "true" was being found - no trues. It's worth noting too that the data was created by a CSV bulk load into mongo.
