### ISSUE TITLE
Curl Request Not Working

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#353]
I am setting up my API and I can't seem to get my curl request for creating a task to work. I have done all sorts of messing around with my create method, but here is the code for my controller.

```rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :update, :destroy]

  def set_task
    @task = tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :due_date, :priority, :details, :completed)
  end

  def index
    @tasks = Task.all

    render json: @tasks
  end

  def create
    @task = tasks.build(task_params)

    if @task.save
      render json: @task, status: :created, location: @task
    else
      render json: @task.errors, status: :unprocessible_entity
    end
  end
end
```

I have also tried the following which sets `tasks` to `Task`: 
```rb
  def create
    @task = Task.build(task_params)

    if @task.save
      render json: @task, status: :created, location: @task
    else
      render json: @task.errors, status: :unprocessible_entity
    end
  end
```

Still doesn't work. here is the route
```rb
post '/tasks', to: 'tasks#create'
```

And the request
```sh
curl --include --request POST http://localhost:4741/tasks \
  --data '{
    "task": {
      "name": "call rick",
      "due_date": "2017-03-01",
      "priority": 1,
      "details": "details",
      "completed": "false"
    }
  }'
```

The error message:
```sh
NameError (undefined local variable or method `tasks' for #<TasksController:0x007fe3c33b69e8>
Did you mean?  tasks_url):
  app/controllers/tasks_controller.rb:19:in `create'
```

I have compared my code with examples and my old app and everything seems to be the same so I am not sure what the issue is. I looked up the error and it I am fairly certain all of my variables and methods are defined, especially the one on the line in question.

**Comment by raq929** [comment]
I believe you want to replace `tasks` with `Task` in expressions like `tasks.find()`.

**Comment by akradin** [comment]
I tried that 😬

**Comment by gaand** [comment]
Please show the error when using `Task`.  It should be different.

**Comment by akradin** [comment]
Method:
```rb
  def create
    @task = Task.build(task_params)

    if @task.save
      render json: @task, status: :created, location: @task
    else
      render json: @task.errors, status: :unprocessible_entity
    end
  end
```

Error message
```sh
NoMethodError (undefined method `build' for #<Class:0x007fe3c93f3748>):
  app/controllers/tasks_controller.rb:19:in `create'
```

**Comment by gaand** [comment]
Okay.  Why do you think Task has a `build` method?  `build` is a method on collection associations.

**Comment by akradin** [comment]
I suppose my though process was  it worked for my last project and in the `example` controller so I assumed it would work for this one. I tried `Task.new(task_params)` and that  worked. Thanks!
