### ISSUE TITLE
Using Websockets with NodeJS backend and EmberJS frontend (see final comment)

### ISSUE THREAD

**Issue by joaufi** [ga-wdi-boston/capstone-project#354]
Idea for my capstone:
I would like to make an encrypted chat app using NodeJS, the ExpressJS template, EmberJS, Socket.io Websockets, and Bookshelf.js to use PostgreSQL. I feel like I'm potentially biting off more than I can chew, and would like some assistance de-scoping my project and discussing if what I have in mind is possible in the time allotted for the project.

Just from an initial pass if I can get Websockets working and Bookshelf integrated with the Express template I will be quite pleased. I think I have a solid enough handle on EmberJS to get that portion working. I can always add message encryption later. 

I would prefer to avoid using Rails because Socket.io seems really nice and Rails 5 Websockets w/ Action Cable seems all over the place (I've tried getting it working so many times at this point.) Also, I would rather work with ExpressJS and NodeJS.

Thanks!

**Comment by gaand** [comment]
You should look at how the game-project-api implements pub/sub and see if Bookshelf supports something like `wait_for_notify`.  If not, you'll need to use some other mechanism that implements pub/sub.

I'm happy to meet with you in the afternoon.  1 o'clock?

**Comment by joaufi** [comment]
That's a great idea with the game-project-api. Also, Caleb turned me onto the [express-api-template bookshelf branch](https://github.com/joaufi/express-api-template/tree/bookshelf) so part of my work might be done for me; I'm looking over it now.

And 1pm sounds great, I will see you then.

**Comment by joaufi** [comment]
After doing some research and speaking with @gaand I have decided to use Rails 5 and EmberJS instead of my previous plan of using NodeJS + ExpressJS + Socket.io + BookshelfJS. The main reason for this decision is because I found quite a few resources that make Websocket implementation using Rails 5 and EmberJS (and PostgreSQL) quite a bit simpler than what I was planning, meaning I will be able to iterate more quickly resulting in a more polished project.

If anyone is interested, I have been utilizing and working off of the following materials:
[Powering Ember Apps with Rails Action Cable](https://www.algonauti.com/posts/powering-your-ember-apps-with-rails-actioncable)
[Action Cable Overview](http://guides.rubyonrails.org/action_cable_overview.html)
