### ISSUE TITLE
1:1 Request - Capstone Project Data Structure

### ISSUE THREAD

**Issue by akadane87** [ga-wdi-boston/capstone-project#355]
Hey Staff! Do you suck at remembering names at the start of new Cohorts?? Not anymore you dont!  My capstone project idea is a flashcards game with the faces of students generated randomly and a place to submit/check the appropriate name. 

I would like to discuss what my data table would look like and if there is a CRUDable resource in there. To me it seems like the "score" of a user is just user owned data. Just want to talk it out.

Thanks!

**Comment by gaand** [comment]
I can't meet today, but tomorrow late morning might work.

**Comment by akadane87** [comment]
Great thanks Antony, I'll slack you in the am to see what your schedule looks like

**Comment by gaand** [comment]
Hey Adam, let's meet now to discuss this.

**Comment by gaand** [comment]
@akadane87 Would you please comment and close if our meeting provided the direction you needed?  Thanks.

**Comment by akadane87** [comment]
Refactored the data tables for app:

Originally had one large form and a single button to check the values of the input fields.
 Now its a single picture with the entire list of names and check button for each picture.
