### ISSUE TITLE
Admin User - Rails API

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/capstone-project#356]
I am trying to build a website for my brother, who refurbishes furniture, where he can show before/after photos of projects, have descriptions, price. However, the way I'm imagining the site, customers would NOT have log-in access. Rather, he would have almost an "admin" view and login capabilities to CRUD on a "Products" resource (Create a new product to showcase, upload a photo for that product (hopefully using AWS but will start with locally stored photos for capstone), update the description/price, and delete.) 

My question is two part:
1) Is it possible to have my app set up that way and meet capstone requirements (Mainly, is it okay that users will not have auth)?
2) How would I go about setting up an 'admin' user or granting admin privileges to just one user (my brother)?

**Comment by raq929** [comment]
Well, some users will have auth. Like admins. :) You will need your admins to fulfill this requirement:
Have user-owned data should said data be owned by a user (this may or may not be the case depending on your application)

But there's no requirement that ALL users have data.

You can create an admin directly on the database (with psql), and then allow admins to create other admins.
@gaand might have further ideas on this?

**Comment by jdaly04** [comment]
So I could still use a 'users' table in SQL? Just flag a user as admin?

**Comment by raq929** [comment]
Yeah. Use the current users table, just add a property `isAdmin` to it. Or, in your case, if you ONLY have admin users and people who can only view, you don't even need that. 
Just don't allow people to create accounts.

**Comment by jdaly04** [comment]
Got it-- thank you so much. Super helpful!
