### ISSUE TITLE
Want to Make Sure The Way I have my data will meet requirements

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#357]
My app is a management application for musicians, so the way my data is set up is a User (potentially) has many bands. When a user clicks on one of their bands it goes to a page with multiple features such as a to-do list and an expense report. Is this okay?

In addition to this, I know under the `Bands` model it should have a `has_many :expenses, :tasks`, but the migration I need to generate is tripping me up. Would be it be something like
`rails g migration AddUserstoBands band:references` and then
`rails g migration AddBandtoExpensesandTasks expense:references task:references`

I am basing those commands off of the one-to-many repository

**Comment by raq929** [comment]
That sounds OK to me, as long as users have ownership. (ie, they can't edit todos or reports for bands that they aren't a member of.)

Re migrations:
What happens when you do those commands? Is it what you want?

**Comment by akradin** [comment]
I did the first one...and I don't know, I think mostly because I forget. I am looking at my Project 2 and and there arent two many hints. The current migration shows
```rb
class AddUserstoBands < ActiveRecord::Migration
  def change
  end
end
```

And there was a change to the schema but I don't really know how to read schema changes. Here is the change: 
  ```add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["token"], name: "index_users_on_token", unique: true, using: :btree

  add_foreign_key "examples", "users"
```

**Comment by akradin** [comment]
I spoke with Rachel, the solution is as follows
`rails g migration AddUserToBands user:references`
This migration looks like this
```rb
class AddUserToBands < ActiveRecord::Migration
  def change
    add_reference :bands, :user, index: true, foreign_key: true
  end
end
```

Then you move into the `user` model and add `has_many :bands` and in the `band` model you add `belongs_to :user`

**Comment by raq929** [comment]
I think we resolved this yesterday... will you comment and close? Or update with where you're at if it's not resolved?
