### ISSUE TITLE
One on One

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/capstone-project#358]
I would like to have a one on one with someone about my app idea. I want to make an app that uses a lot of pictures and I want to tackle what would be the best way to start and plan out how I would go about doing this project. I just need 10 minutes.

**Comment by raq929** [comment]
Let's chat tomorrow morning.

**Comment by raq929** [comment]
Where are you?

**Comment by Sphilippe7** [comment]
hey sorry @raq929 I did not see this. I'll come get you
