### ISSUE TITLE
issues with ember-auth command not found

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/capstone-project#359]
Having strange issues with ember-auth template. Sometimes getting "ember command not found" at command line.

To install, I downloaded the repo and followed instructions as per the ember-template instructions (npm install && bower install, find and replace all instances of ember-auth). 

At first it appeared that no ember commands would run (or npm or bower commands), but I noticed one other behavior -- it seems to work if all other terminal tabs are closed. At that point I seem to get back `ember s` as well as all `ember generate` commands, but lose them again as soon as I open another tab

**Comment by raq929** [comment]
That is bizarre behavior.  It sounds like it's not recognizing that there's an Ember app?
What is the error you get when other tabs are open? 

@payne-chris-r is this similar to what @kiramaa was seeing?

**Comment by raq929** [comment]
I see that it is. @ioncrash, did you verify that you have the hidden files? Or is this resolved? It seemed unclear in slack.

**Comment by ioncrash** [comment]
There are hidden files, yes. @BenGitsCode was doing some debugging on slack with me and @kiraamaa:

Chris Payne [6:02 PM] 
Can you open an issue on `capstone-project`?

Ben Gray [6:03 PM] 
yeah

Chris Payne [6:04 PM] 
You're not the only one. @jbuzzanco and @kiraamaa ran into similar issues. Can we get a conversation going in there? And can you each explain what you did with your repo, how you cloned, or downloaded and zipped, etc. as much detail and as many steps as you can remember so I can try to recreate it and watch it break

Kira MacLean [6:04 PM] 
Yikes fam this collectively sucks

[6:05]  
I did use the command syntax you mentioned @payne.chris.r

Ben Gray [6:09 PM] 
well I'm getting different behavior now... try closing all other terminal tabs and do ember server from a lone terminal window -- that worked for me

[6:12]  
course I lose it again as soon as I open a new tab...

[6:15]  
Issue is open if you want to add your story

Ben Adamski [6:22 PM] 
What happens when you `npm install -g ember-cli`
Ben Gray
-bash: ember: command not found
Posted in #wdi-bos-015-projectsToday at 5:55 PM

[6:23]  
last time I saw that it was because I updated my node version, and I needed to update my global packages to reflect that version.

Alex Kradin [6:39 PM] 
A version issue seems likely, because I am not having the problem (edited)

Ben Gray [6:52 PM] 
`npm install -g ember-cli` looked like it installed some stuff, but still getting the same behavior

Ben Adamski [7:12 PM] 
what does `npm list output`? to be clear, because i just popped in here, the behavior is bash not recognizing the ember command? (edited)

[7:15]  
hey @ioncrash what does `nvm list output`

Ben Gray [7:16 PM] 
@bengitscode -bash: nvm: command not found

Ben Adamski [7:16 PM] 
ah!

Ben Gray [7:16 PM] 
but only if ember server is running, I think

Ben Adamski [7:16 PM] 
yeah you got some broken stuff

[7:16]  
i hope that helped, g'night

[7:17]  
Seriously, this is starting to sound like a pathing issue. Have you made any changes to your dotfiles recently?

Ben Gray [7:18 PM] 
dont think so

[7:18]  
haven't touched them

Kira MacLean [7:18 PM] 
When Patrick took a look at my path he said nvm and mom weren't there

Ben Adamski [7:18 PM] 
hm I’m inclined to believe you but this is strange?

Kira MacLean [7:18 PM] 
Nvm and npm

Ben Adamski [7:18 PM] 
alright let me some dotfiles

Kira MacLean [7:19 PM] 
None of us touched our dot files; we all downloaded and ran npm install && bower install

Ben Adamski [7:19 PM] 
start with `~/.bashrc`

Kira MacLean [7:19 PM] 
I believe

Ben Gray [7:20 PM] 
hm, don't have that one...

Ben Adamski [7:20 PM] 
you said there’s no nvm there? there was at installfest and none of those commands will work without the correct pathing. I believe you , but maybe something changed as an uninteded side effect from something else

[7:20]  
`atom ~/.bashrc` ?

[7:20]  
when you type that into terminal, you get nothing?

Ben Gray [7:21 PM] 
oh no I got something -- must have the hidden files turned off by accident

[7:21]  
I got this

Ben Adamski [7:21 PM] 
*phew*

Ben Gray [7:21 PM] 
`# OSX ONLY
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# rbenv
if which rbenv > /dev/null; then
 eval "$(rbenv init -)"
fi

#Git
function parse_git_branch {
 ref=$(git symbolic-ref HEAD 2> /dev/null) || return
 echo "("${ref#refs/heads/}")"
}
export PS1="\w \$(parse_git_branch)\$ "
export EDITOR='atom --wait'
export VISUAL='atom --wait'

eval "$(hub alias -s)"`

Ben Adamski [7:22 PM] 
Hmph.

[7:23]  
what does brew doctor output?

Ben Gray [7:23 PM] 
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
 git

Ben Adamski [7:23 PM] 
HEYYYY OOOOO

[7:24]  
oh wait

[7:24]  
that doesn’t help us

Ben Gray [7:24 PM] 
ha!

Ben Adamski [7:24 PM] 
i just thought i saw the simple thing i was hoping for

Kira MacLean [7:24 PM] 
i'm getting permission denied when i run `~/.bashrc`

Ben Adamski [7:25 PM] 
you mean `atom ~/.bashrc`? (edited)

Ben Gray [7:30 PM] 
it's weird to me that npm install seems to work fine if no server is running

[7:30]  
I can get the ember server up, but can't generate components while that's happening

Kira MacLean [8:09 PM] 
I will re run that

**Comment by ioncrash** [comment]
The behavior I'm seeing is that ember, npm, and bower commands seem only to work in one tab, and only when the ember server is not running (though I can't try anything in the tab with the server running in it of course)

**Comment by gaand** [comment]
If you open a new terminal (not just a new tab) and type any of those commands, do you get errors?

**Comment by ioncrash** [comment]
same error, yes

**Comment by ioncrash** [comment]
OK correction -- I restarted my computer and now no bash commands seem to run at all 😣

**Comment by gaand** [comment]
That's not good.

**Comment by ioncrash** [comment]
Antony helped me with this -- seems that something went wrong with brew, such that node was broken. Ran `brew upgrade`, which seemed to resolve the issue
