### ISSUE TITLE
Difficulty Getting Started with Ember

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#360]
I would like to have a conversation about starting the front-end of my app. I have the basics of the back end sorted out but now that I am working with the front end I am struggling with how to figure out separation of concerns. For example, the top layer of my application is Bands. A user should, at the welcome page be able to see a list of bands when they login and then they should be able to click on each band to go the next route/view. 

I am not sure if Bands should be a component, seems like it should be? Should I generate a new component or put the `form` to create it in the `application/template.hbs`. I can get a form on the index page and I can get the button associated with that form to `console.log` but I can't figure out how to get any data out of the form. I think it is directly related to the lack of organization.

Things are a bit jumbled so being able to draw up how it should be organized the "proper" way would be helpful. This is basically a plea for a one on one.

**Comment by payne-chris-r** [comment]
Try not to tie routes and resources together. Your routes should be dictated by the "views" or "visualizations" that you want your app to display. Do you want a place that someone can view a band's information? Then a 'band' (`/bands/:id`) route is likely a good name for that. Do you want to see ALL the bands? Then a `/bands` route is probably a good name for that. Just because your app deals with `bands` does not mean you need a `bands` route. It just has to do with the visualizations of the app.

**Comment by akradin** [comment]
Yeah, I definitely understand that idea. I have been playing around a bit with where to put various things but I can't get any actions to happen. This is my dilemma right now. So the issue outlined in the second paragraph is still happening. I will keep  playing around.

**Comment by raq929** [comment]
Throw some code our way and we can try to figure out what's going on.

**Comment by akradin** [comment]
Okay so under `application/template.hbs` I have:
```html
{{my-application signOut="signOut"}}

<form {{action 'newBand'}}>
  {{input}}
  <button>submit</button>
</form>
is anything here?
```

Which is perfect, a user can add a band when the log in. But, the form doesn't do anything.
In `application/route.js` I added this to actions.
```js
    newBand(){
     console.log("click click");
    }
```

And it console logs, which is great, but I know I cant get any data from this form because I have no `{{#each model as |band|}}` so doing something like `this.get('band')` in the route will be pointless.

**Comment by raq929** [comment]
Right. Take a look at how we made a new list in ember-resources. If you don't make progress with that in about 20 minutes, ping me and I'll come by.

**Comment by akradin** [comment]
Okay, so I added a model hook in the route and now nothing displays on the page, which makes sense because the hook doesn't really do anything so I suppose I could put that in a different route but I feel like there has to be a way to get the bands to show on login. I mean I get why nothing is showing up because there is nothing in store but I should still be able to see the nav bar?

```js
  model () {
    return this.get('store').findAll('band');
  },
```

**Comment by akradin** [comment]
I suppose the model hook has to be in a component?

**Comment by akradin** [comment]
Hmm okay so some progress. When I was doing `console.log('band is', band)` I was getting undefined. Rachel let me know this was because I never defined 'Band' in the route file. So, I went ahead and defined band as follows in `application/route.js`:
```js
  Band: {
    name: null
  },
```

Then, in actions, I am just trying to `console.log` and I have: 
```js
    newBand(){
      let band = this.get('Band');
      console.log(" band is", band);
    },
```
Now I am getting an error message whenever I type in the form which looks like this:
```html
<form {{action 'newBand' on='submit'}}>
  {{input placeholder="New Band"
          value=Band.name}}
  <button type="submit">Submit</button>
</form>
```

**Comment by akradin** [comment]
changed `value=Band.name` to `value=Band` and it is working...for now

**Comment by akradin** [comment]
I lied, when it is `value=Band` it console logs but the name part of the object is `null`.  If it is change it to `value=Band.name` any time you type it throws a debugger.

**Comment by raq929** [comment]
What's the error after the debugger?

**Comment by akradin** [comment]
`throw new _emberMetal.Error('Assertion Failed: ' + desc);`
If you step once it shows
`var i18nNatives = requireNative('i18n');` and then in console there are a bunch of errors
The first of which is:
`(CONTENT_SCRIPT context for fijaenjgknobfdombbdchngpamggajpm) Lazy require of i18n.binding did not set the binding field`

**Comment by raq929** [comment]
Well. That's a bunch of gobbletygook before it tells you it can't bind correctly.

**Comment by akradin** [comment]
Okay, so putting all of the same stuff for band into a component instead of a route works. So, that is the solution.
