### ISSUE TITLE
Planning how I should approach| using rails

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/capstone-project#364]
I was planning out working on a blog because I think it would be a good checkmark to have when people look at what applications I've built, and to update later after wdi to help document my progress with development progress/career etc.  

I want to use rails which I felt (more) comfortable and ember. I am trying to figure out how to set up the backend. I want to have blogposts  & comments on a post. So i think data structure-wise like 

`Post title:string author:string body:text`
& 
`Comment author:string body:text post:references`
So I have many posts. Posts have many comments. I just want to be create posts though and am trying to think about how to do that, but anyone who is a user comment.

Just wanted to document this, see if I was having a good approach, and if a consultant had any suggestions, comments, concerns they wanted to talk about for this project.

**Comment by raq929** [comment]
I think you probably want authors on both of these to be a reference to a user.

**Comment by jbuzzanco** [comment]
SO in the model have `user:references` instead of `author:string`?

**Comment by raq929** [comment]
Yep!

**Comment by jbuzzanco** [comment]
Ok cool! Would you say that as the only person who can create posts on my site, I would have to create a different scaffold, like administrator, or it could be just within users, and one and only one user can create blog posts?

**Comment by raq929** [comment]
If there's only one user, I would use open read controller for the posts, and simply not allow users to create accounts. :)

**Comment by jbuzzanco** [comment]
Ok thanks. I'll probably try and do that. That's all I can think of for right now so I think I'm gonna close this issue.
