### ISSUE TITLE
Need help writing records to mongo from ember

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/capstone-project#366]
I need help understanding the process of writing to a mongo collection from ember.

**Comment by raq929** [comment]
I'm not sure what you mean, can you clarify?

**Comment by treep78** [comment]
I' m having trouble understanding how ember communicates with a backend. For instance, if I want to read or write to a mongo collection, how do I determine which collection I want to access?

**Comment by treep78** [comment]
I need to create a model inside a folder with the same name as the collection I am accessing.
