### ISSUE TITLE
Issue with DS.store

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#371]
Alriiiiiight so I can finally make stuff!! I stopped working with Bands for the moment and I am now working with tasks. Whenever I load the tasks page or try to create a task there is an issue with ids.

So, for when the page loads I have a handlebars helper to load the data and I get a bunch of these
`ember.debug.js:6002 WARNING: Encountered "0" in payload, but no model was found for model name "0" (resolved model name using roadie@serializer:application:.modelNameFromPayloadKey("0"))`

One for each `task`

And then when I try to create a `task` it is created on the backend but I get this
`WARNING: Encountered "id" in payload, but no model was found for model name "id" (resolved model name using roadie@serializer:application:.modelNameFromPayloadKey("id"))`

So of course I tried adding `id` to the model. I got yelled at for that.

**Comment by gaand** [comment]
Did you base your API on express-api-template?

**Comment by akradin** [comment]
Nope, rails-api-template

**Comment by akradin** [comment]
I created a serializer (pluralization, or lack therof, MATTERS) and then restarted the server and this worked.
