### ISSUE TITLE
create-board CURL request, all parameters returning null

### ISSUE THREAD

**Issue by kmg1434** [ga-wdi-boston/capstone-project#373]
So I've done a CURL request for sign-up and sign-in and all is good. Got the token from the terminal and use it in the CURL request for creating a board. When I run the script, name, length, and width all show up as `null` in the browser. Even if I hard code these instead of using the ${PARAM} notation I get the same result. 

create-board.sh
```
API="http://localhost:4741"
URL_PATH="/boards"
TOKEN="BAhJIiU5NWE0ZTViMWUwMjhhNDk3NDQ0Njg0NTFiNTVkMjJmNwY6BkVG--f3ef78248f3f4aa2d9feb610c799ace25b8d078c"
NAME="lead"
LENGTH="1.5"
WIDTH="2.5"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
  --data '{
    "board": {
      "name": "lead",
      "length": "'"${LENGTH}"'",
      "width": "'"${WIDTH}"'"
    }
  }'
```

However, when I go into `rails console` and type `b = Board.create([{name: "lead", length: 1.5, width: 2.5}])` then I get the correct parameters to show! So it doesn't seem to be an issue with my back end, it seems to be a problem with the CURL request itself, but I can't figure it out. Any clues? I've used past projects and examples as reference to no avail.

**Comment by kmg1434** [comment]
So what I had to do was permit these parameters in my Board controller by changing my method to: 

```
  def board_params
    params.require(:board).permit(:name, :length, :width)
  end
```

But now for some reason, no matter how I type the curl request, the length and width are saved as string! I eventually want to have some virtual/calculated properties using these values so it would be a pain in the ass to have them saved as strings in the back end. I know it's probably a simple type casting in the front end but I still don't like the idea. In my schema it says:

```
create_table "boards", force: :cascade do |t|
    t.string   "name"
    t.decimal  "length"
    t.decimal  "width"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
  end
```

so these parameters SHOULD ONLY be allowed to be of decimal type... I'm quite confused as to why they are being forced to a string type.

**Comment by raq929** [comment]
@gaand do you know what's going on here?

**Comment by kmg1434** [comment]
I've tried writing an update CURL script to update the data to be decimals and this also does not work:

```
API="http://localhost:4741"
URL_PATH="/boards/"
ID="1"
TOKEN="BAhJIiU5NWE0ZTViMWUwMjhhNDk3NDQ0Njg0NTFiNTVkMjJmNwY6BkVG--f3ef78248f3f4aa2d9feb610c799ace25b8d078c"
curl "${API}${URL_PATH}${ID}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
  --data '{
    "board": {
      "name": "funk",
      "length": 9,
      "width": 9
    }
  }'
```

This still shows as strings in the database:

```
{
"id": 1,
"name": "funk",
"length": "9.0",
"width": "9.0",
"created_at": "2017-01-13T19:03:41.991Z",
"updated_at": "2017-01-13T20:59:22.679Z",
"user_id": 1
}
```

I have validations for numericality in the board model as well and this still happens:

```
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :pedals
  validates :length, numericality: true
  validates :width, numericality: true
end
```

Any ideas?

**Comment by gaand** [comment]
```diff
   --data '{
     "board": {
       "name": "lead",
-      "length": "'"${LENGTH}"'",
+      "length": '"${LENGTH}"',
-      "width": "'"${WIDTH}"'"
+      "width": '"${WIDTH}"'
     }
   }'
```

If you send strings, you get strings.

**Comment by kmg1434** [comment]
@gaand then why doesn't this work?:

```
--data '{
    "board": {
      "name": "funk",
      "length": 9,
      "width": 9
    }
  }'
```

**Comment by payne-chris-r** [comment]
What's the error it returns?

**Comment by kmg1434** [comment]
I'm sorry, I didn't elaborate on that last comment. There is no error @payne-chris-r it simply stores `length` and `width` as strings instead of decimals. What I'm going to do for now is use a method to convert them to decimals when I need to, but eventually I'd like to have it so they are actually stored as decimals in the back end.

**Comment by gaand** [comment]
It may be because `decimal` isn't a type in JavaScript/JSON. 

What does the data look like in the rails console or psql?

**Comment by payne-chris-r** [comment]
That's a good idea. Try it with `integer`/`number` (whichever one it is) and see if it works.

**Comment by kmg1434** [comment]
Well I looked up JavaScript primitive types and `number` was listed. I cannot use `integer` since I want users to be able to type decimals and fractions, since these data attributes are `length` and `width` most likely in inches. Most things wont be integer values.

So I went ahead and changed my migration file to this:

```
class CreateBoards < ActiveRecord::Migration
  def change
    create_table :boards do |t|
      t.string :name
      t.number :length
      t.number :width

      t.timestamps null: false
    end
  end
end
```

I then ran `bundle exec rake db:nuke_pave`.
Aside from getting a TON of gross rubocop errors in atom, I got this message in terminal:

```
-- create_table(:boards)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `number' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x007fed15f02c60>
/Users/Shrugs/wdi/projects/capstone-backend/db/migrate/20170113162921_create_boards.rb:5:in `block in change'
/Users/Shrugs/wdi/projects/capstone-backend/db/migrate/20170113162921_create_boards.rb:3:in `change'
/usr/local/var/rbenv/versions/2.3.1/bin/bundle:23:in `load'
/usr/local/var/rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
NoMethodError: undefined method `number' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x007fed15f02c60>
```

So it seems like Ruby doesn't know what `number` is, but Ruby documentation says otherwise. Is there a datatype I am missing? I'm a bit nervous to use `float` because of the frequent mention of lack of precision but this probably wouldn't be an issue when I only need 4 or 5 significant figures.

**Comment by kmg1434** [comment]
Every time I make an edit in Atom I get this big red window error:

```
Error: spawn rubocop ENOENT
Error: spawn rubocop ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by kmg1434** [comment]
So what I have done is edit my migration file to this:

```
class CreateBoards < ActiveRecord::Migration
  def change
    create_table :boards do |t|
      t.string :name
      t.float :length
      t.float :width

      t.timestamps null: false
    end
  end
end
```

and it seems to have worked! My back end now shows actual numbers instead of a damn string, which is great. My only issue is that I still have that damn rubocop ENOENT error and it's extremely annoying. Any idea what's going on there?

```
Error: spawn rubocop ENOENT
Error: spawn rubocop ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by payne-chris-r** [comment]
Woof. I hate these. I'll come take a look.

**Comment by kmg1434** [comment]
Woof. 🐶 

restarted Atom a second time. All seems ok for now.
