### ISSUE TITLE
Destroy Record Not a Function!?!😱

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#376]
I am trying to delete a task and  my console is claiming `destroyRecord` is not a function. 
[This little piece of documentation](https://guides.emberjs.com/v1.10.0/models/creating-and-deleting-records/) disagrees so I am assuming it is a me issue. Here is the task component, the delete button is at the bottom.
```html
<form {{action 'newTask' on='submit'
                toggleComplete='toggleComplete'}}>
{{input placeholder="Name" value=Task.name}}
{{input placeholder="due date" value=Task.due_date}}
{{input placeholder="priority level" value=Task.priority}}
{{input placeholder="details" value=Task.details}}
<button>new task</button>
</form>

{{#each list as |task|}}
  <div>{{task.name}}</div>
  <div>
    <button {{action 'deleteTask'}}>delete</button>
  </div>
{{/each}}
{{yield}}
```

and then the component.js file that handles the action, again, direct your attention to the bottom:
```js
import Ember from 'ember';

export default Ember.Component.extend({
  Task: {
    name: null,
    due_date: null,
    priority: null,
    details: null,
    completed: false
  },
  actions:{
    newTask(){
      let task = this.get('Task');
      console.log("start of task is", task);
      this.sendAction('newTask', this.get('Task'));
    },
    toggleComplete(){
      console.log('done');
    },
    deleteTask(){
      console.log("this task is being deleted, this task is", this.get('Task'));
      this.sendAction('deleteTask', this.get('Task'))
    },
  }
});
```

So the reason why it is not working is because it is not getting the `task`. In that `console.log` it shows all the task details as `null`, but why!??

**Comment by raq929** [comment]
Because Task in the component has all the details set to null.

**Comment by raq929** [comment]
You need to tell deleteTask about it's task instead of using the Task you're using for new Tasks.

**Comment by raq929** [comment]
Side note: The word Task starts sounding weird really quickly when you repeat it a lot.

**Comment by akradin** [comment]
Hhahahahahaha, so how would I set the task to not be null? make another component?

**Comment by raq929** [comment]
Take a look at ember-resources `app/lists/list/route.js`

**Comment by raq929** [comment]
Issue #302 might be helpful.

**Comment by payne-chris-r** [comment]
If you don't have the `task` it's because you didn't pass it down to this component appropriately.

**Comment by akradin** [comment]
I fixed it by making an component called edit that has a delete function. This is sent to the task-list component, and then the task route.
