### ISSUE TITLE
this.store.queryRecord seems to always return 1st record?

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/capstone-project#378]
I'm trying to make an action which will check to see if a record exists, and if it does, transition to the associated route, but at present it seems to always just go to the one at id:1. Here's my code

```js
export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('video');
  },
  actions: {
    changeVideo(ytid) {
      let result = this.store.queryRecord( 'video', { ytid: ytid } );
      // if(result){
        this.transitionTo('video', result);
      // } else {
      // console.log('in else');
      // }
    }
  }
});
```

I also tried using this.store.query instead, but that seemed to always give me 0 results. Any idea?

**Comment by payne-chris-r** [comment]
What is `ytid`? Is it defined? Can you log it? Take a look at what your rails server is saying the request looks like.

In addition, `this.store.queryRecord` returns a promise, _I believe_, so you may be transitioning to `video` before you have the `result`.

**Comment by ioncrash** [comment]
ytid is a string. Console.log gets the correct result. It's defined in an input box in another component and sent up via an action, so it doesn't . Here's where I pull ytid:

template:
```html
<div class="container">
    <div class="row">
        <div class="col-md-10">{{ember-youtube ytid=video.ytid}}</div>
        <div class="col-md-2">{{chat-box}}</div>
    </div>
    <div class="row"></div>
</div>


{{youtube-finder changeVideo='changeVideo'}}
```

component:
```js
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    changeVideo(ytid) {
      this.sendAction('changeVideo', ytid);
    },
  },
});
```

rails server shows the get request for videos:
SELECT "videos".* FROM "videos"

and then each video popping up

**Comment by payne-chris-r** [comment]
You may need to convert it to a number in order for findRecord to work. 
Also just an FYI (I've done it for you above), if you type `js` or `html` next to your ``` when you're writing github comments, github will format the code block using that language.

**Comment by ioncrash** [comment]
Ok, so how do I do that? I tried this

```js
actions: {
    changeVideo(ytid) {
      console.log(ytid);
      this.store.queryRecord( 'video', { ytid: ytid } )
        .then((video) => {
          console.log("video_id", video.get('id'))
        });
      // if(result){

      // } else {
      // console.log('in else');
      // }
    }
  }
```

but that always results in 1, which I guess is because the ember record has an id of 1? How do I get the actual video's id? Google is being unhelpful

**Comment by ioncrash** [comment]
OK so I think I figured out that my query is always returning the array of all videos, and so when I try to do anything with the results it always takes the first one. So I'm guessing there's something wrong with the ytid: ytid line?

**Comment by ioncrash** [comment]
AH! Ok so I notice my console was giving me this:

`XHR finished loading: GET "http://localhost:4741/videos?ytid=Nm2LwG8Jbio".`

so I think what's happening is that it's trying to query on that url, but since I haven't defined a query route, it just gives all of them back?

**Comment by raq929** [comment]
Likely. Why are you using queryRecord instead of findRecord?

**Comment by ioncrash** [comment]
My understanding is that findRecord only works if you know the id of the thing you're trying to retrieve. In this case, the user supplies a search term, and I want to find the id from that

**Comment by ioncrash** [comment]
OMG SOLVED:

```js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('video');
  },
  actions: {
    changeVideo(ytid) {
      let that = this;
      return new Ember.RSVP.Promise(function(resolve) {
        that.store.findAll('video')
          .then(function(videos) {
          resolve(videos.filterBy('ytid', ytid));
          });
      })
      .then((videos) => {
        let video_id = videos[0].get('id');
        this.transitionTo('video', video_id);
      });
    }
  }
});
```

might have been easier to set up a back-end query, but this works, so oh well!

**Comment by gaand** [comment]
Use `params[:ytid]` in your index action to access the value.
