### ISSUE TITLE
Displaying data as 'cards'

### ISSUE THREAD

**Issue by matthewgsommers** [ga-wdi-boston/capstone-project#379]
I'm having trouble turning my data into 'cards' as we did in the ember-resources repo. So my app is essentially an event tracker ('festivals' in this case, as in music festivals) and I'm attempting to display a list of festivals that can be clicked on in order to find out more about said festival. Each card is supposed to give the user a snapshot of that festival (i.e. display the title, a picture, and a brief description). 

As of right now, I'm able to display the title of each festival - my goal is to have users be able to click on a festival name in order to go to a view that displays more information about the festival they've clicked on. I want to turn them into 'cards' so that users are able to click a delete button to remove that festival from the festivals list. 

As I aforementioned, I'm able to display the title of each festival but they're not clickable because I dont have `/card` route on the `festivals` template. When I add `/card` to `festival-fanatic`'s template, I get the following error: 

"Assertion Failed: You attempted to define a `{{link-to "festival"}}` but did not pass the parameters required for generating its dynamic segments. More context objects were passed than there are dynamic segments for the route: festival.index"

Since I'm clearly having trouble finding where the error is stemming from, I'm going to show a bunch of code below. 

Code:

festivals/template.hbs:
```
<h2>Festival Fanatic</h2>
{{#each model as |festival|}}
// the line below is the source of the error but is also what I need in order for the cards to link
  {{festival-fanatic/card festival=festival
                           editFestival='editFestival'
                           delete='deleteFestival'}}
{{/each}}

{{#link-to 'festivals/new'}}
  Click Here to Add a Festival
{{/link-to}}
```

festivals/route.js: 
```
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('festival');
  }
});
```

festival/template.hbs:
```
{{festival-fanatic festival=model}}
```

festival/route.js:
```
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('festival', params.festival_id);
  },
});
```

components/festival-fanatic/template.hbs:
```
<div class='card-holder'>
  <h3 class='festival-title'>{{festival.title}}</h3>
</div>
```

components/festival-fanatic/card/template.hbs:
```
<h4>
  {{#link-to 'festival' festival}}
    {{festival.title}}
  {{/link-to}}

  <button class='btn btn-danger btn-xs' {{action 'delete'}}>Delete</button>
  <button class='btn btn-default btn-xs' {{action 'editFestival'}}>Edit</button>
</h4>
```

router.js: 
```
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
});

Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('festivals', function() {
    this.route('new');
  });
  this.route('festivals/new');
  this.route('festival', function() {
    this.route('edit');
  });
});

export default Router;
```

**Comment by raq929** [comment]
I don't understand why you're trying to link to the festival in `components/festival-fanatic/card/template.hbs`. Since that's what seems to be the problem, why don't you remove the link. Once the delete and edit buttons are working, you can add it back in. 
One step at a time!

**Comment by raq929** [comment]
Incidentally, you are linking to `festival/template.hbs` in that `link-to`, which might not exist, which would be a good reason for it to blow up.

**Comment by raq929** [comment]
What's your status here?

**Comment by matthewgsommers** [comment]
I was trying to link to the festival via the festival's card so that users could click a 'view more info about this festival' button on the card to go to a new view that contains more information on that festival than is being displayed on the card.

**Comment by raq929** [comment]
So, is this resolved? If you're still having a problem, what its it?

**Comment by matthewgsommers** [comment]
The general problem wasnt really resolved because I'm having trouble going to a specific `festival` view, but I'm pretty sure that part of the confusion is a result of poor naming conventions. I've decided to move forwards in a different direction. Instead of allowing users to see more information about a specific festival by clicking a view button, I'm going to display the aforementioned information on the `festivals` card and allow users to click a `comment` button that will take them to a `comment` view. Resolves the confusion around the naming convention & is essentially the next step I was going to take anyways.
