### ISSUE TITLE
Handlebars/click handler not working

### ISSUE THREAD

**Issue by eshimel** [ga-wdi-boston/capstone-project#38]
I'm trying to use handlebars to display a user's profile.  I am able to create/update/delete profiles on the front end.  I'm getting nothing when I try the "My Profile" button.  I put in a debugger, and it looks I'm not even getting to the click handler for showing the profiles.  I've compared ajax/handlers/html to see if there's a spelling or naming error, but I don't see anything.  I've asked other students to look for a naming error, but no luck.  

I've included what I think might be useful code for you to look at.  What would be the next course of action for me to take to figure out what's going on?

here's my ajax:
  get_profile: function (token, callback) {
    this.ajax({
      method: 'GET',
      url: this.url + '/profiles',
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType: 'application/json; charset=utf-8'
    }, callback);
  },

script.js...here's my click handler

 $("#jello").on('submit', function(e) {
        debugger;
        e.preventDefault();
        var token = $('.token').val();
        swap_api.get_profile(token, function(err, data) {
          if (err) {
            console.log(err);
            return;
          } else {
              var templateTarget = $('#my-profile-template').html();
              var template = Handlebars.compile(templateTarget);
              var content = template(data);
            $('#myProfile').html(content);
html:
 <script id="my-profile-template" type="x-handolebars-template">
    <table>
        <thead>
            <th>username</th>
            <th>studio</th>
            <th>website</th>
            <th>profileid</th>
        </thead>
           <tbody>
           {{each profiles}}
         <tr>
            <td>{{username}}</td>
            <td>{{studio}}</td>
            <td>{{website}}</td>
            <td><button id="edit-profile" type="button" data-id={{id}}>Edit</button></td>
            <td><button id="delete-profile" type="button" data-id={{id}}>Delete</button></td>
         </tr>
            {{/each}}
        </tbody>
        </table>
        </script>

div and buttons for handlebars:

<div><input id="jello" type="submit" value="ShowProfile"></div>

```
            <div id="myProfile" value="Profile"></div>
```

**Comment by eshimel** [comment]
I forgot the template

<script id="my-profile-template" type="x-handolebars-template">
    <table>
        <thead>
            <th>username</th>
            <th>studio</th>
            <th>website</th>
            <th>profileid</th>
        </thead>
           <tbody>
           {{each profiles}}
         <tr>
            <td>{{username}}</td>
            <td>{{studio}}</td>
            <td>{{website}}</td>
            <td><button id="edit-profile" type="button" data-id={{id}}>Edit</button></td>
            <td><button id="delete-profile" type="button" data-id={{id}}>Delete</button></td>
         </tr>
            {{/each}}
        </tbody>
        </table>
        </script>

**Comment by eshimel** [comment]
I mean forgot to share it...not solved the issue

**Comment by GA-MEB** [comment]
So the click handler isn't triggering? Are you sure that it's sending a `submit` event? What if you tell it to watch for `click` instead?

**Comment by eshimel** [comment]
thanks Matt...worked...well the click handler fired, getting tableheads but not table data...I'm console logging some stuff now...standby
