### ISSUE TITLE
cannot load a page containing data owned by other data

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/capstone-project#382]
had some trouble coming up with a title there...

what I've got is, videos have many riffs, so I want to make a page containing a video and with the riffs alongside. The video/:video_id page renders fine if riffs are not included in the video model, but when I add `riffs: DS.hasMany('riff')`, the page comes up blank.

Here are my models:

user:
```js
import DS from 'ember-data';

export default DS.Model.extend({
  email: DS.attr('string'),
  riffs: DS.hasMany('riff')
});
```

video:
```js
import DS from 'ember-data';

export default DS.Model.extend({
  ytid: DS.attr('string'),
  riffs: DS.hasMany('riff')
});
```

riff:
```js
import DS from 'ember-data';

export default DS.Model.extend({
  text: DS.attr('text'),
  flagged: DS.attr('boolean'),
  stamp: DS.attr('number'),
  video: DS.belongsTo('video'),
  user: DS.belongsTo('user')
});
```

As far as I can tell, everything in the models accurately reflects what's on the back end, so I'm not sure where the problem lies. Thoughts?

**Comment by raq929** [comment]
What is the data you are sending from the backend? Ember expects to get JUST ids for the riffs.  If you're including other data, it will be unhappy. 

Is your backend set up to receive GET requests for the riffs?

**Comment by raq929** [comment]
What does your network tab show when you try to display this?

**Comment by ioncrash** [comment]
backend is sending this:

```
{
"video": {
"id": 1,
"ytid": "g3a4jA0jfrk",
"users": [
{
"id": 1,
"email": "herp@derp.com",
"token": "7e554cdcba48c1ffae39dadb517f58bc",
"password_digest": "$2a$10$q6mHy8El1KceM3DGUW0hrOP.2et4fVc.48E3o/ZNNwbG9PoaBxjyC",
"created_at": "2017-01-13T21:23:42.711Z",
"updated_at": "2017-01-14T09:54:16.675Z"
}
],
"riffs": [
{
"id": 1,
"user_id": 1,
"text": "This is rif 1000",
"stamp": 3,
"flagged": false,
"created_at": "2017-01-13T21:36:31.688Z",
"updated_at": "2017-01-13T21:36:31.688Z",
"video_id": 1
}
]
}
}
```

You're saying that should just have an id for riffs instead of all the info? I thought the hasMany/belongsTo on rails was meant to set things up this way.

Yes, backend can receive get requests for riffs. Here's http://localhost:4741/riffs/1

{
"riff": {
"id": 1,
"text": "This is rif 1000",
"stamp": 3,
"flagged": false,
"user_id": 1,
"video_id": 1,
"editable": false
}
}

Network tab shows this:

<img width="1018" alt="screen shot 2017-01-15 at 3 42 45 pm" src="https://cloud.githubusercontent.com/assets/7295863/21966049/1e668b24-db3a-11e6-907d-bee54333bff0.png">

**Comment by ioncrash** [comment]
ah! Solved. Back end serializer was messed up. Had forgotten to add definitions.

in riff_serializer

```js
def video
    object.video.id
  end

  def user
    object.user.id
  end
```

in video_serializer

```js
def riffs
    object.riffs.pluck(:id)
  end
```

and in user_serializer

```js
def riffs
    object.riffs.pluck(:id)
  end
```
