### ISSUE TITLE
One on One Request

### ISSUE THREAD

**Issue by rickdean** [ga-wdi-boston/capstone-project#383]
I'd like to sit down with someone for a few minutes regarding Heroku responsiveness.  I experience a delay in Heroku processing a delete request to my db.  Most of what I've read online points to a slow response time with Heroku for free accounts.  This delay does not happen when I process deletes locally (on local front-end to back-end server calls).  I want to make ensure that I do not experience this during presentation and that my code for the delete requests are not the issue in any way.

**Comment by raq929** [comment]
Hmmm... usually Heroku only has a delay on the *first* request, and then other requests are processed quickly. If that's different than what you're seeing, then yeah, we should take a look at it.
The deletes are successful, I assume?
Are you deleting multiple things with a single request?

**Comment by rickdean** [comment]
It does seem to be a delay on the first request (throws a 404 error as well).  After a few moments it goes through ok and then every subsequent delete is fine without any issues.  And yes - it is one item at a time.  I thought about setting up a ping to keep it open (instead of allowing it to go to sleep after a few minutes) but that seems like overkill.

My delete event appears to be pretty standard:  

```
  const onDeleteItem = function(){
    let id = event.target.getAttribute('data-id');
    // console.log('DELETED', id);
    api.deleteItem(id)
      .then(ui.deleteItemSuccess)
      .then(function(){
        onGetList();
      })
      .catch(ui.deleteItemFailure);
  };
```

Thanks Rachel!

**Comment by rickdean** [comment]
Turned out not to be a heroku performance issue but instead had to do with my 'delete' event. Changing the second line from  "let id = event.target.getAttribute('data-id');" to 
"let id = $(event.target).attr("data-id");" fixed the issue.

Many thanks to Rachel for catching this :)
