### ISSUE TITLE
Can't render model data but getting 200 OK

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/capstone-project#385]
This is probably because I'm doing something dumb but I'm getting a 200OK request from the back end when I index all of my artwalks but view a white page when I include the model on the front. I'm not getting error in the console, and I know it's a problem with a model because I can see test text when I remove the model from the route entirely. 

artwalks/route.js
```js 
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('artwalk');
  },
});
```

artwalks/template.hbs
```
<h2>Artwalks</h2>

<ul>
{{#each model as |artwalk|}}
  <li>{{artwalk.title}}</li>
{{/each}}
</ul>

testing artwalks
```

artwalk/model.js
``` js
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string')
});
```

**Comment by gaand** [comment]
Which adapter are you using?

**Comment by kiraamaa** [comment]
ActiveModelAdapter

**Comment by gaand** [comment]
Okay.  Someone else had an issue with the adapter.  Does the data you expect show up in the network tab in chrome (click in the name column)?

**Comment by kiraamaa** [comment]
Yes it does show up. I used the same code/formatting for my `/artwalks` route as my `/users` route. While the network tab looks identical across the two only users is rendering. 
![screen shot 2017-01-15 at 3 27 54 pm](https://cloud.githubusercontent.com/assets/22806924/21965935/7eefd656-db37-11e6-96f8-be4e93de5cff.png)
![screen shot 2017-01-15 at 3 28 19 pm](https://cloud.githubusercontent.com/assets/22806924/21965934/7eeff1cc-db37-11e6-825f-b901e6cee723.png)

**Comment by gaand** [comment]
If you click on artwalks in that view and then on response, what's shown?

**Comment by kiraamaa** [comment]
The first artwalks shows index.html, second shows "no response data available", and third shows 
```
{"artwalks":[{"title":"Local Art Gallery Gander","length":"2.5 hours"},{"title":"Sculpture Saunter","length":"1.5 hours"},{"title":"Hipster Walk","length":"2.5 hours"}]}
```
which is the data from the back end that I'd like to render.

**Comment by gaand** [comment]
I can't see anything wrong.  

Does `testing artwalks` show?  Do you get any errors in the console?

**Comment by kiraamaa** [comment]
I don't see anything when I include the model and I don't get any errors in the console... I can only see "testing artwalks" when I comment out or remove the model code from my artwalks/route.js file
```
import Ember from 'ember';

export default Ember.Route.extend({
  // model () {
  //   return this.get('store').findAll('artwalk');
  // },
});
```

**Comment by gaand** [comment]
If you leave the model hook but comment out or remove the handlebars that uses it, do you see the text?

**Comment by kiraamaa** [comment]
No, then I get an error message on the page that says something went wrong.

**Comment by gaand** [comment]
What happens if you just return an array of objects with titles from the model hook?

**Comment by kiraamaa** [comment]
That actually works... How do I render all of my artwalks then? I know that I have them because I can see them in my API but apparently I'm not calling them correctly.

**Comment by kiraamaa** [comment]
I can see an ul of artwalks now but they're not the ones from the back end that I need. 

artwalks/route.js
``` js
import Ember from 'ember';

let artwalks = [{
  id: 1,
  title: 'Cool walk'
}, {
  id: 2,
  title: 'Other walk'
}, {
  id: 3,
  title: 'Downtown walk'
}];

export default Ember.Route.extend({
  model() {
    return artwalks;
  },
});
```

artwalks/template.hbs
``` hbs
<h2>Artwalks</h2>

<ul>
{{#each model as |artwalk|}}
  <li>{{artwalk.title}}</li>
{{/each}}
</ul>
```

**Comment by gaand** [comment]
I think I see now.  You're serializer isn't returning ids.

**Comment by kiraamaa** [comment]
That was the problem. Thank you!!

**Comment by kiraamaa** [comment]
I was unable to see my artwalk using the model hook 
``` js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('artwalk');
  },
});
```
because my artwalk serializer didn't include ids. My serializer now looks like so:
``` rb
class ArtwalkSerializer < ActiveModel::Serializer
  attributes :title, :length, :id
end
```
