### ISSUE TITLE
Trying to link Ownership

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#386]
The way my app is laid out is a user has many bands, and the idea is when you click on a band you should be able to see the tasks. I am not sure how to get this to happen. As of right now, my backend is configured to allow this to happen, but when I look at my database and do a search for tasks, there is a `band_id` column, but the column is empty.

I am thinking there has to be something in the `create` function of the task controller, but I am not quite sure. I did add `band_id` into `task_params` method but that is as far as I got.

**Comment by raq929** [comment]
Did you add the relationships? You'll need a `has_many` and `belongs_to` relationship on the models. 
Also, I would be sure to check the controller using curl so you can be sure it's working before you try to access tasks on the front end.

**Comment by akradin** [comment]
Yup, I have added the relevant relationships and tested with curl requests

**Comment by raq929** [comment]
OK, so are you still having the same problem?
Can I see the create function for your tasks controller? How are you telling it about the band_id?

**Comment by akradin** [comment]
That is the root of my question, I have run through a few things in my head but I can't figure out how to correlate `band_id` into the `create` function. I keep getting hung up because I am not sure if `current_user` is involved. When you create a band, it has `current_user` functionality so shouldn't it inherently move down the chain to creating tasks? This is why I don't know what to put in the create function but here it is:
```rb
  def create
    @task = Task.new(task_params)

    if @task.save
      render json: @task, status: :created
    else
      render json: @task.errors, status: :unprocessible_entity
    end
  end
```

**Comment by raq929** [comment]
So, current_user can have multiple bands, yes? You can let them choose which band they're creating the task for - or get the band from the route you're on, if they're making the create task from `bands/<band_name>/tasks` (or similar).

**Comment by akradin** [comment]
Yeah, I want to go with option two. So when I render the Band Names, I should have a link to that individual bands task route. So i need to somehow get the band ID so it will direct me to the `bands/<band_id>/tasks`. Ideally you would just be able to click on the bands and it will direct you to the task but I am not sure how to do this. I could add a button in the interim, but I am not sure how I would refactor all my code to incorporate this new route? Would I just put the `tasks` route folder into the `bands` route? or could I do `/tasks/<band_id>`?

**Comment by akradin** [comment]
The issue right now is grabbing the id. When I do something like this:
```html
{{#each band as |band|}}
  <div {{action 'transition' on='click'}}>{{band.name}}</div>
{{band-list/card band=band
                    edit='editBand'
                  delete='deleteBand'}}

{{/each}}
```

I can click on the band but when you console log the data, it only returns an empty object

**Comment by payne-chris-r** [comment]
Alex is working on this now. He's going to use query params to make a GET to `/tasks` in order to pass the `band_id`. Once that's working, we'll need to modify the adapter for `tasks` to expect the `band_id` and pass it along with the req to the API.

**Comment by akradin** [comment]
Yup, so currently the task index method is as follows
```rb
  def index
    @tasks = Task.where(:band_id => params[:band])
    puts 'params is'
    puts params
    render json: @tasks
  end
```

I tested with curl requests. When you do a post when setting the `band_id` it looks like this:
```sh
TOKEN="<some_token>"

curl --include --request POST http://localhost:4741/tasks \
--header "Authorization: Token token=${TOKEN}" \
--header "Content-Type: application/json" \
  --data '{
    "task": {
      "name": "call rick",
      "due_date": "2017-03-01",
      "priority": 1,
      "details": "details",
      "completed": "false",
      "band_id": 11
    }
  }'
```
That posts successfully and then when you make a get request:
```sh
TOKEN="BAhJIiU3YTcwMzZkMzNiYTRhN2VjZWYwMjdmMWQyN2RmZDllMgY6BkVG--262c4bf4874042e1b89f8e8edbef4f0a5ad460ee"

curl --include --request GET http://localhost:4741/tasks?band=11 \
--header "Authorization: Token token=${TOKEN}" \
--header "Content-Type: application/json" \
```
That works as well, it will show all the tasks associated with the `band_id` which is represented in the url by the `tasks?band=11`

We also added a `band` route so when you type in something like `http://localhost:7165/bands/11`
it will render this template:
```html
{{#link-to 'tasks'}}
<div>Tasks</div>
{{/link-to}}
```
Which means I need to change my router so the `tasks` route has a path like this:
```js
this.route('tasks', { path: 'tasks?band=:band_id' });
```
When I type something like `http://localhost:7165/tasks?band=11` I get a debugger so I tried
hard coding it, so
```js
this.route('tasks', { path: 'tasks?band=11' });
```
it works, but it shows **all** tasks. So what needs to happen is the `link-to` needs to grab the `band_id` somehow and use that in the route so as to show the necessary tasks

[Looks like this might be relevant](https://guides.emberjs.com/v2.7.0/routing/query-params/) but about 97% of that article is going over my head. I think I need to `Opting into a Full Transition` part of the article but I can't seem to wrap my head around how to translate their example into my application.

**Comment by payne-chris-r** [comment]
So, careful here. You're mixing `ember` and `rails` routing. It's easy to do. The change you've just made is in rails. Which means you need to tell ember that when it goes to GET `tasks`, it needs to make a request to that NEW route with the query params instead of a req to `/tasks`

**Comment by akradin** [comment]
@payne-chris-r I updated the comment at the same time you posted that comment. : D

**Comment by akradin** [comment]
tried some stuff. Added this in my tasks route
```js
  queryParams:{
    band_id: {
        refreshModel: true
    }
  },
  model(params){
    return this.get('store').query('Task', params);

  },
```

Changed router to 
```js
this.route('tasks', { path: 'tasks?band=:band_id' });
```

When you click on tasks for a band it just sends you to the above path and shows the user all tasks. In other words, `:band_id` isn't doing anything

**Comment by raq929** [comment]
What is the URL that it sends you to? In your browser?

**Comment by akradin** [comment]
the same exact one in the path 😆 `http://localhost:7165/tasks?band=:band_id` and if i type in
`http://localhost:7165/tasks?band=11` I get the old debugger

**Comment by raq929** [comment]
Oh, yeah, that's not what you want. Have you taken a look at this yet? 
It seems like you might need a controller. But I think you could probably do this without query params? Slack me if you want to explore that route. 
https://guides.emberjs.com/v1.10.0/routing/query-params/

**Comment by akradin** [comment]
Yeah I saw that but I wasn't sure what the deal with controllers were with the ember-auth template.
P.S. I think that is the same link I posted above but with a different ember version

**Comment by akradin** [comment]
Update: Added this method onto the Band Serializer
```rb
  def tasks
    object.tasks.map(&:id)
  end
```
This enables it so the get request only gets the task id

Then we added a bunch of stuff to the front end.

`ember g route band/tasks` which created the following route:
```js
  this.route('band', { path: 'bands/:band_id' }, function() {
    this.route('tasks');
  });
```

In that routes template we just added content to see if it would load, it did not. 

The `band` model looks like this
```js
export default DS.Model.extend({
  name: DS.attr('string'),
  tasks: DS.hasMany('tasks')
});
```

and the `band/tasks/route.js` looks like this
import Ember from 'ember';
```js
export default Ember.Route.extend({
  model(params){
    return this.get('store').findRecord('band', params.band_id).get('tasks');
  }
});
```

Lastly, the `link-to` looks like this  in the `band` route
```html
{{#link-to 'band/tasks' tasks}}
<div>Tasks</div>
{{/link-to}}
```

**Comment by akradin** [comment]
added this into the task model as well.
```js
  band: DS.belongsTo('bands')
```

**Comment by raq929** [comment]
Wait, band belongs to bands?

**Comment by akradin** [comment]
oops, changed it to `task`, still doesn't work
also change `band: DS.hasMany('tasks')` in band model

**Comment by raq929** [comment]
I'm confused. A task has a band, no?

**Comment by akradin** [comment]
A band has many tasks

**Comment by akradin** [comment]
So the issue is definitely something to do with the `link-to` and passing it the parameter `task`.  If someone could give me a hand before the day is over, I would be stoked.

**Comment by akradin** [comment]
@BenGitsCode

**Comment by kmg1434** [comment]
@BenGitsCode

**Comment by raq929** [comment]
Can you use a component instead of `link-to`?

**Comment by akradin** [comment]
I suppose...I tried that but was still getting the same issue

**Comment by raq929** [comment]
If it were me, I'd use the method I have a model for, because then you can compare what ember-resources does against what you're doing.

**Comment by akradin** [comment]
I am pretty certain I have crossed the threshold of not being able to compare my app to ember-resources. I have been using that as reference for the past hour in an attempt to get it to work.

**Comment by akradin** [comment]
Yeah, I definitely can't compare my app to ember-resources. Some in-person assistance would be helpful.

**Comment by akradin** [comment]
ZOMG THE ISSUE IS LIKE 98% SOLVED RACHEL IS DA BOMB.COM
This solution is going to be relatively lengthy so bear with me.
 
On the route level there is a `band` route and then a nested route called `band/tasks`.
The band route.js file has the following model hook:
```js
  model(params){
    return this.get('store').findRecord('band', params.band_id);
  },
```
And its template is a link-to `'band/tasks' model`

The `band/tasks` route has the same model hook as above and this renders the following template:
```html
{{#each model.tasks as |task|}}
<div>{{task.name}}</div>
{{task-list/edit}}
{{/each}}
{{task-list task=task
            newTask='newTask'}}
```

And the model.tasks is because in the band model it has `tasks: DS.hasMany('tasks')`

In the router we added this route
```js
  this.route('band/tasks', { path: 'band/:band_id/tasks'});
```

So now when you click on a band and click on the tasks link you can see all of the tasks that is associated with that band.

Keeping the issue open for now because I can only create tasks with a band_id through the backend, so once I get that sorted out on the front end I will close this issue.

**Comment by akradin** [comment]
Hi, me again. I can't figure out how to get the band_id linked to the task. As you can see above, the `band/task` template calls the `task-list`  component. What is interesting is the tasks post, but there is no band_id associated with them. So I will just show all the functions because I am failry certain it is an issue with `transitionTo` and/or `sendAction`. So low level, component:
```js
    newTask(){
      let task = this.get('Task');
      this.sendAction('newTask', task);
      console.log('click?', task);
    },
```

and log returns all information in the form. Then it is sent to the tasks route, which looks like this
```js
    newTask(task){
      console.log('you getting this click?');
      this.transitionTo('band/tasks', task);
    },
```

So this log returns nothing, which is weird because, the task does post. 
Here is the band/tasks route
```js
    newTask(newTask){
      let task = this.get('store').createRecord('task', newTask);
      console.log("band id is", this.get('band'));
      task.save();
    }
```

Now I know I assume I need to do something like `task.band` somewhere, just not sure where. Maybe an adapter?

**Comment by raq929** [comment]
OK, I think `newTask` is a confusing name for a click handler. How about `createTask`. I expect `newTask` to be a task object.

Why are you transitioning to a new route before saving the task? I'm confused.

**Comment by akradin** [comment]
Okay, changed it all to `createTask` . To answer your question, I assumed that if I was in task-list component and I did a `sendAction` it would automatically send it to the `/tasks` route but since we changed the router above and `/tasks` doesn't exist it looks like it goes up to `band/tasks` which is neat.

Okay so now things look a bit different.

task-list:
```js
    createTask(){
      let task = this.get('Task');
      this.sendAction('createTask', task);
      task.band = this.get('band.id');
      console.log('band is', this.get('band.id'));
      console.log('click?', task);
    },
```

So now this saves the task and it extrapolates the band_id but it is still not adding the `band_id` on the backend. Gonna take a break and keep investigating.

**Comment by akradin** [comment]
An adapter is the solution. So I had to change my backend route
```rb
post 'band/:band_id/tasks', to: 'tasks#create'
```
This way it matches the front end.
 then under `app/task` I created an adapter: 
```js
import ApplicationAdapter from 'roadie/application/adapter';

export default ApplicationAdapter.extend({
  createRecord (store, type, record) {
    let api = this.get('host');
    let serialized = this.serialize(record, { includeid: true });
    console.log("serialized is ", serialized);
    let bandId = serialized.band_id;
    let url = `${api}/band/${bandId}/tasks`;
    let data = { task : serialized };


    return this.ajax(url, 'POST', { data });
  }
});
```

And it works!! Huge shoutout to @sujkid and @raq929 for the help <3
