### ISSUE TITLE
Redirect Action to Another Route

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/capstone-project#387]
I have two route folders at the top-level of my application -  shops and shop. I currently have a delete action in a component but the shop is passed up to my shops router. This results in the wrong call being made to shops/:id rather than shop/:id. How do I pass the shop from the shops to shop?

**shops/route**
```js
export default Ember.Route.extend({
  model() {
    return this.get('store').findAll('shop');
  },
  actions: {
    delete(shop) {
      console.log("Shops/route", shop);
      this.transitionTo('shop', shop); // this didn't work.
    },
  }
});
```

**Comment by gaand** [comment]
Please post your routes file.

**Comment by coffeeisamazing** [comment]
**router.js**
```js
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
});

Router.map(function () {

  // auth routes
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');

  // app routes
  this.route('shops');
  this.route('shops/new');
  this.route('shop', { path: 'shops/:id' });
});

export default Router;
```

**Comment by gaand** [comment]
What do you mean by 

>This results in the wrong call being made to shops/:id rather than shop/:id

The path in the url should be `shops/<id here>` as specified by 

```js
  this.route('shop', { path: 'shops/:id' });
```

which is the correct way to do it.

**Comment by coffeeisamazing** [comment]
I meant that for "delete" I thought it was appropriate to route to /shop as an individual item rather than /shops as the collection. If this is not the case, then I may be able to simply update my backend route from .delete('/shop/:id', 'shop#destroy') to .delete('/shops/:id', 'shops#destroy').

**Comment by gaand** [comment]
Now I understand.  The back-end route path should be plural.  Think of it as a collection with the id as an index.

**Comment by gaand** [comment]
Ember names the routes, singular and plural, which is separate from the path which is always plural for a collection resource.

**Comment by coffeeisamazing** [comment]
Thanks, that makes sense. I've made the change and delete is now removing the record from the database, however, the page is not updated and an error message is given in the console. I've done some research and it looks like this is often due to trying to parse JSON strings that are already JSON...but I couldn't find any instances of JSON.parse in my code.

```bash
jquery.js:9536 XHR finished loading: DELETE "http://localhost:4741/shops/587bcaa0906a83380046b4af".
send @ jquery.js:9536
ajax @ jquery.js:9143
_ajaxRequest @ rest.js:976
(anonymous) @ rest.js:966
initializePromise @ ember.debug.js:58213
Promise @ ember.debug.js:58698
ajax @ rest.js:949
deleteRecord @ rest.js:747
_commit @ store.js:2335
(anonymous) @ store.js:1603
flushPendingSave @ store.js:1586
invoke @ ember.debug.js:339
flush @ ember.debug.js:407
flush @ ember.debug.js:531
end @ ember.debug.js:601
run @ ember.debug.js:724
run @ ember.debug.js:21514
handler @ ember.debug.js:11103
(anonymous) @ ember.debug.js:41005
dispatch @ jquery.js:5201
elemData.handle @ jquery.js:5009
2017-01-15 16:03:53.102 ember.debug.js:16905 SyntaxError: Unexpected token O in JSON at position 0
    at parse (<anonymous>)
    at ajaxConvert (jquery.js:8724)
    at done (jquery.js:9192)
    at XMLHttpRequest.<anonymous> (jquery.js:9484)
```

**Comment by gaand** [comment]
What's the response code for the delete in chrome's network tab?

**Comment by coffeeisamazing** [comment]
Looks like there are two triggered upon clicking delete.
587be5778264694cbb6a7e36	204	xhr	jquery.js:9536	284 B	3 ms	
587be5778264694cbb6a7e36	200	xhr	Other	267 B	5 ms

**Comment by gaand** [comment]
Please post the API's delete action for shops.

**Comment by coffeeisamazing** [comment]
**shops#destroy**
```js
const destroy = (req, res, next) => {
  let search = { _id: req.params.id };
  Shop.findOne(search)
    .then(shop => {
      if (!shop) {
        return next();
      }

      return shop.remove()
        .then(() => res.sendStatus(200));
    })
    .catch(err => next(err));
};
```

**Comment by gaand** [comment]
Does this make a difference?

```diff
       return shop.remove()
-        .then(() => res.sendStatus(200));
+        .then(() => res.sendStatus(204));
     })
     .catch(err => next(err));
```

**Comment by coffeeisamazing** [comment]
That fixed it. Working as expected now. Why would that make the difference?

**Comment by gaand** [comment]
`204` means `No Content`.

**Comment by coffeeisamazing** [comment]
Thanks Antony. Appreciate the help.

**Solution**
- Change API route from /shop/:id to /shops/:id.
- Update the API destroy method response status code from 200 to 204.
