### ISSUE TITLE
Creating a goal with start and end dates

### ISSUE THREAD

**Issue by ielole** [ga-wdi-boston/capstone-project#388]
My start and end date data is not transferring from my form to my database or DS 'store'. I can enter the information in the form, the title persists, but neither date persists.

goal-display/edit-goal template.hbs
```js

form {{ action 'save' on='submit'}}>
  <label for="goal-name">Name of Goal</label>
  {{input placeholder='Name of Goal'
          value=goal.title}}
  <label for="goal-start-date">Start Date</label>
  {{input type='date'
          value=goal.startDate}}
  <label for="goal-end-date">End Date</label>
  {{input type='date'
          value=goal.endDate}}
  <button class="btn btn-xs btn-success" type="submit">Save</button>
</form>

```

goal-display/edit goal component.js
```js

import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    save () {
      this.sendAction('save', this.get('goal'));
    },
  },
});

```

goals/new-goal template.hbs
```js

{{goal-display/edit-goal  goal=model
                          save='createGoal'}}

```

goals/new-goal route.js
```js

import Ember from 'ember';

export default Ember.Route.extend({
  model (){
    return this.get('store').createRecord('goal', {});
  },
  actions: {
    createGoal (goal) {
      // let goal = data;
      console.log("I'm inside goals/new-goal route.js and this is goal: ", goal);
      console.log("This is this.get('goal'): ", this.get('goal'));
      goal.save();
    },
  },
});

```

The goal object returned from this 'log' (console.log("I'm inside goals/new-goal route.js and this is goal: ", goal);), is below. I realize that this means the data is not being transferred, but I'm not sure what to do to get the dates to be saved. Curl requests, to create a goal, to the back end display their dates.
```js
data: EmptyObject
endDate: null
startDate: null
title: "Work"
```

**Comment by gaand** [comment]
Please post the ember model definition.

**Comment by ielole** [comment]
goal model.js
```js

import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  startDate: DS.attr('date'),
  endDate: DS.attr('date'),
});
```

**Comment by gaand** [comment]
Please log `this.get('goal.startDate')` in the component's save action.

**Comment by ielole** [comment]
```js
This is this.get('goal.startDate'): 2017-01-15
```

**Comment by gaand** [comment]
Now in `createGoal` please.

**Comment by ielole** [comment]
```js
This is this.get('goal.startDate'): undefined
```

**Comment by gaand** [comment]
Please change that to `goal.get('startDate')`.

**Comment by ielole** [comment]
Here are the placements of the logs in the goals/new-goal route.js:

```js

import Ember from 'ember';

export default Ember.Route.extend({
  model (){
    return this.get('store').createRecord('goal', {});
  },
  actions: {
    createGoal (goal) {
      // let goal = data;
      console.log("I'm inside goals/new-goal route.js and this is goal: ", goal);
      console.log("This is this.get('goal'): ", this.get('goal'));
      console.log("This is this.get('goal.startDate'):", this.get('goal.startDate'));
      goal.save();
      console.log("I'm inside goals/new-goal route.js and this is goal: after save", goal);
      console.log("This is this.get('goal.startDate'), AFTER save:", this.get('goal.startDate'));
    },
  },
});
```

Both 'log's for 'goal.startDate' returned undefined.

**Comment by ielole** [comment]
```js
This is goal.get('startDate'), AFTER save: 2017-01-15
```

**Comment by gaand** [comment]
Have a look in the network tab in chrome.  Is the request sending the dates?

If it is, then look at the server log.  Does the server get the dates?

**Comment by ielole** [comment]
It's null in the network tab, I'm working on attaching a screen shot.

**Comment by ielole** [comment]
[https://www.dropbox.com/s/bggmovvgbw1dlph/Screenshot%202017-01-15%2016.34.20.png?dl=0](url)

**Comment by ielole** [comment]
![chrome network screenshot](https://cloud.githubusercontent.com/assets/16413561/21966470/b704b2a0-db41-11e6-90fd-f4e48db80622.png)

**Comment by gaand** [comment]
Are you entering a date before you click save?  That image doesn't have dates in the inputs.

**Comment by ielole** [comment]
yes, the image is from after the save button was clicked

**Comment by gaand** [comment]
Does it log a valid date before the save?

**Comment by ielole** [comment]
console.log("This is this.get('goal.startDate'):", this.get('goal.startDate')); logs undefined
console.log("This is this.get('goal.startDate'):", goal.get('startDate'));  logs 2017-01-15
 
Both are before goal.save();

**Comment by gaand** [comment]
Does the goal get added to the store?  Does it have dates if it does?

**Comment by ielole** [comment]
The goal is added to the store with 'null' for both dates.

**Comment by gaand** [comment]
What's different if you change the argument to `DS.attr` from `date` to `string`?

**Comment by ielole** [comment]
Changing DS.attr argument from date to string fixed the issue, the dates are now being added to the DS 'store' and to the database as well.

**Comment by ielole** [comment]
Working code from goal/model.js file.

```js
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  startDate: DS.attr('string'),
  endDate: DS.attr('string'),
});

```
