### ISSUE TITLE
Not connecting my image uploads to aws-sdk

### ISSUE THREAD

**Issue by LaurenGrant** [ga-wdi-boston/capstone-project#39]
I am using paperclip and have installed the paperclip and aws gems needed. I followed Matt's repo to incorporate paperclip on the back-end and added the file reader in my js file. 

When testing this out the image file is read and I can see it in my local database however the image is not being saved in the bucket in AWS S3. 

There are no error messages that I am getting so I am not sure what I am missing.

**Comment by GA-MEB** [comment]
Is your configuration information in `.env` correct? Is it sending the images to the correct bucket?

**Comment by LaurenGrant** [comment]
Yes. Both are correct.

**Comment by jrhorn424** [comment]
Was this resolved and is it related to #42?

Is the image saving now?

**Comment by LaurenGrant** [comment]
This issue is resolved. I can save to AWS. I cannot render the image on my front end from handlebars. I opened issue #44 for that.
