### ISSUE TITLE
How to make landing page without navbar

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/capstone-project#390]
I've tried a couple different things and I cannot figure out how to make a landing page that just shows two lines of text and a button, with the button rendering the 'my-application' component on click. How do I do this? Every other attempt either removes the navbar from the other pages entirely or renders twice the content.

**Comment by gaand** [comment]
Would you please expand on the use case?  This is for someone not signed in?  Or just the root route? Or something else?

**Comment by raq929** [comment]
I would do this by creating an `index` route in the `application` folder.  I believe `ember-routing-dynamic` has an example of that technique.

**Comment by kiraamaa** [comment]
The use case would be for someone not signed in and it would be the root route. I just want users to be able to see a title and a button, click the button, and the load a navbar

**Comment by kiraamaa** [comment]
I'll try the index route in the application

**Comment by kiraamaa** [comment]
I ended up adding the `my-application` component to all of my routes except the application route and adding an outlet in the application template that links to a new index route.
