### ISSUE TITLE
help with handlebars conditionals

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/capstone-project#391]
So I'm trying to have riffs appear as a video plays, using handlebars if/thens. So far, I'm not getting the results I want. 

Template:

```html
{{#if isDisplayed}}
  {{riff.user.email}}: {{riff.text}} -- @{{riff.stamp}} seconds
{{/if}}

<button {{action 'test'}}>button</button>
```

and component:

```js
import Ember from 'ember';

export default Ember.Component.extend({
  currentTime: null,
  stamp: Ember.computed('riff', function() {return this.get('riff').get('stamp')}),

  isDisplayed: Ember.computed.gt('currentTime', 'stamp'),

  actions: {
    test() {
      console.log(this.get('isDisplayed'));
    }
  }
});
```

currentTime comes down from the outer component, as well as riff, and it looks like isDisplayed either always returns false, or always true, depending on how I set up isDisplayed.

I tried using typeof and determined that stamp is a number, but currentTime is an object, so maybe that's why? How do I get the value out of it?

**Comment by ioncrash** [comment]
sorry scratch that. It just always returns false. Also tried this:

```js
  isDisplayed: Ember.computed('currentTime', 'stamp', function() {
    return this.get('currentTime') > this.get('stamp');
  }),```

always false

**Comment by ioncrash** [comment]
got it. for some reason it likes this better:

```js
isDisplayed: Ember.computed('currentTime', 'stamp', function() {
    return this.get('riff').get('stamp') < this.get('currentTime');
  }),
});
```

**Comment by raq929** [comment]
Is this resolved? If yes, please close, if no, can you let us know what the current problem is?

**Comment by payne-chris-r** [comment]
@ioncrash you can also do
```diff
- return this.get('riff').get('stamp') < this.get('currentTime');
+return this.get('riff.stamp') < this.get('currentTime');
```

**Comment by ioncrash** [comment]
Whoops. Sorry, yes. Thank you
