### ISSUE TITLE
Computed properties aren't updating

### ISSUE THREAD

**Issue by kibs86** [ga-wdi-boston/capstone-project#392]
I have a `my-analyses` route that grabs all of the analysis objects a user has created and displays them.  The route makes calls to two components, ```my-analyses-card``` and ```my-analyses-summary```.  The card component is called for each item and displays information about the request.  It also gives users the ability to edit/delete.

The summary component is just a drop down that displays a series of computed properties (total number of positive, negative and neutral analyses).

When a new analysis object is created, the user is routed to the My Analyses page and both the summary and card list populate with the new item.  When an analysis object is deleted however, the card disappears from the screen, but the summary isn't updated.

Is there a way to force a refresh of the data to the summary component so it will recompute the totals?

Part of ```my-analyses``` route that's calling ```my-analyses-summary``` component:
```
<div class="col s12">
      {{my-analyses-summary analyses=model}}
</div>
```

The ```my-analyses-summary``` component file:
```
import Ember from 'ember';

export default Ember.Component.extend({
  totalPositive: Ember.computed('analyses', function() {
    let analyses = this.get('analyses');
    let count = analyses.filterBy('doc_sentiment_type', 'positive').get('length');
    return count;
  }),

  totalNegative: Ember.computed('analyses', function() {
    let analyses = this.get('analyses');
    let count = analyses.filterBy('doc_sentiment_type', 'negative').get('length');
    return count;
  }),

  totalNeutral: Ember.computed('analyses', function() {
    let analyses = this.get('analyses');
    let count = analyses.filterBy('doc_sentiment_type', 'neutral').get('length');
    return count;
  }),
});
```

**Comment by gaand** [comment]
Please show the code handling the delete of an analysis.

**Comment by kibs86** [comment]
This is the ```my_analyses``` route.js file:

```
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('analysis');
  },

  activate: function() {
    Ember.$(".button-collapse").sideNav('hide');
    Ember.$('body').addClass('grey-background');
    Ember.$('#sidenav-bars').removeClass('white-text');
    Ember.$('#sidenav-bars').addClass('cyan-text');
  },

  actions: {
    editAnalysis (analysis) {
      this.transitionTo('my-analysis/edit', analysis);
    },
    deleteAnalysis (analysis) {
      analysis.destroyRecord();
    },
  },
});
```

The data from the model hook in this route file is passed down to two different components.  The ```my_analyses_card``` component is the one that's updating fine (the card for the deleted analysis disappears), but the computed properties in the ```my_analyses_summary``` component aren't updating.

**Comment by gaand** [comment]
Please post the entire route template.

**Comment by kibs86** [comment]
Here's the route template:

```
<div class="container">
  <h2 class="center-align cyan-text">My Analyses</h2>
  <br>
  <div class="row center-align">
    <div class="col s12">
      {{#link-to 'analysis'}}
        <button class="btn-floating btn btn-large waves-effect waves-light cyan white-text hoverable">
          <i class="material-icons">add</i>
        </button>
      {{/link-to}}
    </div>
    <br>
    <br>
    <br>
    <br>
    <div class="col s12">
      {{my-analyses-summary analyses=model}}
    </div>
  </div>
  <div class="row">
    {{#if model}}
      {{#each model as |analysis|}}
        {{my-analyses-card analysis=analysis
                          edit='editAnalysis'
                          delete='deleteAnalysis'}}
      {{/each}}
    {{else}}
      <h5> You haven't made any analysis requests yet. </h5>
    {{/if}}
  </div>
</div>
```

**Comment by kibs86** [comment]
I also realized that if I fully refresh the page (or navigate away and come back), the computed values do update.  I need a way for them to update automatically when an item is deleted though.

**Comment by kibs86** [comment]
I tried updating the model hook in my route file to add the computed properties there instead and pass them down, but they're not updating that way either.

New route file:
```
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    // return this.get('store').findAll('analysis');
    return new Ember.RSVP.hash({
      analyses: this.get('store').findAll('analysis'),
      newTotalPositive: this.store.findAll('analysis').then(function(allAnalyses) {
        return allAnalyses.filterBy('doc_sentiment_type', 'positive').get('length');
      }),
      newTotalNegative: this.store.findAll('analysis').then(function(allAnalyses) {
        return allAnalyses.filterBy('doc_sentiment_type', 'negative').get('length');
      }),
      newTotalNeutral: this.store.findAll('analysis').then(function(allAnalyses) {
        return allAnalyses.filterBy('doc_sentiment_type', 'neutral').get('length');
      }),
    });
  },

  activate: function() {
    Ember.$(".button-collapse").sideNav('hide');
    Ember.$('body').addClass('grey-background');
    Ember.$('#sidenav-bars').removeClass('white-text');
    Ember.$('#sidenav-bars').addClass('cyan-text');
  },

  actions: {
    editAnalysis (analysis) {
      this.transitionTo('my-analysis/edit', analysis);
    },
    deleteAnalysis (analysis) {
      analysis.destroyRecord();
    },
  },
});
```

**Comment by gaand** [comment]
I think your original approach is closer to correct.

I think this may help: https://guides.emberjs.com/v2.10.0/object-model/computed-properties-and-aggregate-data/

**Comment by kibs86** [comment]
It works!! Thank you so much!!  I was missing the .@each.<property> portion when I was defining the computed properties.  I'll add the solution and close this out.

**Comment by kibs86** [comment]
Solution:

Passed the full model down from my route to the component and defined computed properties at the component level.  New component file is below.  The important piece is ```analyses.@each.doc_sentiment_type``` which binds the computed property to the property defined after the ```@each```.  Without that portion, my computed properties weren't bound to anything and therefore weren't being updated.

```
import Ember from 'ember';

export default Ember.Component.extend({
  totalPositive: Ember.computed('analyses.@each.doc_sentiment_type', function() {
    let analyses = this.get('analyses');
    let count = analyses.filterBy('doc_sentiment_type', 'positive').get('length');
    return count;
  }),

  totalNegative: Ember.computed('analyses.@each.doc_sentiment_type', function() {
    let analyses = this.get('analyses');
    let count = analyses.filterBy('doc_sentiment_type', 'negative').get('length');
    return count;
  }),

  totalNeutral: Ember.computed('analyses.@each.doc_sentiment_type', function() {
    let analyses = this.get('analyses');
    let count = analyses.filterBy('doc_sentiment_type', 'neutral').get('length');
    return count;
  }),
});
```
