### ISSUE TITLE
Issue Setting up Current User

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#393]
I am currently trying to set up `current_user` on my backend. I believe  I have everything setup the way it should be but here is some code:

From the `bands` controller:
```rb
  def index
    @bands = Band.where(:user_id => current_user.id)

    render json: @bands
  end

  def create
    @band = current_user.bands.build(chore_params)

    if @band.save
      render json: @band, status: :created
    else
      render json: @band.errors, status: :unprocessible_entity
    end
  end
```

This is where i get an internal server error of 500 and it results in my front end just being a blank white page.
```sh
NoMethodError (undefined method `id' for nil:NilClass):
  app/controllers/bands_controller.rb:13:in `index'
```
I made sure that I set up the migration properly so that a user can have many bands and they are linked with foreign keys. I also haven't changed either of the `user` serializers. My code looks essentially the same as it does for project two. I rubber duckied with a classmate but it yielded no additional solutions.

**Comment by gaand** [comment]
What does your controller inherit from?

**Comment by akradin** [comment]
It was inheriting from `ApplicationController`, switching to `OpenReadController` resolved the issue

**Comment by gaand** [comment]
This might be more clear:

```diff
   def index
-    @bands = Band.where(:user_id => current_user.id)
+    @bands = current_user.bands

     render json: @bands
   end
```

**Comment by akradin** [comment]
^^I like that more
