### ISSUE TITLE
Having trouble creating a new point inside an artwalk

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/capstone-project#395]
I followed the `ember-resources` repo exactly but I'm getting an error when I attempt to create a new point after clicking on artwalk (essentially creating a new item in a list). I'm inside the right route and targeting the right artwalk but the POST request isn't going through. I modeled my `point/adapter.js` file after the `list/adapter.js` file but getting a 404 error when the `artwalkId`. I even tried hard-coding the artwalkId to no avail.

Here is the `point/adapter.js` file
``` js
import ApplicationAdapter from 'ga-wdi-boston.ember-auth/application/adapter';

export default ApplicationAdapter.extend({
  createRecord (store, type, record) {
    let api = this.get('host');
    let serialized = this.serialize(record, { includeId: true});
    let artwalkId = serialized.artwalk_id;
    let url = `${api}/artwalks/${artwalkId}/points`;
    let data = { point: serialized };

    return this.ajax(url, 'POST', { data });
  },
});
```

Here is the error
```
XHR finished loading: POST "http://localhost:4741/artwalks/null/points".
Ember Data Request POST http://localhost:4741/artwalks/null/points returned a 404
```

**Comment by payne-chris-r** [comment]
Does the route that makes this request have the proper `artwalk_id` passed down to it? If yes, you likely aren't passing it back up when the route gets made.

**Comment by kiraamaa** [comment]
The artwalk_id is actually returning null and the point is undefined. What would be causing this?

**Comment by kiraamaa** [comment]
When I click on an artwalk that is persisted in the back end that I know contains an array of points, the GET request for the points fail because the url is loading the name of the point rather than the id.

**Comment by kiraamaa** [comment]
Tabled this functionality until later; will re-open issue if time permits.
