### ISSUE TITLE
Sign-up and Sign-in responding with user object that is "incorrect", using Rails 5.0.1

### ISSUE THREAD

**Issue by joaufi** [ga-wdi-boston/capstone-project#397]
So my [backend](https://github.com/joaufi/dedr-back-end) is built using Rails 5.0.1 so that I can use their implementation of ActionCable. As such, I copied over all authentication needs from the rails-api-template which uses Rails 4. For the most part it works fine.

However, when trying to sign-in, my Rails 5 server responds with the following object:
`{"id":1,"username":"test@test.com","token":"BAhJIiUyM2YzYzEyYzA0MmJhMmMyZGZlMmU1NjE2Y2RkZDllYQY6BkVG--36689aa775f2747eb82a836b428a4dddafe54b6a"}`
(Note: I changed all instances of `email` on both my front and back-end to `username`, as I do not want a user to have to enter an email address for my chat app)

This, unfortunately, causes the Ember-auth (template) to not be able to sign in, because it is expecting an object formatted like the rails-api-template, which responds with this on sign-in:
`{"user":{"id":2,"email":"test1@test.com","token":"BAhJIiU5Njk5YWQ3OGZlMTM3MjU2OWYxYTMyMzYxNjg5YjNjNAY6BkVG--6ccef49a3d35dd3405a56fb5c516c5ccf5df69a9"}}`

The error that is thrown, as per the Ember Inspector:
`Error: Cannot read property 'id' of undefined` 
After getting the response from my Rails 5 server.

The following code is where the problem is located in the Ember-Auth template:
```js
// app/auth/service.js

  signIn (credentials) {
    return this.get('ajax').post('/sign-in', {
      data: {
        credentials: {
          username: credentials.username,
          password: credentials.password,
        },
      },
    })
    .then((result) => {
      this.get('credentials').set('id', result.user.id);   // LINE 31
      this.get('credentials').set('username', result.user.username); // LINE 32
      this.get('credentials').set('token', result.user.token);  // LINE 33
    });
  },

// more code . . . 
```

So lines 31 through 33 is where it is expecting a 'user' key from the response 'result' object. I have tried removing the `.user` portion so it becomes `result.id` which works, but I can already see some issues with ember templates and doing it that way down the line (for example, the 'Users' route/template will no longer list Users). 

I have looked over my code and the rails-api-template code, done curl requests on both, and the object being returned does not have a main key of "user" which causes issues. However, I cannot see any places where my code differs in terms of authentication from the rails-api-template code, so I do not know why one server is responding with a 'user' main key and one is responding without one.

How can I get my Rails 5 server to respond with an object that has a main 'user' key?

**Comment by gaand** [comment]
You can change the default behavior of the serializers to include a root key. This may be in config/initializers (I'm on my phone).

**Comment by joaufi** [comment]
That did it! I had to add the following file into config/initializers: `active_model_serializers.rb` with the following code inside of it:
```ruby
# frozen_string_literal: true
# Root keys on json resources
ActiveModelSerializers.config.adapter = :json
```

Thanks @gaand
