### ISSUE TITLE
Getting Error Messages in Terminal Since Installing Ember Package

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#398]
I wanted to add an ember datepicker so I ran `ember install ember-datepicker` it didn't work so I figured I would just move on but now whenever I try to use the CLI I get this error message:
```sh
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/AlexKradin/wdi/projects/roadie/front-end-roadie/node_modules/ember-cli/lib/models/addon.js:1005:27)
```

I did `npm uninstall ember-datepicker --save` but then I can't use the CLI at all as it prompts me to run `npm install`

**Comment by raq929** [comment]
This article might help: https://emberigniter.com/uninstall-remove-ember-add-on/
It might be related to #359? Take a look at that one.

Let me know if those don't help.

**Comment by akradin** [comment]
Issue persists, tried the steps in the first article (as noted above) and `brew upgrade` doesn't resolve the issue. Wasn't sure what other commands were kosher to run in that issue.

**Comment by raq929** [comment]
What happens if you *do* run npm install like it tells you to?

**Comment by akradin** [comment]
Same thing

**Comment by raq929** [comment]
Can you post the error that tells you to run `npm install`? I don't see that in the deprecation error you posted above.

**Comment by raq929** [comment]
Next try removing all your node modules and reinstalling: `rm -rf node_modules/` then `npm install`.

**Comment by akradin** [comment]
after running `brew upgrade` I can successfully uninstall the addon, but now I just get the same error as above.

tried uninstall and reinstalling node_modules and issue persists. I still have full functionality. It just shows the error message every time I type an `ember` related command. So I am just going to assume it is fine. I'd rather other people's issues get sorted it.

**Comment by raq929** [comment]
You are not the only person getting this error, but you are the only person who can't use `ember-cli`. hmmm...

**Comment by akradin** [comment]
Appears to be a deprecation issue because we are using the newest version of Ember which doesn't allow part of the ember auth template or the `ember-calendar` add-on, not sure which. Issue isn't resolved but isn't having an impact.
