### ISSUE TITLE
Problem using rails console to create a new event

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/capstone-project#4]
I generated a new model called Events with this command:
'rails g model event title:string descr:text location:string instructor:integer price:decimal start_time:datetime end_time:datetime'

Then I ran the migration.

When I bring up the ruby console and try to access the Event table by 'Event' to see the columns in the database, I get this error:

SyntaxError: /Users/laurisa/WDI/Proj_4/freshEX/app/models/event.rb:1: unterminated regexp meets end of file
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `load'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in`block in load_file'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:647:in `new_constants_in'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:456:in`load_file'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:354:in `require_or_load'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:494:in`load_missing_constant'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'
    from (irb):1
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in`start'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in`console'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in`<top (required)>'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in`block in require'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in`require'
    from /Users/laurisa/WDI/Proj_4/freshEX/bin/rails:9:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in`load'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in`load_dependency'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in`<main>'irb(main):002:0>

**Comment by GA-MEB** [comment]
What did you type in just before the error?

**Comment by LaurisaNeuwirth** [comment]
I went to rails c and typed 'Event'

**Comment by GA-MEB** [comment]
Is that the name of your class? Do you have an Event model?

**Comment by LaurisaNeuwirth** [comment]
I generated a new model called Events with this command:
'rails g model event title:string descr:text location:string instructor:integer price:decimal start_time:datetime end_time:datetime'

Then I ran the migration.

**Comment by LaurisaNeuwirth** [comment]
I thought I could go to rails c and type 'Event' and get back the fields for my Event table.

And I thought I could create a new event using rails c too.

**Comment by GA-MEB** [comment]
Can you paste the content of your Event model file?

You should be able to type in the name of your model's class without getting an error, though I don't know about seeing fields. You can also definitely instantiate a new Event.

**Comment by LaurisaNeuwirth** [comment]
right now my model still looks like:

/class Event < ActiveRecord::Base
end

**Comment by LaurisaNeuwirth** [comment]
All I did was generate the model and run the migration.

**Comment by GA-MEB** [comment]
Is your Postgres server running?

**Comment by LaurisaNeuwirth** [comment]
I am using sqlite3

**Comment by LaurisaNeuwirth** [comment]
bc to refresh my knowledge i followed a tutorial and they didnt use posgres until later in the process.

**Comment by LaurisaNeuwirth** [comment]
would it be more efficient to sit together and I can show you?

**Comment by GA-MEB** [comment]
OK. But it's running?

Just checking all the bases. Based on the error message, it seems like there may be a problem with your model file.

**Comment by LaurisaNeuwirth** [comment]
yes postgres is running.

**Comment by LaurisaNeuwirth** [comment]
but all I did was run the generate command and then run the migration.

**Comment by GA-MEB** [comment]
Is Rubocop running? Do you see any issues come up in your model file?

**Comment by LaurisaNeuwirth** [comment]
could the problem be that two fields I created were: start_time:datetime end_time:datetime

**Comment by LaurisaNeuwirth** [comment]
IDK robocop

**Comment by LaurisaNeuwirth** [comment]
-bash: robocop: command not found

**Comment by GA-MEB** [comment]
RUBOcop. It's a Ruby linter. You should have it set up in Sublime. If you don't, then we need to sit down and make sure you have it.

**Comment by LaurisaNeuwirth** [comment]
-bash: RUBOcop: command not found

**Comment by LaurisaNeuwirth** [comment]
does not look like i have that. I don't remember going over that in class.

**Comment by LaurisaNeuwirth** [comment]
Added rubocop and found a '/' at teh beginning of my model file. Deleted that and my rails c works with my Event model.
