### ISSUE TITLE
Having trouble getting my delete actions to work

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/capstone-project#400]
I reviewed and modeled my delete actions after the "Ember-resources" repo and also looked up the code that I wrote. When I click on the delete button for one of my photos, I get an Ember error message in the console saying there is no action handler.

![screen shot 2017-01-17 at 8 42 22 am](https://cloud.githubusercontent.com/assets/9563419/22022677/f1c743bc-dc90-11e6-9875-c45b455a8ed1.png)

**Comment by raq929** [comment]
Can you post the relevant code? I suspect that you're missing a link somewhere in the data-down / actions-up chain.

**Comment by Sphilippe7** [comment]
ok this is my component for your-photo

```
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    click() {
      console.log('i clicked');
    },
    deletePhoto() {
      console.log('it is gone!');
    },
  }
});
```

The template:

```
{{photo.url}}

<button class="btn btn-xs btn-danger" {{action 'deletePhoto'}}>
  Delete
</button>
```

Now here are the routes:

```
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return this.get('store').findAll('photo');
  },
  actions: {
    deletePhoto(photo) {
      photo.destroyRecord();
    },
  }
});
```

The template

```
All of your art!

{{#each model as |photo|}}
  {{your-photo photo=photo
              deletePhoto='deletePhoto'}}
{{/each}}
```

**Comment by payne-chris-r** [comment]
Hahah. So glad you posted this @raq929. @Sphilippe7 just walked in here asking me to comment and I told him the same thing.

**Comment by Sphilippe7** [comment]
I have the console log working, silly syntax error. But the button does not delete the image @raq929 
![screen shot 2017-01-17 at 10 07 59 am](https://cloud.githubusercontent.com/assets/9563419/22025965/5b1798c4-dc9d-11e6-9058-1c0974eb5d40.png)

**Comment by raq929** [comment]
It looks like you're not passing the action up to the route. 
You'll need something like this:
(from ember-resources)
```
    deleteItem (item) {
      return this.sendAction('deleteItem', item);
    },
```

**Comment by payne-chris-r** [comment]
Ok. So you got up to the next level.

**Comment by Sphilippe7** [comment]
Should that be within the delephoto component code I posted above? @raq929

**Comment by payne-chris-r** [comment]
You need to send the action up to the route level. Currently, you're only logging there.

**Comment by Sphilippe7** [comment]
so I added this to the your-photo component file:

```
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    click() {
      console.log('i clicked');
    },
    deletePhoto(photo) {
      console.log('it is gone!');
      return this.sendAction('deletePhoto', photo);
    },
  }
});
```

Now this is the error I'm getting. @raq929 @payne-chris-r 

![screen shot 2017-01-17 at 10 30 35 am](https://cloud.githubusercontent.com/assets/9563419/22026917/26085f58-dca0-11e6-9646-2f9170b0ec32.png)

**Comment by payne-chris-r** [comment]
So what line is blowing up?

**Comment by Sphilippe7** [comment]
In the console log I set up, it says photo is undefined. And when you look at the screenshot, it states that it can not read property of 'destroyRecord'  @payne-chris-r

**Comment by payne-chris-r** [comment]
That's exactly right. Are you passing up the photo that needs to be deleted? I don't think `photo` is defined here.

```js
deletePhoto(photo) {
      console.log('it is gone!');
      return this.sendAction('deletePhoto', photo);
    },
```

**Comment by Sphilippe7** [comment]
I reviewed the ember resources and tried to make changes but I'm still not getting what I want. I don't know what I'm doing wrong. I'm stuck. I know I have to find a way to define what the photo is so I tried writing let "photo = " and passing it to the photo folder that I have but that is not it. I get an error.  @payne-chris-r

**Comment by raq929** [comment]
What's the status of this?

**Comment by payne-chris-r** [comment]
Stanleys on the case. He'll update shortly.

**Comment by Sphilippe7** [comment]
After meeting with Chris just now, we discovered my problem was not adding the "this.get" to my send action.  The delete function works now!
