### ISSUE TITLE
AJAX request sending data as query parameter

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/capstone-project#402]
I have an AJAX request that has data I want to send - but instead of being passed as a data object as expected they are being sent as query parameters. How can I force the data to be sent as an object instead?

**Console**
```bash
search-form Object {search_term: "Starbucks"}
2017-01-17 09:20:43.247 route.js:10 searches/route Object {search_term: "Starbucks"}
2017-01-17 09:20:43.249 service.js:7 search service Object {search_term: "Starbucks"}
2017-01-17 09:20:43.274 jquery.js:9536 XHR finished loading: GET "http://localhost:4741/searches/?search%5Bsearch_term%5D=Starbucks".
```
**Search Service**
```js
  executeSearch (search) {
    console.log("search service", search);
    return this.get('ajax').request('/searches/', {
      data: {
        search: {
          search_term: search.search_term,
        },
      },
    });
  }
});
```

**Comment by raq929** [comment]
Are you using `ember-ajax`? Or just regular Ember?

**Comment by coffeeisamazing** [comment]
I haven't installed any special ajax plug-ins, if that answers the question.

**Comment by coffeeisamazing** [comment]
I'm injecting the ajax service that came with the auth template that extends ember-ajax. I have it working now by modifying my back-end to extract query parameters. I'll revisit this issue later if there's time but further investigation of ember-ajax is required.
