### ISSUE TITLE
Error with getting the id a newly created object

### ISSUE THREAD

**Issue by ielole** [ga-wdi-boston/capstone-project#404]
I'm getting this error when I create a new achievement. The backend database has an id for the object, so I'm not sure what's going on.

ember.debug.js:16905 Assertion Failed: Your achievement record was saved to the server, but the response does not have an id and no id has been set client side. Records must have ids. Please update the server response to provide an id in the response or generate the id on the client side either before saving the record or while normalizing the response.
Error
    at assert (http://localhost:7165/assets/vendor.js:16268:13)
    at Object.assert (http://localhost:7165/assets/vendor.js:27196:34)
    at assert (http://localhost:7165/assets/vendor.js:76280:37)
    at Class.didSaveRecord (http://localhost:7165/assets/vendor.js:86107:43)
    at http://localhost:7165/assets/vendor.js:86835:15
    at Backburner.run (http://localhost:7165/assets/vendor.js:11273:23)
    at Class._adapterRun (http://localhost:7165/assets/vendor.js:86719:31)
    at http://localhost:7165/assets/vendor.js:86825:13
    at tryCatch (http://localhost:7165/assets/vendor.js:68718:12)
    at invokeCallback (http://localhost:7165/assets/vendor.js:68730:13)
defaultDispatch @ ember.debug.js:16905
dispatchError @ ember.debug.js:16888
onerrorDefault @ ember.debug.js:30389
trigger @ ember.debug.js:57833
(anonymous) @ ember.debug.js:58717
invoke @ ember.debug.js:339
flush @ ember.debug.js:407
flush @ ember.debug.js:531
end @ ember.debug.js:601
run @ ember.debug.js:724
join @ ember.debug.js:746
run.join @ ember.debug.js:21556
hash.success @ rest.js:954
fire @ jquery.js:3305
fireWith @ jquery.js:3435
done @ jquery.js:9242
(anonymous) @ jquery.js:9484

Here's my code:

achievement adapter
```js

import ApplicationAdapter from 'learn-to-app/application/adapter';

export default ApplicationAdapter.extend({
  createRecord (store, type, record) {
    let api = this.get('host');
    let serialized = this.serialize(record, {includeId: true});
    let goalId = serialized.goal_id;
    let url = `${api}/goals/${goalId}/achievements`;
    let data = { achievement: serialized };

    return this.ajax(url, 'POST', { data });
  },

```

**Comment by raq929** [comment]
Why are you using the application adapter?
Can I see your create from the backend?

**Comment by ielole** [comment]
I'm using the adapter because I'm not following RESTful convention.

Routes.rb
```rb
Rails.application.routes.draw do
  resources :examples, except: [:new, :edit]
  get 'goals/:goal_id/milestones', to: 'milestones#index'
  get 'goals/:goal_id/milestones/:id', to: 'milestones#show'
  post 'goals/:goal_id/milestones', to: 'milestones#create'
  patch 'goals/:goal_id/milestones/:id', to: 'milestones#update'
  put 'goals/:goal_id/milestones/:id', to: 'milestones#update'
  delete 'goals/:goal_id/milestones/:id', to: 'milestones#destroy'
  get '/goals/:goal_id/achievements', to: 'achievements#index'
  get '/achievements/:id', to: 'achievements#show'
  post '/goals/:goal_id/achievements', to: 'achievements#create'
  patch '/goals/:goal_id/achievements/:id', to: 'achievements#update'
  put '/goals/:goal_id/achievements/:id', to: 'achievements#update'
  delete '/achievements/:id', to: 'achievements#destroy'
  get '/goals' => 'goals#index'
  get '/goals/:id' => 'goals#show'
  post '/goals' => 'goals#create'
  patch '/goals/:id', to: 'goals#update'
  put '/goals/:id', to: 'goals#update'
  delete '/goals/:id', to: 'goals#destroy'
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```

Achievement Controller
```rb
class AchievementsController < ApplicationController
  before_action :set_achievement, only: [:show, :update, :destroy]

  def index
    @achievements = Achievement.all

    render json: @achievements
  end

  def show
    render json: @achievement
  end

  def create
    @achievements = Achievement.new(achievement_params)

    if @achievements.save
      render json: @achievement, status: :created
    else
      render json: @achievement.errors, status: :unprocessable_entity
    end
  end

  def update
    @achievement = Achievement.find(params[:id])

    if @achievement.update(achievement_params)
      head :no_content
    else
      render json: @achievement.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @achievement.destroy

    head :no_content
  end

  def set_achievement
    @achievement = Achievement.find(params[:id])
  end

  def achievement_params
    params.require(:achievement).permit(:id, :log, :image, :goal_id, :user_id)
  end

  private :set_achievement, :achievement_params
end

```

Achievement Model
```rb
class Achievement < ActiveRecord::Base
  belongs_to :goal
end
```

Goal Model
```rb
class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :achievements, dependent: :destroy
  has_many :milestones, dependent: :destroy
end

```

Achievement Serializer
```rb
class AchievementSerializer < ActiveModel::Serializer
  attributes :id, :log, :image, :goal

  def goal
    object.goal.id
  end
end
```

Goal Serializer
```rb

class GoalSerializer < ActiveModel::Serializer
  attributes  :id, :start_date, :end_date, :user, :title, :achievements,
              :milestones

  def achievements
    object.achievements.pluck(:id)
  end

  def milestones
    object.milestones.pluck(:id)
  end
end
```

**Comment by ielole** [comment]
Also, I was going to open another issue about routes in my backend, because I'm running into problems with when to actually break RESTful convention with my achievements and when to stick to the rules.

**Comment by gaand** [comment]
What data do you send/get back?  Check the network tab for the post to achivements.

**Comment by ielole** [comment]
The problem was in the AchievementsController, the instance variables were pluralized instead of being singular in the create method. Removing the 's' from @achievements solved the problem. The front end wasn't getting a response because of the pluralized variables.

The code below works and doesn't result in an error. :

```rb

class AchievementsController < ApplicationController
  before_action :set_achievement, only: [:show, :update, :destroy]

  def index
    @achievements = Achievement.all

    render json: @achievements
  end

  def show
    render json: @achievement
  end

  def create
    @achievement = Achievement.new(achievement_params)

    if @achievement.save
      render json: @achievement, status: :created
    else
      render json: @achievement.errors, status: :unprocessable_entity
    end
  end

  def update
    @achievement = Achievement.find(params[:id])

    if @achievement.update(achievement_params)
      head :no_content
    else
      render json: @achievement.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @achievement.destroy

    head :no_content
  end

  def set_achievement
    @achievement = Achievement.find(params[:id])
  end

  def achievement_params
    params.require(:achievement).permit(:id, :log, :image, :goal_id, :user_id)
  end

  private :set_achievement, :achievement_params
end

```
