### ISSUE TITLE
Using Transitions to Pass Data

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/capstone-project#405]
I'm having some challenges on passing data to another route for it to display. I'm trying different combinations to reference in my template but not sure the appropriate sequence.

**search route**
```js
import Ember from 'ember';

export default Ember.Route.extend({
  search: Ember.inject.service(),
  flashMessages: Ember.inject.service(),

  actions: {
    executeSearch (search) {
      console.log("search/route", search);
      this.get('search').executeSearch(search)
      .then(function(result) {
        console.log(result);
      })
      .then(() => this.transitionTo('search-result'));
    },
  },
});
```

**search-result template**
```
{{#each search as |search|}}
  {{search-results search=search}}
{{/each}}
```

**Comment by raq929** [comment]
I need more information. What exactly are you trying to do, and what is happening as it is right now?
(executeSearch also looks like it's calling itself right now? Which might not be what you want.)

**Comment by coffeeisamazing** [comment]
I'm trying to transition the data from search route --> search-results route --> rendered in search-result component template. The routing is occurring as static content is being displayed - but the data is not.

It's calling the executeSearch method from the service.
```js
  executeSearch (search) {
    console.log("search service", search);
    return this.get('ajax').request('/searches/', {
      data: {
        search_term: search.search_term,
      },
    });
  }
```

**Comment by coffeeisamazing** [comment]
I think my challenge may be from the way I'm retrieving the data. This is the console log of the object that is transitioned.

http://imgur.com/a/rP08R

**Comment by raq929** [comment]
Yeah, ember doesn't like data that doesn't have a parent. You'll want something like:
`{ search_results: []}` for ember to be happy. Also, a search-result model? If I'm understanding what you're trying to do correctly.

**Comment by coffeeisamazing** [comment]
Where could I specify the parent? I think that would be a back-end change?

Instead of moving to search-result, would it be possible to create a route that does not go back to the back-end for more data but just uses the data passed?

**Comment by coffeeisamazing** [comment]
Could we meet to discuss this one? I'm wondering if the way my back-end is designed is making this quite a bit more complicated...

**Comment by raq929** [comment]
Yes, it's a backend change. I think if you want to have a route that doesn't go to the back end, what you want is actually a component, not a route. 
I can come by in 30 minutes (ish).

**Comment by coffeeisamazing** [comment]
Considering options - will update at end of the day.

**Comment by gaand** [comment]
Search usually needs query parameters which need  a controller in ember.  Unless I'm misunderstanding what you're trying to accomplish.

**Comment by coffeeisamazing** [comment]
I'm closing this for now as I've tabled search for now. Will revisit tomorrow or Friday subject to time. Thanks for helping look into this.
