### ISSUE TITLE
500 Server Error for favorites

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/capstone-project#407]
I was rendering a list of favorites and then added a title column to my favorites table and now I have a 500 server error and can't see them at all.

This is the error on the back end 
```
Started GET "/favorites" for ::1 at 2017-01-17 11:12:34 -0500
Processing by FavoritesController#index as HTML
  Favorite Load (0.6ms)  SELECT "favorites".* FROM "favorites"
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Json (28.2ms)
Completed 500 Internal Server Error in 51ms (ActiveRecord: 4.1ms)

NoMethodError (undefined method `id' for nil:NilClass):
  app/serializers/favorite_serializer.rb:11:in `user'
  app/controllers/favorites_controller.rb:10:in `index'
```

**Comment by payne-chris-r** [comment]
`NoMethodError (undefined method `id' for nil:NilClass):` typically comes from calling `current_user.id` or something along those lines. Are `favorites` supposed to be authenticated? Are you sending a token? Paste the curl request and the `favorites` controller so I can review.

**Comment by kiraamaa** [comment]
Just kidding. I had added
``` rb
def artwalk
    object.artwalk.id
  end

  def user
    object.user.id
  end
```
to my favorite_serializer and needed to comment it out. I can now create, edit, and delete favorites.
