### ISSUE TITLE
Trouble figuring out how to create and save an Ember object model. ( Ember Inverse Relationships )

### ISSUE THREAD

**Issue by joaufi** [ga-wdi-boston/capstone-project#408]
So I have an Ember model that looks like this:
```js
// app/conversation/model.js
import DS from 'ember-data';

export default DS.Model.extend({
  sender_id: DS.belongsTo('user'),
  recipient_id: DS.belongsTo('user'),
  messages: DS.hasMany('message'),
})
```

So essentially, a Conversation has two foreign-key references to User, which stores the ID of the Sender and the ID of the Recipient. Then, each conversation has many of Messages.

The way I have it setup at the moment is, to start a Conversation (chat session) with another user, the currently logged in user will click a "CHAT" button next to the name of the User they want to chat with in /users. I have successfully been able to get the ID of the current user onto the template of single-user by injecting the auth component into the single-user component that I created to display a single user (just like we did with item in the listr-list) and then using a Ember.computed.alias to get auth.credentials.id. That looks like this:
```js
// app/single-user/component.js
import Ember from 'ember';

export default Ember.Component.extend({
  auth: Ember.inject.service(),
  currentUserId: Ember.computed.alias('auth.credentials.id'),
  tagName: 'li',
  actions: {
    postConversation () {
      console.log('Click inside single-user.postConversation :: USER:', this.get('user').id);
      // console.log('Current User ID:', this.currentUserId);
      this.sendAction('postConversation', this.get('user').id);
    },
  },
});
```

```js
// app/single-user/template.js
<span>{{user.username}}</span>
<span>Current User Id: {{currentUserId}}</span>
<button class='btn btn-xs' {{action 'postConversation'}}>CHAT</button>
```

So, first question: How would I just get the current user ID into a value in the component itself? I commented out my most recent try in postConversation, which seems close but that returns an AliasedProperty object that has a ton of stuff in it, EXCEPT the current user ID, haha. I have also tried referencing `auth.credentials.id` directly which doesn't work either.

Now, once I can get that, I have the action `postConversation` successfully going up to the route. From there, I know I need to do something like 
```js
postConversation (data) {
      let newConversation = { sender_id: data.sender_id, recipient_id: data.recipient_id };
      let conversation = this.get('store').createRecord('conversation', newConversation);
      conversation.save();
}
```

I haven't tried this just yet (currently working on it) but the above feels wrong. I'm not convinced it'll work, because the object that we are creating a record off of doesn't have all of that Ember.object stuff (like `this.get('item')` had when we were creating items).

So how do I save a new model/object in Ember if I need to build that objects parameters myself?

I've also thought that perhaps I could simply do something like `this.get('user').current` (I know that's wrong, just as an example) and `this.get('user')`then pass both of those in instead of just the ID. 

I just don't know how much Ember... knows. Thanks!

**Comment by joaufi** [comment]
Update:

So I was able to get the `currentUserId` from within the component by doing the following:
`// console.log('Current User ID: ', this.get('currentUserId'));`

**Comment by joaufi** [comment]
Update:

Tried the following in the `app/users/route.js` to see what would happen if I tried to hard-code some values in and save a conversation record:
```js
// app/users/route.js
// . . . 

  actions: {
    postConversation (user) {
      console.log('Action up inside users.postConversation :: USER:', user);
      let conversationTemp = { sender_id: 5, recipient_id: 4 };
      let conversation = this.get('store').createRecord('conversation', conversationTemp);
      console.log('Test new conversation: ', conversation);
    },
  },

// . . .
```

All that did was create an empty Ember object e.g. key/values of `id: null, data: EmptyObject` And data has no needed key/value pairs under it, just having a `__proto__` key and a `constructor: undefined` key.

**Comment by joaufi** [comment]
Update:

Tried to do the following:
```js
// app/single-user/component.js

import Ember from 'ember';

export default Ember.Component.extend({
  store: Ember.inject.service(),
  auth: Ember.inject.service(),
  currentUserId: Ember.computed.alias('auth.credentials.id'),
  tagName: 'li',

  newConversation: {

  },

  actions: {
    createConversation () {
      let data = this.get('newConversation');
      data.sender_id = this.get('store').peekRecord('user', this.get('currentUserId'));
      data.recipient_id = this.get('user');

      this.sendAction('createConversation', this.get('newConversation'));
    },
  },
});
```

So I tried building a `newConversation` object and setting it's sender_id and recipient_id to the actual current user and clicked user objects. I then pass that action up to the users route, which looks like this:
```js
// app/users/route.js

import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('user');
  },
  actions: {
    createConversation (data) {
      console.log('Action up inside users.createConversation :: DATA:', data);
      let conversation = this.get('store').createRecord('conversation', data);
      console.log('Test new conversation: ', conversation);
    },
  },
})
```

Unfortunately, that still just creates an empty Ember.object as before. I feel like I might be closing in on the right answer but I'm not quite there yet.

Any thoughts?

**Comment by raq929** [comment]
OK. I'm a little confused about what you're trying to do here.
I seems like at some point you have a list of usernames, and you can also get the current user's id. So, can't you just pass that data down to the chat component?

**Comment by joaufi** [comment]
So, what I'm trying to do, is when the Current User clicks the "CHAT" button next to the name of a User in the Users list, I have an action `createConversation` (which used to be called postConversation, which I changed) that would then make a POST to the backend, creating an entry in the Conversations table which simply stores two foreign key references: one is `sender_id` which stores the Current User ID, and one is `recipient_id` which stores the User ID of the User that we want to send a message to.

Note: I am not doing `conversation.save()` yet because until I can get the proper Conversation object built there isn't really a point to try POSTing it.

Once this Conversation is successfully created, the plan is to `this.transitionTo` the conversation route with the conversation ID, thus opening a "chat".

I'm just having problems getting the Conversation object created correctly in Ember.

**Comment by raq929** [comment]
Got it. Generally, you would get the conversation ID back from the server after you post. Are you trying to do it differently? (Also, rails or express?)

**Comment by joaufi** [comment]
I am using Rails, but from my understanding, the Ember object even if not persisted in the backend using `.save()` should have the `recipient_id` and `sender_id` fields on the object when I inspect it in the console, correct? Or do I HAVE to `.save()` it to the backend and then it will update correctly? Because right now when I `createRecord` currently the Ember object that is created does not have any keys that I have specified it to have (and the id is null, but that makes sense now).

**Comment by raq929** [comment]
Yeah, it should have those fields. If they are null, then you need to work out how you are passing data to the component that's creating the chat, I think.

**Comment by joaufi** [comment]
It doesn't have those fields at all, though. They aren't even null; they just don't exist.

**Comment by joaufi** [comment]
As per the following doc from EmberJS, my very first try by making a `{ sender_id: 4, recipient_id: 5 }` object and then trying to create a conversation record with that should've worked... perhaps. I think something might be getting screwed up because my model has `sender_id: DS.belongsTo('user')` but that is how it is modeled on my backend.

I've been reading over the following doc to see if I can find anything that I'm missing, so far nothing:
[Creating, Updating, and Deleting Records - EmberJS 2.10](https://guides.emberjs.com/v2.10.0/models/creating-updating-and-deleting-records/)

**Comment by joaufi** [comment]
Okay, so I'm getting somewhere now. Still not 100% there, but it has to do with "inverse" relationships in Ember. I had neglected to define a `conversations` key on my User model, and I did so as the following:
```js
// app/user/model.js

import DS from 'ember-data';

export default DS.Model.extend({
  username: DS.attr('string'),
  conversations: DS.hasMany('conversation'),
});
```

Now, when I try to create a conversation record, the following error pops up:
`"Assertion Failed: You defined the 'conversations' relationship on ga-wdi-boston.ember-auth@model:user:, but multiple possible inverse relationships of type ga-wdi-boston.ember-auth@model:user: were found on ga-wdi-boston.ember-auth@model:conversation:. Look at http://emberjs.com/guides/models/defining-models/#toc_explicit-inverses for how to explicitly specify inverses"`

So I am now in the wild and dangerous world of Ember inverse relationships, which is confusing (but honestly, what isn't in Ember?). Some of the information I've found so far:
[Understanding Inverse Relationships](http://stackoverflow.com/questions/25693518/ember-understanding-inverse-relationships)
[Explicit Inverses and Other Relationships](http://emberjs.com/api/data/classes/DS.html#method_belongsTo)

I will keep diving.

**Comment by joaufi** [comment]
Okay. So, I got it sort of working. It now successfully posts to my backend. And Ember makes the Conversation model with an ID on the frontend.

This is fine. Close enough.

```js
// app/conversation/model.js

import DS from 'ember-data';

export default DS.Model.extend({
  sender: DS.belongsTo('user'),
  recipient: DS.belongsTo('user'),
  messages: DS.hasMany('message'),
});
```

```js
// app/user/model.js
import DS from 'ember-data';

export default DS.Model.extend({
  username: DS.attr('string'),
  sender: DS.hasMany('conversation', { inverse: 'senderId' } ),
  recipient: DS.hasMany('conversation', { inverse: 'recipientId' } ),
});
```
