### ISSUE TITLE
Passing data down freezes entire tab in chrome

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/capstone-project#409]
I am trying to implement an edit function where I use the component set for 'new' for both 'new' and 'edit'. The problem that I have run into is that when I attempt to pass data down to 'edit' to pass to 'new' the entire site is frozen. I pass the data from Route level to a component to a lower component to the 'new' route. I suspect the error may be occurring in this code:
```
model (params) {
    let id = this.get('store').findRecord('portfolio-image', params.portfolioimage_id);
    console.log(id);
    return id;
  },
```
I am very stuck and have been so for at least a half hour. Please help!

**Comment by payne-chris-r** [comment]
I think the issue here is @treep78 is trying to render links to routes that don't work themselves, which ember really doesn't like. I've asked him to go back and try to do one thing at a time.

**Comment by treep78** [comment]
SOLUTION: Was unintentionally attempting to generate a dynamic URL.

**Comment by treep78** [comment]
I had my new image component working briefly, now it has stopped working and I can't tell why.

**Comment by treep78** [comment]
I cannot get the component to even render

**Comment by treep78** [comment]
![routes](https://cloud.githubusercontent.com/assets/7408926/22037636/fa775f58-dcc5-11e6-8841-a036b5363d01.png)
![components](https://cloud.githubusercontent.com/assets/7408926/22037637/fa7e5bf0-dcc5-11e6-9bd2-57ccae97afe1.png)

**Comment by treep78** [comment]
NO SOLUTION: Nested components was not working. Ultimately I chose to refactor.
