### ISSUE TITLE
Getting different components to render that use different models

### ISSUE THREAD

**Issue by Naki21** [ga-wdi-boston/capstone-project#411]
So I can't figure out how to render different components that use different models on one template. I want to have it so when a user visits contest/1, not only does their contest detail render (this happens) but all submissions to that contest also render. contests have many submissions submissions have one contest. I had tried generating a submissions route and model inside my contests route and that didnt seem to work. I also tried generating a submissions model outside the route and using that. I think I have my backend set up the right way. 

Contests Model 
```js
export default DS.Model.extend({
  name: DS.attr('string'),
  prize: DS.attr('number'),
  end_date: DS.attr('string'),
  description: DS.attr('string'),
  submissions: DS.hasMany('submission', { async: true }),
  // user: DS.belongsTo('user')
});
```
Contest template
```js
{{client-contests/info contest=model editContest='editContest'}}
{{#each}}
{{client-contests/submission submission=model.submission}}
{{/each}}
```
I deleted my most recent submissions route. I am not sure if I even need a route purse (at least for listing them) because submissions cant exist outside the scope of a contest. I just want them rendered when in the contest/id page. I then plan on making a submission route which brings you to the individual submission (e.g. contest/1/submission/3). 

Let me know if you need some clarification. 

I want the components rendering underneath the line break 
![ember](https://cloud.githubusercontent.com/assets/22449692/22030808/d9fd5016-dcac-11e6-9cd7-f6066fc04761.png)

**Comment by gaand** [comment]
Typo ❓ 

```diff
 {{client-contests/info contest=model editContest='editContest'}}
 {{#each}}
-{{client-contests/submission submission=model.submission}}
+{{client-contests/submission submission=model.submissions}}
 {{/each}}
```

**Comment by raq929** [comment]
I don't think you can have an each block without telling it what to iterate through. 

Can you get these to display individually? I think that needs to be the first step.

**Comment by Naki21** [comment]
I can get it to work if I go to contest/1/submission/1 but I dont want to do that. I want it to render each inside the contest/1 route. I dont think it was the type :/

**Comment by Naki21** [comment]
typo***

**Comment by Naki21** [comment]
Any thoughts?

**Comment by payne-chris-r** [comment]
"Update ME!"
   - Issue #411

(something something Ember likes ids, and you need to use `pluck` in your API)

**Comment by Naki21** [comment]
Issue resolved. I needed to serialize out my associated ids so that that could be referenced on the front end. 

```js
  def submissions
    object.submissions.pluck(:id)
  end
  def user
    object.user.id
  end
``
