### ISSUE TITLE
Postgres issues

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/capstone-project#412]
I went to lunch and came back and my computer had restarted.  Awesome.  It upgraded something while I was away, I think.  (NOT SURE WHAT!) Now postgres won't connect.  I get the error:

psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

RUNNING brew services list gives me this:

Name       Status  User         Plist
mongodb    started ryanroderick /Users/ryanroderick/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
postgresql error   ryanroderick /Users/ryanroderick/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

RUNNING  brew services restart postgresql gives me this:

Stopping `postgresql`... (might take a while)
==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)

RUNNING brew services list again gives me this:

Name       Status  User         Plist
mongodb    started ryanroderick /Users/ryanroderick/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
postgresql error   ryanroderick /Users/ryanroderick/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

RUNNING which psql gives me this:

/usr/local/bin/psql  (which I believe is correct)

RUNNING tail /usr/local/var/log/postgres.log gives me this:

FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 367) running in data directory "/usr/local/var/postgres"?
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 367) running in data directory "/usr/local/var/postgres"?
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 367) running in data directory "/usr/local/var/postgres"?
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 367) running in data directory "/usr/local/var/postgres"?
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 367) running in data directory "/usr/local/var/postgres"?

I then uninstalled and then reinstalled PG, bundle installed, and I get same errors.  I assume this a path error of some kind.  Help!

**Comment by raq929** [comment]
Please try running the command in #403 and see if that fixes it. (Run `psql` afterwards.) Postgres likely didn't shut down properly.

**Comment by RpRoderick** [comment]
GREAT!  I didn't even see that issue when I searched issues.  It worked.  Solution was:
RUN    rm /usr/local/var/postgres/postmaster.pid
RUN   brew services restart postgresql
RUN   brew services list  (to check that it restarted correctly)


Thank you Rachel
