### ISSUE TITLE
[Ember] Adapter trouble, do I even need an adapter? 

### ISSUE THREAD

**Issue by kmg1434** [ga-wdi-boston/capstone-project#413]
I'm running into an issue generally passing data through ember and setting up routes. It seems when I fix one the other breaks:

I want a user to see a list of all of their `boards` at the URL `/boards`. This was working a moment ago but now `/boards` is entirely blank in browser, not sure why.

What seems to have broken it is when I went to create a `/board` route, which would load by a `link-to` from the users list of `boards`. Each element of the list would be a link. So, in reference to lister-list (ember-resources repo), I generated a board route, model, and template, and I figured I needed an adapter like this:

```
import ApplicationAdapter from 'ga-wdi-boston.ember-resources/application/adapter';

export default ApplicationAdapter.extend({
  createRecord (store, type, record) {
    let api = this.get('host');
    let serialized = this.serialize(record, { includeId: true });
    let boardId = serialized.board_id;
    let url = `${api}/boards/${boardId}`;
    let data = { board: serialized };

    return this.ajax(url, 'POST', { data });
  },
});
```

but I'm not sure I understand this code enough to use/modify it. Here's my other code for the board route:

model.js:
```
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  length: DS.attr('number'), // should be a decimal
  width: DS.attr('number'), // should be a decimal
  pedals: DS.hasMany('pedal'),
});
```

route.js:
```
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('board', params.board_id);
  },
});
```

template.hbs
```
<h4>This is a board!!!!</h4>
{{board.name}}
```

Somehow these files broke my `/boards` route and it displays an entirely blank page with no errors (my template is not loading). Also, on the home page, I have a button that links to `/boards` that displays the flashMessage `There was a problem. Please try again'. I'm confused because I don't think I modified anything in my `boards` route. Lastly, here's my router.js file:

```
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
});

Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('board', { path: 'boards/:board_id' });
  this.route('boards');
});

export default Router;
```

Not sure where to go from here or why `/board` would affect `/boards`.

**Comment by kmg1434** [comment]
Well I deleted my adapter file using `ember d route board` and now ALMOST everything works again.

I'm banging my head against the wall trying to get the syntax for the link:

```<a href="boards/${board.id}">{{board.name}}</a>```

When I click this link it brings me to `http://localhost:7165/boards/$%7Bboard.id%7D` instead of `http://localhost:7165/boards/1`. For some reason the string interpolation is not working, is this the whole reason I need an adapter?

**Comment by kmg1434** [comment]
Also, if I manually type in `http://localhost:7165/boards/1` it will bring me to the correct template, but I do not have access to my board model any longer... as in, I cannot do `{{board.name}}`, it renders nothing.

**Comment by raq929** [comment]
Why aren't you using `link-to`?

**Comment by kmg1434** [comment]
Because writing this:
```
      {{#link-to "boards/${board.id}"}}
        {{board.name}}
      {{/link-to}}
```

 gives me the same issue:

```
ember.debug.js:5715 Uncaught Error: Assertion Failed: You attempted to define a `{{link-to "boards/${board.id}"}}` but did not pass the parameters required for generating its dynamic segments. There is no route named boards/${board.id}
```

It is not interpolating the URL string.

**Comment by raq929** [comment]
Yeah, that's not the right way to do that. Check out how we got individual lists displayed in ember-resources.

**Comment by kmg1434** [comment]
I've been looking at that for 3 hours! It seems we used an adapter to re-route the `items` but my adapter caused my `/boards` route to stop loading the template.

**Comment by kmg1434** [comment]
The item template simply has `{{item.content}}` and it renders. When I type `{{board.name}}` it renders nothing.

**Comment by kmg1434** [comment]
I made a component called board-list, and a component inside that component called card. A card has the title of the list which links to the `/boards/:board_id` just fine.

boards template.hbs
```
<h2>Your Saved Boards:</h2>

{{#each model as |board|}}
  {{board-list/card board=board}}
{{/each}}
```

card template.hbs
```
<h4>
  {{#link-to 'board' board}}
    {{board.name}}
  {{/link-to}}
  <button class='btn btn-default btn-xs' {{action 'editBoard'}}>Edit</button>
<h4>
```
