### ISSUE TITLE
Posting a Photo

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/capstone-project#415]
I've been following the ember resources and when I reached the create part, I realized that my code might look different because I'm posting photos. I would like someone to guide me in the right direction. Originally I wanted users to post a url for their photos but I'm not sure if I have the value wrong or not using the proper syntax to define what it is because I get an error when I try to post a picture. I'm not sure if this is where @payne-chris-r said I would need to use PaperClip or not.

So far, This is my code for my component:

```
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {

    deletePhoto(photo) {
      console.log('photo is photo', photo);
      this.sendAction('deletePhoto', this.get('photo'));
    },
    createPhoto(photo) {
      console.log('photo is photo', photo);
      this.sendAction('createPhoto', this.get('photo'));
    }
  }
});
```
The template:
```
<img src='{{photo.url}}' height=150px width=200>

<button class="btn btn-xs btn-danger" {{action 'deletePhoto'}}>
  Delete
</button>


<form {{action 'createPhoto' on='submit'}}>
  {{input placeholder='New photo'
          value=newPhoto.content}}
  <button class='btn btn-xs btn-success' type='submit'>Post a Photo!</button>
</form>
```

Now here are the routes:

```
import Ember from 'ember';

export default Ember.Route.extend({

  model() {
    return this.get('store').findAll('photo');
  },

  actions: {
    deletePhoto(photo) {
      console.log('photo is photo', photo);
      photo.destroyRecord();
    },
    createPhoto(photo) {
      console.log('photo is photo', photo);
      this.sendAction('createPhoto', photo);
    }
  }
});
```

template:

```
All of your art!

{{#each model as |photo|}}
  {{your-photo photo=photo
               deletePhoto='deletePhoto'
               createPhoto='createPhoto'}}
{{/each}}
```

**Comment by raq929** [comment]
What's the error?

**Comment by Sphilippe7** [comment]
This is the error @raq929 

![screen shot 2017-01-17 at 3 00 08 pm](https://cloud.githubusercontent.com/assets/9563419/22037568/add5b05a-dcc5-11e6-9601-0948dbfeaa36.png)

**Comment by Sphilippe7** [comment]
I changed the code. I added newPhoto to be passed through the create photo method. I also added 'photo.save' to model it after ember resources. Now my error is a 500 internal error. @raq929 @payne-chris-r

**Comment by raq929** [comment]
Oh! I was just about to tell you to do that.
500 error sounds like something on the backend. Please post the request that ember is making, and what your backend server says when you make it.

**Comment by Sphilippe7** [comment]
it is a long error message. @raq929 

![screen shot 2017-01-17 at 4 14 14 pm](https://cloud.githubusercontent.com/assets/9563419/22040188/06e77908-dcd0-11e6-8eb5-f31ed3fd2251.png)


and the backend server says:

![screen shot 2017-01-17 at 4 15 27 pm](https://cloud.githubusercontent.com/assets/9563419/22040248/33034486-dcd0-11e6-9004-1bdb3cb19f76.png)

**Comment by raq929** [comment]
OK. This looks like a backend issue. You're making a request to the right place, but your controller can't handle the request. It's time to go back to curl and make sure you can create a photo using curl.  Take a look at `photo_url` in your create method, because that's what it's complaining about here.

**Comment by Sphilippe7** [comment]
So I tried a lot of different ways and got no result. Suja advised me to switch my code to a method I'd never seen before and it works. It is within the Photo Controller in the backend.  It is as follows @raq929 @payne-chris-r 

```
def create
    photo_params = params.require(:photo)
                         .permit(:name, :category, :url)
                         .merge(user_id: current_user.id)
    @photo = Photo.new(photo_params)
    if @photo.save
      render json: @photo, status: :created
    else
      render json: @photo.errors, status: :unprocessable_entity
    end
  end
```

**Comment by raq929** [comment]
Awesome! Please close the issue if it's resolved.
