### ISSUE TITLE
Issue with components and promises

### ISSUE THREAD

**Issue by kibs86** [ga-wdi-boston/capstone-project#416]
I'm setting up Facebook authentication and I'm trying to display certain text on a page (to start) based on whether a user has already authenticated or not.

Component.js
```
import Ember from 'ember';

export default Ember.Component.extend({
  fb: Ember.inject.service(),

  //fbLoginStatus: Ember.computed.alias('fb.getLoginStatus'),

  checkLoginStatus: Ember.computed('fb', function() {
    this.get('fb').getLoginStatus().then((response) => {
      console.log("response is ", response);
      if (response.status === 'connected') {
        console.log("response.status in if is ", response.status);
        return true;
      } else {
        console.log("response.status in else is ", response.status);
        return false;
      }
    }).catch((error) => {
      console.error(error);
    });
  })
});
```

template.js
```
{{#if checkLoginStatus}}
  you're logged in.
{{else}}
  you're not logged in
{{/if}}
```

I'm trying to get checkLoginStatus to be true or false and then use that to display to the user that either they're logged in or they aren't.  The console log statements I have in place prove to me that response.status equals connected as I would expect, but "you're not logged in" is being displayed to the user.  I'm not sure how to console.log the value of checkLoginStatus itself.

**Comment by raq929** [comment]
The way it's written right now, the function passed to `then` returns true or false, but `checkLoginStatus` isn't returning anything. Try returning the promise if that works.

**Comment by raq929** [comment]
Also use Ember's RSVP promise. :)

**Comment by raq929** [comment]
Does FB give you back a token when you log in? Because a better way to do this might be to do it more like auth is done. Save the token that you get when you log in, and then you can check that token wherever you need to.

**Comment by kibs86** [comment]
I tried adding another return so my component.js file looks like below now.  Whether I'm logged in or not, it just says I'm logged in though so I don't think the values of true or false are actually making it up to checkLoginStatus still.  I'll check out the token recommendation as well.

```
import Ember from 'ember';

export default Ember.Component.extend({
  fb: Ember.inject.service(),

  checkLoginStatus: Ember.computed('fb', function() {
    return this.get('fb').getLoginStatus().then((response) => {
      console.log("response is ", response);
      if (response.status === 'connected') {
        console.log("response.status in if is ", response.status);
        return true;
      } else {
        console.log("response.status in else is ", response.status);
        return false;
      }
    }).catch((error) => {
      console.error(error);
    });
  })
});
```

**Comment by raq929** [comment]
Is `getLoginStatus` an Ember promise? (RSVP)
Because that may be part of why it's not working. 

But I think storing the token is the better solution anyhow.

**Comment by kibs86** [comment]
So I'm trying something new by creating a service similar to the one created in auth.  Facebook provides a special button that performs the login/logout functionality for you so I'm using that and then trying to incorporate the below (from my new service file) to check to see if a user is logged in or not:

```
getLoginStatus: function() {
    return new Ember.RSVP.Promise(function(resolve, reject) {
      FB.getLoginStatus(function(response) {
        if (response.status === 'connected') {
          console.log("getLoginStatus response is ", response);
          resolve(response);
        } else {
          reject();
        }
      });
    })
    .then((response) => {
      this.get('fbCreds').set('id', response.authResponse.userID);
      this.get('fbCreds').set('token', response.authResponse.accessToken);
      console.log("fbCreds is ", this.get('fbCreds'));
    });
  },
```

The ID and token are being stored as expected if a user is logged in, but I need to find a way to reset my fbCreds object if the user isn't logged in.  Using the above code, that would have to be after the reject() somehow.  Is there something like a .then() that can be used to chain a reject()?

**Comment by raq929** [comment]
I talked with Kara, and she's going to use a `catch()` for that functionality.

**Comment by kibs86** [comment]
Using catch() seems to work.  Thank you for the help!
