### ISSUE TITLE
Assertion Failed error for Ember Leaflet

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/capstone-project#417]
I closed some tabs and now I can't render my maps. I'm getting this error in the console.
```
"Assertion Failed: Tried to use <ga-wdi-boston.ember-auth@component:tile-layer::ember595> outside the context of a parent component."
```

**Comment by raq929** [comment]
I suspect more happened than just closing tabs. Look at a git diff.

**Comment by kiraamaa** [comment]
Nothing has happened in my files since yesterday... Pls i am thrashing

**Comment by kiraamaa** [comment]
It's happening with anything leaflet related now... I copied the code from the ember leaflet tutorial over and I'm getting an identical error.

**Comment by raq929** [comment]
In taking to Kira, we discovered that the base layer for ember leaflet is not being recognised. 
Something changed, but we can't trace it because there is too much uncommitted code.

Maybe try uninstalling and reinstalling it?

**Comment by kiraamaa** [comment]
I tried reinstalling to no avail. Going to uninstall then reinstall

**Comment by kiraamaa** [comment]
OK, uninstalled then reinstalled and restarted my server and I'm still getting the same error message.

**Comment by raq929** [comment]
OK. And you tried taking absolutely everything out of there except for the map, right?

If yes, then I think we need to look at what ever is calling that template. 
Can you post the map template, and the template that links to it / calls it?

**Comment by kiraamaa** [comment]
Yes. The map can't render without the various layers seen below which are part of ember-leaflet. When I remove the layers and just leave the `leaflet-map` I can see the navbar and the debugger is gone, but no map exists.

map template
``` hbs
{{my-application signOut="signOut"}}
<div class="col-md-8 gallery">

  {{#leaflet-map lat=lat lng=lng zoom=zoom class="leaflet"}}

    {{#if nightMode}}
      {{tile-layer url="http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png"}}
    {{else}}
      {{tile-layer url="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"}}
    {{/if}}

    {{#each galleries as |g|}}
      {{#marker-layer lat=g.lat lng=g.lng draggable=true onDragend=(action "updateLocation" g)}}
        {{#popup-layer popupOpen=(readonly g.isOpen)}}
          <h3>{{g.name}}</h3>
          <img src={{g.image}} class="popup-image center-block"><br>
          {{g.description}}
        {{/popup-layer}}
      {{/marker-layer}}
    {{/each}}

    {{#polyline-layer locations=dangerZone color="#4B2231"}}
      {{#tooltip-layer sticky=true}}
        DANGER ZONE
      {{/tooltip-layer}}
    {{/polyline-layer}}

  {{/leaflet-map}}
  <p><label>{{input type="checkbox" checked=nightMode}} Night mode</label></p>
  </div>

<div class="col-md-4 gallery" id="gallery-list">
  <h3>Brooklyn Culture</h3>
  <ul>
    {{#each galleries as |g|}}
      <li>
        <strong>{{g.name}}</strong><br>
        {{!-- Lat: {{input value=r.lat}}
        Lng: {{input value=r.lng}}
        <label>{{input type="checkbox" checked=r.isOpen}} Popup open?</label> --}}
      </li>
    {{/each}}
  </ul>
</div>
```

**Comment by kiraamaa** [comment]
There's nothing calling the template ? There's a route and controller for each map, and this is the controller for this one:
``` js
import Ember from 'ember';

export default Ember.Controller.extend({

  lat: 40.669447,
  lng: -73.962884,
  zoom: 12,

  galleries: Ember.A([
    {
      name: 'Brooklyn Historical Society',
      image: 'http://brooklynhistory.org/photos/BHS_AlixPiorun-3_Thumbnail.jpg',
      description: 'The Brooklyn Historical Society, founded in 1863, is a museum, library, and educational center preserving and encouraging the study of Brooklyn\'s 400-year history.',
      lat: 40.694796,
      lng: -73.992408,
    },
    {
      name: 'Brooklyn Botanic Garden',
      image: 'http://www.nycgo.com/images/venues/1116/brooklynbotanicgarden_taggeryanceyiv_9877__x_large.jpg',
      description: 'Brooklyn Botanic Garden (BBG) is a botanical garden in the borough of Brooklyn in New York City. Founded in 1910, and located in the Prospect Park neighborhood, the 52-acre (21 ha) garden includes a number of specialty "gardens within the Garden", plant collections and the Steinhardt Conservatory.',
      lat: 40.669447,
      lng: -73.962884
    },
    {
      name: 'Brooklyn Museum',
      image: 'https://d1lfxha3ugu3d4.cloudfront.net/about/images/Photo_Shoots_1_Plaza_at_night_650x431.jpg',
      description: 'The Brooklyn Museum is an art museum located in the New York City borough of Brooklyn. At 560,000 square feet, the museum is New York City\'s third largest in physical size and holds an art collection with roughly 1.5 million works.',
      lat: 40.670966,
      lng: -73.940452
    },
  ]),

  dangerZone: Ember.computed('galleries.@each.lat', 'galleries.@each.lng', function() {
    return this.get('galleries').map(g => ({lat: g.lat, lng: g.lng}));
  }),

  actions: {
    updateLocation(g, e) {
      let location = e.target.getLatLng();
      Ember.setProperties(g, {
        lat: location.lat,
        lng: location.lng
      });
    }

  }

});
```

**Comment by kiraamaa** [comment]
The ember-leaflet addon is working elsewhere... I tested it by installing in ember-resources and can see a map rendering there

**Comment by raq929** [comment]
OK, so what's the difference between ember-resources and this? 

Is it displayed in an outlet of another route, or is the only way to get to it by changing the url in your browser?

**Comment by kiraamaa** [comment]
It's not displayed in an outlet, it's its own route so you have to change the url.

**Comment by kiraamaa** [comment]
I get a new error when I remove the tile-layer from template.hbs
```
Uncaught TypeError: Cannot read property 'getAttribute' of undefined
    at _default.buildOutletTree (<anonymous>:1371:49)
    at _default.build (<anonymous>:1341:33)
    at Class.viewTree (<anonymous>:4686:33)
    at <anonymous>:4658:27
    at fn (ember.debug.js:922)
    at invoke (ember.debug.js:339)
    at Queue.flush (ember.debug.js:407)
    at DeferredActionQueues.flush (ember.debug.js:531)
    at Backburner.end (ember.debug.js:601)
    at Backburner.run (ember.debug.js:724)
```

**Comment by raq929** [comment]
I verified that the exact code works on ember-resources, but not on Kira's app. We tried removing node_modules and bower_components and reinstalling. Kira is now going to start taking things out until it works again.

**Comment by raq929** [comment]
@gaand or @payne-chris-r if you have any ideas, let us know.

**Comment by raq929** [comment]
Please close!

**Comment by kiraamaa** [comment]
I'm working on building a new front end; haven't rebuilt yet!

**Comment by kiraamaa** [comment]
Rebuilding front end. For whatever reason ember-leaflet works in new repo (template taken from ember-auth) and CRUD functionality is working as well. I think I was just thrashing when I made the first repo and because I wasn't committing frequently I broke the code somewhere and wasn't able to trace it back. 

Moral of the story: Rachel is always right and you should commit your code frequently after every step even if it's not perfect.
