### ISSUE TITLE
ember deployment | can't change my app name

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/capstone-project#418]
I am trying to change the app name with `cmd + shift + f` as outlined in the [ember deployment guide](https://github.com/ga-wdi-boston/ember-deployment-guide) and I am also looking at this issue https://github.com/ga-wdi-boston/capstone-project/issues/330. My app stops working when I change the name to the one I want.
I receive these red `GET` requests in the console
```
 GET http://localhost:7165/assets/blogmon.css 
2017-01-17 14:59:22.094 new:23 GET http://localhost:7165/assets/blogmon.js 
2017-01-17 14:59:23.018 new:23 GET http://localhost:7165/assets/blogmon.js 
```

**Comment by raq929** [comment]
What is the name you're changing it to?

**Comment by jbuzzanco** [comment]
blogmon
*edit I also tried blogmon-ember, that didn't work either.

**Comment by jbuzzanco** [comment]
resolved. I am not sure why. May have been by restarting the server

**Comment by payne-chris-r** [comment]
This issue has been resolved. Probably had to do with not restarting the server, and Ember looking for files where they had just been instead of where they were currently.
