### ISSUE TITLE
Paperclip display error

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/capstone-project#42]
Lauren and I are running into similar issues trying to combine our handlebars with Peperclip and getting images to display.

We timeboxed it but error I am getting is GET 
GET https://s3.amazonaws.com/dogpic/pets/dog_pics/000/000/0/medium/ 403 (Forbidden)
403 (Forbidden)

Where handlerbars isn't filling in the values anymore
https://s3.amazonaws.com/dogpic/pets/dog_pics/000/000/0{{id}}/medium/{{dog_pic_file_name}}

**Comment by jcmeyer10** [comment]
This is the issue I get now, it is filling in the right values but still saying forbidden.
GET https://s3.amazonaws.com/dogpic/pets/dog_pics/000/000/018/medium/1450211952.png 403 (Forbidden)

Here is my Handlebars 

``` javascript
`<script id="dog-index-template" type="text/x-handlebars-template">
    <table>
        <thead>
            <th>Dog Pic</th>
            <th>Dog Name</th>
            <th>Last Rabies</th>
            <th>Last Heartworm</th>
        </thead>
        <tbody>
           {{#each pets}})
                <tr>
                     <td><img src="https://s3.amazonaws.com/dogpic/pets/dog_pics/000/000/0{{id}}/medium/{{dog_pic_file_name}}"</td>
                     <td>{{name}}</td>
                     <td>{{last_rabies}}</td>
                     <td>{{last_tick}}</td>
                     <td>{{last_heartworm}}</td>
                     <td><button id="change-dog" type="button" data-id={{id}}>Edit</button></td>
                     <td><button id="delete-dog" type="button" data-id={{id}}>Delete</button></td>
                </tr>
            {{/each}}
          </tbody>
                </tbody>
                </table>
</script>
```

**Comment by jrhorn424** [comment]
My first guess is that there is a problem with access control. Have you setup permissions for AWS in the way that was demoed in the multer lesson?

**Comment by jrhorn424** [comment]
@LaurenGrant

**Comment by jcmeyer10** [comment]
Mine seems to be working as it was trying to gather a file that was somehow unaccessible.  I will close the issue, but Lauren is still having trouble.  Her handlebars template is generating the right number for the id, but is getting nothing when we reference the {{item_image_file_name}} stored in the database.

GET https://s3.amazonaws.com/wdi-items/items/item_images/000/000/016/item_feature/

WHere it should be https://s3.amazonaws.com/wdi-items/items/item_images/000/000/0{{id}}/item_feature/{{item_image_file_name}}

Here is the handlebars.

`````` javascript
<script id="userItemsDashboard" type="text/x-handlebars-template">

  {{#each items}}
    <li class="card-dashboard">
      <article class="profile">
        <figure>
          <img src="https://s3.amazonaws.com/wdi-items/items/item_images/000/000/0{{id}}/item_feature/{{item_image_file_name}}">
          <figcaption id="item-{{_id}}">{{title}}</figcaption>
          <h3>{{zipcode}}</h3>
          <p>{{description}}</p>
        </figure>
        <ul class="tags">
          <li>
            <a href="#" data-itemId='{{id}}'>Edit</a>
          </li>
          <li>
            <a href="#" data-itemId='{{id}}'>Delete</a>
          </li>
          <li>
            <a href="#">Mark as Borrowed</a>
          </li>
        </ul>
      </article>
    </li>
  {{/each}}

</script>```
``````
