### ISSUE TITLE
Trying to associate resource with user in order to add ownership

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/capstone-project#420]
I need a user, title and body in order to create a post. I am getting 401 unauthorized I believe because I don't have a user in the form on submission. How do I add the current user to the form?
Here is what I tried:
```js
  <div>
    <label>Title:</label>
    {{input type='text' value=model.title}}
  </div>
  <div>
    <label type="hidden" name="user" value="{{user}}"></label>

    <label>Body:</label>
    {{textarea rows="5" value=model.body}}
  </div>
```

**Comment by raq929** [comment]
Check out ember-resources. How was user added to the form there?

**Comment by jbuzzanco** [comment]
I think as a component but I don't know.

**Comment by raq929** [comment]
OK. What are the differences between that route and template and yours?

**Comment by jbuzzanco** [comment]
They import the form as a component. When I do that i get cannot set title on an undefined object

**Comment by raq929** [comment]
That's a different issue. You have to define the object, like ember-resources does in the component file, I believe as newItem.

**Comment by jbuzzanco** [comment]
Ok, I'm not sure what you mean define the object as newItem. Should I open another issue? I am not sure if you mean its a different problem closer to this solution or it is a different issue altogether.

**Comment by raq929** [comment]
Please look at ember-resources and search for newItem. You need to do something similar for your create.

**Comment by raq929** [comment]
Look at the solution or 015/training branch.

**Comment by jbuzzanco** [comment]
Ok. I see this within the `app/listr-list/component` but I don't really konw how it includes the current user.
```
  newItem: {
    content: null,
    done: false,
  },
  actions: {
    toggleListDetail () {
      return this.toggleProperty('listDetailHidden');
    },
    toggleItemDone (item) {
      this.sendAction('toggleItemDone', item);
    },

    deleteItem (item) {
      this.sendAction('deleteItem', item);
    },
    createItem () {
      console.log('inside of createItem, newItem is', this.get('newItem'));
      let data = this.get('newItem');
      data.list = this.get('list');

      this.sendAction('createItem', this.get('newItem'));
    },

```

**Comment by jbuzzanco** [comment]
I tried doing this and defining it. Still the same error

**Comment by raq929** [comment]
And you're sure you're signed in when trying it, yes?

**Comment by jbuzzanco** [comment]
Could I get a one on one for this? I've been trying to figure it out for a while

**Comment by jbuzzanco** [comment]
Yes i am signed in

**Comment by jbuzzanco** [comment]
I am trying something a little different now  think It is something wrong with my model for post. I have the user part commented out and index loads fine so that must be whats wrong.

Here is my post model
```
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  body: DS.attr('string'),
  // user: DS.belongsTo('user'),
  // comments: DS.hasMany('comment')
});
```

**Comment by payne-chris-r** [comment]
Joel, let's meet in Tremont at 11

**Comment by raq929** [comment]
If this issue is resolved, please close it.

**Comment by jbuzzanco** [comment]
Right now trying to get the user_id to be part of the new post ember object in `post/new/route.js`
Tried with this however not working
```
       let newPost = this.get('store').createRecord('post', this.currentModel);
      // let currentUser = this.get('user_id');

      newPost.set('user_id', this.get('user_id'));

```
it still has a 401 error

**Comment by payne-chris-r** [comment]
Cool, can you paste the code?

**Comment by payne-chris-r** [comment]
And can you rename this to "Trying to associate resource with user in order to add ownership".

**Comment by jbuzzanco** [comment]
Resolved by having application adapter include auth. I'm not sure how it was changed, possibly by switching branches but now it is working.
Here is the application adapter.
```
import ENV from 'ga-wdi-boston.ember-template/config/environment';
import ActiveModelAdapter from 'active-model-adapter';

import Ember from 'ember';

export default ActiveModelAdapter.extend({
  host: ENV.apiHost,

  auth: Ember.inject.service(),

  headers: Ember.computed('auth.credentials.token', {
    get () {
      let headers = {};
      const token = this.get('auth.credentials.token');
      if (token) {
        headers.Authorization = `Token token=${token}`;
      }

      return headers;
    },
  }),
});

```
