### ISSUE TITLE
images rendering sometimes

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/capstone-project#425]
I have images stored in public/assets/images per documentation and closed issue 217.  They were rendering correctly, on next ember build they stopped displaying.  I did not change the file path or move the images  Once they are there I don't need to touch them so I never did.  From reading I see that ember may assign a 'fingerprint' to images and that may not display them correctly.  ??  My error is a GET 404 error, 

```
2017-01-17 17:20:08.995 lightbulb-4de1eb983c8d717801e566949746ce12.png:1 GET https://rproderick.github.io/assets/images/lightbulb-4de1eb983c8d717801e566949746ce12.png 
```

Any ideas?

**Comment by raq929** [comment]
If you look at sources in the browser, are the images there? Do they have the same file names?
Is this local or heroku?

**Comment by RpRoderick** [comment]
Ok, sorry.  Was on the train.  No, they do not show up in sources.  And they are not from heroku.  These files are stored within the ember repo under public/assets/images.  They are accessed via a standard tag:
```
<img src="/assets/images/screenpeace.jpg" alt="assets/images/screenpeace.jpg" style="width:100%" style="height:150px">
```

and they render fine on local host.  They WERE rendering fine on deployed site, on rebuild they no longer render.  Again I never touched this script or the filepath of the image.  I tried another ember build just in case something went wrong during the build of the production ENV but I get the same results.  I set the alt= to the same filepath without the preceding / (I had read that older ember versions had problems with the /) in case that was it, but....nada.  Ember build puts the random numbers on them (after the filename in above comment) which leads me to believe that it finds them, because it doesn't generate the random numbers on placeholder image titles that don't exist, meaning that it only builds on images that are actually there as files.  I'm reading that ember precompiles them before render, wondering if something is going wrong there.

**Comment by RpRoderick** [comment]
The network tab is referring to them as text/html, not image files.  They all have the proper file ext on them and the browser reads those extensions because it's on the file name in network.

**Comment by RpRoderick** [comment]
My site is deployed, if you want to look.

https://rproderick.github.io/designmonster

**Comment by raq929** [comment]
Yeah, it seems like they're not being uploaded at all. 
If you look at the gh-pages branch on github, are they there?

**Comment by RpRoderick** [comment]
Yes they are there and they display properly when I click on them in gh-pages on github

**Comment by RpRoderick** [comment]
Anyone have any thoughts?  Others are deployed with images showing correctly...not sure how to approach it because the only errors are 404 errors, but the images are stored correctly on gh-pages.

**Comment by raq929** [comment]
@gaand?

**Comment by RpRoderick** [comment]
Doing some research, it looks like you can turn off fingerprinting in broccoli as a workaround?  Not sure if this is a good solution or even the correct problem, but it does appear that ember build is adding a hash to the end of asset files, then looking for those hashed file names within the public folder, not seeing them, and calling a 404.  Maybe?

**Comment by raq929** [comment]
I don't think adding the hash is the problem, the problem seems to be that the hashed files just aren't being loaded.

**Comment by RpRoderick** [comment]
hmm.  Ok.  I'm going to keep researching.  Maybe the dist/ folder is being selective?  Should I move up one level to public/assets instead of public/assets/images?  I don't want to just start moving all kinds of stuff and hope it works, but if you think?

**Comment by raq929** [comment]
If they once worked where they are, I would keep them there. I know it feels like you didn't do anything to change how this is working, but something changed and now it doesn't work. So we have to figure out what that something is.

**Comment by gaand** [comment]
Your URLs are not properly constructed.  They do not include the path `/designmonster`.

**Comment by RpRoderick** [comment]
That would be found in environment===production?

**Comment by raq929** [comment]
Likely!

**Comment by RpRoderick** [comment]
I ask because...

```
  if (environment === 'production') {
  ENV.rootURL = '/designmonster';
  ENV.locationType = 'hash';
  ENV.apiHost = 'https://vast-taiga-61428.herokuapp.com';
}
```

That's what I have, I think.

**Comment by RpRoderick** [comment]
Compared everything that others had.  They seem to have the same setup.  What am I missing?

**Comment by raq929** [comment]
Right. But your photo srcs aren't using rootURL. That seems to be the issue.

**Comment by RpRoderick** [comment]
Shouldn't they be building with that though?  We shouldn't be setting the rootURL on all local images should we?

**Comment by raq929** [comment]
I would. Otherwise it's looking for them in the wrong place.

**Comment by gaand** [comment]
You should be able to set things appropriately using handlebars.

**Comment by RpRoderick** [comment]
I've set {{rootURL}} in handlebars before the img src filepath.  That doesn't work.  It doesn't even show up on the deployed site, I get the exact same 404 with the same path.  Do I need to import the env variables into the file (require it somehow)?   This is the only thing keeping me from being done and I can't seem to find a legitimate answer online.

**Comment by gaand** [comment]
Please paste the code.

**Comment by RpRoderick** [comment]
```
<img src="{{rootURL}}/assets/images/screenpeace.jpg" alt="assets/images/screenpeace.jpg" style="width:100%" style="height:150px">
```

**Comment by gaand** [comment]
What does that render (elements tab of the Chrome inspector)?

**Comment by RpRoderick** [comment]
that renders:

```
<script src="/designmonster/assets/vendor-842bb941a1d9a1d117c7dd64c27d57c2.js"></script>
```

**Comment by RpRoderick** [comment]
And some other stuff but I assume that's what you're looking for.

**Comment by gaand** [comment]
No, what does the `img` tag you posted render?

**Comment by RpRoderick** [comment]
Oh, it must have grabbed something else.  Here you go:

```
<img src="/assets/images/screenpeace-b848167343219924708a8ede9215ef34.jpg" alt="/assets/images/screenpeace-b848167343219924708a8ede9215ef34.jpg" style="height:150px">
```

**Comment by RpRoderick** [comment]
No rootURL

**Comment by gaand** [comment]
Have you tried a relative path?  No leading `/`?  

Or you could write you own helper  https://guides.emberjs.com/v2.10.0/templates/writing-helpers/ to provide the root url.

I'm not sure why some parts of the web think `{{rootURL}}` exists.

**Comment by RpRoderick** [comment]
Removing the / produces the same results.  Am I wrong in assuming that rootURL in ENV production should be setting this?  I'll look into the handlebars helper.

**Comment by RpRoderick** [comment]
I did read something on setting a prefix to the Ember fingerprint statement.  But I don't know anything about that, seems like I'd be tinkering with some internal wiring there...

**Comment by RpRoderick** [comment]
Ok I've got a workaround.

1:  Change rootURL to '/' for production.
2: Add a routerRootURL property to config/environment.js with a value of '/yourreponame/'
3: Change app/router.js to use rootURL: config.routerRootURL

Works!

**Comment by RpRoderick** [comment]
This, btw, makes things work for production, and breaks routes for development.  But I'm ok with changing a few lines on deploy if it works.
