### ISSUE TITLE
Using "def editable" - Rails API

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/capstone-project#426]
I have been trying to get handlebars to render "Create", "edit", and "delete" buttons only if the data is owned by the user. I've looked at some closed issues and googled the issue but haven't been successful in getting it to work: Issues Looked at-  #319 and #414. I'm NOT using Ember and am using the Rails API template. As of now, none of the buttons appear, even if a user is signed in and owns the data.

HANDLEBARS.JS:
```js
<div id="template-title">VIEW PROJECTS</div>
<div id="create-product">
  <button id="new-prod"class="btn btn-default test-button" data-toggle="modal" data-dismiss="modal" aria-hidden="true">Create New Product</button>
</div>
<hr>
{{#each products as |product|}}
<ul class=handlebars-body>
<h4 id="product-description">Product Description: {{product.description}}</h4>
<h5>Price: ${{product.price}}</h5>
<h5 class="modal-photos">Before-Photo Link: <img src="{{product.before_photo_url}}"></h5>
<h5 class="modal-photos">After-Photo Link: <img src="{{product.after_photo_url}}"></h5>
<hr>
{{#if product.editable}}
  <form class="updateProduct">
    <fieldset>
      <input type="hidden" name="product[id]" value="{{product.id}}" placeholder="Product ID">
      Edit Product Description: <input type="text" name="Description" value="{{product.description}}" placeholder="New Description">
      <hr>
      Edit Before Photo: <input type="text" name="Before Photo" value="{{product.before_photo_url}}" placeholder="Before Photo">
      <hr>
      Edit Price $: <input type="text" name="Price $" value="{{product.price}}" placeholder="Price">
      <hr>
      Edit After Photo: <input type="text" name="After Photo" value="{{product.after_photo_url}}" placeholder="After Photo">
      <hr>
      <input type="submit" value="Edit Project" id="update-submit">
    </fieldset>
  </form>
  <form class="deleteProduct" id="delete-form">
    <fieldset>
      <input type="hidden" name="product[id]" value="{{id}}">
      <input type="submit" name="submit" value="Delete" class="delete-product btn" id="delete-button">
    </fieldset>
  </form>
  {{/if}}
</ul>
<hr>
{{/each}}
```

PRODUCT SERIALIZER:
```js
class ProductSerializer < ActiveModel::Serializer
  attributes :id, :before_photo_url, :description, :price, :after_photo_url,
             :editable

  def editable
    scope == object.user
  end
end
```

I have tried moving the location of the ``` {{if product.editable}}``` statement to be right below the ```js {{#each products as |product|}}```in my handlebars template, but that did not work. I also tried moving it directly below  ```js  <form class="updateProduct">```. Moving its location doesn't seem to change anything, so I don't know if it's an issue with the back-end? 

Does anyone know why the buttons/forms aren't rendering for appropriate users?

**Comment by raq929** [comment]
When you make a curl request to your backend, do products have the editable property?

**Update** from talking to Julia: Yes.

**Comment by raq929** [comment]
Can you show `editable` in the template? Like, instead of `{{if product.editable}}` just `{{product.editable}}`?  That might give you more information about what's going on.

**Comment by jdaly04** [comment]
When I take out the if part, and just put ```js{{product.editable}}``` it doesn't seem to do anything in the template. The edit and delete buttons load on all products even when not signed in. 

Maybe I'm misunderstanding what you want me to try? I made the template look like: 
```js
<div id="template-title">VIEW PROJECTS</div>
<div id="create-product">
  <button id="new-prod"class="btn btn-default test-button" data-toggle="modal" data-dismiss="modal" aria-hidden="true">Create New Product</button>
</div>
<hr>
{{#each products as |product|}}
<ul class=handlebars-body>
<h4 id="product-description">Product Description: {{product.description}}</h4>
<h5>Price: ${{product.price}}</h5>
<h5 class="modal-photos">Before-Photo Link: <img src="{{product.before_photo_url}}"></h5>
<h5 class="modal-photos">After-Photo Link: <img src="{{product.after_photo_url}}"></h5>
<hr>
{{product.editable}}
  <form class="updateProduct">
    <fieldset>
      <input type="hidden" name="product[id]" value="{{product.id}}" placeholder="Product ID">
      Edit Product Description: <input type="text" name="Description" value="{{product.description}}" placeholder="New Description">
      <hr>
      Edit Before Photo: <input type="text" name="Before Photo" value="{{product.before_photo_url}}" placeholder="Before Photo">
      <hr>
      Edit Price $: <input type="text" name="Price $" value="{{product.price}}" placeholder="Price">
      <hr>
      Edit After Photo: <input type="text" name="After Photo" value="{{product.after_photo_url}}" placeholder="After Photo">
      <hr>
      <input type="submit" value="Edit Project" id="update-submit">
    </fieldset>
  </form>
  <form class="deleteProduct" id="delete-form">
    <fieldset>
      <input type="hidden" name="product[id]" value="{{id}}">
      <input type="submit" name="submit" value="Delete" class="delete-product btn" id="delete-button">
    </fieldset>
  </form>

</ul>
<hr>
{{/each}}
```

Did you mean something different?

**Comment by raq929** [comment]
Yeah, so product.editable isn't true or false...
OK, when you make the request to the server, what's the object you're getting back?

**Comment by jdaly04** [comment]
With my curl request?

**Comment by jdaly04** [comment]
this is what I get back from my GET curl request to view all products:
```js
{"products":[{"id":1,"before_photo_url":null,"description":"refurbished liquor cabinet - sanded, installed glass, repainted, new knobs","price":300,"after_photo_url":"http://imgur.com/HE35TDa","editable":true},{"id":2,"before_photo_url":null,"description":"numbered kids dresser with new knobs, sanded, painted, stencil work","price":300,"after_photo_url":"http://imgur.com/9go65le","editable":true},{"id":4,"before_photo_url":null,"description":"living room table sanded and painted","price":250,"after_photo_url":null,"editable":false},{"id":5,"before_photo_url":"http://imgur.com/77QFKdT","description":"living room table sanded and painted","price":250,"after_photo_url":null,"editable":false},{"id":6,"before_photo_url":"http://imgur.com/77QFKdT","description":"living room table sanded and painted","price":250,"after_photo_url":"http://imgur.com/HE35TDa","editable":false},{"id":7,"before_photo_url":"","description":"Bookshelf - rebuilt shelves, sanded, added chalkboard paint","price":0,"after_photo_url":null,"editable":false},{"id":8,"before_photo_url":"","description":"wooden chest - replaced rotting wood, rebuilt drawers, installed new knowbs","price":400,"after_photo_url":null,"editable":false}]}
```

**Comment by jdaly04** [comment]
I've redeployed my back-end, and "editable" is showing up as an attribute. However, it's showing up as "false" on every product. So, it's not toggling properly between true and false. Now, the edit/delete buttons do not show up at all even where they should. 

Any thoughts?

**Comment by raq929** [comment]
Maybe your user does not own what you think they own.

**Comment by raq929** [comment]
Test with curl, and make sure that your user can own objects.

**Comment by jdaly04** [comment]
Tested with curl and editable did switch to "true".

**Comment by raq929** [comment]
Cool. So, when you're creating from the front end, it's not getting the user id.

**Comment by raq929** [comment]
(I would put a validator on the back end at this point to make sure that things can't be created without user ids. But that's not this issue.)

**Comment by jdaly04** [comment]
I'm not sure why it wouldn't be getting the user id. I guess I can put a hidden form field to ensure that it's passed. Also, agreed -- back-end validator for create!

**Comment by jdaly04** [comment]
Actually, I'm not sure how to even put in a hidden form field, because the form exists in my index.html file, not in handlebars. Is there another way I can get the user id to be passed to the back-end on create?

**Comment by jdaly04** [comment]
Newest update is that I was able to successfully create a new product and have the "editable" attribute switch to "true'" in the product object. However, the edit/delete still do not show up even though the product IS editable.

**Comment by jdaly04** [comment]
This was how I was able to successfully create a product and have "editable" switch to true:

EVENTS.JS FILE:
```js
const onCreateProduct = function(event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  data.product.user_id = store.user.id;
  console.log("inside onCreateProduct data is", data);
  api.createProduct(data)
    .then(ui.createProductSuccess)
    // .then(function() {
    //   onViewProducts();
    // })
    .catch(ui.failure);
};
```

**Comment by raq929** [comment]
Awesome! Close the issue please.

**Comment by jdaly04** [comment]
It's not working though!

**Comment by jdaly04** [comment]
The handlebars template is not rendering properly which was the original issue and still is.

**Comment by raq929** [comment]
Wait, last I saw it, it was rendering correctly! I'm confused.

**Comment by jdaly04** [comment]
No, the editable attribute toggled to "true' but the edit button and delete button in the modal do NOT show up at all.

**Comment by jdaly04** [comment]
And that's the reason for using "editable" to begin with. I want those buttons to only show up for the logged in user.

**Comment by raq929** [comment]
So, what changed since I last saw it? Because it was working then...

**Comment by jdaly04** [comment]
It's never been working. The only thing that changed is that now "editable" is not always fault when I inspect the products object in the console.

The handlebars template has never properly rendered the "edit" and "delete" buttons based on "editable" being true or false.

**Comment by jdaly04** [comment]
**false not "fault" in previous comment

**Comment by gaand** [comment]
Please put something like

```hbs
<span>Editable:{{product.editable}}<span>
```

in your template and let us know what shows after "Editable".

Thanks.

**Comment by jdaly04** [comment]
I added that to the template and removed the "if" statement. After "Editable", is "false". All of them are showing false, even when I sign in, create a new product, and view them (which should result in "Editable": true).

**Comment by gaand** [comment]
Please post the create action from your API's product controller.

**Comment by jdaly04** [comment]
```js
  #  # POST /products
  def create
    print product_params
    @product = current_user.products.build(product_params)

    if @product.save
      render json: @product, status: :created
    else
      render json: @product.errors, status: :unprocessable_entity
    end
  end

```

**Comment by gaand** [comment]
Let me have a look.

**Comment by gaand** [comment]
@jdaly04 Please update with your solution and close.  Thanks.

**Comment by jdaly04** [comment]
The problem with "editable" was on the front-end, and stemmed from my API call for "viewAllProducts".  I was not passing the user token so there was not way for the back-end to know which user was making the request and thus wasn't able to determine whether "editable" was "true" or "false. Antony helped me fix my AJAX call, which now reads:
```js
const viewAllProducts = (data) => {
  const request = {
    url: config.apiOrigins.production + '/products',
    method: 'GET',
    data,
  };
  if (store.user) {
    request.headers ={
      Authorization: 'Token token=' + store.user.token,
    };
  }
  return $.ajax(request);
};
```

This way a non-authenticated user can still view all products without any issues, but an authenticated user will have edit/delete capabilities.
