### ISSUE TITLE
Accessing a model other than what is available in my route.

### ISSUE THREAD

**Issue by ielole** [ga-wdi-boston/capstone-project#427]
I created a achievement/new-achievement route and was using it to display a component which contained a form to create a new achievement. I am getting a 500 server error because no goal id is being added to the achievement. I realized that I don't have access to the goal model in achievements. I attempted to get the goal and its id by moving the route to goal (goal/new-achievement) and used a model hook which uses 'this.modelFor'.  I'm still getting null for goal. Is there a better way to gain access to the goal model or maybe just the id of the goal that the achievement will belong to? Also, I think that I'm missing something in the model hook with 'this.modelFor' because I've defined 'goal', but haven't used it, or so the linter says.

Error Message when I click save:

XHR finished loading: POST "http://localhost:4741/goals/null/achievements".
send @ jquery.js:9536
ajax @ jquery.js:9143
_ajaxRequest @ rest.js:976
(anonymous) @ rest.js:966
initializePromise @ ember.debug.js:58213
Promise @ ember.debug.js:58698
ajax @ rest.js:949
createRecord @ adapter.js:10
_commit @ store.js:2335
(anonymous) @ store.js:1603
flushPendingSave @ store.js:1586
invoke @ ember.debug.js:339
flush @ ember.debug.js:407
flush @ ember.debug.js:531
end @ ember.debug.js:601
run @ ember.debug.js:724
run @ ember.debug.js:21514
handler @ ember.debug.js:11103
(anonymous) @ ember.debug.js:41005
dispatch @ jquery.js:5201
elemData.handle @ jquery.js:5009
2017-01-17 19:56:00.377 ember.debug.js:16905 Ember Data Request POST http://localhost:4741/goals/null/achievements returned a 500

Here is the goal/new-achievement route.js:
```js
export default Ember.Route.extend({
  model () {
    let goal = this.modelFor('goal.new-achievement');

  },
  actions: {
    createAchievement (data) {
      console.log("This is inside goal route.js, newLog is: ", data);
      data.goal = this.get('goal');
      let achievement = this.get('store').createRecord('achievement', data);
      console.log("Inside 'goal route' route.js 'createAchievement' and this is achievement: ", achievement);
      achievement.save();
    },
  },
});
```

goal/new-achievement template.hbs:
```hbs

{{goal-display/achievement/edit goal=goal
                                createAchievement='createAchievement'}}

```

goal-display/achievement/edit component.js:
```js
import Ember from 'ember';

export default Ember.Component.extend({
  newLog: {
    log: null,
    image: null,
  },
  actions: {
    createAchievement () {
      console.log("This is newLog: ", this.get('newLog'));
      let data = this.get('newLog');
      console.log("This is data: ", data);
      data.goal = this.get('goal');
      console.log("This is data after data.goal:", data);
      this.sendAction('createAchievement', data);
      // console.log("This is this.sendAction('createAchievement', data);: ", this.sendAction('createAchievement', data));
      // console.log("This is data after sendAction: ", data);
    },
  },
});
```

goal-display/achievement/edit template.hbs:
```html
This is the goal you're working towards: <h2>{{goal.title}}</h2>
<form {{ action 'createAchievement' on='submit'}}>
  <label for="log-text">Today's Progress</label>
  {{input placeholder="Record today's achievement!"
          value=newLog.log}}
  <label for="log-image">Today's Picture</label>
  {{input placeholder="Add a picture to represent today's achievement."
          value=newLog.image}}
<button type="submit" class="btn btn-xs btn-info">Save</button>
</form>

```

**Comment by raq929** [comment]
It seems like you've got the goals title here, can't you also pass the id?

**Comment by ielole** [comment]
The issue was solved by changing the model hook to get a goal id via params and changing what was being passed down to the component. I kept the new-achievement route nested under the goal route, because it works. 

Here are the working files with the changes:


goal-display template.hbs
```hbs
<h3>Goal: {{goal.title}}</h3>
{{#link-to 'goal/update-goal' goal}}
  <button class="btn btn-xs btn-warning">Update Goal</button>
{{/link-to}}
<p>Start Date: {{goal.startDate}}</p>
<p>End Date: {{goal.endDate}}</p>

<ul>
  {{#each goal.achievements as |achievement|}}
      {{goal-display/achievements-main  achievement=achievement
                                        delete='deleteAchievement'}}
  {{/each}}
</ul>

{{#link-to 'goal/new-achievement'}}
  <button class="btn btn-xs btn-primary">Add A Daily Achievement</button>
{{/link-to}}

```


goal/new-achievement route.js
```js

import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('goal', params.goal_id);
  },
  actions: {
    createAchievement (data) {
      console.log("This is inside goal route.js, newLog is: ", data);
      // data.goal = this.get('goal');
      let achievement = this.get('store').createRecord('achievement', data);
      console.log("Inside 'goal route' route.js 'createAchievement' and this is achievement: ", achievement);
      achievement.save();
    },
  },
});

```

goal/new-achievement template.hbs
```hbs
{{goal-display/achievement/edit goal=model
                                createAchievement='createAchievement'}}


```
