### ISSUE TITLE
ActiveRecord Validations

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#428]
So in my application there are various fields that a user can leave blank. However, if they were to fill them out, I would like to validate them. For example, if a user adds a contact, they might not have that contacts phone number, which is fine, but lets say they get it at a later point, then I would want back-end validation. 

I read the ActiveRecord Validation documentation and did some googling but couldn't find out if this is possible.

**Comment by raq929** [comment]
What exactly are you trying to validate? Like, do you need to be sure it's a phone number, or something else?

**Comment by akradin** [comment]
Exactly, so doing something like 
```rb
  validates :phone_number, numericality: { only_integer: true }
  validates :phone_number, length: { is: 10 }
```

Is the kind of validation I would implement, but only if the user actually types something in

**Comment by raq929** [comment]
Well, rails will only validate once you send the data to it. And that seems like a good way to do backend validation. 

Are you wanting front-end validation as well?

**Comment by akradin** [comment]
Right, it only works if you send it data. So if I leave the phone number field blank, and add a new contact, It will result in an error.

**Comment by raq929** [comment]
Ok, so what do you want it to do?

**Comment by akradin** [comment]
So lets say I am in a band and I meet someone, say a booking agent. They give me their email address and their name and I input that into my app. If I leave phone number blank, that is okay because I didn't get their number. Later on, I get there number, I want to make sure I can't put 'boogity boo' into the phone number field.

long story  short:
1234567890 ===  okay
'' === okay
somestring === not okay
123456789012 === not okay (more than 10 digits)

**Comment by raq929** [comment]
Right. But isn't that what's happening now? You say you're getting an error when it's not a number.

**Comment by akradin** [comment]
Oh yeah, sorryyyyyy. Yeah so the validation is working (can't but in strings or more than 10 integers), *but* it gets mad when I leave it blank.

**Comment by raq929** [comment]
Can you post the file that has your validations?

**Comment by raq929** [comment]
I think if you set presence to false, it should allow it. http://guides.rubyonrails.org/active_record_validations.html#presence

**Comment by akradin** [comment]
Yeah, I tried this
```rb
class Contact < ActiveRecord::Base
  belongs_to :band
  validates :name, presence: true
  validates :phone_number, presence: false
  validates :phone_number, numericality: { only_integer: true }
  validates :phone_number, length: { is: 10 }
end
```

And if I leave `phone_number` blank I get a 500.
So I think if you have specific validation, aka anything that is **not** `presence` it assumes `presence: true`. That is my guess, but you would think that if you override that it would work.

**Comment by raq929** [comment]
All of the things need to be in the same object, I think. 
`validates :phone_number, { presence: false, numericality: { only_integeger: true }, length: { is: 10 }}`

Or some such. Look for an example of multiple validations in for the same field for the correct syntax.

**Comment by raq929** [comment]
Any luck?

**Comment by akradin** [comment]
So if you go to 5.5 in the active record validation guide there is some stuff about it, it is pretty confusing though so I am taking a break and deloying. I think I need to use `if` or `unless` so I am going to play around with that after I take a break

**Comment by akradin** [comment]
So I think I am going to save this for Friday and just set up standard validation for now. I don't fully understand the active record validation guide so I think I am going to close this issue

**Comment by raq929** [comment]
OK. Reopen on Friday and we can dig into it.

**Comment by gaand** [comment]
See `:allow_blank`

**Comment by akradin** [comment]
`:allow_blank` FTW HUZZAHHHHHH!!!!!!!!!!
