### ISSUE TITLE
[Ember] Creating new resource

### ISSUE THREAD

**Issue by kmg1434** [ga-wdi-boston/capstone-project#429]
I've got an issue creating a new `board`. For whatever reason the model method is annihilating the  edit template. Here is my app/boards/new/route.js:
```
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    console.log('this is ', this); // => ember object
    return this.get('store').createRecord('board', {}); // this lines throws flashMessage?!
  },

  actions: {
    save (board) {
      board.save();
    },

    cancelCreateBoard (board) {
      console.log('in boards/new route cancelCreateBoard');
      board.rollbackAttributes();
    },
  },
});
```

Here's the /new template that fails to load:
```
<form {{action 'save' on='submit'}}>
  {{input placeholder='Board Title'
          value=board.name}}
  <button type='submit' class='btn btn-xs'>Save</button>
  <button {{action 'cancelCreateBoard'}} class='btn btn-xs btn-danger'>Cancel</button>
</form>
```
Here's the button, it simply links to `/boards/new` but instead it throws a red flashMessage and does nothing else, no errors, no refresh, nothing.
```
{{#link-to 'boards/new'}}
  <button class="btn">Add a New Board</button>
{{/link-to}}
```

If I am to comment out the `return this.get('store').createRecord('board', {});` then obviously I get some `Cannot read property of undefined` errors since the store is not accessing anything, BUT then the boards/new template DOES load... so I'm confused here.

**Comment by raq929** [comment]
What happens if you move the create method into the save function? 
Like 
```javascript
 save (board) {
       newBoard = this.get('store').createRecord('board', board)
      newBoard.save();
    },
```

Also, this is a route, not a component, correct?

**Comment by kmg1434** [comment]
Like this? I think you need `let` in there:
```
    save (board) {
      let newBoard = this.get('store').createRecord('board', board);
      newBoard.save();
    },
```
Well if I do this INSTEAD of the model method (model method is now empty) then the button loads the correct template but as soon as I try and type any letters in the form field I get a `ember.debug.js:5715 Uncaught Error: Assertion Failed: Cannot call set with 'name' on an undefined object.` . Maybe this isn't what you were suggesting. If I keep the same `model()` method and add the `newBoard` definition to the `save(board)` function, then nothing changes.

And yes, this is a route, not a component.

**Comment by raq929** [comment]
LOL I've been writing Python for too long; I keep forgetting the `let`.
So, my memory of how we did this in resources is that we had a component for the form, and in the component we had `newItem` which was an object that the form fields could bind to. I think it might be worth doing it that way instead of trying to do all the work in the route. Otherwise, I think you'll need a controller to define the empty newBoard object.

**Comment by kmg1434** [comment]
Well I was following along `ember-resources` to a T, it was a route within a route, but that route generated a component `listr-list/edit` because we were borrowing that edit template for creating a new list as well. This was also giving me terrible errors.
<img width="163" alt="screen shot 2017-01-18 at 10 23 42 am" src="https://cloud.githubusercontent.com/assets/20648046/22069944/3bbcc258-dd68-11e6-95d4-21dbcb540429.png">

lists/new/template.hbs:
```
{{listr-list/edit list=model
                  save='createList'
                  cancel='cancelCreateList'}}
```

and `listr-list/edit` was the exact form that I am using!

```
<form {{action 'save' on='submit'}}>
  {{input placeholder='List Title'
          value=list.title}}
  <button type='submit' class='btn btn-xs'>Save</button>
  <button {{action 'cancel'}} class='btn btn-xs btn-danger'>Cancel</button>
</form>
```

So why wouldn't it work if I'm simply removing one layer of reference? 
I've now done what you've suggested and followed exactly along with `ember-resources`. Now `boards/new` calls to the `board-details/edit` component... but I still get the same exact error:
`ember.debug.js:5715 Uncaught Error: Assertion Failed: Cannot call set with 'name' on an undefined object.`

**Comment by raq929** [comment]
You need to define the object. What does your component file look like?

**Comment by kmg1434** [comment]
Doesn't `return this.get('store').createRecord('board', {});` define the empty object?

My component now looks like: 
```
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    save () {

      this.sendAction('save', this.get('board'));
    },

    cancel () {
      this.sendAction('cancel', this.get('board'));
    },
  },
});
```

But I liked it my way more which used a route within a route, but that didn't work either.

**Comment by raq929** [comment]
Yeah, you still don't have an object in the component for the form fields to bind to. I suggest `newBoard`.

**Comment by kmg1434** [comment]
I don't understand why this is diverging so far from `ember-resources` which does the same exact thing. There is no `newList` object in the component there, how does it even work? There is only:
```
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    save () {

      this.sendAction('save', this.get('board'));
    },

    cancel () {
      this.sendAction('cancel', this.get('board'));
    },
  },
});
```

And is `newBoard` an object or a method that creates an object? Is it in the actions... thing?

**Comment by raq929** [comment]
Related to #283

**Comment by raq929** [comment]
In ember-resources lists/list/route.js
```
createItem (data) {
      let item = this.get('store').createRecord('item', data);
      return item.save();
    },
```

I think you're missing the `let item` line?

**Comment by kmg1434** [comment]
so uh I added `save='save'` in my `/boards/new' template and it fixed everything.
