### ISSUE TITLE
Creating new submissions to contests

### ISSUE THREAD

**Issue by Naki21** [ga-wdi-boston/capstone-project#430]
So I'm having trouble rendering my route using a {{linkto}} or just directly navigating to the url. I'm trying to add submission to contests. My route is currently contest/ID/submission/new. When I navigate here I get a blank page. I'm not sure what is wrong with my model. I tried structuring it like my new contests but because It is very nested I think it is acting different.

Contest Route
```js 
import Ember from 'ember';

export default Ember.Route.extend({
  model(params) {
  return this.get('store').findRecord('contest', params.contest_id);
},
actions: {
  editContest(){
    console.log('In Contest Route');
    this.transitionTo('contest.edit');
  }
}
});
```
Contest Model
```js 
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  prize: DS.attr('number'),
  end_date: DS.attr('string'),
  description: DS.attr('string'),
  submissions: DS.hasMany('submission', {async: true}),
  user: DS.belongsTo('user')
});
```
Submission Route
```js 
import Ember from 'ember';

export default Ember.Route.extend({
    model(params){
    return this.get('store').findRecord('submission', params.submission_id);
  }
});
```
Submission/new route
```js 
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return this.get('store').createRecord('submission');
  },
});
```
Helps please !

**Comment by payne-chris-r** [comment]
Dude. Those routes should be `/contest**s**/:contest_id/submission**s**/new`!

**Comment by Naki21** [comment]
Yeah but we talked about that yesterday and I set them up different... :/

**Comment by Naki21** [comment]
womp womp..

**Comment by payne-chris-r** [comment]
Yup

**Comment by payne-chris-r** [comment]
I'll come take a look in a minute.

**Comment by Naki21** [comment]
WOO HOO!

**Comment by Naki21** [comment]
Issue solved. Bad model hook was preventing page from loading route properly. 

```js
export default Ember.Route.extend({
    model(params){
    return this.get('store').findRecord('submission', params.submission_id);
  }
});
```
I deleted this and the route rendered properly.
