### ISSUE TITLE
Design of multiple resources from one route

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/capstone-project#431]
I have two routes: shops and yelp_search_results. On the edit screen of a shop, I'd like to have data displayed based on the shop#show method and the yelp_search_results#index method. I'm not clear on the approach that can be used to get data from multiple resources in one component/route. Any general recommendations on how to look into this? Started looking at controllers but I'm worried I'm falling into over-engineering.

**Comment by raq929** [comment]
What about putting things in components and just calling the components from the same template?
Alternately, you can have more than one outlet if they are named, so that might be worth looking into.

**Comment by coffeeisamazing** [comment]
![unknown](https://cloud.githubusercontent.com/assets/14969865/22070058/a95ffe74-dd68-11e6-9834-e04a09a95cce.jpeg)

**Comment by coffeeisamazing** [comment]
Attached my current thinking above. Do you have a few minutes to talk through? Not sure I quite followed your last comment.

**Comment by raq929** [comment]
Can you update with what we talked about?

**Comment by coffeeisamazing** [comment]
We discussed keeping everything in the same route but setting up a new Yelp-Results sub-route and corresponding components.
