### ISSUE TITLE
Creating model from local storage

### ISSUE THREAD

**Issue by kibs86** [ga-wdi-boston/capstone-project#432]
Is there a way to create a model hook that pulls data from local storage instead of from Ember data?  Currently, a user can authenticate with Facebook and pull in their timeline posts and I have those posts being saved using ember-local-storage.  I'm trying to figure out how I can then display all of that data so a user can edit it (or delete it) before actually triggering the create of Ember objects.  I was trying to load the array of posts into my model to pass it down to a component, but it doesn't seem to be working.

route.js
```
import Ember from 'ember';
import { storageFor } from 'ember-local-storage';

export default Ember.Route.extend({
  fbPosts: storageFor('facebook'),

  facebook: Ember.inject.service(),

  model () {
    return this.get('fbPosts').get('posts');
  },

  activate: function() {
    Ember.$(".button-collapse").sideNav('hide');
    Ember.$('body').addClass('grey-background');
    Ember.$('#sidenav-bars').removeClass('white-text');
    Ember.$('#sidenav-bars').addClass('cyan-text');
  },

  actions: {
    fbLogin: function() {
      let self = this;
      this.get('facebook').getLoginStatus().then(function() {
        self.get('facebook').getAccessToken().then(function(accessToken) {
          console.log("successful login and accessToken is ", accessToken);
          //self.sendAction('success', accessToken);
          }, function(reason) {
            //self.sendAction('failure', reason);
            console.log("login failure and reason is ", reason);
        });
      });
    },
    fbLogout: function() {
      this.get('facebook').fbSignout();
      //console.log("fbLogout triggered in route");
    },
    fbTimeline: function() {
      this.get('facebook').getTimeline().then((response) => {
        let postsArray = [];
        for (let i = 0; i < response.data.length; i++) {
          let postObj = {};
          postObj.title = "Facebook Post " + i;
          postObj.text = response.data[i].message;
          postsArray.push(postObj);
          this.get('fbPosts').set('posts', postsArray);
        }

        console.log("fbTimeline response is ", response);
        console.log("postsArray is ", postsArray);
        console.log("fbPosts is ", this.get('fbPosts').get('posts'));
      });
    },
  },
});
```

The console.log statements above prove that ```this.get('fbPosts').get('posts')` gives me an array of post objects (each with a title and text), but it's not passing through to the component:

template.hbs for route
```
<h3 class="cyan-text center-align">New Facebook Analysis</h3>
<br>
<div class="row center-align">
  <fb:login-button scope="public_profile,email" autologoutlink="true" size="large">
    Log In with Facebook
  </fb:login-button>
</div>
<div class="container">
  {{fb-timeline fbLogin='fbLogin'
                fbLogout='fbLogout'
                fbTimeline='fbTimeline'}}

  {{#each model as |post|}}
    {{fb-timeline-posts post=post}}
  {{/each}}
</div>
```

component template.hbs
```
Hello
{{post.title}}
{{post.text}}
```

**Comment by raq929** [comment]
I think you need to create an adapter to tell Ember where to look for the data. (My memory may be wrong here, but it's worth looking into.)

Also useful - in the chrome inspector, if you look at the `Application` tab, you can see what's in localStorage.

**Comment by kibs86** [comment]
I'm trying a different approach of creating a for loop that creates a new analysis object for each timeline post that's pulled in.  It seems to work fine, but my transition kicks in before all of the objects have been created so the page needs to be refreshed.  Is there a way to promisify a for loop so the transition won't happen until the loop completes?

**Comment by raq929** [comment]
I don't see why not. Just stick it inside a new promise that has a resolve() after the for loop completes.

**Comment by kibs86** [comment]
How do I know if the for loop has completed though?

**Comment by raq929** [comment]
Save asynchronous, so results were not all being returned in time, even with the promise. Kara is going to create a button for the transition for now.

**Comment by raq929** [comment]
Checkout the documentation from #437.

**Comment by kibs86** [comment]
I checked out the issue above and I think that does work for me too, but because some of my formatting in my component is based on computed properties, I don't think that portion is updating quite fast enough so when I transition, my objects are all there, but they aren't formatted quite yet.  The button works though so I'll stick with that as a work around for now.  Thank you for your help!
