### ISSUE TITLE
trying to create a simple post with contact form

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/capstone-project#435]
I have a contact folder with a model, a route and template.  

Model:
```
import DS from 'ember-data';

export default DS.Model.extend({
  email: DS.attr('string'),
  comment: DS.attr('string')
});
```

Route:

```
import Ember from 'ember';

export default Ember.Route.extend({
model () {
    return this.get('store').createRecord('contact', {});
  },
  actions: {
    createContact (contact) {
console.log("contact is", contact);
      contact.save();
      this.transitionTo('contact');
    },
  },
});
```

Template:

```
Is anything here?
<h1>Contact</h1>
<form {{action 'createContact' on='submit'}}>
  <div class="form-group">
    <label for="inputEmail">Email address</label>
    {{input type="email" class="form-control" id="inputEmail"
      placeholder="Email" value=contact.email}}
  </div>
  <div class="form-group">
    <label for="inputComments">Comments</label>
    {{textarea cols="80" rows="6" class="form-control" id="inputComments"
      placeholder="Comments" value=contact.comment}}
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
```

I seem to be missing something.  It's just a form with two fields.  When I enter a character into the form fields, my console throws an error.

'uncaught Ember Error - assertation error - cannot call set with email on undefined object'.  

It does the same for the comment field - I am reading the error as 'contact' is undefined, but I am following createRecord in my route and just using the model hook to create 'contact' as an empty object.  I only need to post the data to my backend, I do not need to display it on my front end in any way.  Is it because I'm entering in text to the form fields (value=contact.email) before the object is created?  The 'submit' button is supposed to create, so....not getting it.

**Comment by RpRoderick** [comment]
Well, I can get by that error by taking the 'contact.'  off of the form values.  But do I want to do that?  I somehow need to define the object contact.  BUT, I am defining it on create.  Is this a conceptual data-down issue?  The data doesn't exist until I click submit, and neither does the object.  I thought that I was a: creating the object, and then b: saving data to it.  I'm not sure which step I should take next to try and solve this, other than the general 'try to define the object' step.

**Comment by raq929** [comment]
I think the easiest way to do this is to move your form into a component, which can have an empty contact object to bind the form values to. Related to #429

**Comment by raq929** [comment]
Also #283

**Comment by RpRoderick** [comment]
That's what I was thinking...it seems strange that I HAVE to have a component for something like this.  Because Ember I guess.  But, it seems like extra steps to me.  So anytime you are doing an 'action' it needs to be from a component?  Or it's just convention?  A form that renders nothing and just creates a post feels 'un-component' like to me, or am I wrong?  But I'll do it that way.  Should I close issue or wait until it works?

**Comment by raq929** [comment]
I'd say close it, and then re-open if you run into issues.
