### ISSUE TITLE
.then is firing before expected

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/capstone-project#437]
This is an action in my shop controller. The shop.ID prints as null. It appears that the .then is not waiting for the shop.save() to completely finish. How can I instruct .then to wait for shop.save() to finish before running?

```js
    createShop(shop) {
      shop.save()
        .then(console.log("SHOP ID",shop.id))
        .then(this.transitionTo('application'));
    },
```
```bash
SHOP ID null
```

**Comment by raq929** [comment]
So, this is similar to Kara's issue: #432.

The deal is that save **is** completing. It's done when it fires the POST request. The problem is that it's not waiting for that POST request to come back before going to the `then`. 

I'm going to look into this briefly and get back to you.

**Comment by raq929** [comment]
OK, I lied. The POST **is** completing: https://guides.emberjs.com/v2.9.0/models/creating-updating-and-deleting-records/#toc_promises

But you are using the original shop, not the shop returned from the POST request (which has the id).

**Comment by raq929** [comment]
Your `then` function needs to use the data it gets from the server.

**Comment by coffeeisamazing** [comment]
Ah, that did the trick. This is working now as expected. Thanks Rachel!

```js
    createShop(shop) {
      shop.save()
        .then(function(result){
          console.log("result", result.id);
        })
        .then(this.transitionTo('application'));
    },
```
