### ISSUE TITLE
Need help accessing ember object values from model hook

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/capstone-project#438]
Since I'm in a non-relational database I'm trying to use the model hook of a route to filter images out of a database I have an image with a ```category``` attribute and I want to get all of the images from a separate collection with the same value in their ```category``` attribute. The code I currently have is:
```
export default Ember.Route.extend({
  model(params) {
    let imgIn = this.get('store').find('portfolio-image', params.image_id);
    let imgOut = this.get('store').findRecord('category', {category: imgIn.category});
    return imgOut
  },
```
the problem occurs where I attempt to access ```imgIn.category``` which as far as I can tell is not how you would access that attribute from inside the route.js file. I know the info I want is logged as ```class.content.data.category``` but that doesn't seem to work either, nor does ```imgIn.get('category')```. What do I do to correctly access the data I'm after?

**Comment by raq929** [comment]
I would findAll the images and then filter that list using array methods. Not sure if that will work with what Ember gives you, but it's worth a try.

**Comment by treep78** [comment]
The issue is not filtering, the issue is getting the ```category``` attribute value from imgIn.

**Comment by treep78** [comment]
Never mind, apparently ```SOLUTION: imgIn.get('category')``` does work, I just did it slightly wrong that one time.
