### ISSUE TITLE
using mailer in rails

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/capstone-project#439]
I have a form on the front end which creates a 'contact' and sends the info to a table in my rails backend.  I am then using a rails mailer to send out an email to myself (through a third party mail system called sendgrid).  The email contains the information that was submitted within the ember form on the front end.  Rails mailer parses it, renders it into an email, and sends me the email saying
'you've got a contact from your website' (or whatever).  I have the ember form working.  I have the table on the backend set up.  And I have the mailer set up.  I have to configure the mailer within the environment.rb file on the rails app, however as it is not good practice to store username and password in files that will be committed, I want to store them in an env file and call them to the environment file, similar to what we did with the secret key base and token.  I want to make sure that I do this correctly.  Here's what I'm thinking, based on the way the rails template is set up.  Please correct me if I'm wrong:

1:  Declare user_name and password (from sendgrid email service) in my .env file.

2:  Declare those same user_name and password in my secrets file as 
user_name: <%= ENV['USER_NAME}' %>  &
password: <%= ENV['PASSWORD}' %>     under production:

3:  And use.....user_name and password?  (within my environment.rb)  (seen below)

```
ActionMailer::Base.smtp_settings = {
  user_name: 'WHAT GOES HERE?',
  password: 'WHAT GOES HERE?',
  domain: 'https://rproderick.github.io/designmonster',
  address: 'smtp.sendgrid.net',
  port: 587,
  authentication: :plain,
  enable_starttls_auto: true
}
```

Again, this is just an outline of what I think I would do.  Documentation from the sendgrid website uses npm packages like figaro, etc, but as I see it, you've already taken care of not deploying secret files, yes?  This step should complete the process.  Let me know, thanks!

**Comment by raq929** [comment]
To make sure you're not overwriting other variables, I would call them MAILER_USERNAME and MAILER_PASSWORD or some such. 

I believe you can call them in your environment.rb file as you did in secrets... ` <%= ENV['USER_NAME}' %>`. Give it a try. :)

**Comment by RpRoderick** [comment]
Ok, and I'm getting an error  "uninitialized constant ActionMailer (NameError)"
on submit.  Google tells me this means that I haven't required ActionMailer in my application.rb file.  I'm looking for solution right now, but if you know it off the top of your head....

**Comment by raq929** [comment]
Nope, I've never used this before.

**Comment by RpRoderick** [comment]
Ok.

**Comment by RpRoderick** [comment]
I'm going to close the issue and focus on other stuff, hopefully get this working tonight or tomorrow.  If/when I do, I'll edit the solution for everyone.
