### ISSUE TITLE
Paperclip Image Not Loading

### ISSUE THREAD

**Issue by LaurenGrant** [ga-wdi-boston/capstone-project#44]
I have been working with Jeff that he had a similar issue with but his solution is not working for me. 

I am able to upload a photo to AWS but I am not able to get the image file path to pass into my handlebars template for the item. 

My handlebars template is 

```
<script id="userItemsDashboard" type="text/x-handlebars-template">

  {{#each items}}
    <li class="card-dashboard">
      <article class="profile">
        <figure>
          <img src="https://s3.amazonaws.com/wdi-items/items/item_images/000/000/0{{id}}/item_feature/{{item_image_file_name}}">
          <figcaption id="item-{{id}}">{{title}}</figcaption>
          <h3>{{zipcode}}</h3>
          <p>{{description}}</p>
        </figure>
        <ul class="tags">
          <li>
            <a href="#" data-itemId='{{id}}'>Edit</a>
          </li>
          <li>
            <a href="#" data-itemId='{{id}}'>Delete</a>
          </li>
          <li>
            <a href="#">Mark as Borrowed</a>
          </li>
        </ul>
      </article>
    </li>
  {{/each}}

</script>
```

The error I am getting in my console is 

"GET https://s3.amazonaws.com/wdi-items/items/item_images/000/000/030/item_feature/              403 (Forbidden)"

It is not reading the {{item_image_file_name}} which is the correct name of how it is stored in my local database.

**Comment by GA-MEB** [comment]
`{{item_image_file_name}}` may be how it's stored in the database. But is it accessible in the template?

Instead of using it in a URL, try just putting it inside some `<p>` tags and see what value it has.
i.e.
`<p>{{item_image_file_name}}</p>`

**Comment by gaand** [comment]
Following what @MattB-GA-Boston said, console log the object you're passing to the template to see what it contains.

**Comment by LaurenGrant** [comment]
I just added "<p>{{item_image_file_name}}</p>" right above the img tag in the handlebars template and received the same error. Nothing appeared on the front end in terms of where the p tag would show up.

**Comment by LaurenGrant** [comment]
I am not sure where you mean to console log the object.

**Comment by gaand** [comment]
Actually, I just remembered, you can call `{{log item_image_file_name}}` in your template.  This should show that value in the chrome console when the template is rendered.

**Comment by LaurenGrant** [comment]
I just tried {{log item_image_file_name}}. Nothing was logged. No change in error message.

**Comment by gaand** [comment]
Try `{{log "the item image file name is: " item_image_file_name}}`.

**Comment by LaurenGrant** [comment]
I just tried 

```
<script id="userItemsDashboard" type="text/x-handlebars-template">

  {{#each items}}
    <li class="card-dashboard">
      <article class="profile">
        <figure>
          <img src="https://s3.amazonaws.com/wdi-items/items/item_images/000/000/0{{id}}/item_feature/{{log "the item image file name is: " item_image_file_name}}">
          <figcaption id="item-{{id}}">{{title}}</figcaption>
          <h3>{{zipcode}}</h3>
          <p>{{description}}</p>
        </figure>
        <ul class="tags">
          <li>
            <a href="#" data-itemId='{{id}}'>Edit</a>
          </li>
          <li>
            <a href="#" data-itemId='{{id}}'>Delete</a>
          </li>
          <li>
            <a href="#">Mark as Borrowed</a>
          </li>
        </ul>
      </article>
    </li>
  {{/each}}

</script>
```

No change in error message. Nothing was logged in my console.

**Comment by LaurenGrant** [comment]
Actually I was wrong, I can see it says 

"Object {items: Array[33]}
the item image file name is:  undefined"

**Comment by gaand** [comment]
That means the value you're trying to use is empty.  What do you see if you query the model from the rails console?

**Comment by LaurenGrant** [comment]
The item name was wrong in my serializer. Jeff and Saad just helped me with this. Going to close the issue now. Thanks for your help!
