### ISSUE TITLE
having trouble figuring out how to present data from a table and have it be arranged according to one of the fields, in ember.

### ISSUE THREAD

**Issue by kfili** [ga-wdi-boston/capstone-project#440]
In my API i have one table called channels, one of the fields in the table is called "city".

In my ember front end, I want to present a list of the cities. Each city should have a sublist of channels that are in that city.  So somehow I'd need to populate a list of cities using the data from the API's channels table. Can this be done just on the front end? How would I get the channels to show as a sublist to each city? 

Currently I'm able to get a list of cities to show up. I haven't yet gotten any channels to show up under each city.

listr-list/template:
```
<h3 class="list-header" {{action 'toggleListDetail'}}>listr-list component: {{channel.city}}</h3>
{{!-- #each listr-list component 'toggleListDetail' - so they are hidden from the beginning --}}

<ol>
  Comment: listr-list trying to display each channel here:
  {{#each channel as |channel|}}

    {{listr-list/item channel=channel
                      toggleDone='toggleItemDone'
                      delete='deleteItem'}}
  {{/each}}
</ol>
```

listr-list/item/template:
```
<h3>listr-list/item component</h3>
<span class="list-item">{{channel}}</span>
```

**Comment by kfili** [comment]
I'm thinking I'd probably have to do something in router.js, and channels/route.js. I will probably have to use ```findRecord```

**Comment by raq929** [comment]
What happens right now?

In general, ember wants hasMany relationships to be a list of IDs. You'll also need a channel model.

**Comment by kfili** [comment]
I've pasted my channel model below. So I take it that I might want to try making a hasMany('city') or something like that?

```
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  url: DS.attr('string'),
  city: DS.attr('string'),
  state: DS.attr('string'),
  // items: DS.hasMany('item'),
});
```

**Comment by kfili** [comment]
right now I have it displaying a list of cities basically. And it displays some cities twice. I haven't gotten it to show channels under the cities

**Comment by raq929** [comment]
I'm confused about what's going on. The model here has one city, which is a string. Are you actually giving it an array of cities?

**Comment by kfili** [comment]
I thought what this meant is that 'city' is a field of the 'channels' table...
I'm not sure exactly what channel/model.js does, I know I need it for the get request to work. After i generated it, I adapted the code from the ember-resources repo and produced the above code.

**Comment by raq929** [comment]
`channel.model` tells Ember what to expect each object to look like when it makes requests to `channels/`

**Comment by raq929** [comment]
So, when you make a get request to `channels/` what do you get back?

**Comment by kfili** [comment]
I get an array of channels as objects. Should I make a table of cities in my express API, and make some relations to my channels table? Or can I build a list of cities using ember, and use and ember model to create a relation like city hasMany channels

**Comment by raq929** [comment]
I don't understand what cities are and what you want out of them. Can you give me more context?

**Comment by kfili** [comment]
here is the schema for the channels table, if that helps. 
each channel has a city
```
const channelSchema = new mongoose.Schema({
  title: {
    type: String,
    unique: true,
  },
  url: {
    type: String,
    unique: true,
    required: true,
  },
  city: {
    type: String,
    required: true,
  },
  state: {
    type: String,
    required: true,
  },
```

**Comment by kfili** [comment]
on my front end I want to basically sort the channels by city. What I want the user to see first is a list of cities, and then they can see a sub list under each city that contains the channels

**Comment by raq929** [comment]
AH, it all makes sense now! 

This is a component, right?

I think you need a key in your component that is a computed property, that returns all the unique cities in the models as an array.

Then in your template, you display each city in the cities array, and have if statements to display the channels `if` they match the city.

**Comment by kfili** [comment]
I'm closing this temporarily, until i have time to try this approach. I have to prioritize some other tasks right now.
