### ISSUE TITLE
POST - Creating 5 New Items instead of One

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/capstone-project#442]
When I create an item on the front-end, there are five items created and rendered on the front-end. I do not understand why the POST action is firing 5 times. I've searched the entire front-end app and confirmed the POST function is only being called once.  I'm not seeing any closed issues related to this problem and am also not finding anything useful via google searches. Cannot figure out why this would be happening.

**Comment by raq929** [comment]
LOL. (I'm laughing with you.) Are there 5 items created on the back end?

**Comment by jdaly04** [comment]
This problem has been solved. This issue was that I was attaching click handlers to the create, update, and delete submit buttons EVERY time I clicked "View all projects". Depending on how many times I clicked "View all Projects", that would match the number of POST/PATCH/DELETEs. 

Chris helped me find a solution by changing code to:
```js
const onViewProducts = function(event) {
  event.preventDefault();
  api.viewAllProducts()
    .then(ui.viewAllSuccess)
    .then(function() {
      $('#new-prod').off();
      $('#create-form').off();
      $('.updateProduct').off();
      $('.deleteProduct').off();
      $('#new-prod').on('click', onCreateNewButton);
      $('#create-form').on('submit', onCreateProduct);
      //$('.edit-product').on('click', onUpdateProductButton);
      $('.updateProduct').on('submit', onUpdateProduct);
      $('.deleteProduct').on('submit', onDeleteProduct);

    })  //getAllSuccess needs to be updated
    .catch(ui.failure);
  // }
};
```
