### ISSUE TITLE
Can't set get associated ID to set on creation of resource.

### ISSUE THREAD

**Issue by Naki21** [ga-wdi-boston/capstone-project#444]
Im trying to get newly created submissions to associate properly with their contest. Right now I'm pulling form data from a component and passing that up. My problem is I cant seem to set the contest model anywhere along the component chain or on the route. I can't seem to access the id from anywhere. 

Submission Component
``js
import Ember from 'ember';

export default Ember.Component.extend({

    actions: {
      save() {
        console.log('Inside submission new component');
        console.log(this.get('contest'));
        console.log(this.get('contest.id'));
        console.log(this.get('submission.contest'));
        let submission = this.get('submission');
        submission.contest = this.get('contest');
        this.sendAction('save', submission);
      },
      cancel() {
        this.sendAction('cancel', this.get('submission'));
      }
    }
});
```
Submission Route
```js
  model() {
    return this.get('store').createRecord('submission');
  },
  actions: {
    saveSubmission(submission) {
    console.log(this.get('contest'));
    console.log('backhere');
    console.log(submission);
    submission.save();
    }
  }
});
```
Submission Template
 ```js 
{{client-contests/submission/new submission=model contest=model.contest save='saveSubmission' cancel='cancelSubmission'}}
```

Ive tried to pass and set the contest id all over and I cant seem to do it.

**Comment by raq929** [comment]
Does cancel work?

**Comment by raq929** [comment]
Also, what is the error?

**Comment by raq929** [comment]
And please post the component template

**Comment by Naki21** [comment]
I haven't got to cancel yet. the error is a null value error for contest_id on the backend.

**Comment by Naki21** [comment]
Sorry about the template but I was trying to pass the contest model down on it so I thought it was relevant

**Comment by raq929** [comment]
No no, I totally want that template. I also want the component template. MOAR CODE PLZ.

**Comment by Naki21** [comment]
```html 
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-file">  </span>POST NEW DESIGN</a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
              <form class="form" {{action 'save' on='submit'}}>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    {{input type="text" class="form-control" placeholder="Title" value=submission.title }}
                  </div>
                  <div class="form-group">
                    {{textarea class="form-control" placeholder="Description" rows="5" value=submission.description }}
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="well well-sm">
                    <div class="input-group">
                      <span class="input-group-addon">www.jquery2dotnet.com/</span>
                      {{input type="text" class="form-control" placeholder="Image Url" value=submission.image}}
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="well well-sm well-primary">
                        <button type="submit" class="btn btn-success btn-sm">
                                                <span class="glyphicon glyphicon-floppy-disk"></span>Save</button>
                  </div>
                </div>
              </div>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by Naki21** [comment]
Is it possible I could sit down with you and look this over?  Im hung up on this and I can't really do anything else

**Comment by Naki21** [comment]
Issue resolved. 

Not exactly sure how we did it. Now I pass the contests model down and define submissions on the component and then send that up and createRecord inside the route...
