### ISSUE TITLE
Ember| Update Post

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/capstone-project#446]
I am trying to update a post as an authenticated user. i have create working, so  it will be similar to that.
I want to show the post that will need to be updated and then have a form to update it.
Right now I created a submit button with form fields that attempts to update the Blog Post. It needs to have the title, body, and id to update.
I am currently getting the errror:
```
EmberError {description: undefined, fileName: undefined, lineNumber: undefined, message: "Assertion Failed: `id` passed to `findRecord()` has to be non-empty string or number", name: "Error"…}
```

I am trying to user findRecord. I believe it takes an id as a parameter  but i don't know how to pass it.

**Comment by raq929** [comment]
How are you getting to this view? ie, what template links to this or has it as a component. 
Please post your form code, your route, and any other relevant files.

**Comment by jbuzzanco** [comment]
Posts route
```import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return this.get('store').findAll('post');
  },
  actions: {
    delete(post) {
      post.deleteRecord();
      post.save();
    },


    save(params) {
      console.log('params id is', params.id);
      let newPost = this.get('store').findRecord('post', params.id);
      // let currentUser = this.get('user_id');

      // newPost = Ember.Object.Extend({
      //   currentUser: function(){
      //     return `$this.get('user_id')}`
      //   }
      // });
      console.log("new post 24 is ", newPost);
      // console.log("user is", this.get('user'));
      //
      // this.get('store').findRecord('user', this.get('user'))
      //   .then((user)=>{
      //     newPost.set('user_id', user);
      //     console.log("new post 26 is ", newPost);
      //
      //   });
      // console.log("new post 28 is ", newPost);

      newPost.save().then((post) => {
        this.transitionTo('post', post);
      });
    },
  }
});
```
posts template
```
<h3>Posts index</h3>

<ul>
    {{#each model as |post|}}
      <li>
        {{#link-to 'post' post}}
          {{post.title}}
        {{/link-to}}
        <br>
        <button class='btn btn-md btn-danger'{{action 'delete' post}}>Delete</button>


        <h3>Post Edit</h3>
          <form>
            <div>
              <label>Title:</label>
              {{input type="text" value=model.title}}

              {{!-- <label>You're {{currentUser}}{{model.user.id}}{{user}}</label>
         --}}
            </div>
            <div>
              <label>Body:</label>
              {{textarea rows="10" value=model.body}}
            </div>
            <div>
              <button {{action 'save'}}>Save Post</button>
              <button {{action 'cancel'}}>Cancel</button>
            </div>
          </form>





      </li>
    {{/each}}
</ul>
{{#link-to 'post.new'}}<button class="btn btn-lg">New Post</button>{{/link-to}}

```

**Comment by jbuzzanco** [comment]
Also , as an update of what I tried, when I hard code the post id for findRecord it gives back newPost.save is not a function. 

I don't know if that is helpful to explaining what is going wrong or not, but ya, I'm not sure what's going on.

**Comment by raq929** [comment]
newPost is new, it doesn't have an id yet, so this line `let newPost = this.get('store').findRecord('post', params.id);` makes no sense to me.

**Comment by raq929** [comment]
`save` should be receiving the post you've created with your form.

**Comment by jbuzzanco** [comment]
Ok. I am thinking it won't actually work to update from the index view because the model is
`return this.get('store').findAll('post');`
and I get a linter error that there can't be multiple returns when I try to include findRecord. As in after return i put, `return this.get('store').findRecord('post', params.post_id)`

**Comment by raq929** [comment]
I would not update from the index view. I mean, it depends what index view you're talking about. I need a lot more context to be useful here.

**Comment by jbuzzanco** [comment]
It is the index of all posts,
and I was attempting to edit within that view

**Comment by raq929** [comment]
Yeah, I think, like in #434, you will need to link to an update view.

**Comment by jbuzzanco** [comment]
Ok I will take a look at it

**Comment by raq929** [comment]
What's your status?

**Comment by jbuzzanco** [comment]
Ok it is resolved. I have been working on it until now and Chris has helped me too.  Thanks for checking up, basically I didn't add another view. this is the route for posts, not part of a component, but right in posts view
```
edit(post){
      console.log('youre at posts route. your ppost is ', post);
      post.save();
willTransition(){
      // console.log('insideWillTransition');
      this.get('store').peekAll('post').forEach(function(post){

        // console.log("post.get('hasDirtyAttributes');",   post.get('hasDirtyAttributes'));
        if (post.get('hasDirtyAttributes')) {
          post.rollbackAttributes();
        }
      });
```
