### ISSUE TITLE
My edit and delete buttons won't appear. only the first html element renders.

### ISSUE THREAD

**Issue by kfili** [ga-wdi-boston/capstone-project#449]
I have a table of 'channels' and render a list of channels using a top level component: 'listr-list'.
Inside the listr-list template is a link, and two buttons. The problem is only one of those 3 elements is ever rendered for each channel.  

I have tried:
- rearranging the elements.
- checking the action and data chains.
- wrapping all elements in a div or span.
- removing classes
- removing ```{{action 'something'}}```
- removing the <a> tag

here is listr-list/template
```
<a href="{{channel.url}}">
    <h3 class="list-header" target="_blank">{{channel.title}}</h3>
    {{channel.city}}, {{channel.state}}
</a>
<button class='btn btn-xs' {{action 'editChannel'}}>edit</button>
<button class='btn btn-xs btn-danger' {{action 'delete'}}>delete</button>
```
here is listr-list/component
```
import Ember from 'ember';

export default Ember.Component.extend({
  classNames: ['listr'],
  classNameBindings: ['listDetailHidden'],
  listDetailHidden: true,
  actions: {
    toggleListDetail () {
      return this.toggleProperty('listDetailHidden');
    },
    toggleItemDone (item){
      console.log('youre in toggleDone listr-list Component');
      this.sendAction('toggleItemDone', item);
    },
    editChannel(){
      console.log('Youre inside editList');
      this.sendAction('editChannel', this.get('channel'));
    },
    delete (channel) {
      this.sendAction('deleteChannel', channel);
    },
  },
});
```
here is channels/template
```<h2>Channels route</h2>

{{#link-to 'channels/new'}}
  Add a new channel
{{/link-to}}


{{#each model as |channel|}}
<div>
  {{listr-list  channel=channel
                editChannel='editChannel'
                delete='deleteChannel'}}
</div>
{{/each}}
```
here is channels/route
```
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('channel');
    // return this.get('store').findRecord('channel', params.list_id);

  },
  actions:{
      createItem (){
        console.log('inside createitem, item is ', this.get('item'));
        console.log('inside createitem this.get(newItem) is ', this.get('newItem') );
        // console.log('inside createitem ', );
        let data = this.get('newItem');
        data.list = this.get('list');
        // this.get('newItem').set('list', this.get('list'));
        this.sendAction('createItem', this.get('newItem'));
      },
      editChannel (channel) {
        console.log('im in channels/route', channel);
        this.transitionTo('channel/edit', channel);
      },
      deleteChannel (channel) {
        channel.destroyRecord();
      }
  }
});
```

**Comment by raq929** [comment]
Is it always the same thing being rendered, or does the element render change when you reorder?

**Comment by raq929** [comment]
Please try to do things one step at a time. Don't add delete until edit is working.

**Comment by kfili** [comment]
Ok I'll remove delete for now. 

the element rendered changes, its always just the first element rendering. So either the link, or the edit button.

**Comment by raq929** [comment]
Huh. When you inspect element using your chrome inspector, are both elements there?
It sounds like poorly formatted html. But I don't see what the issue is.

**Comment by raq929** [comment]
Wait, you're iterating through channels. Does the first thing show up for **each** channel, or does only the very first thing show up?

**Comment by kfili** [comment]
what do you mean by thing?

**Comment by raq929** [comment]
The link or edit button.

**Comment by kfili** [comment]
All channels show up. either a link or a button shows up for all channels.

**Comment by kfili** [comment]
I tried putting the button in the #each statement in my route template and the button shows up but doesn't work properly

**Comment by raq929** [comment]
If you remove the link and have both buttons, do they both show up?

(Also, this issue was a really good issue, btw. You told us what you did, posted all the code... ❤️ )

**Comment by kfili** [comment]
I tried that and only one of the buttons shows up
(oh thanks:)

**Comment by raq929** [comment]
Well shit. That's really strange. 

Um. OK. Take things out of the component one by one and see if that fixes the problem.

**Comment by raq929** [comment]
If that doesn't work, create a **new** component (different name) and copy things to it one by one and see when it breaks. 

#isolateTheProblem

**Comment by kfili** [comment]
I found the problem. It was some leftover code(see below) in the channels/route file (full code in first comment)

```
  classNameBindings: ['listDetailHidden'],
  listDetailHidden: true,
```
