### ISSUE TITLE
Finding all items in database collection with a value and storing that value

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/capstone-project#450]
I need to find a way to search through every item in a database, check their 'category' value and if that value is unique add it to a list of categories that can be accessed by a template. I have been stuck on this for the better part of an hour and am completely out of ideas. I thought I could do something like:
```
let records = this.get('store').findAll('portfolio-image');
let tags = {};
for(let i in records) {
 let category = records[i].get('category');
 tag[category] = category;
}
```
But ember data in ember objects can't be accessed that easily from the router.js file. I'm totally stumped and in desperate need of help.

**Comment by raq929** [comment]
Is there a reason to do this on the front end rather than the back end? It sounds like it might be easier to do there. Have a categories table, and when new things are added, check if their category is in it, then add if not.

**Comment by treep78** [comment]
If I knew how to do that it might be, but I have no idea how to build a separate collection based on the contents of a collection.

**Comment by treep78** [comment]
I can give it a shot

**Comment by treep78** [comment]
I tried, but could not get it to work 
```
const create = (req, res, next) => {
  let portfolio_image = Object.assign(req.body.portfolio_image, {
    _owner: req.user._id,
  });
let category = req.body.portfolio_image.category;
  Portfolio_images.create(portfolio_image)
    .then(portfolio_image =>
      res.status(201)
        .json({
          portfolio_image: portfolio_image.toJSON({ virtuals: true, user: req.user }),
        }))
      .then(Categories.create(category))
      .then(category =>
        res.status(201)
          .json({
            category: category.toJSON({virtuals: true, user: req.user}),
          }))
        .catch(next);
};
```

**Comment by treep78** [comment]
there is also a model which is imported at the top of the file

**Comment by raq929** [comment]
What's the error?
Also, you can't send two responses to one request. I think this request should return the portfolio image, and then Ember can make a seperate get request to categories when it needs them.

**Comment by treep78** [comment]
I did some reworking and got it to work!
```
const create = (req, res, next) => {
  let portfolio_image = Object.assign(req.body.portfolio_image, {
    _owner: req.user._id,
  });
let category = Object.assign({category: req.body.portfolio_image.category}, {_owner: req.user._id,});
  Portfolio_images.create(portfolio_image)
    .then(portfolio_image =>
      res.status(201)
        .json({
          portfolio_image: portfolio_image.toJSON({ virtuals: true, user: req.user }),
        }))
    .then(Categories.create(category))
    .catch(next);
};
```

**Comment by treep78** [comment]
thanks!
