### ISSUE TITLE
when I try to edit I get an error on submit. "Uncaught TypeError: channel.save is not a function" from channel/edit/route.js

### ISSUE THREAD

**Issue by kfili** [ga-wdi-boston/capstone-project#452]
I have a table of 'channels'. When I try to edit one of my channels and then click save, it throws the following error.

I've tried:
- making it this.channel (also not a function)
- console logging the 'channel' param in channel/edit/route saveChannel function ( see next comment for console log)

```
Uncaught TypeError: channel.save is not a function
    at Class.saveChannel (route.js:10)
    at Router.triggerEvent (ember.debug.js:27862)
    at trigger (ember.debug.js:55572)
    at Router.trigger (ember.debug.js:57141)
    at Class.send (ember.debug.js:27052)
    at Class.send (ember.debug.js:31061)
    at Class.triggerAction (ember.debug.js:34765)
    at Class.sendAction (ember.debug.js:39860)
    at Class.save (component.js:18)
<snip>
```

channel/edit/route.js 
```
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
      console.log(params);
      return this.get('store').findRecord('channel', params._id);
    },
  actions: {
    saveChannel (channel) {
      console.log('in channel/edit route. channel is', channel);
      channel.save();
      this.transitionTo('channels');
    },
    cancel (channel) {
      channel.rollbackAttributes();
      this.transitionTo('channels');
    },
    // editChannel (channel) {
    //   console.log('im in channels/route', channel);
    //   this.transitionTo('channel/edit', channel);
    // },
    deleteChannel (channel) {
      channel.destroyRecord();
    }
  }
});
```

Here is channels/route.js (it calls the previous file)
```
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('channel');
    // return this.get('store').findRecord('channel', params.list_id);

  },
  actions:{
      createItem (){
        console.log('inside createitem, item is ', this.get('item'));
        console.log('inside createitem this.get(newItem) is ', this.get('newItem') );
        // console.log('inside createitem ', );
        let data = this.get('newItem');
        data.list = this.get('list');
        // this.get('newItem').set('list', this.get('list'));
        this.sendAction('createItem', this.get('newItem'));
      },
      editChannel (channel) {
        console.log('im in editChannel, in channels/route channel is', channel);
        this.transitionTo('channel/edit', channel);
      },
      deleteChannel (channel) {
        channel.destroyRecord();
      }
  }
});
```
Here is  listr-list/compnent  (it calls the previous file)
```
import Ember from 'ember';

export default Ember.Component.extend({
  classNames: ['listr'],
  // classNameBindings: ['listDetailHidden'],
  // listDetailHidden: true,
  actions: {
    toggleListDetail () {
      return this.toggleProperty('listDetailHidden');
    },
    toggleItemDone (item){
      console.log('youre in toggleDone listr-list Component');
      this.sendAction('toggleItemDone', item);
    },
    editChannel(){
      console.log('Youre inside listr-list/component in editList, this.get(channel) is ', this.get('channel'));
      this.sendAction('editChannel', this.get('channel'));
    },
    // delete (channel) {
    //   this.sendAction('deleteChannel', channel);
    // },
  },
});
```

**Comment by kfili** [comment]
console logging the 'channel' param in channel/edit/route saveChannel function and the object looks like this:

```
in channel/edit, in saveChannel, channel is
 Object
city: (...)
get city: GETTER_FUNCTION()
set city: SETTER_FUNCTION(value)
state: (...)
get state: GETTER_FUNCTION()
set state: SETTER_FUNCTION(value)
<snip>
```

**Comment by payne-chris-r** [comment]
So, there is always the flow of route -> component -> component, and then back up again. Remember "data down, actions up".
So after the model hook in your channel/edit route, are you passing it down to the component? If so, are you passing it back up with the newly added data when you call `saveChannel`? When you log `in channel/edit, in saveChannel, channel is` is there an `id` in there anywhere?

**Comment by kfili** [comment]
>So after the model hook in your channel/edit route, are you passing it down to the component? 

Not sure, I put a log in the model hook in channel/edit/route but it never gets run. I can't remember how to tell if im doing it right in the model hook.

>If so, are you passing it back up with the newly added data when you call saveChannel? 

Maybe not because first the component is logging and then the route.

>When you log in channel/edit, in saveChannel, channel is there an id in there anywhere?

no, I looked around in it but didnt see anything. I messed up my ember-resources repo so Im not sure how to roll back commits so that I can use it as a reference. I'm pretty sure I'm passing the wrong thing to saveChannel... I think its supposed to show up in the console as 'class', when i log it, instead of an object full of getters and setters.

**Comment by raq929** [comment]
Post your templates please. And the route/component if they've been updated.

**Comment by kfili** [comment]
Just managed to fix this, I deleted my nested edit component and created a top level component for editing and added some code to the function that finally sends the update request

```
  actions: {
    save (channel) {
      let _this = this;              // new line
      channel.save().then(    //  added a .then
      _this.transitionTo('channels'));
    },
```
