### ISSUE TITLE
Deployment Issue with `ember build --environment=production`

### ISSUE THREAD

**Issue by matthewgsommers** [ga-wdi-boston/capstone-project#453]
I've been following the steps listed in the deployment guide, but when I enter the following command, I get the following error:

Command entered:
`$ ember build --environment=production`

Error given back:
`-bash: ember: command not found`

Attempting to `npm install` and `bower install` (even though I did it when I originally created each repo) yields the following results, respectively:

`$ npm install`
`-bash: npm: command not found`

`$ bower install`
`-bash: bower: command not found`

So needless to say, I'm a bit confused. Thank you!

**Comment by gaand** [comment]
First run `brew update` then `brew upgrade`. Then `nvm ls`.  You might need to close the terminal application afterward and reopen. If you get any errors, please post them.

**Comment by matthewgsommers** [comment]
The first two commands ran successfully. I tried `nvm ls` and received the following error:
`-bash: nvm: command not found`

**Comment by matthewgsommers** [comment]
Never mind, I closed terminal and reopened the terminal and ran `nvm ls` and it appeared to work. I thought I would have to close & reopen after `nvm ls`, not after. The response I received was: 

```
->       v4.6.0
default -> v4 (-> v4.6.0)
node -> stable (-> v4.6.0) (default)
stable -> 4.6 (-> v4.6.0) (default)
iojs -> N/A (default)
lts/* -> lts/argon (-> v4.6.0)
lts/argon -> v4.6.0

```
