### ISSUE TITLE
Ember refuses to use data sent back from server

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/capstone-project#454]
So to get my project to work I have had to highly modify the data my server returns, however I have had trouble getting ember to use it. The modification is as follows
```
const index = (req, res, next) => {
  Categories.find()
    .then(categories => {
      let tags = {};
      for(let tag in categories){
        if(tags[categories[tag].category]) {
          tags[categories[tag].category] += 1;
        } else {
          tags[categories[tag].category] = 1;
        }
      }
      tags.id='587ffef41a6013eb19c098a0';
      console.log(categories);
      res.json({'categories': tags});
    })
    .catch(next);
};
```
VS ORIGINAL:
```
const index = (req, res, next) => {
  Example.find()
    .then(examples => res.json({
      examples: examples.map((e) =>
        e.toJSON({ virtuals: true, user: req.user })),
    }))
    .catch(next);
};
```
I had to ad a bogus ```id``` to the returned data to get ember to stop complaining, but it still refuses to actually let me use the data. When curl requested the data looks like this:
```
categories": {
"advhfdeoif": 1,
"Siding": 1,
"siding": 2,
"decks": 3,
"id": "587ffef41a6013eb19c098a0"
}
```
This had to be done to get a list of all the categories and then the number of times they occur.

**Comment by raq929** [comment]
Yeah, it needs IDs. Do you have a category model?

**Comment by raq929** [comment]
Ah. When Ember sees a plural, it expects a list, but you're giving it a single object. Try sending it as an array.

**Comment by treep78** [comment]
I did, but no difference. The only thing I can think is that all objects currently have the same id. Could that be a problem?

**Comment by raq929** [comment]
I can't imagine that not being a problem.

**Comment by treep78** [comment]
ok, they all have unique ids. No progress.

**Comment by treep78** [comment]
ok, so through a convoluted process of modifying models, front and back end, and turning everything into a string I finally have it working.
