### ISSUE TITLE
Auth sign-in / sign-up 404 Errors

### ISSUE THREAD

**Issue by matthewgsommers** [ga-wdi-boston/capstone-project#455]
After successfully deploying my website, I'm unable to sign in or up. When I try to, I receive the following lines in the console:

`POST https://evening-oasis-74949.herokuapp.com/festivals/sign-up 404 (Not Found)`
`XHR finished loading: POST "https://evening-oasis-74949.herokuapp.com/festivals/sign-up".`

So it seems like I'm receiving a 404 and then the post is going through successfully? Not sure why this is happening. 

Deployed site: https://callmelife.github.io/festival-fanatic-front-end/

**Comment by payne-chris-r** [comment]
Why is it posting to `.../festivals/sign-up`?

**Comment by callmelife** [comment]
I meant when I try to sign-up I receive that error, I'll be more explicit with my phrase next time - Thanks!

**Comment by matthewgsommers** [comment]
If I'm not correct, I think thats coming from app/sign-in/route.js. I had changed it from `application` to `festivals` so that it would auto-load a different view. Code:
```
actions: {
    signIn (credentials) {
      return this.get('auth').signIn(credentials)
      .then(() => this.transitionTo('festivals')) // changed  `application` to `festivals`
      .then(() => this.get('flashMessages').success('Thanks for signing in!'))
      .catch(() => {
        this.get('flashMessages')
        .danger('There was a problem. Please try again.');
      });
    },
  },
```

**Comment by payne-chris-r** [comment]
No, it's trying to make a `sign-up` request as a POST to `https://evening-oasis-74949.herokuapp.com/festivals/sign-up`. You changed it elsewhere (like in the adapter).

**Comment by matthewgsommers** [comment]
I just checked my first commit version of my adapter against my last, their both the same. So where else would you imagine that this could be coming from if not my SignIn function nor the adapter?

code from app/application/adapter.js:

```
import ENV from 'festival-fanatic/config/environment';
import ActiveModelAdapter from 'active-model-adapter';

import Ember from 'ember';

export default ActiveModelAdapter.extend({
  host: ENV.apiHost,

  auth: Ember.inject.service(),

  headers: Ember.computed('auth.credentials.token', {
    get () {
      let headers = {};
      const token = this.get('auth.credentials.token');
      if (token) {
        headers.Authorization = `Token token=${token}`;
      }

      return headers;
    },
  }),
});
```

**Comment by matthewgsommers** [comment]
Also looking at `app/sign-up` since it starts the sequence of events. Although I havent found anything.

```
import Ember from 'ember';

export default Ember.Route.extend({
  auth: Ember.inject.service(),
  flashMessages: Ember.inject.service(),

  actions: {
    signUp (credentials) {
      this.get('auth').signUp(credentials)
      .then(() => this.get('auth').signIn(credentials))
      .then(() => this.transitionTo('application'))
      .then(() => {
        this.get('flashMessages')
        .success('Successfully signed-up! You have also been signed-in.');
      })
      .catch(() => {
        this.get('flashMessages')
        .danger('There was a problem. Please try again.');
      });
    },
  },
});

```

**Comment by raq929** [comment]
Can you sign in via curl request?

**Comment by payne-chris-r** [comment]
What's `ENV.apiHost`?

**Comment by matthewgsommers** [comment]
Chris mentioned in person that he believed I was incorrectly making requests to `https://evening-oasis-74949.herokuapp.com/festivals/` so I went back and checked config/environment after each step in the deployment guide and manually removed `/festivals` from the URL. 

I'm now able to access my deployed site.
