### ISSUE TITLE
Deployment Failure

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/capstone-project#456]
First attempt: I tried following the ember deployment guide alongside Chris and Ariel and was getting a build error due to favicon.png being outside the security scope (?)/ not being found. I deleted the favicon I had added and the favicon that was part of the original repo and tried to build again. This build resulted in being able to see some of my divs, but my background image and my leaflet maps were not rendering.

Second attempt: I implemented some of Ryan's changes in an attempt to render images. I added a routerRootURL to my ENV variable and changed the rootURL where `environment === production`. This resulted in 404 errors and nothing rendering. I also heard from Caleb (who is also using leaflet) that his fix to deploy used the opposite of the route Ryan suggested to deploy background images. So I think my issue is two-fold in that I need a deployment method that renders images and leaflet maps.

**Comment by raq929** [comment]
I would go Caleb's route.

**Comment by raq929** [comment]
Status?

**Comment by kiraamaa** [comment]
Trying Caleb's route, Need to fix some other bugs before re-deploying

**Comment by kiraamaa** [comment]
Caleb's fix in the config file to change 
```js
if (environment === 'production') {
    ENV.rootURL = '/capstone-frontend';
    ENV.locationType = 'hash';
    ENV.apiHost = 'https://blooming-castle-72694.herokuapp.com';
  }
```
to
``` js
if (environment === 'production') {
    ENV.rootURL = '/capstone-frontend/';
    ENV.locationType = 'hash';
    ENV.apiHost = 'https://blooming-castle-72694.herokuapp.com';
  }
```
broke my deployment. I changed it back to the first block of code and am now waiting for the site to render through gh-pages.

I also added this fingerprint from the ember leaflet tutorial to render the layers and markers properly.:
```js
fingerprint: {
    exclude: [
      'images/layers-2x.png',
      'images/layers.png',
      'images/marker-icon-2x.png',
      'images/marker-icon.png',
      'images/marker-shadow.png'
    ]
  },
```

**Comment by kiraamaa** [comment]
Was able to deploy and see markers by using Caleb's fix in the config file:
```js
if (environment === 'production') {
    ENV.rootURL = '/capstone-frontend/';
    ENV.locationType = 'hash';
    ENV.apiHost = 'https://blooming-castle-72694.herokuapp.com';
  }
``
