### ISSUE TITLE
Disambiguation of capstone project technical requirements

### ISSUE THREAD

**Issue by joaufi** [ga-wdi-boston/capstone-project#458]
When I was planning my app (a chat app) the main action concerns that I determined for my project were the following:
Show and Create on Messages
Index, Show, and Create on Conversations
And then the built in User auth actions

For a chat app, especially within the time span that we have/had, and using technologies such as Websockets and Ember for its implementation, I feel that this is a valid set of action concerns. 

Of course, one could argue that it being able to destroy a Conversation/Message would be an action worth implementing but I don't feel it is necessary to the delivery of a chat app product. Further, being able to Edit a Message would be a neat feature to have but, again, not a necessary feature.

As per the technical requirements:
> Be a complete product, which most likely means multiple relationships and CRUD functionality for at least a couple models

There is multiple relationships between User, Conversation, and Messages. However, all of the functionality is of the Create and Read variety, leaving Update and Destroy off.

As we've gone through projects today it has been said that we need to CRUD. I went forward based off the written requirements, and I did not see cause to worry because multiple times throughout the capstone requirements it said it was up to us what we wanted to design as long as we met some certain criteria.

Now I feel that the intent of requirements does not match up with what was written and am confused. 

So would my project/product, as described above, meet requirements without having specific Update and Destroy functionality on tables other than User.

**Comment by payne-chris-r** [comment]
If your app is really designed to be a "public community slack channel" then I would implement some sort of "screen name" or "user name" that isn't an email. If you can CRUD on that, then you will meet expectations without needing to CRUD on messages.

**Comment by joaufi** [comment]
It isn't designed to be a public community slack channel. It is designed to facilitate one to one conversations between two users. So, basically, there will never be a conversation with more than two users in it. Also, the Users table does have a 'username' field instead of an 'email' field. But running with your advice, I will make an 'email' field on the User model such that a user can optionally enter their e-mail to be associated with their account, and be able to modify and/or destroy it as need be. 

Thank you for your advice. 

As it currently stands, however, I am currently designing some sort of CRUD machine that is going to be using Rails and the Browser Auth Template. There is just too many potential areas in my app where it is possible that I couldn't even conceptualize of the existence of an error (e.g. Redis, ActionCable websockets, **Ember**, and complicated frontend/backend relationship modelling). I will certainly finish this project because I can see it being really awesome, but to pass this course I think it is the wrong move.

Thank you for your response, closing this as issue was resolved.
