### ISSUE TITLE
Opinion on Validation

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#459]
As of right now, for backend validation for date in my tasks it is as follows:
```rb
  validates :due_date, format: { with: /\d{4}\-\d{2}\-\d{2}/ }
```
So in the front end, without a date picker, it makes life difficult for the user. Alternatively I can use `input type="date"` on the front end which uses Ember's built in date picker. This then makes the validation not work, even if I change it to:
```rb
  validates :due_date, format: { with: /\d{2}\-\d{2}\-\d{4}/ }
```
 This is better for the user, but I think it means I have to change the data type of `due_date` to be a string on the back end. From a validation perspective, which is better?

**Comment by raq929** [comment]
First, I don't think this is critical for meeting requirements. So I would save it for later.
It depends what you're doing with the dates. I don't think it makes a difference from a validation perspective, it makes a difference to you as a developer. In general, it's probably best to save them as dates if they're dates. 

I would ask Ariel what she did with dates to make them a bit more user-friendly.

**Comment by akradin** [comment]
opened this before I got the does not meet email, closing for now
