### ISSUE TITLE
paper-clipped my will 

### ISSUE THREAD

**Issue by eshimel** [ga-wdi-boston/capstone-project#46]
This is a two person issue...Jeff and I are trying to send a patch request that includes a "paperclipped" parameter, whether we really want it to or not.  

We've tried dividing the problem solving:  I've been working on changing the appropriate controller's update:   Here's what I changed my profile controller to 
  def update
    @profile = Profile.find(params[:id])
    @profile.update_attributes(:username, :studio, :website)
end

and here's my terminal error:
ArgumentError (wrong number of arguments (3 for 2)):
  app/controllers/profiles_controller.rb:39:in `update'

I don't understand what 3 for 2 means.

Jeff has been trying to work the problem from the frontend: 
Here's his terminal response
ActionController::ParameterMissing (param is missing or the value is empty: pet):
 app/controllers/pets_controller.rb:54:in `pet_params'
 app/controllers/pets_controller.rb:35:in`update'

**Comment by gaand** [comment]
You're passing three arguments, all symbols. You probably want to pass a hash containing those three symbols as keys. Most likely using `params.require`.

**Comment by gaand** [comment]
`ActionController::ParameterMissing (param is missing or the value is empty: pet):` means that the JSON sent doesn't have "pet" as a top level key and he's calling 'params.require(:pet)`.

**Comment by eshimel** [comment]
Wasn't passing any data in the profile object, so its wasn't working.  Here's a snippet of the object just incase somebody runs into the issue:
var update_profile = {
          profile : {
 username: $('[data-field=username][data-id=' + updateid + ']').val(),
...Jeff is good...he had a content-type error.
