### ISSUE TITLE
if post.editable not working- Handlebars.

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/capstone-project#460]
I am trying to get a delete button to show only when it is by the user. Only a user who created a post can delete something, as it is validated on the backend. Here is some relevant code.
```
<ul>
    {{#each model as |post|}}
      <li>
        {{#link-to 'post' post}}
          {{post.title}}
        {{/link-to}}
        <br>
        {{#if post.editable}}
        <button class='btn btn-md btn-danger'{{action 'delete' post}}>Delete</button>
        {{/if}}

        {{post-user/edit post=model save='savePost'
                            cancel='cancel'}}

      </li>

    {{/each}}
</ul>
```
right now it does not show the delete button at all with signed in user on a post.

**Comment by jdaly04** [comment]
@jbuzzanco  - I had a similar issue if you want to take a look at: https://github.com/ga-wdi-boston/capstone-project/issues/426 to make sure it's not something similar

**Comment by raq929** [comment]
If you put in just {{post.editable}} (remove the if) what do you get?
Also, check out Julia's issue. Be sure that you're getting editable from the backend and that it's in your ember model.

**Comment by jbuzzanco** [comment]
Ok thanks. just an empty space is what happens with {{post.editable}}

**Comment by raq929** [comment]
OK, that means it's not there. Is it in your ember model? What happens when you make a curl request? Does your post have it then?

**Comment by jbuzzanco** [comment]
OK thanks for your help. I got it fixed by adding def editable into my post serializer
```
class PostSerializer < ActiveModel::Serializer
  attributes :id, :title, :body, :comments, :editable
  belongs_to :user

  def editable
    scope == object.user
  end
end

```
that is my post serializer for reference
