### ISSUE TITLE
Unsure of How To Assign Current User

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#461]
So part of why I didn't meet requirements is because `current_user` owns bands. A band owns tasks, expenses, and contacts so I assumed that `current_user` would blanket over those other things but I guess not. I am not sure how to assign ownership to, lets say  contacts. I have tried the following in my `create method`

`@contact = current_user.Contact.new(contact_params)`
`@contact = current_user.Contact.build(contact_params)`
`@contact = current_user.contacts.build(contact_params)`

With all of these I get:
```sh
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `contacts' for nil:NilClass):
  app/controllers/contacts_controller.rb:23:in `create'
```

**Comment by raq929** [comment]
Your contact_params come with a band_id, right? I would check that the current_user owns that band. If they don't, send back a 403. If they do, carry on.

**Comment by raq929** [comment]
Alternately, or maybe better! On your model, you can do something like
has_many :contacts through :bands

Which you can then use your `current_user.Contact.new(contact_params)` with.

**Comment by raq929** [comment]
The above syntax for has_many is WRONG and you will need to look it up.

**Comment by akradin** [comment]
looked up the syntax and added the following to my user model: 
`has_many :contacts, through: :bands`
And in my contacts model
`belongs_to :user`
and then the `create` method
`@contact = current_user.Contact.new(band_params)`

Same error

**Comment by raq929** [comment]
Ah, sorry, you said create and I was thinking GET. I think you should be able to create the new contact, if and only if the band_id on the contact is in the current user's list of bands. Sorry for leading you a bit astray. I'm tired. 
So something like (syntax is likely wrong)
```ruby
if current_user.bands.any? {|band| band.id === params.band_id}
  do the thing
else
 403
```

**Comment by raq929** [comment]
Also I'm not sure if current_user.bands will return band objects or band ids, so ymmv.

**Comment by payne-chris-r** [comment]
My solution would be `@contact = current_user.bands.find(params.band_id).contacts.find(params.contact_id)` if the band_id that was passed belongs to a band that the current_user owns, then it proceeds to find the contact that belongs to that band.

**Comment by payne-chris-r** [comment]
What I'm not sure of is, if `current_user.bands.find(params.band_id)` returns nil, this may break. You may need an if `current_user.bands.find(params.band_id) && current_user.bands.find(params.band_id).contacts.find(params.contact_id)` or something like that...

**Comment by akradin** [comment]
Uhhh Chris I think you are thinking about GET

**Comment by akradin** [comment]
Do you mind telling me how you got this to happen so I can test,
I am assuming you do the following with CURL Requests:
Sign In/Up with a User
Create a Task
Sign Out
Sign In with a different User
Then delete the other users tasks?

**Comment by raq929** [comment]
Sign in as a user who doesn't own the band whose contacts you want to change (via curl) and attempt to change that band's contacts. (tasks, etc.)

**Comment by akradin** [comment]
Yeah alright, so I did generated a migration adding user references to contacts to and then added the `user_id` into the contacts serializer. I also added 
`if current_user` before my delete and update functions because I have heard from fellow developers that has worked...but it didn't

Also, Rachel's suggestion didn't work either

**Comment by raq929** [comment]
Watch out for #208.
Wait, why are you adding user references to contacts? It doesn't need it, it has them through bands.

**Comment by raq929** [comment]
What do you mean by 'didn't work'? What happened?

**Comment by raq929** [comment]
Please update and close if this is resolved.

**Comment by akradin** [comment]
Still working on the `if` statement for update and delete and how to send back 403
I have tried
`render json: {}, status: :forbidden` and `render status: :forbidden`

**Comment by raq929** [comment]
Try `head :forbidden`

**Comment by akradin** [comment]
Made quite a few changes to the controller and tested all of them with curl requests. Going to post the whole thing and leave the issue open while I work on integrating the changes into the front end.
```rb
class ContactsController < ProtectedController
  before_action :set_contact, only: [:show, :update, :destroy]

  def set_contact
    # @contact = Contact.find(params[:id])
    @contact = current_user.bands.find(contact_params[:band_id]).contacts.find(params[:id])
    puts 'contact is '
    puts @contact
  end

  def contact_params
    params.require(:contact).permit(:name, :phone_number, :email, :company, :details, :band_id)
  end

  def index
    @contacts = Contact.where(:band_id => params[:band])

    render json: @contacts
  end

  def show
    render json: Contact.find(params[:id])
  end

  def create
    if current_user.bands.find(contact_params[:band_id])
      @contact = Contact.new(contact_params)
    else
      render json: { error: 'Not Authorized' }
    end
    puts contact_params

    if @contact.save
      render json: @contact, status: :created
    else
      render json: @contact.errors, status: :unprocessible_entity
    end
  end

  def update
    if @contact.update(contact_params)
      head :no_content
    else
      render json: @contact.errors, status: :unprocessible_entity
    end
  end

  # def destroy
  #   if current_user.bands.find(contact_params[:band_id])
  #     @contact = Contact.find(params[:id])
  #     @contact.destroy
  #     head :no_content
  #   else
  #     render json: { error: 'Not Authorized' }
  #   end
  # end

  def destroy
    @contact.destroy

    head :no_content
  end
end
```

**Comment by akradin** [comment]
As expected, experiencing some front end issues since updating the back end, but I am not really sure what is causing them.

So I nuked and paved after making all of the back end changes and created a new user. I can create a new band and its resources, but if I reload the page, none of the resources are loading. Now, it is creating properly. When I go into rails console I can see whatever resource has been created and it has the correct association. 

Let's say I go to `/band/1/contacts` on the front end, I get
```sh
Started GET "/contacts/1" for ::1 at 2017-01-20 09:37:41 -0500
Processing by ContactsController#show as HTML
  Parameters: {"id"=>"1"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "60c705e8b1beef94057e3c320a0629d3"]]
Completed 400 Bad Request in 2ms (ActiveRecord: 0.2ms)

ActionController::ParameterMissing (param is missing or the value is empty: contact):
  app/controllers/contacts_controller.rb:12:in `contact_params'
  app/controllers/contacts_controller.rb:6:in `set_contact'
```

And this same error will occur for tasks and expenses.
I assume it is related, but this has also messed with my error handling, so if you add a new contact with no name, it should throw a catch to `flashMessages` but that no longer happens.

**Comment by akradin** [comment]
If I change
`before_action :set_contact, only: [:index, :update, :destroy]`
to
`before_action :set_contact, only: [:update, :destroy]`
It is fine...is that okay?

**Comment by raq929** [comment]
Does it allow other bands to get contacts that don't belong to them? Because that's a problem.

What is your server returning when you make the get request that doesn't work? I think this is likely a problem we can solve in the serializer.

**Comment by akradin** [comment]
Yeah disregard my last comment, the server error is posted above

**Comment by akradin** [comment]
It is a params thing so I need to change what is being searched for

**Comment by akradin** [comment]
So I changed my index method to be as follows:
```rb
  def index
    @contacts = current_user.contacts.where(:band_id => params[:band])

    render json: @contacts
  end
```

and

```rb
  def index
    @contacts = current_user.contacts

    render json: @contacts
  end
```


It still doesn't work. Everything seems to be fine when I remove `:show` from the `before_action`

**Comment by akradin** [comment]
Just kidding, I literally can't do anything except add content.  ¯\_(ツ)_/¯

**Comment by raq929** [comment]
k... so what's going on in show?

**Comment by akradin** [comment]
```rb
  def show
    render json: Contact.find(params[:id])
  end
``` 

So I am assuming it needs  to look more like the `set_contact` method

**Comment by gaand** [comment]
Please explain when I find you.

**Comment by gaand** [comment]
@akradin refactored to

```ruby
def set_contact
  @contact = Contact.find(params[:id])
  @band = current_user.bands.find(@contact.band)
end
```

The `@band` line will throw `ActiveRecord::RecordNotFound` if the contact doesn't belong to a band owned by the current user.

**Comment by akradin** [comment]
Yup! did what was said above and changed all other methods within the controller accordingly. Tested on the front end, everything works. Tested with curl requests and everything works. I also signed in via curl request with a second user and attempted to edit and delete another users content and got a 404. Also got a 404 when I tried to add something to a different users band so it looks like we are all set on the back end

**Comment by akradin** [comment]
Everything works on the front end with the exception of a certain sequence of events. If a user deletes a resource, and then tries to add a resource, the typing in the form throws a debugger:
`desc = "Cannot call set with 'cost' on an undefined object.", test = false`

If I route back to `/bands` it solves this problem. But obviously it sucks for the user.

Thoughts? Should I settle with that or use some of the spare time to fix it?

**Comment by akradin** [comment]
Oh wait, I found a psuedo-solution. In my delete function at the `route` level if I do something like this:
```js
    deleteContact(contact){
      contact.destroyRecord();
      contact.rollbackAttributes();
    },
```

It solves the problem of the form not being able to be typed in , BUT, if you delete a contact, and then add a new contact, the deleted contact comes back, obviously it doesn't actually exist (what is real, anyway?) because the DELETE happens successfully and clicking the buttons associated with that contact don't work, but it still shows up nonetheless

**Comment by gaand** [comment]
Does this help https://github.com/ga-wdi-boston/capstone-project/issues/419#issuecomment-273330888 ❓

**Comment by akradin** [comment]
Ah,  Ryan suggested that as well I went ahead and modified that function so it is more in line with my app but the issue persists. 
```js
    willTransition() {
      let store = this.get('store');
      store.peekAll('contact').forEach(function(contact) {
        if (contact.get('isNew') && contact.get('hasDirtyAttributes')) {
          contact.rollbackAttributes();
        }
      });
      return true;
    },
```

I also got crafty and called that function in my delete function with `contact.willTransition()` just to try it out but it didn't work

**Comment by akradin** [comment]
Worked on this for quite a bit with Antony. The jist of what we tried was setting up willTransition. The issue persists if you go to a different view. If you add delete a contact, add a contact, and are transitioned to a different view and navigate back to the contacts view, the 'phantom' contact is still there.

Another thing we tried was placing the new contact form into a different route. If you put the new contact form into an embedded route and then transition back to the contacts list after adding a new one, the issue will still occur.

**Comment by gaand** [comment]
Can you provide the hierarchy of invocations and the names used to pass data down.

**Comment by akradin** [comment]
In the `band/contacts` route, here is the template:
```html
{{contact-list band=model
              createContact='createContact'}}

{{!-- {{#link-to 'band/contacts/new' model }}Add Contact {{/link-to}} --}}

{{#each model.contacts as |contact|}}
<div class="contact-info">{{contact.name}}</div>
<div class="contact-info">{{contact.phone_number}}</div>
<div class="contact-info">{{contact.email}}</div>
<div class="contact-info">{{contact.company}}</div>
<div class="contact-info">{{contact.details}}</div>
{{contact-list/edit contact=contact
                    delete='deleteContact'
                    edit='editContact'}}

{{/each}}
```
The most important part is the `contact-list` component that it calls which is this:
```html
<form class="create-contact" {{action 'createContact' on='submit'}}>
<div class="contact-form">{{input placeholder="Name (required)" value=Contact.name}}</div>
<div class="contact-form">{{input placeholder="Phone Number - 1234567890" value=Contact.phone_number}}</div>
<div class="contact-form">{{input placeholder="email" value=Contact.email}}</div>
<div class="contact-form">{{input placeholder="company" value=Contact.company}}</div>
<div class="contact-form">{{input placeholder="details" value=Contact.details}}</div>
  <div class="button-holder">
    <button class="add-item">Add Contact</button>
  </div>
</form>

```
Then the `component.js` file that handles that action
```js
import Ember from 'ember';

export default Ember.Component.extend({
  Contact: {
    name: null,
    phone_number: null,
    email: null,
    company: null,
    details: null
  },
  actions :{
    createContact(){
      let contact = this.get('Contact');
      contact.band = this.get('band');
      this.sendAction('createContact', contact);
      this.set('Contact.name', '');
      this.set('Contact.phone_number', '');
      this.set('Contact.email', '');
      this.set('Contact.company', '');
      this.set('Contact.details', '');
    },
    deleteContact(contact){
      this.sendAction('deleteContact', contact);
    },
    editContact(contact){
      this.sendAction('editContact', contact);
    }
  }
});
```

Then back up to the `route.js` file
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model(params){
    return this.get('store').findRecord('band', params.band_id);
  },
  actions:{
    willTransition() {
      let store = this.get('store');
      store.peekAll('contact').forEach(function(contact) {
        if (contact.get('isNew') && contact.get('hasDirtyAttributes')) {
          contact.rollbackAttributes();
        }
      });
      return true;
    },
    createContact(newContact){

      let contact = this.get('store').createRecord('contact', newContact);
      return contact.save()
      .then(() => this.get('flashMessages').success('Contact created, keep making connections!'))
      // .then(()=> this.transitionTo('band', newContact.band))
      .catch(() => {
        this.get('flashMessages')
        .danger('Oh No! Something is not quite right. Make sure you have filled out required fields with the right format');
        contact.rollbackAttributes();
      });
    },

    deleteContact(contact){
      contact.rollbackAttributes();
      let band = contact.get('band');
      contact.destroyRecord();
      // this.transitionTo('band', band);
      // this.transitionTo('band/contacts', band);
    },
    editContact(contact){
      this.transitionTo('contacts/edit', contact);
    }
  }
});
```

**Comment by gaand** [comment]
I don't think this is the problem, but would you please change the name from `Contact` to `contact`?  Thanks.

**Comment by akradin** [comment]
Change made, issue persists

**Comment by gaand** [comment]
@akradin Also, I think you should close this issue (which started as one thing and changed to another) and reference it from a new issue focused on the phantom contacts.

**Comment by akradin** [comment]
Relating to new issue #477

**Comment by gaand** [comment]
@akradin Would you mind closing this since it's referenced by #477.
