### ISSUE TITLE
Ownership

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/capstone-project#462]
So yesterday when me and @raq929 spoke. I told her I was having ownership issues so she recommended that I changed the "Photo.all" in the index of the Photos controller to "currentuser.id" It worked but the problem is it made the other page the same way, which is not what I want. 

-When you click on "Your Photos" I want to only be able to see photos that I posted and be able to delete them

-When you click on "Rate These Photos" You see ALL the photos that were posted to the app from multiple users and be able to rate them.

The problem is I was able to see only my photos posted when clicking "your photos" but then when I clicked "Rate these photos" I could only rate my own photos.

This is the Photos Controller I have now. I reverted it back to the "Photo.all" within the index 

```
class PhotosController < ProtectedController
  before_action :set_photo, only: [:show, :update, :destroy]
  def index
    @photos = Photo.all

    render json: @photos
  end

  def show
    render json: Photo.find(params[:id])
  end

  def set_photo
    @photo = current_user.photos.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:name, :category, :url, :user_id)
  end

  def create
    photo_params = params.require(:photo)
                         .permit(:name, :category, :url)
                         .merge(user_id: current_user.id)
    @photo = Photo.new(photo_params)
    if @photo.save
      render json: @photo, status: :created
    else
      render json: @photo.errors, status: :unprocessable_entity
    end
  end

  def update
    if @photo.update(photo_params)
      head :no_content
    else
      render json: @photo.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @photo.destroy

    head :no_content
  end

  private :set_photo, :photo_params
end
```

**Comment by raq929** [comment]
It sounds like you might need an if statement in your route or two different routes to get what you need. One that gets all the photos, and one that only gets your photos.
Alternately, you can have an 'editable' flag on the photos, and only show users the update/delete buttons for editable photos. 
It depends on your use case.

**Comment by Sphilippe7** [comment]
an if statement in the back end? within the controller? @raq929

**Comment by raq929** [comment]
Of the three ideas I listed, I like that one the least.
In order of my preference:
1. Editable - we know how to do this, there's an example in the examples serializer
2. Two routes. 
3. If statement in the index route - this is harder because Ember would have to send you some property to use to determine if you should show them all or not, and I don't know how to do that off the top of my head.

Another option is to filter the images on the front end depending on the route. That might be a great option, actually. I rank it tied with 1.

**Comment by Sphilippe7** [comment]
so I added this to my photo serializer:

```
class PhotoSerializer < ActiveModel::Serializer
  attributes :id, :name, :category, :url, :user_id, :editable
  has_one :user

  def editable
    scope == object.user
  end
end
```

But I can't figure out where to put the if statement on my front end. I tried adding it to my your-photos route but it does not work. Nothing is showing on my app now. @raq929

**Comment by raq929** [comment]
Did you tell Ember about it in the photos model? 
Have you verified via curl that editable is showing up? 
Joel's code from #460 may be helpful. He was missing the serializer part but had the rest.

**Comment by Sphilippe7** [comment]
This is what is in my photo model:

```
class Photo < ActiveRecord::Base
  belongs_to :User
end
```

I have to make it identical to the Photo Serializer? @raq929

**Comment by raq929** [comment]
No, it should be ok. I'm not sure that User should be capitalized though. Check the examples model.

**Comment by Sphilippe7** [comment]
I changed it to lowercase and now my page has returned but I'm still seeing all photos in the your photos page @raq929

**Comment by Sphilippe7** [comment]
But on a brighter note, I cannot delete Ryan's Photos only my own 👍

**Comment by raq929** [comment]
OK, but do photos have an `editable` property? If yes, you need to deal with that on the front end, using something similar to the code in the issue I linked to.

**Comment by Sphilippe7** [comment]
when you ask if it has an editable property do you mean within that back end model? because it does not.

**Comment by raq929** [comment]
No, I mean, when you make a curl GET request to photos/, do the photos have an editable property.

**Comment by raq929** [comment]
Like this: 
```
{"products":[{"id":1,"before_photo_url":null,"description":"refurbished liquor cabinet - sanded, installed glass, repainted, new knobs","price":300,"after_photo_url":"http://imgur.com/HE35TDa","editable":true},
{"id":2,"before_photo_url":null,"description":"numbered kids dresser with new knobs, sanded, painted, stencil work","price":300,"after_photo_url":"http://imgur.com/9go65le","editable":true},{"id":4,"before_photo_url":null,"description":"living room table sanded and painted","price":250,"after_photo_url":null,"editable":false},
{"id":5,"before_photo_url":"http://imgur.com/77QFKdT","description":"living room table sanded and painted","price":250,"after_photo_url":null,"editable":false},
{"id":6,"before_photo_url":"http://imgur.com/77QFKdT","description":"living room table sanded and painted","price":250,"after_photo_url":"http://imgur.com/HE35TDa","editable":false},
{"id":7,"before_photo_url":"","description":"Bookshelf - rebuilt shelves, sanded, added chalkboard paint","price":0,"after_photo_url":null,"editable":false},
{"id":8,"before_photo_url":"","description":"wooden chest - replaced rotting wood, rebuilt drawers, installed new knowbs","price":400,"after_photo_url":null,"editable":false}]}
```

(From #426)

**Comment by Sphilippe7** [comment]
with the help of @payne-chris-r , we determined that my model on the front end did not have editable listed. My model now looks like this:

```
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  category: DS.attr('string'),
  url: DS.attr('string'),
  editable: DS.attr('boolean')
  // userId: DS.attr('integer')
});
```

And then the proper code I had to write in the route (for your-photos) is

```
{{#if photo.editable}}

{{/if}}
```

Thank you! @raq929
