### ISSUE TITLE
Clearing Forms on Submit

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#463]
I am trying to clear forms on submit and have tried a couple of different things. I haven't seen any closed issues on the matter either.
As a simple fix, I have transitioned back to the `/band` route but when you go back to a bands tasks, that form still has data in it. Some of the things I have tried

http://stackoverflow.com/questions/21242555/ember-js-how-to-clear-the-form-data-after-saving-the-record
http://stackoverflow.com/questions/23238860/how-can-clear-form-data-in-ember-js
http://jsfiddle.net/vine77/4pZub/

In both of those articles they set `controller` to `this` but it seems like I have already been doing this based off of much I use this.

So I guess here is everything?
task-list component which has the create form:
```html
<form {{action 'createTask' on='submit'}}>
{{input placeholder="Name (required)" value=Task.name}}
{{input placeholder="Due Date (required, YYYY-MM-DD)" value=Task.due_date}}
{{input placeholder="priority level (required, maximum of 9)" value=Task.priority}}
{{input  placeholder="details" value=Task.details}}
<button class="add-item">Add Task</button>
</form>
```

Its component:
```js
import Ember from 'ember';

export default Ember.Component.extend({
  Task: {
    name: null,
    due_date: null,
    priority: null,
    details: null,
    completed: false,
  },
  actions:{
    createTask(){
      let task = this.get('Task');
      task.band = this.get('band');
      this.sendAction('createTask', task);
    },
    toggleComplete(){
      console.log('done', this.get('Task'));
    },
    deleteTask(task){
      this.sendAction('deleteTask', task);
      console.log('second step of deleting', task);
    },
    editTask(task){
      this.sendAction('editTask', task);
    },
    completeTask(task){
      this.sendAction('completeTask', task);
    }
  }
});
```

That component is generated by the `band/tasks` template
```html
{{task-list band=model
            createTask='createTask'}}
```

Then its route
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model(params){
    return this.get('store').findRecord('band', params.band_id);
  },
  actions: {
    createTask(newTask){
      let task = this.get('store').createRecord('task', newTask);
      console.log(task);
      return task.save()
      .then(() => this.get('flashMessages').success('Task created, keep making working hard!'))
      .then(()=>{
        this.set('Task', '');
        this.$().find('input').focus();
      })
      .catch(() => {
        this.get('flashMessages')
        .danger('Oh No! Something is not quite right. Make sure you have filled out required fields with the right format');
        task.rollbackAttributes();
      });

    },
    editTask(task){
      this.transitionTo('tasks/edit', task);
    },
    deleteTask(task){
      return task.destroyRecord()
      .then(()=> task.rollbackAttributes());
    }
  },
});

```

So  this part:
```js
      .then(()=>{
        this.set('Task', '');
        this.$().find('input').focus();
      })
```
I have messed around with that a lot and pretty much every iteration either doesn't clear the form or doesn't clear the form **and** throws an error. I have tried `Task.name` to try to target that specific field but that generates an error in the sense that the promise chain goes to the `catch`. I have also tried removing the `.focus()` line but still nothing.

**Comment by raq929** [comment]
I would do it in the component right after sendAction. Something like `this.set('Task') = <your empty task object>`

**Comment by akradin** [comment]
bless you 🙌

Solution, in the component file instead:
`this.set('Task', '');`

And then got rid of the whole `.then` above
