### ISSUE TITLE
getting some weird behavior in chat-box when not signed in

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/capstone-project#464]
my chat-box isn't showing emails when a user isn't signed in. The console shows 401, unauthorized, but the backend shows a successful get request. Do I need to change something with permissions in the front end?

**Comment by raq929** [comment]
That seems... like what you say is happening might be different from what's actually happening. Are you sure you're talking to the server you think you're talking to?

**Comment by ioncrash** [comment]
oh... heh. Closing this until I can look closer
