### ISSUE TITLE
Need help determining if I need validation to check if something is code or not

### ISSUE THREAD

**Issue by joaufi** [ga-wdi-boston/capstone-project#467]
For my project I have a ZeroDay model that has a title, lang (which is the language it is supposed to be programmed in), and content. Content should be the actual code of the ZeroDay attack. I am storing it as a string. However, since User's can post these, I can see a potential for having non-code entries in the database (potential vandalism, it is a script kiddie site after all).

I can certainly research how I might run some sort of script that would check if something is code or not but I feel that might be outside of my ability to get this project done before 5pm. Definitely have it as a stretch goal though.

So, would this be necessary to meet requirements? If it is I might have to think of a project where User's post RandomText which has a title and content, haha.

**Comment by raq929** [comment]
I'm confused, because this seems unrelated to the chat app you presented.

**Comment by joaufi** [comment]
See the resolution of [Issue 458](https://github.com/ga-wdi-boston/capstone-project/issues/458). I'm doing a pivot project now. ¯\\\_(ツ)\_/¯

**Comment by gaand** [comment]
@joaufi If this is no longer an active issue, please close.  Thanks.

**Comment by joaufi** [comment]
@gaand I have yet to get an answer/resolution to my issue.

**Comment by joaufi** [comment]
Having passed the capstone project (woo!), it looks like I did not need to validate if what was entered into the ZeroDay content textarea. This feature is certainly something that interests me and I will look into how one might potentially do that; seems quite open-ended if we allow all programming languages.

Closing this as it was resolved due to finishing project.
