### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/capstone-project#469]
Followed the steps to deployment and I cannot get my page to load

**Comment by raq929** [comment]
Related to #466

**Comment by Sphilippe7** [comment]
So I changed my URL path to match the one on my repo, I ran the ember build, and I also went through the deployment repo and followed the steps. I made 5 attempts at doing the same thing and still have a blank screen when I try to view my deployed site link

**Comment by Sphilippe7** [comment]
In my environment file under config I have:

```

  if (environment === 'production') {
    ENV.rootUrl = '/RateMyPhotos-frontend';
    ENV.locationType = 'hash';
    ENV.apiHost = 'https://floating-escarpment-34212.herokuapp.com';
  }
```

at the bottom

**Comment by gaand** [comment]
Do you get any errors when pushing to github?

**Comment by raq929** [comment]
I think we likely have it fixed now... waiting for github to update.

**Comment by raq929** [comment]
OK, so in my test deployment site, https://raq929.github.io/test-ember-deployment/, the assets folder is a child of `test-ember-deployment`. But in Stanley's it's a sibling. Any ideas on how that could happen?

**Comment by Sphilippe7** [comment]
So the main problem was my spelling error. In my config file, I had "rootUrl =" the correct spelling is "rootURL =" . Spelling is VERY IMPORTANT. Copy and paste is highly suggested when going over any of these deployment guides!
