### ISSUE TITLE
Deploying to Heroku successful, but doesn't actually show up

### ISSUE THREAD

**Issue by HoldenMills** [ga-wdi-boston/capstone-project#47]
I have deployed to heroic using the commands

`git push heroku master`

`heroku run rake db:migrate`
`heroku run rake db:seed`

`heroku restart && heroku open`

Everything went through without an error, but when I go to my deployed page https://stormy-caverns-8878.herokuapp.com it tells me that the page cannot be found.

**Comment by HoldenMills** [comment]
_Update_ I had not updated my front end api url to point to my heroku link.  After doing that I am now getting this error;

XMLHttpRequest cannot load http://stormy-caverns-8878.herokuapp.com/register. The request was redirected to 'https://stormy-caverns-8878.herokuapp.com/register', which is disallowed for cross-origin requests that require preflight.

**Comment by gaand** [comment]
Trying changing the scheme from `http` to `https`.

**Comment by tdyer** [comment]
Was missing the head method from the CORS config in the app/application.rb file.
