### ISSUE TITLE
Getting 'undefined' in url bar

### ISSUE THREAD

**Issue by ielole** [ga-wdi-boston/capstone-project#470]
When I transfer to the view-state of a single achievement the url bar shows:

http://localhost:7165/goals/undefined/achievements/undefined

In my router.js file, I have this route:
```js
this.route('achievement', { path: 'goals/:goal_id/achievements/:achievement_id'});
```

If I try to change the path, then the achievements don't show up.

If I change where the route file is nest, then other aspects don't show up. Everything works fine in the app, but I would like for the url bar to show the correct path.

**Comment by ielole** [comment]
```hbs

<h3 class="goal-title">
  Goal: {{goal.title}}
  {{#link-to 'goal/update-goal' goal}}
    <button class="btn btn-xs btn-warning">Update Goal</button>
  {{/link-to}}
</h3>
<br>
<h6>
  <span class="start dates">Start Date: {{goal.startDate}}</span>
  <span class="end dates">End Date: {{goal.endDate}}</span>
</h6>

<span class="achievement-word"><h3>Achievements</h3></span>
<ul>
  <li class="achievements">
    {{#each goal.achievements as |achievement|}}
      {{goal-display/achievements-main achievement=achievement
                                        delete='deleteAchievement'}}
    {{/each}}
  </li>
</ul>

<div class="center">
  {{#link-to 'goal/new-achievement' goal}}
    <button class="btn btn-xs btn-secondary daily-add">Add A Daily Achievement</button>
  {{/link-to}}
</div>

```

**Comment by ielole** [comment]
```hbs
{{#link-to 'achievement' achievement}}
<div class="single-achievement">
{{achievement.log}}
</div>
{{/link-to}}

```

**Comment by gaand** [comment]
I think you need to explore nested routes to make this work.

**Comment by gaand** [comment]
@ielole Have you made any progress on this issue?

**Comment by gaand** [comment]
@ielole Has this been resolved?

**Comment by ielole** [comment]
No, it hasn't been resolved, I'm still working on it.

**Comment by gaand** [comment]
Okay.  If you need assistance, please ask.

**Comment by ielole** [comment]
So, I just generated an achievement route, adapter and model inside of the goal route, but I am still getting 'goals/undefined/achievements/undefined' in the url when I navigate to an individual achievement. I've been trying to figure out how to pass two parameters in a 'link-to' helper, but every time I try, I get this error:

EmberError code: undefined
description: undefined
fileName: undefined
lineNumber: undefined
message:
"Assertion Failed: You attempted to define a `{{link-to "goal/achievement"}}` but did not pass the parameters required for generating its dynamic segments. More context objects were passed than there are dynamic segments for the route: goal/achievement"

name: "Error"
number: undefined
stack: "Error↵    at assert (http://localhost:7165/assets/vendor.js:16268:13)↵    at Object.assert (http://localhost:7165/assets/vendor.js:27196:34)↵    at http://localhost:7165/assets/vendor.js:18524:23↵    at runInDebug (http://localhost:7165/assets/vendor.js:16381:5)↵    at Object.runInDebug (http://localhost:7165/assets/vendor.js:27220:38)↵    at Class.computeLinkToComponentHref (http://localhost:7165/assets/vendor.js:18509:19)↵    at ComputedPropertyPrototype.get (http://localhost:7165/assets/vendor.js:26852:28)↵    at Object.get (http://localhost:7165/assets/vendor.js:31759:19)↵    at RootPropertyReference.compute (http://localhost:7165/assets/vendor.js:24853:26)↵    at RootPropertyReference.value (http://localhost:7165/assets/vendor.js:24720:45)"
__proto__
:Error

This is my crazy looking router.js file:
```js
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
});

Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('about');
  this.route('goals');
  // this.route('goals.achievement', { path: 'goals/:goal_id/achievements/:achievement_id'});
  this.route('goals/new-goal');
  this.route('goal', { path: 'goals/:goal_id' }
  // , function() {
    // this.route('achievement', function() {
    //   this.route('update-achievement');
    // }); }
  );
  // this.route('goal/achievement', { path: 'goals/:goal_id/achievements' });
  this.route('goal/new-achievement', {path: 'goals/:goal_id/new-achievement'});
  this.route('goal/update-goal', {path: 'goals/:goal_id/update-goal'});
  this.route('goal/achievement', { path: 'goals/:goal_id/achievements/:achievement_id'});
  // this.route('achievement/update-achievement', { path: 'achievements/:achievement_id'});
  this.route('goal/achievement/update-achievement', { path: 'goals/:goal_id/achievements/:achievement_id/update-achievement'});
  this.route('achievements', {path: 'goals/:goal_id/achievements'});
  // this.route('achievements.new-achievement', {path: 'achievements/new-achievement'});
});

export default Router;
```

This is my goal-display/achievements-main/template.hbs file
```handlebars
{{#link-to 'goal/achievement' achievement goal}}
<div class="single-achievement">
{{achievement.log}}{{achievement.id}}
</div>
{{/link-to}}
{{goal}}
```
I've also attempted to use the goal params in the goals/achievement model hook without success.
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('achievement', params.achievement_id);
// return this.get('store').findRecord('goal', params.goal_id);
  },
  actions: {
    deleteAchievement (achievement) {
      achievement.destroyRecord();
      this.transitionTo('goals');
    },
  },
});
```
Every time I try to search for 'multiple params in link-to' or 'use parent model in nested route' or 'using a different model than the route you're in', I get results talking about controllers.

**Comment by gaand** [comment]
Those aren't actually nested routes.  Nested routes look like this:

```js
Router.map(function () {
  this.route('lists', function () {
    this.route('new');
  });
  this.route('list', { path: 'lists/:list_id' }, function () {
    this.route('edit');
  });
});
```

Then in the route you can use `modelFor` to set the goal: http://emberjs.com/api/classes/Ember.Route.html#method_modelFor
