### ISSUE TITLE
Bug in deployed site makes null objects

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/capstone-project#472]
I cannot replicate this issue in my local site. When I go to edit a favorite, hit cancel, and then use the browser back button I am taken to the edit favorites route for `Brooklyn Standards`. When I navigate to artwalks there is then a null artwalks object that isn't persisted in the back end or posted in the console but still appears in the interface.

**Comment by kiraamaa** [comment]
Locally, there is a flash message from this action that says "There was a problem" and then a null obejct is not created. I identified that this message is coming from `application/route.js`:
```js
error (reason) {
      let unauthorized = reason.errors && reason.errors.some((error) =>
        error.status === '401'
      );

      if (unauthorized) {
        this.get('flashMessages')
        .danger('You must be authenticated to access this page.');
        this.transitionTo('/sign-in');
      } else {
        this.get('flashMessages')
        .danger('There was a problemsshjsjshfjshjs. Please try again.');
      }
```

**Comment by kiraamaa** [comment]
Added if statement to artwalks/template.hbs and waiting for deployment to process.
``` js
  {{#each model as |artwalk|}}
  {{#if artwalk.title}}
    {{artwalk-walk/card artwalk=artwalk
                      edit='editArtwalk'
                      delete='deleteArtwalk'
                      createNewFavorite='createNewFavorite'}}
  {{/if}}
  {{/each}}
```

**Comment by gaand** [comment]
@kiraamaa Is this still an issue ❓ 

If not, please close.
