### ISSUE TITLE
Can't Add Band 

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#473]
This may be similar to the other issue I have open but I just discovered if you try to add a band using the return key it throws an error. Also, if you click to add, it works, but then you can't add subsequent bands. Tried `rollbackAttributes` and `willTransition`

**Comment by raq929** [comment]
Show us the code!
Also, I'm assuming you can add as many bands as you want via curl, yes?

**Comment by raq929** [comment]
And post the error please.

**Comment by akradin** [comment]
error
`desc = "Cannot call set with 'name' on an undefined object.", test = false`

component
```js
  actions: {
    newBand(){
      this.sendAction('newBand', this.get('Band'));
      this.set('Band', '');
    },
```

route
```js
    newBand(newBand){
      let band = this.get('store').createRecord('band', newBand);
      return band.save()
      .then(() => this.get('flashMessages').success('Band created, rock on'))
      .then(()=> band.rollbackAttributes())
      .catch(() => {
        this.get('flashMessages')
        .danger('Oh No! you need to add a name!');
      });
```

**Comment by akradin** [comment]
Yeah so this is an issue that is plaguing all of my code, every time you submit anything, anywhere, it destroys my entire application. If I submit a task, and then hit submit on the form again, it throws a debugger even though I have an error handler

**Comment by akradin** [comment]
solution - in component:
```js
    newBand(){
      let band = this.get('Band');
      this.set('Band', {});
      this.sendAction('newBand', band);

    },
```

**Comment by akradin** [comment]
Weird, this only a temporary fix. So If I  add a contact, then go back to bands, then back to contact, that form value is still there

**Comment by raq929** [comment]
Contact is a different form, isn't it?

**Comment by akradin** [comment]
Yes, but a similar issue as what we were experiencing before

**Comment by akradin** [comment]
Adding
`this.set('Band.name', '');`
 works for clearing forms and allowing the user to continue to write in the form after having submitted data. However, it also adds an unwanted Front End Validation. If you are creating a contact you would have 
```js
      this.set('Contact.name', '');
      this.set('Contact.phone_number', '');
      this.set('Contact.email', '');
      this.set('Contact.company', '');
      this.set('Contact.details', '');
```

But this makes it so a user can't leave a field blank which is should be allowed

**Comment by gaand** [comment]
I don't understand what you mean by "an unwanted Front End Validation" or why the code you pasted makes "a user can't leave a field blank" true.

**Comment by akradin** [comment]
Nevermind, solution above works as expected
