### ISSUE TITLE
Problems with my deployed site

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/capstone-project#474]
Images will not load and sign in/up functions not working

**Comment by raq929** [comment]
Images are related to #425.

Stanley is working on allowing the origin of his deployed site on the backend so that HTTP requests are accepted.

**Comment by raq929** [comment]
Or #193

**Comment by gaand** [comment]
@Sphilippe7 Is this issue resolved?

**Comment by gaand** [comment]
@Sphilippe7 Bump.
