### ISSUE TITLE
'Phantom' Data Not being Removed After Adding New Information

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#477]
The jist of this issue is that when data is deleted, it is deleted from the back end but not the front end. So, you click delete, and the content goes away and is removed from the database. But if you are to add a new resource, the deleted content appears again. A lot of what has been done in an attempt to resolve the issue is in [#461](https://github.com/ga-wdi-boston/capstone-project/issues/461) .

What is interesting is if you create a new resource and route of the page as a part of the create action, the issue persists but if you hit the back button and go forward, it doesn't happen.

**Comment by akradin** [comment]
Antony suggested I reference ember-resources. This issues does not occur in ember-resources and that code is set up pretty identical to mine.

**Comment by gaand** [comment]
Your route currently invokes multiple components.  I suggest changing it to invoke one that both iterates through the contacts and displays the new contact form. This is closer to what happens here https://github.com/ga-wdi-boston/ember-resources/blob/013/training/app/list/index/template.hbs

**Comment by akradin** [comment]
So when I do that I come up with this in the `contact-list` template:
```html
<form class="create-contact" {{action 'createContact' on='submit'}}>
<div class="contact-form">{{input placeholder="Name (required)" value=contact.name}}</div>
<div class="contact-form">{{input placeholder="Phone Number - 1234567890" value=contact.phone_number}}</div>
<div class="contact-form">{{input placeholder="email" value=contact.email}}</div>
<div class="contact-form">{{input placeholder="company" value=contact.company}}</div>
<div class="contact-form">{{input placeholder="details" value=contact.details}}</div>
  <div class="button-holder">
    <button class="add-item">Add Contact</button>
  </div>
</form>

{{#each band.contacts as |contact|}}
<div class="contact-info">{{contact.name}}</div>
{{contact-list/edit contact=model
                    delete='deleteContact'}}
{{/each}}
``` 
The component that calls is:
```html
<div class="button-wrapper">
<button class="edit" {{action 'edit'}}>Edit</button>
<button class="delete" {{action 'delete'}}>Delete</button>
</div>
```

And the both are rendered by the `band/contact` route
```html
{{contact-list band=model
              createContact='createContact'
              deleteContact='deleteContact'}}
```

This results in getting contact as undefined, so at the lowest level, which is the component that just contains the buttons, this action:
```js
    delete(){
      this.sendAction('delete',this.get('contact'));
      console.log("step 1 contact is",this.get('contact') );
    },
```
 is not being handled properly. I tried `this.get('band.contact')` but that didn't work either

**Comment by gaand** [comment]
Please post the rest of the contact-list component.js file.

**Comment by akradin** [comment]
Yup, here it is:
```js
import Ember from 'ember';

export default Ember.Component.extend({
  contact: {
    name: null,
    phone_number: null,
    email: null,
    company: null,
    details: null
  },
  actions :{
    createContact(){
      let contact = this.get('contact');
      contact.band = this.get('band');
      this.sendAction('createContact', contact);
      this.set('contact.name', '');
      this.set('contact.phone_number', '');
      this.set('contact.email', '');
      this.set('contact.company', '');
      this.set('contact.details', '');
    },
    deleteContact(contact){
      this.sendAction('deleteContact', contact);
      console.log("step two contact is", contact);
    },
    editContact(contact){
      this.sendAction('editContact', contact);
    }
  }
});
```

**Comment by gaand** [comment]
```diff
 {{#each band.contacts as |contact|}}
 <div class="contact-info">{{contact.name}}</div>
-{{contact-list/edit contact=model
+{{contact-list/edit contact=band
                     delete='deleteContact'}}
 {{/each}}
```

**Comment by akradin** [comment]
Hmmm that causes the 'delete' button to target the band it belongs to, not the contacts.
If you change that line to 
`{{contact-list/edit contact=band.contacts`
It targets the whole array of contacts and if you do just `band.contacts` then the button doesn't target anything

**Comment by gaand** [comment]
I didn't read it correctly, but then you didn't either 🤖 

```diff
 {{#each band.contacts as |contact|}}
 <div class="contact-info">{{contact.name}}</div>
-{{contact-list/edit contact=model
+{{contact-list/edit contact=contact
                     delete='deleteContact'}}
 {{/each}}
```

**Comment by akradin** [comment]
Ah-ha, that works...but he issue persists

**Comment by gaand** [comment]
Change `contact` to `newContact` where appropriate.

**Comment by akradin** [comment]
Not sure what you mean here, went ahead and changed it in the `contact-list` component  for `createContact()`
```js
    createContact(){
      let newContact = this.get('contact');
      newContact.band = this.get('band');
      this.sendAction('createContact', newContact);
      this.set('contact.name', '');
      this.set('contact.phone_number', '');
      this.set('contact.email', '');
      this.set('contact.company', '');
      this.set('contact.details', '');
    },
```

**Comment by gaand** [comment]
```diff
 export default Ember.Component.extend({
-  contact: {
+  newContact: {
    name: null,
```

And in the sets above.  This aligns more closely with ember resources items.

**Comment by akradin** [comment]
Ah, alright, yeah changed that as well...not really sure how naming conventions would cause this problem...

**Comment by gaand** [comment]
Me either, but if it's different than items, let's get it close to that to leave only substantive differences.

**Comment by akradin** [comment]
Fair enough, made those changes and compared with ember-resources and can't notice any other differences other than in ember resources we did this 
```js
      let data = this.get('newItem');
      data.list = this.get('list');
      this.sendAction('createItem', this.get('newItem'));
``` 
and I did this:
```js
      let newContact = this.get('newContact');
      newContact.band = this.get('band');
      this.sendAction('createContact', newContact);
```

**Comment by gaand** [comment]
I think `unless` might work:

```hbs
  {{#each list.items as |item|}}
  {{#unless item.isDeleted}}
    {{listr-list/item item=item
                      toggleDone='toggleItemDone'
                      delete='deleteItem'}}
  {{/unless}}
  {{/each}}
```

Likely related to https://github.com/emberjs/data/issues/3027

**Comment by akradin** [comment]
Sorry for swearing but holy shit it finally works. The saga is over (for now.)

```html
  {{#each band.contacts as |contact|}}
  {{#unless contact.isDeleted}}
    <div class="contact-name">{{contact.name}}</div>
    <div class="contact-number">{{contact.phone_number}}</div>
    <div class="contact-email">{{contact.email}}</div>
    <div class="contact-company">{{contact.company}}</div>
    <div class="contact-details">{{contact.details}}</div>
    <div class="contact-buttons">
      {{contact-list/edit contact=contact
                          delete='deleteContact'
                          edit='editContact'}}
    </div>
  {{/unless}}
  {{/each}}
```
