### ISSUE TITLE
How to access 2 different data tables in one handlebars template...?

### ISSUE THREAD

**Issue by akadane87** [ga-wdi-boston/capstone-project#478]
I can't figure out how to render 2 different data table's information in one handlebars template. The goal here is, with in my flash cards app, to have a list of pictures be generated a long with a list of names as options for a potential match to the picture. The problem is that my "pictures" data table is only made up of image urls and a corresponding name_id. While my "names" data table is made up of names and a corresponding picture_id. I cant remember why my pictures data table is NOT made up of urls AND names (strings) but someone much better at data relations than me told me it was a good idea .  If this is confusing please see attached screen shots of said tables in active record.
![names-table](https://cloud.githubusercontent.com/assets/12720136/22231766/51a824f0-e1b3-11e6-84f1-2d16ad6a0e56.png)
![pics-table](https://cloud.githubusercontent.com/assets/12720136/22231767/51a9f92e-e1b3-11e6-8f9c-eb9a18d41649.png)

https://github.com/akadane87/guess-that-dev-front    (dev is current branch)

Things I've tried:
2 {{each}} statements in one template - breaks it
2 separate handlebars templates jquery'd in the same element - .html called twice overwrites the previous one 
Lots of irrelevant stackoverflow 

Possible Solutions:
Another jquery method to append text besides .html -- will keep looking 
handlebars partials? -- but all the examples I've found seem to be referencing the same "parent" data object
new data column in pictures table? -- I'm hoping I dont have to take this route 
some sort of handlebars helper? -- not sure if its possible

I also have some questions about game state I was hoping to hash out:
	When should reset occur - End of Game? or Each time the image slider is turned?
	When does score update -- Same instances as above^

Thanks very much for your time and feedback.

**Comment by gaand** [comment]
1.  For a one-to-one relationship, `has_one` <=> `belongs_to` you only need one foreign key (having more actually may introduce problems).  So, `name_id` in pictures, and no `picture_id` in names.
2.  Did I suggest separating them?  I don't remember saying that, but if I did (or that's what you thought I said), how are you going to make use of this separation in the scoring?
3.  You can assemble a "parent" from the results of the gets by passing along the first result as a property of an object passed to a then executing the second get and then adding that result to the "parent".


@akadane87 Please open a separate issue for the game state question.  When you do, please expand on the rules you want to implement for the game.

**Comment by akadane87** [comment]
1.) Ok, I'll remove the ```picture_id``` column from the names table
2.) No I don't think you did - I just had a lot of different help setting up my rails database and it deviated quite a bit from the original blue print. Could you spare 10 minutes to have a discussion with how to refactor my data tables? --As far as scoring I was going to put correct answers into an empty array, but I don't think the table separation really helps me.
3.) I think I understand what you mean by combining the GET requests but the last piece I don't really understand how to implement that with a handlebars template. 

And yes I will absolutely open a separate game state issue once I'm there, but as of right now I'm feeling a bit hamstringed with not knowing how to proceed with the data tables.

**Comment by gaand** [comment]
I'm happy to set up a 1-on-1 after lunch, but please describe how you're going to use the list of names and pictures.  I remember talking with you about this, but it's been over a week, so a reminder would be useful.

**Comment by akadane87** [comment]
Resolved handlebars issue by implementing the second template into a div inside the first template

Got clarification on data table relations via 1:1

Thanks @gaand
