### ISSUE TITLE
CRUD resource question for Update -- Flashcards app

### ISSUE THREAD

**Issue by akadane87** [ga-wdi-boston/capstone-project#480]
Currently my app is behaving the way I want it to. I have a GET POST and DELETE call but no resource to UPDATE. I could potentially generate an additional column in a data table for a user to populate and UPDATE but I would rather not spend time adding meaningless functionality to my final project and instead either develop game stats further, get another cohort's names and pictures available for the game or work on stylings and adding an image carousel. 

Could I request a 1:1 on how to proceed? Maybe there is a piece of functionality that I could add that would require UPDATE that wouldn't be just adding UPDATING some text to meet requirements.

Thanks!

**Comment by gaand** [comment]
If you've added `attempt` to users, then starting a new attempt would be a `POST` incrementing `attempt` and answers would be a `PATCH` (updating the attempt by adding a row to the join table for the current nam/picture match guess).

Does that address your issue?

**Comment by akadane87** [comment]
Just to clarify I should...

1.) Change my existing POST to PATCH and no behavior is changed or added 
2.) Add an ```attempts``` column to the users table and write a similar POST that would increment in the same way

I did attempt the above and broke a whole bunch in the process. I'll formulate a more detailed comment of the errors in the morning.

**Comment by akadane87** [comment]
Hey Antony,

I'm fairly sure my interpretation of what you suggested is incorrect. Could you elaborate a bit further?

Also as a side note: If I created another table called ```attempts``` that received "changes" as a result of a POST to the ```responses``` table, would that fulfill the update requirement?

**Comment by gaand** [comment]
I thought something like below was your interpretation:

Start a new attempt: POST to /attempts and get back the incremented number from the User model.
Guess a name: PATCH to /guesses inserting a row with the attempt number, and the appropriate ids.
Get score for last attempt: GET to /score dn return correct our of total

Routes don't have to map controllers 1-to-1.  Controllers don't need to map to models 1-to-1.  Semantic names and routes are sometimes much better. 

I believe the above, with ath and ownership, meets expectations.

**Comment by akadane87** [comment]
Added ```attempts``` column to users table and ```attempts_id``` to responses. By ending a game the attempt and attempt_id column update
