### ISSUE TITLE
Question on Resubmission Requirements 

### ISSUE THREAD

**Issue by akadane87** [ga-wdi-boston/capstone-project#484]
I have a question on #2 of my resubmission requirements. 

2.Data unprotected by ownership (update and delete actions for responses resource).

The way my app is laid out, the user doesn't actually update or delete a "response" so there's no data to own there- those actions happen on the "attempts column" in the "users" table and the user does in fact own that data. The following is from the UsersController:
```
def destroyattempts
    puts "DESTROY attempts RUNNING"
    current_user.attempts = 0
    current_user.save
    Response.where({user_id:current_user.id}).destroy_all

    head :no_content
  end

  def postattempts
    current_user.attempts = current_user.attempts + 1
    current_user.save

    head :no_content
  end
```

https://github.com/akadane87/guess-that-dev-back/blob/master/app/controllers/users_controller.rb

This in combination with the actions that I have on my "response" resource covers my CRUD requirements as addressed in my previous issue "CRUD resource question for Update -- Flashcards app #480." I've slacked and emailed this concern as well to staff. Let me know if we're all on the same page here. Thanks

**Comment by gaand** [comment]
@akadane87 If this was addressed by my response to your e-mail, please post a resolution and close.  Thanks.

**Comment by akadane87** [comment]
For a client to own information then all of the available routes you make to that user on a given resource must have user owned information. I put user owned statements on the routes even tho they werent used.
