### ISSUE TITLE
Match `current user` to the another table's object's ID - 1 to 1

### ISSUE THREAD

**Issue by computingbets** [ga-wdi-boston/capstone-project#486]
I'm trying to have users that are signed in "vote" on if there are ads on tv. I’m chaining an api POST for votes to try to associate a current user vote to the vote id.  The POST of a vote to the db is onSignIn because I thought `current user` code on the back end would take care of any duplicate votes per user. The issue is every time I sign in with the same user, a new vote gets posted. How can I keep from duplicating votes? Is it a front end issue?

**Comment by payne-chris-r** [comment]
Things are very rarely "just taken care" of in development. If you want it done, you need to make sure it's done. I think I answered this in slack, no?
