### ISSUE TITLE
DB Column not Displayed in localhost3000

### ISSUE THREAD

**Issue by computingbets** [ga-wdi-boston/capstone-project#487]
I successfully POSTed an api call to "votes" table in my db. I did not post with data specified for "ads" true or false. However, when I check localhost, the only thing displayed is ID. I want to see the "ads" column of the votes table. Shouldn't ads be displayed as null?

**Comment by payne-chris-r** [comment]
Have you tried curl? What have you done to confirm it worked? Did rails issue a success message?

**Comment by computingbets** [comment]
i tried curling a post and it came back without an ID. I can confrim that localhost:3000/votes has objects without the "ads" boolean feature. The object in the console on the app's development says successful POST but no console.log(data), so no object gets returned.

**Comment by computingbets** [comment]
uh, i got an undefined object passed back. i'll try cURL'ing

**Comment by computingbets** [comment]
SOLUTION
The serializer needed ads params.
```
class VoteSerializer < ActiveModel::Serializer
  attributes :id, :ads
end
```
