### ISSUE TITLE
No Method Error

### ISSUE THREAD

**Issue by computingbets** [ga-wdi-boston/capstone-project#488]
i’m getting `NoMethodError (undefined method 'votes' for nil:NilClass)`. I used the example controller as a basis and set the params to public instead of private. Google results indicate nil:NilClass is a major component of this issue. However, 
``` 
def create
    #@vote = Vote.new(vote_params)
    # @vote.created_by = current_user.id
    @vote = current_user.votes.build(vote_params)

    if @vote.save
      render json: @vote, status: :created, location: @vote
    else
      render json: @vote.errors, status: :unprocessable_entity
    end
  end
```
is straight from example_controller.
After looking at previous issues, I have tried making `data` in the req with just the ads params as well as  a req with ads, channel_id, and user_id as the table all the tables columns are: ads, channel_id, and user_id.

**Comment by gaand** [comment]
Have you looked at the user model?

**Comment by payne-chris-r** [comment]
It's saying that the thing that you're calling `.votes` on is nil.

**Comment by computingbets** [comment]
yes. `has_many :votes`

**Comment by gaand** [comment]
So, what's `nil` then?  And why would it be `nil`?

**Comment by computingbets** [comment]
payne, does that have to do with `before_action :set_vote, only: [:show, :update, :destroy]` in the controller?

**Comment by computingbets** [comment]
my solutions are **nil**! Hiyooo!

**Comment by computingbets** [comment]
Wait a sec, because the create method needs an object? I'm passing in
```
curl --include --request POST http://localhost:3000/votes    --header "Content-Type: application/json"    --data '{
       "vote": {
            "id": 10,
            "channel_id": "1",
            "user_id": "3"
       }
   }'
```
Sure looks like an object to me : /

**Comment by payne-chris-r** [comment]
If you're calling `current_user.votes...` and it's saying "cannot read method of `nil`" then the thing you're calling `.votes` on is nil (i.e. current_user)

**Comment by computingbets** [comment]
```
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all

    render json: @votes
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
    render json: @vote
  end

  # POST /votes
  # POST /votes.json
  def create
    # @vote = Vote.new(vote_params)
    # @vote.created_by = current_user.id
    @vote = current_user.votes.build(vote_params)

    if @vote.save
      render json: @vote, status: :created, location: @vote
    else
      render json: @vote.errors, status: :unprocessable_entity
    end
  end

  def vote_params
    params[:vote]
  end
  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json

  def update
    @vote = Vote.find(params[:id])
    @vote.created_by = current_user.id
    if @vote.update(vote_params)
      head :no_content
    else
      render json: @vote.errors, status: :unprocessable_entity
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy

    head :no_content
  end

  private

  def set_vote
    @vote = Vote.find(params[:id])
  end
end
```
Controller... controlling only hack code atm! jk

**Comment by payne-chris-r** [comment]
That's not helpful. What's the problem? What's `nil`?

**Comment by computingbets** [comment]
`nil` is evidence that its not being called on an object or a syntax error.

**Comment by computingbets** [comment]
i suspect i'm missing a `do` somewhere.

**Comment by computingbets** [comment]
I was told to paste the controller into this issue by you, Chris.
I don't know what `nil` is and have not had luck googling it.
I don't know what this means: http://stackoverflow.com/questions/34377789/undefined-method-save-for-nilnilclass-on-controller

**Comment by payne-chris-r** [comment]
If you're calling `current_user.votes..`. and it's saying "cannot read method of nil" then the thing you're calling `.votes` on is `nil`. `current_user` is nil. Which means it's not defined. Which means you dont have access to it. In order to have access to it you need to inherit from a `ProtectedController`. Look at the very top of `ExamplesController`

**Comment by computingbets** [comment]
New error! Yay!
404 on this curlé, as the french would say:
```
curl --include --request POST http://localhost:3000/votes  --header "Content-Type: application/json"  --header "Authorization: Token token=BAhJIiViNTAxMjVlNmIxMzU3YjBkNzNiYjFlM2FkNjcyMDM1OAY6BkVG--a90a32565afbb1331cad435a767354a0483f14eb"  --data '{
   "vote": {
     "ads": "true",
     "channel_id": 1,
     "user_id": 3
   }
 }'
```
I tried this curl because the columns on the votes table has these three params
and a 404 parse error on:
```
curl --include --request POST http://localhost:3000/votes  --header "Content-Type: application/json"  --header "Authorization: Token token=BAhJIiViNTAxMjVlNmIxMzU3YjBkNzNiYjFlM2FkNjcyMDM1OAY6BkVG--a90a32565afbb1331cad435a767354a0483f14eb"  --data '{
   "vote": {
     "ads": "true",
   }
 }'
```
I tried this curl because putting localhost 3000 in the browser only displays vote ID and ads(null, atm)

**Comment by computingbets** [comment]
Is it my routes?
```
Rails.application.routes.draw do
  resources :votes, except: [:destroy]
  resources :channels # , except: [:new, :edit]
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
  get '/channels/:number' => 'channels#search'
  post '/votes' => 'votes#create' # this is what I added after last comment - same 404, I thought resources was sufficient since it worked for channels
end
```
running `rake routes` detailed i have a route for create
```
Prefix Verb   URI Pattern                    Controller#Action
       votes GET    /votes(.:format)               votes#index
             POST   /votes(.:format)               votes#create
```
all google results points to routes, but i'm stuck

**Comment by payne-chris-r** [comment]
You don't need that last night `post '/votes'...`. It's taken care of by the line `resources :votes, except: [:destroy[`

**Comment by payne-chris-r** [comment]
What is the 404 saying? What can't it find? What are the requirements for creating a vote?

**Comment by computingbets** [comment]
the 404 is saying it can't find a vote id. `[["id", nil]]`
i added user_id and channel_id to the serializer to match my curl, so creating requires a ads boolean, channel and user id. still getting a 404

**Comment by payne-chris-r** [comment]
If you don't send the channel id, then I won't know what channel to associate the vote with

**Comment by computingbets** [comment]
Thanks - I am sending a channel id. i am not sending a vote id. Does that matter to the ole' bleep blorpy (computer)?
