### ISSUE TITLE
Querying third party API from Rails back end

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/capstone-project#494]
Ideally, I would like to store only a reference to a datasets that I am trying to retrieve in my actual database. This means that when a user requests the dataset, I would send a requests to Boston's open data API to retrieve the data itself. After some research I am planning to use `OpenURI` to make these requests, since they are just simple GETs. However, I am not sure where I need to define the method for making the request. My instinct it to do it in the model, but the controller could also make sense. When I try to do it in the Model like this:

```rb
# frozen_string_literal: true
require 'open-uri'

class Dataset < ApplicationRecord
  def boston_dataset
    'https://data.boston.gov/api/action/datastore_search?resource_id='
  end

  def get_data(resource_id)
    url = "#{boston_dataset}#{resource_id}"
    buffer = open(url)
    buffer
  end
end
```
And test in the rails console with `Dataset.get_data('long id string')` I get the following NoMethodError:

```
NoMethodError: undefined method `get_data' for Dataset (call 'Dataset.connection' to establish a connection):Class
Did you mean?  get_callbacks
from /home/samuel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/dynamic_matchers.rb:21:in `method_missing'
```

Is this simply because I have not instantiated a Dataset? Should I just define a method on the controller to make the request instead of on the model? I have tester using `open-uri` to make requests in pry, so I know that it is possible, I'm just not sure I'm doing it in the right place.

Alternatively, is this going to just simply be too complicated? Should I just store csvs on the server and open those? That is my backup plan if by noon tomorrow I am not in a place where this is done or close to being done.

**Comment by samordonez** [comment]
I have to leave this until tonight, but I plan to try defining this on the controller instead and will update the issue once I have.

**Comment by raq929** [comment]
I like the idea of using the API, I agree with defining it on the controller. Do you need a model for this, or are you just passing data on to the front end?

**Comment by samordonez** [comment]
Currentky there is a model that is storing some information about the data and it's id on the third party api, which is a long hexadecimal string so it seems bad to me to make users find and type that. I guess I could just store those ids on the front end though, since for now I am heavily limiting the datasets available.

**Comment by jrhorn424** [comment]
This is definitely a model concern, but I don't see anything that says this needs to be backed by a database table.

EDIT: I take it back. Your comment came in at the same time.

**Comment by jrhorn424** [comment]
> there is a model that is storing some information about the data and it's id on the third party api
> which is a long hexadecimal string so it seems bad to me to make users find and type that. 

Yep. That's useful to "store" in some way.

>I guess I could just store those ids on the front end though, since for now I am heavily limiting the datasets available.

Ew (client). If you're heavily limiting datasets available, just store a model with a `url` attribute by using your `seeds.rb` file. That's pretty much the definition of a seed.

**Comment by samordonez** [comment]
So ti clarify, should I just store the url serverside and make the call to the third party from my front end, at least for now?

**Comment by gaand** [comment]
Not if it the API requires a token, key, etc.

Never get data in a controller.  Always get it from a model.

Also, once you meet requirements, you might consider caching the data.

**Comment by samordonez** [comment]
It is an open data API so GET requests at least don't require a token. However I probably don't want to send the entire spreadsheet to the client since it will only be using a portion of it, so I'll probably do some processing server side and send back only the relevant columns. I'll try this tonight and update.

**Comment by samordonez** [comment]
with `require 'open-uri'`, the following is now working.

```rb
  def retrieve_data
    url = "#{boston_dataset}#{resource}"
    buffer = open(url)
    buffer.each do |l|
      puts l
    end
  end
```
I'm not sure why it wasn't before, but since the only difference is that this time I used seed data, I suspect it was due to me trying to call it on the Class itself rather than an instance of it the first time I tested.

**Comment by samordonez** [comment]
Obviously I'm going to do something other than `puts`ing the data, but since this issue was specifically about getting said data, I'm closing.
