### ISSUE TITLE
Posts for sign-up are not going through

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/capstone-project#497]
I am trying to get the auth stuff working before doing the repo crud files, but my sign-up button is not making the post request properly. I am getting the following error in my backend server: 
```
2017-03-26 14:53:38 -0400: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
2017-03-26 14:53:38 -0400: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.7.0 Snowy Sagebrush", "GATEWAY_INTERFACE"=>"CGI/1.2"}
```

But I have not touched the backend yet, because this stuff was taken care of for us. I believe this error means that the data is not properly formatted to make the request, but I don't know what I should do to fix this.

**Comment by dsweetser** [comment]
@alexkarasik I was having some issues with my backend that were fixed with a db:migrate.  I'd recommend trying that (and heroku migrate too, although I can't remember that command off the top of my head).

**Comment by alexkarasik** [comment]
Thanks Dan, I thought that was the issue at one point, but I tried that and it did not work unfortunately.

**Comment by raq929** [comment]
Please post the code you're running to make the requests.

**Comment by alexkarasik** [comment]
Here is my API request:
```
const signUp = function(data) {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data,
  });
};
```
And this is the sign-up back end but I haven't touched it, so I don't know why I should be having this issue:
```
  def signup
    user = User.create(user_creds)
    if user.valid?
      render json: user, status: :created
    else
      render json: user.errors, status: :bad_request
    end
  end
```

**Comment by bernardlee** [comment]
What does `data` look like when you're sending the request?

**Comment by raq929** [comment]
What do you see in the network tab for the request?

**Comment by alexkarasik** [comment]
At the moment, I am getting an error from another separate function. Once I get that fixed, I'll get back to you on the data.

**Comment by alexkarasik** [comment]
The status just says (failed). In my console, the error says 
```
jquery.js:9566 POST https://localhost:4741/sign-up net::ERR_CONNECTION_REFUSED
```
So I think something is wrong with the way it is communicating to the backend, but I checked my config files over and over and see nothing wrong. 
This is my config.js file:
```
'use strict';

const config = {
  apiOrigins: {
    production: 'https://git.heroku.com/sheltered-lake-27953.git',
    development: 'https://localhost:4741'
  },
};

module.exports = config;
```

**Comment by bernardlee** [comment]
Look closely at the `config.js` file.

**Comment by alexkarasik** [comment]
I think my production link was not correct, butI changed it and am still getting the network error.
Here is what is is now:
```
'use strict';

const config = {
  apiOrigins: {
    development: 'https://localhost:4741',
    production: 'https://sheltered-lake-27953.herokuapp.com/'
  }
};

module.exports = config;
```

**Comment by bernardlee** [comment]
https://github.com/ga-wdi-boston/capstone-project/issues/497#issuecomment-289470454

**Comment by alexkarasik** [comment]
I don't know what that is in reference to.

**Comment by bernardlee** [comment]
Your API request from the front end.

**Comment by alexkarasik** [comment]
So local host was set to 4741 and not 7165, so I fixed that and am no longer getting the network connection error.
I am now getting a 404 error however when I try to sign-up. 
Here is the data from Headers in the network tab:
```
credentials[email]:trep
credentials[password]:t
credentials[password_confirmation]:t
submit:Sign up!
```
I have checked the API request many times against other project and don't see anything wrong with it.

**Comment by raq929** [comment]
Your backend server is on 4741. It should be 4741. 
Do you have a working curl request for signup? 

I'm interested in the `request` part of the network tab, i.e., what are you actually sending. 

Please answer Bernard's question by console.logging data before sending it.

**Comment by alexkarasik** [comment]
It was the wrong port as you said. It's working now. Thanks
