### ISSUE TITLE
Submit form, page regresh

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/capstone-project#498]
Once again these submit forms are just refreshing the page.

The div in the index exists when the page loads. The click handler uses that div. It points to the correct function and has the event.preventdefault.

Handlebars:
```handlebars
<form class="create">
    <input class="clear-input" type="text" name="my_gears[quantity]" value="" placeholder="Quantity">
    <input class="clear-input" type="text" name="my_gears[name]" value="" placeholder="Name">
    <input type="submit" name="submit" value="Submit">
</form>
```

Index.html
```html
  <div class="gear-table">
  </div>
```

Clickhandler:
```javascript
  $('.gear-table').on('submit', '.create', onCreate)
```

Event function:
```javascript
const onCreate = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  api.create(data)
    .then(ui.createSuccess)
    .then(onIndex)
    .catch(ui.createFailure)
}
```

Goal: when user clicks on submit, the onCreate function is called and the page does not refresh.

**Comment by gaand** [comment]
`.gear-table` is not a form so I don't think it has a `submit` event.

**Comment by doremaxime** [comment]
Whoops, did not have the addhandlers in the on doc ready.

added in index.js:
```javascript
$(() => {
  events.addHandlers()
})
```
