### ISSUE TITLE
deploying one page app and visual question on my views

### ISSUE THREAD

**Issue by gracenjambi** [ga-wdi-boston/capstone-project#50]
Good morning,

I have an app that uses views. Since this will be one repository, where should I deploy to gh-pages or heroku?

I have some quick questions on views. I have the views working but trying to make sure I use the <% %> and <%= %> tags correctly with my bootstrap.

**Comment by srhoulam** [comment]
This is now about how to link a custom (additional) stylesheet in Rails Views.

**Comment by gaand** [comment]
If you're rendering views on the server then heroku.

`<%=` adds text to the view.  `<%` just executes the ruby code.

**Comment by gracenjambi** [comment]
so i have tried adding it to application.html.erb but the minute i add the tags below I get an error when I remove the app works fine.

<%= javascript_include_tag "custom" %>
<%= stylesheet_link_tag "style" %>

**Comment by gaand** [comment]
Do you have a `app/assets/stylesheets/style.css` file?  Do you have a `app/assets/javascripts/custom.js` file?

If you do, what error do you get?

**Comment by gracenjambi** [comment]
yes I do the path is as above.

When I put  the links back i get

Sprockets::Rails::Helper::AssetFilteredError in Products#index
Showing /home/grace/WDI/project4/project4Backend/benjyapp/app/views/layouts/application.html.erb where line #7 raised:

Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( custom.js )` to `config/initializers/assets.rb` and restart your server
Extracted source (around line #7):
5
6
7
8
9
10

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "custom" %>
  <%= stylesheet_link_tag "style" %>

  <%= csrf_meta_tags %>

Rails.root: /home/grace/WDI/project4/project4Backend/benjyapp

Application Trace | Framework Trace | Full Trace
app/views/layouts/application.html.erb:7:in `_app_views_layouts_application_html_erb__1712618118774524704_69843385290800'

**Comment by gaand** [comment]
I think you just need to follow the instructions from the error message, i.e.

add Rails.application.config.assets.precompile += %w( custom.js ) to config/initializers/assets.rb and restart your server

**Comment by gracenjambi** [comment]
Thank you it worked. I was adding custom.js and forgetting the style.css I needed to add both to config/initializers/assets.rb

Rails.application.config.assets.precompile += %w( style.css )
Rails.application.config.assets.precompile += %w( custom.js )
