### ISSUE TITLE
Index error with deployed link

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/capstone-project#500]
With the localhost I can sign up/in and it automatically indexes all the resources.

However, when on the deployed link, i can sign-up/in, but the index action does not work and gives the error: ```GET https://capstone-project-gear.herokuapp.com//my_gears 404 (Not Found)```

I find this strange knowing that the auth works in deployed link and that the index works with the localhost...

API:
```javascript
const index = function () {
  return $.ajax({
    url: config.apiOrigin + '/my_gears',
    method: 'GET',
    headers: {
      Authorization: `Token token=${store.user.token}`
    }
  })
}
```

Deployed link: https://doremaxime.github.io/gear-frontend/

**Comment by jordanallain** [comment]
`GET https://capstone-project-gear.herokuapp.com//my_gears 404 (Not Found)`

looks like you have a double slash after .com, you must have it at the end of `config.apiOrigin` and it starts the string `'/my_gears'`

**Comment by doremaxime** [comment]
The reason I have the extra ```/``` is because it works on my second project.
I tried it without the extra ```/``` but it's the same result..

**Comment by raq929** [comment]
Did you migrate on heroku?

**Comment by doremaxime** [comment]
Can you help me understand how it may help?
I wonder because sign up and sign work and that resource get CRUDed.
Plus I can CRUD on my other resource on the CLI...

**Comment by doremaxime** [comment]
I have now merged my feature branch to master and pushed master.
I then pushed heroku and ran db:migrate.
However, I now get a 500 error for sign-up/in:
![screen shot 2017-03-27 at 12 16 30 pm](https://cloud.githubusercontent.com/assets/24608045/24366683/d3e40a64-12e7-11e7-9e23-5bf3a03ad4f0.png)
I heard github pages was having issues today, could it be due to that?

**Comment by raq929** [comment]
Nope. This is heroku.

So, this works locally on your master branch, yes? And when you make the same `curl` request to heroku, it fails?

If yes, make the request again, and type `heroku logs` to look at the logs. Hopefully that will tell you what's going on.
https://devcenter.heroku.com/articles/logging

**Comment by doremaxime** [comment]
Yes, on master branch i can sign up/in using heroku as the API.
But not on the deployed link.

From what i can understand in the heroku logs is
```ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist```
But how come? users exists since i'm doing it through the CLI.

**Comment by raq929** [comment]
It's talking about the _relation_ users, not the `users` table. Did you add a relationship with users?

Wait, I'm not clear what's happening. 
1. Can you make a curl request to your heroku server successfully?
2. Can you make a successful request from your local client?
3. Can you make a successful request from your deployed client?

Whatever you can do successfully, figure out what's different about that request and the other ones. I'd use the network tab to look closely at the request you're sending.

**Comment by doremaxime** [comment]
Yes, there is a relation. I tested it and a user can only CRUD on her own resources.

1. Yes, CLI:

```sh
API="https://capstone-project-gear.herokuapp.com/" EMAIL="n@n" PASSWORD="n" sh scripts/sign-in.sh 

HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"e607ee0e2d81361a5944919e5e456fdc"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: db16c15a-7bf6-497e-ab58-c0bf1d2f125a
X-Runtime: 0.201466
Vary: Origin
Transfer-Encoding: chunked
```
```md
{"user":{"id":8,"email":"n@n","token":"BAhJIiU3MzQ3Y2U1ODU4MDNhMDM1NGU5NzA5MWFhZTdjMmYyZAY6BkVG--d2c76b51ca932588e243638d0d9b19bda0d8bbed"}}
```

2. Yes
![screen shot 2017-03-27 at 2 41 00 pm](https://cloud.githubusercontent.com/assets/24608045/24372280/73686ff4-12fb-11e7-9bc9-e6a97ae8caa6.png)

3. No
![screen shot 2017-03-27 at 2 42 16 pm](https://cloud.githubusercontent.com/assets/24608045/24372326/9c4c1344-12fb-11e7-8816-cf351383a960.png)
I had looked in the network tab but I did not find any hints.
![screen shot 2017-03-27 at 2 42 51 pm](https://cloud.githubusercontent.com/assets/24608045/24372366/bcb7ee14-12fb-11e7-8c10-a50730f2bc50.png)
![screen shot 2017-03-27 at 2 43 04 pm](https://cloud.githubusercontent.com/assets/24608045/24372369/be291bf6-12fb-11e7-92fd-22c030fdddac.png)

**Comment by doremaxime** [comment]
I've taken out the extra ```/``` again in the config file and it does not make a difference (same 500 error)

**Comment by raq929** [comment]
Come see me in classroom 4 in 20 minutes.

**Comment by doremaxime** [comment]
The migration command I had used was:
```
heroku run rake db:migrate VERSION=0
heroku run rake db:migrate db:seed db:examples
```
However, still not working, Rachel said to try ```heroku run bin/rake db:migrate``` which worked!

Thank you again Rachel!
