### ISSUE TITLE
One on One to talk about Ember planning?

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/capstone-project#501]
Monday preferable? I just want to make sure I'm understanding components right for my project.

**Comment by raq929** [comment]
I got the lowdown from Jeff. I'm in Comm ave and can talk now.

**Comment by laurpaik-zz** [comment]
We discussed having an adapter that uses a serializer to convert the Ember object into a regular object that my back-end would expect, similar to [what we did in Listr-list](https://github.com/laurpaik/ember-resources/blob/training/app/adapters/item.js).

We also discussed having just one component for profile-create rather than four separate ones for each form; that way, I can just reuse that component if I want users to be able to update their profiles.

In terms of news-feed, we discussed how to make the front-end path (/news-feed) point to the correct path on the api (/couchposts) in the route:
```js
route('news-feed', { path: '/couchposts' })
```
