### ISSUE TITLE
One-on-One for Scoping and Ember Approach

### ISSUE THREAD

**Issue by cshea93** [ga-wdi-boston/capstone-project#502]
I was hoping to set up a time to meet with someone regarding project scoping and checking in on a few questions I had regarding ember. Anytime works!

**Comment by raq929** [comment]
Come by Comm Ave @ 10 am plz.

**Comment by raq929** [comment]
Please link to your ERD, wireframes and user stories.

**Comment by cshea93** [comment]
Went over ERD's and decided that learning ember would be best accomplished this week, so I will go with ember for my front-end. 

http://i.imgur.com/ecllvpO.jpg

http://i.imgur.com/nI2fd9v.jpg

http://i.imgur.com/zQT4gXY.jpg
