### ISSUE TITLE
One-on-One for Ember Planning

### ISSUE THREAD

**Issue by cob0910** [ga-wdi-boston/capstone-project#503]
Could I please meet with someone to discuss my app's structure and how to approach it for ember?

**Comment by raq929** [comment]
Please link to ERD, wireframes, and user stories. Once that's done, come by Comm ave @ 10:20 am

**Comment by cob0910** [comment]
https://github.com/cathyob/bundleUpServer - ERD
https://github.com/cathyob/bundleUP/tree/develop - User stories and wireframe

**Comment by cob0910** [comment]
Discussed diagram and app structure

![ember diagram](https://cloud.githubusercontent.com/assets/24627406/24362051/937bae2c-12d9-11e7-8857-fb8ddffd3cb5.png)


![rachel's notes](https://cloud.githubusercontent.com/assets/24627406/24362018/7ad8edc6-12d9-11e7-8a8f-5d2deca829e5.jpg)
