### ISSUE TITLE
1-1 for project planning

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/capstone-project#504]
I just want to discuss my project idea and make sure that it's acceptable for a capstone project

**Comment by raq929** [comment]
Awesome. Please post wireframes, ERD and user stories. Come by Comm Ave at 10:40

**Comment by ggabrakadabra** [comment]
https://github.com/ggwilliams/pictures-app-client/tree/auth

these are my user stories, erd, wireframe atm

**Comment by raq929** [comment]
Thanks!

**Comment by ggabrakadabra** [comment]
Talked about adding a news feed and a feature that will alert the user if another user comments on their favorite picture
