### ISSUE TITLE
React Deployment

### ISSUE THREAD

**Issue by ddobson** [ga-wdi-boston/capstone-project#505]
I'm building my client app with React. I would like to have a 1-1 to make sure there aren't any gotchas I should be aware of.

**Comment by payne-chris-r** [comment]
I think @danman01 and @raq929 are the only two here with any sort of React experience... I'll reach out to them.

**Comment by raq929** [comment]
File name for components _must_ start with a capital letter. No really. Guh.

Please post wireframes, user stories & ERD and we can chat more.

**Comment by bernardlee** [comment]
I've built some small and simple applications in React as well, but Rachel and Danny probably know more.

**Comment by raq929** [comment]
I know React/Redux, so I've actually never touched React's state. I can help with things like component hooks and such, but for state, we used Redux's store exclusively.

**Comment by ddobson** [comment]
Thanks all. @danman01 is going to meet with me this afternoon about deployment. I'm going to change this issue to focus just on deployment for now.

**Comment by danman01** [comment]
Closing this issue. @ddobson is going to look into Github Pages. We also discussed Surge and Heroku. Links: 
GH Pages & Surge: https://medium.freecodecamp.com/surge-vs-github-pages-deploying-a-create-react-app-project-c0ecbf317089 
heroku: https://blog.heroku.com/deploying-react-with-zero-configuration 
heroku env variables: https://devcenter.heroku.com/articles/config-
