### ISSUE TITLE
1-1 for project planning

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/capstone-project#506]
I plan on making a web crawler to find all the meet-ups that have free beer in Boston.
I plan on making the app using Python.  I am in the process of learning Python and am having trouble with:
1. the installation
2. making an ERD with what I want to .
3. best practices on learning a new language on my own.
Part of my project is to stop "learning how to think like" a developer and to ACT as a developer.
thank you.

**Comment by raq929** [comment]
We unfortunately cannot support you with Python. There is no one on our team who has used Python as a JSON API. (I've used Django serving HTML, but not otherwise.)

**Comment by Soboscott** [comment]
okee dokee

**Comment by Soboscott** [comment]
How about help with the ERD?

**Comment by raq929** [comment]
Yes, we can help with that. Will schedule soon.

**Comment by raq929** [comment]
Please post your user stories and an attempt at an ERD so we can talk it over.

**Comment by Soboscott** [comment]
https://docs.google.com/document/d/1J5CPg7aya5Z2bQJOOLLYBeD6wak0nIcZ6z9bDRu-N8o/edit

**Comment by raq929** [comment]
Give me permission to view, please!

**Comment by bernardlee** [comment]
I can meet with you.

**Comment by Soboscott** [comment]
Thanks Bernard

**Comment by raq929** [comment]
Please comment with what you met about and close the issue.

**Comment by Soboscott** [comment]
Bernard and I discussed how to go about getting a backend that will work with Python.  Django was what was brought up.  after learning about Python, I am going to research Django and how to set up the back end.  We discussed wether or not to use a web crawler and if I do which one to choose based on what I want to pull out of the API.
