### ISSUE TITLE
1-on-1 for Scoping and planning project

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/capstone-project#507]
Can I meet with someone today to talk about my project using rails and ember.

**Comment by raq929** [comment]
Please post wireframes, ERD, and user stories.

**Comment by AshlenPrice** [comment]
![image](https://cloud.githubusercontent.com/assets/24688275/24362151/e6d8f926-12d9-11e7-9aa0-f5e1f64c5b3f.png)

## User Stories

  As a guest I want to:
    - Visit KitchnListr to view available kitchens to rent.
    - Create an account/ sign-in to list a kitchen I own for rent.
    - Create an account/sign-in to review a kitchen I have rented.


  As a Kitch'n Owner I want to:
    - Create a Kitch'n listing.
    - Upload pictures of my Kitch'n.
    - Edit my listing and its data.
    - Remove my Kitch'n listing
    - View my ratings/reviews
    - Change my password.
    - be able to log out.

  As a Chef I want to:
    - Create a review and rate Kitch'ns I've rented.
    - Change/Edit the reviews I've written.
    - Delete My reviews/ratings.
    - Add a Kitch'n to my favorites
    - Schedule/Reserve a kitch'n slot.
    - Add pictures of what I've cooked.
    - Change my password.
    - be able to log out.

**Comment by raq929** [comment]
I'm in classroom 4.

**Comment by AshlenPrice** [comment]
Went over questions in regards to profile model. 
Will try implementing [this](http://api.rubyonrails.org/classes/ActiveRecord/Enum.html). To implement roles for my users. 

My model should look like this
```rb class Profile role: {chef: 0, owner: 1}```
