### ISSUE TITLE
One on One request for Ember overview

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/capstone-project#508]
I know there are a lot of requests for these, but today I am going to start working with Ember and want to make sure that my understanding of the structure of routes and components is not flawed in a way that will overcomplicate my project. I think I know the components I need, but I would appreciate the chance to talk to somebody and go over my planning.

**Comment by payne-chris-r** [comment]
I got you, b.

**Comment by samordonez** [comment]
This one on one has happened.
