### ISSUE TITLE
one-on-one project review request

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/capstone-project#509]
I would like to go over my ERD's and wireframes to get on track as soon as possible.

Thanks

**Comment by bernardlee** [comment]
Can you post or link them here?

**Comment by alexkarasik** [comment]
Wireframe:
https://i.imgur.com/ebf3nJu.jpg 
ERD:
https://i.imgur.com/nNY0FIX.jpg

**Comment by bernardlee** [comment]
Meet me in the student lounge.

**Comment by alexkarasik** [comment]
Bernard just met with me. Thanks
