### ISSUE TITLE
One on one ERD for EzSpeaky Web App

### ISSUE THREAD

**Issue by s0phi4** [ga-wdi-boston/capstone-project#510]
Good morning!

[README](https://github.com/yenpraja610/ezspeaky/tree/home-therapies)
Can I have a one on one about my ERD. Here is the link to my possible ERDs. 
![file mar 27 10 19 42 am](https://cloud.githubusercontent.com/assets/16325294/24361119/1f5d330a-12d7-11e7-9eb8-4f1797217dcb.jpeg)
![file mar 27 10 20 16 am](https://cloud.githubusercontent.com/assets/16325294/24361118/1f5b5238-12d7-11e7-8aa0-b1ca36db057d.jpeg)

Question:

In my app I provide the speech therapy types and the videos that correspond to each therapy type. Users are not able to create nor delete therapy types nor videos. The only CRUD allowed to users is on comments. I am confused about how to set up the relationships when the user can only CRUD on comments; therapies and videos belong to all users. 

App front-end Ember Images below:

<img width="1402" alt="screen shot 2017-03-27 at 10 15 17 am" src="https://cloud.githubusercontent.com/assets/16325294/24360941/a5f359ae-12d6-11e7-9534-c908b60a2842.png">
<img width="1382" alt="screen shot 2017-03-27 at 10 15 32 am" src="https://cloud.githubusercontent.com/assets/16325294/24360942/a5f9aeda-12d6-11e7-82f4-ade494f10437.png">

![file mar 26 10 47 52 pm](https://cloud.githubusercontent.com/assets/16325294/24361419/f2a2d97c-12d7-11e7-8870-e72499121d7b.jpeg)

**Comment by payne-chris-r** [comment]
Can users comment on Therapies AND Videos? Or just on one?

**Comment by payne-chris-r** [comment]
Are there multiple videos for each therapy?

**Comment by bernardlee** [comment]
Meet me in the student lounge.

**Comment by s0phi4** [comment]
All set! Thanks! @bernardlee  
@payne-chris-r  User can only comment on therapies so, it is 
* user has many comments and comments belong to user.
* Therapy has many comments and comments belong to therapy
* Therapy has many videos, videos belong to therapy. 

Comments has 2 foreign keys and is a join table!

Thanks!

Yen
