### ISSUE TITLE
1-1 request

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/capstone-project#511]
Need help planning the ember structure.

ERD:
![erd](https://cloud.githubusercontent.com/assets/24608045/24362885/287e5e82-12dc-11e7-9b34-70ee60abab62.JPG)

Wireframe:
![img_1828](https://cloud.githubusercontent.com/assets/24608045/24362923/40907316-12dc-11e7-9b75-a8e8ec360fc9.JPG)

Will have a link (Gear) in the nav bar that will show the user's gear. 
Within that view will also be from to add/edit/delete gear.

**Comment by raq929** [comment]
Classroom 4!

**Comment by doremaxime** [comment]
![wrieframe](https://cloud.githubusercontent.com/assets/24608045/24413058/50c229d8-13a8-11e7-9679-b7fb89e903bf.JPG)

**Comment by jrhorn424** [comment]
How are these upside down?

**Comment by jrhorn424** [comment]
Fix when you can. Thanks @doremaxime!

**Comment by doremaxime** [comment]
Yeah I don't understand either, they are normal on my computer, sometimes pictures on github get put upside down. Same for my READMEs... i'm not finding any rotate icons or buttons
