### ISSUE TITLE
Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/capstone-project#512]
I'm trying to make a call to an api but I'm getting this error in the console.

```
Uncaught SyntaxError:  sounds?q=apollo&api_key=T9Rfu2Fl6lIsh6xAlOGq3fKH9q29wtvjvjy1d8la&json_callback=jQuery32101282495788…:1
Unexpected token :
```

but, in the network tab, the get request says 200 ok and I'm getting a response back.

this is my api function 

```
const searchSoundsApi = function () {
  const searchText = $('#search-box').val()
  const apiKey = 'T9Rfu2Fl6lIsh6xAlOGq3fKH9q29wtvjvjy1d8la'
  const soundUrl = 'https://api.nasa.gov/planetary/sounds?'
  $.ajax({
    url: `${soundUrl}q=${searchText}&api_key=${apiKey}`,
    dataType: 'JSONP',
    // crossDomain: true,
    jsonp: 'json_callback',
    method: 'GET',
    success: function (result) {
      console.log('sound results', result)
      // for (let i = 0; i < result.results.length; i++) {
      //   const singleSearchResult = showSoundsTemplate(result.results[i])
      //   $('.single-search-result-sounds').append(singleSearchResult)
      // }
    }
  })
}
```

I'm just trying to console log the results so I can create the handlebars file for it.

**Comment by raq929** [comment]
If you're getting a response back, the syntax error is likely happening somewhere after the request comes back.

**Comment by raq929** [comment]
Run `grunt nag`; it should tell you where the error is.

**Comment by ggabrakadabra** [comment]
grunt nag didn't show me any errors in that function

**Comment by raq929** [comment]
Right, because your error probably isn't in that function. If it were there, the AJAX request wouldn't get made. Fix all your `grunt nag` errors. I'd be surprised if that doesn't fix it. (You can run `grunt make-standard` if it's yelling at you about semicolons.)

**Comment by ggabrakadabra** [comment]
the only errors I am getting in the file after running grunt nag is 

```
/Users/Gabrakadabra/wdi/pictures-app-client/assets/scripts/crud/events.js
   45:28  error  Expected '===' and instead saw '=='  eqeqeq
   80:33  error  Expected '===' and instead saw '=='  eqeqeq
  146:29  error  Expected '===' and instead saw '=='  eqeqeq
```

but I need the == so that a different function runs properly

**Comment by raq929** [comment]
Ummm... I'm confused about why you would ever need `==` and I would refactor to avoid it. 

Aaanyway, are you getting this console.log()? `console.log('sound results', result)`

**Comment by ggabrakadabra** [comment]
no I'm not getting the console.log at all so it's not reaching that point.
I'm using == because I don't need a strict comparison and I'm not assigning anything when I'm using it. But the functions that those == are in are running smoothly. It's only this one that's giving me issues

**Comment by ggabrakadabra** [comment]
when I look in the network tab under headers, under the query string parameters it says 

```
q:apollo
api_key:T9Rfu2Fl6lIsh6xAlOGq3fKH9q29wtvjvjy1d8la
json_callback:jQuery32105812006822066957_1490633286558
_:1490633286559
```
there's a semicolon there, I think that might be the issue, but I don't know how to fix that.

**Comment by ggabrakadabra** [comment]
Or maybe not, because when I click view source on that tab it shows

```
q=apollo&api_key=T9Rfu2Fl6lIsh6xAlOGq3fKH9q29wtvjvjy1d8la&json_callback=jQuery32105812006822066957_1490633286558&_=1490633286559
```

and then there's no semi colon

**Comment by ggabrakadabra** [comment]
When I click on the error, it brings me to the response and it has the : highlighted 

```
{"count": 10, "results": 
```
so is it the : after count that is causing the error?

**Comment by raq929** [comment]
You should always use strict comparisons. It leads to fewer errors. But is likely not the problem here.

I need more context to see what's going on here. But yes, that semi-colon is unexpected. It seems like something that should be there, though, so the error is likely right before it.

**Comment by ggabrakadabra** [comment]
What do you want me to send you?

**Comment by raq929** [comment]
Nothing? I was trying to get you to look for an error in the line(s) before that semicolon.

**Comment by raq929** [comment]
Come to classroom 4 and let's figure it out.

**Comment by ggabrakadabra** [comment]
Decided to run api calls from the back end and information is going to the front end and console logging now
