### ISSUE TITLE
Ember - model issue

### ISSUE THREAD

**Issue by cob0910** [ga-wdi-boston/capstone-project#513]
It can see how many logs I've made and adds buttons and plain text < h3 > for them but I cannot access the attributes of the model

<img width="611" alt="screen shot 2017-03-27 at 12 14 56 pm" src="https://cloud.githubusercontent.com/assets/24627406/24366390/03b453bc-12e7-11e7-8e7b-c2e677774f97.png">
<img width="868" alt="screen shot 2017-03-27 at 12 15 11 pm" src="https://cloud.githubusercontent.com/assets/24627406/24366412/0ffb099a-12e7-11e7-8f12-03854788adfe.png">

<img width="537" alt="screen shot 2017-03-27 at 12 15 35 pm" src="https://cloud.githubusercontent.com/assets/24627406/24366431/1e670358-12e7-11e7-9836-eaa806db3fc5.png">
<img width="876" alt="screen shot 2017-03-27 at 12 15 58 pm" src="https://cloud.githubusercontent.com/assets/24627406/24366438/299c3c0c-12e7-11e7-86d9-c3b9d1adf030.png">

<img width="613" alt="screen shot 2017-03-27 at 12 16 19 pm" src="https://cloud.githubusercontent.com/assets/24627406/24366470/358a874e-12e7-11e7-86bb-dd46e7616c70.png">

**Comment by cob0910** [comment]
<img width="547" alt="screen shot 2017-03-27 at 12 20 22 pm" src="https://cloud.githubusercontent.com/assets/24627406/24366662/c5025320-12e7-11e7-9339-051b5fa30e54.png">

**Comment by raq929** [comment]
What does the model hook return? What is that called in the template? (Hint: it's not `log`)

**Comment by cob0910** [comment]
templates/logs/index.hbs

the model is |log|
<img width="590" alt="screen shot 2017-03-27 at 12 28 00 pm" src="https://cloud.githubusercontent.com/assets/24627406/24366968/deea4bfc-12e8-11e7-815c-f3d445fc9aca.png">

**Comment by cob0910** [comment]
Solved!!

I had forgotten to ask about how doing ember and express may impact the way I set up my backend API. 

The fix was to update my log model so that the data points (forgetting the technical term right now) are camel case:
```
const logSchema = new mongoose.Schema({
  date_time: {
    type: Date,
    default: Date.now,
  },
  location: {
    type: String,
    required: true,
  },
  temp: {
    type: Number,
  },
  feels_like: {
    type: Number,
    required: true,
  },
...
```
I already had it but another thing to be sure is that to be sure the toJSON has the "virtuals: true," line:
```
  toJSON: {
    virtuals: true,
    transform: function (doc, ret, options) {
      let userId = (options.user && options.user._id) || false;
      ret.editable = userId && userId.equals(doc._owner);
      return ret;
    },
```

Then I deleted the prior logs I had created with curl scripts and remade them so they have the snake case style.

After redeploying the backend to heroku it worked!

<img width="389" alt="screen shot 2017-03-27 at 1 48 28 pm" src="https://cloud.githubusercontent.com/assets/24627406/24370082/19233788-12f4-11e7-8ef0-22af7ea2ee08.png">
