### ISSUE TITLE
Capstone Project 1:1

### ISSUE THREAD

**Issue by SquirtleSquad1988** [ga-wdi-boston/capstone-project#516]
Whenever anyone has time to meet with me this afternoon. I just need to have the preliminary discussion about project scope and reach goals. Below is the link for my front end repo which has the README.md at the bottom:

https://github.com/SquirtleSquad1988/moody-lords-front-end

Thanks!
Alex

**Comment by raq929** [comment]
Come by classroom 4 at 2:50

**Comment by SquirtleSquad1988** [comment]
Rachel and I talked about the final goal of my project. She convinced me to stick with using the browser template and creating a front end with what I have on the backend already (which is two models: blogs and comments). After that is complete, I will work on implementing a shopping cart using the stripe API. Thanks Rachel!
