### ISSUE TITLE
Ember - Edit Action

### ISSUE THREAD

**Issue by cob0910** [ga-wdi-boston/capstone-project#517]
I am getting an error saying there is no action handler but I think I am getting mixed up with what action names go where and I can't figure it out. I can type /edit in this url and get to my edit form and I can save or cancel those changes but the actual button to initiate the edit doesn't work. Can I please sit with someone to walk through the files?

<img width="869" alt="screen shot 2017-03-27 at 3 35 50 pm" src="https://cloud.githubusercontent.com/assets/24627406/24374495/1917b9bc-1303-11e7-802a-e48c6781baa1.png">

<img width="874" alt="screen shot 2017-03-27 at 3 43 43 pm" src="https://cloud.githubusercontent.com/assets/24627406/24374808/36573cd6-1304-11e7-8cdd-e228fa824caf.png">

**Comment by cob0910** [comment]
Solved! @raq929 is an ember wizard and knew exactly where my issue would be!

After double checking if the action names were correct in this:
<img width="1008" alt="screen shot 2017-03-27 at 3 52 59 pm" src="https://cloud.githubusercontent.com/assets/24627406/24375267/b8634854-1305-11e7-8ad5-7f5ab89c0978.png">

Then I had overlooked the action names in this file and had to correct them:
<img width="1011" alt="screen shot 2017-03-27 at 3 53 59 pm" src="https://cloud.githubusercontent.com/assets/24627406/24375296/caccee96-1305-11e7-97bf-c12d842c7598.png">

**Comment by jrhorn424** [comment]
Please avoid screenshots in the future.
