### ISSUE TITLE
Thinking of switching back to a regular javascript front-end

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/capstone-project#518]
I was lost on a few points on Ember this weekend, so I don't think I should use it for the capstone project anymore. I would like to understand if this might be an issue for any reason and if it would cause me any difficulties. I understand Ember can make some things easier, but I don't think it is a good time to try to learn it with how slow my progress generally is, so I would like to discuss the decision with someone.

**Comment by raq929** [comment]
The decision is up to you. If you think it would be better to use `browser-template`, you should use that.

**Comment by raq929** [comment]
`browser-template` has been updated to standard js (no semicolons).

**Comment by alexkarasik** [comment]
Thanks, but I must user ember.
