### ISSUE TITLE
One on one request

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/capstone-project#521]
I want to clarify my understanding of the way the data will work in my tables, because right now, I am not confident about it. My understanding was that the only data that would be saved to a table would be the attributes specified in my  Repo resource, but that this data was being saved in the Bookmarked_repo Resource, so I am not really saving any data to the Repo table and It's not entirely necessary. I'm going to need to try to cache data as well, but I thought this can be done with the data in the Bookmarked_repos table, but that will not be the case, because every single saved repo belongs to a specific user, so there wouldn't be a need to cache. 
Some of this was just explained to me, but I want to be more confident in my understanding as soon as possible and have some of this written down properly to reference. 
Thanks

**Comment by raq929** [comment]
Please post your ERD, and tell us what you've tried.

**Comment by alexkarasik** [comment]
I think I don't fully understand how the ember data from the front end is going to work with my back end. A user searches a keyword and certain attributes about the repos that match that will appear. When a user clicks an "add" button, they are adding that repository to their bookmarked_repos resource. I can not test my backend data until I get the data rendered from the 3rd party api to the screen and this is where I am having trouble at the moment.

**Comment by raq929** [comment]
I'm not sure I understand your issue. 
Please answer these questions in order:
1. What do you want to happen?
2. What is currently happening? (Post the error if there's an error.)
3. What have you tried? (Post the code)

**Comment by raq929** [comment]
Please rename this issue to include what the problem is.

**Comment by alexkarasik** [comment]
I think I can not verify my backend data, because I do not have any until my front end is working. My users' bookmarked database is made up of repositories they add after searching a keyword from github's 3rd party API. As of now, I have not gotten that far in my front end, but I want to make sure my understanding of this is correct as soon as possible before I proceed. I need to insert an add button on the returned data from the github API.

**Comment by raq929** [comment]
You can absolutely do everything on the backend without a frontend. You can do this via the rails console (if you're using rails), mongoose scripts (if you're using mongo) or curl requests (for both). You should not move forward until you have verified your backend works.

I will not continue to respond to this issue unless it includes code.
