### ISSUE TITLE
Modal on update won't close, stuck in limbo

### ISSUE THREAD

**Issue by lbreguet** [ga-wdi-boston/capstone-project#527]
I'm having a problem where my update modal blocks all access to the page. The PATCH works but it causes users to have to refresh the page. This might be because after I'm chaining a GET request to the success. 

Here is my code: 
ui.js
```js
const updateSuccess = (data) => {
  console.log(data)
  $('#myModal').modal('hide')
}
```
events.js
```js
const onUpdatePost = (event) => {
  event.preventDefault()
  const data = getFormFields(event.target)
  const id = event.target.dataset.id
  api.update(data, id)
    .then(ui.success)
    .then(() => onMenu())
    .catch(ui.failure)
}
```

**Comment by jordanallain** [comment]
It looks like you are calling a function called `success` when you want to be calling `updateSuccess`

**Comment by lbreguet** [comment]
Yep that should do it. Thanks for pointing that out.

**Comment by jrhorn424** [comment]
@tvlangley Do not close issues unless you are the one that opened them. Thanks!

cc @ga-wdi-boston/core
