### ISSUE TITLE
Problem getting link to to display the correct view state 

### ISSUE THREAD

**Issue by s0phi4** [ga-wdi-boston/capstone-project#528]
I have the following in the speaky-missions  component and it renders the therapies I have indicated in the back end which is what I aimed for and it works.
```
{{#each model as |therapy|}}
<li>{{#link-to 'speech-emission'}}{{therapy.name}}{{/link-to}}</li>
```
When I click on all the therapies it renders the content for the first therapy, and when I wan to render the content for the other therapies and I used this 

```
<ul>
{{#each model as |therapy|}}
<li>{{#link-to 'speech-emission'}}{{therapy.name}}{{/link-to}}</li>
<li>{{#link-to 'articulation'}}{{therapy.name}}{{/link-to}}</li>
{{/each}}
</ul>
```

I get duplications and it links to the corresponding therapy but on the second link.
Speech Emission
Speech Emission
Articulation
Articulation
Sound Recognition
Sound Recognition

I tried object.first and doesn't work
I also tried an if statement and doesn't work.

**Comment by jrhorn424** [comment]
@yenpraja610 What happened? Did you receive a 1on1 or did you find a solution?

**Comment by s0phi4** [comment]
Hola! Yeah , found solution using ember helpers
