### ISSUE TITLE
Resourceful Ember routes and binding associated data in routes

### ISSUE THREAD

**Issue by s0phi4** [ga-wdi-boston/capstone-project#532]
When trying to create a comment in the therapies I get a array-proxy error. 
My code to post comments in the  
```javascript

export default Ember.Route.extend({
  model() {
    return this.store.findAll('comment');
  },

  actions: {
    createComment(model) {
      let comment = this.get('store').createRecord('comment', {
        title: model.title,
        content: model.content,
      });
      comment.save();
    }
  },
});
```
I created a component to post the comment and this is the code
```
<article>
    <br>
    <h2>{{attrs.comment.title}}</h2>
    <p>{{attrs.comment.content}}</p>
    <br><br><br>
    <hr>
</article>

**Comment by raq929** [comment]
Please post the error.

**Comment by raq929** [comment]
Your model returns an array, but your are trying to see a single comment.

**Comment by yenpraja610** [comment]
Do not call your controller property content - accessing content automatically tries to load the model provided by the route and ignores the controller property altogether.???

**Comment by yenpraja610** [comment]
not sure how to fix this.

**Comment by yenpraja610** [comment]
When I enter title in my comment box, and continue to enter text in the comment box, as soon as I enter the second letter it throws that error
<img width="1367" alt="screen shot 2017-03-28 at 5 51 53 pm" src="https://cloud.githubusercontent.com/assets/16325294/24429285/65c5bcbe-13df-11e7-8c8b-8e7781dbee9f.png">
<img width="1413" alt="screen shot 2017-03-28 at 5 52 07 pm" src="https://cloud.githubusercontent.com/assets/16325294/24429286/65c5ee3c-13df-11e7-80bc-0dd1f1c66260.png">

**Comment by raq929** [comment]
OK. So, you bound the text of the box to something that Ember thinks is an array.

**Comment by raq929** [comment]
Come see me, I'll take a look.

**Comment by s0phi4** [comment]
These are the steps I took to create comment
1. Created a model called comment with attributes title: string and content: string
2. Generate component create-comment
3. In the component create-comment template I added the below
```
<h3>Comment</h3>

<form id="NewComment">
    <p>
      {{input value=newComment.title placeholder="Title"}}
    </p>
    <p>
      {{textarea value=newComment.content placeholder="Content" rows="10" cols="140"}}
    </p>
    <p>
        <button {{action "createComment" newComment}}>Create</button>
    </p>
</form>
```
4. Added the below to the template where I want the create-comment HTML  form to show up.
```
{{#create-comment newComment=model createComment="createComment"}}{{/create-comment}}
```
5. SUCCESS. I CAN SEE THE FORM.
6. SDince I entered action in my create button, I went to the create-comment component.js file and added the action there as seen below ,to send the value from the component to the route. 
```  javascript
actions: {
    createComment: function (model) {
      this.sendAction('createComment', model);

      //To clear input fields
      this.set('newComment.title', null);
      this.set('newComment.content', null);
    }
  }
});
```

SOLUTION APPROACHED

```javascript
export default Ember.Route.extend({
  model() {
    // return this.store.findAll('comment');
    return {};
  },

  actions: {
    createComment(model) {
      let comment = this.get('store').createRecord('comment', {
        title: model.title,
        content: model.content,
      });
      comment.save();
    }
  },
});
```
And the new error is 422 Unprocessable entity

<img width="1413" alt="screen shot 2017-03-28 at 6 44 17 pm" src="https://cloud.githubusercontent.com/assets/16325294/24430841/b0f3b8c4-13e6-11e7-9cb9-03a8d497fffc.png">

**Comment by jordanallain** [comment]
It's saying `null` in the id column, I assume there should be an id for each comment

**Comment by payne-chris-r** [comment]
`null` in ember data typically means it wasn't saved correctly. It has it in Ember data, but it's not persisting to the back end.

**Comment by raq929** [comment]
From what I saw earlier tonight, your new comment is just an empty object, not created using ember's store. You must create the new comment using Ember, not just a plain JS object.

**Comment by s0phi4** [comment]
I tried this and still getting error...
``` javascript
export default Ember.Route.extend({
  model() {
    return this.store.findAll('comment');
    // return this.get('store').createRecord('comment', {});
  },

  actions: {
    createComment(model) {
      let comment = this.get('store').createRecord('comment', {
        title: model.title,
        content: model.content,
      });
      comment.save();
    }
  },
});

**Comment by s0phi4** [comment]
Comments is a join table between users and therapies... are join tables handled differently in Ember?
Nope... didn't work
```javascript
 let therapy = this.store.peekRecord('therapy', 1);
  let comment = this.store.createRecord('comment', {
  });
  therapy.get('comments').pushObject(comment);
  comment.save();

**Comment by raq929** [comment]
Please meet with Jeff at noon.

**Comment by s0phi4** [comment]
App is not binding down from route.
Route name needs to be therapies and the path can be speaky mission
Next route needs to be with therapy id. 

Creating new branch and starting again! 👍
