### ISSUE TITLE
One on One request to specify 'Complete Product' for my project

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/capstone-project#533]
This is not really a code issue, but I am worried that what I have and what I plan to do in the remaining work time might not be enough to be considered a 'complete product' as per requirements.

I just want to have a one on one to determine if there is enough subtance to what my app is doing to qualify as being a complete product, or if I need to add more functionality.

**Comment by raq929** [comment]
What do you have? 
What does your app do? What would make it a complete product in your mind?

**Comment by samordonez** [comment]
It currently renders some graphs from the datasets that the API returns. I am planning to implement a feature where you can save said graphs, even though you could still just see that graph if you navigated to the page. I'm just worried that even though the technical tings the app is doing are interesting, it is not 'complete'. I guess some kind of customization (probably just color) of the graphs would be enough for me to justify users saving them and being a 'complete product'.

**Comment by payne-chris-r** [comment]
For the most part what it means is "does it do something"? Can it CRUD on a resource? Is authentication enabled?

**Comment by samordonez** [comment]
If I did everything I have planned it would lack only update, but I think I can do update easily (allow users to change the color of the graph). I think I'll update my user stories accordingly.
