### ISSUE TITLE
1-1 Request React Router

### ISSUE THREAD

**Issue by ddobson** [ga-wdi-boston/capstone-project#535]
I am having trouble setting up react router to properly handle login state. I would like a 1-1 to get some help with this. I am using React Router v4 and having trouble understanding the documentation in this area. Google is mostly returning examples with old versions of the router.

**Comment by raq929** [comment]
I'll try to work with you tomorrow morning.

**Comment by raq929** [comment]
Can you update and close please? I think we handled this issue; open a new one if there are new problems.
