### ISSUE TITLE
You can no longer pass a modelClass as the first argument to store.buildInternalModel.

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/capstone-project#536]
I'm getting this error when I try to view my couchposts now:
```
You can no longer pass a modelClass as the first argument to store.buildInternalModel. Pass modelName instead.
```

The only things I changed was I added these to my back-end:
*couchpost serializer*
```diff
class CouchpostSerializer < ActiveModel::Serializer
  attributes :id, :location, :date_needed, :couch_found

+  has_one :profile

+  def profiles
+   object.profiles.pluck(:id)
+  end
end
```
*profile serializer*
```diff
class ProfileSerializer < ActiveModel::Serializer
-  attributes :id, :given_name, :surname, :gender, :dob
+  attributes :id, :given_name, :surname, :gender, :dob, :editable

+  def editable
+    scope == object.user
+  end
end
```
*couchpost controller*
```diff
def couchpost_params
-    params.require(:couchpost).permit(:location, :date_needed, :couch_found)
+    params.require(:couchpost).permit(:location, :date_needed, :couch_found,
+                                      :profile_id)
end
```
*couchpost model*
```diff
class Couchpost < ApplicationRecord
  belongs_to :profile

  validates :location, presence: true
  validates :date_needed, presence: true
  validates :couch_found, presence: true
+  validates :profile, presence: true
end

```
Not 100% what to do because I feel like I need these changes on the back-end, but now the front-end is _really_ messy and I don't know what the error means.

**Comment by laurpaik-zz** [comment]
Woof, I am having an adventure! So I muted the belongs_to line on the Ember model for couchpost:
```js
export default DS.Model.extend({
  location: DS.attr('string'),
  dateNeeded: DS.attr('date'),
  couchFound: DS.attr('string'),
  // profile: DS.belongsTo('profile'),
});
```
And now it's working. Idk what this means, but I will go back to the previous issue now.

**Comment by jrhorn424** [comment]
I honestly don't know whether it should be singular or plural without seeing your API model relationships, but this is your problem:

```diff
-  has_one :profile

-  def profiles
+  def profile
-   object.profiles.pluck(:id)
+   object.profile.pluck(:id)
   end
```

**Comment by laurpaik-zz** [comment]
ohh gotcha, yea that worked:
*couchpost api serializer*
```rb
class CouchpostSerializer < ActiveModel::Serializer
  attributes :id, :location, :date_needed, :couch_found

  def profile
    object.profiles.pluck(:id)
  end
end
```

*couchpost model front-end*
```js
export default DS.Model.extend({
  location: DS.attr('string'),
  dateNeeded: DS.attr('date'),
  couchFound: DS.attr('string'),
  profile: DS.belongsTo('profile'),
});
```
Did you want me to keep this issue open, @jrhorn424 ?

**Comment by raq929** [comment]
It it's resolved, please close it.

**Comment by jrhorn424** [comment]
```
  def profile
    object.profiles.pluck(:id)
  end
```

I can't figure out why it's being serialized out as an array of IDs. Why is the method name on object `profiles` instead of `profile`? Is there more than one? If so, the method should be named profile, and additionally the Ember model relationship should be a "hasMany" not "belongsTo".

If it's singular, don't `pluck`. Just grab the value.

**Comment by laurpaik-zz** [comment]
@jrhorn424 See solution from [here](https://github.com/ga-wdi-boston/capstone-project/issues/574)
