### ISSUE TITLE
getting api request to only return specified attributes

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/capstone-project#539]
This is my search controller that goes to the github api to return the information on a query search:
```

# frozen_string_literal: true
require 'open-uri'
require 'json'
require 'net/http'

class PracticesController < OpenReadController
  before_action :set_example, only: [:update, :destroy]
  # GET /practices

  def search_github
    query = params[:search][:query]
    url = "https://api.github.com/search/repositories?q=#{query}"
    response = open(url)
    data_string = response.read
    json_string = JSON.parse(data_string)
    render json: json_string
  end
end
```
I think it is in the url where I write out that I only want those certain attirbutes returned (the title of the repo, the author of the repo, the number of stars, the number of forks and the language), but the documentation is not very clear to me on how to do this. 
I think I just add those query parameters in the url, but I am not sure how to format that.

**Comment by raq929** [comment]
In general, queries are formatted:
`?key=value&key=value&key=value`

**Comment by alexkarasik** [comment]
I think I phrased my question poorly or may be misunderstanding my own issue. I want just certain attributes to return after a user clicks a search button. I don't think I want to write that in the url, but want it retireved from the data that returns from the url.

**Comment by jordanallain** [comment]
do you have them in the serializer?

**Comment by bernardlee** [comment]
If the GitHub API returns all of the information about a repository to your back end, then what can you do with that data before it gets sent to the front end?

**Comment by bernardlee** [comment]
Any update on this?

**Comment by alexkarasik** [comment]
I am getting some of the attributes that I want to render. My next move is to write a script for the backend that saves this to a specified user, but i guess that is another issue, so I will close this.

**Comment by bernardlee** [comment]
Please post your solution (code, etc.).
