### ISSUE TITLE
Need help updating record on backend and pushing it to front-end from delayed job

### ISSUE THREAD

**Issue by atsundwn** [ga-wdi-boston/capstone-project#54]
I have delayed_jobs somewhat working and when it sends the sms I also want the backend to a field on that record and save it and push the new array forward.  I am not sure how to approach it.

**Comment by gaand** [comment]
Since you're using rails for the backend you can look at the code I wrote for the tic tac toe api.

It doesn't work well on Heroku.  We might have to deploy your app to DigitalOcean.
