### ISSUE TITLE
Requiring files for FlipClock.js

### ISSUE THREAD

**Issue by jwaskow** [ga-wdi-boston/capstone-project#540]
Hi.  I'm trying to use [FlipClock.js](http://flipclockjs.com/) for a countdown timer for my tea-steeping app.  Their documentation seems very straightforward, but instructions on how to install and require files are very minimal.  Their GitHub README has only one instruction: `npm install flipclock`.  I did this and attempted to require the package, but the npm website says "flipclock lists no main file and has no index.js, so it can't be directly required".  Next I tried loading the files in the HTML as flipclockjs.com suggests: 
```
<html>
	<head>
		<link rel="stylesheet" href="/assets/css/flipclock.css">
	</head>
	<body>
		<div class="your-clock"></div>
		
		<script src="/assets/js/libs/jquery.js"></script>
		<script src="/assets/js/flipclock/flipclock.min.js"></script>
	</body>
</html>
```

I Duplicated the `flipclock.css` and `flipclock.min.js` files from the package into a folder in the root of my directory, and adjusted the paths in the html accordingly.  I still see nothing when I try their "Basic Example" clock.  I've been researching how to get this to work for about an hour and a half, and have yet to find anything explaining how to actually load the files (in every issue, they have already loaded the clock and have questions about other things).  This leads me to believe that getting the clock to show is simple, and I'm just missing something.  I understand that we did not cover this package in class so it is unlikely that anyone is familiar with it, but I would really appreciate some help with requiring the files appropriately.  Thanks

**Comment by raq929** [comment]
Do you get an error when you run the server?

**Comment by raq929** [comment]
Also, does this file exist? You may need to require it from `node_modules`. Which is not the right way to do this. So, is there a different node module you can use for this? It kind of sounds like the people writing it don't know how to write node modules.

**Comment by jwaskow** [comment]
The server seems fine.  My app was loading fine before but now it gives the error `Paused on exception.  ReferenceError: jQuery is not defined`.

I chose this module because it seemed like it would be easy, just install it and you're good to go.  Seeing how this isn't the case, I think I may look into other countdown options.
