### ISSUE TITLE
1:1 for verification of "complete" product

### ISSUE THREAD

**Issue by akgoode** [ga-wdi-boston/capstone-project#541]
Hi all,

I would like to have a brief one on one at some point tomorrow for verification on if my project fulfills the complete product requirement.  I'm pretty sure that it does but I would still like to check.  

Alternatively, my project is deployed here:
https://akgoode.github.io/posts-with-friends

And my github repo with links to all parts of the project is here: 
https://github.com/akgoode/posts-with-friends

If in fact it is deemed to be complete I will continue working on features that I will merge and deploy after I pass the capstone.

Thanks all,

Andrew

**Comment by akgoode** [comment]
So to clarify, I don't NEED a 1:1, I would just like some feedback if I have a complete project.  A short convo on slack or here will suffice.

**Comment by akgoode** [comment]
My goal by Friday is to have the first step towards a social-media platform (hence the name).  As of right now, my project consists of a one to many relationship between user and posts.  All the CRUD functionality for posts is implemented on the front end as well as a lot of protections for routes that unauthorized users should not be able to access.

Users can create posts, update and delete their posts, and view all the posts in the database.  In addition, there is a tab that allows users to see only their own posts.  This is my prototype for a profile, while the list of all the posts is a prototype for a news feed.

The next feature that I will implement is followees.  A user will be able to follow people, and will have the option to see a list of posts from people they follow.  Depending on whether or not my project meets requirements right now I may have this feature available for demo at the presentation.

My goal by the meet and hire is to have a much more functional social media platform.  I want usernames to be associated with posts on the feed, I want users to be able to follow other users, and I want to have a functional user profile where followers can see only that user's posts.

I think that right now I have a complete project for delivery on Friday.  While it doesn't have the complete functionality that a *social* media platform does, I think it offers a complete experience when it comes to creating posts and viewing them, and is a good starting point for the implementation of features that will allow it to reach my longer-term goals sooner rather than later.

I would love to hear your (read: anyones!) thoughts on this.

Thank you,
Andrew

**Comment by raq929** [comment]
Ember or not?

**Comment by akgoode** [comment]
Yes front end is in Ember

**Comment by akgoode** [comment]
I am going to close this issue for now.  I think that my project is a complete product and I feel confident presenting it as such.

**Comment by jrhorn424** [comment]
Chiming in to say it seems you've done a great job planning and scaffolding your work, @akgoode. Let's see on, Friday. I applaud your conservatism w.r.t. to trying to deploy too much by Friday.

**Comment by akgoode** [comment]
This is precisely the kind of feedback that I've been looking for.  Since the requirements in the capstone project say "most likely have multiple relationships and other features" some doubt started to creep in, and I just wanted some reassurance with the end looming so near.  I think one of the strongest arguments in my mind for it being complete is that I feel I have set myself up well to add new features.

**Comment by jrhorn424** [comment]
Good to hear. Please see also how I'm interpreting the requirement in a general sense: https://github.com/ga-wdi-boston/capstone-project/issues/567#issuecomment-290299328
