### ISSUE TITLE
Comment input error

### ISSUE THREAD

**Issue by moshiko1988** [ga-wdi-boston/capstone-project#544]
I am trying to create a new comment on a post, and as I enter a letter in the input field I get the following error : `Assertion Failed: Cannot call set with 'body' on an undefined object.`

I am able to display the comments that I posted on curl script but I cant create one on ember.

routes/comments.js
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return this.get('store').createRecord('comment');
},
actions: {
  createComment (comment) {
    console.log('HI');
    comment.save()
    .then(()=> this.transitionTo('comments'));
  },
}

}); ```

components/create-comment.js
```js
import Ember from 'ember';

export default Ember.Component.extend({

  actions: {
    save() {
      console.log('yo');
      this.sendAction('save', this.get('comment'));
    },
  }
});
```

models/comment.js

```js
import DS from 'ember-data';

export default DS.Model.extend({
  body: DS.attr('string'),
  user: DS.belongsTo('user'),
  post: DS.belongsTo('post')
});
```

templates/component/create-comment.hbs
```js


<form {{action 'save' on='submit'}} >
  {{input placeholder="Comment..."
          value=comment.body}}
</form>
```

templates/post.js
(this is the post page, I can see the comments that I created on the back end in here)
```js
<h1>POSTS</h1>



{{outlet}}
<div class="panel panel-primary">
  <div class="panel-body">
    <li class='post-title'>{{model.title}}</li>

  </div>
  <div class="panel-footer"><li class='post-body'>{{model.body}}</li></div>

</div>


{{create-comment save='createComment'}}



{{#each model.comments as | comment |}}

  <div class="panel-footer"><li class='post-body'>{{comment.body}}</li></div>
{{/each}}
```

**Comment by raq929** [comment]
Please see #532

**Comment by moshiko1988** [comment]
So I added an empty object to routes/comments.js and get the same error.

```js
    return this.get('store').createRecord('comment', {});```

**Comment by moshiko1988** [comment]
can I request 1 on 1 for this issue ?

**Comment by raq929** [comment]
Are you passing that data down to the component?

I will do a 1:1 if you have a nice diagram of your ember app like we had in `ember-resources`

**Comment by moshiko1988** [comment]
@raq929 I dont have a diagram because im too confuse at this point.

**Comment by moshiko1988** [comment]
and I am passing data

**Comment by raq929** [comment]
Do your best to make a diagram and then we can talk about it. The diagram is what will make this clear.

**Comment by moshiko1988** [comment]
@raq929 ok I did it.
when could we meet?

**Comment by raq929** [comment]
Why don't you meet with Jeff @ 12:30

**Comment by raq929** [comment]
Was this issue resolved? Can you update and close, please? Or at least update?

**Comment by moshiko1988** [comment]
Its not solved. Jeff helped me write the create action but now theres a new issue when I create a post i get this error : 
```POST http://localhost:4741/comments 422 (Unprocessable Entity)```
and in the back end server the error is:
```
Started POST "/comments" for 127.0.0.1 at 2017-03-29 15:48:25 -0400
Processing by CommentsController#create as HTML
  Parameters: {"comment"=>{"body"=>"adss", "user_id"=>nil, "post_id"=>nil}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "899a42c045d40f66b6e60cfecaf42be7"], ["LIMIT", 1]]
Unpermitted parameter: user_id
   (0.2ms)  BEGIN
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
   (0.1ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.08ms)
Completed 422 Unprocessable Entity in 40ms (Views: 2.4ms | ActiveRecord: 0.9ms)
```

I tried to create a comment again with curl script and it did not create so I added the following code in the `create` comment controller : 
```ruby
    @comment.user_id = current_user.id
```
so now Im able to create comments with curl script but i still get the same error when I try to create it in the browser.

**Comment by raq929** [comment]
Please look at the unsuccessful request in the network tab and look at the data you're posting. How is it different from the data you're sending on the curl request?

**Comment by moshiko1988** [comment]
Thats what I see in the network tab : 
``` 
{comment: {body: "asdas", user_id: null, post_id: null}}
comment
:
{body: "asdas", user_id: null, post_id: null}
```

and comment controller params: 
```ruby
  def create
    @comment = current_user.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      render json: @comment, status: :created
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

def comment_params
    params.require(:comment).permit(:body, :post_id)
  end 
```

**Comment by raq929** [comment]
Cool. You're not sending a post_id. You probably need one to create a comment. (Does your curl request have one?)
If you look at `ember-resources`, we added list to the item when creating it. you need to do that here for post. 
https://github.com/ga-wdi-boston/ember-resources/blob/016/training/app/components/shopping-list.js

**Comment by moshiko1988** [comment]
yes I believe I do

routes/comment-new.js
```js

export default Ember.Route.extend({
  auth: Ember.inject.service(),

  model(params) {

    const user_id = this.get('auth.credentials.id');
    const hash = Ember.RSVP.hash({
      user: this.get('store').findRecord('user', +user_id),
      post: this.get('store').findRecord('post', params.post_id),
    }); console.log('yo', hash);
    return this.get('store').createRecord('comment', hash);

  },
  actions: {
    createComment(comment) {
      comment.save();
    },
  }
});

```

**Comment by raq929** [comment]
Come see me if you're still here.

**Comment by jrhorn424** [comment]
@raq929 What happened? I thought I left @moshiko1988 in a good place.

**Comment by moshiko1988** [comment]
Solved: 

The comment.new route is not nested route
```js
Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('posts');
  this.route('create');
  this.route('post', { path: '/posts/:post_id' }, function() {
    this.route('edit');
    this.route('comments');
  });
  this.route('comment-new', { path: '/posts/:post_id/comments/new'});
}); 
```

Linked to create-commonet components with post=model 

templates/comment-new.hbs
```js
{{create-comment createComment='createComment' post=model }}
```
Setup model hook : 
routes/comment-new
```js

export default Ember.Route.extend({
  model(params) {
    return this.get('store').findRecord('post', params.post_id);
  },
  actions: {
    createComment(data) {
      const comment = this.get('store').createRecord('comment', data);
      comment.save();
    },
  }
});
```
created a new object, newComment, to store the input 

Components/create-comments.js

```js
export default Ember.Component.extend({
  newComment:{
    body: null,
  },
}); 
```
Link the value to the object that was just created, newComment

templates/components/create-comment.hbs

```js
<form {{action 'createComment' on='submit'}} >
  {{input placeholder="Comment..."
          value=newComment.body}}
</form>
```
Back to Components/create-comments.js
Link post to data and send up action createComment with the input data
```js
  actions: {
    createComment() {
      let data = this.get('newComment');
      data.post = this.get('post');
      this.sendAction('createComment', data);
      this.set('comment', null);
    },
  }
```
Lastly, back to routes/comment-new create ember data instant object comment and save. 

Thank to @newayliu1 for the help!

**Comment by payne-chris-r** [comment]
Well done!
