### ISSUE TITLE
Bug with resetting javascript timer

### ISSUE THREAD

**Issue by jwaskow** [ga-wdi-boston/capstone-project#550]
So I have a countdown timer written in javascript, and I'm able to press a button next to a row on a table and load that row's time into the timer and start the timer.  It works fine, and stops at 0 and displays a message, and you can't load a new time while the timer is running.  However, I encounter bugs after the timer ends.  If I load a new time, the timer will count down as usual but every second it will flash to 0:00 (from the previous timer).  Also, you can load multiple times while the timer is running, causing the timer to rapidly flash between those times.  This only happens after the timer successfully counts down once.  Really confused here, I don't quite know what to do.

```
let isRunning = false

const startTimer = function (duration, display) {
  let timer = duration
  let minutes
  let seconds
  isRunning = true

  setInterval(function () {
    minutes = parseInt(timer / 60, 10)
    seconds = parseInt(timer % 60, 10)

    seconds = seconds < 10 ? '0' + seconds : seconds

    display.text(minutes + ':' + seconds)

    if (--timer < 0) {
      display.text('')
      $('#timer-message').text('TEA TIME')
      isRunning = false
      return isRunning
    }
  }, 1000)
}

const loadTime = function (event) {
  event.preventDefault()
  const id = event.target.getAttribute('data-id')
  api.showTea(id)
  .then(function (data) {
    if (isRunning === true) {
      return
    } else {
      startTimer(data.tea.steepTime, $('#time'))
    }
  })
}
```

I basically need to restrict the timer to one instance at a time.  Functionally the timer works, but I need it to reset correctly.

**Comment by raq929** [comment]
Cool. so you need something (probably in that else) to get rid of the old timer. Does the library have anything like that? Can you just delete it from the html before you make a new one?

**Comment by raq929** [comment]
(I have no idea what your app is, but zomg tea time.)

**Comment by raq929** [comment]
Any update on this?

**Comment by bernardlee** [comment]
I suspect that the "0:00" flashing is caused by the existence of the previously created intervals being active.  This might be what you need: [clearInterval()](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/clearInterval).

**Comment by jwaskow** [comment]
Yes.  I was just working with Steve, because he he's also worked with timers before.  He gave me some good suggestions about using `clearInterval` and said my issue probably has to do with the scope of `isRunning`, which I agree with.  Heres my current code:

```
let isRunning = false

const endTimer = function (startTimer) {
  clearInterval(startTimer)
  console.log('end timer working')
}

const startTimer = function (duration, display) {
  let timer = duration
  let minutes
  let seconds

  setInterval(function () {
    isRunning = true
    minutes = parseInt(timer / 60, 10)
    seconds = parseInt(timer % 60, 10)

    seconds = seconds < 10 ? '0' + seconds : seconds

    display.text(minutes + ':' + seconds)

    if (--timer < 0) {
      display.text('')
      $('#timer-message').text('TEA TIME')
      endTimer(startTimer)
      isRunning = false
      return isRunning
    }
  }, 1000)
}

const loadTime = function (event) {
  event.preventDefault()
  const id = event.target.getAttribute('data-id')
  api.showTea(id)
  .then(function (data) {
    console.log(isRunning)
    if (isRunning === false) {
      startTimer(data.tea.steepTime, $('#time'))
    } else {
      return
    }
  })
}
```

Its very strange, before the timer initially runs, `isRunning` logs `false`.  During the first time it runs, `isRunning` logs `true`.  However after it finishes and I begin a new timer, when I click the button to begin a new timer again, sometimes `isRunning` logs `true` (and i cannot add the time, this is correct), and other times it logs `false` (adding an instance to the timer and blinking between that and the current timer), seemingly at random.

**Comment by jwaskow** [comment]
It's rather confusing, and I'd probably be able to explain the issue better in person

**Comment by bernardlee** [comment]
`clearInterval()` should take an `intervalID` as an argument.

**Comment by jwaskow** [comment]
Did I not do that?  I have `clearInterval(startTimer)`, and `startTimer` is the name of the function in which the interval needs to clear

**Comment by bernardlee** [comment]
`startTimer` in that case is a function not an `intervalID`.  Check [setInterval()](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval).

**Comment by jwaskow** [comment]
Ok I read through that documentation and I'm still confused.  I tried passing pretty much everything I could to `clearInterval`, and nothing changed.  I also tried splitting up my function so I could use a callback but the scope of the variables gets very complicated.  I'm still not fully understanding intervals and intervalID's

**Comment by bernardlee** [comment]
Can you post the code that you've recently tried?

**Comment by jwaskow** [comment]
I was able to fix it!

I refactored the main function so I could get the right interval ID

```
let isRunning = false

const startTimer = function (duration, display) {
  let timer = duration
  let minutes
  let seconds

  let timerLogic = function () {
    isRunning = true
    minutes = parseInt(timer / 60, 10)
    seconds = parseInt(timer % 60, 10)

    seconds = seconds < 10 ? '0' + seconds : seconds

    display.text(minutes + ':' + seconds)

    if (--timer < 0) {
      display.text('')
      $('#timer-done-message').text('TEA TIME')
      $('#timer-wait-message').text('')
      endTimer(timerLogic)
      isRunning = false
      return isRunning
    }
  }
  timerLogic = setInterval(timerLogic, 1000)
}

const endTimer = function (timerLogic) {
  clearInterval(timerLogic)
}

const loadTime = function (event) {
  event.preventDefault()
  const id = event.target.getAttribute('data-id')
  api.showTea(id)
  .then(function (data) {
    console.log(isRunning)
    if (isRunning === false) {
      $('#timer-done-message').text('')
      startTimer(data.tea.steepTime, $('#time'))
    } else {
      $('#timer-wait-message').text('Please wait until the current timer finishes')
      return
    }
  })
}
```

**Comment by jwaskow** [comment]
I'll close this issue and hopefully it's now bug-free
