### ISSUE TITLE
Ember: trying to toggle a property

### ISSUE THREAD

**Issue by dsweetser** [ga-wdi-boston/capstone-project#552]
Okay, I'm filing an issue, since ember continues to be a lot for me to wrap my head around and I don't want to be stuck too much longer.  I'm trying to toggle a property on my order object from false to true with a button.  Here's the bits of code that are relevant as best I can tell:

templates/components/app-order/confirm.hbs
```
<button class='btn btn-primary btn-xs' {{action 'confirmOrder'}}>Complete Order</button>
```
components/app-order/confirm.js
```
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    confirmOrder() {
      return this.sendAction('confirmOrder', this.get('order'));
    },
  }
});
```
templates/shop/orders.hbs
```
<h2>ORDER HISTORY</h2>


{{#each model as |order|}}
Order {{order.id}}
<ul>
  {{#if order.shippingAddress}}
  <li>Shipping Address: {{order.shippingAddress}}</li>
  {{/if}}
  {{#if order.billingAddress}}
  <li>Billing Address: {{order.billingAddress}}</li>
  {{/if}}
  <li>Order total: ${{order.total}}</li>
  <li>Completed? {{order.paid}}</li>
  {{#unless order.paid}}{{app-order/confirm order=model confirmOrder='confirmOrder'}}{{/unless}}
</ul>
{{/each}}

{{#link-to 'shop'}}Back{{/link-to}}
```
routes/shop/order.js
```
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('order');
  },

  actions: {
    confirmOrder (order) {
      order.toggleProperty('paid');
      order.save()
      .then(() => this.transitionTo('shop.orders'));
    },
  }
});
```
currently it doesn't seem to be toggling the properties of the selected item and is sending out a put request for each of the orders on the page.

Let me know if there's something else that I can show!

**Comment by raq929** [comment]
This is a great issue.
`{{#unless order.paid}}{{app-order/confirm order=model confirmOrder='confirmOrder'}}`

I think you need to change `order=model` (model is an array of orders) to `order=order` (where it's an individual order).

**Comment by dsweetser** [comment]
That's exactly it!!!! I had a feeling it was something in that definition but wasn't sure what the problem was.
