### ISSUE TITLE
Heroku Deployment - Old heroku app transfer to New one

### ISSUE THREAD

**Issue by skylarkJ** [ga-wdi-boston/capstone-project#555]
I have used a heroku application created from the study deployment before the project started but I think I should not. So I deleted the heroku app from heroku dashboard and created new heroku app. But in the terminal, if I put remote -v it's pointing me to the old heroku app. Should I just repeat these two steps? (because I have still the .env with keys)

```
In order to make requests to your deployed API, you will need to set SECRET_KEY_BASE in the environment of the production API (using heroku config:set or the Heroku dashboard).
In order to make requests from your deployed client application, you will need to set CLIENT_ORIGIN in the environment of the production API (e.g. heroku config:set CLIENT_ORIGIN https://<github-username>.github.io).
```

Or I have to delete from the terminal old pointing to the old heroku app somehow?

**Comment by raq929** [comment]
If you're not using the old heroku app, I would delete the remote, and then add the new remote.  (You can easily google deleting a remote in git.) 
I'm not quite sure _why_ you need a new remote, but that's what I would do.

**Comment by skylarkJ** [comment]
Yeah, It didn't look like deployment was successful before and someone told me to rather start new heroku app.

```
$ heroku create
Creating app... done, ⬢ peaceful-shelf-33934
https://peaceful-shelf-33934.herokuapp.com/ | https://git.heroku.com/peaceful-shelf-33934.git
~/wdi/projects/sport-api (master)
$ git remote -v
heroku	https://git.heroku.com/agile-caverns-89764.git (fetch)
heroku	https://git.heroku.com/agile-caverns-89764.git (push)
origin	git@github.com:skylarkJ/sport-api.git (fetch)
origin	git@github.com:skylarkJ/sport-api.git (push)
~/wdi/projects/sport-api (master)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.editorconfig
	.gitignore
	.remarkrc
	.rubocop.yml
	.ruby-version

nothing added to commit but untracked files present (use "git add" to track)
~/wdi/projects/sport-api (master)
$ atom .env
~/wdi/projects/sport-api (master)
$ heroku git:remote -a appname
 ▸    You do not have access to the app appname.
~/wdi/projects/sport-api (master)
$ 
```

**Comment by skylarkJ** [comment]
I need to have it on the peaceful-shelf-33934 which is new app on heroku, while the old one called agile-caverns-89764  is already gone.

**Comment by skylarkJ** [comment]
Okay, Have done this.
```
$ git remote rm heroku
~/wdi/projects/sport-api (master)
$ git remote -v
origin	git@github.com:skylarkJ/sport-api.git (fetch)
origin	git@github.com:skylarkJ/sport-api.git (push)
~/wdi/projects/sport-api (master)
$ 
```

**Comment by raq929** [comment]
Cool. Now you need to add your new heroku app as  a remote.

**Comment by skylarkJ** [comment]
I did a heroku create again and got stuck on heroku config:set
```
$ heroku create
Creating app... done, ⬢ powerful-citadel-79189
https://powerful-citadel-79189.herokuapp.com/ | https://git.heroku.com/powerful-citadel-79189.git
~/wdi/projects/sport-api (master)
$ git remote -v
heroku	https://git.heroku.com/powerful-citadel-79189.git (fetch)
heroku	https://git.heroku.com/powerful-citadel-79189.git (push)
origin	git@github.com:skylarkJ/sport-api.git (fetch)
origin	git@github.com:skylarkJ/sport-api.git (push)
~/wdi/projects/sport-api (master)
$ heroku config:set
 ▸    Usage: heroku config:set KEY1=VALUE1 [KEY2=VALUE2 ...]
 ▸    Must specify KEY and VALUE to set.
~/wdi/projects/sport-api (master)
$ 
```

**Comment by BenGitsCode** [comment]
Ah look closely at that error.

Similarly, if I were to type _just_ `brew install` brew would think on it a bit and then tell me:
`Error: Invalid usage: This command requires a formula argument`
Because `brew install` installs the specificed formula, without an argument specified, to knows to install, but not _what to install_


Your objective from above: `In order to make requests to your deployed API, you will need to set SECRET_KEY_BASE in the environment of the production API (using heroku config:set or the Heroku dashboard).
In order to make requests from your deployed client application, you will need to set CLIENT_ORIGIN in the environment of the production API (e.g. heroku config:set CLIENT_ORIGIN https://<github-username>.github.io).`

Reread that carefully as well as the error heroku is giving you. What's missing?

**Comment by skylarkJ** [comment]
I thought that it's missing the second step but it's written in 2 steps, why?

**Comment by skylarkJ** [comment]
Hm. No.

```
$ heroku config:set CLIENT_ORIGIN https://skylarkj.github.io
 ▸    CLIENT_ORIGIN is invalid. Must be in the format FOO=bar.
~/wdi/projects/sport-api (master)
$ 
```

**Comment by BenGitsCode** [comment]
You're getting closer, the error is trying to lead you to the right syntax **`Must be in the format FOO=bar`**

**Comment by skylarkJ** [comment]
All right. So please adjust the discovery in the template "="
[https://github.com/skylarkJ/rails-api-template](https://github.com/skylarkJ/rails-api-template)

```
$ heroku config:set CLIENT_ORIGIN=https://skylarkj.github.io
Setting CLIENT_ORIGIN and restarting ⬢ powerful-citadel-79189... done, v3
CLIENT_ORIGIN: https://skylarkj.github.io
~/wdi/projects/sport-api (master)
$ ```

**Comment by BenGitsCode** [comment]
I opened an issue now, thanks for catching that, I just opened an issue. Please summarize your resolution and close this issue.

**Comment by skylarkJ** [comment]
Sorry, I have another question about this. When I have already done  ```bin/rake db:nuke_pave``` at the beginning of the project do I have to run it again?

**Comment by BenGitsCode** [comment]
That's a separate issue.  It would depend on whether or not you need to drop, create, migrate and seed your database again.

**Comment by skylarkJ** [comment]
When I check Heroku dashboard I don't have in those config variables other than client origin link.

**Comment by skylarkJ** [comment]
okay, so I fixed that by $ git push heroku master
```
remote: Verifying deploy... done.
To https://git.heroku.com/powerful-citadel-79189.git
```

**Comment by skylarkJ** [comment]
So I have done again the secret keys and such. And restarted - got the message on the screen. 
```
$ heroku config:set SECRET_KEY_BASE=$(rake secret)
$ heroku config:set SECRET_TOKEN=$(rake secret)
$ heroku config:set CLIENT_ORIGIN=https://yourgithubname.github.io
```
