### ISSUE TITLE
Radio Buttons won't get highlighted when I click them

### ISSUE THREAD

**Issue by zchenbonterra** [ga-wdi-boston/capstone-project#556]
Basically, I am getting the data I want when I click on the radio buttons. But, the buttons won't get highlighted or checked for some reason. Please advise! Below are my codes.

components/apparel-type
```
import Ember from 'ember';

export default Ember.Component.extend({
  classNames: ['form-group'],
  tagName: 'div',

  actions: {
  atiToggled(choice) {
    console.log("changing ati choice", choice);
    this.set('ati', choice);
  }
}
});
```

templates/components/apparel-type
```
<label for="ati">Type</label>

<input
  type="radio"
  value=ati
  name="kind"
  {{action 'atiToggled' "Coat"}}>
  Coat

  <input
    type="radio"
    value=ati
    name="kind"
    {{action 'atiToggled' "Jacket"}}>
    Jacket
```

**Comment by raq929** [comment]
You'll probably have much better luck using ember's input helper.
https://guides.emberjs.com/v2.11.0/templates/input-helpers/

**Comment by zchenbonterra** [comment]
I think I should use the following code to make it work, but I am not sure how to implement it. Please advise! I have read the documentation on get and mut, but very confused.

```
{{input value=(mut (get person field))}}
```

**Comment by zchenbonterra** [comment]
Or should I just generate a helper for this???

**Comment by raq929** [comment]
There are some premade ones, it looks like. Maybe this? https://www.npmjs.com/package/ember-radio-buttons

**Comment by zchenbonterra** [comment]
Fixed!!! All I needed to do was to use the input helper and use the click attribute for the action. Please see below for codes in the template.

```
<div class="apparel-type-input">
  <label class="apparel-label">Type:</label>
  <br>

  {{input click=(action "atiToggled" "Coat")
    type="radio"
    value=ati
    name="kind"
  }}Coat<br>

  {{input click=(action "atiToggled" "Jacket")
    type="radio"
    value=ati
    name="kind"
  }}Jacket<br>

</div>
```
