### ISSUE TITLE
404 Not Found sh scripts/videos/show.sh or index.sh

### ISSUE THREAD

**Issue by s0phi4** [ga-wdi-boston/capstone-project#557]
I am having an issue showing accessing videos on the back end when I run the show and index script. All the other tables work fine when I run the scripts except for this one. When I access the database I can see the videos. But can access them when I run the script. 

ezspeaky-api_development=# select * from videos;
 id |        name         |                     url                     | therapy_id |         created_at         |         updated_at         
----+---------------------+---------------------------------------------+------------+----------------------------+----------------------------
  1 | Repeat and Identify | https://www.youtube.com/watch?v=BLuZdiX7Wrg |          1 | 2017-03-29 14:06:53.084007 | 2017-03-29 14:06:53.084007
  2 | Pronunciation       | https://www.youtube.com/watch?v=ky2hngeUcUg |          1 | 2017-03-29 14:06:53.176642 | 2017-03-29 14:06:53.176642
  3 | Articulation Game   | https://www.youtube.com/watch?v=XhuU3c5QSso |          2 | 2017-03-29 14:06:53.178968 | 2017-03-29 14:06:53.178968
  4 | S and Z             | https://www.youtube.com/watch?v=kTAtVWsvhNA |          2 | 2017-03-29 14:06:53.181118 | 2017-03-29 14:06:53.181118
  5 | Escape of Air       | https://www.youtube.com/watch?v=k1juKhiqReU |          3 | 2017-03-29 14:06:53.182978 | 2017-03-29 14:06:53.182978
  6 | Practice S          | https://www.youtube.com/watch?v=gHVtHEc4PU4 |          3 | 2017-03-29 14:06:53.184905 | 2017-03-29 14:06:53.184905
(6 rows)

This is what I have in controller
```js
class VideosController < ProtectedController
  before_action :set_video, only: [:index, :show]
# GET /videos
  def index
    @videos = Video.all

    render json: @videos
  end

  # GET /videos/1
  def show
    render json: @video
  end
# Use callbacks to share common setup or constraints between actions.
  def set_video
    @video = Video.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def video_params
    params.require(:video).permit(:name, :url)
  end

  private :set_video, :video_params
end
```
Video Model

```js
class Video < ApplicationRecord
  belongs_to :therapy
  validates :name, :url, presence: true
end
```

Therapy Model
```js
class Therapy < ApplicationRecord
  has_many :users, through: :comments
  has_many :comments
  has_many :videos
  validates :name, presence: true
end
```
Video Serializer 
```js
class VideoSerializer < ActiveModel::Serializer
  attributes :id, :name, :url, :therapy

  def therapy
    object.therapy.id
  end
end
```
Therapy Serializer
```js
class TherapySerializer < ActiveModel::Serializer
  attributes :id, :name, :videos
  def videos
    object.videos.pluck(:id)
  end
end
```
Routes
```js
Rails.application.routes.draw do
  resources :comments, only: [:index, :show, :create, :update, :destroy]
  resources :videos, only: [:index, :show]
  resources :therapies, only: [:index, :show]
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```
Migration
```js
class CreateVideos < ActiveRecord::Migration[5.0]
  def change
    create_table :videos do |t|
      t.string :name, null: false
      t.string :url, null: false
      t.references :therapy, index: true, foreign_key: true, null: false

      t.timestamps
    end
  end
end
```
Index script for videos
```js
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/videos"
curl "${API}${URL_PATH}" \
  --include \
  --request GET \
  --header "Authorization: Token token=$TOKEN"

echo
```
Show Script for video
```js
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/videos/${ID}"
 curl "${API}${URL_PATH}" \
 --include \
 --request GET \
 --header "Authorization: Token token=$TOKEN"

 echo
```

**Comment by raq929** [comment]
What's the error on the script?

**Comment by raq929** [comment]
The rote is not valid. So, check your `config/routes.rb`. If that seems right, something might be wrong with how you're formulating the route in the request.

**Comment by s0phi4** [comment]
This is what I have in config routes

  resources :videos, only: [:index, :show]

And this is the error I get


🐤 ~/wdi/projects/ezspeaky-api (tables)
$ TOKEN=BAhJIiVmNzBkYzY5ZDExMTdlNDQ3Yzc1MDk1NTY5ZTkxNjVkNwY6BkVG--bf01a5efdde5f56a6a6846e349018825c71eeb03 THERAPY_ID=1 sh scripts/videos/show.sh
HTTP/1.1 404 Not Found
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 74bfba4a-a354-407f-baf5-356009647c3f
X-Runtime: 0.008646
Vary: Origin
Transfer-Encoding: chunked

{"error":{"message":"Not Found"}}

**Comment by raq929** [comment]
You're inheriting from `Protected controller`, so users will only be able to see videos they created. You probably want to inherit from `OpenReadController`?

**Comment by payne-chris-r** [comment]
Remember if the user doesn't *own* that video, the rails-template is set up to deliver 404: Not Found.

**Comment by s0phi4** [comment]
Problem solved! Follow advice from @raq929 and @payne-chris-r  and modified Controller to  OpenReadController.
200 OK

Thanks!
