### ISSUE TITLE
1-1 to discuss if my project fulfills requirements 

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/capstone-project#559]
I want to ask whether my project meets requirements. I also want to discuss how to make each piece flow together. Right now it looks basic and ugly.

**Comment by raq929** [comment]
These are two issues. In this one, please pitch your app to us, as I asked Andrew to in #541 .

Please open a separate issue about UI and include a diagram of what you would like it to look like. If you don't know what you want it to look like, include a diagram of what it looks like now, and describe in more detail what you want. 
Consultants, please don't respond about UI on this issue, as it should be a new one.
Thanks, all! (Gabby included.)

**Comment by ggabrakadabra** [comment]
I wanted to make an app that uses basically all of the NASA APIs. 
Currently, I have APOD (and a search for APOD), patents, sounds, mars rover, and NEO stats. A user can save APOD to a favorites list and comment on them, as well as see other users comments on their favorite pictures. 
Since users can create comments, read comments, update comments, and delete them, I think this fulfills CRUD. A user can also create, read, and destroy favorites. The user navigates through the website using a nav bar and they can change password and sign out.
I used more than one table, favorites, pictures, and comments.

**Comment by raq929** [comment]
That tells me why you think it fulfills requirements. I'm interested in your pitch (which later you can copy-paste into your README, btw). Why is your app awesome? What does it do? What value does it have for the user?

**Comment by ggabrakadabra** [comment]
I just want to know if it meets requirements?
So we need to have a project pitch in our readme in order to pass?

**Comment by raq929** [comment]
No, you have to pitch it to me in order for me to tell you whether it meets requirements. :) 
There is unfortunately not time to go over everyone's app and tell them whether it meets. 
It just happens to be a nice thing for employers to read in your README later.
I think you're probably fine in terms of complexity, from what I've seen earlier. But an argument for how it's complete would help.

**Comment by jrhorn424** [comment]
@ggwilliams You're being disrespectful when a senior asks you for something and you skirt the ask. You know better than that. Get it together.
