### ISSUE TITLE
Creating profile when registering: cannot register when profile has attached file

### ISSUE THREAD

**Issue by kaylal12** [ga-wdi-boston/capstone-project#56]
I have successfully been able to register and create a profile at the same time before adding paperclip to the profile model, but when I added the "has_attached_file" into the profile model, register no longer works and gives an error saying: 

```
NoMethodError (undefined method `profile_picture_content_type' for #<Profile:0x007f85b3d2c810>):
  app/controllers/auth_controller.rb:20:in `register'
```

this is my controller for creating a profile when registering:

```
def register
    @user = User.create(credentials)
    @user.build_profile(profile)

    if @user.save
      render json: @user, status: :created, location: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end
```

```
def profile
    params.require(:profile).permit(:first_name, :surname)
  end
```

It seems to still register a user to the database, but then gives a 500 error and does not create the profile.

**Comment by gaand** [comment]
It create a user because you call `User.create`.

The error from trying to save the profile causes the error logged.

**Comment by gaand** [comment]
What does your profile schema look like?

**Comment by kaylal12** [comment]
Of course, didnt run rake:db migrate for profiles. Seems good, thanks!
