### ISSUE TITLE
Requesting 1-1 to go over project requirements

### ISSUE THREAD

**Issue by ddobson** [ga-wdi-boston/capstone-project#561]
I would like a 1-1 to go over project requirements and make sure that I am on track.

The idea of my app is that a user can store a collection of cookbooks. When they create a cookbook they can enter the pages which contain recipes. For example pages 5 to 100. The server then builds an array of available pages using that data and will give the client a random page from that list. Cookbooks have recipes which also contain a start and end page. When a user creates a recipe the range of available pages in the cookbook will be removed.

I have some questions surrounding my implementation of this formula and want to be sure that I build any validations instructors feel are needed to meet requirements.

**Comment by raq929** [comment]
As I've explained to others with these questions, we simply don't have time to go over everyone's app one by one before presentation day. I wish we could. 
Please ask your questions here, and your concerns about validations, and we'll do our best to answer them.

**Comment by ddobson** [comment]
Closing this issue

**Comment by jrhorn424** [comment]
@ddobson If this isn't about meeting requirements, but a general question about an implementation, I'd be willing to meet with you and discuss.
