### ISSUE TITLE
Project UI

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/capstone-project#562]
I'm not sure what I want my project to look like. But I want it to be user friendly and flow well.
Right now, on the search page, I have panels with the search params and then panels showing NEO facts. I know this project can look better but I'm not sure what to do next to make it better.

this is my current project
![project](https://cloud.githubusercontent.com/assets/23526112/24467042/f1af9cb2-1480-11e7-8147-9765c5965314.jpg)
and here is the deployed version thus far
https://ggwilliams.github.io/pictures-app-client/

**Comment by tvcrawley** [comment]
Here's an article showcasing [UI Designs](http://www.creativebloq.com/web-design/examples-ui-design-7133429), this should be a good resource as you are designing your project. 

Note: 
- Notice how the example sites are laid out 
- While traversing through it ask yourself if the user can easily do x, y, z 
- Then apply those same questions to your project

The answer will help in determining what you should add (or take away)

**Comment by raq929** [comment]
Something like this might clean up the front page: http://getbootstrap.com/components/#nav-tabs

**Comment by raq929** [comment]
Did either of those help? Do you still want to talk more about this?
