### ISSUE TITLE
Uncaught Error: You must provide param `repos` to `generate`.

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/capstone-project#564]
This is my console error on my deployed site. This is the file its listing on my right side:
```
vendor-6325b888bf398c8cd6a4272ac2e064f5.js:2
```
My vendor folder only has one file in it: .gitkeep and that is empty, so I am not sure what to make of this console error.

**Comment by raq929** [comment]
It is trying to access a file that isn't there.
Do you have a `dist/` directory in the sources tab?
Or you can check this by looking at the `gh-pages` branch on gitHub.

If not, you did not correctly comment out `dist` in the `.gitignore`, build, commit, and push.

**Comment by raq929** [comment]
https://github.com/ga-wdi-boston/capstone-project/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20deployment%20

**Comment by alexkarasik** [comment]
I do have a dist directory and dist is commented out in .gitignore

**Comment by BenGitsCode** [comment]
I believe that was one of the last things we did together. Just to eliminate weird side effects with github pages as a possibility (cuz that's a thing) try this, just to confirm that's not the problem:

on gh pages branch
- `git push origin :gh-pages` this will delete your gh pages remote
- confirm dist is definitely commented out in gitignore ( think it is but checking again makes me happy)
- `ember build --environment=production`
- then push the subtree again. give it a solid minute or two and check in incognito. 

Is it exactly the same? Working? Or still not working but with a different error? I suspect it's the first or former option but let's confirm.

**Comment by alexkarasik** [comment]
after doing that stuff, I am not getting a 404 error displaying and no errors in my console.

**Comment by BenGitsCode** [comment]
and it's working? or you're not getting errors but nothing is showing?

**Comment by alexkarasik** [comment]
no, nothing is rendering at all. I am not getting errors, but nothing is showing

**Comment by alexkarasik** [comment]
It's back and working! I think this was a case of having to wait for it. Thanks.

**Comment by alexkarasik** [comment]
Sorry, but I just realized that it is only working in incognito mode for some reason... the 404 is still happening in a regular browser window.

**Comment by alexkarasik** [comment]
My understanding now is that it should only be working in incognito, so I guess this is taken care of.
