### ISSUE TITLE
Can't create new comment

### ISSUE THREAD

**Issue by lbreguet** [ga-wdi-boston/capstone-project#565]
After being able to make a `GET` on the comments, I've been trying to create a new comment using the nested resource. Using my curl script I'm getting a 422 error because it says that the `user must exist`. I know that this is definitely a back-end issue, but I just don't know what needs to be changed. I've tried adding `current_user` to no avail. 

Here is the create action in the controller:
```rb
def create
    post = Post.find(params[:post_id])

    @comment = post.comments.create(params[:comment])

    if @comment.save
      render json: @comment, status: :created
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end
```

Here is my curl script:
```sh
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/posts/1/comments"
TOKEN="BAhJIiVjZTc0YWRlZDllOTA4ZDA2YWZmZWYwYzdjODJlZTEyZAY6BkVG--d31c0b0d59784bb9616697ccf4948741e76715c3"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content_Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
  --data '{
    "comment": {
      "body": "oienrvoenovkerv"
    }
  }'
```

**Comment by raq929** [comment]
Can you post the server log?

**Comment by lbreguet** [comment]
Here is the output from the server:
```bash
HTTP/1.1 422 Unprocessable Entity
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 2ec04c1a-fe09-4489-b625-617c8e34ae1b
X-Runtime: 0.043228
Vary: Origin
Transfer-Encoding: chunked

{"user":["must exist"]}
```

**Comment by bernardlee** [comment]
Check #524.  I think that it might be the same issue.

**Comment by bernardlee** [comment]
Can you post the Comment model?

**Comment by lbreguet** [comment]
Sure here it is:

```rb
# frozen_string_literal: true
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end
```

**Comment by bernardlee** [comment]
What does the comments table look like?

**Comment by lbreguet** [comment]
The comments table in the schema:

```rb
create_table "comments", force: :cascade do |t|
    t.text     "body",       null: false
    t.integer  "user_id",    null: false
    t.integer  "post_id",    null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["post_id"], name: "index_comments_on_post_id", using: :btree
    t.index ["user_id"], name: "index_comments_on_user_id", using: :btree
  end
```

**Comment by bernardlee** [comment]
I think that the error is caused by attempting to save a record to the `comments` table without a `user_id`.  Check the `comment` record that you're creating and attempting to save.

**Comment by lbreguet** [comment]
The server gave this back when I checked the `comment` record:
```bash
<Comment id: nil, body: nil, user_id: nil, post_id: 1, created_at: nil, updated_at: nil>
```

So `post_id` is being seen because I've hard-coded into it the script.

**Comment by bernardlee** [comment]
According to your schema, the `body` and `user_id` fields can't be null, so those need to be filled before calling `save` on the instance of `Comment`.  Compare the `comments` table schema with your `CommentController`'s `create` method.

**Comment by lbreguet** [comment]
I don't really know what I should be comparing between the two. I thought that the `token` that is being passed would substitute the `user_id`.

**Comment by bernardlee** [comment]
A valid token sent to the back end will set `current_user` to an instance of `User` that corresponds to the user that the token belongs to.

Think of an instance of `Comment` as a blank row in the `comments` table that hasn't been saved yet.  It needs to have all of its columns filled with valid data before it can be saved.

**Comment by lbreguet** [comment]
I found a way to bypass the nested route because I can't get it to work. Instead of saving to the nested resource of `comments`, I'm saving to the main resource `comments`.

Here is what I changed in the controller:
```rb
def create
    @comment = current_user.comments.build(comment_params)

    if @comment.save
      render json: @comment, status: :created
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
```

And my curl script is now this:
```sh
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/comments"
TOKEN="BAhJIiUwMDlkM2IyNjRlMWIwZjBlMjJhYTIwZjUwMjdiODY5NQY6BkVG--f669171b96c87359ccde3db76d6a3ba8b470415b"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content_Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
  --data '{
    "comment": {
      "body": "oiendfdfdvsdfvjkbnskvbjskvkerv",
      "post_id": "2"
    }
  }'
```

This seems to work to create new comments.

**Comment by raq929** [comment]
If that works, and the nested route did not, I suspect you did not nest it in your `config/routes.rb`

**Comment by lbreguet** [comment]
So I just had to add a new instance of `current_user` to `@comment.user`. This allowed create to work on the nested resource.
Here is the update create controller:
```rb
def create
    post = Post.find(params[:post_id])

    @comment = post.comments.create(comment_params)
    @comment.user = current_user

    if @comment.save
      render json: @comment, status: :created
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end
```
