### ISSUE TITLE
Editable Causing Causing Buttons to Dissapear

### ISSUE THREAD

**Issue by cshea93** [ga-wdi-boston/capstone-project#566]
While users do not have the option to edit/delete other user's posts, my update and delete buttons are disappearing after one use. I have tried a variety of ways to get around this but nothing seems to be working.

post-index.hbs component template
![image](https://cloud.githubusercontent.com/assets/16327726/24473171/55670fd2-1496-11e7-8490-613093631939.png)

post-index.js component
![image](https://cloud.githubusercontent.com/assets/16327726/24473212/7baf87fa-1496-11e7-878c-77031128f1b2.png)

post model

![image](https://cloud.githubusercontent.com/assets/16327726/24473270/a72c5642-1496-11e7-834b-baab9a701080.png)

**Comment by cshea93** [comment]
I should clarify, when I remove the {{#if editable}} statement from post-index.hbs, the buttons persist, but then other users have the ability to edit/delete other user's work.

**Comment by raq929** [comment]
I find this issue hilarious for some reason.

**Comment by raq929** [comment]
OK. So, the buttons and the whole post _should_ disappear after delete, yes?
So update is the problem. Are you successfully updating the post? What do you see in the network tab after update? I'm wondering if you're loosing 'editable' when you update somehow.

**Comment by cshea93** [comment]
Yes, both should disappear after delete. 

I am getting a status 200 in the network tab.

**Comment by raq929** [comment]
Are they disappearing after delete?

**Comment by raq929** [comment]
What is the data you are sending on the request? (Network tab)
It seems like you're updating the post but accidentally updating editable to false. Or, more likely undefined. Can I see how you're editing the post?

**Comment by cshea93** [comment]
Yes delete is disappearing as it should; both buttons are disappearing after as post is updated for the first time.

**Comment by cshea93** [comment]
thats the preview of the data below:
![image](https://cloud.githubusercontent.com/assets/16327726/24475568/43a2cf54-149e-11e7-8de6-0373a821292f.png)

**Comment by cshea93** [comment]
I'm editing the post with these files specifically.

![image](https://cloud.githubusercontent.com/assets/16327726/24475601/61a6f8c2-149e-11e7-9dae-cf15abff49be.png)

![image](https://cloud.githubusercontent.com/assets/16327726/24475620/71a58d6a-149e-11e7-886d-7b4d6edb2b9b.png)


![image](https://cloud.githubusercontent.com/assets/16327726/24475639/8a3b3c6c-149e-11e7-93c6-f94453d3d8d1.png)


![image](https://cloud.githubusercontent.com/assets/16327726/24475651/95213b86-149e-11e7-915c-e82761a0bf66.png)

**Comment by cshea93** [comment]
![image](https://cloud.githubusercontent.com/assets/16327726/24475673/b0e01c84-149e-11e7-9c0c-6731a453ff01.png)

**Comment by raq929** [comment]
Can I see where you define the model? Probably in the route?

**Comment by cshea93** [comment]
![image](https://cloud.githubusercontent.com/assets/16327726/24475692/c8154456-149e-11e7-833f-1314e19ccae1.png)

**Comment by cshea93** [comment]
![image](https://cloud.githubusercontent.com/assets/16327726/24475711/d48c9626-149e-11e7-9a56-0c93fb7fa843.png)

**Comment by cshea93** [comment]
model hook

![image](https://cloud.githubusercontent.com/assets/16327726/24476196/6f1464d4-14a0-11e7-951f-ed3024efd459.png)

**Comment by cshea93** [comment]
controller coming

**Comment by cshea93** [comment]
![image](https://cloud.githubusercontent.com/assets/16327726/24476233/915ab5de-14a0-11e7-9859-c71369fdbe0e.png)

I took out the 'private' stuff at the bottom of the controller yesterday....could that be something here?

**Comment by raq929** [comment]
Don't allow `user_id`! That is a security risk and means you don't have ownership. The current_user thing will set the user id.

**Comment by raq929** [comment]
Umm.... yes. You need that stuff. Probably.

**Comment by raq929** [comment]
Come see me in classroom 4 if you're still here.

**Comment by cshea93** [comment]
I removed user_id requirement from my post_params in my post_controller. Solved the problem, for some reason....
