### ISSUE TITLE
1-1 to discuss if my project fulfills requirements

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/capstone-project#567]
I would like to know where I stand with requirements in order to improve my planning for the rest of today and tomorrow.
Deployed link: https://doremaxime.github.io/gear-frontend/
Front-end repo: https://github.com/doremaxime/gear-frontend
Back-end repo: https://github.com/doremaxime/gear-backend

**Comment by raq929** [comment]
@jrhorn424 tell me that this is something we should have discussed when you planned your app. Today is too late to figure that out.

I say, we cannot review everyone's app before presentation day. Please pitch your project to me and explain how it is a complete app. (A la #541) Have others in the class, and at least one person who is not it it, use your app in strange ways to try to break it. Fix any bugs. Be sure form fields clear, and anything that users say is weird, try to make not weird.  You are probably fine. :)

**Comment by doremaxime** [comment]
Not sure what you mean by the first line. I did plan it and talked about it with you.
To clarify, since some requirements are not specific and uses words such as "likely means" instead of "must" for example,  or "a visually impressive design" which is opinionated, I am wondering if it requirements are met. 
Thank you for the issue link, I will do as suggested and close the issue in the mean time :)

**Comment by jrhorn424** [comment]
@doremaxime I apologize for miscommunication, but I intended everyone to hear this on Monday: "be a complete product" is a **requirement**, CRUD on multiple resources and multiple relationships are **advice**.

Using bootstrap is enough to accomplish "visually impressive design". Using our template, and not using *any* of bootstrap's built-in styling features is **not** enough. Anyway, "visually impressive" is something necessary for an exceeds, not a meet.
