### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/capstone-project#570]
#tbt to the solution [here](https://github.com/ga-wdi-boston/capstone-project/issues/529), so the date shows up on the browser, but in GMT, so _technically speaking_ it's the "correct time" based on the input, but realistically it's not.
Basically if I put in the date "2017-01-01" for couchpost.dateNeeded, Ember spits out
```
Sat Dec 31 2016 19:00:00 GMT-0500 (EST)
```
which I guess is technically not wrong if we assume I'm inputting date by GMT, but it's not ideal. Does anyone know a good way to reformat this? My code is in the issue referenced.

**Comment by raq929** [comment]
Ember seems to think you should make a handlebars helper. It also seems like moment.js is built in and accessible in Ember? I'm unclear on that. But you can try it.
https://guides.emberjs.com/v2.12.0/templates/writing-helpers/

**Comment by raq929** [comment]
http://codepen.io/mthouve/pen/gbebEr

**Comment by payne-chris-r** [comment]
HELPERS ARE AWESOME!!!

**Comment by raq929** [comment]
@payne-chris-r how are you so excited so late at night.

**Comment by raq929** [comment]
Any update on this @laurpaik?

**Comment by laurpaik-zz** [comment]
Sorry, I was working with Yen for a bit on her project. Figuring out how to write this helper, will update when I have something working or if I get really stuck.

**Comment by laurpaik-zz** [comment]
Had trouble actually importing moment in Ember for some reason; it didn't like `import moment from 'moment'` whenever I used it, so after a while I went a simpler route. Since each date was formatted the same exact way, I just generated a helper 'format-date' that looks like:
```js
export function formatDate(params) {
  let day = params.toString();
  return day.slice(0, 15);
}
```
 and then in the template:
```hbs
{{profile.givenName}} {{profile.surname}} needs a couch near {{couchpost.location}} on {{format-date couchpost.dateNeeded}}
```

Thank you for pointing me to helpers, and shout out to @jwaskow for helping me!

**Comment by laurpaik-zz** [comment]
Reopening because I just realized it's just making the date nicer to look at, but the time zone is still an issue.

**Comment by jrhorn424** [comment]
https://momentjs.com/timezone/

**Comment by bernardlee** [comment]
Try installing [Moment.js](https://momentjs.com) through bower rather than npm and then following the instructions at [Ember.js - Addons and Dependencies: Managing Dependencies](https://guides.emberjs.com/v2.12.0/addons-and-dependencies/managing-dependencies/).

**Comment by laurpaik** [comment]
Turns out the timezone issue was a back-end... type needed to be datetime, not date.

**Comment by laurpaik-zz** [comment]
Finally officially resolved by generating transform with `ember generate transform custom-date`
```js
export default DS.Transform.extend({
  deserialize(serialized) {
    return moment.utc(serialized).format('MMMM Do YYYY');
  },

  serialize(deserialized) {
    return deserialized;
  }
});
```

*couchpost model*
```diff
export default DS.Model.extend({
  location: DS.attr('string'),
-  dateNeeded: DS.attr('date'),
+  dateNeeded: DS.attr('custom-date'),
  couchFound: DS.attr('boolean'),
  profile: DS.belongsTo('profile', { async: true }),
  editable: DS.attr('boolean'),
});
```
