### ISSUE TITLE
user notification

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/capstone-project#571]
If a user tries to sign up with an already taken email, must she be specifically informed that it is taken?
Or is a div shaking right to left, indicating an error, like in my [first](https://doremaxime.github.io/tic-tac-toe/) and [second](https://doremaxime.github.io/daily-boulders/) project considered ok?

**Comment by bernardlee** [comment]
If it wasn't a problem with your first two projects, then I don't think that it will be a problem with this project either.  Specificity is always nice though.

**Comment by doremaxime** [comment]
Thank you!
