### ISSUE TITLE
Sign Up Form Clearing Issue

### ISSUE THREAD

**Issue by cob0910** [ga-wdi-boston/capstone-project#572]
I found a bug where if a user signs up, signs out, then goes back to the sign up form the prior input is still there. Technically, they couldn't do anything with it since the new account already exists but as a user it isn't ideal to see previously submitted input still there.

`routes/sign-up.js`
```
import Ember from 'ember';

export default Ember.Route.extend({
  auth: Ember.inject.service(),
  flashMessages: Ember.inject.service(),

  actions: {
    signUp (credentials) {
      this.get('auth').signUp(credentials)
      .then(() => this.get('auth').signIn(credentials))
      .then(() => this.transitionTo('application'))
      .then(() => {
        this.get('flashMessages')
        .success('Successfully signed-up! You have also been signed-in.');
      })
      .catch(() => {
        this.get('flashMessages')
        .danger('There was a problem. Please try again.');
      });
    },
  },
});
```

**Comment by cob0910** [comment]
After some trial and error I found a solution.

In the same file `route/sign-up.js` update the signUp action:

I have tested locally and deployed and it works!

```
  actions: {
    signUp (credentials) {
      this.get('auth').signUp(credentials)
      .then(() => this.get('auth').signIn(credentials))
      .then(() => {
        credentials.password = null;
        credentials.email = null;
        credentials.passwordConfirmation = null;
        this.transitionTo('application');
      })
```

**Comment by jrhorn424** [comment]
Hm. This isn't a great workaround. Would you mind filing an issue on `ember-auth` @cathyob? I think it's something we need to address. Thanks!

**Comment by cob0910** [comment]
@jrhorn424 - @akgoode also implemented this and neither of us have seen any side effects so far. We were both worried that this would count as a bug since the user might view it as a security issue and leaving the values looks bad. Should we take it out of our projects?

Issue on ember-auth - https://github.com/ga-wdi-boston/ember-auth/issues/15
