### ISSUE TITLE
Incorporating notify.js

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/capstone-project#573]
With the use of these two links: [1](https://notifyjs.com/) [2](http://www.jqueryscript.net/other/jQuery-Plugin-To-Create-Fixed-Stackable-Notifications-Notification.html), I have been trying to incorporate a user notification when a user successfully create a "gear". 

I addded the following to the ```<head>``` in the index.html as such:
```html
<head>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <script src="js/jquery.notification.min.js"></script>
  <link rel="stylesheet" href="css/jquery.notification.css">
</head>
```

And call the function in my ```createGearSuccess``` function in my ```ui.js``` as such:
```javascript
const createGearSuccess = () => {
  $.notify('Great', 'Created successfully', 'success', 5000)
}
```

However, when testing it, the browser (Chrome) console indicates that it is not a function:

![screen shot 2017-03-29 at 8 05 12 pm](https://cloud.githubusercontent.com/assets/24608045/24481833/1772db6e-14bb-11e7-85d1-89f7c66800be.png)

I believe that somehow the links and scripts are not connecting properly. Is that possible? Do I need to somehow require a certain file in my ```ui.js```?

**Comment by doremaxime** [comment]
Update:
I have tried adding ```<script src="notify.js"></script>``` in the head but all the links cannot be found and come back as 404..
The browser console informs the following:
![screen shot 2017-03-29 at 8 22 15 pm](https://cloud.githubusercontent.com/assets/24608045/24482203/8ac5fb08-14bd-11e7-9764-e948e5856c82.png)

**Comment by raq929** [comment]
Yeah, webpack won't like that. You'll have more luck incorporating it as an npm module. 
https://www.npmjs.com/package/notify-js

**Comment by raq929** [comment]
Haha nevermind that's a totally different package that has nothing to do with the thing you're talking about. Same name, though! I'm going to ask Antony if he can help you incorporate this using our build tools.

**Comment by raq929** [comment]
The library you're using is: https://notifyjs.com/, correct?

**Comment by doremaxime** [comment]
Yes, that is correct.

**Comment by doremaxime** [comment]
Any word from Antony?

**Comment by raq929** [comment]
Yes! Download the minified file. Put it in a folder in your app, like `vendor`. Require it in a `document.ready()` function in `index.js` or some such. No ember, right?

**Comment by doremaxime** [comment]
correct, no ember.
I'll try that and update

**Comment by doremaxime** [comment]
A search doesn't return any folder by the name of ```vendor``` so i'll make one.

**Comment by doremaxime** [comment]
Solution:

Download **notify.min.js** on [this](https://notifyjs.com/) site and save it in your repo.
Require it in a ```document.ready()``` function in ```index.js``` (ga-wdi-boston etiquette).

when calling the function, having 4 arguments (title, message, type, timer) did not work for me, such as:
 ```javascript
$.notify('Nice', 'your item is stored', 'success', 2000)
````
The 2nd link in my first comment, which shows 4 arguments, must be outdated..

Instead, having 2 arguments works (taking out the first being the title, and the last being the timer) such as:
```javascript
  $.notify('your item is stored', 'success')
```
Note: the timer can be changed in the downloaded file but the default is about 4 seconds.
Check the site though because you can do a lot more!
