### ISSUE TITLE
Nesting attributes in Ember

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/capstone-project#574]
Hi, I've been trying to get a couchpost's owner to display, and when I call it it usually just displays `<DS.PromiseObject:ember545>` for each owner. I used it as a placeholder while I was trying to fix other things, but now I'm here!

the questionable line in my template:
*templates/components/couchpost-list/couchpost.hbs*
```hbs
{{couchpost.profile}}found a couch near {{couchpost.location}} for {{couchpost.dateNeeded}}
```
with `couchpost.profile` being the placeholder

*models/couchpost.js*
```js
export default DS.Model.extend({
  location: DS.attr('string'),
  dateNeeded: DS.attr('date'),
  couchFound: DS.attr('boolean'),
  profile: DS.belongsTo('profile', { async: false }),
  editable: DS.attr('boolean'),
});
```
*models/profile.js*
```js
export default DS.Model.extend({
  givenName: DS.attr('string'),
  surname: DS.attr('string'),
  gender: DS.attr('string'),
  dob: DS.attr('date'),
  couchposts: DS.hasMany('couchpost'),
  user: DS.belongsTo('user'),
});
```
*templates/couchposts/index.hbs*
```hbs
{{#each model as |couchpost|}}
  {{couchpost-list/couchpost
    couchpost=couchpost
    delete='deleteCouchpost'
  }}
{{/each}}
{{#link-to 'couchposts.new'}}Post a couch request!{{/link-to}}
<br/>

{{#link-to 'index'}}Back{{/link-to}}
```
*router*
```js
const Router = Ember.Router.extend({
  location: config.locationType,
});

Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users', function() {});
  this.route('couchposts', function() {
    this.route('new');
  });
  this.route('couchpost', { path: '/couchposts/:couchpost_id' }, function() {
    this.route('edit');
  });
});

export default Router;
```

Finally, I was playing around with serializers, so here's this:
*serializers/couchpost.js*
```js
export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    profiles: { embedded: 'always' }
  }
});
```

per suggestion from [theJSGuy](http://thejsguy.com/2016/01/29/working-with-nested-data-in-ember-data-models.html) and [the documentation](https://emberjs.com/api/data/classes/DS.EmbeddedRecordsMixin.html), but it's a little late so I'd like to test it out more with fresh eyes in the morning. Mostly I want to file this because it is an issue I have, and I want people to know about it, but I'm still working on it too.

I don't know much about Ember serializers, but it seemed a lot nicer than [nesting another route](https://emberjs.com/api/classes/Ember.Route.html#method_modelFor).

Does anyone have thoughts on this? Since adding the serializer the PromiseObject stopped showing up, as did the date, for some reason, so I'm not sure how to structure the template to point it to the model I want. I tried `{{couchpost.profile}}`, `{{couchpost.profile.givenName}}`, `{{couchpost.profile.id}}`, and `{{profile.givenName}}` so far, just trying to get *something* to show up. Have not moved to `date` yet, but I have a feeling it has something to do with [the solution to this issue from earlier today](https://github.com/ga-wdi-boston/capstone-project/issues/529).

**Comment by raq929** [comment]
Please see Jeff in Tremont at 9:30 am

**Comment by laurpaik-zz** [comment]
Turns out I didn't need the serializer! Shout out to @sofistication for helping me debug:
*app/templates/couchposts/index.hbs*
```diff
{{#each model as |couchpost|}}
  {{couchpost-list/couchpost
    couchpost=couchpost
+    profile=couchpost.profile
    delete='deleteCouchpost'
  }}
{{/each}}
{{#link-to 'couchposts.new'}}Post a couch request!{{/link-to}}
<br/>

{{#link-to 'index'}}Back{{/link-to}}
```

*app/templates/components/couchpost-list/couchpost.hbs*
```diff
-  {{couchpost.profile.givenName}}found a couch near {{couchpost.location}} for {{couchpost.dateNeeded}}
+  {{profile.givenName}}found a couch near {{couchpost.location}} for {{couchpost.dateNeeded}}
```

backend:
*couchpost serializer*
```diff
class CouchpostSerializer < ActiveModel::Serializer
-  attributes :id, :location, :date_needed, :couch_found, :editable
+  attributes :id, :location, :date_needed, :couch_found, :profile, :editable

  def editable
    scope == object.profile.user
  end

  def profile
-    object.profiles.pluck(:id)
+    object.profile.id
  end
end
```
