### ISSUE TITLE
Ember services data

### ISSUE THREAD

**Issue by dsweetser** [ga-wdi-boston/capstone-project#576]
Hey Team!

I'm having a bit of trouble figuring out if I'm dealing with the right data here.  I'm trying to define a current order to add additional items to.  I currently have this:

services/cart.js
```
import Ember from 'ember';

export default Ember.Service.extend({
  currentOrder: null,
});
```
and I'm trying to define and capture it when I create an order here:
```
import Ember from 'ember';

export default Ember.Route.extend({
  cart: Ember.inject.service(),

  model () {
    return this.get('store').createRecord('order', {});
  },

  actions: {
    createOrder(order){
      order.save()
      .then((response) => Ember.set(this.cart, 'currentOrder', response))
      .then(() => Ember.get(this.cart, 'currentOrder'))
      .then(() => this.transitionTo('shop'));
    },
    cancel () {
      history.back();
    },
  },
});
```

I've tried various other permutations, such as cart.set('currentOrder', response) with similar luck.  Like everything else has been in Ember, I feel like there's something here just slightly beyond my grasp of the subject matter...

Thanks for the help team!

**Comment by raq929** [comment]
Is the response what you expect it to be?

**Comment by raq929** [comment]
Also, I think `this.set` only takes two arguments. What are you trying to set to what?

**Comment by dsweetser** [comment]
so here's my ideal functionality that I'd like to build towards: I'm looking for a way to store the created order ID so I can reference it later. I could probably get around this by having users enter in the order ID to enter a stamp into that order as a workaround.  I'm sleepy enough that that comment may not make sense to anybody who is not me and I'll see if I can't come up with a workaround in the morning that uses that rather than services.
