### ISSUE TITLE
Problems getting dataset_id for join table from Ember

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/capstone-project#577]
This issue is I believe very similar to #532 but I read through it and was unable to solve my problem.

I have a resource, Visualization, which on my back end is a join between Users and Datasets. The user ownership is handled by the controller using `current_user`, so I don't need to (an really shouldn't, of course) send a user id from the front end. However, I do need to send the dataset ID, which I spent most of the afternoon trying to do with little success. What I have currently isn't necessarily the most Ember-y way to do this, since really I should probably refactor most of this into a component, but my attempts to solve it have led me to believe that the issue isn't that I am putting these things in the route. What I have right now in my `dataset/save` route is:

`routes/dataset/save`:
```js
import Ember from 'ember';

export default Ember.Route.extend({
  actions: {
    createVisualization (color, model) {
      let datasetId = model.get('id');
      let visualization = this.get('store').createRecord('visualization', {
        color: color
      });
      visualization.set('dataset_id', datasetId);
      console.log(visualization.get('dataset_id'));
      visualization.save()
        .then(() => this.transitionTo('visualizations'));
    }
  }
});
```

`templates/dataset/save`:
```hbs
<h3>Customize visualization for {{model.name}} {{model.year}}</h3>
<div class="form-group">
  <label for="graph-color">Graph color</label>
  {{input type="text"
          class="form-control"
          id="graph-color"
          placeholder="Enter a hex code!"
          value=color}}
</div>
<button class="btn btn-info btn-sm" {{action "createVisualization" color model on="click"}}>Save</button>

{{visualizr-dataset/graph dataset=model color=color}}
```

The `console.log` is giving me the correct dataset id, but the server returns a 500 error, and when checking the logs there I am seeing that the `dataset_id` param is `nil`. I have tried this a number of different ways and even when I can verify through console logs that the correct dataset id is being set, I am having the same problem. I believe part of the problem is that I don't quite understand how relationships in Ember work, since the relationships have been defined on the Ember models:

`models/dataset`:
```js
import DS from 'ember-data';
import Ember from 'ember';

export default DS.Model.extend({
  name: DS.attr('string'),
  year: DS.attr('number'),
  visualizations: DS.hasMany('visualization'),
  zipcodeCount: DS.attr(),

  saved: Ember.computed('visualizations', function () {
    let visualizations = this.hasMany('visualizations');
    return visualizations.ids().length;
  }),

  formattedCount: Ember.computed('zipcodeCount', function () {
    return Object.keys(this.get('zipcodeCount')).map((e) => {
      return {
        value: this.get('zipcodeCount')[e],
        label: e
      };
    });
  }),
});
```

`models/visualization`:
```js
import DS from 'ember-data';

export default DS.Model.extend({
  user: DS.belongsTo('user'),
  dataset: DS.belongsTo('dataset'),
  color: DS.attr('string')
});
```

I know that people have had similar issues and not yet figured out how to get this working properly, but I would appreciate some help with getting the dataset id to send with the request.

**Comment by raq929** [comment]
See Jeff at 9:30 in Tremont. He's also helping Lauren with a join table issue. It's more of a 1:2.

**Comment by samordonez** [comment]
I fixed it!

So it was definitely a question me not understanding Ember properly. I was trying to give Ember just an id to send, but what it wants is the actual Ember Data model, from which it extracts to id to send to the server.

I changed my route action to the following:

```js
import Ember from 'ember';

export default Ember.Route.extend({
  actions: {
    createVisualization (color, model) {
      // let datasetId = model.get('id');
      let visualization = this.get('store').createRecord('visualization', {
        color: color
      });
      visualization.set('dataset', model);
      console.log(visualization.get('dataset_id'));
      visualization.save()
        .then(() => this.transitionTo('visualizations'));
    }
  }
});
```

where model is the dataset model being passed to the action by the template calling it.
