### ISSUE TITLE
Adding an "add" actions button

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/capstone-project#578]
I want to add the individual results of my API request from one view state to another by clicking a button, but I am having a lot of trouble finding out how to write the action to do this. 
I have this in my repos template:
```
{{log model.totalCount}}

{{#each model.items as |links|}}
<div class="wrap">
<h1><a href={{links.html_url}}>{{links.full_name}}</a></h1>
<h5>Language: {{links.language}}</h5>
<h5>Score: {{links.score}}</h5>
<h5>Number of Forks: {{links.forks}}</h5>
<h5>Description: {{links.description}}</h5>
{{!-- <a href={{links.html_url}}>{{links.full_name}}</a> --}}
<button type="submit" class="btn btn-primary" {{action 'save'}}>Add to Favorites</button>
<br>
</div>
{{/each}}
```
And I want that action from the save button to move a copy of these individual divs from the repos-results page/view state to a favorites page/view state.

**Comment by raq929** [comment]
Here's my understanding of what you're saying (correct me if I'm wrong).
1. The user clicks a the "Add to Favorites" button
2. An api request is made adding these links to the user's favorites
3. There is a change in view state taking the user to their favorites page.

What is happening now when the user clicks the button?

**Comment by alexkarasik** [comment]
I already have the API request rendering the data I want from the github API on a 'search' view state. I want a button to add individual divs/results from this view state to a 'favorites' view state that becomes the data that belongs to the individual user. 
I have the button appearing in these divs, but need to write the action that transfers the div from this view to the 'favorites' view, so the button does not have any action associated with it yet. I don't need to take it out of the results view, I just want to add it to the favorites view, so the same data will be appearing in two places.
I think I need to use transitionTo, which I understand transfers view states, but i am not sure how to actually add the content/data to this view state in the same way it is rendered in my search results.

**Comment by raq929** [comment]
I don't understand. If clicking the button doesn't persist any data to the database, then the favorite isn't saved. 
You need an action on the `Add to Favorites` button. You have one now, which is `save`. You'll need to send that action up to the route, where you can use `transitionTo` to move to a new view state.

**Comment by alexkarasik** [comment]
Ok, so I am writing the 'save' action in the repo route, right? Repos is the template this button is inside of.

**Comment by raq929** [comment]
You are in a component. The save action needs to be written in the component's `js` file and passed up to it's parent route. The route will then handle the action, persisting the relevant data to the database, and transition to the other view.

**Comment by alexkarasik** [comment]
I've realized that this will not work until I've got the curl script working in the back end, so I am going to go back to that and once that is working I will try this again. The data can not be saved the way I want where it is owned by the user until I work that out.

**Comment by alexkarasik** [comment]
Alright, I got my create script working in the backend, so the error I am getting in my console when I click the "Add to Favorites" Button is an "uncaught Ember error": 
```

"Nothing handled the action 'save'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble."
```
I need to make a component for each result from the search. This is what I had in my repos template that was working, so I moved it a component I generated called returned-repo:
```
{{log model.totalCount}}

{{#each model.items as |links|}}
<div class="wrap">
<h1><a href={{links.html_url}}>{{links.full_name}}</a></h1>
<h5>Language: {{links.language}}</h5>
<h5>Score: {{links.score}}</h5>
<h5>Number of Forks: {{links.forks}}</h5>
<h5>Description: {{links.description}}</h5>
{{!-- <a href={{links.html_url}}>{{links.full_name}}</a> --}}
<button type="submit" class="btn btn-primary" {{action 'save'}}>Add to Favorites</button>
<br>
</div>
{{/each}}
```
I am not sure if this is the right place to put it and am confusing myself about the flow of the data from the component to the route. I believe the component connects to the route, which is suppsoed to hold the action for 'save'.

**Comment by alexkarasik** [comment]
I think I can better rephrase my question. I currently have a template called repos.hbs that has the content i posted above. I need this to be a component so that I can write an action that moves that content from the search/results page to the favorites page and stores it in the users' database. 
I have generated a component several times now to try to do this, but it has not been working. 
I am getting an error on the action, but before I fix that I need to make the component work for the results. i don't understand what should be different about this new component than what I have posted above. 
I then need to write the save action that saves this data to the users' profile.

**Comment by raq929** [comment]
Please post (and label with the file path):
- the route js file
- the route .hbs file
- the component js file
- the component hbs file

**Comment by alexkarasik** [comment]
Here is the repos.hbs file. I know this action will not work yet, I based it off the mySearch function:
```
import Ember from 'ember';

export default Ember.Route.extend({
  ajax: Ember.inject.service(),
  // model: function(params) {
  //     return this.get('store').findAll('search', params);
  // },
  actions: {
    mySearch(search) {
      this.get('ajax').request(`/searches/${search}`)
      .then((data) =>{
        console.log(data);
        return this.transitionTo('repos', data);
      });
    },
    save(search) {
      this.get('ajax').request(`/searches/${search}`)
      .then((data) =>{
        console.log(data);
        return this.transitionTo('favorites', data);
      });
},
  }
});
```
Here is the repos.js file:
```
import Ember from 'ember';

export default Ember.Route.extend({
  model: function(){
    let url = 'https://api.github.com/';
    return Ember.$.getJSON(url).then(function(data){
      return data;
    });
  },
  save(repo) {
    console.log('repos route');
    repo.save();
  }

});
```
Here is my repos component:
```
{{log model.totalCount}}

{{#each model.items as |links|}}
<div class="wrap">
<h1><a href={{links.html_url}}>{{links.full_name}}</a></h1>
<h5>Language: {{links.language}}</h5>
<h5>Score: {{links.score}}</h5>
<h5>Number of Forks: {{links.forks}}</h5>
<h5>Description: {{links.description}}</h5>
{{!-- <a href={{links.html_url}}>{{links.full_name}}</a> --}}
<button type="submit" class="btn btn-primary" {{action 'save'}}>Add to Favorites</button>
<br>
</div>
{{/each}}
```
Here is my search-result.js:
```
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    mySearch() {
      this.sendAction('mySearch', this.get('search'));
    },
    save(data){
      this.sendAction('save', this.get(data));
    }
  }
});
```

I know these files have a lot of errors, but they are just my starting points. The first thing I need to do is make a component based on repos.hbs which is actually a template at the moment.

**Comment by raq929** [comment]
I'm not clear on which of these files are routes and which are components. Can you edit to include the full path of each file?

**Comment by alexkarasik** [comment]
The first is routes/search.js
The second is routes/repos.js
The third is templates/repos.hbs
The fourth is components/search-result.js

I would really appreciate being able to sit down for a one on one for this. I am not understanding something fundamental here. 
I've been working on this particular issue for most of the day today and am exhausted from it.

**Comment by jrhorn424** [comment]
Hi @alexkarasik, has this been addressed?

**Comment by alexkarasik** [comment]
Yes, I know what to do now. it was not working because I did not have an action as an ajax request written properly and I will take care of that today and clean my project up this week. Thanks
