### ISSUE TITLE
Can't delete a post because of comments

### ISSUE THREAD

**Issue by lbreguet** [ga-wdi-boston/capstone-project#580]
I can't delete a post because there are comments attributed to it. I'm wondering if it's something I have to change in my `posts_controller.rb`. I can a post that has no comments, but not one with them. I've been trying to another method to the destroy action:
```rb
@post = current_user.posts.find(params[:id])

def destroy
    @post.comments.destroy
    @post.destroy

    head :no_content
end
```

This, however, does not seem to be working.

**Comment by raq929** [comment]
You probably want something like this on your model: http://stackoverflow.com/questions/331394/can-i-set-up-cascade-deleting-in-rails

**Comment by lbreguet** [comment]
Fixed. Just changed something in the model for posts.

Here's code:
```rb
# frozen_string_literal: true
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end
```

Thanks @akgoode
