### ISSUE TITLE
Api promisses 

### ISSUE THREAD

**Issue by wilsonkaya** [ga-wdi-boston/capstone-project#582]
After making my post request I need to make api.index() request to refresh my reviews.
 My api needs certain "id" object. I get this data from my click event, create an object with it and send data with api.index(id). The issues is even though  the post request fails, api.index() being called  because of having a param event though it is inside of .then() promise. How can I overcome this issue ?

```
const onPostReview = function(event){
  event.preventDefault()
  let data = getFormFields(event.target)
  let rental = data.review.rentals
  let id  = {
    rentals: rental
  }
  api.post(data)
  .then(
  api.index(id)
  .then(ui.onIndexSuccess)
  .catch(ui.onIndexError)
    )
  .catch(ui.onPostError)
}

```

**Comment by raq929** [comment]
I'm confused about what's going on here. You're calling something `id` that isn't an `id`, and sending it to your `index` request. `GET` requests shouldn't need data.

**Comment by raq929** [comment]
Come on back, I'll take a look at it.

**Comment by wilsonkaya** [comment]
We have wrapped the api.index() in a function so that it won't be called right away. And I have changed the id into object to not cause confusion.

```
const onPostReview = function(event){
  event.preventDefault()
  let data = getFormFields(event.target)
  let rental = data.review.rentals
  let obj  = {
    rentals: rental
  }
  api.post(data)
  .then(() => {
    return api.index(obj)
  })
  .then(ui.onIndexSuccess)
  .catch(ui.onIndexError)
  .catch(ui.onPostError)
}
```
