### ISSUE TITLE
Flipster Issue

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/capstone-project#584]
I decided to implement flipster to view the mars rover photos. 

A user enters the date for the photos they want to see, then flipster shows the slideshow. But this only works for one date, if I try to search another date, it breaks and doesn't show anything. But there are no console errors.

This is my function
```
const searchMarsRoverApi = function () {
  const earthDate = $('#earth-date').val()
  const data = {
    search: {
      query: earthDate
    }
  }
  $.ajax({
    headers: {
      Authorization: `Token token=${store.user.token}`
    },
    url: config.apiOrigin + '/search/mars',
    method: 'POST',
    data: data
  }).done(function (results) {
    $('.mars-list').empty()
    for (let i = 0; i < results.photos.length; i++) {
      const singleSearchResult = marsTemplate(results.photos[i])
      $('.mars-list').append(singleSearchResult)
    }
    $('#mars-search-results').flipster({
      itemContainer: 'ul',
      itemSelector: 'li',
      style: 'coverflow',
      start: '0',
      spacing: -0.6
    })
  })
}
```
handlebars file
```
<li><img src="{{img_src}}" style="width: 500px; height: 500px;"></img>
</li>
```

html
```
         <div id="mars-search-results">
           <ul class="mars-list" style="height: 500px; width: 100%;">
           </ul>
         </div>
```
After clicking for the second search, the mars-list div clears but nothing comes up. 
I tried to clear the mars-search-results but that makes it display nothing. 
I think it's a problem with trying to clear the previous results and then put the new results in their place but it's being glitchy. Some times pictures show up but then they aren't in a slideshow.

**Comment by bernardlee** [comment]
Is this an external library?  If so, then can you provide a link to it?

**Comment by ggabrakadabra** [comment]
I followed this 
https://github.com/drien/jquery-flipster

and I have it in my package json and in the webpack file and in my html and in the scss file. So all of the required things are present when loading my page.

**Comment by bernardlee** [comment]
Check the Methods section on that page.  The last method sounds like it might solve your issue.  If not, then I'll take a look at it.

**Comment by raq929** [comment]
Also, in order for it to work on your deployed site, you will have to install it as an npm module or do what Max did in #573. :)

**Comment by ggabrakadabra** [comment]
I added 
```
const searchMarsRoverApi = function () {
  const earthDate = $('#earth-date').val()
  const data = {
    search: {
      query: earthDate
    }
  }
  $.ajax({
    headers: {
      Authorization: `Token token=${store.user.token}`
    },
    url: config.apiOrigin + '/search/mars',
    method: 'POST',
    data: data
  }).done(function (results) {
    $('.mars-list').empty()
    for (let i = 0; i < results.photos.length; i++) {
      const singleSearchResult = marsTemplate(results.photos[i])
      $('.mars-list').append(singleSearchResult)
    }
    $('#mars-search-results').flipster({
      itemContainer: 'ul',
      itemSelector: 'li',
      style: 'coverflow',
      start: '0',
      keyboard: true,
      click: true,
      fadeIn: 400,
      loop: false,
      click: false,
      autoplay: false,
      spacing: -0.5
    })
    $('#mars-search-results').flipster('index')
  })
}
```
Now it loads the other searches, but it's extra glitchy. Is that just what happens with flipster or is it possible to make it smoother?

**Comment by bernardlee** [comment]
I haven't used this library before.  What happens if you move the line `$('#mars-search-results').flipster('index')` so that it's immediately after the `for` loop?

**Comment by ggabrakadabra** [comment]
@raq929 If I have flipster in the package.json and in the webpack file, won't let allow it to work on the deployed site? Since grunt deploy will package everything?

**Comment by ggabrakadabra** [comment]
Yup, you're totally right. After deploying I get this in the console
```
Mixed Content: The page at 'https://ggwilliams.github.io/pictures-app-client/#' was loaded over HTTPS, but requested an insecure stylesheet 'http://a.drien.com/src/css/jquery.flipster.css'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by raq929** [comment]
Yeah, you can add it as an npm module, and take it out of your `index.html`, or you can do what Max did and download the file, put it in a `vendor` file and require it from there.

**Comment by ggabrakadabra** [comment]
So first,
I downloaded flipster from npm
[https://www.npmjs.com/package/jquery.flipster/tutorial](url)

then I put this stylesheet in the html
```
<link rel="stylesheet" href="css/flipster.min.css">
```

I checked in local host and it still works properly.

Then merged and deployed from master.

and I'm getting this error still
```
GET https://ggwilliams.github.io/pictures-app-client/css/flipster.min.css 
```

**Comment by ggabrakadabra** [comment]
Ok I'll try that now.

**Comment by ggabrakadabra** [comment]
So,
I took the link tag out of index.html and it still worked on local host.
Then I tried deploying again.
NO RED ISSUES AND IT WORKS!
But now I have
```
Mixed Content: The page at 'https://ggwilliams.github.io/pictures-app-client/#' was loaded over HTTPS, but requested an insecure image 'http://mars.jpl.nasa.gov/msl-raw-images/msss/01536/mcam/1536ML0078720000604513I01_DXXX.jpg'. This content should also be served over HTTPS.
```
And it shows for each picture that's loaded. I don't know why I'm getting the http error because my url in the backend uses https
```
    url = "https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?page=1&earth_date=#{query}&api_key=#{api_key}"
```
and in the front end it's served over https. Is this something I should ignore, or can I fix it?

**Comment by bernardlee** [comment]
As far as I know, that isn't something that you can fix.  Did you try my suggestion and did it fix your image display bug?  If not, then have you found an alternative solution?

**Comment by ggabrakadabra** [comment]
Sorry, I didn't see your suggestion until now. 
If I move it here,
```
    for (let i = 0; i < results.photos.length; i++) {
      const singleSearchResult = marsTemplate(results.photos[i])
      $('.mars-list').append(singleSearchResult)
    }
    $('#mars-search-results').flipster('index')
    $('#mars-search-results').flipster({
```
Then I get this issue.
```
Uncaught TypeError: Cannot read property 'index' of undefined
```

So I guess I have to have it at the end. It does work though. But if I find any solutions, I'll post them.

**Comment by bernardlee** [comment]
We can take a look at it together later on if you haven't found a solution by then.

**Comment by ggabrakadabra** [comment]
So far, if I just click the photos instead of paging over with the arrows it works a lot cleaner.

**Comment by ggabrakadabra** [comment]
Ok sounds good. 👍

**Comment by bernardlee** [comment]
Any update on this?

**Comment by ggabrakadabra** [comment]
To make it less glitchy,
I set 
```
 keyboard: false,
```

because using the arrow keys was slowing it down.
