### ISSUE TITLE
Setting a service property in Ember

### ISSUE THREAD

**Issue by dsweetser** [ga-wdi-boston/capstone-project#586]
I've been close to getting this for along time, and now I'm filing an issue.  What I'm trying to do is save an ID to an ember service so that I can access it in other parts of my app.

UPDATE: have it working, but I can't get it to transition to another page on success now.

shop/new.js
```
import Ember from 'ember';

export default Ember.Route.extend({
  cart: Ember.inject.service(),
  model () {
    return this.get('store').createRecord('order', {});
  },

  actions: {
    createOrder(order){
      this.get('cart').createOrder(order)
// the below line is what's throwing an error
      .then(() => this.transitionTo('shop'));
    },
    cancel () {
      history.back();
    },
  },
});
```
I've tried a million variations on the code, this is where it currently is.  The console.log is returning the newly created order id, which is what I want to set the currentOrder variable on the cart service to be.  I'm fully aware that the set line is wrong at the moment - my best guess is that it should be `.then((response) => Ember.set(cart, 'currentOrder', (Ember.get(response, 'id'))))`... but that isn't working either.

services/cart.js
```
import Ember from 'ember';

export default Ember.Service.extend({
  currentOrder: null,

  createOrder(order){
    console.log('boo');
    order.save()
    .then((response) => this.set('currentOrder', Ember.get(response, 'id')))
    .then(() => console.log(this.get('currentOrder')));
  },
});
```

I tried the this.transitionTo in the cart too and it didn't work, probably because of the different environment.  I suspect it has something to do with chaining these promises together, but I'm taking a walk and around and hoping for insight!

Thanks so much!
Dan

**Comment by raq929** [comment]
What's the error?

**Comment by dsweetser** [comment]
"cannot read property 'then' of undefined

**Comment by raq929** [comment]
Yeah, I think `this.get()` does not return a promise. What happens if you take it out of the then?

**Comment by dsweetser** [comment]
That was the inside I needed!  more specifically, this is what the action in shop/new.js looks like:
```
  createOrder(order){
      this.get('cart').createOrder(order);
      this.transitionTo('shop');
    },
```
