### ISSUE TITLE
Front End Admin Verification

### ISSUE THREAD

**Issue by SquirtleSquad1988** [ga-wdi-boston/capstone-project#588]
So I am using local storage to store a user object to the store file so when a user visits the page, for instance, it checks to see if theres an object named user in the store and if there is it logs the user in automatically. I am not trying to use this functionality to create an admin attribute that is checked via front end logic to display delete buttons and whatnot.

Some Code:

in auth/events.js
```js
const onSignIn = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.signIn(data)
    .then((response) => {
      // sets the local storage key "user" to the object response.user
      // which contains the user token
      localStorage.setItem("user", JSON.stringify(response.user));
      store.user = response.user;
      return store.user;
    })
    .then(ui.signInSuccess)
    .catch(ui.signInFailure);
};
```

in index.js:
if store.user exists it hide buttons, and if the user has a admin key in the user object it hides all classes named admin.
```js
$(() => {
  // sets the store.user parameter to the key 'user' in local storage
  store.user = JSON.parse(localStorage.getItem('user'));
  setAPIOrigin(location, config);
  if (store.user) {
    $('.sign-up-dropdown').hide();
    $('.sign-in-dropdown').hide();
    if (!store.user.admin) {
      $('.admin').hide();
    }
  } else {
    $('.change-password-dropdown').hide();
    $('#exit').hide();
    $('.admin').hide();
  }
);
```

Example response from local storage when a user is signed in:
```
> localStorage.getItem('user')
"{"id":1,"email":"q@q","token":"BAhJIiU4YmRmMWE4OWQ3NTgyZDkxN2E3YzgzYjRkY2YyYzllZAY6BkVG--cbc3baedd12ced979a30f8d47b9c2f4e291e6f0e","admin":true}
"
```

I am just wondering if this would be Kosher for the project. In other words, is this method of setting an administrator OK to do for the final project or should I find another way to make this functionality work.

**Comment by raq929** [comment]
@gaand says: It's not an issue if the API checks as well.  If the API doesn't check, then it's an issue whether or not it's stored in local storage.

**Comment by SquirtleSquad1988** [comment]
Ok I think I am going to abandon this since I'm not really sure how I would have the API check when I am loading a comments template. I will probably just alter my backend and check to see if editable = true when loading buttons in my handlebars template. Thanks!
