### ISSUE TITLE
Need to load related model in Ember Route

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/capstone-project#589]
I am working on displaying my visualizations and everything works well when the user arrives at the routes to view and edit visualizations by navigating through the app. However, if the the user arrives at certain parts of the page directly from the URL, only the visualization model is loaded, the dataset model that it is related to does not. I do not have this problem if the user visits the `visualizations` route first, since that model hook for some reason also loads the datasets associated with the visualizations. I think this is due to differences in how `findAll` and `findRecord` work.

`routes/visualizations`, the route that properly loads the related models:
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('visualization');
  }
});
```

`routes/visualization`, the route that does not load the dataset correctly:
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('visualization', params.visualization_id);
  }
});
```

I have been trying to find how one can load mupltiple Ember Data objects with a single model hook, but all the examples I can find are about loading children in routes nested under the part model's route.

I have managed to get the following to work though this solution is very hacky:
`routes/visualizations`:
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findAll('dataset')
      .then(() => this.get('store').findRecord('visualization', params.visualization_id));
  }
});
```
I can live loading all the datasets at the cost of performance for now, but would like to know a better way.

**Comment by jrhorn424** [comment]
Routes with dynamic segments do not run their model hooks unless they are accessed via URL. `transitionTo` and `linkTo` will bypass the model hook, since it is expected that a context object be passed along with them.

```
   return this.get('store').findAll('dataset')
      .then(() => this.get('store').findRecord('visualization', params.visualization_id));
  }
```

This returns visualizations only. The dataset is swallowed by the second part of the Promise, the `then`.

For problems like this, you should prefer `Ember.RSVP.hash({})`. See: https://emberigniter.com/load-multiple-models-single-route/

**Comment by jrhorn424** [comment]
@Sofistication Will return this problem later today. What he has now works, it just isn't idiomatic.

**Comment by jrhorn424** [comment]
Actually, on second thought, if these models are related, why doesn't accessing them through their relationships work?

You may want to look at https://github.com/fivetanley/ember-promise-helpers

**Comment by raq929** [comment]
Update?

**Comment by jrhorn424** [comment]
Has this been addressed @Sofistication?

**Comment by samordonez** [comment]
Haven't had the chance to look at it, but I will close for now.
