### ISSUE TITLE
Ember services referencing models

### ISSUE THREAD

**Issue by dsweetser** [ga-wdi-boston/capstone-project#591]
I'm trying to create a new listItem that needs two variables: an order id and a stamp id.  I'm loading both into my services/cart.js file, but I can't seem to find a way to create a listItem as a new instance of the listItem class.

Here's my relevant code:
```
import Ember from 'ember';

export default Ember.Service.extend({
  listItem: this.get('store').findRecord('listItem'),

  currentOrder: null,

  createOrder(order){
    order.save()
    .then((response) => this.set('currentOrder', Ember.get(response, 'id')));
  },

  createListItem(stamp) {
    let listItem = this.ListItem.create({
      stamp: stamp.id,
      order: this.get('currentOrder')
    });
    console.log(listItem);
    listItem.save()
    .then((response) => console.log(response));
  }
});
```

current error is: Uncaught TypeError: this.get is not a function

I've also tried loading listItem as a model and calling model.create.new, but that breaks it it.  Here's what that call looked like:
```
import Ember from 'ember';

export default Ember.Service.extend({
  model() {
    return this.get('store').findRecord('listItem');
  },

  currentOrder: null,

  createOrder(order){
    order.save()
    .then((response) => this.set('currentOrder', Ember.get(response, 'id')));
  },

  createListItem(stamp) {
    let listItem = this.model.create({
      stamp: stamp.id,
      order: this.get('currentOrder')
    });
    console.log(listItem);
    listItem.save()
    .then((response) => console.log(response));
  }
});
```
which returns Uncaught TypeError: this.model.create is not a function

I think that's the relevant code, let me know if there's something else needed!
Thanks!
Dan

**Comment by raq929** [comment]
What happens if you save the `this.get()` as a variable and use that variable in the `this.model.create()`? I think it's a scope issue; the scope inside `this.model.create()` is different from outside it.

**Comment by dsweetser** [comment]
I've changed it to not have the model import above and be this:
```
  createListItem(stamp) {
    let itemModel = this.get('store').findRecord('listItem');
    let listItem = itemModel.create({
      stamp: stamp.id,
      order: this.get('currentOrder')
    });
    console.log(listItem);
    listItem.save()
    .then((response) => console.log(response));
  }
```
which is giving me this error:
`Uncaught TypeError: Cannot read property 'findRecord' of undefined`

**Comment by jrhorn424** [comment]
@dsweetser and I discussed using model relationships to manage needing multiple models in a view-state. He will relate the models, and research how `peekRecord` and `pushObject` might help him accomplish what he wants.

**Comment by dsweetser** [comment]
Okay, I've set up relationships now and I'm testing it out this way.

app/routes/stamps.js
```
import Ember from 'ember';

export default Ember.Route.extend({
  cart: Ember.inject.service(),

  model () {
    return this.get('store').findAll('stamp');
  },

actions: {
  deleteStamp(stamp) {
    stamp.destroyRecord()
    .catch(() => {
      this.get('flashMessages')
      .danger('That stamp has been used for an order and cannot be deleted.');
    });
  },
  addStampToOrder(stamp) {
    console.log(Ember.get(stamp,'id'));
    console.log(Ember.get('cart', 'currentOrder'));
    let listItem = {
      stamp: +Ember.get(stamp, 'id'),
      order: 3
    };
    console.log(listItem);
    Ember.set(stamp,'listItemId',listItem);
    listItem.save().catch(() => {
      this.get('flashMessages')
      .danger('There was a problem. Do you have a cart selected?');
    });
  },
  },
});
```

my understanding of the relationship is that setting stamp.listItemId will also access the list item in question... but I'm not sure how to use this create a new list item.

**Comment by dsweetser** [comment]
oh god I'm questioning everything because I maybe made a name space error

**Comment by jrhorn424** [comment]
Names like `listItemId` are an anti-pattern, since your models should be receiving a `listItem` model instance, not a number. Without an Ember object, observers can't keep your UI up-to-date.

**Comment by jrhorn424** [comment]
@Sofistication may be able to show you a quick code example if he isn't busy.

**Comment by dsweetser** [comment]
more specifically, I was calling this model list-item on the front end and list_model on the back end and I don't know if Ember was telling the difference.

**Comment by raq929** [comment]
Probably not

**Comment by raq929** [comment]
Where are you at?

**Comment by dsweetser** [comment]
I'm flailing and not making progress.

**Comment by raq929** [comment]
If you can stay, Jeff can help @ 5:30

**Comment by dsweetser** [comment]
PIZZA has lured me to stay. Also, new error is best error!

```
addStampToOrder(stamp) {
      // console.log(Ember.get(stamp,'id'));
      // console.log(Ember.get('cart', 'currentOrder'));
      let newListItem = this.store.createRecord('list_item', {
        stamp: +Ember.get(stamp, 'id'),
        order: 3
      });
      // let listItem = function () {
      //   return this.get('store').findAll('list_item')
      // }

      console.log(newListItem);

      // this.get('stamp').set('listItemId', newListItem)

      newListItem.save().catch(() => {
        this.get('flashMessages')
        .danger('There was a problem. Do you have a cart selected?');
      });
    },
```
results in a failed POST request of 422!!!!

**Comment by raq929** [comment]
Wooo!

**Comment by dsweetser** [comment]
Turns out I was not passing Ember the whole object(s), simply the ID's.
