### ISSUE TITLE
Required field on sign up isnt working.

### ISSUE THREAD

**Issue by moshiko1988** [ga-wdi-boston/capstone-project#593]
I added an attribute `full_name` to the back end sign up form, I add migration and added in the controller and serializer.

I am able to create a `full_name` attribute and use it (in the back end and in the front end) but the issue is that the the sign up form a user can leave the field empty and it still create the user.

001_create_users.rb
``` ruby
# frozen_string_literal: true
class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :email, null: false, index: { unique: true }
      t.string :token, null: false, index: { unique: true }
      t.string :password_digest, null: false
      t.string :full_name, null: false

      t.timestamps null: false
    end
  end
end
```
I also added a `required` in the input form (which works on all other forms other then this one):

app/templates/components/fullname-input.hbs
```ruby

<label for="fullName">FullName</label>

{{input type="text"
        placeholder="Full Name"
        value=fullName
        required="required"
    }}
```

I could ask for this area to be optional but it would be nice if I would know why is it even passing in the server if its a required and null false?

**Comment by raq929** [comment]
What do you mean by 'isn't working'? Is there an error?
What do you expect to happen? What is happening instead?
Please post all the relevant code. (HTML, api request, etc.)

**Comment by moshiko1988** [comment]
sorry I posted just the title by mistake and then edited the body  😅

**Comment by raq929** [comment]
Can I see your users controller?

**Comment by moshiko1988** [comment]
```ruby

  def signup
    user = User.create(user_creds)
    if user.valid?
      render json: user, status: :created
    else
      render json: user.errors, status: :bad_request
    end
  end


  def user_creds
    params.require(:credentials)
          .permit(:email, :password, :password_confirmation, :full_name)
  end
```

**Comment by raq929** [comment]
Come on over!

**Comment by raq929** [comment]
We nuke_paved just to be sure the migration was working, but no dice.

**Comment by moshiko1988** [comment]
Solved!

Added validetions to user model
```ruby
  validates :full_name, presence: true
```
