### ISSUE TITLE
Rails - setting character limit

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/capstone-project#594]
On my front-end, I have set a character limit in input-fields.
However, I need to do it on the back-end too but I'm not sure where and how to do that.
Couldn't find it on documentations so... any tips?
It is a string which would have a limit of 15 characters.

**Comment by MicFin** [comment]
String vs Text as the datatype affects length allowed.
https://stackoverflow.com/questions/3354330/difference-between-string-and-text-in-rails

You can validate the length specifically in the model.
https://stackoverflow.com/questions/4441882/validating-min-and-max-length-of-a-string-but-allowing-it-to-be-blank

The google search I used was `rails string max length`

**Comment by doremaxime** [comment]
Perfect! validating was a key word i didn't have in my searches!
