### ISSUE TITLE
Random Page Changes Multiple Times after Error

### ISSUE THREAD

**Issue by ddobson** [ga-wdi-boston/capstone-project#595]
When a user submits a new recipe with an error, I prevent the change page from changing. When they resubmit without an error it updates multiple times. (http://quick.as/YXZotJDW6). I would like to prevent this. 

Here is the relevant code in the component with the random number.

```
class RecipeForm extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      randomPage: ' ',
    }

    this.handleNewSubmit = this.handleNewSubmit.bind(this);
    this.getRandomPage = this.getRandomPage.bind(this);
   }

  componentWillReceiveProps(nextprops) {
    if (nextprops.availPages && nextprops.updateRandom) {
      this.getRandomPage(nextprops.availPages);
    }
  }

  getRandomPage(availPages) {
    const randomPage = availPages[Math.floor(Math.random()*availPages.length)];

    this.setState({ randomPage });
  }

// in render() function
<h1 className='suggestion'>{ this.state.randomPage || 'None Left!' }</h1>
```

Here is the relevant code in the parent component. 
```
class CookbookDetail extends React.Component {
  constructor(props){
    super(props);

    this.state = {
      isLoading: true,
      open: false,
      errorMsg: '',
      updateRandom: true,
      cookbook: {
        recipes: []
      }
    }

    this.cookbookId = this.props.match.params.id;

    this.handleNewRecipe = this.handleNewRecipe.bind(this);
    this.handleDestroyRecipe = this.handleDestroyRecipe.bind(this);
  }

handleNewRecipe(formData, form, valid) {
    if (!valid[0]) {
      this.setState({ open: true, errorMsg: valid[1], updateRandom: false })
      return;
    }

    this.setState({ open: false, errorMsg: '', updateRandom: true })

    cbService.createRecipe(this.cookbookId, formData)
      .then(() => {
        this.setState( {isLoading: true} )
        cbService.getCookbook(this.cookbookId)
          .then((response) => response.json())
          .then((json) => {
            this.setState({ cookbook: json.cookbook, isLoading: false })
          })
          .catch(() => this.setState({ open: true, errorMsg: ajaxErrorMsg }));

        form.reset();
      })
      .catch(() => this.setState({ open: true, errorMsg: ajaxErrorMsg }));
  }
```

**Comment by raq929** [comment]
I would put a console.log() in `componentWillReceiveProps` and see what's going on, since it seems to be receiving props more than once. Or at least it's updating more than once, so possibly use `componentWillUpdate()` to debug the behavior.

**Comment by raq929** [comment]
@bernardlee also mentioned  that you call `setState()` twice in the last function. This is likely causing the refresh.

**Comment by ddobson** [comment]
that `setState` is needed to ensure that error messages load correctly though. I'm basically cleaning up if there were any errors previously since it seems to leave the `open` state in true.

**Comment by raq929** [comment]
Is there a lifecycle hook that will prevent the view from refreshing if when one of those state changes is made?

**Comment by jrhorn424** [comment]
@ddobson If you un-nest your `.then` and `.catch`, it should work as you expect, and you'll only need one `.catch` at the end.

- http://taoofcode.net/promise-anti-patterns/
- http://www.datchley.name/promise-patterns-anti-patterns/
- http://solutionoptimist.com/2013/12/27/javascript-promise-chains-2/

**Comment by ddobson** [comment]
Okay, I tried the following but I still am having the issue and now my error pop up happens on valid submissions. Does this look correct?

```
handleNewRecipe(formData, form, valid) {
    if (!valid[0]) {
      this.setState({ open: true, errorMsg: valid[1], updateRandom: false })
      return;
    }

    cbService.createRecipe(this.cookbookId, formData)
      .then((response) => {
        this.setState({ isLoading: true })
        return Promise.all([response, cbService.getCookbook(this.cookbookId)])
      })
      .then((response) => response.json())
      .then((json) => this.setState({ cookbook: json.cookbook, isLoading: false, updateRandom: true, open: false, errorMsg: '' }))
      .catch(() => this.setState({ open: true, errorMsg: ajaxErrorMsg }));
```

**Comment by raq929** [comment]
What does `Promise.all()` return? I suspect it's an array, which means that response.json() may be what's throwing your error?

**Comment by ddobson** [comment]
@raq929 @jrhorn424 I am not making any progress. I really need some help. This is the last thing I think I need to fix. Can one of you pair with me?

**Comment by raq929** [comment]
I'm in classroom 4, come on by.

**Comment by raq929** [comment]
Update and close please!

**Comment by ddobson** [comment]
Closing this issue. Thank you so much, @raq929!
