### ISSUE TITLE
Getting a race condition issue

### ISSUE THREAD

**Issue by lbreguet** [ga-wdi-boston/capstone-project#596]
Again, sometimes the comments from the post are trying to load up before the post, which creates an issue displaying the comments and also an issue creating a comment. 

Here's the code that makes the `GET` request for the comments:
```js
const onShowPost = (event) => {
  event.preventDefault()
  const id = event.target.dataset.id
  api.show(id)
    .then(ui.showSuccess)
    .then(commentsApi.index(id)
          .then((data) => commentsUi.indexSuccess(data, id)))
    .catch(ui.failure)
}
```

**Comment by raq929** [comment]
You are running the `commentsApi.index()` function immediately, I think.

```diff
const onShowPost = (event) => {
  event.preventDefault()
  const id = event.target.dataset.id
  api.show(id)
    .then(ui.showSuccess)
-    .then(commentsApi.index(id)
+   .then(() => commentsApi.index(id))
          .then((data) => commentsUi.indexSuccess(data, id)))
    .catch(ui.failure)
}
```

Should wait until you get to the then.

**Comment by jrhorn424** [comment]
Please don't nest `.then`.

**Comment by lbreguet** [comment]
Thanks @raq929 , that seems to work. The final code is the following:
```js
const onShowPost = (event) => {
  event.preventDefault()
  const id = event.target.dataset.id
  api.show(id)
    .then(ui.showSuccess)
    .then(() => commentsApi.index(id))
          .then((data) => commentsUi.indexSuccess(data, id))
    .catch(ui.failure)
}
```

And I'll remember that for future reference @jrhorn424.

**Comment by jrhorn424** [comment]
Great! Here's some references, @lbreguet:

- http://taoofcode.net/promise-anti-patterns/
- http://www.datchley.name/promise-patterns-anti-patterns/
- http://solutionoptimist.com/2013/12/27/javascript-promise-chains-2/
