### ISSUE TITLE
Conditionally display handlebars

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/capstone-project#597]
Front-end with browser template.

Currently, when signing in, a user's resources is being displayed with handlebars (includes an ```<h2>``` and an each loop).

Goal: when user does not have resources, none of the handlebar file is displayed.

In my ui.js, I have a function that determines if objects returned from the GET of the index is empty or not:
```javascript
function countObj (obj) {
  let i = 0
  for (const key in obj) {
    ++i
  }
  return i
}
```

Called function in ui.js:
```javascript
const indexGearSuccess = (data) => {
  const indexMyGearHtml = indexMyGearHandlerbars({
    my_gears: data.my_gears
  })

  // HERE
  if (countObj(data) !== 0) {
    $('.gear-table').html(indexMyGearHtml)
  } else {
    $.notify('Add your gear!', 'success')
  }
}
```

The  issue is that when there is no data, the ```<h2>``` still gets displayed.

Example with data:
![screen shot 2017-03-30 at 4 30 26 pm](https://cloud.githubusercontent.com/assets/24608045/24524973/8bd1acf0-1566-11e7-88ec-84a79ac730ad.png)

Example with no data:
![screen shot 2017-03-30 at 4 30 13 pm](https://cloud.githubusercontent.com/assets/24608045/24524967/844e8200-1566-11e7-9a79-f7d23d381214.png)

handlebars
```handlbars
<h2>Gear</h2>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {{#each my_gears as |gear|}}
      <tr data-id="{{gear.id}}">
        <td>{{gear.quantity}}</td>
        <td>{{gear.name}}</td>
        <td><button...............
```

How can make so that none of the handlebar file is injected when a user has no data?

**Comment by bernardlee** [comment]
Have you tried using the `if` block helper?  If not, then check [Handlebars.js - Built-In Helpers](http://handlebarsjs.com/builtin_helpers.html) and try it out.

**Comment by doremaxime** [comment]
I had not! thank you.
update to come.

**Comment by doremaxime** [comment]
Temporary solution:
Add ```{{#if you-resource-here}}``` at the very top of your handlebars and ```{{/if))``` at the very bottom.

However, it technically does not resolve the root of the issue as it still displays the divs that the handlebars are inserted into as such (2 dots at the top left as I have 2 handlebar files):
![screen shot 2017-03-30 at 4 57 11 pm](https://cloud.githubusercontent.com/assets/24608045/24525945/496dea96-156a-11e7-8e32-47ac042514dd.png)

A better solution would be to add (as well as solution above) a show/hide to the div in the index.html if there is no data so that nothing appears.
