### ISSUE TITLE
Flash message doesn't show up in deploy link

### ISSUE THREAD

**Issue by newayliu1** [ga-wdi-boston/capstone-project#599]
Flash message does not show in my deploy link.

**Comment by raq929** [comment]
When I spoke to you, you were saying you wanted to uninstall an npm package?

Do you want the flash messages to show up? What are you using to display them? Do they work locally.

**Comment by newayliu1** [comment]
I installed couple package before which are: 
ember-cli-confirm-dialog
ember-confirm-dialog 
ember-flash-message

**Comment by newayliu1** [comment]
My local flash message is working, which comes from ember auth template

**Comment by newayliu1** [comment]
I fixed it. I uninstall ember-cli-confirm-dialog on local and re-deploy again. It works.

**Comment by raq929** [comment]
Ok, and you don't want any of those packages, right? I think you can do 
`npm uninstall <package name> --save` to uninstall. The flash package hopefully is the problem.
