### ISSUE TITLE
cannot get drop table migration to run

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/capstone-project#60]
I did a rails g model User_events and did a db:migrate

Then I decided I wanted to try a 
rails g resource user_event instead so I could see all of the routes, models etc created.

I have tried 2 drails g migration drop_user_events (yes I have manually edited the migration files before the db:migrate) and it keeps failing, says it is trying to create the table, when I want to drop it.

rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: table "user_events" already exists: CREATE TABLE "user_events" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer, "event_id" integer, "role" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL) /Users/laurisa/WDI/Proj_4/freshEX/db/migrate/20151217192306_create_user_events.rb:3:in `change'
ActiveRecord::StatementInvalid: SQLite3::SQLException: table "user_events" already exists: CREATE TABLE "user_events" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer, "event_id" integer, "role" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL) 
/Users/laurisa/WDI/Proj_4/freshEX/db/migrate/20151217192306_create_user_events.rb:3:in`change'
SQLite3::SQLException: table "user_events" already exists
/Users/laurisa/WDI/Proj_4/freshEX/db/migrate/20151217192306_create_user_events.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by jrhorn424** [comment]
Was this an ordering issue with migrations?
