### ISSUE TITLE
A folder from my repo appeared on my desktop?

### ISSUE THREAD

**Issue by jwaskow** [ga-wdi-boston/capstone-project#600]
So I just noticed a new folder on my desktop, called `Tea Time_files` (my app is called Tea Time).  I didn't create this folder, at least not intentionally.  It says it was created at about 2:30pm today.  The folder has 5 files: `application.js, css, css(1), css(2), vendor.js`.  It seems like these files came from my repo, but I don't know if they were moved or copied.  My app seems to be working fine, is there any way I can check that I didn't lose these files from my repo?  I looked through the folder structure in my repo and could not find them.

**Comment by raq929** [comment]
git status will tell you

**Comment by jwaskow** [comment]
I recently committed, so git status says everything is clean.  I looked through my commit history for today and didn't see anything out of the ordinary.  Any idea why this might have happened?

**Comment by raq929** [comment]
Not really. Can you drag files out of atom? Seems bizarre to me.

**Comment by jwaskow** [comment]
Yeah its really spooky.  But my app seems to be working, so I guess ill close this issue.
