### ISSUE TITLE
Ember sign up form does not clear if user navigates away through Ember transitions

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/capstone-project#602]
If the user starts filling in the sign up form and navigates away (for example by clicking the home button in the nav bar), the input fields do not clear. I solved this by adding an init hook to the component, now it looks like this:

```js
import Ember from 'ember';

export default Ember.Component.extend({
  tagName: 'form',
  classNames: ['form-horizontal'],

  credentials: {},

  init() {
    this._super(...arguments);
    this.set('credentials', {});
  },

  actions: {
    submit () {
      this.sendAction('submit', this.get('credentials'));
    },

    reset () {
      this.set('credentials', {});
    },
  },
});
```

Technically this does not clear the fields when the user leaves, but it does clear them when they return. This can also be used for things like create forms, future developers who might be reading this. ;)

(Tell me if this should be filed on ember-auth rather than here)

**Comment by jrhorn424** [comment]
Has this been addressed @Sofistication?

**Comment by samordonez** [comment]
Yes, closing.
