### ISSUE TITLE
XHR finished loading:

### ISSUE THREAD

**Issue by mbisht** [ga-wdi-boston/capstone-project#606]
XHR finished loading: GET "https://employee-564d8.firebaseio.com/employee.json".
 {"data":{"contact":"near alpine echo apartement ","email":"mayankbisht.com@gmail.com","first_name":"mayank","last_name":"bisht","salary":6000},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"https://employee-564d8.firebaseio.com/employee.json","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"}

**Comment by jordanallain** [comment]
Hey not sure who you are but if you want to reformat your code to make it easier to read you can surround it with three back ticks before and after.

**Comment by payne-chris-r** [comment]
??? @mbisht ???

**Comment by mbisht** [comment]
I have solved the problem couple of days before, some coding mistake in my Program.

**Comment by jordanallain** [comment]
Ah cool. You should leave a comment describing how you fixed it and close the issue! Great job!

**Comment by payne-chris-r** [comment]
@mbisht plz close this with a solution.
