### ISSUE TITLE
create not working

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/capstone-project#608]
I have been trouble shooting this for about an hour and am at a point where rails is no longer giving me errors I can use.

I am trying to create a quote.

I am running this command: `sh scripts/quotes/create-quote.sh`
Which runs this curl script:
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/quotes"
DATE="05-06-2017"
QUOTE="test quote"
TOKEN="BAhJIiU1YTA0NTUyZTQyZGYyNzZiYWNlYjE4NzVhZjA2NDc5NQY6BkVG--0bac781c3f32888de316129da20067127edf03fa"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "quote": {
      "date": "'"${DATE}"'",
      "quote": "'"${QUOTE}"'"
    }
  }'

echo
```
and I get this error:
```
Started POST "/quotes" for 127.0.0.1 at 2017-06-05 11:02:30 -0400
Processing by QuotesController#create as */*
  Parameters: {"quote"=>{"date"=>"05-06-2017", "quote"=>"test quote"}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "5a04552e42df276baceb1875af064795"], ["LIMIT", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.09ms)
Completed 404 Not Found in 15ms (Views: 2.0ms | ActiveRecord: 0.2ms)
```
The controller for create quotes is:
```
class QuotesController < OpenReadController
  # changed to OpenReadController from ProtectedController
  before_action :set_quote, only: [:update, :destroy, :create]

  # POST /quotes
  # POST /quotes.json

  def create
    @quote = current_user.quotes.build(quote_params)

    if @quote.save
      render json: @quote, status: :created
    else
      render json: @quote.errors, status: :unprocessable_entity
    end
  end
```

**Comment by payne-chris-r** [comment]
What routes are available??

**Comment by awoodrum87** [comment]
Here is the route:
`resources :quotes, except:[:new, :edit]`

@laurpaik suggested I ask if if my schema is a problem. My quotes table has a quote attribute. Is this a problem?

**Comment by awoodrum87** [comment]
update: I ran a migration to change the name of the column to `quote_text` and that did not fix the problem :)

**Comment by payne-chris-r** [comment]
What before action(s) are you running?

**Comment by awoodrum87** [comment]
I set the quote:
`before_action :set_quote, only: [:update, :destroy, :create]`

```
  def set_quote
    @quote = current_user.quotes.find(params[:id])
  end
```

**Comment by payne-chris-r** [comment]
What's the point of `:set_quote`?

**Comment by awoodrum87** [comment]
finds the quotes associated with the `current_user`...which means that is garbage for create because the quote has to be created to be associated with a user??

**Comment by awoodrum87** [comment]
when I take out the create method from the `:set_quote` before action this is the error I get:

```
Started POST "/quotes" for 127.0.0.1 at 2017-06-05 12:35:10 -0400
Processing by QuotesController#create as */*
  Parameters: {"quote"=>{"date"=>"05-06-2017", "quote"=>"test quote"}}
  User Load (1.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "5a04552e42df276baceb1875af064795"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 3ms (ActiveRecord: 1.3ms)


  
ActiveModel::UnknownAttributeError (unknown attribute 'quote' for Quote.):
  
app/controllers/quotes_controller.rb:23:in `create'
```

**Comment by payne-chris-r** [comment]
New error!!! Yayyy!

**Comment by awoodrum87** [comment]
huzzah!

**Comment by payne-chris-r** [comment]
What's happening on line 23 of your quotes controller?

**Comment by awoodrum87** [comment]
`@quote = current_user.quotes.build(quote_params)`
This is building the quote based off the quote params that were passed in.

**Comment by jordanallain** [comment]
what does the `quote_params` method look like?

**Comment by awoodrum87** [comment]
```
  def quote_params
    params.require(:quote).permit(:date, :quote)
  end
```

**Comment by jordanallain** [comment]
Hmm, you shouldn't need `:quote` in both require and permit, just in one.

**Comment by awoodrum87** [comment]
Actually, quotes is the table and quote is the attribute. I think that is the problem. I trashed that repo and started over. will report back when I'm done running the migrations

**Comment by payne-chris-r** [comment]
Do not do this again. If you trash your repo and start again after today you cannot meet expectations for this project.

**Comment by awoodrum87** [comment]
got it. 
I'm still unable to create a quote.
more or less getting the same error. Here is the relevant code:
ERROR:
```
Started POST "/quotes" for 127.0.0.1 at 2017-06-05 13:34:29 -0400
Processing by QuotesController#create as */*
  Parameters: {"quote"=>{"date"=>"05-06-2017", "quote_text"=>"test quote"}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "c04602225b63eee3224a754c59f3b518"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.2ms)


  
NoMethodError (undefined method `quotes' for #<User:0x007fcb4ec43a58>
Did you mean?  quoted_id):
  
app/controllers/quotes_controller.rb:21:in `create'
```

CREATE METHOD IN THE CONTROLLER (no before actions)
```
  def create
    @quote = current_user.quotes.build(quote_params)

    if @quote.save
      render json: @quote, status: :created
    else
      render json: @quote.errors, status: :unprocessable_entity
    end
  end
```

CURL REQUEST:
```
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/quotes"
DATE="05-06-2017"
TEXT="test quote"
TOKEN="REMOVED"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "quote": {
      "date": "'"${DATE}"'",
      "quote_text": "'"${TEXT}"'"
    }
  }'

echo
```

**Comment by laurpaik-zz** [comment]
Do you still have 
```
before_action :set_quote, only: [:update, :destroy, :create]
``` 
and if so, is there a reason :create is in there?
(asking because examples_controller just has this:)
```
before_action :set_example, only: [:update, :destroy]
```

**Comment by awoodrum87** [comment]
Nope! I removed create from the before actions. 
Also, I looked up the other syntax for the build method and it doesn't work. I don't understand why the build method is consistently undefined. 
```
@quote = current_user.build_quotes(quote_params)
@quote = current_user.quotes.build(quote_params)
```

**Comment by laurpaik-zz** [comment]
I believe the top one is specifically for `has_one` relationships, while the second is for `has_many` relationships. https://github.com/ga-wdi-boston/full-stack-project/issues/614#issuecomment-280871303

**Comment by awoodrum87** [comment]
I think I need to set the current user somewhere. That method is undefined FOR #<User:0x007fad2d3039c8>

**Comment by awoodrum87** [comment]
It turns out that I did not add the `has_many` macro to my model. (laughs, cries, stress eats)
I no longer have the method undefined error after adding that. 
Thanks @payne-chris-r
