### ISSUE TITLE
Cannot find my user_registrations table

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/capstone-project#61]
I ran a rails g resource user_event and I had a table for it, but I dont see it in the db schema file

**Comment by LaurisaNeuwirth** [comment]
I did run rake db:migrate but the file is blank now that I look at it. I thought the rails g resource... would have populated that migration file. So now do I put into the migration file the create table info and can I re-run the migration?

**Comment by LaurisaNeuwirth** [comment]
I think this migration file was from a previous command and that the rails g resource command did not create a migration file at all.

**Comment by jrhorn424** [comment]
Feel free to delete that migration and create a new one. If you have to write it yourself, the [guide](http://edgeguides.rubyonrails.org/active_record_migrations.html) has some really great examples.

**Comment by LaurisaNeuwirth** [comment]
I saw Antony in the kitchen about an hour ago and asked him about deleting the migration file. He said to never delete a migration file unless I wanted to drop the whole database, not just a table?

**Comment by LaurisaNeuwirth** [comment]
And if I do delete the migration, do I need to delete the whole rails g resource? If you are onsite can we go over this in person?

**Comment by LaurisaNeuwirth** [comment]
Just to be clear I want to keep the database, just need the user_events table.

**Comment by jrhorn424** [comment]
I'll be by in a moment.
