### ISSUE TITLE
Heroku Issues

### ISSUE THREAD

**Issue by sjruby** [ga-wdi-boston/capstone-project#610]
Testing the simple login functionality once I've deployed to Heroku and Git Pages, I get the following error:  

sjruby.github.io/:1 XMLHttpRequest cannot load https://salty-citadel-91716.herokuapp.com//sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://sjruby.github.io' is therefore not allowed access. The response had HTTP status code 503.

I double checked that I ran the access origin command from the Express API setup, my heroku Config according the command line is:

=== salty-citadel-91716 Config Vars
CLIENT_ORIGIN: https://sjruby.github.io

I've been looking at past projects to figure out what I've done wrong.  I will keep hammering away at this but would like to meet 1:1 to just talk through Heroku as it has given me fits with every project.

**Comment by payne-chris-r** [comment]
It's that damn salty-citadel!

**Comment by payne-chris-r** [comment]
You have a '//' but that's not what's causing the problem. Go double back through the heroku deployment guide and make sure you've done everything.

**Comment by BenGitsCode** [comment]
Please add a comment with some details on the resolution!
