### ISSUE TITLE
Need Advice on Switching from Ember to a Non-Framework

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/capstone-project#611]
I am wanting to switch from using Ember framework and want a clean repo to replace the Ember repo out there. What is the best way to do this other than scrapping and re-creating a repo? Based on the message, it looks like we shouldn't be doing this, but I'd like to keep the names consistent.
Thank you.

**Comment by BenGitsCode** [comment]
When you say keep names consistent, you mean the names of the repositories on GitHub?

**Comment by lisamsmith100** [comment]
yes.  I already deployed sort of the Ember and didn't have the best luck.  Need to back all of that work out.  What is the best way?

**Comment by lisamsmith100** [comment]
Can you recommend a solution other than scrapping?  I haven't done enough work on front-end yet to say it's worth anything but I'd like to spend quite a bit of time on this tonight so any suggestions would be greatly appreciated.

**Comment by BenGitsCode** [comment]
There are a few ways you go back to previous work in git. 

 I would review your git log, and find a commit you want to go back to.

There are several different strategies you could use for going back to the right commit, how many commits do you have on master? Do you have a commit before ember was integrated? 

Are deployment issues the reason you're switching from Ember?

**Comment by lisamsmith100** [comment]
I do not want to go back to any work in git.
I do not want to keep any of my commits since it's basically ember-auth/ember-template.
I made 6 commits.  I do not have a commit before ember was integrated.
No re: deployment issues the reason.  They're only part of the reason.  I'm not comfortable with ember for this particular project (I'd like to practice more) and given the short amount of time to produce an app, the lack of documentation along with my notes not being robust enough to recreate based on the pace of the Ember lessons, and needing to figure out the integration and nuances between ember-auth and ember-template, I'd prefer to use browser template.  I can say I spent some time on it this weekend on my own and need more time than I can spend on it this week.  I like Ember and will be practicing after this course.  It's a neat tool.

**Comment by BenGitsCode** [comment]
I think the most important part is preserving your history of the change, either by reverting the commits or removing the files and showing history of those changes by adding and committing them. I'm not sure what the best practice for making changes that big though, @payne-chris-r do you have an idea of the best practice for this context?

**Comment by payne-chris-r** [comment]
If you're definitely against sticking with Ember you should start over from a browser-template repo where the initial commit points to your Ember repo. Leave both on GH. Let's chat in the morning though.

**Comment by lisamsmith100** [comment]
I'd like to chat on this first thing in the morning.  I'm not sticking with Ember.  I've spent hours on this during the weekend and also today with this back and forth on the issue queue and trying to preserve code that I do not want to preserve has derailed my project schedule and plan.  I am not in the habit of scrapping repos, first time in entire cohort.  The decision to try Ember over weekend and change to browser template if not comfortable with the Ember was decided in 1:1 project planning.  And now the deployment is not working correctly for browser template.  I'd like to take a look to make sure I can deploy with success tomorrow.

**Comment by lisamsmith100** [comment]
Closing this issue after renaming my old repo and creating a new, with reference to old repo.
Sat with C. Payne for an hour with no resolution to the deployment issues to come to the conclusion that starting over from scratch is best plan.  I started from scratch with the browser template from the .ly repo and deployed successfully.
