### ISSUE TITLE
Need help adding data-tableplugin https://datatables.net/

### ISSUE THREAD

**Issue by Ryaong792** [ga-wdi-boston/capstone-project#613]
Attempting to use plugin - from: https://datatables.net/
added the links to script areas but still not working.

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
  
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>

Was still unable to get this plug in working.  Did not do the NPM Install since I was not sure if this would break other things but wanted to see if anyone from used this site before and got it working.

$(document).ready( function () {
    $('#table_id').DataTable();
} );

is all that is needed to use this plug-in but still will not work.  Not able to find the DataTable plugin.  
Not a rush will disregard this plugin if I can't get it working

**Comment by jordanallain** [comment]
going the npm install route is definitely preferred over script tags, do you want to give it a shot that way?

**Comment by Ryaong792** [comment]
cool will try that out later today.  Finishing my handlebars tables then will attempt it.  I'll give a status when I attempt the NPM Instal..  Thx Jordan!

**Comment by Ryaong792** [comment]
Will do NPM install later.  Closing issue

**Comment by Ryaong792** [comment]
Jordan would you be able to come help me with this? I have done the NPM install but still having problems.  I wont take more then 10mins of your time.  no reush

**Comment by Ryaong792** [comment]
Also did the npm --save

**Comment by BenGitsCode** [comment]
I'll take a look at this with you.

**Comment by BenGitsCode** [comment]
Was this resolved @Ryaong792 ?

**Comment by Ryaong792** [comment]
No still having problems getting the plug in to work.  Not sure what else to do.

**Comment by BenGitsCode** [comment]
You added both the `js` and `css` script tags?

**Comment by Ryaong792** [comment]
i added both via link but did not work.  I did a npm install and still not working :(

**Comment by Ryaong792** [comment]
i'm reviewing the NPM doc again but if anyone can come over to help that would be cool

**Comment by danman01** [comment]
I would do this: Google -> node datatables -> read through a few of the top posts to see how it's implemented.

Also what framework / language(s) are you using for frontend / backend?

**Comment by Ryaong792** [comment]
just using browser template and express/mongo api

**Comment by Ryaong792** [comment]
Yeah not sure what is wrong.  Maybe since i might be loading more then one JS that is overwriting it.

**Comment by danman01** [comment]
To be clear, you want to implement data tables on the client side as opposed to server side? Definitely check your javascript dev tools console too, and if you're getting an error, please post it here.

**Comment by Ryaong792** [comment]
vendor.js:11777 jQuery.Deferred exception: $(...).DataTable is not a function TypeError: $(...).DataTable is not a function
    at Object.addHandlers (http://localhost:7165/public/application.js:2524:18)
    at HTMLDocument.<anonymous> (http://localhost:7165/public/application.js:127:18)
    at mightThrow (http://localhost:7165/public/vendor.js:11500:30)
    at process (http://localhost:7165/public/vendor.js:11568:13) undefined

**Comment by danman01** [comment]
How are you including data tables? How are you calling data tables? Are you following a certain guide or method to implement DataTables that you have run through but your final outcome doesn't work as expected? If so, please link to that guide.

**Comment by Ryaong792** [comment]
i been following the guide from datatables.net . 

tried initialising it through JS 
$('#table_id').dataTable();
$('#table_id').DataTable();
$('#table_id').datatable();

etc
$(document).ready(function(){
    $('#myTable').DataTable();
});

The main problem is that when i try to require per directions its not working.  I would like someone to come by if possible to see what i'm doing wrong.  I might just give up on adding this feature.
https://datatables.net/manual/installation

NPM install -
npm install --save  datatables.net    # Core library
npm install --save  datatables.net-dt # Styling

**Comment by Ryaong792** [comment]
resolving issue - found that it needed to in index.js on the primary tree not the index.js on apps.
