### ISSUE TITLE
Request assistant with git history

### ISSUE THREAD

**Issue by khan-ngo** [ga-wdi-boston/capstone-project#614]
I inadvertently committed and merged data into our team project. I need to "undo" these changes from the team project's repo and restore from the commit from 

```
commit 4cbc09f0588306851a9d50c61621f42fc9ea05d0
Merge: be3b8bc 998feba
Author: conorjennings <conorjennings@users.noreply.github.com>
Date:   Fri May 19 01:35:05 2017 -0400
```

![image](https://cloud.githubusercontent.com/assets/26236941/26799540/10e1adc4-4a04-11e7-9477-d63c955ee5e8.png)

@mattkwondo

**Comment by BenGitsCode** [comment]
could you show the output of `git log --stat --oneline` and specific which commits you want to remove, by their SHAs?

**Comment by BenGitsCode** [comment]
Also this should be in the `team project` issue queue. 

Can you copy the contents of your message into a new issue on that queue? I will close this one when you've opened one there.

**Comment by khan-ngo** [comment]
Thanks, Ben. 
https://github.com/ga-wdi-boston/team-project/issues/332 has been submitted

**Comment by BenGitsCode** [comment]
Thanks!
