### ISSUE TITLE
Keeping API key secret

### ISSUE THREAD

**Issue by MattKwonDo** [ga-wdi-boston/capstone-project#616]
I am hoping to connect to the google (javascript) places web service api and am not sure how to keep my api key secret. I have added it to a .env file and added .env to the .gitignore, but I'm not sure how to pull it into my code. 

I have this code in my html, which connects successfully when I have my api key in place of "YOUR_API_KEY":

```html
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places"></script>
```

**Comment by BenGitsCode** [comment]
Can you think of an example of where we've used variables from our .env files before and see how it was done there?

What have you tried other than the script tag?

**Comment by MattKwonDo** [comment]
I looked into copying what was done in the express-multer-upload-api. Seems overly complicated, was thinking I should be able to access that value from the .env file and declare it as a variable?

**Comment by BenGitsCode** [comment]
What does the documentation for the api say?

**Comment by MattKwonDo** [comment]
I've been able to access the .env file and pull it in via the express template and then send it to the front end, though it's probably not the right way to do it and it's probably not secure. I'm going to hold off on continuing to work on this for the moment and focus on making the front-end look nicer.

**Comment by BenGitsCode** [comment]
Any updates on this Matt?

**Comment by MattKwonDo** [comment]
nope, still working on making it look nice. may be an enhancement.

**Comment by jordanallain** [comment]
wanna close this issue @MattKwonDo ?
