### ISSUE TITLE
Requirements Clarification

### ISSUE THREAD

**Issue by cpm5041** [ga-wdi-boston/capstone-project#617]
For MVP, I wanted to allow users to include an optional image URL to include a picture of a pet. This is a string which then renders in handlebars as an image. I want to make sure its not considered a "bug" if they post gibberish in the text field. I can account for this by adding an "alt" image value of "Image not found". I am considering an image upload but for MVP wanted to get this working. Thanks!

ERD: https://www.dropbox.com/s/6od6ckdyfqsumgk/Photo%20Jun%2005%2C%2010%2048%2032%20AM.jpg?dl=0

**Comment by payne-chris-r** [comment]
That sounds like a good plan!

**Comment by cpm5041** [comment]
Thanks, Chris! Closing this issue and will add an alt value to handle this.
