### ISSUE TITLE
Hitting a custom route from ember

### ISSUE THREAD

**Issue by antleo1995** [ga-wdi-boston/capstone-project#619]
So, back to thrashing a bit here. I have a custom route setup on the backend which I am going to use to pull everyone's recipes, so that you can see that list as a logged in user, and potentially save favorites. My problem is making a route from ember to hit that. 

What I am trying so far is to directly make this call from the model and parse he JSON into something useable as a model. 

in a new route called allrecipes
routes/allrecipes.js
```
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
   const  json =  Ember.$.getJSON('http://localhost:4741/allrecipes')
   console.log(json);
  }
});
```
As you can see I am hard coding the URL for now. This will return a json object, but I am having trouble massaging it into something useable for the route's model. 

You can just hit the URL as a custom route and it will return all recipes from all users as expected. 

the open-read file in my api(notice showall):
```
# frozen_string_literal: true
# Inherit from this class to allow unauthenticate access to read actions
class OpenReadController < ProtectedController
  READ_ACTIONS = [:index, :show, :showall].freeze
  skip_before_action :authenticate, only: READ_ACTIONS
  before_action :set_current_user, only: READ_ACTIONS
end
```
routes file in my api:
```
# frozen_string_literal: true
Rails.application.routes.draw do


  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  get '/allrecipes' => 'recipes#showall'
  resources :users, only: [:index, :show]
  resources :examples, except: [:new, :edit]
  resources :recipes, except: [:new, :edit]

end
```
and the code in the recipes controller:
```
  def showall
    # render json: current_user.recipes
    @recipes = Recipe.all
    render json: @recipes
  end
```

**Comment by BenGitsCode** [comment]
>This will return a json object, but I am having trouble massaging it into something useable for the route's model.

What have you tried so far in modifying what that returns?

**Comment by payne-chris-r** [comment]
Tony! King of the Thrashers! 😜

**Comment by antleo1995** [comment]
Trying to use JSON.parse, but that keeps barfing. Not sure if there is other recourse or just perhaps an easier way to hit this custom route. I had assumed and hoped that if I named the routes the same they would just line up...not the case apparently.

**Comment by payne-chris-r** [comment]
Getting ALL recipes should be a GET to /recipes
Getting ALL MY recipes should be a GET to /recipies?owned=true (or something like that)
The other way of showing JUST YOUR recipes is to look at how `ExamplesSerializer` works with `editable` and do the same, where in your Ember app GETS all of them, and then you filter by doing something like this: 
```html
{{#if thing.editable}}
  <span> heres that {{thing}}
{{/if}}
```

**Comment by antleo1995** [comment]
ok, i can go that route. thanks again. :D

**Comment by antleo1995** [comment]
Leaving this open for just a bit in case I am totally stuck.

**Comment by payne-chris-r** [comment]
You need to fight your urges to create custom routes -- they make it extremely difficult for future you and your coworkers. Custom routes should always be your last resort!

**Comment by antleo1995** [comment]
Fair enough. They give me fits enough. haha.

**Comment by antleo1995** [comment]
Ok, using editable as my control works wonderfully. I think I can comfortably close this issue. I have the edit button controlled this was as well so only items that can be edited get that button. Thanks again....

Moving along.
