### ISSUE TITLE
cannot use handlebars to render something on the screen

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/capstone-project#620]
I'm able to GET quotes in the console, but cannot render it on the screen. 
Unfortunately, not getting any errors to help out. I'm sure that I'm not making it to the handlebars file because I put errors in that file and none of them are happening. I believe the piece of data I want is undefined. Not sure why.

handlebars code:

```
{{#each quotes as |quote|}}
   <ul data-id="{{quote.id}}">
     <li> Date: {{quote.date}}</li>
     <li> Review: {{quote.quote_text}}</li>
   </ul>
{{/each}}
```

UI code:

```
const showQuotes = require('../templates/all_quotes.handlebars')
const getQuotesSuccess = (data) => {
  console.log('get quote success')
// the below line of code is undefined!!!!!!! 
  console.log(data.quotes)
  const showQuotesHTML = showQuotes({quotes: data.quotes})
  $('.render-quotes').html(showQuotesHTML)
}
```

**Comment by benjimelito** [comment]
I would start off by console.logging `data` after `getQuoteSuccess` has been called, just to see if it in fact has a property called `quotes` attached to it.

**Comment by awoodrum87** [comment]
thanks ben. I actually just realized that I can't pass in `data.quotes` but rather need to pass in just `data`
`const showQuotesHTML = showQuotes({quotes: data.quotes})`

It works now :)
