### ISSUE TITLE
Trouble resetting timer

### ISSUE THREAD

**Issue by naributler** [ga-wdi-boston/capstone-project#621]
I've built a timer that starts and stops using the following code: 
```
let timer = null
let duration = 1500

function tick () {
  // Decrease duration by increment of 1
  const time = --duration
  // Format time into minutes and seconds
  const minutes = parseInt(time / 60, 10)
  let seconds = parseInt(time % 60, 10)
  seconds = seconds < 10 ? '0' + seconds : seconds
  document.getElementById('input').innerHTML = (minutes + ':' + seconds)
  if (duration <= 0) {
    document.getElementById('input').innerHTML = "Time's Up!"
  }
}

function start () {
  tick()
  timer = setTimeout(start, 1000)
}

function stop () {
  clearTimeout(timer)
}

const timerHandlers = function () {
  $('#start').click(start)
  $('#stop').click(stop)
}
```
Now, I'm trying to reset the timer. The current strategy is to re-render the timer using this code: 
```
const resetTimer = function () {
  uxLogic.showTimer()
  timer.timerHandlers()
  $('#reset').click(resetTimer)
}
```
```
const showTimer = function () {
  console.log('showTimer ran')
  $('#timer').empty()
  $('#timer').append(TimerHB)
}
```
While the page does re-render when I click the RESET button, it still remembers how many intervals have passed. When I click the START button after resetting, it picks up right where it left off in the previous round. Is there a way to make the window "forget" how many intervals have passed so that the timer can start over?

I've looked at issue #550, but I don't believe resetting was addressed on that project. Thank you!

**Comment by benjimelito** [comment]
The amount of time lapsed is stored in the `duration` variable, correct? Are you able to somehow reset that variable to it's original value?

**Comment by naributler** [comment]
Ahh okay that makes sense..I will try that now

**Comment by BenGitsCode** [comment]
Any updates?

**Comment by naributler** [comment]
Sorry - just got back from lunch. Yes, this code worked: 
```
function reset () {
  document.getElementById('input').innerHTML = '25:00'
  // clearTimeout(timer)
  duration = 1500
  timer = null
}
```
Thank you, @benjimelito! Closing now.

**Comment by naributler** [comment]
Reopening because I have another timer issue :( 

I would like to prevent the user from clicking a button once it has already been clicked.  Here's the code I'm trying to use: 
```
const timerHandlers = function () {
  $('.start-timer').on('click', function () {
    start()
    $('.start-timer').off()
    $('.stop-timer').on()
    $('.reset-timer').on()
  })
  $('.stop-timer').on('click', function () {
    stop()
    $('.start-timer').on()
    $('.stop-timer').off()
    $('.reset-timer').on()
  })
  $('.reset-timer').on('click', function () {
    reset()
    $('.start-timer').on()
    $('.stop-timer').on()
    $('.reset-timer').off()
  })
}
```
The `on` and `off` hasn't been consistent. I clicked the start button. I tried to click it again and it would not let me. This is as intended because in previous versions of the code, the timer would speed up if I clicked the start button multiple times in a row. 

Then, I clicked the stop button. The timer stopped. Then, I clicked the start button again. The timer did not start up again.

I'm guessing I've missed something really obvious, but help would be appreciated. Thank you!

**Comment by BenGitsCode** [comment]
@narichasavanorkejoyce What does the jquery method `.on()` do? Is there another`one` with similar behavior you could be using?

**Comment by naributler** [comment]
`on` attaches some kind of event to a listener. `one` does the same thing as `on`, except it unbinds as soon as the action runs once. However, I'd still like to be able to repeatedly toggle between START, STOP, and RESET. I tried out `one`, but it doesn't let me rebind an action after it runs once. Maybe I'm not understanding your suggestion?

**Comment by BenGitsCode** [comment]
Ah, you had my suggestion right but I didn't realize that wasn't the issue. 🔨  

It sounds like you want to have those three states and toggle between them, have you thought about breaking those up into smaller pieces, it might make it easier to debug.

Have you stepped through those steps in a debugger to find out where it's unbinding?

**Comment by naributler** [comment]
Trying out another approach using `show` and `hide`. Once a user clicks a button, it goes away so they simply don't have the ability to click it again. If they click START, the only options left are to either STOP or RESET. If they click STOP, the only options are to START or RESET. If they click RESET, the only option they have left is to START. 

Here's the full code: 
```
let timer = null
let duration = 1500
let minutes

function tick () {
  console.log('tick ran')
  // Decrease duration by increment of 1
  --duration
  // Format duration into minutes and seconds
  minutes = parseInt(duration / 60, 10)
  let seconds = parseInt(duration % 60, 10)
  seconds = seconds < 10 ? '0' + seconds : seconds
  document.getElementById('input').innerHTML = (minutes + ':' + seconds)
  if (duration <= 0) {
    document.getElementById('input').innerHTML = "Time's Up!"
  }
}

function start () {
  timer = setInterval(tick, 1000)
}

function stop () {
  clearInterval(timer)
}

function reset () {
  document.getElementById('input').innerHTML = '25:00'
  clearInterval(timer)
  duration = 1500
  timer = null
}

const startHandlers = function () {
  $('#start-timer').on('click', function () {
    start()
    $('#start-timer').hide()

    $('#stop-timer').show()

    $('#reset-timer').show()
  })
}

const stopHandlers = function () {
  $('#stop-timer').on('click', function () {
    stop()
    $('#stop-timer').hide()

    $('#start-timer').show()

    $('#reset-timer').show()
  })
}

const resetHandlers = function () {
  $('#reset-timer').on('click', function () {
    reset()
    $('#reset-timer').hide()

    $('#start-timer').show()

    $('#stop-timer').hide()
  })
}

module.exports = {
  startHandlers,
  stopHandlers,
  resetHandlers,
  reset
}
```

**Comment by naributler** [comment]
And many many thanks to @payne-chris-r for helping me rework the timer logic!!!

**Comment by jordanallain** [comment]
are you still having an issue with this @narichasavanorkejoyce ?

**Comment by naributler** [comment]
It seems to be working now - I'll close the issue.
