### ISSUE TITLE
Error when deploying to front-end

### ISSUE THREAD

**Issue by MattKwonDo** [ga-wdi-boston/capstone-project#622]
I get the following errors on my deployed front-end:
GET https://mattkwondo.github.io/capstone-client/public/vendor.js index.html:11 
GET https://mattkwondo.github.io/capstone-client/public/application.js index.html:12 

the corresponding html:
```html
<script src="public/vendor.js" type="text/javascript" charset="utf-8" defer></script>
<script src="public/application.js" type="text/javascript" charset="utf-8" defer></script>
```

**Comment by BenGitsCode** [comment]
Woah Deja vu.

**Comment by BenGitsCode** [comment]
have you changed your repo name / project names recently?

**Comment by MattKwonDo** [comment]
ya, that should be up to date

**Comment by BenGitsCode** [comment]
What are the errors you're seeing on the client?

**Comment by MattKwonDo** [comment]
that's the only thing that shows in the console and my page won't load
anything after that. It is very plain, only the plain html loads

**Comment by BenGitsCode** [comment]
What's the output of `git diff origin/master --name-status`

It seems to work for me without any changes so there's likely something we're not seeing.

**Comment by MattKwonDo** [comment]
what does that do? doesn't seem to do anything on my end

**Comment by BenGitsCode** [comment]
Nothing is actually what I was expecting, I should have mentioned that. That means your remote and local repo are 👌 

when you run grunt deploy, you don't get any errors at all?

**Comment by MattKwonDo** [comment]
it doesn't look like there are any errors

**Comment by MattKwonDo** [comment]
I tried to take out those two lines from my index.html but that made the local version of the app do the same thing as the remote..

**Comment by BenGitsCode** [comment]
I'm on my way. I've got it working so let's just go step by step and find the differences. It's like finding Carmen Sandiego—except **we will.**

**Comment by MattKwonDo** [comment]
the setting for the gh-pages source was incorrect, needs to be gh-pages-branch:
![image](https://user-images.githubusercontent.com/25626886/26845559-d63683e0-4ac4-11e7-890b-f43b35700f63.png)

**Comment by MattKwonDo** [comment]
thanks, Ben!
