### ISSUE TITLE
Controlling Order of Ajax Calls/Rendering

### ISSUE THREAD

**Issue by rrdaniels85** [ga-wdi-boston/capstone-project#624]
Hello!

I've been struggling with an issue for a bit. In my application, the user has many tanks(aquariums) and each tank has many animals. One one of my screens, I want a user to be able to add animals to tank. After the POST request has been successfully processed and the create animal success function in UI has run, I want a GET request to be sent to get the new list of animals so they can be re-rendered by handlebars for the user with the new animal included. I have tried a number of different variations with .done and .then but cannot seem to control the order that the create animal success and get animals functions run. I suspect this has something to do with promises but am kind of stuck at the moment. Here is my code: 
Events.js
```
const onCreateAnimal = function (event) {
  console.log('yo')
  // prevent screen from refreshing
  event.preventDefault()
  // assign form field inputs to variable data
  const data = getFormFields(this)
  const tankId = $(event.target).attr('data-id')
  console.log(data)
  console.log(tankId)
  api.createAnimal(tankId, data)
    .done(ui.createAnimalSuccess(tankId), getAnimals(tankId))
    .catch(ui.createAnimalFailure)
}

const getAnimals = function (tankId) {
  // send request to API to get goals without an event trigger
  api.getAnimals(tankId)
    .then(ui.getAnimalsSuccess)
    .catch(ui.getAnimalsFailure)
}
```
api.js
```
 const createAnimal = (tankId, data) => {
  return $.ajax({
    url: config.apiOrigin + '/tanks/' + tankId + '/animals',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

const getAnimals = (tankId) => {
  return $.ajax({
    url: config.apiOrigin + '/tanks/' + tankId + '/animals',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```
ui.js
```
'use strict'
const store = require('../store.js')
const api = require('./api.js')
const listAnimalsTemplate = require('../templates/list-animals.handlebars')

const createAnimalSuccess = (data) => {
  $('#createanimalmodal').modal('toggle')
  $('body').removeClass('modal-open')
  $('.modal-backdrop').remove()
  console.log('you successfully created an animal')
  console.log('tank id after creat is', data)
}

const createAnimalFailure = () => {
  $('.createerror').text('An error occurred. You must fill in all fields in order to create an animal.')
  console.log('create animal failed')
}

const getAnimalsSuccess = (data) => {
  console.log('list animals ran')
  console.log('animal data list is', data)
  let listAnimals = listAnimalsTemplate({ animals: data.animals })
  $('#handlebarstwo').html(listAnimals)
  // const listAnimals = listAnimalsTemplate({ tanks: data.tanks })
  // $('#handlebarstwo').html(listAnimals)
}

const getAnimalsFailure = () => {
  console.log('get animals failed')
}
```
Any suggestions and/or guidance would be appreciated!

**Comment by rrdaniels85** [comment]
What's even more confusing is that in the console, it appears that they are executing in the right order given the POST then GET but the data coming back isn't  correct: 
<img width="452" alt="screen shot 2017-06-06 at 2 37 11 pm" src="https://user-images.githubusercontent.com/26202864/26845831-c863cc40-4ac5-11e7-8cfb-365d0a8a0de9.png">

**Comment by danman01** [comment]
Have you tried chaining like:
```
const someFunction = () => {
  return $.ajax({...})
}
  .done({...})
  .then({...})
```
This looks like a good comprehensive article on the topic of javascript promises: https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html

**Comment by rrdaniels85** [comment]
I have not.... let me look into this and ill keep you posted

**Comment by danman01** [comment]
This also looks like a helpful SO answer to look at the difference in `.then()` and `.done()`: https://stackoverflow.com/questions/5436327/jquery-deferreds-and-promises-then-vs-done

**Comment by rrdaniels85** [comment]
So, I tried reworking it and am still running into the same issue: 
```
const onCreateAnimal = function (event) {
  console.log('yo')
  // prevent screen from refreshing
  event.preventDefault()
  // assign form field inputs to variable data
  const data = getFormFields(this)
  const tankId = $(event.target).attr('data-id')
  console.log(data)
  console.log(tankId)
  api.createAnimal(tankId, data)
    .done(ui.createAnimalSuccess(tankId)).then(getAnimals(tankId))
    .catch(ui.createAnimalFailure)
}
```

**Comment by rrdaniels85** [comment]
I also tried moving my call to get animals to be inside the create animal success function and still have the same issue: 
```
const createAnimalSuccess = (data) => {
  console.log('create animal data is', data)
  $('#createanimalmodal').modal('toggle')
  $('body').removeClass('modal-open')
  $('.modal-backdrop').remove()
  api.getAnimals(data)
  .then(getAnimalsSuccess)
  .catch(getAnimalsFailure)
}
```

**Comment by payne-chris-r** [comment]
```js
const onCreateAnimal = function (event) {
  console.log('yo')
  // prevent screen from refreshing
  event.preventDefault()
  // assign form field inputs to variable data
  const data = getFormFields(this)
  const tankId = $(event.target).attr('data-id')
  console.log(data)
  console.log(tankId)
  api.createAnimal(tankId, data)
    .then(()=>{
      ui.createAnimalSuccess(tankId))
    })
    .then(()=>{
      getAnimals(tankId))
    })
    .catch(ui.createAnimalFailure)
}
```

**Comment by payne-chris-r** [comment]
Rules for Promisifying Your Code:

1. Only ever pass a function as a call back. NEVER pass a function invocation!

Why?
The difference is `.then()` _expects_ a callback. If you invoke the function, the `.then` gets a _value_ NOT a function to invoke later.
.then(JSON.parse)
// vs
.then(JSON.parse(json))


Source: https://git.generalassemb.ly/ga-wdi-boston/node-api-promises

**Comment by rrdaniels85** [comment]
Thanks! This was a helpful reminder on promises
