### ISSUE TITLE
Dynamically editing value of Ember textarea

### ISSUE THREAD

**Issue by jscohen** [ga-wdi-boston/capstone-project#625]
I am making a word-processor type app with a resource called Doc (i.e. document) in Ember.  I want to be able to dynamically set the value of a text area to the text of a document that I select.  Right now I am getting a list of the documents the following way by listing the documents in the docs.hbs template 

//models/doc.js
```js
import DS from 'ember-data';

export default DS.Model.extend({
  text: DS.attr('string'),
  title: DS.attr('string'),
  _id: DS.attr('string')
});

```

// docs.hbs
```html
<h2 class="titleHeader">Documents</h2>

{{#each model as |doc|}}
  {{#link-to "edit-doc" (query-params doc=doc)}}<h3>Edit this Doc</h3>{{/link-to}}
  <h4 class="titleHeader">{{doc.title}}</h4>
  <p class="titleHeader">{{doc.text}}</p>
  <br />
  <button {{action 'deleteDocs' doc}}>Delete this document</button>
{{/each}}
```

Upon linking to the edit-doc route, I have the following text area:

```html
{{outlet}}
<div class="new-doc-wrap">
  <h1 class="titleHeader">Edit title here</h1>
  <input class="editedTitle" type="text"/>
  {{textarea action 'mouseUp' cols='80' rows='6' class='jumbotron' id='doc' value=(mut (get doc text))}}
  <br />
  <button {{action 'saveDoc'}} type="button" data-dismiss="alert" aria-label="Close" class="textButton" style="color: black;">
    <span style="font-size: 3em;"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    Save Document</span>
  </button>

  {{yield}}
</div>
```

The idea is that if I click the edit link the next page will have a text area populated by doc.text for the selected doc.  However, nothing displays in the text area when this page loads.  I'm assuming this is something about passing the parameter.  I could also use a component where I can get the values of the selected doc, but I'm not sure how to set the value of the Ember text area from there.  Any help would be appreciated.  The mut and get helpers are based on the ember documentation for this specific scenario.

Thank you,

 - Jon

**Comment by BenGitsCode** [comment]
Any updates @jscohen ?

**Comment by jscohen** [comment]
Hi @BenGitsCode,

No updates yet.  I am trying to deploy for now, and I just opened another issue about that.

 - Jon

**Comment by jscohen** [comment]
@tvlangley just solved this issue for me.  We resolved it by putting the edit-doc component on the same page instead of trying to pass the doc resource via a link-to.  Closing issue
