### ISSUE TITLE
Issue deploying Ember App

### ISSUE THREAD

**Issue by jscohen** [ga-wdi-boston/capstone-project#627]
I am trying to deploy my app, created in Ember, to the Github IO pages.  I followed the instructions in the following template: 

https://github.com/ga-wdi-boston/ember-deployment-guide

My repo and page are called capstone_front_end.  My code is as follows:

// config/environment.js
```js
module.exports = function (environment) {
  'use strict';
  var ENV = {
    modulePrefix: 'https://jscohen.github.io/capstone_front_end',
    environment: environment,
    rootURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      },
      EXTEND_PROTOTYPES: {
        // Prevent Ember Data from overriding Date.parse.
        Date: false,
      },
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    },
  };

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
    let port = +('GA'.split('').reduce((p, c) =>
      p + c.charCodeAt().toString(16), '')
    );
    ENV.apiHost = `http://localhost:${port}`;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.rootUrl = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {
    ENV.locationType = 'hash';
    ENV.rootURL = '/capstone_front_end';
    ENV.apiHost = 'https://young-savannah-37906.herokuapp.com/'
  }

```

// app/adapters/application.js
// app/services/ajax.js

```js
import ENV from 'capstone_front_end/config/environment';

...etc.
```

When I deploy my build to github, I am seeing the following: https://jscohen.github.io/capstone_front_end/.  The background image shows, but no other part of the app does.  In addition, there is an error: 

vendor-0ac899bd131890656c4d18c41f701b13.js:1 Uncaught Error: Could not find module `https://jscohen.github.io/capstone_front_end/app` imported from `(require)`
    at o (vendor-0ac899bd131890656c4d18c41f701b13.js:1)
    at a (vendor-0ac899bd131890656c4d18c41f701b13.js:1)
    at requireModule (vendor-0ac899bd131890656c4d18c41f701b13.js:1)
    at ga-wdi-boston.ember-auth-92795d5….js:2

I'm not familiar with Ember deployment, and these look like minimized files.  I opened them on my end and could not figure them out.  

Thanks in advance,

 - Jon

**Comment by BenGitsCode** [comment]
Let's start with that environments file. The `modulePrefix` value should be the name of your client, not the URL. It should match the `ENV.rootURL` variable. Try changing it to the name of your client repo and redeploy.

**Comment by jscohen** [comment]
hi Ben,

I tried changing the name from the URL in modulePrefix to the name of the client, so now it looks like so:

```js
/* jshint node: true */

module.exports = function (environment) {
  'use strict';
  var ENV = {
    modulePrefix: 'capstone_front_end',
    environment: environment,
    rootURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      },
      EXTEND_PROTOTYPES: {
        // Prevent Ember Data from overriding Date.parse.
        Date: false,
      },
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    },
  };

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
    let port = +('GA'.split('').reduce((p, c) =>
      p + c.charCodeAt().toString(16), '')
    );
    ENV.apiHost = `http://localhost:${port}`;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.rootUrl = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {
    ENV.locationType = 'hash';
    ENV.rootURL = '/capstone_front_end';
    ENV.apiHost = 'https://young-savannah-37906.herokuapp.com/'
  }

  return ENV;
};

```

I'm still getting the same error, just with the new path:

Uncaught Error: Could not find module `capstone_front_end/app` imported from `(require)`
    at o (vendor-b0cbf5b….js:1)
    at a (vendor-b0cbf5b….js:1)
    at requireModule (vendor-b0cbf5b….js:1)
    at ga-wdi-boston.ember-auth-446c171….js:2
13:11:09.708

**Comment by BenGitsCode** [comment]
What is the output of `grunt nag`?

**Comment by BenGitsCode** [comment]
Ah scratch that, but feel free to share it anyway. In your own words, feel free to reference your terminal history with `history`, what steps did you follow for deployment. 

Your gh-pages branch does not look like it should.

**Comment by BenGitsCode** [comment]
Any updates @jscohen ?

**Comment by jscohen** [comment]
Hi Ben,

I committed my changes, did ember build --environment=production and then I followed the command on the ember deployment guide to push only the dist folder:

```sh
git subtree push --prefix dist origin gh-pages
```

My interpretation of this is that only the dist folder in my app should be pushed to the gh-pages branch.  It looks like given the error that something is looking for an app folder, which is not in dist.  The app folder is the main application folder.

**Comment by jscohen** [comment]
Folllowing instructions here: https://github.com/ga-wdi-boston/ember-deployment-guide

**Comment by BenGitsCode** [comment]
Yeah, that all sounds correct but what I'm seeing in your gh-pages doesn't have the expected result. Let's walk through it together. You in the kitchen area?

**Comment by jscohen** [comment]
I'm in the lobby near the front desk

**Comment by jscohen** [comment]
Issue resolved
