### ISSUE TITLE
Issues populating handlebars template

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/capstone-project#629]
My site is having issues populating a specific HB template. The site is a to-do list and uses various templates to switch views. When a user is at the all list view template (user-lists-all.handlebars), the user can click on a specific list which should bring them to another view template that will show all items for that list (items-view.handlebars). When the user gets to the items-view, nothing is showing up - it seems like I'm not iterating through the items array correctly to display them in the view.

Would it be possible to have someone look through this with me to ensure that I'm passing in the data correctly to the HB template? Thanks.

items-view.handlebars
```html
<p>This is from items-view.handlebars</p>

<ul>
  {{#each list as |list|}}
    {{#each list.items as |item|}}
      <li class='col-md-12 list-unstyled' data-id='{{item.id}}'>{{item.itemName}}
      </li>
    {{/each}}
  {{/each}}
</ul>
```

ui.js
```js
'use strict'

const store = require('../store')
const api = require('./api')
const showMainTemplate = require('../templates/main-page.handlebars')
const showListItemsTemplate = require('../templates/items-view.handlebars')
```
...
```js
const getListItemsSuccess = (data) => {
  console.log('+#+ get list items successful')
  console.log('getListItemsSuccess', data)
  const showListItems = showListItemsTemplate({
    list: data.list
  })
  $('#main-hb-div').html(showListItems)
}
```

**Comment by jordanallain** [comment]
have you opened up the ember inspector to see if you have access to the lists and items at that state in the app?

**Comment by ghost** [comment]
I'm just using browser template for now.

**Comment by jordanallain** [comment]
then throw a debugger in there and find out what yer data is

**Comment by ghost** [comment]
I can see the data from the console.log, and it's correct. Not sure if I'm rendering the stuff in the template correctly?

**Comment by jordanallain** [comment]
is it happening asynchronously?

**Comment by ghost** [comment]
Think it's happening in the correct order - is there a way to check?

**Comment by jordanallain** [comment]
you can step through line by line with a debugger

**Comment by ghost** [comment]
I'll check with the debugger

**Comment by ghost** [comment]
Stepping through with the debugger, I can see that the sequence to bring up the template is correct. I also put some test text in template and it shows up correctly, but items are not showing.

**Comment by ghost** [comment]
Seems like I had nested too much in the handlebars template. Changed the following code from:
```html
<ul>
  {{#each list as |list|}}
    {{#each list.items as |item|}}
      <li class='col-md-12 list-unstyled' data-id='{{item.id}}'>{{item.itemName}}
      </li>
    {{/each}}
  {{/each}}
</ul>
```
to:
```html

<ul>
    {{#each list.items as |item|}}
      <li class='col-md-12 list-unstyled' data-id='{{item.id}}'>{{item.itemName}}
      </li>
    {{/each}}
</ul>
```
