### ISSUE TITLE
Edit form does not populate

### ISSUE THREAD

**Issue by LaurenGrant** [ga-wdi-boston/capstone-project#63]
I just made a function with a get method that will allow me to populate an edit field with information from an object id. I can see the objects information in my console but it is not loading up in my edit form. 

There is no specific error in my console which makes me believe it how I call my form id or class when I hide and show it. I have googled this for a while now and talked with a few classmates and no solutions have worked yet.

**Comment by gaand** [comment]
Okay.  This seems like talking with an instructor is the first step in clarifying the issue.
