### ISSUE TITLE
Sign in modal not allowing access to page after success

### ISSUE THREAD

**Issue by MattKwonDo** [ga-wdi-boston/capstone-project#630]
I could use help troubleshooting why the tint over the page no longer goes away on sign in success. 

I can tell that sign in works successfully, I'm just not able to interact with the app because the tint stays on the page. I recently moved the modal html from a different part of the index.html.

**Comment by payne-chris-r** [comment]
Code? What you've tried? Your issues should be better than this by now.

**Comment by MattKwonDo** [comment]
Figured it was too complex to copy in all my code.
Resolved with adding this into my signInSuccess function:
$('.modal-backdrop').remove()

**Comment by MattKwonDo** [comment]
also added this in the signInSuccess function: $('#signInModal').modal('hide')
