### ISSUE TITLE
Table not displaying data after successful update

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/capstone-project#631]
My front end is not displaying the output after a successful call to update a row on my table. There are no errors been generated. This only happens after I generate an UPDATE command. The show table button works correctly the first time i click it and displays the handlebars output. 

But once I do an update (which works correctly) and then hit the same 'show' button again, nothing displays on the screen and no errors thrown anywhere.

Spent 2+ hour on this and got no where in debugging. 

Let me know what else you need as I could copy/paste a ton of code... but in the interest of time, maybe a 1-1 on my one and only issue for capstone project would greatly help.

Thank you

**Comment by payne-chris-r** [comment]
Past the code that runs the API call

**Comment by payne-chris-r** [comment]
Paste*

**Comment by glasneed** [comment]
Here is the API call from wine-events. 

``` const readWines = function () {
  api.readWines()
    .done(ui.readWinesSuccess)
    .fail(ui.readWinesFailure)
} ```

**Comment by glasneed** [comment]
index.html call site: 
```  
 <div class="section">
    <div class="row container">
      <h2 class="header">Wine Collection</h2>
      <button class="grey-text text-lighten-4 wine-list green-grape-color" id ="read-wines">Wine List</button>
      <button class="grey-text text-lighten-4 wine-list green-grape-color create-wine-open-form">Add Wine</button>
      <div class="list-group" id="wine-collection"></div>  <!-- This is where handlebars dynamically loads the entire list of wines -->
    </div>
  </div> 
```

Here is the relevant handler code in wine-events:
```
 const wineHandlers = () => {
...
  $('#read-wines').on('click', readWines)
} 
```

which in turn invokes this method in wine-events:
```
 const readWines = function () {
  api.readWines()
    .done(ui.readWinesSuccess)
    .fail(ui.readWinesFailure)
} 
```

The odd behaviour is:
1) Zero errors in console window so nothing to go on.
2) It works correctly the first time I click the button to display the wines.

**Comment by glasneed** [comment]
I put console.log statements in events call site, the API Ajax GET method and the UI for readWinesSuccess and can validate that all 3  are been invoked correctly when I click 'Wine List' button. So all steps are firing off, just the rendering of the output on the screen is not occurring. Thats all I have..

**Comment by glasneed** [comment]
And here is the UI code that invokes the handlebars to then display the output in the HTML ID of #wine-collection..

``` 
const readWinesSuccess = (data) => {
  store.wines = data.wines
  console.log('>>> Entering readWinesSuccess with data ', data)
  const showWinesInCellar = wineListingHandleBars({ wines: data.wines })
  $('#wine-collection').html(showWinesInCellar)
}
```

**Comment by jordanallain** [comment]
you never pasted in what chris asked you to paste in earlier!

**Comment by jordanallain** [comment]
have you looked at the `heroku logs` for when you are updating?

**Comment by payne-chris-r** [comment]
Does it work after you refresh the page?
This line concerns me: `const showWinesInCellar = wineListingHandleBars({ wines: data.wines })`

**Comment by glasneed** [comment]
Yes it does work after I sign out and back in.
The ``` showWinesInCellar``` does contain all the correct data when I console.log it.

**Comment by payne-chris-r** [comment]
Even the second time (after it's added)?

**Comment by payne-chris-r** [comment]
Are you reassigning `showWinesInCellar`?

**Comment by glasneed** [comment]
No I am not. I just use it in my ``` readWinesSuccess ``` function as shown above.

Just to recap, this works correctly the first time I invoke. But once I click on the update button (and even if i hit the cancel button immediately to go back to main screen) hitting the Show wines button doesn't render the output. Even though the output is correctly been captured in the above handlebars query in my onSuccess method.

**Comment by glasneed** [comment]
Per Jordan's comment, let me look at the logs on the rails back end to see if anything jumps out. Otherwise can I meet first thing tomorrow with a consultant to review in person.

Thank you

**Comment by glasneed** [comment]
No issues with back end server logs. Also retested a PATCH CURL script and it worked fine. When I click "Wine List" button each time, it logs the following on the back end (Completed 200 OK) as well as store all this returned data in handlebars correctly. It just doesn't render on screen.


``` Started GET "/wines" for 127.0.0.1 at 2017-06-07 20:06:25 -0400
Processing by WinesController#index as */*
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "4a96ec012e17238bb90af74879b6c72d"], ["LIMIT", 1]]
  Wine Load (0.5ms)  SELECT "wines".* FROM "wines"
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Json (3.31ms)
Completed 200 OK in 8ms (Views: 5.4ms | ActiveRecord: 0.7ms)

```

**Comment by payne-chris-r** [comment]
What happens the second time through that function though? I'm not sure reassigning is the right move... and esp not using const inside the function. Do a log of showWinesInCellar before you try to render it.

**Comment by glasneed** [comment]
I did write ``` showWinesInCellar ``` to a console.log  before it is rendered and it does show the correct data for 3 bottles of wine:

```
 wine-ui.js:24 showWinesInCellar =      <div class="col s3" data-id="3" >
      <h5>
        Joel Gott
      </h5>
          <h6>Grape: Zinfandel</h6>
          <h6>Vintage: 2014</h6>
          <h6>Quantity: 19</h6>
      <button type="button" class="update-one-wine btn btn-default" data-id="3"><i class="material-icons right">mode_edit</i></button>
      <button type="button" class="delete-wine btn btn-default" data-id="3"><i class="material-icons right">delete_forever</i></button>
      </p>
      </div>
    <div class="col s3" data-id="6" >
      <h5>
        Cakebread Cellars
      </h5>
          <h6>Grape: Chardonnay </h6>
          <h6>Vintage: 2012</h6>
          <h6>Quantity: 28</h6>
      <button type="button" class="update-one-wine btn btn-default" data-id="6"><i class="material-icons right">mode_edit</i></button>
      <button type="button" class="delete-wine btn btn-default" data-id="6"><i class="material-icons right">delete_forever</i></button>
      </p>
      </div>
    <div class="col s3" data-id="11" >
      <h5>
        Cline Cellars
      </h5>
          <h6>Grape: Zinfandel</h6>
          <h6>Vintage: 2012</h6>
          <h6>Quantity: 48</h6>
      <button type="button" class="update-one-wine btn btn-default" data-id="11"><i class="material-icons right">mode_edit</i></button>
      <button type="button" class="delete-wine btn btn-default" data-id="11"><i class="material-icons right">delete_forever</i></button>
      </p>
      </div> 
```

**Comment by payne-chris-r** [comment]
const readWinesSuccess = (data) => {
  store.wines = data.wines
  $('#wine-collection').html(wineListingHandleBars({ wines: data.wines }))
}

**Comment by glasneed** [comment]
Thanks for the suggestion. I tried it out but yielded the same result. I attached a photo of log that shows what renders each time I click the button after I used the Update button followed by a cancel. No errors, just GET function been invoked each time...
<img width="517" alt="screen shot 2017-06-07 at 10 16 22 pm" src="https://user-images.githubusercontent.com/26227953/26909497-3f7d0238-4bcf-11e7-96a7-42a8b466af5a.png">

**Comment by glasneed** [comment]
Chris - Thanks for all your help with debugging this one. It took much longer than it should have!

The bug was caused by code I'd written when the user clicks on the Cancel button in the Update Form.  

```
  $('#update-wine-form').on('reset', onHideUpdateWine)
```
This onHideUpdateWine method hides the updateWine form as well as the  wine-collection too!

```
const onHideUpdateWine = function () {
  $('#update-wine-form').hide()
  $('.parallax-section').show()
  $('#wine-collection').hide()
}
```

What I needed to add back into the UI code was the following:

```
const readWinesSuccess = (data) => {
  store.wines = data.wines
  $('#wine-collection').html(wineListingHandleBars({ wines: data.wines }))
  $('#wine-collection').show()
}
```
