### ISSUE TITLE
Please help - authentication not working in production

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/capstone-project#633]
I have both client and api deployed and the authentication is not successful in the client.
Based on researching other issues, I closely followed steps again in heroku deployment guide repo.
I reviewed the production database (heroku) and the posts are populating the database (users table).

I reviewed the code and references in the client files and corrected a couple small spellings that fixed but redeployed and still getting an error upon signup.

The authentication works correctly on my local.

My deployed (but, by no means ready) client and api are:
https://lisamsmith100.github.io/listFul/
https://listful-rails-api.herokuapp.com/

Here's what I see:
<img width="1399" alt="screen shot 2017-06-07 at 10 04 23 pm" src="https://user-images.githubusercontent.com/26127720/26909214-56e6514c-4bcd-11e7-83d5-6e2b1b28d9dd.png">

This issue is causing delay with dev and testing of the authenticated items.  Really need help.  Thanks.

**Comment by awoodrum87** [comment]
My prod back end wasn't working earlier either. Questions I was asked to diagnose:
does it work locally? If yes..
does your `config.js` point to your heroku app?
did you run migrate in the heroku app? (this was my issue)

**Comment by lisamsmith100** [comment]
Thanks, Angie!
It works locally.
My config.js file points to my heroku app.
I ran heroku migrate command per the deployment guide and all other commands.
I reviewed the production database and the posts are working with a correct 201 Created.

Here's what heroku logs command shows me:
```sh
2017-06-08T02:37:50.317452+00:00 app[web.1]: [44a702c6-6a90-48fe-8e9e-e38f0107979f]   User Exists (1.3ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "ihaveanissue"], ["LIMIT", 1]]
2017-06-08T02:37:50.319800+00:00 app[web.1]: [44a702c6-6a90-48fe-8e9e-e38f0107979f]   SQL (1.3ms)  INSERT INTO "users" ("email", "token", "password_digest", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["email", "ihaveanissue"], ["token", "dcbccf6de38d5f5d23a8d2e7cbcd6d31"], ["password_digest", "$2a$10$SxVVxSCWPX.0AT6UbmZNQuLOLnfNm9/14YmPfMHe/.ljYCSW7kNCu"], ["created_at", 2017-06-08 02:37:50 UTC], ["updated_at", 2017-06-08 02:37:50 UTC]]
2017-06-08T02:37:50.322119+00:00 app[web.1]: [44a702c6-6a90-48fe-8e9e-e38f0107979f]    (1.9ms)  COMMIT
2017-06-08T02:37:50.324463+00:00 app[web.1]: [44a702c6-6a90-48fe-8e9e-e38f0107979f]   User Exists (1.3ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 AND ("users"."id" != $2) LIMIT $3  [["email", "ihaveanissue"], ["id", 12], ["LIMIT", 1]]
2017-06-08T02:37:50.325318+00:00 app[web.1]: [44a702c6-6a90-48fe-8e9e-e38f0107979f] [active_model_serializers] Rendered UserSerializer with ActiveModelSerializers::Adapter::Json (0.26ms)
2017-06-08T02:37:50.325544+00:00 app[web.1]: [44a702c6-6a90-48fe-8e9e-e38f0107979f] Completed 201 Created in 88ms (Views: 0.8ms | ActiveRecord: 6.9ms)
```
and it's in my production database.

Here's result of heroku logs command:
```sh
$ heroku config
=== listful-rails-api Config Vars
CLIENT_ORIGIN:            https://lisamsmith100.github.io/listFul/
DATABASE_URL:             postgres://xvqxwlxeivkkub:c4fbe042a9b44d303043f1d728570bfd5aa9f9d55118e4552e3ac39ff48a7faa@ec2-23-23-222-147.compute-1.amazonaws.com:5432/dac7hsjmue2auo
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_LOG_TO_STDOUT:      enabled
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          50642b86262ffa7de9c4140ccc1b395078c43c4ec3f73949fc78ee9368a0df6861a25037b65e2b84c105c1043ff4fa51ef227d8230a8a55d24530c4aa5966242
SECRET_TOKEN:             fd86a387d83e438deb12d64ffe80ecbcffd2ba337342eb6281835dd380cd171af3ccfb1a98de980c2d85487fac111356833ca1284a63daba7b2a46f9f3feae1a

```

something on front end... but not seeing it.

**Comment by MattKwonDo** [comment]
You have a (extra) forward slash at the end of your path in your config file causing the path to have two //'s in a row: "...//sign-in."

**Comment by lisamsmith100** [comment]
Will give that a shot

**Comment by lisamsmith100** [comment]
Removing the slash did not solve the issue
they're posting to database but maybe it's the promise.  at this pace, I'm not going to meet expectations.  any help with this would be greatly appreciated.
<img width="1247" alt="screen shot 2017-06-08 at 1 06 06 am" src="https://user-images.githubusercontent.com/26127720/26913079-ae70c550-4be6-11e7-833e-043d56244bf7.png">
I will take another look at the promise but it is borrowed code from a working api.  Can someone take a look with me first thing in am?  I'm frantic and need another pair of eyes.  Thanks.

**Comment by naributler** [comment]
Hey Lisa, I ran into this issue as well. I basically went through every step in the Heroku deployment guide again (git push heroku master, heroku run rake db:migrate, heroku run rake db:seed, generate new secrets, heroku restart). Then, the authentication worked.

**Comment by BenGitsCode** [comment]
Lisa, try what Nari suggested and update us with any changes.

**Comment by lisamsmith100** [comment]
Thanks. I gave that a shot yesterday before posting the issue, each one of those commands but still not working.  Giving something else a try.

**Comment by lisamsmith100** [comment]
The issue is closed.  The problem was that for the client origin I was using 
https://lisamsmith100.github.io/listFul/
instead of 
https://lisamsmith100.github.io when assigning CLIENT-ORIGIN.
