### ISSUE TITLE
Request for 1:1 to discuss user feedback

### ISSUE THREAD

**Issue by vanduong28** [ga-wdi-boston/capstone-project#635]
I would like to meet briefly to review user feedback on my app when an item is added, updated, and deleted. I would like to confirm there are no issues with the display dynamically updating without a confirmation message explicitly displayed.

**Comment by BenGitsCode** [comment]
When you say dynamically updating you mean that as a user, i perform a crud action and then I immediately see the result of the action, displayed on the page?

**Comment by vanduong28** [comment]
Yes. For example, when a user wants to add a new item to the list a modal opens for them to input fields. Upon submission the modal is closed and the list is updated with the new information at the top of the list but I don't have a message that explicitly tells them the item was successfully added.

**Comment by BenGitsCode** [comment]
I think that's great, as long as the user is never unclear on what's happening that's what's important. Is your client deployed?

**Comment by vanduong28** [comment]
Thanks for the feedback!

Client: https://vanduong28.github.io/eatalog/

The current deployment has an alert upon successful update (successful creation and deletion do not have messages displayed) but I would like to remove it as I don't like that type of user feedback and prefer to have the list dynamically update without the display of a message.

**Comment by BenGitsCode** [comment]
Ah ok, I'll go through it now and see how it feels. I think that's okay—notifications are most important when the result of user actions isn't immediately obvious, i.e. not having a notification along the lines ` resource was updated, click update list to view new item` when you need to perform another action, like clicking a button, to see that update—that would be poor ux.

**Comment by vanduong28** [comment]
Thanks for talking it through with me, @BenGitsCode! I redeployed the client to remove the successful update alert as that was a bit more distracting than beneficial. Let me know if there are any issues with the new deployment. If not I will close the issue.

**Comment by BenGitsCode** [comment]
I'll take a look at that now, tangentially it looks like one of those errors is your signup ajax firing twice so you should take a look at that. Let me know if you're not able to reproduce it.

**Comment by BenGitsCode** [comment]
Definitely like it better without the notification 👍

**Comment by vanduong28** [comment]
I still haven't been able to reproduce the error on my side but made an update to my onSignUp function (event.preventDefault() was called twice) and deployed the changes. Please let me know if you are still encountering issues with sign up. Thanks!

**Comment by BenGitsCode** [comment]
I'm still getting a 500, after the 201 on signup 🤔

**Comment by vanduong28** [comment]
I was listening for the sign up event in two places (doh!) and that is why the ajax request was called twice. I have since removed the duplication and deployed and the 500 error is no longer appearing.

**Comment by BenGitsCode** [comment]
No more double POSTS tested on 3 browsers with three different users 🎉  Good catch!

**Comment by vanduong28** [comment]
Thanks for all your help, really appreciate it!
