### ISSUE TITLE
Imgur for Audio

### ISSUE THREAD

**Issue by naributler** [ga-wdi-boston/capstone-project#639]
I'd like to play a sound when the timer on my app finishes. The sound plays locally. I downloaded a .wav file and reference it using this code: 
`<audio id="alert-audio" src="assets/scripts/audio/bell-ring.wav"></audio>`

However, the bell-ring.wav file cannot be found in production. In order to display images in production, I usually upload to Imgur and reference the file from there. Is there a site like Imgur that I could use for accessing audio files?

**Comment by jordanallain** [comment]
theres a bunch, you can try this one

https://clyp.it/

**Comment by jordanallain** [comment]
theres also soundcloud, vocaroo, probably more too.

**Comment by naributler** [comment]
Thanks! I tried out clyp.it, but I'm still not quite there. I tried setting the source to `src="https://clyp.it/p4b4v1gq/widget"`. Sound didn't play. 

I'm guessing it's because on clyp.it, I still have to click play in the widget in order to get the sound. I don't have that kind of button on my app - I just want the sound to play when the timer ends. 

I'll check out soundcloud and vocaroo to see if they offer more options.

**Comment by BenGitsCode** [comment]
Let me know if that works/changes the error at all!

**Comment by naributler** [comment]
This works locally! 
`<audio id="alert-audio" src="https://raw.githubusercontent.com/narichasavanorkejoyce/pomodoro-client/master/assets/scripts/audio/bell-ring.wav"></audio>`

Now, I'm trying to deploy and test it in production. I'm having some issues deploying though - my site isn't updating with the latest version. Will post when I can get it running again...

**Comment by naributler** [comment]
Oh! The latest version of my site just deployed..I guess I just had to wait a bit. 

The sound works now!! Thank you, @BenGitsCode!!

**Comment by BenGitsCode** [comment]
¯\_(ツ)_/¯
