### ISSUE TITLE
CORS error thrown when logging in, but it still works anyways?

### ISSUE THREAD

**Issue by TeoPaolucci** [ga-wdi-boston/capstone-project#64]
When I log in with an account on my front-end, I get the following error:

```
XMLHttpRequest cannot load http://localhost:3000/login. The request was redirected to 'http://localhost:3000/', which is disallowed for cross-origin requests that require preflight.
```

The weird part is, my backend still creates a session cookie to a valid logged in user and if I refresh the page, it acts as if the user is logged in (the intended behavior).

**Comment by jrhorn424** [comment]
What does your back-end action look like?

**Comment by srhoulam** [comment]
Teo, your handler for the `/login` route is redirecting users to `/`. It doesn't mean the login doesn't work, but it does mean the browser will be unhappy about it. I wrote the fix code for project 3 and slacked it in the code channel.

**Comment by srhoulam** [comment]
https://ga-students.slack.com/archives/wdi-bos-09-code/p1448908245000003
https://ga-students.slack.com/archives/wdi-bos-09-code/p1448908296000005

**Comment by TeoPaolucci** [comment]
Thanks Saad
