### ISSUE TITLE
Thrashing hard over here - many bugs

### ISSUE THREAD

**Issue by antleo1995** [ga-wdi-boston/capstone-project#640]
So, I have my feature more or less completed, but my site is doing terribly whacky things now. I have no clue what to do. 

First and foremost, my association is broken. When Ember is trying to look up the picture for the recipe it is looking for the recipe id as the picture ID
in other words, if I am looking at recipe 7
my url is: http://localhost:7165/recipes/7

When it tries to look up the picture it goes to 
http://localhost:4741/pictures/7

But the picture ID is not the same as the recipe ID so it fails. 

Additionally, for some crazy reason, I have a bug where if I upload a photo, and come back to another recipe, then it starts loading the last uploaded URL to all the recipes in site. 

Help please. Really concerned I won't get these bugs fixed in time. If I can figure out these last things I can call it complete, but I fear thrashing too much and making things worse. 

Really want to figure out the mis-matched association more than anything. 

I believe this is all done in the models in ember:
So...

Recipe model:
```
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  ingredient_list: DS.attr('string'),
  directions: DS.attr('string'),
  prep_time: DS.attr('string'),
  editable: DS.attr('boolean'),
  picture: DS.belongsTo('picture', {async: true})
});
```

and picture model:
```
import DS from 'ember-data';

export default DS.Model.extend({
  url: DS.attr('string'),
  recipe: DS.belongsTo('recipe', {async: true})
});
```
Let me know if you would like to look at any other files.

**Comment by jordanallain** [comment]
Hmm we'll try to look at one problem at a time. Which problem do you think should be solved first?

**Comment by antleo1995** [comment]
The association issue - I am fairly certain this was working yesterday.

**Comment by jordanallain** [comment]
So the problem is that it is using the recipe id to lookup both the recipe and the picture?

have you checked in rails to see how you are extracting those IDs?

**Comment by antleo1995** [comment]
Pretty sure that was the serializer..right?
recipe serializer
```
class RecipeSerializer < ActiveModel::Serializer
  attributes :id, :title, :ingredient_list, :directions, :prep_time, :editable,
            :picture

  def picture
    object.id
  end

  def editable
    scope == object.user
  end
end
```
picture serializer:
```
# frozen_string_literal: true
#
class PictureSerializer < ActiveModel::Serializer
  attributes :id, :url, :recipe

  def recipe
    object.recipe.id
  end
```

**Comment by jordanallain** [comment]
i was thinking controller actions, where is it extracting the id from the url?

**Comment by antleo1995** [comment]
Not sure exactly what to look for but it looks like the items controller as best I can tell:
```
# frozen_string_literal: true

class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :update, :destroy]

# GET /pictures
# GET /pictures.json
def index
  @pictures = Picture.all

  render json: @pictures
end

# GET /pictures/1
# GET /pictures/1.json
def show
  render json: @picture
end

# POST /pictures
# POST /pictures.json
def create
  @picture = Picture.new(picture_params)

  if @picture.save
    render json: @picture, status: :created, location: @picture
  else
    render json: @picture.errors, status: :unprocessable_entity
  end
end

# PATCH/PUT /pictures/1
# PATCH/PUT /pictures/1.json
def update
  @picture = Picture.find(params[:id])

  if @picture.update(picture_params)
    head :no_content
  else
    render json: @picture.errors, status: :unprocessable_entity
  end
end

# DELETE /pictures/1
# DELETE /pictures/1.json
def destroy
  @picture.destroy

  head :no_content
end

  private

def set_picture
  @picture = Picture.find(params[:id])
end

def picture_params
  params.require(:picture).permit(:url, :recipe_id)
end
end
```

**Comment by antleo1995** [comment]
I will note that dependent destroy is working so if I delete a recipe it delete the corresponding picture

**Comment by jordanallain** [comment]
this is the line i'm talking about

`@picture = Picture.find(params[:id])`

is it possible that it is getting the recipe ID from this line?

**Comment by antleo1995** [comment]
Again, seems to match the items controller, but I tried it with recipe ID just in case but no go.

**Comment by antleo1995** [comment]
Looking at ember resources it definitely does go to the item route and grab the id's that are associated with the list - not sure what's different

**Comment by jordanallain** [comment]
ahh okay hmm..

```
class RecipeSerializer < ActiveModel::Serializer
  attributes :id, :title, :ingredient_list, :directions, :prep_time, :editable,
            :picture

  def picture
    object.id
  end
```

so you're thinking its how you are building the picture here? I could see that because it looks like it is using the id from recipe perhaps. Maybe using `object.picture.id` ? but yeah could be something in the serializer.

**Comment by antleo1995** [comment]
i am looking specifically at that. That line should be object.picture.id, but for whatever reason that totally blows up even though binding.pry shows this to give the picture ID

**Comment by antleo1995** [comment]
give this error:
 Completed 500 Internal Server Error in 67ms (ActiveRecord: 8.7ms)


  
NoMethodError (undefined method `id' for nil:NilClass):
  
app/serializers/recipe_serializer.rb:8:in `picture'
app/controllers/recipes_controller.rb:8:in `index'

**Comment by jordanallain** [comment]
could be a case of needing to use pluck again, here's an article that talks a little about what pluck and select do.

http://findnerd.com/list/view/Select-Vs-Pluck-in-Rails/19258/

**Comment by jordanallain** [comment]
more plucky goodness https://collectiveidea.com/blog/archives/2015/05/29/how-to-pluck-like-a-rails-pro

**Comment by antleo1995** [comment]
so, pluck is for multiple ids. what is confusing once again is I can access object.picture.id - this will give me a picture ID back, but for whatever reason if I use that in my code i get the above error, makes no sense - i am even doing that on the picture controller just fine - 

```
# frozen_string_literal: true
#
class PictureSerializer < ActiveModel::Serializer
  attributes :id, :url, :recipe

  def recipe
    object.recipe.id
  end
end
```

**Comment by tvcrawley** [comment]
Is there a way for the api to find the `picture id` in the params?

**Comment by antleo1995** [comment]
i believe i tried that

**Comment by antleo1995** [comment]
Changed the recipe controller code to :
```  
def picture
    object.picture(:id)
  end
```

No longer barfing but now it isn't looking for the picture at all

**Comment by antleo1995** [comment]
So, now the back end is grabbing the correct record but now ember is no longer trying to use the records. ....chasing my tail here....

**Comment by MicFin** [comment]
Could you please explain why you are setting `async: true` in your models?
```js
export default DS.Model.extend({
  url: DS.attr('string'),
  recipe: DS.belongsTo('recipe', {async: true})
});

export default DS.Model.extend({
  title: DS.attr('string'),
  ingredient_list: DS.attr('string'),
  directions: DS.attr('string'),
  prep_time: DS.attr('string'),
  editable: DS.attr('boolean'),
  picture: DS.belongsTo('picture', {async: true})
});
```

**Comment by antleo1995** [comment]
not sure - probably just how the example i saw showed it.

**Comment by MicFin** [comment]
In a simple relationship, where a User hasMany Stuff,
```js
stuff: DS.hasMany('stuff', {async: false})
```
then Ember Data is expecting a request for User to get something like this in response:
```js
{
stuff: [ { id: 1, user_id: 1 }, { id: 2, user_id: 1 }, { id: 3, user_id: 1 } ],
user: { id: 1, stuff_id: [1, 2, 3] }
}
```
but if the relationship was
```js
stuff: DS.hasMany('stuff', {async: true})
```
then Ember Data is just expecting this:
```js
{
user: { id: 1, stuff_id: [1, 2, 3] }
}
```
Check your API response by going to its URL and seeing if the data is what your ember app is expecting.

**Comment by antleo1995** [comment]
```
{
"picture": {
"id": 19,
"url": "http://www.sjerseybusinessdirectory.com/uploads/news-pictures/1-new-york-blog-post-image-20160120150120.jpeg",
"recipe": {
"id": 20,
"title": "test",
"ingredient_list": "test",
"directions": "test",
"prep_time": "test",
"created_at": "2017-06-08T18:35:12.212Z",
"updated_at": "2017-06-08T18:35:12.212Z",
"user_id": 1,
"editable": false,
"picture_id": null
}
}
}
```
Api is handing

**Comment by antleo1995** [comment]
Kinda back to where I started now:
Error when loading a record - notice it is passing an object rather than an ID to the get pictures call
```
14:49:04.158 :4741/pictures/%5Bobject%20Object%5D:1 GET http://localhost:4741/pictures/%5Bobject%20Object%5D 404 (Not Found)
14:49:04.159 jquery.js:9566 XHR finished loading: GET "http://localhost:4741/pictures/%5Bobject%20Object%5D".
```

**Comment by antleo1995** [comment]
So here is what my console shows when I run the serializer for object.picture(:id):
```
Object.picture(:id) is: 
#<Picture:0x007ff8b94fe958>
```

Somehow i need to get a actual number passed over from the serializer, I believe, for ember to find the records.

**Comment by antleo1995** [comment]
ok, so i figured out one part of the problem - now it isn't loading the picture automatically. I have to refresh the page on the recipe and it will finally load the image

I had to do some JSON wizardry to get the ID to come over - my serializer:
```
  def picture
    response = object.picture.as_json
    response[0]['id']
  end
```

So, that's one part of the issue fixed. I now can hit the correct path. But I still don't know why ember isn't getting this record when the component loads.

**Comment by MicFin** [comment]
Your rails API should not be sending back TWO `id` properties with its resource, right?  How could you fix that?
```js
"picture": {
"id": 19,
"url": "http://www.sjerseybusinessdirectory.com/uploads/news-pictures/1-new-york-blog-post-image-20160120150120.jpeg",
"recipe": {
"id": 20,
```

**Comment by MicFin** [comment]
Did you try removing the `{async: true}`?

**Comment by antleo1995** [comment]
Two ids is probably correct. One is for the picture, and one is for the recipe. and I did try making async false...let me try removing it

**Comment by MicFin** [comment]
Yes, I deleted my comment about the IDs because I misread the response you posted.

**Comment by antleo1995** [comment]
Oh, and my 'fix' for the ID not coming over now breaks my create ...sigh...

**Comment by antleo1995** [comment]
Thanks for the help everyone. This feature now functions as intended! Closing issue

**Comment by MicFin** [comment]
@antleo1995 can you share what the bug was and how it was fixed?

**Comment by antleo1995** [comment]
Ultimately it was an issue with the serializer as suspected. Null records for picture - which were expected were causing the system to stop dead in its tracks. An if statement in the recipes serializer seems to have been the biggest key:

```
# frozen_string_literal: true
#
class RecipeSerializer < ActiveModel::Serializer
  attributes :id, :title, :ingredient_list, :directions, :prep_time, :editable,
             :picture

  def picture
    if object.picture
      object.picture.id
    end
  end

  def editable
    scope == object.user
  end
end
```
This fixed pretty much al the issues along with removing the async true from the ember models. From there I was able to get moving again.

**Comment by MicFin** [comment]
Another way to write that might be 
```rb
class RecipeSerializer < ActiveModel::Serializer
  attributes :id, :title, :ingredient_list, :directions, :prep_time, :editable
  attribute :picture, if: :has_picture?

  def has_picture?
    !object.picture.nil?
  end

  def picture
    object.picture.id
  end
