### ISSUE TITLE
DOMexception Error

### ISSUE THREAD

**Issue by naributler** [ga-wdi-boston/capstone-project#641]
Occasionally, when I refresh my deployed app, I get the following error: 
<img width="1386" alt="screen shot 2017-06-08 at 12 08 50 pm" src="https://user-images.githubusercontent.com/20606223/26939627-e30776ce-4c45-11e7-99c7-d54c619da53e.png">

I'm having a hard time finding the root of this issue, especially since it doesn't seem to appear consistently. I googled the error, and maybe I need to remove a child element somewhere? (https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild) 

Any help would be much appreciated.

**Comment by jordanallain** [comment]
sounds like it is trying to use the removeChild function on a node that doesn't exist or isn't the child of the node it is targeting. do you use removeChild in your code anywhere? you could always just drop a debugger in there and step through to watch when it hits that error on a certain line.

**Comment by naributler** [comment]
I just did a global search on my project and I'm not using removeChild anywhere. Not sure if this could be related at all, but I do use document.getElementById once.

**Comment by naributler** [comment]
Would it be possible to have a 1on1 and take a look at this?

**Comment by BenGitsCode** [comment]
Did you try to step through the debugger yet?

**Comment by narichasavanorkejoyce** [comment]
I'm not really sure how to do that - where should I drop the debugger? This error only happens occasionally when I open or refresh the login page of the deployed app. It's not happening locally.

**Comment by naributler** [comment]
I tried, but I don't think I'm using the debugger correctly - not exactly sure where to place the debugger.

**Comment by BenGitsCode** [comment]
Where have you tried putting it so far?

**Comment by naributler** [comment]
Actually, I think this may be related to the Ember Inspector Chrome Extension. The error was pointing me to this site: chrome-extension://bmdblncegkenkacieihfhpjfppoconhi/content-script.js

This script just talked about Ember Inspector. So I removed the Chrome extension and then stopped getting this error. Really confused, since I'm not using Ember, but the error does seem to have disappeared.

**Comment by Jcornmanhomonoff** [comment]
@narichasavanorkejoyce are you all set on this issue? If so, please close. Thank you! 🙃

**Comment by naributler** [comment]
I'm still trying to understand why this issue seems to have been related to Ember Inspector. Has anyone had experience with this before?

**Comment by BenGitsCode** [comment]
I haven't seen this issue before but were you using a private window? You could confirm it by ensuring ember inspector is disabled incognito and then test it in there.

**Comment by naributler** [comment]
Okay, I'll close the issue and give that a try. I wasn't using a private window, but I'll double check by disabling incognito.
