### ISSUE TITLE
REACT App Deploy - Front End Not Talking with Back End

### ISSUE THREAD

**Issue by danielleletarte** [ga-wdi-boston/capstone-project#642]
I have deployed both the front and back ends of my app to Heroku. I followed the following documentation.

Backend [https://github.com/ga-wdi-boston/express-api-deployment-guide#creating-mlab-addon](url)

Front End [https://git.generalassemb.ly/pages/education-product/module-fe-framework-react/532rwqfzbfasnbfansfbasnbfqpi4u4p1421fafaa/lectures/04-further-information/08-heroku.html](url)

I can load both sites, but the front end doesn't appear to be talking to the backend. I'm sure it's a minor setting somewhere that I am missing, but I've spent about an hour with now luck. Thanks!

**Comment by jordanallain** [comment]
you deployed to github enterprise? if so you likely have the CLIENT_ORIGIN set to github.io which is normal github not github enterprise. maybe try deploying to regular github.

**Comment by danielleletarte** [comment]
I'm trying to deploy the client to Heroku, not GitHub.

**Comment by jordanallain** [comment]
ah, well then you will need to make sure the CLIENT_ORIGIN is set correctly, it won't be the github.io link it will be a heroku link.

**Comment by danielleletarte** [comment]
That is my issue, I'm just not sure where that would be included in the React template. I tried adding a static.json file per the React Study we had with a proxy but I think I'm missing something..

**Comment by jordanallain** [comment]
no i mean on heroku.com

**Comment by scottyscripts** [comment]
did you set up your proxy like so https://github.com/heroku/heroku-buildpack-static/blob/master/README.md#proxy-backends ?

**Comment by danielleletarte** [comment]
I'm actually all set. Worked with @jim-moody to get this up and running. Thanks Jim!
