### ISSUE TITLE
Seeing wine data when signed in as a different user

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/capstone-project#643]
Of course, I have to hit this on Capstone! Never had it before. 

I just signed in with a new user ID and am able to read the existing contents of my wine table for a different user. 

I am comparing my code to what I did on project 2 to see if I can locate the bug. I will also validate a curl script too on the back end to see if thats the issue.

Opening ticket for visibility to get some assistence as this is my last bug on Capstone and churning a bit here.

Thank you

**Comment by danman01** [comment]
Do you know the API call responsible for showing the data? 

If not, can you find the code responsible for showing the data that is visible, and trace that front-end data to the API response that is responsible for displaying the code? If so, then you can verify with a curl request that when you hit that API endpoint, the data is returned, without needing to be authenticated as the user that "owns" it.

Also, what is your stack (front-end / back-end framework)?

**Comment by glasneed** [comment]
Front End - Browser Template.
Back End - Rails

I verified that the issue is back end. My CURL script also brought back the data that belonged to a different user.

The API call in wine-api is just a GET as follows

```
const readWines = function () {
  return $.ajax({
    url: config.apiOrigin + '/wines',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```

**Comment by glasneed** [comment]
I found the bug once I calmed down and followed the debug steps. After CURL failed, I checked the wine controller and noticed that I had omitted current_user in the GET method. Fixed that and all is good again.. 

Thanks Danny!

```
  def index
    @wines = current_user.wines.all

    render json: @wines
  end 
```
