### ISSUE TITLE
Manually handling an omniauth handshake

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/capstone-project#646]
For my capstone, I am attempting to interact with the [coinbase](https://developers.coinbase.com/api/v2) api via their oauth protocol called [coinbase connect](https://developers.coinbase.com/docs/wallet/coinbase-connect/). One slight issue comes from the fact that the [omniauth wrapper for coinbase](https://github.com/coinbase/omniauth-coinbase) does not manually handle the handshake process (the handshake being the return of a usable access token from their url). As things stand, this is not a huge issue, as coinbase provides temporary development tokens which can be used to access the API, but timeout after 30 minutes. I have been able to ping the API and interact with it this way, creating a route for building the functionality I want. This fix, however is decidedly temporary and it is pretty annoying to have to secure a new token every half hour. 

I have been pouring through the documentation on how to implement the handshake, and have come across a good amount of information, but I am not sure how to deal with all of it. The following are my points of confusion (all linked to [this](https://developers.coinbase.com/docs/wallet/coinbase-connect/integrating) set of instructions):

First (and far and away most seriously): How do I redirect users to access the application? I understand that I need to construct an authorization url (and have a good idea of how to construct it) and take data back, but I am not sure where I should deal with this logic handling. My intuition tells me it should be in the routes file, but I am not sure how to make the jump from curl to rails. This same point of confusion is relevant in step 3, where you need to send the code returned from step 1 to actually get the access token. 

Second: Once I have my access token, how would I go about locally caching it to be passed through to the API?

**Comment by danman01** [comment]
Once you have the access token from omniauth-coinbase, you can then make authenticated calls to the coinbase API, sending that access token along with your requests to coinbase.

> One slight issue comes from the fact that the omniauth wrapper for coinbase does not manually handle the handshake process (the handshake being the return of a usable access token from their url)

Are you sure? Omniauth's purpose is to handle that handshake for you. Have you gone through this repo and read about omniauth: https://github.com/omniauth/omniauth

This is a good read (read the answers) from the creator of Omniauth: https://stackoverflow.com/questions/5675029/how-to-use-omniauth-to-make-authenticated-calls-to-services

**Comment by danman01** [comment]
There is this coinbase-ruby wrapper as well which also has OAUTH2 support: https://github.com/coinbase/coinbase-ruby

**Comment by d00medman** [comment]
hmm I actually see I made a conceptual mistake: I was under the assumption that omniauth-coinbase didn't handle the handshake. This is incorrect, it is coinbase which does not. This actually is a bit of a step back, as I was under the impression I had dealt with using omniauth.

**Comment by d00medman** [comment]
alright, so in omniauth coinbase, the instructions are to include the following middleware at config/initializers/omniauth.rb

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :coinbase, ENV["COINBASE_CLIENT_ID"], ENV["COINBASE_CLIENT_SECRET"]
end
```

This will allow me to access the url `/auth/coinbase`

EDIT:
In the omniauth documentation, they want you to create a route as follows:
```ruby
get '/auth/:provider/callback', to: 'sessions#create'
```

and a sessions controller which looks like this:

```ruby
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    self.current_user = @user
    redirect_to '/'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end
```

I suppose I'll try doing this and see if I can get a token back from the back end.

**Comment by danman01** [comment]
Do you have an understanding of how to send a request to coinbase, and then get back the response, and allow omniauth to handle it from there? Read up on configuring omniauth, and if you can't find a tutorial for coinbase, take a look at facebook or twitter, as there's loads of tutorials about using omniauth with those APIs. Any other API that implements oauth2 and has an omniauth wrapper will act pretty much the same.

**Comment by d00medman** [comment]
So I'm following an online tutorial on how to use omniauth. Pretty much all of them have a sessions controller which goes to the route. I have created a fairly barebones sessions controller:

```ruby
# Implementation found in omniauth github readme
class SessionsController < ApplicationController
  def create
    auth_hash = request.env['omniauth.auth']

    render :text => auth_hash.inspect
  end
end
```

And written a curl request

```shell
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/auth/:provider/callback"
curl "${API}${URL_PATH}" \
  --include \
  --request GET \

echo
```
I think If I can get this method to fire properly, I'll be in good shape. 

When I try and run my curl script, I get a 500 error saying that I have SessionsController as an uninitialized constant (though I think this can be attributed to bad routing. When I attempt to got to `localhost:4741/auth/coinbase` I get an error from coinbase telling me I have an improper callback URI.

**Comment by d00medman** [comment]
Alright, so I realized that my conceptual approach to my project does not actually match my authorization strategy. As it turns out, I want to use an API key, something far simpler to implement. This makes an oauth based approach more of a stretch goal than anything.
