### ISSUE TITLE
Deployed Version Different from local

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/capstone-project#648]
I am able to create a new poem and view new poems locally, but when I go to the deployed site the act of retrieving all the poems throws a 500 error.   Here is the code where the error is hitting:

```
export default Ember.Route.extend({
  model(){
    console.log('get all poems', this.get('store').findAll('poem'))
    return this.get('store').findAll('poem');
},
```
 The heroku log does not copy well but it says 
```
2017-06-10T18:02:54.190903+00:00 app[web.1]: [65308bcf-2278-439b-8454-093e9a2fa2dd] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "poems" does not exist

```
It seems like I am somehow calling it in a way that doesn't work deployed.   
I changes it to findAll('Poem') but that didn't work either.  It is making the call to the correct address, my heroku/poems, but then returning a 500 error.   I had been thinking the problem could be that it is returning an empty object, but that shouldn't get a 500 error.    When I run it locally it works correctly with a new users and says:
```
XHR finished loading: GET "http://localhost:4741/poems".
```

**Comment by MicFin** [comment]
Have you run all your migrations in the heroku environment?
`PG::UndefinedTable: ERROR:  relation "poems" does not exist` 

https://stackoverflow.com/questions/5450930/heroku-postgres-error-pgerror-error-relation-organizations-does-not-exist

**Comment by Maggicorp** [comment]
That was totally it.  Thanks Mike! 
In summary I forgot to run my heroku migration, and after I ran it everything behaved as expected
Specific I ran this - heroku run rake db:migrate
