### ISSUE TITLE
Ember breaking when I try to implement auth

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/capstone-project#649]
So I'm trying to implement ember auth. Rather than build it all up, I copied the code from Toni's lesson on friday. When I did this, booting my server and going to localhost 7165 brought me to a blank page. To workaround this, I actually tried ripping out my front end and reconfiguring the ember auth lesson to be my new front end (replacing all instances of ga-wdi-boston.ember-auth with my app's name), but I am getting the exact same result. Any ideas why this may be happening?

[front end repo](https://github.com/d00medman/medici). I am currently actually working in the ember auth lesson, with the intent of moving my code back to my main repo when this issue gets resolved.

**Comment by MicFin** [comment]
What happens when you go to /sign-up?

**Comment by d00medman** [comment]
All the routes lead to blank pages

**Comment by MicFin** [comment]
Any messages in the console? Or the client server log?

**Comment by d00medman** [comment]
Nothing is appearing in either

**Comment by d00medman** [comment]
I've been able to narrow down the source of the error. I checked out to a different branch and replaced all instances of `ga-wdi-boston.ember-auth` with `medici`. This exactly replicated the error I was dealing with, meaning that one of these `ga-wdi-boston.ember-auth` statements is vital to the template's functionality. Specifically, the two locations it causes breakdowns is when you make the changes in `index.html`, `config/environment.js` and `app/adapters/application.js`.

**Comment by MicFin** [comment]
Nice job!

**Comment by jordanallain** [comment]
is it working now @d00medman ?

**Comment by d00medman** [comment]
Working is relative. I haven't been able to touch the namespaces if I want a working app. In practice, there are major functionality gaps which need to be addressed, pushing this problem waaaaay down my list of priorities. In practice, means kicking this problem down the road until such a point in time where my app is reasonably functional.

**Comment by d00medman** [comment]
I am actually still having this issue, which is becoming relevant again as I would like to deploy my application with namespacing which matches my app.

**Comment by d00medman** [comment]
Was able to solve the issue by shutting down my terminal/atom and reopening them, causing changes in my environment to stick.
