### ISSUE TITLE
issue with pushing to Heroku

### ISSUE THREAD

**Issue by francescadal** [ga-wdi-boston/capstone-project#65]
Heroic is not showing the page.My index files are being displayed by the server

**Comment by jrhorn424** [comment]
Did not diagnose.
1. Deleted deployed app
2. Deleted remote
3. `heroku create`
4. `git push heroku master`
5. Add 12 factor gem and ruby version
6. `git push heroku master`
7. `heroku run rake db:migrate db:seed`
8. `heroku open` and observe working app
