### ISSUE TITLE
Ember can't access 3rd party jquery and css files

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/capstone-project#650]
I'm trying to access a 3rd party jquery plugin called jquery-wheelcolorpicker and its css files. I followed all steps according to this site: https://github.com/fujaru/jquery-wheelcolorpicker/wiki/Getting-Started. I downloaded the 'Wheel Color Picker Plugin', added the folder in my ember app under /app folder, and added the link tag and the script tag in index.html that should be pointing to the right files.

I added wheelcolorpicker script tag and the link tag  in app/index.html to test it out: 
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EmberTemplate</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{content-for "head"}}
    <link rel="stylesheet" href="{{rootURL}}assets/vendor.css">
    <link rel="stylesheet" href="{{rootURL}}assets/ember-capstone.css">
    <link type="text/css" rel="stylesheet" href="colorpicker/css/wheelcolorpicker.css" />

    {{content-for "head-footer"}}
  </head>
  <body class="container-fluid">
    {{content-for "body"}}

    <script src="{{rootURL}}assets/vendor.js"></script>
    <script src="{{rootURL}}assets/ember-capstone.js"></script>
    <script type="text/javascript" src="colorpicker/jquery.wheelcolorpicker.js"></script>

    {{content-for "body-footer"}}
  </body>
</html>
```

I added an input tag (as written in documentation) in application.hbs.
```
{{my-application signOut="signOut"}}

{{!-- calls all the other components that we see on the page --}}

<input type="text" data-wheelcolorpicker />
```

file structure:
<img width="323" alt="screen shot 2017-06-10 at 6 57 08 pm" src="https://user-images.githubusercontent.com/16979795/27006883-b9278b9e-4e0e-11e7-9519-80619e8add11.png">

console errors:
<img width="855" alt="screen shot 2017-06-10 at 6 39 09 pm" src="https://user-images.githubusercontent.com/16979795/27006799-7443cc42-4e0c-11e7-891f-0885fc1019a9.png">

According to the console errors, it says that it's making a GET request to ```localhost:7165/colorpicker/jquery-2.0.3.min.js``` and ```localhost:7165/colorpicker/jquery.wheelcolorpicker.js``` but can't find the files. It's weird to me that it's not trying to go to ```localhost:7165/colorpicker/jquery-2.0.3.min.js``` and ```localhost:7165/app/colorpicker/jquery.wheelcolorpicker.js```. 

I did all above steps on my portfolio website just to test it out, and it works. When I click inside the input, a color wheel gets displayed as it's supposed to. However, in my ember app, when I click on inside the input, nothing happens. 

I read in ember docs that "Third-party JavaScript not available as an addon or Bower package should be placed in the vendor/ folder in your project." So I looked for a ```vendor``` folder but it doesn't exist in our ember app template.
https://guides.emberjs.com/v2.13.0/addons-and-dependencies/managing-dependencies/

I really need to make this color wheel work so that I can move on with my project.

FYI - demo of plugin:
http://files.jar2.net/jquery/wheelcolorpicker/example-v3/example.html

Thank you in advance.

**Comment by MicFin** [comment]
Ember Template has a [vendor](https://git.generalassemb.ly/ga-wdi-boston/ember-template/tree/master/vendor) folder.
```
app
config	
grunt	
public	
tests	
vendor	
```

**Comment by nriser** [comment]
Thanks @MicFin. I decided to not go this route.
