### ISSUE TITLE
Alex learns how to use ember components

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/capstone-project#651]
Pretty much exactly what it sounds like; How can I call upon the current user of my application (my auth implementation is the one we were given)? I am trying to return the account of the current user, but am not sure how to call upon the current user to return this data:

```js
import Ember from 'ember';
import { storageFor } from 'ember-local-storage';

export default Ember.Route.extend({
  credentials: storageFor('auth'),

  model () {
    // console.log(credentials.email);
    // user_id = this.get('store')
    return this.get('store').findRecord('account', '?' );
  },
});
```

**Comment by laurpaik-zz** [comment]
is [this](https://guides.emberjs.com/v2.13.0/routing/specifying-a-routes-model/#toc_dynamic-models) what you're talking about? 
What does your account model look like?

**Comment by d00medman** [comment]
Account ember model:

```js
import DS from 'ember-data';

export default DS.Model.extend({
  user_name: DS.attr('string'),
  content_type: DS.attr('string'),
  creator: DS.attr('boolean'),
  // Not sure if I'll need these back in. As it stands, I can create w/o them, and need
  // to build too much to really test
  // coinbase_email: DS.attr('string'),
  // user_id: DS.belongsTo('user')
});
```
On the back end, my account resource belongs to a user, meaning I can use the ID of the current user to pull the information of the account associated with them. In the rails template, there is the current_user syntactic structure which lets you call the information of the current user fairly easily. In order to hit my goals on the front end, I need to find some way to mimic this.

**Comment by laurpaik-zz** [comment]
I'm going to guess you'll at least need `user: DS.belongsTo('user')` if that's how you have the relationship on the backend, and you'll need to define that relationship on both models see [here](http://www.ember-doc.com/classes/DS.html#method_belongsTo). It doesn't look like Ember is going to recognize a connection without that.

Did you look at the route structure in the link I sent you in the above comment?

**Comment by d00medman** [comment]
Yeah. I'm actually very confused on how routing works in relation to pinging my back end. I was under the impression that the routes files are for touching the back end, while the router is for determining the loading of templates/components. I'm starting to think I'm wrong about this, and that the router.js file actually determines what path the template and component file take from the app to the back end. Needless to say, I'm pretty confused as to how ember works.

**Comment by laurpaik-zz** [comment]
You're not alone in that, for sure. Ember's an adventure because it's super opinionated and expects you to use _exactly_ what it wants. 

I think the router just maps out what goes to which URL. The routes files are for getting the data from the back-end, yes, and I don't remember all the wiring under the hood for this but when you generate a route, Ember understands when the templates match a route or a component's template matches a component.

In the meantime, take things one step at a time. It's really easy to get lost in Ember, and it's hard to figure out where that happens if you go too quickly. 
Figure out what ingredients you _need_ to have, then make sure your syntax is correct. 
Read your errors (were there errors when you tried this? What were they?)
In this case, make sure all your relationships are defined on both ends.
Make sure whatever button you're using to look at the account actually does something, so you know that the error is from how something's set up and not because the button doesn't work.
Check your bindings on your template. Find out what's _not_ causing errors and work from there.

**Comment by d00medman** [comment]
This is actually a subset of a broader issue where I'm unable to take the data returned from my back end and manifest it in a template. I know that I am able to ping my datastore (when I hardcode a value), As I am returning an ember object, but all my efforts to manifest it in a template fail.

templates/accounts.hbs

```js
<h3>accounts.hbs</h3>
{{accounts model=account}}
<p>{{account.id}}</p>
```
The error is telling me that 'accounts is not a helper', but I cannot seem to find any good information on what this means or any solid examples on how to manifest a single item returned from a server (almost every example uses `{{#each}}`

I'd like to move this into a nested component, but I cannot even get it to fit on a top level template. This is probably the opinionated nature of ember getting in my way, but I don't even know how to find out what those opinions are.

**Comment by laurpaik-zz** [comment]
Ah. If you want this view to change with every user, would it help to have a component for an individual account?
It looks like Ember thinks you want to display a list of accounts, in which case you would use `{{#each model as |account|}}` or something.
Do you have any kind of route for an individual account? re: your initial issue code, what file is that in?

**Comment by d00medman** [comment]
Yeah, I actually have a component called my-account, meant to be used to display the current user's account. I've been trying to work with it, but with little luck.

My current route in router.js (this has actually caused my app to break at this url, but I am fairly certain it is at least conceptually a step in the right direction):

```js
this.route('accounts', function(){
    this.route('my-account', {path:'/:account_id'});
  });
```

I also have a component file, but this is basically empty. Broadly speaking, Sending data down has proven far more difficult for me than sending actions up.

**Comment by laurpaik-zz** [comment]
This might be annoying, but try
```diff
this.route('accounts', function(){
+    this.route('my-account', { path: '/:account_id' });
-    this.route('my-account', {path:'/:account_id'});
});
```
Then see if anything shows up from your my-account template.

**Comment by benjimelito** [comment]
Any updates?

**Comment by d00medman** [comment]
So I took a step back and was able to get it kinda-sorta working. As it stands, here is my code

router.js
```js
this.route('accounts', function(){
    this.route('my-account');
  });
```

accounts.hbs

```hbs
<h4>Account.hbs</h4>

{{accounts/my-account account=model}}
```

components/my-account.hbs

```hbs
<h4>my-account.hbs</h4>

<p>{{account.user_name}}</p>

{{yield}}
```

routes/accounts.js

```js
import Ember from 'ember';

export default Ember.Route.extend({

  model (params) {
    return this.get('store').findRecord('account', 10);
  },

});
```

Together, this code path manifests the correct user_name at both the routes `/accounts` and `/accounts/my-account`. While this is definitely a step in the right direction, it's still far from my goal. I only want the my-account component to be shown at the `accounts/my-account route`, and am frankly entirely unsure of how to move its manifestation downwards. I also have no idea how to get an account without hardcoding the ID I want; largely a result of uncertainty about what is being passed as params to the route file. 

All of this points to some serious knowledge gaps in my understanding of ember. I think I really need a one-on-one in order to fill these gaps.

**Comment by d00medman** [comment]
Alright, so after a one-on-one, I am closer to solving my problem. In the templates, I decided to go with a less attractive but more manageable functionality in the form of simply have a link-to statement from my `accounts` to `my-account`. I also figured out how to access the ID of the current user;

routes/accounts.js:

```js
import Ember from 'ember';

export default Ember.Route.extend({

  auth: Ember.inject.service(),

  model (params) {
    let current_user = this.get('auth.credentials.id');
    console.log('current user ', current_user);
    console.log(params);
    return this.get('store').findRecord('account', 14);
  },

});
```

Were I directly pinging my back end, this would be the solution, as I would simply search my account table for a matching user_id. The problem is that I am interacting with the local ember store as defined by by my model, and efforts to create the relation between account and user proved problematic. Furthermore, a lot of this data handling is done on the back end, and I am distressingly unsure of how the model interacts with my rails controllers. 

UPDATE: Linking is actually a bit of a pain. I am not sure How to pass data down to the my-account template and how to make the top level accounts template to be taken off the screen. How would I go about doing these two things?

**Comment by jordanallain** [comment]
what did you try?

**Comment by d00medman** [comment]
So I blanked out my account route (a perennial source of problems) just to try and get the link logic working.

templates/accounts.hbs 

```js
<h4>Account.hbs</h4>

{{#link-to 'accounts.my-account'}}my account{{/link-to}}

{{outlet}}

{{!-- {{accounts/my-account account=model}} --}}
```

Note that the commented out statement at the bottom does allow me to display the `my-account` component w/ the appropriate data, but I do not want it appearing at this level, I want to click the link to see it.

templates/components/accounts/my-account.js

```js
<h4>my-account.hbs</h4>

{{!-- <p>{{account.user_name}}</p> --}}

{{#link-to 'accounts'}}Back{{/link-to}}

{{yield}}
```
As things stand, I can't even get to a dummy route. What happens is that I click the link and the url updates, but no change is made to the view.

**Comment by d00medman** [comment]
I think I'm structuring my components wrong, if someone could take a look at it and point out the flaws in my code, it could make a difference

**Comment by laurpaik-zz** [comment]
[here](https://github.com/laurpaik/ember-routing/tree/training/#index-templates) are a couple notes on `index` files.

**Comment by d00medman** [comment]
Alright, so the issue was largely a question wacky file structure. I failed to understand the relationship between routes and the displaying of templates. I realized that routes and components are made of two interlocked files which should be created using the generator. This bit of insight has shed a huge amount of light on how to go about generating views and  components moving forward.
