### ISSUE TITLE
"Compile Error: spectrum-color-picker is not a helper"

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/capstone-project#652]
I installed an ember addon called ```ember-spectrum-color-picker``` and have spent multiple hours trying to figure out how to use it. 

https://www.npmjs.com/package/ember-spectrum-color-picker

How I installed it in terminal:
```
$ ember install ember-spectrum-color-picker
WARNING: Ember CLI is using the global NPM, but your NPM version has not yet been verified to work with the current Ember CLI release.
NPM: Installed ember-spectrum-color-picker
installing ember-spectrum-color-picker
  install bower package spectrum
  cached https://github.com/bgrins/spectrum.git#1.8.0
Bower: Installed spectrum=spectrum
Installed addon package.
```
Doing so created a `package-lock.json` file and added ```"ember-spectrum-color-picker": "^0.5.2"``` in ```package.json``` file. 

It also added a dependency in my bower.json file.
```
{
  "name": "ember-capstone",
  "dependencies": {
    "ember": "~2.10.1",
    "ember-cli-shims": "0.1.3",
    "ember-qunit-notifications": "0.1.0",
    "bootstrap-sass": "^3.3.7",
    "blob-polyfill": "^1.0.20150320",
    "spectrum": "^1.8.0"
  }
}
```

No other folders/files were created.

I then added ```{{spectrum-color-picker color=teamColor}}``` in templates/components/my-application.hbs
```
<nav class="navbar navbar-default">
  <div class="container-fluid">
    {{navbar-header}}

    <div class="collapse navbar-collapse" id="navigation">
      <ul class="nav navbar-nav">
        {{#if isAuthenticated}}
        {{!-- if user is authenticated, then display users --}}
        <li>{{#link-to "users"}}Users{{/link-to}}</li>
        {{/if}}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {{#if isAuthenticated}}
        <li>{{#link-to "change-password"}}Change Password{{/link-to}}</li>
        <li><a href="#" {{action "signOut"}}>Sign Out</a></li>
        {{else}}
        <li>{{#link-to "sign-up"}}Sign Up{{/link-to}}</li>
        <li>{{#link-to "sign-in"}}Sign In{{/link-to}}</li>
        {{/if}}
      </ul>
    </div>
  </div>
</nav>

<h1>Welcome to Ember!</h1>

{{spectrum-color-picker color=teamColor}}

{{#each flashMessages.queue as |flash|}}
  {{flash-message flash=flash}}
{{/each}}

<div class="col-md-8 col-md-offset-2">
  {{outlet}}
</div>
```

<img width="479" alt="screen shot 2017-06-11 at 11 22 53 am" src="https://user-images.githubusercontent.com/16979795/27012147-757bcd94-4e98-11e7-8d5c-3f1ae1620220.png">

I've looked up the error message and honestly, it led me nowhere. Some stuff I found but not helpful:
https://github.com/jamesarosen/ember-i18n/issues/448
https://discuss.emberjs.com/t/helper-cannot-be-found/12366

**Comment by MicFin** [comment]
Do you need to add the component files?

- https://github.com/RSSchermer/ember-spectrum-color-picker/blob/master/addon/components/spectrum-color-picker.js
- https://github.com/RSSchermer/ember-spectrum-color-picker/blob/master/app/components/spectrum-color-picker.js

**Comment by nriser** [comment]
Thanks @MicFin. Yes it seems like ```ember install ember-spectrum-color-picker``` is supposed to generate new files for you (according to people online) but I guess I'll have to manually add those files in.

I actually decided to dumb down my project even more and focus on building a minimum viable product first. I will try using the color-picker later if I have time.
