### ISSUE TITLE
How to loop an adapter into your route

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/capstone-project#653]
I have a custom route as the critical piece of functionality in my application, but I have no idea how I go about directing ember to use the adapter file I have built. This is a problem because I know for a fact I have implemented the adapter wrong, but cannot even begin to debug until I can use it to ping my server. 

```js
import ApplicationAdapter from './application';

export default ApplicationAdapter.extend({
  // Not super confident about this adapter, not am I super confident about how I
  // am passing data through it.
  donate(store, type, record) {
    let api = this.get('host');
    let serialized = this.serialize(record, {includeId: true});
    let accountId = serialized.account_id;
    let url = `${api}/accounts/${accountId}/donate`;
    let data = {account: serialized};
    return this.ajax(url, 'PATCH', {data});
  }
});
```

app/component/donate-form.js
```js
import Ember from 'ember';

export default Ember.Component.extend({
  tagName: 'form',
  classNames: ['form-horizontal'],

  params: {},

  actions:{
    submit () {
      this.sendAction('submit', this.get('params'));
    },

    reset () {
      this.set('params', {});
    },
  }
});
```

app/routes/donate.js

```js
import Ember from 'ember';

export default Ember.Route.extend({

  actions: {
    donate(params){
      console.log('hits');
      console.log(params);
      let patron = this.get('store').findRecord('account', 10);
      // here is where I need to link to my adapter
      patron.donate(params);
    }
  }
});
```

My templates are working As I want them to (sending data up the chain). What do I need to do to use my adapter file?

**Comment by MicFin** [comment]
I believe since you are not using your Adapter to override a method already defined on the Ember object then you have to use `adapterFor`
https://stackoverflow.com/questions/31907854/can-i-create-custom-ember-data-methods

Another useful read
https://stackoverflow.com/questions/17938294/how-do-you-create-a-custom-adapter-for-ember-js

**Comment by d00medman** [comment]
This is another subject I'm in pretty serious need of a 1:1 in. I've been reading docs about this all weekend and I am still no closer to really understanding how exactly I use an adapter.

**Comment by d00medman** [comment]
A broad view of my current problem, what I know and what I don't:

The critical functionality for my application is the donate function. I have this working on the back end via a patch request (though it does not actually do any patching, the patch request is sort of legacy from an earlier implementation). What I need to do is send data to the custom routes. I know that I need to use an adapter for this, and my guess is that I need to overwrite the RESTAdapter's `urlForRequest` method in order to send my data to my controller. This is about where my knowledge ends. 

My best guess as to what I should be doing: 

My adapter should be creating a custom URL which matches my rails URL to ping the donate method. It will do this by overwriting `urlForRequest` 

In my donate route, I will send data to the new URL.

What I need to know:

-How exactly do I go about overwriting the `urlForRequest` method?

-How do I call the overwritten `urlForRequest` method in my donate route file?

-Once I have my url, how do I package it with the required data and send it to the server and where do I do this packaging? 

-Should I be concerned with serializers? They pretty much always appear in documentation associated w/adapters, but I am not actually interacting w/my database, so there doesn't really appear to be any need to use them. 

UPDATE: dummied in some code for a router. Have two separate implementations, one which overwrites the `urlForRequest` and one which uses a custom donate method (modeled on the adapter we built in class during the ember resources lesson). I still don't know how to leverage them, but I do have a vague idea of what they will do once I learn how to do so.

```js
import ApplicationAdapter from './application';

export default ApplicationAdapter.extend({
  urlForRequest: function (account_id){
    const api = this.get('host');
    const url = `${api}/accounts/${account_id}/donate`;
    return url;
  }

  // donate (store, type, record) {
  //   const api = this.get('host');
  //   const serialized = this.serialize(record, { includeId: true });
  //   const accountId = serialized.account_id;
  //   const url = `${api}/lists/${accountId}/items`;
  //   const data = { item: serialized };
  // 
  //   return this.ajax(url, 'POST', { data });
  // }
});
```

**Comment by d00medman** [comment]
Was able to finally make the call to the adapter. One of my biggest pitfalls was the fact that my adapter file was named `donations.js`, when it should have been named `account.js` so it could correspond with the account model which I will be calling on. In my donate route, the following code allows me to touch the custom method laid out in my adapter.

```js
const adapter = this.store.adapterFor('account');
adapter.donate();
```
Moving on to building and testing the custom route, something certain to prove troublesome in its own right.
