### ISSUE TITLE
Ember Local Storage Problem

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/capstone-project#654]
My poems are storing locally even if they don't have all the requirement to be stored on the back end.  For example, if you hit submit without filling in the forms you get an error message, but you also locally create an empty poem.   When you sign out and sign back in again the poem is gone, because it is not stored in the database, but it exists locally.  Any idea why that might be happening?

**Comment by Maggicorp** [comment]
I did this, but it isn't working for edit, only create.  Is there a better way to do a validations? I feel like there should be 
```
  if(data.firstline === null || data.secondline === null || data.thirdline === null) {
        this.get('flashMessages')
        .danger('error, please include a valid input for all three lines')
        return
      }
```

**Comment by Maggicorp** [comment]
The problem is that it is updating locally before I hit submit, how can I turn the binding off? Or how else could I do this.  I spent a lot of time (hours) looking into how to just reload the model without using store, but I was not able to get that to work.  Any suggestions on getting the model to only load from whats in the api?  When I refresh the page it always shows the correct data, so how do I do the equivalent of that?

**Comment by jordanallain** [comment]
is this a problem with PATCHing? trying to understand what the issue is. is it that you update the data locally but it doesn't persist to the back end?

**Comment by Maggicorp** [comment]
The problem is that due to databinding changes happen from the edit button before you hit submit.  When I refresh I see the right thing but before I refresh I don't

**Comment by Maggicorp** [comment]
```js
  actions: {
    onInit: function(){
      console.log('on init');
    }.on("init"),
    edit() {
      console.log('at update poem in each poem edit component, poem is', this.get('poem'))
      let firstline = this.get('poem').get('firstline')
      let secondline = this.get('poem').get('secondline')
      let thirdline = this.get('poem').get('thirdline')
      console.log('they are', firstline, secondline, thirdline)
      if (firstline === '' || secondline === '' || thirdline === '') {
        console.log('at error')
        this.get('flashMessages')
          .danger('Error, please include a valid input for all three lines')
        return
      }
      this.sendAction('editPoem', this.get('poem'))
    }
}
});
```


this is the handlebars
```hbs
<div class="edit">
<h3> Edit this Haiku </h3>
<form class='form-group'>
  <div class='input-group'>
  {{input placeholder='Title (optional)' class='form-control' value=poem.title}}
  {{input required=true placeholder='first line' class='form-control' value=poem.firstline}}
  {{input required=true placeholder='second line' class='form-control' value=poem.secondline}}
  {{input required=true placeholder='third line' class='form-control' value=poem.thirdline}}
<div class='input-group-btn'>
<button type='submit' class="btn btn-primary" {{action 'edit'}}>
  Submit
</button>
</div>
</div>
</form>

{{#link-to 'poem'}}<button>Back</button>{{/link-to}}
</div>
```

**Comment by Maggicorp** [comment]
And here is the model for poem.  Part of the problem is that the model is loading this local data before it has been saved
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model(){
    console.log('get all poems', this.get('store').findAll('Poem'));
    const poems = this.store.findAll('Poem', {backgroundReload: true});
    return poems;
},
```
backgroundReload true seems to be having to effect

**Comment by jordanallain** [comment]
so you have the data bound to the text field that you are updating, but it doesn't actually persist unless you hit the submit button?

**Comment by Maggicorp** [comment]
it does show those changes, that is the problem.  
You can see it in action -- https://maggicorp.github.io/ember-capstone-maggie/#/

**Comment by Maggicorp** [comment]
It is making the changes locally before I hit submit, which means that they aren't getting verified, and it is temporarily showing changes that have no been saved to the database.  Like a poem with only two lines.

**Comment by jordanallain** [comment]
right but it doesn't actually PATCH the data unless you submit it right? if so is that just annoying to you that it shows up before submitting it? doesn't seem like a bug.

**Comment by laurpaik-zz** [comment]
What does your Ember console say in 'Data'?

**Comment by Maggicorp** [comment]
Hmmm, I'm pretty sure showing inaccurate data is a bug.

**Comment by Maggicorp** [comment]
Basically I just want it not to bind until I hit submit

**Comment by jordanallain** [comment]
this SO question looks kind of promising.

https://stackoverflow.com/questions/16466411/how-to-use-one-way-binding-on-emberjs

**Comment by laurpaik** [comment]
Would it help if you have a `cancel` action instead of just have `back`?

**Comment by Maggicorp** [comment]
I'm trying to do that but adding this view tag is breaking my handlebars - {{view Ember.TextField valueBinding="nameOnController"}}

Lauren said she just added a cancel button which reverts these changes, maybe I'll just do that?

**Comment by Maggicorp** [comment]
same goes for using {{unbound}}

**Comment by jordanallain** [comment]
a cancel button that does what exactly?

**Comment by Maggicorp** [comment]
A cancel button which rolls back the changes like this --
```js
  cancel () {
      history.back();
    }
```
then
```js
  cancel () {
    console.log('at cancel in poem-edit')
    history.back();
  }
```
Is that okay? It reverts in, the only way that you see the bad data is if you click away not using the submit or cancel button

**Comment by Maggicorp** [comment]
It's not actually a cancel button, it says back to poems, it just reverts back to saved changes.  Now the back button works properly, which was part of the problem before.

**Comment by MicFin** [comment]
Looks like you may want to do some Ember model validation manually
http://emberwatch.com/recipes/user_interface_and_interaction/basic_form_validations.html

Or with an NPM package such as the one used in this video tutorial
https://www.emberscreencasts.com/tags/editing-and-validating-forms-with-ember-changeset

Another NPM package to consider
https://github.com/esbanarango/ember-model-validator

**Comment by laurpaik-zz** [comment]
Heh, turns out I have the same issue 😬 
@gaand recommended checking this out:
https://guides.emberjs.com/v2.6.0/routing/preventing-and-retrying-transitions/
Basically you can set it up so it asks if you're okay with leaving the page, and if you hit 'okay' it'll do what `cancel` does.

**Comment by Maggicorp** [comment]
I tried to use this package https://github.com/esbanarango/ember-model-validator but even just importing it causes my poem page not to load.  I don't really want to have a pop when someone tried to leave the page.  I also looked into getting the nav bar to hide on different the edit-poem route, but that also is not ideal

**Comment by Maggicorp** [comment]
I have validation, the form send the right errors, it just makes the changes locally anyway.  But there is ample feedback to tell the user to fill in the fields

**Comment by Maggicorp** [comment]
Could I get a one on one to have someone look at this with me please?

**Comment by Maggicorp** [comment]
Used pastPoem to bind data to and didn't bind until the end - cancel rollback is now unnecssary, but here is all the code anyway.  Sorry for all the console logs
```js
export default Ember.Component.extend({
  pastPoem: {
    title: null,
    firstline: 'two',
    secondline: 'third',
    thirdline: 'four'
  },
  onInit: function(){
    console.log('on init in each poem');
    console.log(this.get('poem'))
    let firstline = this.get('poem').get('firstline')
    let secondline = this.get('poem').get('secondline')
    let thirdline = this.get('poem').get('thirdline')
    if (this.get('poem').get('title')) {
      let title = this.get('poem').get('title')
      this.set('pastPoem.title', title)
    } else {
      this.set('pastPoem.title', null)
    }
    console.log('they are', firstline, secondline, thirdline)
    this.set('pastPoem.firstline', firstline)
    this.set('pastPoem.secondline', secondline)
    this.set('pastPoem.thirdline', thirdline)
  }.on("init"),
  actions: {
    edit() {
      console.log('at update poem in each poem edit component, poem is', this.get('pastPoem'))
      let pastPoem = this.get('pastPoem')
      let firstline = pastPoem.firstline
      let secondline = pastPoem.secondline
      let thirdline = pastPoem.thirdline
      let title = pastPoem.title
      console.log('they are', firstline, secondline, thirdline, title)
      if (firstline === '' || secondline === '' || thirdline === '') {
        console.log('at error')
        this.get('flashMessages')
          .danger('Error, please include a valid input for all three lines')
        return
      }
      let poem = this.get('poem')
      this.set('poem.firstline', firstline)
      this.set('poem.secondline', secondline)
      this.set('poem.thirdline', thirdline)
      this.set('poem.title', title)
      this.sendAction('editPoem', this.get('poem'))
    },
    cancel(){
      console.log('at cancel');
      this.get('poem').rollbackAttributes();
      this.sendAction('cancel');
    }
}
});
```
