### ISSUE TITLE
DEPRECATION: The `initialize` method for Application...

### ISSUE THREAD

**Issue by rowlandhill** [ga-wdi-boston/capstone-project#658]
Hi!  I am getting this error in my Chrome console:

```ember.debug.js:5563 DEPRECATION: The `initialize` method for Application initializer 'inject-flash-messages' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.```

I went to the website they directed me to, but it did not clarify the error.  The flash messages are working, so the error is not breaking any code, but it sounds like a warning that the code I'm using will be obsolete soon.  

Here is my initialize method:

```js
let App;

Ember.MODEL_FACTORY_INJECTIONS = true;

App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver
});

loadInitializers(App, config.modulePrefix);

export default App;
```

When I reduce it to just accept `App` as an argument, the error message goes away, but the flash messages no longer work.  I'm kind of lost.  Any nudge in the right direction would be great!

Thanks,
Rowland

**Comment by MicFin** [comment]
You may ignore that message, it is in regards to Ember deprecating methods in future versions but it is safe to use currently.

**Comment by rowlandhill** [comment]
Thanks, Mike!  Closing this out.
