### ISSUE TITLE
trying to have the equivalent .env file for the front end

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/capstone-project#660]
I have this mashable key that I am using on the front end to make a call to a third party api.  Any good ways to do the equivalent of making it a .env file/ heroku config variable on the front end?

**Comment by cpearce31** [comment]
see here: https://stackoverflow.com/questions/11470389/how-to-protect-an-api-key-when-using-javascript. It may not be possible to really protect it, short of having your backend do the the querying for you. Even then, someone could just keep querying your server, which would forward it to Mashable, until you reached the limit.

**Comment by Maggicorp** [comment]
Hmm, thats a good point.  Basically all you can do with it is ping the api a bunch of times which you could do anyway.  I guess I'll just keep an eye on it, see if I can set up a notification if it reaches more than 2,500 pings per day.  I'm not sure why anyone would want to do that though.
