### ISSUE TITLE
Using dynamic routes to pass parameters to my route files 

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/capstone-project#662]
The sequel to [this](https://github.com/ga-wdi-boston/capstone-project/issues/657) issue.

So by adding a serializer to my backend, I was able to solve the problem of binding users and accounts to each other. Unfortunately, this problem was simply standing in the way of a larger problem; being able to pull specific accounts from the data store by their account ID. In my current understanding, I would leverage the fact that each account has a user id associated with it, and I would use this user ID to query the database and find the appropriate record.

routes/accounts/my-account.js (the route file which has a model hook meant to display the account of the current user):

```js
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    console.log(params);
    // let current_user = this.get('auth.credentials.id');
    // ?????? 
    return this.get('store').findRecord('account', 27);
  },
});
```

For reference, here is how I was able to find the user id in the account:

```hbs
<p>User ID: {{account.user.id}}</p>
```

Broadly, I see it as entirely possible to use my current approach to get the account of the current user. This being said, I do not believe this is a good approach. I think a far more elegant approach would be to use dynamic routing and pass the target ID to my model hook as params. I am unclear, however, on how to go about doing this. 

the current state of my router:

```js
  // this.route('accounts');
  this.route('accounts', function(){
    this.route('my-account');
  });
  // this.route('accounts', function(){
  //   this.route('/:account_id', {path:'/my-account'});
  //   this.route('my-account', {path:'/:account_id'});
  // });
  this.route('donate');
```

I'd like to note that I am facing fundamentally the same problem in two different locations: in my donate method and in the model hook of my account. Resolving it in one would likely resolve it in both, and would be hugely impactful. 

Am I correct in my determination I should abandon my initial approach? If so, how would I go about properly manifesting dynamic routes to pass the ID's I want into my routes?

**Comment by MicFin** [comment]
You can pass ID's to a route.

```js
this.route('accounts', function() {
    this.route('my-account', { path: '/my-account/:id' });
});
```
The route will end up looking like `http://localhost:7165/accounts/my-account/e34b3ce3`.

Then in your route you can do
```js
import Ember from 'ember';
export default Ember.Route.extend({
  model(params) {
      return this.get('store').findRecord('account', params.id);
    });
  }
});
```
https://stackoverflow.com/questions/41241559/how-can-i-get-the-id-from-the-url-in-an-ember-route

**Comment by d00medman** [comment]
So I've implemented it like this, placing the route code in the model hook for my account, and it currently works at that route. However, there are two caveats; 

First, this new route has basically broken my top level accounts index. I imagine this is because the following link in my accounts index is broken.

```hbs
{{#link-to 'accounts.my-account'}}My Account|{{/link-to}}
```

This actually ties fairly neatly into my second problem, which is basically the same overarching problem that has been plaguing me; I still have no idea how to specify that I am trying to retrieve the account information of the current user, it has only pushed the location of where I need to do this data passing up the chain.

**Comment by tvcrawley** [comment]
`1st caveat:`
If the router.js has been changed like Mike suggested above, then the link-to would have to be modified to accept the specific account you want displayed.
https://guides.emberjs.com/v2.13.0/templates/links/

`2nd caveat:`
The user id could be included in the url. So above you are getting the account_id from the params, user_id could be included in the route as well.

**Comment by d00medman** [comment]
So I'm pretty sure the problem of finding an account by using a user id can be solved with the [queryRecord](https://emberjs.com/api/data/classes/DS.Store.html#method_queryRecord) method native to ember data. My current query looks like this:

```js
this.store.queryRecord('account', { filter: { user: { id:current_user } } })
```

This is returning an ember class (a structure whose general obtuseness I have struggled in the past with) so I know it is hitting something. However, it is trying to fire the following GET request to my API: 

`http://localhost:4741/accounts?filter%5Buser%5D%5Bid%5D=44`

and is returning me an error reading "Cannot convert undefined or null to object".

I am definitely missing something here, but I am not sure what. I have been able to read the user id of a given account to my templates (via `{{account.user.id}}`), so why am I failing to return one using similar logic?

**Comment by tvcrawley** [comment]
Before getting to `queryRecord`, have you tried the suggestions of the last comment?

If so, what were your results?

**Comment by d00medman** [comment]
Yeah, the routing for the link worked as intended.  When I trued to pass the `user_id` as params via the url, I found myself back at square one: needing to find some way to trade it in for an account ID before loading the account I want in my-account.

Broadly speaking, I do not want `my-account` to be able to access any account, I only want it to the account of the current user. Once I get this done, I plan on using this methodology to build out a different component path to return and view any account in the system.

**Comment by BenGitsCode** [comment]
Did you _not_ use ember generate to create your `accounts/index` route?

**Comment by BenGitsCode** [comment]
It doesn't appear to have a matching javascript file.

**Comment by d00medman** [comment]
I did use the cli, but I only generated a template. Could that prove problematic?

**Comment by tvcrawley** [comment]
To effectively use Ember, all files need to be generated or it's really easy to have missing functionality. What Ben is referring to is that since there is no accompanying js file for this template, Ember is looking for something that doesn't exist `accounts/index.js`.

**Comment by d00medman** [comment]
The index template is really just the top level view, right? I'm really only using index as a go-between  to help me access my other views templates. Do index templates really need component files if their sole purpose is linking?

**Comment by tvcrawley** [comment]
Every `.hbs` needs a `.js` even if the `.js` isn't being used. This is what Ember expects.

**Comment by d00medman** [comment]
So, I've found part of the problem, courtesy of [this](https://stackoverflow.com/questions/44528824/finding-data-in-a-belongs-to-relationship-in-ember/44529193?noredirect=1#comment76051611_44529193) SO question: my index call was broken on the back end. With my index call reverted to functional:

```ruby
def index
    @accounts = Account.all
    render json: @accounts
  end
```

And my current my-account route looking like this:

```js
model (params) {
    // console.log(params);
    let currentUser = this.get('auth.credentials.id');
    // console.log('current user ', currentUser);
    // const adapter = this.store.adapterFor('account');
    // let targ = adapter.getAccountId(currentUser);
    // targ.then((accountId) => {
    //   return this.get('store').findRecord('account', accountId);
    // });
    // return adapter.getAccountId(currentUser);
    // let targ = (this.store.queryRecord('account', { filter: { user: { id:currentUser } } }));
    // let targ = (this.store.queryRecord('account', { filter: { user_id: currentUser} }));
    // console.log('targ: ', targ);
    // targ = targ.id;
    // This needs to be tremendously simplified and hardcoded
    // console.log(targ);
    // console.log(params);
    // let user = this.store.peekRecord('user', currentUser);
    // return this.store.queryRecord('account', { filter: { user: user} });
    // console.log(targ.user_name);
    // return targ;
    // return this.get('store').findRecord('account', targ);
    // let accountID = this.store.query('account', { filter: { user: { id:currentUser} } });
    // console.log(accountID.id);
    // return this.get('store').findRecord('account', accountID);
    return this.store.queryRecord('account', { filter: { user:  currentUser } })
    // return this.store.queryRecord('account', { filter: { user_id: currentUser } })
    .then((accounts) => {
     return accounts.get('firstObject');
    })
    .catch((error) => {
      console.log(error);
    });
  },
```
I am able to write the first account in my database to my template. This is a huge step in the right direction. A lot of questions remain, however. For example, why is my back end returning everything, rather than narrowing down to the one I want? Is it possible for me to direct my route to a show, rather than an index? I think that the editable tag could be the key to solving this problem, if i could get some help understanding it, that would be incredibly helpful.

**Comment by d00medman** [comment]
So after a fairly brutal slog, I was finally able to get the functionality working as intended. Given that I was getting an array, I had my template iterate through the array and only instantiate the account with an editable attribute.

While it is a huge relief to have this problem solved, I am concerned about the fact that this solution is not super replicable, especially given that I will need to replicate it in other locations. That said, I am certain there is a way to both maintain the appropriate data and pass it on when it is needed.
