### ISSUE TITLE
Update feature not working (Ember)

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/capstone-project#663]
I'm trying make an update feature to work. So far, I have gotten Create, Read, and Delete actions to work.

I have my model defined in palettes.js that returns the result of an index request to get all palettes from the database. I'm trying to send the data down to inner routes and components.

```Palettes``` is a route, and its template contains ```palettes-all``` component.
```palettes-all``` component contains a link to a route called ```edit```.
```edit``` template/page contains a component called ```palette-edit``` with forms to edit a single palette.

When I type in text in each form field to edit a palette (which consists of color1, color2, color3, color4, in ```templates/components/palette-edit.hbs```), I get this error in the console each time I type (and for each color field): 

``` "Assertion Failed: Cannot call set with 'color1' on an undefined object."```
<img width="1107" alt="screen shot 2017-06-13 at 12 57 47 am" src="https://user-images.githubusercontent.com/16979795/27066686-e15b03d6-4fd3-11e7-9daa-6ef56044aad8.png">

I'm trying to access the model from routes/palettes.js:
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    // index method, gets all palettes
    console.log('get all palettes', this.get('store').findAll('palette'));
    return this.get('store').findAll('palette');
  },
  actions: {
    deletePalette (palette) {
      palette.destroyRecord();
    },
  },
});
```

templates/palettes.hbs
```
<h2>My Palettes</h2>

{{!-- refers to palette from index action in palettes.js --}}
{{#each model as |palette|}}
  {{palettes-all palette=palette deletePalette='deletePalette'}}
{{/each}}
```

templates/components/palettes-all.hbs (below) has a link to the ```edit``` route. Here, I am passing in ```palette``` in the link-to so that the ```edit``` route has access to the ```palette``` model.
```html
<span>{{palette.color1}}</span>
<span>{{palette.color2}}</span>
<span>{{palette.color3}}</span>
<span>{{palette.color4}}</span>

<button class="btn btn-xs btn-danger btn-primary" {{action 'deletePalette'}}>Delete</button>

{{#link-to 'edit' palette=palette}}<button type="button" class="btn btn-info btn-sm">Edit</button>{{/link-to}}
```

templates/edit.hbs
I think this is how it works, but I am trying to set the model of edit.hbs as the model for palette so that the edit route has access to the data of all palettes.
```html
{{palette-edit palette=model editPalette='editPalette'}}
```

routes/edit.js
```
import Ember from 'ember';

export default Ember.Route.extend({
  actions: {
    editPalette(newPalette) {
      console.log('edited palette in edit.js is', newPalette);
      newPalette.save();
    }
  }
});
```

templates/components/palette-edit.hbs
```
<form class='form-group' {{action 'editPalette' on='submit'}}>
  {{input class='form-control' value=palette.color1}}
  {{input class='form-control' value=palette.color2}}
  {{input class='form-control' value=palette.color3}}
  {{input class='form-control' value=palette.color4}}
</form>

<button type="submit" class="btn btn-primary" {{action "editPalette"}}>
  Submit Edited Palette
</button>
```

components/palette-edit.js
```
import Ember from 'ember';
export default Ember.Component.extend({
  newPalette: {
    color1: null,
    color2: null,
    color3: null,
    color4: 'hihihi'
  },
  actions: {
    editPalette () {
      let newPalette = this.get('palette');
      console.log('this is ', palette);
      console.log('newPalette in palette-edit.js', newPalette);
      this.sendAction('editPalette', newPalette);
    }
  }
});
```

**Comment by laurpaik** [comment]
Can you edit the above comment to have the full file paths? i.e. `templates/palette.hbs` or `templates/components/edit.hbs` or something?

**Comment by nriser** [comment]
@laurpaik Sorry about that. I added the full relative paths

**Comment by laurpaik-zz** [comment]
in `components/palette-edit.js`-
```js
import Ember from 'ember';
export default Ember.Component.extend({
  newPalette: {
    color1: null,
    color2: null,
    color3: null,
    color4: 'hihihi'
  },
  actions: {
    editPalette () {
      let newPalette = this.get('newPalette'); // where is the newPalette inside the `get` defined?
      console.log('this is ', palette);
      console.log('newPalette in palette-edit.js', newPalette);
      this.sendAction('editPalette', newPalette);
    }
  }
});
```

**Comment by nriser** [comment]
@laurpaik I'm sorry about that, I believe that used to be 'palette', changed thing around, and didn't realize to change that back. Thank you for bringing it to my attention. 

```this.get('palette')``` refers to the 'palette' in palette-edit.hbs.

FYI, the error messages I get are still the same: Each time I type in a letter in any of the fields (color1, color2, color3, and color4), I get ```"Assertion Failed: Cannot call set with 'color1' on an undefined object."```

**Comment by tvcrawley** [comment]
What is the role of `newPalette` and how is it related (in the code) to `palette`?

**Comment by nriser** [comment]
@tvlangley @laurpaik I redefine the user-generated palette (to newPalette) that's been edited from the existing palette by grabbing the 'palette' from templates/components/palette-edit.hbs.

templates/components/palette-edit.hbs 
```html
<form class='form-group' {{action 'editPalette' on='submit'}}>
  {{input class='form-control' value=palette.color1}}
  {{input class='form-control' value=palette.color2}}
  {{input class='form-control' value=palette.color3}}
  {{input class='form-control' value=palette.color4}}
</form>
```

I send this 'newPalette' up to the edit route to have newPalette finally saved to the database. 

```js
export default Ember.Route.extend({
  actions: {
    editPalette(newPalette) {
      console.log('edited palette in edit.js is', newPalette);
      newPalette.save();
    }
  }
});
```

**Comment by tvcrawley** [comment]
In palettes-all.hbs:

`{{#link-to 'edit' palette=palette}}`
What is  the 1st palette vs the 2nd palette (aka where is the data coming from (in the code)?)


In edit.hbs:

`{{palette-edit palette=model editPalette='editPalette'}}`
Where is the model data coming from (in the code)?

**Comment by laurpaik-zz** [comment]
Just to be clear, `edit` is _not_ a nested route for `palette`, correct?

**Comment by nriser** [comment]
@tvlangley 

> ```{{#link-to 'edit' palette=palette}}```
> "What is the 1st palette vs the 2nd palette (aka where is the data coming from (in the code)?)"

The first 'palette' corresponds to the variable "palette" in palettes-all.hbs and the second corresponds to the variable name that will be passed to edit.hbs. At least, this is what I believe is what's happening.

> ```{{palette-edit palette=model editPalette='editPalette'}}```
> "Where is the model data coming from (in the code)?"

I'm trying to pass down the model data from routes/palettes.js down to templates/components/palettes-edit.js so that palettes-edit.js has access to that model.

**Comment by tvcrawley** [comment]
`palettes-all.hbs:`
Passing data in a link-to is different than passing to a component, thus `{{#link-to 'edit' palette=palette}}` would be more like `{{#link-to 'edit' palette}}`

`edit.hbs:`
By using model here, Ember thinks there is a model hook in this file's route.js. Does this file have another way to access the data we need so it can be passed into the `palette-edit` component?

**Comment by nriser** [comment]
@laurpaik 

> Just to be clear, edit is not a nested route for palette, correct?

Yes, edit is not a nested route for palette. 

My router.js file is as follows:
```
Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('create');
  this.route('palettes');
  this.route('edit');
  // this.route('edit', {path: 'palettes/:palette_id/edit'});
});
```
I have the last line commented out for now because it's the next step after I stop getting error messages each time I type in the four input fields.

**Comment by laurpaik-zz** [comment]
1. Does Ember have a way of finding an individual palette?
1. Once Ember finds that individual palette, is the proper edit form showing up?
1. Does the back-end server say anything to indicate it's trying to go forward with the PATCH?

**Comment by nriser** [comment]
@laurpaik & @tvlangley , thank you so much for your help. I spoke with @MicFin and was able to come to a solution. 

The key thing I was missing is what @tvlangley mentioned: 
>palettes-all.hbs:
>Passing data in a link-to is different than passing to a component, thus {{#link-to 'edit' palette=palette}} would be more like {{#link-to 'edit' palette}}

>edit.hbs:
>By using model here, Ember thinks there is a model hook in this file's route.js. Does this file have another way to access the data we need so it can be passed into the palette-edit component?

I was trying to pass down the model data from routes/palettes.js down to routes/edit.js (from a route to another route), which was incorrect. I was having a fundamental misunderstanding of the relationship between the hbs and its corresponding model. 

First, I renamed files to the following to be more specific with the naming: 
```
templates/components/edit.js --> templates/components/palette-edit.hbs
components/edit.js --> components/palette-edit.js

templates/components/palette-edit.js --> templates/components/palette-edit-form.hbs
components/palette-edit.js --> components/palette-edit-form.js
```

Second, I added the correct route for the palette-edit route:
```
Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('create');
  this.route('palettes');
  this.route('palette-edit', {path: 'palettes/:palette_id/edit'});
});
```

Then I had to define a model in routes/palette-edit.js that returns a single palette (show method): 
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').find('palette', params.palette_id);
  },
  actions: {
    editPalette(newPalette) {
      console.log('edited palette in edit.js is', newPalette);
      newPalette.save();
    }
  }
});
```

Then, in templates/palette-edit.hbs, pass down the model from routes/palette-edit.js to its inner component, templates/components/palette-edit-form.hbs.

templates/palette-edit.hbs:
```html
{{palette-edit-form palette=model editPalette='editPalette'}}
```

Finally, I bound the user-inputted value to the 'palette' object that was passed down. 

templates/components/palette-edit-form.hbs:
```
<form class='form-group' {{action 'editPalette' on='submit'}}>
  {{input class='form-control' value=palette.color1}}
  {{input class='form-control' value=palette.color2}}
  {{input class='form-control' value=palette.color3}}
  {{input class='form-control' value=palette.color4}}
</form>
```

Everything works now! Thank you so much!
