### ISSUE TITLE
Best way to store and sum data in am ember route

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/capstone-project#664]
I am working on getting a total syllables count and am having difficulty figuring out the best way to locally and sum the number of syllabuls.  I would like to have a local array that I push the value to, and then make a finally call to return the total sum and reset it to an empty array.   What I am having difficulty doing is making that local empty array and figuring out how to push to it.  I have started on a couple of routes, using a store.js file, using a computer route, creating a model, creating an ember object, but have not had success with any of them.  Any suggestions on what the best way to go about this would be?  Here is the relevent code.  
At the moment it loops for however many words are in the sentence, which is way I need to be able to store the response.syllables.count somewhere so I can add them once all the syllables have been counted.
```js
import Ember from 'ember';

export default Ember.Route.extend({
  ajax2: Ember.inject.service(),
  actions: {
    callapi (word) {
      let url = 'https://wordsapiv1.p.mashape.com/words/' + word + '/syllables'
      return this.get('ajax2').request(url, {
        method: 'GET',
        headers: {'X-Mashape-Key': 'KT2RseIfS9mshXfUPbtRmjsnE9qkK1Wrs6es'}
      })
      .then((response) => {
        console.log(response)

        this.get('flashMessages')
        .success('The number of syllabuls in the word ' + word + ' is ' + response.syllables.count, {
        sticky: true,
});
```

**Comment by BenGitsCode** [comment]
What's happening now, is not creating the array at all? What's the error?

**Comment by Maggicorp** [comment]
Its not currently throwing an error because I was struggling to pick a route to go down.  I think it makes sense to maybe build an object locally.  Or import and export and object locally?  What I am looking for now is direction on what is the best way to do this, specifically for how to locally store the json object sent back from the api.

**Comment by payne-chris-r** [comment]
What is ajax2? #smh 😜

**Comment by payne-chris-r** [comment]
What does `response` look like?

**Comment by BenGitsCode** [comment]
Have you looked into using the `push()` method to push the records into the data store? Is that what you mean?

**Comment by Maggicorp** [comment]
Ajax 2 is what I use to not pass the header you guys added

**Comment by Maggicorp** [comment]
Here is the newest version.  This is currently getting the right sum in the console log.  No issue at the moment but I am going to wait on closing it until I know it works elsewhere as well. 
```
// import store from 'store.js'

import Ember from 'ember';

export default Ember.Route.extend({
  ajax2: Ember.inject.service(),
  count: [],
  actions: {
    callapi (word) {
      let url = 'https://wordsapiv1.p.mashape.com/words/' + word + '/syllables'
      console.log('call api in create.js');
      return this.get('ajax2').request(url, {
        method: 'GET',
        headers: {'X-Mashape-Key': 'KT2RseIfS9tRmjsnE9qkK1Wrs6es'}
  })
      .then((response) => {
        console.log(response)
        let count = this.get('count')
        console.log('count is', count)
        count.push(response.syllables.count);
        console.log('count is', count)
        count.filter(n => true)
        console.log('sum is', count.reduce((a, b) => a + b, 0));
        this.get('flashMessages')
        .success('The number of syllables in the word ' + word + ' is ' + response.syllables.count, {
        sticky: true,
});

**Comment by Maggicorp** [comment]
using count as an array is working.  I can use push and pop for whats in it in, along with this.get('count').
