### ISSUE TITLE
[Rails] - trouble with .where()

### ISSUE THREAD

**Issue by aprilsourz** [ga-wdi-boston/capstone-project#666]
Hello,

I'm having trouble using .where() in the create action in conversations_controller.rb

Here's the action.

```ruby
def create
    if current_user.account_type == 'engineer'
      render status: 401
      return
    end

    if @recruiter.conversations.where(recruiter_id: create_conversation_params[:recruiter_id]).where(engineer_id: create_conversation_params[:engineer_id]) != []
      render status: 400
        return
      end
    @conversation = @recruiter.conversations.build(create_conversation_params)

    if @conversation.save
      render json: @conversation, status: :created, location: @conversation
    else
      render json: @conversation.errors, status: :unprocessable_entity
    end
  end
```

I want to prevent more than one conversation being created between an engineer and a recruiter. Engineers and Recruiters are in separate tables. A conversation belongs_to an engineer and a recruiter. Recruiters and engineers has_many conversations.

The query I am trying to write should check if a conversation already exists between the recruiter creating the conversation and that engineer. If they do share a conversation I want to send back a 400 and return, if they don't share a conversation I want to create the conversation.

I thew in a binding.pry() right after the first if statement and typed the where query into the console.
It generates this SQL query:

```
SELECT "conversations".* FROM "conversations" WHERE "conversations"."recruiter_id" = $1 AND "conversations"."recruiter_id" IS NULL AND "conversations"."engineer_id" = $2  [["recruiter_id", 17], ["engineer_id", 3]]

```
which returns an empty array. Rails is putting the AND "recruiter_id" IS NULL in there. I think this would work without the IS NULL. What do I need to change in the syntax of my query?

**Comment by jordanallain** [comment]
Rails has something that may be what you want to use, google `validates_uniqueness_of` with `rails` and see if that helps at all.

**Comment by aprilsourz** [comment]
In addition to what what I'm doing or instead of?

**Comment by jordanallain** [comment]
instead of

**Comment by aprilsourz** [comment]
``` ruby
validates_uniqueness_of :engineer_id, scope: :recruiter_id
```

Putting this in models/conversation.rb worked. Thanks!

**Comment by tvlangley** [comment]
Try it out! See what works and what doesn't and let us know.
