### ISSUE TITLE
Rails Migration

### ISSUE THREAD

**Issue by rowlandhill** [ga-wdi-boston/capstone-project#668]
Hi!

I tried to add a 'user_type' to my 'user' in the schema, and when I initially tried to add a 'null: false' requirement, I got an error stating that I wasn't allowed to do that.  I think the reason it was mad was that there's data in the database that has 'user_type' set to 'null'.

Anyway, I used Google, and thought I had the solution which was to add the column with bull: false and a default user, then change the column:

```ruby
class AddUserTypeToUsers < ActiveRecord::Migration[5.0]
  def change
    add_column :users, :user_type, :string, { null: false , default: "user" }
    change_column :users, :user_type, :string, { null: false }

  end
end
```

However, this is what my schema looks like now:

```ruby
create_table "users", force: :cascade do |t|
    t.string   "email",                         null: false
    t.string   "token",                         null: false
    t.string   "password_digest",               null: false
    t.datetime "created_at",                    null: false
    t.datetime "updated_at",                    null: false
    t.string   "user_type",       default: "user", null: false
    t.index ["email"], name: "index_users_on_email", unique: true, using: :btree
    t.index ["token"], name: "index_users_on_token", unique: true, using: :btree
  end
```

I'm able to successfully create users, but the user_type is not passing through to the database:

```
Started POST "/sign-up" for 127.0.0.1 at 2017-06-13 14:31:50 -0400
  ActiveRecord::SchemaMigration Load (0.3ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by UsersController#signup as */*
  Parameters: {"credentials"=>{"user_type"=>"customer", "email"=>"yyy", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}
Unpermitted parameter: user_type
```
I'm not sure how to ask the internet how to fix this problem.  Do I need to create a new migration but use self.up and self.down?  I'm not entirely sure what those do, but I read about them a little bit.

Thanks!
Rowland

**Comment by jordanallain** [comment]
do you have a :user_type permitted in your params in the controller?

**Comment by rowlandhill** [comment]
Ahhhh I had not done that yet!  Thank you!  Will the default give me any issues?  Or am I fine to just leave the default in there and move on?

**Comment by jordanallain** [comment]
what are you trying to do with that line?

**Comment by rowlandhill** [comment]
I added default, because Rails wouldn't let me add the `user_type` column with `null: false`.  Adding the `default` allowed me to add the column, but now I have a default in there.

**Comment by rowlandhill** [comment]
I talked to Jordan in person, he said that the default shouldn't give any issues, since the user will be forced to choose between contractor or customer.  Also, when it goes to production, there will be a new DB and the users, again, will have to choose.  I can fix it down the line, but it shouldn't matter for current needs.
