### ISSUE TITLE
Populating Modals with content

### ISSUE THREAD

**Issue by sstone72389** [ga-wdi-boston/capstone-project#670]
So I am running into an issue populating modals with content. 

here is the code in my events:

```
const onShowModal = function (event) {
  const findId = $(event.target).attr('data-id')
  store.currentId = findId
  const findContent = $(event.target).attr('data-content')
  $('.modal-content').find('textarea').html(findContent)
  $('#updatePostModal').modal('show')
}

const onUpdatePost = function (event) {
  const data = getFormFields(this)
  event.preventDefault()
  if (data.post.content.length >= 1) {
    api.updateById(data, store.currentId)
      .then(ui.updatePostSuccess)
      .then(() => {
        api.showPosts(data)
          .then(ui.showPostSuccess)
          .catch(ui.showPostFailure)
      })
      .catch(ui.updatePostFailure)
  } else {
    $('#succ-fail-mess-two').text('Please Fill in all fields').fadeIn().delay(2000).fadeOut('slow')
    $('input').val('')
  }
}
```

I am able to successfully populate the modals, however, as soon as I edit one... it no longer pre-populates with the correct data. Instead, it shows me the content from the newly updated modal.

If I don't SUBMIT the edit form, it will consistently show the correct data. 

I have been stuck on this for quite some time, so any help would be appreciated!!!

**Comment by jordanallain** [comment]
have you put a debugger in there anywhere and walked through line by line to try and see where its doing the actions you don't want to happen?

**Comment by sstone72389** [comment]
Yes. I was able to fix this by using:
```
const onShowModal = function (event) {
  const findId = $(event.target).attr('data-id')
  store.currentId = findId
  const findContent = $(event.target).closest('.post-list').find('.post-content li').text()
  $('.modal-content').find('textarea').val(findContent)
  $('#updatePostModal').modal('show')
}
```

the problem was that I was using an id where a class was needed and `.html()` instead of `.val()`
