### ISSUE TITLE
Point of clarification re:actions bubbling up in ember

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/capstone-project#672]
I am trying to run a basic update crud action on my account resource. The following is my filepath;

templates/accounts/my-account.hbs

```hbs
<h3>hola</h3>
{{#each model as |account|}}
  {{#if account.editable}}
    {{accounts/my-account account=account}}
  {{/if}}
{{/each}}
{{#link-to 'accounts'}}Back{{/link-to}}
{{outlet}}
```
/templates/components/accounts/my-account.hbs

```hbs
<h4>My Account</h4>
<p>Username: {{account.user_name}}</p>
<p>Creator status: {{account.creator}}</p>
<p>Account ID: {{account.id}}</p>
{{accounts/update-account submit="updateAccount"}}
```
/templates/components/accounts/update-account.hbs

```hbs
<h6>Update account</h6>
{{input value=params.user_name placeholder="Update Username"}}
<button type="submit" class="btn btn-primary" {{action "submit"}}>
  Update Account
</button>
<button class="btn btn-default" {{action "reset"}}>
  Cancel
</button>
```
/components/accounts/update-account.js

```js
import Ember from 'ember';
export default Ember.Component.extend({
  tagName: 'form',
  classNames: ['form-horizontal'],
  params: {},
  actions:{
    submit(){
      this.sendAction('submit', this.get('params'));
    },
    reset () {
      this.set('params', {});
    },
  }
});
```
/components/accounts/my-account.js

```js
import Ember from 'ember';
export default Ember.Component.extend({
  actions:{
    submit(){
      this.sendAction('submit', this.get('params'));
    },
  }
});
```

app/routes/accounts/my-account.js

```js
actions: {
    updateAccount(params) {
      console.log('hits');
      console.log(params);
    },
  }
```

I can state with reasonable confidence that the problem is my failure to send actions down/up. I think that my getting this component to work will be illustrative of how this process works. The error I am getting reads "<ga-wdi-boston.ember-auth@component:accounts/my-account::ember762> no action handler for: updateAccount"`.  This error makes it clear that my problem is in the lack of such an action handler in my component for `/components/accounts/my-account.js`, but I thought that actions were sent up, not down. Exactly where have I gone wrong, and how can I get my `update-account` component to fire the update account method in the `my-account route?`

**Comment by MicFin** [comment]
Start at the bottom.  Share the lowest level component (where the action occurs) hbs and it's js file

**Comment by d00medman** [comment]
From lowest level to highest:

update-account (component):
```hbs
<h6>Update account</h6>
{{input value=params.user_name placeholder="Update Username"}}
<button type="submit" class="btn btn-primary" {{action "submit"}}>
  Update Account
</button>
<button class="btn btn-default" {{action "reset"}}>
  Cancel
</button>
```

```js
import Ember from 'ember';
export default Ember.Component.extend({
  tagName: 'form',
  classNames: ['form-horizontal'],
  params: {},
  actions:{
    submit(){
      this.sendAction('submit', this.get('params'));
    },
    reset () {
      this.set('params', {});
    },
  }
});
```

my-account (component)

```hbs
<h4>My Account</h4>
<p>Username: {{account.user_name}}</p>
<p>Creator status: {{account.creator}}</p>
<p>Account ID: {{account.id}}</p>
{{accounts/update-account submit="updateAccount"}}
```

```js
import Ember from 'ember';

export default Ember.Component.extend({
  actions:{
    submit(){
      this.sendAction('submit');
    },
  }
});
```

my-account (route)

```hbs
<h3>hola</h3>
{{#each model as |account|}}
  {{#if account.editable}}
    {{accounts/my-account account=account}}
  {{/if}}
{{/each}}
{{#link-to 'accounts'}}Back{{/link-to}}
{{outlet}}
```
```js
import Ember from 'ember';
export default Ember.Route.extend({
  auth: Ember.inject.service(),
  model () {
    let currentUser = this.get('auth.credentials.id');
    return this.store.query('account', { filter: { user:  currentUser } })
    .then((accounts) => {
        return accounts;
      })
    .catch((error) => {
      console.log(error);
    });
  },
  actions: {
    updateAccount(params) {
      console.log('hits');
      console.log(params);
    },
  }
});
```

**Comment by laurpaik-zz** [comment]
[Here](https://guides.emberjs.com/v2.11.0/models/creating-updating-and-deleting-records/#toc_persisting-records) is some documentation on `.save()`.
You used it in your [`create account`](https://github.com/d00medman/medici/blob/master/app/routes/create-account.js) method.

Things to think about:
- "Actions up" - what does that mean?
- Does Ember expect your component action and your route action to interact somehow?
- How were you able to send the `create` action up? Could `update` be a similar process?

**Comment by d00medman** [comment]
Alright, so I was able to smooth out my conceptual understanding of how actions are sent up. The following is my component path, from lowest to highest:

update-account

```hbs
<h6>Update account</h6>

{{input value=params.userName placeholder="Update Username"}}

<button type="submit" class="btn btn-primary" {{action "submit"}}>
  Update Account
</button>

<button class="btn btn-default" {{action "reset"}}>
  Cancel
</button>
```
```js
import Ember from 'ember';

export default Ember.Component.extend({
  tagName: 'form',
  classNames: ['form-horizontal'],

  params: {},

  actions:{
    submit(){
      this.sendAction('submit', this.get('params'));
    },

    reset () {
      this.set('params', {});
    },
  }
});
```

my-account component

```hbs
<h4>My Account</h4>
<p>Username: {{account.user_name}}</p>
<p>Creator status: {{account.creator}}</p>
<p>Account ID: {{account.id}}</p>
{{accounts/update-account submit="submit"}}
```

```js
import Ember from 'ember';
export default Ember.Component.extend({
  actions:{
    submit(params){
      this.sendAction('submit', params);
    },
  }
});
```

my-account route

```hbs
<h3>hola</h3>
{{#each model as |account|}}
  {{#if account.editable}}
    {{accounts/my-account account=account submit="updateAccount"}}
  {{/if}}
{{/each}}
{{#link-to 'accounts'}}Back{{/link-to}}
{{outlet}}
```

```js
actions: {
    updateAccount(params) {
      console.log('in route: ', params)
    },
```

I am able to ping the route. Next step is to figure out how to specify that it only wants to update the account of the current user. To do this, I think I will need to reconfigure the model hook for my-account. The process of getting this up and running was an absolute slog, but I think the combination of the `editable` tag added to my back end and the solution to [this](https://stackoverflow.com/questions/44533540/returning-a-record-with-a-string-in-ember/44534841#44534841) problem will make the reconfiguration substantially less painful than the intial implementation.
