### ISSUE TITLE
Unprocessable Entity

### ISSUE THREAD

**Issue by rowlandhill** [ga-wdi-boston/capstone-project#674]
Hi!  I'm getting this error when I try to create a new project:

```
Started POST "/projects/" for 127.0.0.1 at 2017-06-14 10:43:47 -0400
Processing by ProjectsController#create as */*
  Parameters: {"project"=>{"title"=>"lp", "description"=>"lp"}, "submit"=>""}
   (0.7ms)  BEGIN
   (0.2ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.19ms)
Completed 422 Unprocessable Entity in 49ms (Views: 7.9ms | ActiveRecord: 8.9ms)
```

I looked this up online, and what I read was that this error occurs when the syntax of the request entity is correct, but the backend was unable to process the contained instructions.  It sounds like this is an error in the controller, but I'm not sure what to change or what's wrong.  

I'll start from the beginning.  Here the code in index.html:

```html
<form id="createProject" class="form-group">
              <div class="form-group">
                <input class="form-control" type="text" name="project[title]" placeholder="project name">
              </div>
            <div class="form-group">
            <textarea class="form-control" name="project[description]" rows="7" placeholder="add description here"></textarea>
            </div>
            <button type="submit" class="btn btn-default" id="create-project" name="submit">create</button>
            <button type="submit" class="btn btn-default" id="more-task-inputs" name="submit">+ task</button>
            </form>
            </div>
```

here is the click handler:

```js
$('#createProject').on('submit', onCreateProject)
```

event handler:

```js
const onCreateProject = function (event) {
  event.preventDefault()
  const data = getFormFields(this)
  api.createProject(data)
    .then(ui.createProjectSuccess)
    .catch(ui.createProjectFailure)
}
```

the api call:

```js
const createProject = (data) => {
  console.log('createProject data is', data)
  return $.ajax({
    url: config.apiOrigin + '/projects/',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```

the create method in the controller:

```ruby
# POST /projects
  def create
    @project = current_user.project.build(project_params)
    # @project = Project.new(project_params)

    if @project.save
      render json: @project, status: :created, location: @project
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end
```

the route:

```ruby
  resources :projects, only: [:new, :edit, :create, :index, :show, :destroy, :update]
```

the schema:

```ruby
create_table "projects", force: :cascade do |t|
    t.string   "title"
    t.text     "description"
    t.integer  "user_id"
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
    t.index ["user_id"], name: "index_projects_on_user_id", using: :btree
  end
```

I'm not sure what else you need to see the path of the data.  It's getting the data, but something must be happening on the backend that's preventing it from processing it.  I console.logged the data, and it's showing the items that Projects requires: title and description.

**Comment by jordanallain** [comment]
`Parameters: {"project"=>{"title"=>"lp", "description"=>"lp"}, "submit"=>""}`

this seems curious, are you trying to pass `"submit"` to the back end?

**Comment by rowlandhill** [comment]
I'm not, but I'm not sure why it's including submit as data?  It's just a button with no value:

```js
            <button type="submit" class="btn btn-default" id="create-project" name="submit">create</button>
```

**Comment by jordanallain** [comment]
did you use a debugger or console.log statement to check out what the data is before you send it to the back end?

**Comment by cpearce31** [comment]
I think this is caused by having two `<button>`s with `type="submit"` inside the same form. According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button, buttons will have their `name` properties submitted along with the rest of the form info. I think the `submit` key in `Parameters: {"project"=>{"title"=>"lp", "description"=>"lp"}, "submit"=>""}` is coming from the `name` field of one of your buttons. Your wouldn't expect a param called `"submit"`, so it throws an error.

**Comment by rowlandhill** [comment]
I used a debugger and saw that it was passing title and description.  I removed the second button and submit is no longer being passed, but now I'm seeing this 422 Unprocessable Entity error:

```
Started POST "/projects/" for 127.0.0.1 at 2017-06-14 11:05:59 -0400
Processing by ProjectsController#create as */*
  Parameters: {"project"=>{"title"=>"lp", "description"=>"lp"}}
   (2.5ms)  BEGIN
   (1.2ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.15ms)
Completed 422 Unprocessable Entity in 21ms (Views: 1.1ms | ActiveRecord: 3.7ms)
```

My ProjectSerializer looks like this:

```ruby
class ProjectSerializer < ActiveModel::Serializer
  attributes :id, :title, :description
end
```

I tried create with the Serializer looking like this, and also removing ```:id``` which is referencing the user.

**Comment by cpearce31** [comment]
Is your controller expecting just `{"title"=>"lp", "description"=>"lp"}` instead of `{"project"=>{"title"=>"lp", "description"=>"lp"}}`?

**Comment by rowlandhill** [comment]
It's expecting project.  Here are the params in the Project Controller:

```ruby
def project_params
    params.require(:project).permit(:title, :description)
  end
```

**Comment by cpearce31** [comment]
It appears to me that the code you just posted is expecting `:project`, `:title`, and `:description` to be top-level properties of `params`.

**Comment by rowlandhill** [comment]
I'm sorry, I don't understand what that means :/

**Comment by cpearce31** [comment]
@rowlandhill My last comment was incorrect so I deleted it. Please disregard!

**Comment by rowlandhill** [comment]
Ah, no worries!  So, I ran a curl script and now this is the error I'm seeing:

```
NoMethodError (undefined method `build' for nil:NilClass):
  
app/controllers/projects_controller.rb:19:in `create'
```
line 19 of my projects_controller looks like this:

```ruby
    @project = current_user.project.build(project_params)
```

**Comment by MicFin** [comment]
Use `binding.pry` to see what the value of `params` and `project_params` is.
Then use `binding.pry` to see why `@project.save` does not work.
```rb
def create
    @project = current_user.project.build(project_params)
    binding.pry 
    if @project.save
      render json: @project, status: :created, location: @project
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end

**Comment by MicFin** [comment]
Does a User have 1 or many project(s)? 
Should it be `current_user.project` or `.projects`?

**Comment by rowlandhill** [comment]
has_one

**Comment by MicFin** [comment]
`.build` is for has_many only.
https://stackoverflow.com/questions/2472982/using-build-with-a-has-one-association-in-rails

**Comment by rowlandhill** [comment]
it's written:

```ruby
has_one :project
```

**Comment by rowlandhill** [comment]
ohhhhhh my gooooood

**Comment by rowlandhill** [comment]
@MicFin I just changed it over per the Stackoverflow article, to this:

```ruby
def create
    @project = current_user.project_build(project_params)

    if @project.save
      render json: @project, status: :created, location: @project
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end
```

but am now getting this error:

```
NoMethodError (undefined method `project_build' for #<User:0x007f842a471520>
Did you mean?  project=):
  
app/controllers/projects_controller.rb:19:in `create'
```

My Controllers file validates the user, but for some reason it's telling me there's no build method for project?  I'm not sure what this error is telling me.

**Comment by jordanallain** [comment]
did you mean project.build?

**Comment by rowlandhill** [comment]
Oh wait, standby.  I have a typo.  Sorry!  I'll post again once I've tested

**Comment by rowlandhill** [comment]
I had incorrectly typed my create method like this:

```ruby
    @project = current_user.project_build(project_params)
```

I just needed to reverse project_build, to look like this:

```ruby
@project = current_user.build_project(project_params)
```

After changing the code, and testing, I successfully created a wonderful task called "lp" and got the glorious 201:

```
Started POST "/projects/" for 127.0.0.1 at 2017-06-14 12:06:08 -0400
Processing by ProjectsController#create as */*
  Parameters: {"project"=>{"title"=>"lp", "description"=>"lp"}}
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "0ac05ee31719b4d023f3b498b1a0db3b"], ["LIMIT", 1]]
  Project Load (13.2ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
   (0.2ms)  BEGIN
  SQL (9.5ms)  INSERT INTO "projects" ("title", "description", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["title", "lp"], ["description", "lp"], ["user_id", 1], ["created_at", 2017-06-14 16:06:08 UTC], ["updated_at", 2017-06-14 16:06:08 UTC]]
   (0.4ms)  COMMIT
[active_model_serializers] Rendered ProjectSerializer with ActiveModelSerializers::Adapter::Json (0.29ms)
Completed 201 Created in 117ms (Views: 3.8ms | ActiveRecord: 39.3ms)
```

Thank you all for your help!
