### ISSUE TITLE
[Ember] Sending request to 3rd party API

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/capstone-project#675]
I am having trouble writing a request to an API called Impalette. 

The info provided in the documentaiton for Impalette API provides is very minimal: 
[(https://impalette.com/Home/Api)]
```
Endpoint: https://impalette.com/api/scan

Parameters:
- apiKey: Your personal, private API key. Get one by signing up for an account Here
- link: The url of the image you want to scan.
- ...
```
As you can see, there is no mention of what type of HTTP request it expects.

So far, I have tried the following (and other variations of this) in ```routes/palette-create.js```:
```js
import Ember from 'ember';

export default Ember.Route.extend({
  ajaxImageAnalysis: Ember.inject.service('ajax-image-analysis'),

  actions: {
    createPalette (data) {
        ...
        ...
    },
    callImpaletteApi(imageUrl) {
      console.log('call impalette api inside palette-create.js');
      let urlToSend = 'https://impalette.com/api/scan'; // 

      return this.get('ajaxImageAnalysis').request(urlToSend, {
        link: imageUrl,
        method: 'GET',
        headers: {
          'Access-Control-Allow-Origin': 'https://impalette.com/api/scan',
          'apiKey': 'c6f4b375-9098-48e8-ab77-93d8972b4401',
        }
      });
    }
  }
});
```
```imageUrl``` refers to the user-inputted url of an image, like: 
https://user-images.githubusercontent.com/16979795/27139521-3e6ea190-50f1-11e7-8735-2f7619657ab4.png

Every variation of the request I try gives me the following error messages in the console:

<img width="602" alt="screen shot 2017-06-14 at 11 03 39 am" src="https://user-images.githubusercontent.com/16979795/27139521-3e6ea190-50f1-11e7-8735-2f7619657ab4.png">

I'd really appreciate help with this. 

FYI: If you add the following link on your browser, you'll see that you'll get a response successfully from the API:
https://impalette.com/api/scan/?apiKey=c6f4b375-9098-48e8-ab77-93d8972b4401&link=https://www.serviceseeking.com.au/blog/wp-content/uploads/2015/04/tree-696839_1280.jpg

**Comment by cpearce31** [comment]
This looks like a CORS issue. Check out: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS. Look at the preflighting section. They may be expecting an OPTIONS request as discussed there.

**Comment by benjimelito** [comment]
I think the 'Access-Control-Allow-Origin' header that you're passing is expecting a different value than the one you're giving it. Try checking out some example of that header.

**Comment by nriser** [comment]
@cpearce31 I changed the method to an 'OPTIONS' method, but it still gives me the same errors: 

```js
...
    callImpaletteApi(imageUrl) {
      console.log('call impalette api inside palette-create.js');
      let urlToSend = 'https://impalette.com/api/scan/?apiKey=c6f4b375-9098-48e8-ab77-93d8972b4401&link=' + imageUrl;

      return this.get('ajaxImageAnalysis').request(urlToSend, {
          method: 'OPTIONS',
          headers: {
            'Access-Control-Allow-Origin': 'https://impalette.com/api/scan'
          }
      });
    }
  }
});
```

<img width="642" alt="screen shot 2017-06-14 at 11 54 25 am" src="https://user-images.githubusercontent.com/16979795/27142179-5186da02-50f8-11e7-9062-f3ac1ad25d4e.png">


@benjimelito 

I've also tried this but to no avail & same error messages: 
```js
...
    callImpaletteApi(imageUrl) {
      console.log('call impalette api inside palette-create.js');
      let urlToSend = 'https://impalette.com/api/scan/?apiKey=c6f4b375-9098-48e8-ab77-93d8972b4401&link=' + imageUrl;

      return this.get('ajaxImageAnalysis').request(urlToSend, {
          method: 'GET',
          headers: {
            'Access-Control-Allow-Origin': 'https://impalette.com/' 
                           // I also tried 'https://impalette.com/api/scan', their endpoint
          }
      });
    }
  }
});
```

**Comment by nriser** [comment]
@benjimelito @cpearce31 

I found this article about how to run https on localhost: 
http://userpath.co/blog/a-simple-way-to-run-https-on-localhost/

is this worth a try? I don't want to commit to it yet for fear of installing something that could mess with other things installed.

**Comment by benjimelito** [comment]
Have you tried setting that header to '*' rather than a url?

**Comment by nriser** [comment]
@benjimelito 

is this what you mean?

```js
callImpaletteApi(imageUrl) {
      console.log('call impalette api inside palette-create.js');
      let urlToSend = 'https://impalette.com/api/scan/?apiKey=c6f4b375-9098-48e8-ab77-93d8972b4401&link=' + imageUrl;

      return this.get('ajaxImageAnalysis').request(urlToSend, {
          method: 'GET',
          headers: {
            'Access-Control-Allow-Origin': '*'
          }
      });
    }
  }
});
```

I get this error message: 
<img width="746" alt="screen shot 2017-06-14 at 12 13 30 pm" src="https://user-images.githubusercontent.com/16979795/27143022-eb3cb0f2-50fa-11e7-9c2f-3fb9fc8ec466.png">

**Comment by benjimelito** [comment]
Ah I thought that might help. Per our conversation in the kitchen, I would try making this request from the back-end rather than the front-end.

**Comment by benjimelito** [comment]
Any luck making this API call from the back-end?

**Comment by nriser** [comment]
@benjimelito 

Thanks for your advice. I was hesitant to make the request from the backend because I haven't done that before (only frontend), so I used a different API (https://market.mashape.com/apicloud/colortag) that works from the frontend. The downside is that it's max limit for requests is 500 per month, and you'd get charged per request if you go over (you have to give it your credit card info). 

Ideally, I'd get the first API (max 1000 requests/mo, no credit card) to work using the backend but since I'm feeling pressed for time, I decided to go with the second one for now. 

Thanks @benjimelito @cpearce31
