### ISSUE TITLE
create location error

### ISSUE THREAD

**Issue by eliottenos** [ga-wdi-boston/capstone-project#676]
Im trying to create a new location but the page refreshes and its not hitting my server at all even though looks like it should be passing the data to the correct route?
```html
<h3>Create Location</h3>
        <form class='locations' id='location-create'>
        <div class="form-group" class="form-reset">
          <input type="text" name="location[country]" id="location-create" placeholder="Location">
            <input type="text" name="location[note]" id="location-create" placeholder="Note">
        <input type="submit" name="submit" value="Submit">
      </form>
```
```js
const onCreateLocation = function (event) {
  const data = getFormFields(event.target)
  event.preventDefault()
  api.createLocation(data)
    .then(ui.createLocationSuccess)
    .catch(ui.createLocationFailure)
}
const addHandlers = () => {
  $('#location-create').on('submit', onCreateLocation)
}

const createLocation = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/create-location',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: data
  })
}
```

**Comment by eliottenos** [comment]
looks like it was an error with my properties when migrating
Ive tried to roll back the migration to correct it and start again with ```rake db:rollback``` but it wont roll back for some reason?

**Comment by eliottenos** [comment]
it needs to have skipped the last migration and rolled back examples?
```
$ rake db:rollback
== 2 CreateExamples: reverting ================================================
-- drop_table(:examples, {})
   -> 0.1461s
== 2 CreateExamples: reverted (0.1507s) =======================================

```

**Comment by cpearce31** [comment]
What error do you get on `rake db:rollback`?

**Comment by eliottenos** [comment]
I dont get an error but its not rolling back my last migration for some reason?

**Comment by jordanallain** [comment]
you likely never ran the migration because it is rolling back the migration that created the examples table.

**Comment by eliottenos** [comment]
@jordanallain its definitely showing in my migrations?
db/migrate/20170613161039_create_locations.rb

**Comment by cpearce31** [comment]
Have you tried `rake db:migrate` just to double check that they've all been run?

**Comment by eliottenos** [comment]
why would the server say its been rolled back but all the locations files are still in my repo?
```
$ rake db:rollback
== 20170613161039 CreateLocations: reverting ==================================
-- drop_table(:locations)
   -> 0.8242s
== 20170613161039 CreateLocations: reverted (0.8286s) =========================

```

**Comment by MicFin** [comment]
It is only rolling back the schema.rb, one migration file at a time.  It does not affect any models or controllers.

**Comment by eliottenos** [comment]
so I decided to scrap that and start a fresh migration for Places but I think have inadvertently rolled back some User files as Im now getting a 500 error when signup/log in?
```
Started POST "/sign-in" for 127.0.0.1 at 2017-06-15 10:06:04 -0400
  
PG::ConnectionBad (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
):
```

**Comment by eliottenos** [comment]
created new migration to start from scratch
