### ISSUE TITLE
Deployed ember app broken

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/capstone-project#679]
I recently ran through the deployment guide, and my app appears to be building properly, but is failing to connect to my deployed api. It is claiming to be throwing 500 errors, but on my heroku dashboard, it is showing to still be asleep, leading me to believe it was never even hit with these errors. I am also unable to access any of my routes, which should not be happening, even for a non-authenticated user.

It is worth noting that I may have screwed up my initial deployment, missing the step where you deploy commit the changes made in your dist before running ember build. I also did not set an apihost in my ENV file, as I was told it should not matter if that is stopping my functionality.

My personal inclination in this situation is to burn it all down and start from scratch, assiduously following the instructions. That said, I'm not sure how to do this and think it is something of an extreme solution. I could really use some guidance on how to get this working, it is obviously hugely important. 

UPDATE: So the reason it was failing to connect to my backend is because I had some old code which was meant to run omniauth before realizing I would not be using omniauth. After scrubbing all references to omniauth, I am able to connect to my back end. This, however, does not solve the other problem in that none of my non-auth routes are appearing.

**Comment by MicFin** [comment]
What is the status of this?

**Comment by tvcrawley** [comment]
@d00medman ☝️

**Comment by d00medman** [comment]
Putting the problem off until my next deployment. Ben Adamski said he was going to sit down with me to see where I went wrong/how to right it at that point in time
