### ISSUE TITLE
Trouble with users in Saads express backend

### ISSUE THREAD

**Issue by mkutter72** [ga-wdi-boston/capstone-project#68]
My app needs several people to be longed in at once and perform DB writes.    I'm using 
{userName: req.user.userName,  to set my username in the database.   The username written to the database is always the last person log in

**Comment by GA-MEB** [comment]
Mike, can you be more clear about the intended and actual behavior?

**Comment by mkutter72** [comment]
Misunderstanding.    You can't run 2 clients on one computer with the same brower
