### ISSUE TITLE
'GET' request success, but getProjectSuccess method not firing

### ISSUE THREAD

**Issue by rowlandhill** [ga-wdi-boston/capstone-project#682]
I'm not sure why, but my `getProjectSuccess` method is not firing after a successful `GET` request.  

I can see in my Chrome console in the Network tab that it's returning the Project.  Even when I create a new Project, then execute the `GET` request again, it returns the new Project.  So it's communicating with the backend, but I'm not sure what's wrong in my code that is preventing the getProjectSuccess from firing.  So, here is the code:

click event
```js
$('#getProjectButton').on('click', onGetProject)
```

onGetProject in events.js
```js
const onGetProject = function (event) {
  console.log('data is ', data)
  const data = getFormFields(this)
  event.preventDefault()
  console.log('made it 1 ', data)
  api.getProject(data)
    .then(ui.getProjectSuccess)
    .catch(ui.getProjectFailure)
  console.log('what ', data)
}
```

getProject in api.js
```js
const getProject = () => {
  console.log('made it 2')
  return $.ajax({
    url: config.apiOrigin + '/projects',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```

getProjectSuccess in ui.js
```js
const getProjectSuccess = (data) => {
  console.log('we made it')
  // console.log('getAllRecipesSuccess fired')
  store.projectList = data.projects
  refreshProject()
}
```

`console.log('we made it')` never fires when I start the event, but all the others fire, even the `console.log('what')` underneath the promises.  Is there anything missing?  Again, the call is successful, this is what's returning in the network tab in Chrome's console:

<img width="698" alt="screen shot 2017-06-15 at 8 50 14 am" src="https://user-images.githubusercontent.com/20341219/27181969-bbb0fc64-51a7-11e7-9009-0ff318878012.png">

In the picture, it does look like there are two `GET` requests happening, one returning empty, the other returning with the correct data.  However, I noticed the same thing on `POST` and `POST` is working perfectly.

**Comment by cpearce31** [comment]
Are you certain that `ui.getProjectFailure` isn't firing instead?

**Comment by rowlandhill** [comment]
Yes.  I just double-checked and added a `console.log()` message in `ui.getProjectFailure` and nothing was returned.  Here is the code that did not fire:

```js
const getProjectFailure = (error) => {
  console.error('getProject failure is ', error)
}
```

**Comment by cpearce31** [comment]
If you `console.log(ui.getProjectSuccess)` in `events.js`, does it show the function correctly? I might also try  nesting the `ui.getProjectSuccess` call in an anonymous function inside the `.then()` parens, just to see if that changes anything.

**Comment by rowlandhill** [comment]
`console.log('success function is ', ui.getProjectSuccess)` returns `success is undefined`

Nesting it in an anonymous function doesn't cause it to fire, either :/

The console.log() inside the anonymous function fires, though.  Here's the nested code:

```js
const onGetProject = function (event) {
  const data = getFormFields(event.target)
  event.preventDefault()
  api.getProject(data)
  .then(() => {
    ui.getProjectSuccess
    console.log('nested function firing?')
  })
}
```

I can see `nested function firing?` in the Chrome console, but `ui.getProjectSuccess` does not fire.

**Comment by cpearce31** [comment]
if `ui.getProjectSuccess` is undefined in the scope of `events.js` then it's likely an issue with how you're importing and exporting modules.

**Comment by rowlandhill** [comment]
Would it be possible to have a consultant look at my code?  The importing and exporting of the modules for this `GET` request mimics the modules for `POST`, and that's working.  I'm not sure what I'm doing wrong here.

**Comment by rowlandhill** [comment]
Met with Caleb and I wasn't exporting the `getProjectSuccess` and `getProjectFailure` functions in ui.js -_-

Thank you Caleb!
