### ISSUE TITLE
Injecting a service into a route level template

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/capstone-project#686]
I am trying to leverage the `isAuthenticated` functionality of the auth service in my templates. I am able to access it in the my application component, and I am pretty sure I am doing so via the following line of code in the my-application.js file:

```js
auth: Ember.inject.service(),
user: Ember.computed.alias('auth.credentials.email'),
isAuthenticated: Ember.computed.alias('auth.isAuthenticated'),
```

However, When I copy this code into the js files of other route/component js files, it does not give me access to the functionality. For example, in the file components/accounts/my-account.js, I have placed the code in and tried to leverage it with little success. Exactly what am I missing about injecting this service?

**Comment by danman01** [comment]
Is there additional setup code such as a `require` to get access to the Auth service?

This may be a useful read: http://www.thegreatcodeadventure.com/creating-a-current-user-property-in-ember/

**Comment by cpearce31** [comment]
Any progress here?

**Comment by d00medman** [comment]
Sort of. Found a way to mimic the functionality. My plan is to resolve other ui issues, then circle back and determine if this problem is still relevant. My guess is it probably will be, but its hard to say at the moment.

**Comment by d00medman** [comment]
Alright, so the mystery here has deepened. As it turns out, I am properly passing the isAuthenticated property to the js side of my component, but I am unable to make the jump over to the associated hbs file. This is made all the stranger by the fact that I am able to use the properties in the my-accounts component file using the exact same methodology which has been failing in the other routes. Why would this code succeed in one place, but fail in another with the exact same methodology?

**Comment by d00medman** [comment]
Was actually able to solve this by only using the property in component paths.
