### ISSUE TITLE
[Ember] this.get('palette') is not the user input of the edited palette colors?

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/capstone-project#690]
I used regular expressions in ```components/palette-create-form.js``` (create page) where users can create a new palette of four colors. The regular expression validates user-inputted values for color1 - color4, and check to see that the values are valid hexadecimal color codes.

The trouble I'm having is that I'm trying to use the same exact code for my edit page where users can edit each of the four colors of a single palette. 

components/palette-create-form.js
```js
import Ember from 'ember';

export default Ember.Component.extend({
  tagName: 'form',
  classNames: ['color-palette-form'],

  newPalette: {}, // reset
  //   color1: null,
  //   color2: null,
  //   color3: null,
  //   color4: null
  // }, // This object is filled in with user's inputs for colorone, two, three, and four in color-palette.hbs.

  actions: {
    createPalette () {
      let data = this.get('newPalette');
      console.log('data in palette-create-form.js is', data);
      
      if (data.color1.match(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/) &&        data.color2.match(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/) &&
      data.color3.match(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/) &&
      data.color4.match(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/)) {
        this.sendAction('createPalette', data);
        this.set('newPalette.color1', null);
        this.set('newPalette.color2', null);
        this.set('newPalette.color3', null);
        this.set('newPalette.color4', null);
      } else {
        this.get('flashMessages')
        .danger("Error: Please provide a valid hex code, starting with a '#'");
      }
    }
  },
});
```

I used the same code from above in components/palette-edit-form.js, but I am given an error message in the console, shown below code. 
```js
import Ember from 'ember';

export default Ember.Component.extend({
  palette: {
    color1: null, // value gets updated by value=palette.color1 in palette-edit-form.hbs (binding the value to the model data)
    color2: null,
    color3: null,
    color4: null
  },
  actions: {
    editPalette () {
      console.log("hooray, inside palette-edit-form, editPalette action");
      let newPalette = this.get('palette'); // this gets 'palette' from line 4, but one with data that user inputted.
      console.log('newPalette in palette-edit.js', newPalette);

      if (newPalette.color1.match(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/) &&        newPalette.color2.match(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/) &&
      newPalette.color3.match(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/) &&
      newPalette.color4.match(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/)) {
        this.sendAction('editPalette', newPalette);
      } else {
        this.get('flashMessages')
        .danger("Error: Please provide a valid hex code, starting with a '#'");
      }
    },
  }
});
```

Error message:
<img width="949" alt="screen shot 2017-06-15 at 2 07 39 pm" src="https://user-images.githubusercontent.com/16979795/27195269-16344dd6-51d4-11e7-9075-9f39c1f96d12.png">

So I think the reason I'm getting this error is due to the fact that, at this point, ```newPalette``` had already been 'emberified' (made into an Ember object) because the new palette has already been created. 

But since components/palette-edit-form.js has access to the newly inputted user data in components/palette-edit-form.hbs, I thought that ```this.get('palette')``` gets the  'palette' that has been newly edited by the user (value=palette.color1, value=palette.color2, value=palette.color3, value=palette.color4). I'm quite lost! 

components/palette-edit-form.hbs
```js
<form class='form-group' {{action 'editPalette' on='submit'}}>
  {{input class='form-control' value=palette.color1}}
  {{input class='form-control' value=palette.color2}}
  {{input class='form-control' value=palette.color3}}
  {{input class='form-control' value=palette.color4}}
</form>

{{!-- value=palette.color2: binding the user inputted data --}}

<button type="submit" class="btn btn-primary" {{action "editPalette"}}>
  Submit Edited Palette
</button>
```

**Comment by MicFin** [comment]
Can you `console.log(newPalette.color1)`?

**Comment by nriser** [comment]
@MicFin 

This is what I get: 

<img width="905" alt="screen shot 2017-06-15 at 2 29 37 pm" src="https://user-images.githubusercontent.com/16979795/27196086-21dcd7cc-51d7-11e7-9128-3368ba063393.png">

**Comment by cpearce31** [comment]
I believe you may need to access `color1` via `newPalette.get('color1')` instead of `newPalette.color1`

**Comment by cpearce31** [comment]
Also worth noting that if you call `.match()` on something that's not a string, you get the same error you're getting. It's possible that `color1` is still null when `.match()` gets called.

**Comment by nriser** [comment]
@cpearce31 @MicFin 

It works!!! I did what @cpearce31 said. That makes sense. Will write an explanation.

**Comment by nriser** [comment]
@cpearce31 Actually, I'm unsure about the underlying concept. May I request a quick one-on-one with you? I'd like to point to things on my screen with all the relevant files out in Atom so that I can better understand the connection between variables in different files.

**Comment by MicFin** [comment]
Should we be doing `newPalette.get('color1')` then?
https://guides.emberjs.com/v2.7.0/object-model/computed-properties/#toc_computed-properties-in-action

**Comment by nriser** [comment]
@MicFin Sorry for the delayed!

Yes, the fix was newPalette.get('color1'). I had to do .get('color1') instead of .color1 because I'm accessing the database through Ember. 

Thank you @MicFin & @cpearce31!
