### ISSUE TITLE
[requirements] Would this be considered a bug?

### ISSUE THREAD

**Issue by aprilsourz** [ga-wdi-boston/capstone-project#691]
Hi,

In my app there a two account types, engineer and recruiter. They are in separate tables in the database. The recruiter can view a list of all the engineers, select one and start a conversation with them. In this view they will always see all the engineers in the database.

A conversation consists of 1 invitation(sent from the recruiter) and 1 response(sent from the engineer). Invitation and response are columns in the conversations table. Only one conversation can exist between a recruiter and an engineer at a time. My rails app will send back a 422 if a recruiter attempts to create a second conversation with an engineer.

In the front end, if a recruiter attempts to start a second conversation with an engineer they will be redirected back to the list of engineers and a flash message appears reading "Only one invitation per engineer".

Engineers the recruiter has already sent an invitation too will appear in the list. Would that be considered a bug? I think the way I'm handling this in the UI is sufficient. I wanted to open an issue to clarify.

**Comment by payne-chris-r** [comment]
Sounds like you're handling the error exactly how you should. It might be cool to grey out engineers that recruiters have already reached out to, but that would be going above and beyond. As long as there is feedback to the user when they do an action that results in an error, you are 👍

**Comment by aprilsourz** [comment]
Thanks Chris! Sounds good.
