### ISSUE TITLE
deployment error

### ISSUE THREAD

**Issue by JLisaW** [ga-wdi-boston/capstone-project#692]
I'm getting an error when I deploy on heroku

![image](https://user-images.githubusercontent.com/26361086/27199285-6ca3a176-51e3-11e7-90d1-fe0f03154ac2.png)

I reset the heroku config and pushed but it's still giving me an error.

**Comment by MicFin** [comment]
Take a look at these and see if they help:
https://github.com/ga-wdi-boston/full-stack-project/issues/958

**Comment by JLisaW** [comment]
i had an extra slash after my repo name
