### ISSUE TITLE
[Ember] /palettes/create page is displayed even when not signed in

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/capstone-project#693]
I'm using the authentication files from our ember-auth lecture, and everything is working just fine. 

Here is my app so far: https://nriser.github.io/ember-capstone/#
**(side question: Why does the deployed url have a '#' symbol?**

Without signing in, if you add ```/paletttes``` to the URL, you'll see that it gives you an error message ("You must be signed in to access this page") and get redirected to the sign-in page.
(https://nriser.github.io/ember-capstone/#/palettes). 

However, if you type (https://nriser.github.io/ember-capstone/#/palettes/create), the palette-create-form and palette-analysis-form components in my palette-create route gets displayed. If you try to create a new palette, it'll give the below error:

console error: 
```
POST https://colorpal.herokuapp.com//palettes 401 (Unauthorized)
```

Even though a user cannot create a new palette when not signed in, I want it so that it'll give an error message and redirect to the sign-in page like it does for the ```/palettes``` route. 

My question is, why does the /palette page redirect to the sign-in page but not the /palette/create page? I can't seem to understand 

This is what I currently have for templates/palette-create.hbs, the landing page, where the links to ```palette-create``` and ```palette``` routes are wrapped with {{#if isAuthenticated}}{{/if}}. 

```hbs
<nav class="navbar navbar-default">
  <div class="container-fluid">
    {{navbar-header}}

    <div class="collapse navbar-collapse" id="navigation">
      <ul class="nav navbar-nav">
        {{#if isAuthenticated}}
        {{!-- if user is authenticated, then display users --}}
        <li>{{#link-to "users"}}Users{{/link-to}}</li>
        {{/if}}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {{#if isAuthenticated}}
        <li>{{#link-to "change-password"}}Change Password{{/link-to}}</li>
        <li><a href="#" {{action "signOut"}}>Sign Out</a></li>
        {{else}}
        <li>{{#link-to "sign-up"}}Sign Up{{/link-to}}</li>
        <li>{{#link-to "sign-in"}}Sign In{{/link-to}}</li>
        {{/if}}
      </ul>
    </div>
  </div>
</nav>

<h1>Welcome to Ember!</h1>

{{#each flashMessages.queue as |flash|}}
  {{flash-message flash=flash}}
{{/each}}

{{#if isAuthenticated}}
{{#link-to "palette-create"}}Create New Palette{{/link-to}}
{{#link-to "palettes"}}My Palettes{{/link-to}}
{{/if}}

<div class="col-md-8 col-md-offset-2">
  {{outlet}}
</div>
```

... but I think this simply displays/hides the ```palettes``` and ```palette-create``` links depending on whether you'er signed in or not.

So then I checked routes/application.js: 
```js
import Ember from 'ember';

export default Ember.Route.extend({
  auth: Ember.inject.service(),
  flashMessages: Ember.inject.service(),
  actions: {
    signOut () {
      this.get('auth').signOut()
        .then(() => this.get('store').unloadAll())
        .then(() => this.transitionTo('sign-in'))
        .then(() => {
          this.get('flashMessages').warning('You have been signed out.');
        })
        .catch(() => {
          this.get('flashMessages')
          .danger('There was a problem. Are you sure you\'re signed-in?');
        });
    },

    error (reason) {
      let unauthorized = reason.errors && reason.errors.some((error) =>
        error.status === '401'
      );

      if (unauthorized) {
        this.get('flashMessages')
        .danger('You must be authenticated to access this page.');
        this.transitionTo('/sign-in');
      } else {
        this.get('flashMessages')
        .danger('There was a problem. Please try again.');
      }

      return false;
    },
  },
});
```

I see that the redirecting is happening in the 'error' action, but I can't find where this action is being referenced anywhere else in the project repository.

**Comment by danman01** [comment]
Does your API endpoint return a 401 error when not authenticated for `palettes/create`? Maybe that is what your routes catches on the front end and redirects the user appropriately

**Comment by nriser** [comment]
No, it does not.

**Comment by nriser** [comment]
Talked with @danman01 and came to a solution.

The solution (although Danny said it might not be the best solution) is to hit the backend API in the router model so that it triggers the ```error``` action in application.js (taken from the ember-auth class example). 

Here's an example router model:
```js
  model () {
    let hitApiToRedirectToSignIn = this.get('store').findAll('palette');
    return hitApiToRedirectToSignIn;
  },
```

error action in application.js
```js
error (reason) {
      let unauthorized = reason.errors && reason.errors.some((error) =>
        error.status === '401'
      );

      if (unauthorized) {
        this.get('flashMessages')
        .danger('You must be authenticated to access this page.');
        this.transitionTo('/sign-in');
      } else {
        this.get('flashMessages')
        .danger('There was a problem. Please try again.');
      }
```
