### ISSUE TITLE
Deployed version not working

### ISSUE THREAD

**Issue by jbeltrami** [ga-wdi-boston/capstone-project#696]
I'm using ROR and deploying to Heroku.
On the client side, when I try to run any functionality, I'm getting

```
XMLHttpRequest cannot load https://jb-management.herokuapp.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://jbeltrami.github.io' is therefore not allowed access. The response had HTTP status code 400.
```

Ran: `heroku config:set CLIENT_ORIGIN=https://jbeltrami.github.io` a few times, varying what comes after `=`, but no success so far.

Any ideas on how to fix that?

Thank you.

**Comment by MicFin** [comment]
`heroku config:set CLIENT_ORIGIN=https://jbeltrami.github.io`
and
`heroku restart`
