### ISSUE TITLE
Want to understand best Date format for ActiveRecord 

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/capstone-project#7]
My models are built, simple but built and are tested in Rails C, and the idea is that a User will have a Pet.  In that Pet they will be able to say the date of the last rabies, heartworm and tick medicine application.  Then this will reset a predetermined clock (saw a couple promising gems but they seem to involve views) and start a new countdown.

There are several options and I want to make sure I am utilizing the right type in order to accomplish the goals of the app.

I have looked into this for a couple hours and am just not finding the answers that click.

Thanks in advance.

my schema:
 create_table "pets", force: :cascade do |t|
    t.string   "name"
    t.string   "dob"
    t.date     "last_rabies"
    t.date     "last_tick"
    t.date     "last_heartworm"
    t.datetime "created_at",     null: false
    t.datetime "updated_at",     null: false
    t.integer  "user_id"
  end

**Comment by jrhorn424** [comment]
What's wrong with using a `date` type?

**Comment by jcmeyer10** [comment]
Nothing that I can see, just wanted to make sure I was following best practices when it came to dynamically integrating it later!

**Comment by jrhorn424** [comment]
I can't imagine this being a terrible choice. What did you have in mind for later? Specifically, I don't know what you mean by "dynamically integrating"?

**Comment by jcmeyer10** [comment]
The idea is that every 30 days (or 2 years for rabies) you have to give a dog certain meds to keep them happy and healthy.  I want a User to be able to change the date for the last x medicine, which will then start a countdown so the user knows the next time they need to give that medicine.

**Comment by jrhorn424** [comment]
Seems like `date` is the right choice.
