### ISSUE TITLE
Ember deployment guide

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/capstone-project#700]
It was mentioned last Thu or Fri that an Ember client deployment guide would be available.

We have the Ember client template(s). Do we still use `grunt deploy`? Or is there some other Ember-specific deployment guide?

**Comment by cpearce31** [comment]
https://git.generalassemb.ly/ga-wdi-boston/ember-deployment-guide

**Comment by EricLScace** [comment]
Thanks. Also saw Toni's push of the link in the Slack forum. Don't know what that did not show up in my Slack over the weekend...
