### ISSUE TITLE
Project 1:1 Request

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/capstone-project#702]
Hey All, 

I'd like to review my planning docs with you (linked below). I'm planning to build an ember/rails app based on the card game Set. This is a game where players find sets of 3 cards where each of attributes of the three cards is either all the same or all different. Version one will be a single player game. 

I'm most interested in discussing how to best organize ember routes, components and methods.

Thanks,

Matt

Game:
https://en.wikipedia.org/wiki/Set_(game)
ERD/App Diagram:
https://drive.google.com/file/d/0BxtpRPyddhwRdjVPSk4wSmt6M3M/view?usp=sharing
Wireframe:
https://drive.google.com/file/d/0BxtpRPyddhwRTGtzdFFuMHFUVzA/view?usp=sharing
Components Diagram:
https://drive.google.com/file/d/0BxtpRPyddhwRZzNsaTlQc253bms/view?usp=sharing
Card data:
https://docs.google.com/spreadsheets/d/1e9FEer-k-9zQy5ozUzHObaozEdF9c5QZqdHV-CF070Y/edit?usp=sharing

**Comment by cpearce31** [comment]
We will be scheduling 1:1s for everyone shortly, we'll keep you posted!

**Comment by artpylon** [comment]
Met with @sdavidson140 this morning. Will re-convene tomorrow.
