### ISSUE TITLE
I am confused about the table i will be making on the backend 

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/capstone-project#704]

**Comment by cpearce31** [comment]
Can you provide a little more info about what you're trying to do?

**Comment by isharma-sharma** [comment]
I m trying to make a kidz school website   so i am having confusion  which
table will be referred to which one  and how any table to make

**Comment by cpearce31** [comment]
What information will your app be keeping track of?

**Comment by isharma-sharma** [comment]
i want two login one for the administrator who can view each details who
can populate teachers table and other the parents who can view information
regarding their students one table for request call back one table for fees

**Comment by cpearce31** [comment]
Did your 1:1 clarify this for you at all?

**Comment by isharma-sharma** [comment]
how can i add column to my users table

bin/rails generate migration add_name_to_users  name:string;

is creating new migration file, not adding column to my users table

**Comment by cpearce31** [comment]
Did you run `bin/rake db:migrate` after generating the migration?

**Comment by isharma-sharma** [comment]
i wss forgetting the :
