### ISSUE TITLE
Rails - Unable to seed data - csv file not found.

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/capstone-project#707]
I am attempting to populate a table I've created called cards with data from a csv file that I've stored in my repo cards cards.csv. 

In my db/seeds.rb file I've created this function:

```ruby
require 'csv'

csv_text = File.read('./cards.csv')
csv = CSV.parse(csv_text, :headers => true)
csv.each do |row|
  Card.create!(row.to_hash)
end
```
I've stored the cards.csv in the db folder.

In the terminal I am running this command:

bin/rails db:seed 

This is the output:

```
$ bin/rake db:seed
Running via Spring preloader in process 30938
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - ./cards.csv
/Users/matthewgray/wdi/projects/splice_backend/db/seeds.rb:13:in `read'
/Users/matthewgray/wdi/projects/splice_backend/db/seeds.rb:13:in `<top (required)>'
-e:1:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
~/wdi/projects/splice_backend (games)
```
I've tried various versions of the file path here, such as 'cards.csv' and './cards.csv' but it can't seem to find it.

**Comment by artpylon** [comment]
Also tried this: 

changed the require to include the file name, i.e.:

```
require 'cards.csv'
```
Then, ran bin/rake db:seed again and this was the output (a different error):
```
$ bin/rake db:seed
Running via Spring preloader in process 31085
rake aborted!
LoadError: cannot load such file -- cards.csv
/Users/matthewgray/wdi/projects/splice_backend/db/seeds.rb:11:in `<top (required)>'
-e:1:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Comment by cpearce31** [comment]
Path literals don't always work the way you'd expect in Rails, but there's a built-in method to deal with it. Check this out: https://stackoverflow.com/questions/3724487/rails-root-directory-path

**Comment by artpylon** [comment]
Sweet, thanks! This worked:

```ruby
require 'csv'

csv_text = File.read(Rails.root.join('db', 'cards.csv'))
csv = CSV.parse(csv_text, :headers => true)
csv.each do |row|
  Card.create!(row.to_hash)
end
```
