### ISSUE TITLE
Trouble deploying to Heroku

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/capstone-project#71]
~/WDI/Project-4/petminder-backend (master)$ RAILS_ENV=production bundle exec rake db:create
FATAL:  role "project4-api" does not exist
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/

Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"project4-api_production", "username"=>"project4-api", "password"=>nil}

**Comment by GA-MEB** [comment]
Are you working through my walkthrough repo? It looks like you may have missed a step: setting up a new role in Postgres.

**Comment by jcmeyer10** [comment]
Yes I am and I tried to follow the steps exactly, I saw CREATE ROLE and then \q and then ran the RAILS_ENV

**Comment by jcmeyer10** [comment]
JeffMeyer=# create role "desolate-beach-8919" login createdb;
CREATE ROLE

**Comment by jcmeyer10** [comment]
I change the database from project2-api to project4-api, would that matter?

**Comment by jcmeyer10** [comment]
Postgres Console

```
postgres=# create role <local app_name (NOT HEROKU APP NAME)> login createdb;
postgres=# \q
```

This will create the proper role.
