### ISSUE TITLE
allthemats v0.2: user story, wireframes, ERD, development plan

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/capstone-project#710]
* [User story](https://github.com/EricLScace/allthemats-ember/wiki/user-stories)
* [v0.2 UX flow diagram](https://raw.githubusercontent.com/wiki/EricLScace/allthemats-ember/ux-flow-v0-2.png)
* [Wireframe for matrix code search](https://raw.githubusercontent.com/wiki/EricLScace/allthemats-ember/wireframe-v0-2-1.png)
* [Wireframe for typographical attribute search](https://raw.githubusercontent.com/wiki/EricLScace/allthemats-ember/wireframe-v0-2-4.png]
* [Updated ERD & discussion](https://github.com/EricLScace/All-the-Matrices-back-end/wiki/v0-2-tables)
* [Development plan](https://github.com/EricLScace/allthemats-ember/wiki/schedule)

For additional documentation, see:
* [Ember client wiki](https://github.com/EricLScace/allthemats-ember/wiki)
* [server wiki](https://github.com/EricLScace/All-the-Matrices-back-end/wiki)

**Comment by EricLScace** [comment]
Still need to update the API documentation for v0.2... after lunch!

**Comment by EricLScace** [comment]
[Full API documentation here](https://github.com/EricLScace/All-the-Matrices-back-end/wiki/v0-2-api-intro)

**Comment by scottyscripts** [comment]
@EricLScace Great documentation as always, did you need further assistance here following your 1 on 1??

**Comment by EricLScace** [comment]
Not on this issue — just using it to post compliance with project requirements.

**Comment by jordanallain** [comment]
@EricLScace  cool as long as they make it to your readme you can close this issue!

**Comment by EricLScace** [comment]
ok
