### ISSUE TITLE
Question about generation of rails resources

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/capstone-project#711]
For my capstone, I am making an arts listing app.  I'm going to have the following resources/relationships: 

Users ----|----< Shows (Users have many shows)
Galleries ---|---< Shows (Galleries have many shows)

The /users resource is already set up, of course. But here's my question: what is the right way to set up Shows and Galleries? 

I *think* that I am creating a many to many relationship where 'galleries' acts like a join table. 

I am reading the [following repo from our lesson Rails Many to Many as a resource](https://git.generalassemb.ly/lisawilliams/rails-api-many-to-many#join-tables). 

If I am correct, I think I will be running: 

For an individual art show:
`bin/rails generate scaffold show date:date time:time show_name:string description:string`

For a gallery:
`bin/rails generate scaffold gallery user:references show:references date:datetime gallery_name:string address:string phone:string website:string`

Blink twice if you think I am headed in the right direction. 
Send scary ghost emoji if I am headed for trouble. And maybe some ideas about a better approach after the emoji.

**Comment by cpearce31** [comment]
If I'm understanding right, galleries and users each have many shows, but each show has exactly one user and one gallery. In that case, don't you want the foreign key references to both be in the shows table?

**Comment by scottyscripts** [comment]
@lisawilliams Any updates on this issue?

**Comment by tvcrawley** [comment]
@lisawilliams ☝️

**Comment by lisawilliams** [comment]
Hi guys! I currently have a `user` and `shows` resource that are connected via a foreign key relationship. If it's okay with you, I'd like to leave this open because I'd like to add one more resource -- `gallery`. If that goes well, I'll close this issue; if not, this can be a placeholder.

**Comment by scottyscripts** [comment]
@lisawilliams any updates on this?

**Comment by lisawilliams** [comment]
OK friends! I have completed the front & back end for: `users` and `shows`. 

I want this project to have a third Rails resource.  Initially, I thought that resource would be `gallery`, but now I'm not so sure. I actually think details about the gallery belong in the `show` object.  Perhaps it would be better to have: 

Users ---|--< Shows ---|--< Artists 

If so, is it possible for me to update my `shows` resource to include details about the gallery the art show is being held at (gallery name, location, etc?) .

**Comment by benjimelito** [comment]
Yes, you should be able to do this by running a new migration in the rails console. I would recommend looking up the syntax, but it should be something like `rails generate migration AddColumnsToShows location:string gallery_name:string ...`

**Comment by lisawilliams** [comment]
Awesome, thanks, Ben. What do you think about "shows have many artists"? Doesn't sound too insane to me.

**Comment by benjimelito** [comment]
Nope, not insane at all 🙃

**Comment by lisawilliams** [comment]
OK I'm going to close this :D
