### ISSUE TITLE
Question about proper way to set up two related Rails resources

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/capstone-project#712]
For my capstone, I am making an arts listing app.  I'm going to have the following resources/relationships: 

Users ----|----< Shows (Users have many shows)
Galleries ---|---< Shows (Galleries have many shows)

The /users resource is already set up, of course. But here's my question: what is the right way to set up Shows and Galleries? 

I *think* that I am creating a many to many relationship where 'galleries' acts like a join table. 

I am reading the [following repo from our lesson Rails Many to Many as a resource](https://git.generalassemb.ly/lisawilliams/rails-api-many-to-many#join-tables). 

If I am correct, I think I will be running: 

For an individual art show:
`bin/rails generate scaffold show date:date time:time show_name:string description:string`

For a gallery:
`bin/rails generate scaffold gallery user:references show:references date:datetime gallery_name:string address:string phone:string website:string`

Blink twice if you think I am headed in the right direction. 
Send scary ghost emoji if I am headed for trouble. And maybe some ideas about a better approach after the emoji.

**Comment by benjimelito** [comment]
So I think you will need a join table, but I don't know if galleries is the right way to phrase it. As I see it, users will have many shows and shows will have many users. Maybe a third table called "user_shows" would be appropriate, and you could have a foreign key on each show that would point to a gallery.

**Comment by lisawilliams** [comment]
Thanks, Ben!

**Comment by benjimelito** [comment]
Let me know if you have any questions about how this should be set up, but I believe this schema should work for your purposes

**Comment by lisawilliams** [comment]
(Just leaving this open temporarily while I work on a number of other things. I plan to set up my resources in the morning. If it works I'll close it!)

**Comment by scottyscripts** [comment]
@lisawilliams How is this going?

**Comment by lisawilliams** [comment]
Update: I've successfully created a `shows` resource with the following schema: 

  create_table "shows", force: :cascade do |t|
    t.string   "show_name"
    t.date     "show_date"
    t.time     "show_time"
    t.text     "notes"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

I *think* that my next move is to create a Users -- have many -- Shows; Shows -- belong to -- Users relationship.  I ran the following command: 

`bin/rails generate migration AddUserToShows user:references` . 

which created the following migration file, which I have **NOT** run yet: 

```
class AddUserToShows < ActiveRecord::Migration[5.0]
  def change
    add_reference :shows, :user, foreign_key: true
  end
end
```
Does this look like the right direction?

**Comment by scottyscripts** [comment]
If you are trying to create a `has_many` relationship with `Users` having many `Shows` then you are headed in the right direction! Is galleries still a resource you are using? What is your current ERD looking like?

**Comment by lisawilliams** [comment]
I think I will -- I'm just doing things one at a time.  Another option for a third resource might be: 

Shows ----|---< Artists

**Comment by lisawilliams** [comment]
If I did galleries, we would have: 

Galleries ----|----< Shows

Which seems a little confusing...I'm not quite sure how to take that and create a listing for a single show, for example, that shows the show's information (show title, date, time, notes) and the gallery information (gallery name, location, website).

**Comment by scottyscripts** [comment]
Excellent, great that you are being methodical, one step at a time. So like I said for the issue at hand, If your goal is to create a users has_many shows relationship in your database, run that migration! Don't forget to set up the relationship in your model as well

**Comment by lisawilliams** [comment]
Yup, right now I have: 

`show.rb`: 

```
class Show < ApplicationRecord
  belongs_to :user
end
```
and `user.rb`:
```
# frozen_string_literal: true
class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_many :shows
end
```

**Comment by scottyscripts** [comment]
Looks good!

**Comment by lisawilliams** [comment]
This migration ran successfully and produced the expected results (it created a foreign key column of `user_id` on the `shows` table: 

<img width="601" alt="screen shot 2017-07-18 at 3 03 37 pm" src="https://user-images.githubusercontent.com/809042/28334820-4f0174d0-6bca-11e7-808b-0b38a64373ef.png">

Closing issue!
