### ISSUE TITLE
Ember - route does not make request for cards

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/capstone-project#713]
I have setup a route and model for 'game', this should index both /games and /cards endpoints, however only a /games request is being made.

games and cards should each return an array of objects. I found a stackoverflow post that indicates I can include an array as a datatype in my model but simply not specifying the type:
https://stackoverflow.com/questions/14879013/ember-js-array-as-models-property

routes/game.js

```ember
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    const games = this.get('store').findAll('game');
    const cards = this.get('store').findAll('card');
    return {games: games, cards: cards}
  },
});
```

modes/game.js
```ember
import DS from 'ember-data';

export default DS.Model.extend({
  games: DS.attr(),
  cards: DS.attr()
});
```

**Comment by cpearce31** [comment]
I think you need separate models for `games` and `cards`, since they come from different API endpoints. Also, this is apparently the official Ember approach to loading multiple models in one model hook:
https://guides.emberjs.com/v2.2.0/routing/specifying-a-routes-model/#toc_multiple-models

**Comment by artpylon** [comment]
Thank you. This worked:

```ember
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return Ember.RSVP.hash({
      games: this.store.findAll('game'),
      cards: this.store.findAll('card')
    });
  },
});
```
