### ISSUE TITLE
not able to add column of reference  to student table

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/capstone-project#714]
according to table students belongs to users 
`````
bin/rails generate migration students references:users
 is not  adding the column of reference id on students table

**Comment by isharma-sharma** [comment]
bin/rails generate migration ADDUSERTOSTUDENTS user:references

**Comment by isharma-sharma** [comment]
this also didnt work

**Comment by cpearce31** [comment]
What happens when you run `bin/rake db:migrate`? Do you get an error? Can you post the contents of the generated migration?

**Comment by isharma-sharma** [comment]
Running via Spring preloader in process 48139
Expected string default value for '--serializer'; got true (boolean)
      invoke  active_record
      create    db/migrate/20170717191301_addusertostudents.rb
~/wdi/kidsproject4/kids-school-backend (master)
$ bin/rails db:migrate
== 20170717191301 Addusertostudents: migrating ================================
== 20170717191301 Addusertostudents: migrated (0.0000s) =======================

**Comment by isharma-sharma** [comment]
this is my migration file
```
class Addusertostudents < ActiveRecord::Migration[5.0]
  def change
  end
end

**Comment by cpearce31** [comment]
It looks like the migration is not getting generated correctly, since there's no change specified in the migration. This StackOverflow has the right syntax for generating that migration: https://stackoverflow.com/questions/22815009/add-a-reference-column-migration-in-rails-4

**Comment by isharma-sharma** [comment]
i used the same i ran bin/rails db:migrate also

**Comment by isharma-sharma** [comment]
is their any other command to follow to create references

**Comment by jordanallain** [comment]
> references:users

you had these flipped, references should be to the right of the colon and user should be singular. have you progressed with this?
