### ISSUE TITLE
ember - Unable to import ember-lodash addon to component js file

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/capstone-project#716]
I need a shuffle method to randomize an array, so I found the lodash package for ember and installed it. Then, I imported it in the game-board.js component file. However, I'm getting errors in console saying that it cannot find this module.

I followed the installation steps here:
https://www.npmjs.com/package/ember-lodash

game-board.js file:
```ember
import Ember from 'ember';
import _ from 'lodash';

export default Ember.Component.extend({
  deck: Ember.computed('model.cards', function(){
    return _.shuffle(this.get('model.cards'));
  })
});
```

**Comment by artpylon** [comment]
<img width="1058" alt="screen shot 2017-07-17 at 9 01 11 pm" src="https://user-images.githubusercontent.com/26583372/28295993-1aa642e8-6b33-11e7-8cd3-5a76001107b2.png">

**Comment by MicFin** [comment]
Adding an entire library just to shuffle an array seems excessive.  You should be try to write your own JS function to shuffle for you.
https://stackoverflow.com/questions/2450954/how-to-randomize-shuffle-a-javascript-array

**Comment by artpylon** [comment]
Sound good.

**Comment by payne-chris-r** [comment]
To be clear, I'm totally happy helping you figure this out! Just make sure the essential pieces are done first, and consider the cost/benefit of importing lodash vs. writing your own!
