### ISSUE TITLE
Deploying to heroku - questions

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/capstone-project#72]
1- in my .env file (yes I put .env in .gitignore) is there a '#' after the SECRET_KEY_BASE?
2 - should i set my config_serve_static_files = true in my config produciton.rb?

**Comment by LaurisaNeuwirth** [comment]
my app is called freshEX
is this line correct:
'create role freshEX login createdb;'

I am unsure about the 'createb' part

**Comment by LaurisaNeuwirth** [comment]
I got an error: Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"freshex_production", "username"=>"freshex_app", "password"=>nil}

I had put in 'create role freshEX login createdb;' (w/out the ticks) but maybe createdb wasn't right?

**Comment by LaurisaNeuwirth** [comment]
should it be:
'create role <freshEX> login createdb;'
?

**Comment by GA-MEB** [comment]
1 - No, that `#` is there to create a comment.

**Comment by GA-MEB** [comment]
2 - You ran that line from within the `postgres` database, right? 

You might need to put quotes around the name, since you've got capital letters. i.e.
`create role "freshEX" login createdb;`

**Comment by LaurisaNeuwirth** [comment]
Ok I am past that now. When I run foreman start, it looks like a server running and I tested my app at http://localhost:3000/events. It all works. Is there anything else I do to test?

**Comment by GA-MEB** [comment]
Nope, that's it. If everything's working locally, go ahead and push to Heroku.

**Comment by LaurisaNeuwirth** [comment]
error: failed to push some refs to 'https://git.heroku.com/tranquil-fortress-6307.git'

I searched gemfile and gemfile.lock and do not have sqlite3 anywhere

**Comment by LaurisaNeuwirth** [comment]
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/tranquil-fortress-6307.git'

**Comment by LaurisaNeuwirth** [comment]
An error occurred while installing sqlite3 (1.3.11), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install sqlite3 -v '1.3.11'` succeeds before bundling.
remote:  !
remote:  !     Failed to install gems via Bundler.

**Comment by LaurisaNeuwirth** [comment]
I searched my whole repo for 'sqlite3' and got this error:

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
remote:        /tmp/build_eba9fb1a9cf2e4b53ef263cab33bd0e2/vendor/ruby-2.0.0/bin/ruby extconf.rb
remote:        checking for sqlite3.h... no
remote:        sqlite3.h is missing. Try 'port install sqlite3 +universal',
remote:        'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
remote:        and check your shared library search path (the
remote:        location where your sqlite3 shared library is located).
remote:        **\* extconf.rb failed ***
remote:        Could not create Makefile due to some reason, probably lack of necessary
remote:        libraries and/or headers.  Check the mkmf.log file for more details.  You may
remote:        need configuration options.
remote:        Provided configuration options:
remote:        --with-opt-dir
remote:        --without-opt-dir
remote:        --with-opt-include
remote:        --without-opt-include=${opt-dir}/include
remote:        --with-opt-lib
remote:        --without-opt-lib=${opt-dir}/lib
remote:        --with-make-prog
remote:        --without-make-prog
remote:        --srcdir=.
remote:        --curdir
remote:        --ruby=/tmp/build_eba9fb1a9cf2e4b53ef263cab33bd0e2/vendor/ruby-2.0.0/bin/ruby
remote:        --with-sqlite3-dir
remote:        --without-sqlite3-dir
remote:        --with-sqlite3-include
remote:        --without-sqlite3-include=${sqlite3-dir}/include
remote:        --with-sqlite3-lib
remote:        --without-sqlite3-lib=${sqlite3-dir}/
remote:        Gem files will remain installed in /tmp/build_eba9fb1a9cf2e4b53ef263cab33bd0e2/vendor/bundle/ruby/2.0.0/gems/sqlite3-1.3.11 for inspection.
remote:        Results logged to /tmp/build_eba9fb1a9cf2e4b53ef263cab33bd0e2/vendor/bundle/ruby/2.0.0/gems/sqlite3-1.3.11/ext/sqlite3/gem_make.out
remote:        An error occurred while installing sqlite3 (1.3.11), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install sqlite3 -v '1.3.11'` succeeds before bundling.
remote:        Bundler Output: Fetching gem metadata from https://rubygems.org/...........
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Rubygems 2.0.14.1 is not threadsafe, so your gems must be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
remote:        Installing rake 10.4.2
remote:        Installing i18n 0.7.0
remote:        Installing json 1.8.3
remote:        Installing minitest 5.8.3
remote:        Installing thread_safe 0.3.5
remote:        Installing tzinfo 1.2.2
remote:        Installing activesupport 4.2.4
remote:        Installing builder 3.2.2
remote:        Installing erubis 2.7.0
remote:        Installing mini_portile2 2.0.0
remote:        Installing nokogiri 1.6.7
remote:        Installing rails-deprecated_sanitizer 1.0.3
remote:        Installing rails-dom-testing 1.0.7
remote:        Installing loofah 2.0.3
remote:        Installing rails-html-sanitizer 1.0.2
remote:        Installing actionview 4.2.4
remote:        Installing rack 1.6.4
remote:        Installing rack-test 0.6.3
remote:        Installing actionpack 4.2.4
remote:        Installing globalid 0.3.6
remote:        Installing activejob 4.2.4
remote:        Installing mime-types 2.99
remote:        Installing mail 2.6.3
remote:        Installing actionmailer 4.2.4
remote:        Installing activemodel 4.2.4
remote:        Installing arel 6.0.3
remote:        Installing activerecord 4.2.4
remote:        Installing coffee-script-source 1.10.0
remote:        Installing execjs 2.6.0
remote:        Installing coffee-script 2.4.1
remote:        Installing thor 0.19.1
remote:        Installing railties 4.2.4
remote:        Installing coffee-rails 4.1.0
remote:        Installing concurrent-ruby 1.0.0
remote:        Installing multi_json 1.11.2
remote:        Installing jbuilder 2.3.2
remote:        Installing jquery-rails 4.0.5
remote:        Using bundler 1.9.7
remote:        Installing sprockets 3.5.2
remote:        Installing sprockets-rails 2.3.3
remote:        Installing rails 4.2.4
remote:        Installing rdoc 4.2.0
remote:        Installing sass 3.4.20
remote:        Installing tilt 2.0.1
remote:        Installing sass-rails 5.0.4
remote:        Installing sdoc 0.4.1
remote:  
remote:        Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
remote:  
remote:        /tmp/build_eba9fb1a9cf2e4b53ef263cab33bd0e2/vendor/ruby-2.0.0/bin/ruby extconf.rb
remote:        checking for sqlite3.h... no
remote:        sqlite3.h is missing. Try 'port install sqlite3 +universal',
remote:        'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
remote:        and check your shared library search path (the
remote:        location where your sqlite3 shared library is located).
remote:        **\* extconf.rb failed ***
remote:        Could not create Makefile due to some reason, probably lack of necessary
remote:        libraries and/or headers.  Check the mkmf.log file for more details.  You may
remote:        need configuration options.
remote:  
remote:        Provided configuration options:
remote:        --with-opt-dir
remote:        --without-opt-dir
remote:        --with-opt-include
remote:        --without-opt-include=${opt-dir}/include
remote:        --with-opt-lib
remote:        --without-opt-lib=${opt-dir}/lib
remote:        --with-make-prog
remote:        --without-make-prog
remote:        --srcdir=.
remote:        --curdir
remote:        --ruby=/tmp/build_eba9fb1a9cf2e4b53ef263cab33bd0e2/vendor/ruby-2.0.0/bin/ruby
remote:        --with-sqlite3-dir
remote:        --without-sqlite3-dir
remote:        --with-sqlite3-include
remote:        --without-sqlite3-include=${sqlite3-dir}/include
remote:        --with-sqlite3-lib
remote:        --without-sqlite3-lib=${sqlite3-dir}/
remote:  
remote:  
remote:        Gem files will remain installed in /tmp/build_eba9fb1a9cf2e4b53ef263cab33bd0e2/vendor/bundle/ruby/2.0.0/gems/sqlite3-1.3.11 for inspection.
remote:        Results logged to /tmp/build_eba9fb1a9cf2e4b53ef263cab33bd0e2/vendor/bundle/ruby/2.0.0/gems/sqlite3-1.3.11/ext/sqlite3/gem_make.out
remote:        An error occurred while installing sqlite3 (1.3.11), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install sqlite3 -v '1.3.11'` succeeds before bundling.
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !  
remote:  !     Detected sqlite3 gem which is not supported on Heroku.
remote:  !     https://devcenter.heroku.com/articles/sqlite3
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
remote: Verifying deploy...
remote: 
remote: !   Push rejected to tranquil-fortress-6307.
remote: 
To https://git.heroku.com/tranquil-fortress-6307.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/tranquil-fortress-6307.git'
