### ISSUE TITLE
i am not able to runt the curl script of request

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/capstone-project#721]
below is my curl request
`````````
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/examples"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "request": {
      "name": "'"${NAME}"'",
       "telephone": "'"${TELEPHONE}"'",
        "email": "'"${EMAIL}"'"
    }
  }'
````````
below is my error
`````
~/wdi/kidsproject4/kids-school-backend (master)
$ NAME=pooja TELEPHONE=1234 EMAIL=t@gmail scripts/createrequest.sh 
-bash: scripts/createrequest.sh: Permission denied

**Comment by isharma-sharma** [comment]
do i need token , but i don't want the person writing the request should sign-up or sign-in
and want the admin 0r teacher to see the request

**Comment by isharma-sharma** [comment]
the same problem i am facing for student table

**Comment by jordanallain** [comment]
is the file executable? what is the output of `ls -l scripts/`

**Comment by isharma-sharma** [comment]
HTTP/1.1 401 Unauthorized
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
WWW-Authenticate: Token realm="Application"
Content-Type: text/plain; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 373b1de3-4706-4319-b2db-5ce5074a57b5
X-Runtime: 0.342014
Vary: Origin
Transfer-Encoding: chunked

HTTP Token: Access denied.

**Comment by scottyscripts** [comment]
make sure you are using `sh` before file name!

**Comment by isharma-sharma** [comment]
on my server i m getting`````````
Started POST "/examples" for 127.0.0.1 at 2017-07-18 09:12:25 -0400
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by ExamplesController#create as */*
  Parameters: {"request"=>{"name"=>"pooja", "telephone"=>"12345", "email"=>"p@gmail"}}
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.1ms | ActiveRecord: 0.0ms)

`````````
why my examples is getting invoked

**Comment by isharma-sharma** [comment]
why iam getting unprocessable entity

``````
sh scripts/create-request.sh 
HTTP/1.1 422 Unprocessable Entity
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 003d7db7-483d-4578-98ab-8627bd638550
X-Runtime: 0.063020
Vary: Origin
Transfer-Encoding: chunked

`````

**Comment by isharma-sharma** [comment]
my latest error msg by running curl

`````$ sh scripts/create-request.sh 
HTTP/1.1 422 Unprocessable Entity
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 003d7db7-483d-4578-98ab-8627bd638550
X-Runtime: 0.063020
Vary: Origin
Transfer-Encoding: chunked

{"user":["must exist"]}
``````
below is my rails server output
`````
Started POST "/requests" for 127.0.0.1 at 2017-07-18 09:35:28 -0400
Processing by RequestsController#create as */*
  Parameters: {"request"=>{"name"=>"pooja", "telephone"=>"12345", "email"=>"p@gmail"}}
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.17ms)
Completed 422 Unprocessable Entity in 60ms (Views: 4.8ms | ActiveRecord: 4.7ms)
``````
and i checked my table also 
no field is filled

**Comment by jordanallain** [comment]
```sh
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/examples"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "request": {
      "name": "'"${NAME}"'",
       "telephone": "'"${TELEPHONE}"'",
        "email": "'"${EMAIL}"'"
    }
  }'
```
```sh
{"user":["must exist"]}
```


You are naming the data object `request` but it should be `user`

**Comment by isharma-sharma** [comment]
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/requests"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "user": {
      "name": "pooja",
       "telephone": "12345",
        "email": "p@gmail"
    }
  }'

```````
will this fill up my request table or overwrite my users table

**Comment by isharma-sharma** [comment]
i did it gave me 400 bad request

**Comment by jordanallain** [comment]
what are you trying to do with the curl script?

**Comment by isharma-sharma** [comment]
yes

**Comment by jordanallain** [comment]
no, what are you trying to do? one of the scripts you posted was a POST to /examples and another was a POST to /requests. what is it that you are trying to do?

**Comment by isharma-sharma** [comment]
i was making mistake earlier but i have posted you my right curl script sending you again


API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/requests"
curl "${API}${URL_PATH}" 
--include 
--request POST 
--header "Content-Type: application/json" 
--data '{
"user": {
"name": "pooja",
"telephone": "12345",
"email": "p@gmail"
}
}'

**Comment by isharma-sharma** [comment]
and error i m getting are below 

HTTP/1.1 422 Unprocessable Entity
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 003d7db7-483d-4578-98ab-8627bd638550
X-Runtime: 0.063020
Vary: Origin
Transfer-Encoding: chunked

{"user":["must exist"]}
below is my rails server output

Started POST "/requests" for 127.0.0.1 at 2017-07-18 09:35:28 -0400
Processing by RequestsController#create as */*
  Parameters: {"request"=>{"name"=>"pooja", "telephone"=>"12345", "email"=>"p@gmail"}}
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.17ms)
Completed 422 Unprocessable Entity in 60ms (Views: 4.8ms | ActiveRecord: 4.7ms)
and i checked my table also

**Comment by isharma-sharma** [comment]
i deleted my references to the users because it was not needed    


thankyou  Scott
