### ISSUE TITLE
Ember load fails to include assets, yet they are on the gh-pages branch

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/capstone-project#726]
<img width="1066" alt="screen shot 2017-07-18 at 11 35 59" src="https://user-images.githubusercontent.com/6785602/28325984-64436802-6bad-11e7-91d7-632a488891ae.png">

<img width="837" alt="screen shot 2017-07-18 at 11 37 57" src="https://user-images.githubusercontent.com/6785602/28326044-9acb0326-6bad-11e7-9ed4-7173eb5a0133.png">

GitHub configured to deploy from gh-pages.

**Comment by jordanallain** [comment]
how are they referenced in your code?

**Comment by jordanallain** [comment]
wait sorry disregard that question.

**Comment by EricLScace** [comment]
Hmm... Well, of course it works on localhost.

index.html
```html
    <link rel="stylesheet" href="{{rootURL}}assets/vendor.css">
    <link rel="stylesheet" href="{{rootURL}}assets/allthemats.css">
```

config/environment.js
```js
  const ENV = {
    modulePrefix: 'allthemats',
    environment: environment,
    rootURL: '/',
...
  if (environment === 'production') {
    ENV.rootURL = '/EricLScace/allthemats-ember';
    ENV.locationType = 'hash';
    ENV.apiHost = 'https://allthemats.herokuapp.com';
  }
```

**Comment by EricLScace** [comment]
Changing ENV.rootURL to = `'ericlscace.github.io/allthemats-ember'`

and retesting...

**Comment by jordanallain** [comment]
are you deploying from development branch or master?

**Comment by EricLScace** [comment]
from gh-pages branch, which was branched from master.

and the ENV.rootURL isn't the problem, looking back at the error messages on console.log

**Comment by jordanallain** [comment]
i believe it should only be /allthemats-ember

**Comment by EricLScace** [comment]
master was rebased off development anyhow.

**Comment by EricLScace** [comment]
ok will try that

**Comment by EricLScace** [comment]
Left out 2 steps in the tedious build process before. Fixed. https://ericlscace.github.io/allthemats-ember/
