### ISSUE TITLE
CSV not seeding correctly?

### ISSUE THREAD

**Issue by RoryEnright** [ga-wdi-boston/capstone-project#727]
I tried to follow along with https://github.com/ga-wdi-boston/capstone-project/issues/707
CSV file is named 4KBagger.csv
seeds.rb code
```
require 'csv'

csv_text = File.read(Rails.root.join('db', '4KBagger.csv'))
csv = CSV.parse(csv_text, :headers => true)
csv.each do |row|
  Mountain.create!(row.to_hash)
end
```
It looks like it ran without issue, but when I ``` bin/rails db ``` , ``` \d mountains ``` it doesn't look populated.
Also, my localhost:4741/mountains displayes ``` status: 500,
error: "Internal Server Error",
exception: "#<NoMethodError: undefined method `user' for #<Mountain:0x0055ba2c622398>>", ```
With a bunch of "traces" for errors.

**Comment by RoryEnright** [comment]
```
$ bin/rake db:seed
Running via Spring preloader in process 8074
~/wdi/capstone/back-end (scaffold)
$ 
```
This is the response from running the db:seed

**Comment by jordanallain** [comment]
are you referencing `user` in your mountains controller?

**Comment by RoryEnright** [comment]
only the user_id
```
    # Only allow a trusted parameter "white list" through.
    def mountain_params
      params.require(:mountain).permit(:name, :height, :user_id, :hike_id)
    end
end
```

**Comment by jordanallain** [comment]
what about the serializer

**Comment by scottyscripts** [comment]
can you post a sample of your CSV file (maybe the first ten lines including the headers

**Comment by RoryEnright** [comment]
```
class MountainSerializer < ActiveModel::Serializer
  attributes :id, :name, :height
  has_one :user
  has_one :hike
end
```
Hmm, this might be an error from a previous action.  I think I want ```has_many :hike``` and nothing for user.

**Comment by RoryEnright** [comment]
sample from CSV
```
name,height
Mount Adams,5774
Mount Bond,4698
Bondcliff,4265
"Mount Bond, West Peak",4540
Mount Cabot,4170
Cannon Mountain,4100
Mount Carrigain,4700
Carter Dome,4832
"Carter, Middle",4610
```

**Comment by jordanallain** [comment]
you need to reference your ERD to set this up correctly. do users have many hikes and hikes have many users?

**Comment by scottyscripts** [comment]
Is anything showing up in the `mountains` table at all? I have a hunch there is something wrong with the path you are giving File.read. This would make `csv_text` undefined. Try passing a relative path to `File.read`. So something like `File.read('../4KBagger.csv')` obviously replacing with your path to that file

**Comment by RoryEnright** [comment]
ERD:   users -|---< hikes >---|- mountains

**Comment by jordanallain** [comment]
is that, users have many mountains through hikes and mountains have many users through hikes?

**Comment by RoryEnright** [comment]
I was going for.  Users have many hikes and Mountains have many hikes.  Hikes would have ref to the user who created an instance of the hike, and also a ref to the mountain

**Comment by jordanallain** [comment]
so, users have many hikes, hikes belong to one user

and mountains have many hikes, hikes belong to one mountain?

**Comment by RoryEnright** [comment]
Yes

**Comment by jordanallain** [comment]
looks like you have `has_one` in your model ?

**Comment by RoryEnright** [comment]
Fixed some pre-existing issues with model/serializer.
The initial command had actually worked. I was looking in the wrong spot through the terminal.  I was running bin/rails db, \d mountains  which was only displaying the set up, not the actual table with data.

After using the ruby console (bin/rails console), Mountains.all displays the list imported from the CSV.
Thanks all!
