### ISSUE TITLE
CURL script for create Profile returns a 422 Unprocessable Entity

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/capstone-project#728]
Server shows following error:

Started POST "/profiles" for 127.0.0.1 at 2017-07-18 11:41:20 -0400
Processing by ProfilesController#create as */*
  Parameters: {"profile"=>{"user_name"=>"fun99", "about_me"=>"fun"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "63a5f01eaecec654e161d066b4593156"], ["LIMIT", 1]]
   (0.1ms)  BEGIN
   (0.2ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.09ms)
Completed 422 Unprocessable Entity in 26ms (Views: 4.5ms | ActiveRecord: 0.6ms)

Model 
```
class Profile < ApplicationRecord
  belongs_to :user

  validates :user_name, :user, presence: true
end 
```

Controller 
```
  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      render json: @profile, status: :created, location: @profile
    else
      render json: @profile.errors, status: :unprocessable_entity
    end
  end
```

CURL script
```
API="http://localhost:4741"
URL_PATH="/profiles"

curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
  --data '{
    "profile": {
      "user_name": "'"${NAME}"'",
      "about_me": "'"${ABOUT}"'"
    }
  }'

echo
```

TOKEN=BAhJIiU2M2E1ZjAxZWFlY2VjNjU0ZTE2MWQwNjZiNDU5MzE1NgY6BkVG--771a2cec8d90367fc2a2d5e83a57e65c15d6a852 NAME=fun99 ABOUT=fun sh scripts/profiles/create.sh

**Comment by jordanallain** [comment]
can you post the profile_params method?

**Comment by MarcyNash** [comment]
```
  def profile_params
      params.require(:profile).permit(:user_name, :about_me)
    end
end
```

**Comment by tvcrawley** [comment]
```rb
  validates :user_name, :user, presence: true
```

looks like `:user` is required upon the creation of a profile

**Comment by MarcyNash** [comment]
Only valid users can create a profile. Did I set up the profile model incorrectly?

Before running the Curl script I am logged in and expect to create a profile. I've modeled the profile using examples. Have I missed something?

**Comment by tvcrawley** [comment]
How does a profile know it has been created by the `current_user`?

**Comment by MarcyNash** [comment]
Oops.  Just changed the profile controller to 
```
def create
    @profile = current_user.profiles.build(profile_params)

    if @profile.save
      render json: @profile, status: :created, location: @profile
    else
      render json: @profile.errors, status: :unprocessable_entity
    end
  end
```
And create now works.

Thanks, Toni!
