### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by LaurenGrant** [ga-wdi-boston/capstone-project#73]
I am receiving the following error when I am typing the command "heroku run rake db:migrate" from my master branch. i.e. ~/WDI/Project-4/WDI-Capstone-Project-BE (master)$ heroku run rake db:migrate

error is long and pasted below but the lines it is referring to also talk about the ' config' that Matt helped me with where config had a weird symbol in front of it. That is fixed in my back end now. 

rake aborted!
NameError: undefined local variable or method `​ config' for #<Project2Api::Application:0x007ff3234e5458>
/app/config/environments/production.rb:68:in`block in <top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/railtie.rb:210:in `instance_eval'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/railtie.rb:210:in`configure'
/app/config/environments/production.rb:1:in `<top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in`require'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in`load_dependency'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:598:in`block (2 levels) in class:Engine'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:597:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:597:in`block in class:Engine'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in`run'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:44:in`each'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in`run_initializers'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/app/config/environment.rb:5:in`<top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in`block in require'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in`require'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:457:in`block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment

My document lines that this error is referring to is 

app/config/environments/production.rb:68

```
Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Code is not reloaded between requests.
  config.cache_classes = true

  # Eager load code on boot. This eager loads most of Rails and
  # your application in memory, allowing both threaded web servers
  # and those relying on copy on write to perform better.
  # Rake tasks automatically ignore this option for performance.
  config.eager_load = true

  # Full error reports are disabled and caching is turned on.
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = true

  # Enable Rack::Cache to put a simple HTTP cache in front of your application
  # Add `rack-cache` to your Gemfile before enabling this.
  # For large-scale production use, consider using a caching reverse proxy like
  # NGINX, varnish or squid.
  # config.action_dispatch.rack_cache = true

  # Disable serving static files from the `/public` folder by default since
  # Apache or NGINX already handles this.
  config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?


  # Specifies the header that your server uses for sending files.
  # config.action_dispatch.x_sendfile_header = 'X-Sendfile' # for Apache
  # config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect' # for NGINX

  # Force all access to the app over SSL, use Strict-Transport-Security, and use secure cookies.
  # config.force_ssl = true

  # Use the lowest log level to ensure availability of diagnostic information
  # when problems arise.
  config.log_level = :debug

  # Prepend all log lines with the following tags.
  # config.log_tags = [ :subdomain, :uuid ]

  # Use a different logger for distributed setups.
  # config.logger = ActiveSupport::TaggedLogging.new(SyslogLogger.new)

  # Use a different cache store in production.
  # config.cache_store = :mem_cache_store

  # Enable serving of images, stylesheets, and JavaScripts from an asset server.
  # config.action_controller.asset_host = 'http://assets.example.com'

  # Ignore bad email addresses and do not raise email delivery errors.
  # Set this to true and configure the email server for immediate delivery to raise delivery errors.
  # config.action_mailer.raise_delivery_errors = false

  # Enable locale fallbacks for I18n (makes lookups for any locale fall back to
  # the I18n.default_locale when a translation cannot be found).
  config.i18n.fallbacks = true

  # Send deprecation notices to registered listeners.
  config.active_support.deprecation = :notify

  # Use default logging formatter so that PID and timestamp are not suppressed.
  config.log_formatter = ::Logger::Formatter.new

  # Do not dump schema after migrations.
  config.active_record.dump_schema_after_migration = false

  config.paperclip_defaults = {
  :storage => :s3,
  s3_credentials: {
    bucket: ENV['S3_BUCKET_NAME'],
    access_key_id: ENV['AWS_ACCESS_KEY_ID'],
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  },
   :url =>':s3_domain_url',
   :path => '/:class/:attachment/:id_partition/:style/:filename'
  }

end
```

app/config/environment.rb:5:in

```
# Load the Rails application.
require File.expand_path('../application', __FILE__)

# Initialize the Rails application.
Rails.application.initialize!
```

**Comment by GA-MEB** [comment]
It might be another 'special character'  error  - everything else looks fine.

**Comment by GA-MEB** [comment]
Are you still on campus?

**Comment by LaurenGrant** [comment]
i am not. I can screen hero. That same  'special character'  was there when i checked those files but the same error appeared when i deleted it.

**Comment by LaurenGrant** [comment]
Still no progress on my end. Same error.

**Comment by jcmeyer10** [comment]
Did you add and commit those changes?  That was a problem for me.

**Comment by LaurenGrant** [comment]
Let me double check

**Comment by LaurenGrant** [comment]
I just added and committed. Same error. 

First line in the error references "Project2Api". I am not sure if that is messing things up or not. 

NameError: undefined local variable or method `​config' for #Project2Api::Application:0x007f6bc8eb4110

**Comment by GA-MEB** [comment]
@LaurenGrant I'm free now - can we connect on ScreenHero?

**Comment by LaurenGrant** [comment]
Scott helped me. Thanks!
