### ISSUE TITLE
button reloading on click, have event.preventDefault in code

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/capstone-project#731]
Function won't run on submit action, reloads instead.
Code:
```$('.create-book').on('submit', onCreateBook)``` jQuery
```const onCreateBook = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  event.preventDefault()
  api.createBook(data)
    .then(ui.createBookSuccess)
    .catch(ui.fail)
}``` js function

```<input class= "create-book" type="submit" class="btn btn-default button" name="submit" value="Add Book">``` input html

**Comment by tvcrawley** [comment]
Can you post all html for the input? (So if it's in a form post the form as well)

**Comment by ghost** [comment]
```       <form id="add-book" class="modal_form">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">Add a Book</h3>
              </div>

            <div class="modal-body">
              <div id="below-modal-title" class="form-group">
                <label>Title</label>
                <input type="text" name="book[title]" placeholder="Book Title" class="form-control folder-add" required="true">
              </div>

              <div class="form-group">
                <label>Author</label>

                <input type="text" name="book[author]" placeholder="Book Author" class="form-control name-add" required="true">
              </div>


              <div class="form-group">
                <label for="addTagNew">Add a Tag:</label>
                <select name="book[tag]" class="form-control" id="addTagRecommended">
                  <option value="Recommended">Recomended</option>
                  <option value="Not Recommended">Not Recommended</option>
                </select>
              </div>

              <div>
                <p class="errormsg"></p>
              </div>

            </div>
              <div class="modal-footer">
                <input class= "create-book" type="submit" class="btn btn-default button" name="submit" value="Add Book">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
              </div>

            </form>
```

**Comment by tvcrawley** [comment]
What is triggering the reload?

**Comment by ghost** [comment]
Think I have a wrong api reference so I will edit that and report back

**Comment by ghost** [comment]
Wasn't that, clicking  the button 'Add Book' triggers the reload

**Comment by ghost** [comment]
Data does not pass to the back end if that helps

**Comment by tvcrawley** [comment]
So it looks like 'Add Book' is the `input` originally referenced so let's answer some questions:

- What is the default function of an input of type submit when it is clicked? 
- What is the default function of a form upon submission?

**Comment by ghost** [comment]
Reloading?

**Comment by sdavidson140** [comment]
You are currently listening for a submit event on a form with a class of `create-book` in this line. 
`$('.create-book').on('submit', onCreateBook)`

However, in your html I don't see any form with a class of `create-book`
I do see a form with an id of `add-book`
So what should we really be listening for a submit event on?

**Comment by sdavidson140** [comment]
You are currently listening for a submit event on a form with a class of create-book in this line.
$('.create-book').on('submit', onCreateBook)

However, in your html I don't see any form with a class of create-book
I do see a form with an id of add-book
So what should we really be listening for a submit event on?

**Comment by ghost** [comment]
Thank you, I should have been referencing #add-book, I now get a 401 unauthorized error I will close this issue
