### ISSUE TITLE
Would like to change a Rails resource I generated & ran migration on. How should I do it?

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/capstone-project#732]
Hi, friends: 

I ran the following generate command, and it didn't have expected results: 

`bin/rails generate scaffold show show_name:string show_date:string show_time: time notes:text`

Here's the schema it generated:
```
  create_table "shows", force: :cascade do |t|
    t.string   "show_name"
    t.string   "show_date"
    t.string   "show_time"
    t.string   "time"
    t.text     "notes"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
```

What I would really like is something like: 

 ```
 create_table "shows", force: :cascade do |t|
    t.string   "show_name"
    t.date   "show_date"
    t.time   "show_time"
    t.text     "notes"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
```
Sadly, I also ran `$ bin/rails db:migrate`, so I now have a db that looks like this: 

Two questions: 1) How should I proceed if I want to change or delete and re-do the table?
2) I am using :date and :time from the [list of Rails model types I found here](https://stackoverflow.com/questions/3260345/list-of-rails-model-types) Is it worthwhile to use these, or is it simpler just to make them all strings? At some point I would like to be able to sort shows by date.

**Comment by tvcrawley** [comment]
If you want to "re-do" the schema, is there a way to go (or roll) back to modify the migration file with the correct info?

**Comment by lisawilliams** [comment]
** goes off to google ** Any thoughts on the use of :date and :time vs. :string?

**Comment by lisawilliams** [comment]
Aha! I knew this sounded familiar...
For any WDI cohort members in the far, far future, if you make a mistake generating a model and you want to roll back a migration, [here are the docs](http://edgeguides.rubyonrails.org/active_record_migrations.html#rolling-back).

**Comment by lisawilliams** [comment]
OK, I ran `$ bin/rails db:rollback` but I still have a table called `shows` in my db. Should I run db:nuke_pave to complete the process?

**Comment by tvcrawley** [comment]
Instead of nuking your db, try running the new migration and see what happens

**Comment by lisawilliams** [comment]
ok cool 👍

**Comment by lisawilliams** [comment]
oops sorry didn't intend to close with that comment...back in a minute....

**Comment by lisawilliams** [comment]
Oh, ok: update -- 
It didn't get rid of the table `shows` because I'd switch to the development branch, and the branch where I was working on creating the `show` resource hadn't been merged. I switched to the `issue#4` branch and reran `bin/rails db:rollback` and indeed, the `shows` table is now gone from the db.  `schema.rb` also has no reference to `shows`, which I think is good. 

However, controllers/shows_controller.rb, models/show.rb and the rest of the files created by the generate command still exist.  At this point, should I only run a `generate migration` command? I think the rest of the files will be OK, yes?

**Comment by tvcrawley** [comment]
If you want to keep `show` as a resource, then the controller and model files are necessary. If you want to create a `show` table in your database, then a migration is needed.

**Comment by lisawilliams** [comment]
Gotcha.

**Comment by lisawilliams** [comment]
Thank you for the assistance! Closing issue.
