### ISSUE TITLE
ember - Unsure how to identify the game to be deleted

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/capstone-project#733]
Background:
In my app, a 'game' record is used purely for stats and contains only sets_found and over properties. This will eventually allow me to displayed sets for found in the current game, lifetime sets for for the user and number of total games played. 

Issue:
After signing in, the user clicks button "Play Game", this creates a game record on in the backend. This is successful. The user may choose to click restart game button, this should delete the last game record they created and restart a new game. 

I am unsure how to identify the last game the user created. If I were using ajax, I would store the game information front the create call api response in a .then. I've tried this, but ember returns a syntax error. 

game route js file:
```ember
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return Ember.RSVP.hash({
      games: this.store.findAll('game'),
      cards: this.store.findAll('card')
    });
  },
  currentGame: {},
  actions: {
    validSet () {
    },
    createGame (game) {
      let gameRecord = this.get('store').createRecord('game', game);
      gameRecord.save()
        .then(response) {
          response.id = this.set('currentGame.id')
          response.sets_found = this.set('currentGame.sets_found')
          response.over = this.set('currentGame.over')
        };
    },
    deleteGame (game) {
      game.destroyRecord(this.get('currentGame.id'))
    },
  }
});

```

**Comment by jordanallain** [comment]
can you do something similar to we did way back in project 1? when you create the game if you could save a local instance of it you would know the ID number of it.

**Comment by artpylon** [comment]
I thought about that, but wouldn't the id be set by the api? Is there some way to know it without the api response?

**Comment by scottyscripts** [comment]
The only way you'll know the `id` of a game as it is in the database is by communicating with your API. Perhaps when you start a game on the browser, it does a `POST` to create a new game. Then you will have the id of that game, as Jordan said. (In this case, `data` about the game would be returned upon successful creation)

**Comment by artpylon** [comment]
In the code above, I attempted to add a .then() following the saving of the game record to what I think you're describing. I've updated this, but it's still returning an error that it cannot set undefined:

```ember
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return Ember.RSVP.hash({
      games: this.store.findAll('game'),
      cards: this.store.findAll('card')
    });
  },
  currentGame: {id:'', sets_found:'', over:''},
  actions: {
    validSet () {
    },
    createGame (game) {
      let gameRecord = this.get('store').createRecord('game', game);
      gameRecord.save()
        .then(function(response) {
          response.id = this.set('currentGame.id')
          response.sets_found = this.set('currentGame.sets_found')
          response.over = this.set('currentGame.over')
        });
    },
    deleteGame (game) {
      game.destroyRecord(this.get('currentGame.id'))
    },
    updateGame () {

    },
  }
});
```

**Comment by artpylon** [comment]
<img width="636" alt="screen shot 2017-07-18 at 2 29 54 pm" src="https://user-images.githubusercontent.com/26583372/28333324-9bdcac20-6bc5-11e7-8f9c-9731fe13631d.png">

**Comment by artpylon** [comment]
The response from the api looks like this in the console:
<img width="540" alt="screen shot 2017-07-18 at 2 33 34 pm" src="https://user-images.githubusercontent.com/26583372/28333507-20f55d26-6bc6-11e7-9d87-ed3373e80438.png">

**Comment by artpylon** [comment]
So, based on that I updated the response references in my create function, but the same error is still returned:

```ember
    createGame (game) {
      let gameRecord = this.get('store').createRecord('game', game);
      gameRecord.save()
        .then(function(response) {
          response.game.id = this.set('currentGame.id')
          response.game.sets_found = this.set('currentGame.sets_found')
          response.game.over = this.set('currentGame.over')
        });
```

**Comment by scottyscripts** [comment]
take a look at the syntax for `.set`. Are you sure you want to use `=` when you are using this method? https://www.emberjs.com/api/ember/2.14/classes/Ember.Object/methods/set?anchor=set

**Comment by artpylon** [comment]
ahhhh... ok, do I need a this.get('currentGame') to to get the property that's being set? Made this update, but returns error it cannot get property of undefined.

```ember
    createGame (game) {
      let gameRecord = this.get('store').createRecord('game', game);
      gameRecord.save()
        .then(function(response) {
          this.get('currentGame').set('currentGame', response.game)
          // response.game.sets_found = this.set('currentGame')
          // response.game.over = this.set('currentGame')
        });
        record.set("key", value);
```

**Comment by artpylon** [comment]
I made this update, but I'm sure how to identify that currentGame is the property I want to update, this returns error cannot 'get' property of undefined:

```ember
    createGame (game) {
      let gameRecord = this.get('store').createRecord('game', game);
      gameRecord.save()
        .then(function(response) {
          this.get('currentGame').set('currentGame', response.game)
          // response.game.sets_found = this.set('currentGame')
          // response.game.over = this.set('currentGame')
        });
        record.set("key", value);
    },
```

**Comment by scottyscripts** [comment]
from ember docs it looks like `record.set(key,value)` where record is your object. So after getting your object, call set with the first argument being the keyname (`id`), and the second argument being value (whatever the id is)

**Comment by artpylon** [comment]
The record I want to update is currentGame, so I'm trying to call this.get('currentGame') then set the value on it, but I believe the get is what isn't being recognized here:

```
this.get('currentGame').set('id', response.game.id)
```

**Comment by artpylon** [comment]
<img width="567" alt="screen shot 2017-07-18 at 2 51 39 pm" src="https://user-images.githubusercontent.com/26583372/28334277-a51ab798-6bc8-11e7-801e-a3403b20e109.png">

**Comment by scottyscripts** [comment]
What happens when you log `this.get('currentGame')`?? Perhaps `this` isn't what we think it is inside of the `.then`

**Comment by artpylon** [comment]
I didn't think we could use console.log there, no?

Actually the 'get' error is returned from line 15 which is outside of the .then and refers to a line of code that worked before I tried to add this .then to store the id. The let gameRecord =...

```
    createGame (game) {
      let gameRecord = this.get('store').createRecord('game', game);
      gameRecord.save()
        .then(function(response) {
          console.log('current game is ', this.get('currentGame'))
          this.get('currentGame').set('id', response.game.id)
        });
    },
```

**Comment by artpylon** [comment]
I'm able to successfully console log the currentGame object above the .then, returns as expected.

**Comment by artpylon** [comment]
If I comment out the .then, the create function works.
