### ISSUE TITLE
localhost:xxxx/public/assets/images/filename.png not found 404

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/capstone-project#734]
This HTML generates an error in attempting to find the image file. Can't see why...

```css
<div class="test-box container col-sm-2 height-row-0">
    <span>
      <img src="{{rootURL}}/public/assets/images/linotype-matrix.png" class="img-responsive">
    </span>
  </div>
```

Console.log
`linotype-matrix.png:1 GET http://localhost:7165/public/assets/images/linotype-matrix.png 404 (Not Found)`

Removing {{rootURL}} didn't have any effect — failed with the same GET address.

**Comment by scottyscripts** [comment]
Webpack causes issues with image links. I suggest hosting the image somewhere online and making the img's `src` equal to the url of where your image is. A common workaround is dragging an image into an existing issue on your repo. This will generate a URL for your image. You can then use this URL to link to your image. Here is an example 
https://github.com/blog/2061-attach-files-to-comments
You don't have to hit the `comment` button either, as soon as you see a link generated where you dragged the image you are good to go!

**Comment by EricLScace** [comment]
Worked. Thanks.
