### ISSUE TITLE
Project requirements question

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/capstone-project#735]
For my project I am doing a Book recommendation website, is editing a tag (Recommended/Not Recommended) sufficient for an 'update' CRUD action? or should other attributes (title, author) be able to be updated as well?

**Comment by tvcrawley** [comment]
Was this discussed during your project 1 on 1?

**Comment by ghost** [comment]
No, I do not think so

**Comment by MicFin** [comment]
Given your applications goals for its users, I think it would make sense for the Recommend/Not Recommended to be updated on its own without updating the other fields, potentially as a switch or button that the user can push.

However, there is also the scenario where a user creates a book and then after creating it realizes they have a typo in the title.  I think they should be able to click an edit button and then be shown a form to edit the title and author to fix the typo.

**Comment by ghost** [comment]
Thank you for the answer
