### ISSUE TITLE
Ember auth: cannot get ember-local-storage working

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/capstone-project#741]
When the page loads, this error occurs:
```
Uncaught Error: Could not find module `ember-local-storage` imported from `allthemats/services/auth`
```

`npm install ember-local-storage` was successful and it appears every reference to ember-local-stroage is the same as in the Ember-auth template.

I'm stuck here as nothing renders after this point. I'm putting this branch on hold for now to try and work on something else. :-(

**Comment by EricLScace** [comment]
Basically stuck here as I cannot even get a sign-in button to appear on the screen to start the authentication process.

**Comment by jordanallain** [comment]
is `ember-local-storage` in your package.json?

**Comment by EricLScace** [comment]
yes
also in package-lock

**Comment by jordanallain** [comment]
when you say you are using it the same as the auth template, you mean you have this at the top of your file?

`import { storageFor } from 'ember-local-storage';`

and then you try to use the function like so `storageFor('auth')` ?

**Comment by EricLScace** [comment]
Yes.

**Comment by EricLScace** [comment]
storageFor() is the only function that is used from ember-local-storage.

**Comment by EricLScace** [comment]
My strategy was to import the successful auth process from Ember-auth, rather than to spend a day re-writing auth from scratch... and make tweaks/improvements. And, along the way, learn something about making Ember dance. So far, 2 left feet!
