### ISSUE TITLE
cannot get a basic HTML table to load into a 2nd component on landing page

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/capstone-project#742]
`template/application.js` contains the following:

```hbs
{{row-0}}
{{table}}
```

The row-0 component works fine.

The table component has a simple static HTML table (for testing purposes). This table fails to render.

If the table code is pasted into the end of the row-0 component, the table renders correctly.

I don't understand why both component .hbs files aren't loading. :-(

Another Ember roadblock...

**Comment by EricLScace** [comment]
<img width="1118" alt="screen shot 2017-07-18 at 17 02 41" src="https://user-images.githubusercontent.com/6785602/28339720-06f29884-6bdb-11e7-9d67-307b04ee5724.png">
<img width="1116" alt="screen shot 2017-07-18 at 17 03 07" src="https://user-images.githubusercontent.com/6785602/28339721-06f39b8a-6bdb-11e7-8c5c-0b365958f5bd.png">

**Comment by scottyscripts** [comment]
Remember to name components with a `-` in Ember.

**Comment by EricLScace** [comment]
That was, indeed, the solution. Oy vey!
