### ISSUE TITLE
Ember component fails to render as anticipated.

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/capstone-project#746]
I am trying to make my first component function. It is intended to be a utility that posts messages on the client display. There are three parts of the client that would use this utility: one when the user is logged-in, another point where messages have to be posted about authentication/registration issues, and the third where messages need to be posted regarding progress during a search of the database. Hence, a clear candidate for a re-usable component.

`ember generate component ui-messages` created the scaffolding. I have gotten stuck trying to wire up the .js side and the .hbs to render a simple message.

`components/ui-messages.js`:
```js
import Ember from 'ember'

export default Ember.Component.extend({
  // model returns a callback function
  model () {
    return [ {message: 'Hello, world!'}]
  }
})
```

`templates/components/ui-messages.hbs`:
```html
{{#each model as |message|}}
  {{message.message}}
{{/each}}
```
This generates an empty <div>.

I've also tried variations in the return statement of the .js, such as:
`return 'Hello, world!'` <-- simple string
`return ['Hello, world!'] <-- a list containing one string
`return {message: 'Hello, world!'}` <-- object with one key:value pair

I also altered the .hbs in ways such as the following:
```html
model
```
which gave the expected result: the word "model" on the screens. :-D

```html
{{model}}
```
rendered `function () ... `, also not surprising.

   I have been reviewing the ember-components classroom module and ember.js tutorials, but clearly I'm missing something basic here. :-(

**Comment by cpearce31** [comment]
If you put `{{model}}` in the template, what is the `...` in the resulting `function () ...`?

**Comment by cpearce31** [comment]
@EricLScace can we close this since you're changing directions?

**Comment by EricLScace** [comment]
yes...
