### ISSUE TITLE
Need some guidance with Ember components/routing

### ISSUE THREAD

**Issue by constaac** [ga-wdi-boston/capstone-project#750]
I am building an Ember app that relies on using datatables to render one of two lists. Each list has its out route that properly renders its data with datatables.

I'm struggling to figure out a solution to implementing a add/edit functionality. I originally planned on creating a component that renders within one of the lists routes when the edit/add button is pressed. I figured the datatable would disappear while the edit form was displayed and then re-render when that editor is submitted or canceled.

I've been searching through google searches/ember docs/SO, but havn't yet found anything I can wrap my head around. Should I use an outlet within the datatable component or simply toggle hide and show on the editor and the datatable. I wanted to use a component so that I can pass the id of the entry I'm editing into the component.

The other option I can think of is to create an editor route that requires a parameter in its path, which is where I would pass the id of the entry. However, if thats the case, I also need to pass a second parameter to define which list is being edited. Two solutions to that problem are to conjoin the two parameters with something like a dash, and then split the string on the dash when it arrives, or find a way to send the second parameter. If not, I could create an editor route for each list and pass one entry id parameter.

If I can figure out a clean way to solve this for either the add or edit function, the other one should come very quickly.

Thanks!

**Comment by constaac** [comment]
I think Id rather lean towards the component idea, because there seems to be less configuration... But I can't figure out how to load the component via button while toggling the current view

**Comment by constaac** [comment]
Thanks for the help. Im going to be trying to nest add and edit routes within each list route. For edit I will pass the entry id into the edit route. Each template will use an editor-form component ideally. I am closing the issue, but if I run into problems I will reopen it.

**Comment by constaac** [comment]
Im having some issues actually hitting any of the routes i generated

For instance, I have a list called inventories

I generated two nested routes via:
ember g route inventories/add
ember g route inventories/edit

This is my router:
`Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('wish_lists', function() {
    this.route('add');
    this.route('edit');
  });
  this.route('inventories', function() {
    this.route('add');
    this.route('edit');
  });
});`

When I go to my url/inventories/edit the datatable that normally displays in the template at url/inventories is still displaying, and my test p tag in my inv/edit handlebars does not display.

Do I need an outlet in my inventories handlebars?

**Comment by scottyscripts** [comment]
Yes! The outlet helper tells the nested template where it should render.

**Comment by scottyscripts** [comment]
Can you update this issue with what you've done since we discussed a new approach to the problem?

**Comment by constaac** [comment]
New solution:
Generates add and edit routes (4 total)

Generates wladd/wledit/invadd/invedit via:
ember g route <name>

Configures paths in router to mimic format:
list-name/add
list-name/edit/:id

Solution works for me because it displays the editor without using hide/show and doesn't show the datatable itself meanwhile. 

The routes let us rerender the datatables from the api when we link back to them
