### ISSUE TITLE
need help to set handlebar with each column having form field to show update action

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/capstone-project#754]

**Comment by isharma-sharma** [comment]
this is my handlebars file 
```
{{#each students as |student|}}
<tr data-id="{{student.id}}">
<td data-id="{{student.id}}"><button id="deleteStudent{{student.id}}" class="btn btn-default deleteRequest">Delete</button></td>
<td data-id="{{student.id}}"><button id="editStudent{{student.id}}" class="btn btn-default editStudent rep" data-toggle="modal" data-target="#updateStudent">Edit</button></td>
<td class="sname" name="[student][name]"><{{student.name}}></td>
<!-- <td><form class="updetail">
      <div class="form-group">
        <input type="text" name="student][name]" class="form-control" class="rep">
      </div></form></td> -->
<td class="scontact" name="[student][email]"><{{student.email}}</td>
<td class="saddresss" name="[student][addresss]"><{{student.addresss}}</td>
<td class="smessage" name="[student][gender]"><{{student.gender}}</td>
<td class="saddresss" name="[student][division]"><{{student.division}}</td>
<td class="smessage" name="[student][dateofbirth]"><{{student.dateofbirth}}</td>
</tr>
{{/each}}
```
i need to add the form feild in each row to show update action

**Comment by isharma-sharma** [comment]
when html is being rendered it doesnot show any of the studentInfo table

**Comment by isharma-sharma** [comment]
don't know how will i do this

**Comment by isharma-sharma** [comment]
need help to generate form field to edit email, division and address of the students

**Comment by scottyscripts** [comment]
It seems you sat down with Ben. The last comment sounds like it may be a seperate issue?

**Comment by isharma-sharma** [comment]
I asked for how to make a form field on handlebars and I was given advice to attach a modal   I tried but don’t know how to do this by handle bar, this the same issue ben help me on the delete action,

**Comment by isharma-sharma** [comment]
how can i add the id or class of the row to do edit on handlebar or  how will my modal get the id of the row i need to edit

**Comment by isharma-sharma** [comment]
how can I  mention {{student.id}} to modal which pops up to do update action on handlebars listed table of students

**Comment by isharma-sharma** [comment]
i made a handelbar template that contains the modal form  and pass the id of the row that need to be updated to that form
