### ISSUE TITLE
Ember: Generated a list, how to make each item link to it's ID

### ISSUE THREAD

**Issue by RoryEnright** [ga-wdi-boston/capstone-project#758]
I have generated my list of mountains with 
mountains.hbs
```
<h2>Mountains</h2>

<ul>
{{#each model as |mountain|}}

  <li>{{mountain.name}} {{mountain.height}} ft</li>

{{/each}}
</ul>
```
Now I'm trying to make them clickable to take you to a unique view to a singular mountain with ref to it's ID.
Not sure if I should be adding a {{link-to}} in there, after making a new model/route for mountain with a 
```this.route('mountain', { path: '/mountains/:mountain_id' });``` and connecting the two.  I was also looking into a .transition(), but not sure if that's appropriate.

routes/mountains.js
```
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
  return this.get('store').findAll('mountain');
 }
});
```
model/mountain.js
```
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  height: DS.attr('number')

});
```
router
```
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
});

Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('mountains');
});
```

**Comment by cpearce31** [comment]
I think using `{{link-to}}` and a corresponding route and template is the right approach, looks like you're on the right track! Have you encountered problems with this approach?

**Comment by RoryEnright** [comment]
Looking at the ember-resources repo, maybe I should be doing something similar to 
```
ember generate model item content:string done:boolean list:belongs-to:list
ember generate route list
 export default DS.Model.extend({
   title: DS.attr('string'),
   hidden: DS.attr('boolean'),
+  items: DS.hasMany('item'),
 });
 Router.map(function () {
   this.route('lists');
-  this.route('list');
+  this.route('list', { path: '/lists/:list_id' });
 });
 export default Ember.Route.extend({
+  model (params) {
+    return this.get('store').findRecord('list', params.list_id);
+  },
 });
```
To make a relationship to mountains and mountain.  Still missing the step on how to make each list item a clickable event that links to it's own view state.

**Comment by cpearce31** [comment]
I'll come take a look.

**Comment by RoryEnright** [comment]
Solved.
{{link-to}} goes inside of the <li> tags when hbs makes the list.  Make sure you're linking to a good route with a new hbs template to render the new location.

Thanks Caleb!
