### ISSUE TITLE
Ember, GET based on join table IDs

### ISSUE THREAD

**Issue by RoryEnright** [ga-wdi-boston/capstone-project#762]
I'm trying to GET hikes so the user only sees their hikes from a specified mountain.
I think I want to use something like: 
```
this.get('store').query('person', {
  filter: {
    name: 'Peter'
  }
```
Unsure what to use as filters.  I'm guessing this is where we filter 'hike' by user_id and mountain_id.
Been looking into the ember docs for .query() with a filter.

I don't want to filter by the hike_id, the same user could hike the same mountain more than once and I would like the user to be able to see all of there hikes on a given mountain.

model:
```
import DS from 'ember-data';

export default DS.Model.extend({
  when: DS.attr('date'),
  trail: DS.attr('string'),
  duration: DS.attr('number'),
  note: DS.attr('string')
});
```
hbs
```
<h2>Hikes</h2>

<ul>
{{#each model as |hike|}}

  {{hike.when}} {{hike.trail}} {{hike.duration}} {{hike.note}}

  {{!-- <li>{{#link-to 'hike' hike.id}}{{hike.name}} {{hike.height}} ft{{/link-to}}</li> --}}

{{/each}}
</ul>
```
routes
```
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
  return this.get('store').query('hike', {
  filter: {
  mountain_id  : mountain.id
  user_id : user.id
  }
 }
});
```
router
```
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
});

Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('mountains');
  this.route('mountain', { path: 'mountains/:mountain_id'});
  this.route('hikes');
});

export default Router;
```

**Comment by scottyscripts** [comment]
Just to clarify,  you doing the `index` action for hikes? But you only want to see the current user's hikes for a specified mountain?

**Comment by RoryEnright** [comment]
correct

**Comment by scottyscripts** [comment]
After discussion, we decided to
1) make index for hike only show current_user's hikes
2) nest hikes under mountains so that index route is `/mountains/:mountain_id/hikes`

**Comment by RoryEnright** [comment]
Created a nested route with ember g mountain/hikes, now I'm having trouble with showing the hikes again.  Probably an issue with paths to the nested route.

Maybe I can talk to someone about refactoring?

**Comment by RoryEnright** [comment]
Because of the relationship between mountain and hikes, mountain knew about hikes, but the serializer was not set up to show them.  Had to add a :hikes attribute to the serializer and then define it to send the ID for Ember.

```
class MountainSerializer < ActiveModel::Serializer
  attributes :id, :name, :height, :hikes
  def hikes
    object.hikes.pluck(:id)
  end
end
```
