### ISSUE TITLE
Trouble Resetting Form Fields

### ISSUE THREAD

**Issue by constaac** [ga-wdi-boston/capstone-project#764]
I have a component that is meant to add an entry to my datatable. The entry gets added properly, but I want to have the form cleared for the next time the form is routed to.

This is my component.js: 

```entry: {},
actions: {
    createEntry: function () {
      this.get('store').createRecord('inventory', this.get('entry')).save().then(
        () => {
          resetFields();
          this.get('router').transitionTo('inventories');
        }
      ).catch(() => {
        this.get('flashMessages')
        .danger('There was a problem adding your entry. Please try again.');
      })
    },
```

I have tried doing `this.set('entry', {})` which properly clears the object, but the form doesn't actually clear. I followed what was going on in the changePassword form, but can't replicate it.

Next I tried a function that sets the values to empty strings using jquery, which not only did not work, but also causes my catch to fire as well as the next it is called in.

I have several input fields, mostly text, but two number inputs, and one select. Here is an example:
```
`<div class="form-group">
  <label for="wl-name">Name</label>
  {{input type="text"
          class="form-control"
          id="wl-name"
          placeholder="Bottle Name"
          value=entry.name}}
</div>
```

Thanks!

**Comment by payne-chris-r** [comment]
Take a look at this:
```js
import Ember from 'ember';

export default Ember.Component.extend({
  newItem: {
    content: null,
    done: false,
  },
  classNames: ['listr'],
  classNameBindings: ['listDetailHidden'],
  listDetailHidden: false,
  actions: {
    toggleListDetail () {
      return this.toggleProperty('listDetailHidden');
    },

    toggleItemDone (item) {
      this.sendAction('toggleItemDone', item);
    },

    deleteItem (item) {
      this.sendAction('deleteItem', item);
    },

    createItem () {
      let data = this.get('newItem');
      data.list = this.get('list');
      this.sendAction('createItem', data);
      this.set('newItem.content', null);
    },
  },
});
```

**Comment by constaac** [comment]
Had to set each value equal to the property name; for example:
value=entry.name    becomes     value=entry

In the JS object, we defined entry=''

This patterned is repeated for each input field, and then the entry object to be passed to create the record is built via a computed property.

Thanks!
