### ISSUE TITLE
Data Down Action Up, help with path?

### ISSUE THREAD

**Issue by RoryEnright** [ga-wdi-boston/capstone-project#765]
Working on my delete action.  Tried to follow along with the ember-resources repo, but that has some nested routes and components for it's DDAU.  I think I have a decent grasp as to what I should be using for crud actions, but I'm having trouble with which layers they should go in.

My problem may be the fact that I haven't made a components folder yet.  Could I get a quick 1 on 1 to go over components and pathing?  

Doesn't help that a lot of stackOverflow still mentions "controllers", heh.

Thanks!

**Comment by scottyscripts** [comment]
We will sit down for a one on one and tackle this after the other issue. Using a component is a good idea for sure, isolating actions and bubbling them up to the route from there.

**Comment by scottyscripts** [comment]
@RoryEnright How is this going?

**Comment by RoryEnright** [comment]
Alex gave me some good insight, but I wouldn't mind sitting down for a sec.
I'm not sure if a component is necessary because my app is on the smaller side, but it's probably best practice.  

Whenever you have some time, I'm good to go.

**Comment by RoryEnright** [comment]
Made a component to bubble up the delete action.  Console.logs are very helpful to see where the action is getting caught while being passed up.  Make sure when the component is being rendered to give it the info it needs.  Such as item=item and action='action'.

Thanks Caleb
