### ISSUE TITLE
Need guidance with Configuring Editor Form Component

### ISSUE THREAD

**Issue by constaac** [ga-wdi-boston/capstone-project#767]
I have two routes housing two datatable lists which have delete/add/edit functions for each entry. The delete and edit buttons are actual buttons within the entry's row, and the add button lies underneath the data table itself. The delete button works properly as well as the add functionality. 

The add button works by linking to an listname-add route where a form field is filled out, and the record is created from those values, so that the datatable rerenders with that new data when it is linked back to.

I'm pulling the data from the formfields by setting the html value attribute to entry.<property name>. The object in the component JS file is then used to build the record.

I intend for the edit field to work very similarly, except the form will be pre-filled out with the values of the entry after retrieving it from the API/store via id (passed to the route as a param).

The issue I'm running into is with how I should go about pre-filling out the form. If I pass the component the model, and set the value attributes to {{model.<property>}}, I may run into issues since I could no longer follow the format I've been using for the add forms where the value is equal to entry.property.

How can I go about populating the form while still pulling the values via binding?

**Comment by cpearce31** [comment]
After the fix to your previous issue, your form fields' values are each bound to a property on the component i.e. `value=winery`. As you said, you should definitely maintain this binding. So can you set the `winery` property on the component based on what you get back from the store?

**Comment by constaac** [comment]
Im really struggling with defining how to set the "selected" attribute on the select option corresponding to the entry's  value when the form loads. 

The ember select helper was depricated a long time ago, and I've been having trouble finding any alternatives. 

To solve this I've tried setting the value of the select tag dynamically based on the model being passed in, using jquery (feels like its the right path to pursue), and even a ton of if helpers within the option tags. The if tags would call a function from the JS file that would return true if the value was equal to that select option. An example looked like this:

```
<select>
   <option {{if isStandard selected}} value="Standard">Standard</option>
</select>
```

It doesn't like the if helper, and it also doesn't want if blocks with #.

Aside from npm installing some 3rd party solution, I can't figure out how to go about this. Its the last step of implementing the editor window.

**Comment by constaac** [comment]
If I leave that out, the editor function works properly, it just seems odd that all of the information for the entry is loaded into the form, except for the size which is defaulted to a certain value. Feels wonky to have to change the quantity back to what it should be every time you edit something thats not the default size.

**Comment by constaac** [comment]
I may have found a workaround in the meantime:

`<option selected disabled>Change Bottle Size (optional)</option>`

Keeps the value unchanged unless a size is chosen

**Comment by constaac** [comment]
Works for now!
