### ISSUE TITLE
ember - play game flow

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/capstone-project#768]
I'm having what seems like a simple problem, but I've tried a few approaches to solve it and haven't had any success. I'd like to have a button on the homepage called play game that creates a new game record and transitions the user to the /games/game_id route, where they can play the game. 

Currently, I have these routes:
index
/games
/games/game_id

The play game button is on the /games route, and it works as described above. BUT, if you start at the homepage and you're already signed in, you have to click a superfluous button to get you to the /games route where you then click play game to start a game. Successful sign in transitions to /games automatically.

I've tried moving the play game button and corresponding action around, but it only works on /games
- creating a play-game component rendered in my-application
- moved play-game component to index
- put play game button on index

All of these attempts fail, I think, because the ember only knows where to send the request when it's on /games...

**Comment by scottyscripts** [comment]
can you post the code in your `play-game` component and template? What action is happening when you click that button?

**Comment by artpylon** [comment]
I reverted back to the initial (flawed) design, here is the createGame code that I would like to include on the homepage of the app and perhaps also on /games. 

games.hbs
``` hbs
<div class='btn-group game-menu'>

    <button class='btn play-game' {{action 'createGame'}}>Play Game</button>

</div>

<h4>How to play:</h4>
<p>Each card has four properties: shape, color, shading, and number.</p>
<p>Select three cards where, across those 3 cards, each of the individual properties
  is either all the same, or all different.</p>

{{outlet}}
```

games.js
```js
import Ember from 'ember';

export default Ember.Route.extend({
  auth: Ember.inject.service(),

  user: Ember.computed.alias('auth.credentials.email'),
  isAuthenticated: Ember.computed.alias('auth.isAuthenticated'),
  actions: {
    createGame(){
      let self = this;
      let currentGame = this.get('store').createRecord('game', {
        over: false
      });
      currentGame.save()
        .then(function(savedGame){
          self.transitionTo('game', savedGame.get('id'))
        })
    }
  }
});

```

**Comment by artpylon** [comment]
An alternative solution, I think, would be to wrap text prompting the user to sign in to start a game in a hbs if statement based on isAuthenticated property. I attempted to implement this, but the if statement is not hiding the prompt when use is signed in. See below:

games.js
```js
import Ember from 'ember';

export default Ember.Route.extend({
  auth: Ember.inject.service(),

  user: Ember.computed.alias('auth.credentials.email'),
  isAuthenticated: Ember.computed.alias('auth.isAuthenticated'),
  actions: {
    createGame(){
      let self = this;
      let currentGame = this.get('store').createRecord('game', {
        over: false
      });
      currentGame.save()
        .then(function(savedGame){
          self.transitionTo('game', savedGame.get('id'))
        })
    }
  }
});
```
games hbs
```hbs
{{#unless isAuthenticated}}
<p>(Must be signed in to start a new game)</p>
{{/unless}}

<div class='btn-group game-menu'>

    <button class='btn play-game' {{action 'createGame'}}>Play Game</button>

</div>

<h4>How to play:</h4>
<p>Each card has four properties: shape, color, shading, and number.</p>
<p>Select three cards where, across those 3 cards, each of the individual properties
  is either all the same, or all different.</p>

{{outlet}}
```

**Comment by artpylon** [comment]
Unfortunately, adding quotes for isAuthenticated didn't work.

**Comment by scottyscripts** [comment]
@artpylon How is this going??
