### ISSUE TITLE
getFormFields sending weird object...

### ISSUE THREAD

**Issue by slammyde7113** [ga-wdi-boston/capstone-project#770]
When I do event.target I'm getting a data object, with an empty string as an attribute, and then the data I want to pass as the attribute of the empty string obejct. Here's so code for clarification:

Browser response as a console log:
```
Object {"": Object}
""
:
Object
articles
:
Object
id
:
"7"
```

Associated HTML:
```
<div>
                <form id="search-form" class="navbar-form navbar-left" role="search">
                <input type="text" class="form-control" name=[articles][id] placeholder="Search by Article ID">
                <button type="submit" class="btn btn-default">Submit</button>
                </form>
              </div>
```

Events.js
```
const onSearchArticles = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  console.log(data)
  api.searchArticles(data)
    .then(ui.searchArticlesSuccess)
    .catch(ui.searchArticlesFailure)
}
```

**Comment by scottyscripts** [comment]
It looks like getFormFields is creating nested objects with `[]` in the name attr. Have you tried modifying that name? Maybe removing brackets from the first part since that seems to be creating the nested object

**Comment by slammyde7113** [comment]
thats it! thank you very much sensei
