### ISSUE TITLE
Querying Records From a Join Table

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/capstone-project#774]
My join table (Myconcert) has a profile_id and a concert_id. Is there a best way to so this? SQL brute force? Or try and use Rails. I've been looking at http://edgeguides.rubyonrails.org/active_record_querying.html and really can't tell which way to go.

Obviously, Myconcert.all is not the way to go :-)

**Comment by cpearce31** [comment]
What are you trying to get? All concerts for a given profile, or the other way around?

**Comment by MarcyNash** [comment]
All concerts for a given profile

**Comment by scottyscripts** [comment]
What is the use case for this? Is this for your `index` action for `Myconcert`? What is the end goal?

**Comment by scottyscripts** [comment]
This is where ActiveRecord makes our lives way easier. Luckily we won't have to write any raw SQL for this. You should take a look at `.find_by `. 
http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by
You can call this on a class so, Myconcert.find_by() passing in a key and value of what you want to query by.

**Comment by scottyscripts** [comment]
@MarcyNash how is this going?

**Comment by MarcyNash** [comment]
Having trouble with the syntax of find_by.

The syntax I tried --
@myconcerts =  Myconcert.joins(:concerts).where(myconcerts: {  profile_id: params[:id]}).find_by(myconcerts: {id: myconcerts[concert_id]}) 

The server replied --

Started GET "/myconcerts" for 127.0.0.1 at 2017-07-20 15:35:59 -0400
Processing by MyconcertsController#index as */*
Completed 500 Internal Server Error in 528ms (ActiveRecord: 0.0ms)
  
NameError (undefined local variable or method `myconcerts' for #<MyconcertsController:0x007f9ed1edaef0>

**Comment by MarcyNash** [comment]
Myconcerts_controller.rb now inherits from OpenReadController. For CRUD index, 
current_user.profile.myconcerts returns all the concerts for a user. Yay!

Thanks, Scott

**Comment by MarcyNash** [comment]
With these changes to user model, user has_one profile, I can no longer create a profile

**Comment by MarcyNash** [comment]
Changing 

```
  def create
    @profile = current_user.profiles.build(profile_params)
```
to 
```
  @profile = Profile.create(profile_params)
    current_user.profile = @profile
```
fixed the create profile issue.

Thanks Scott!
