### ISSUE TITLE
Glyphicon Trouble

### ISSUE THREAD

**Issue by constaac** [ga-wdi-boston/capstone-project#775]
I am implementing bootstrap glyphicons by importing the cdn in my scss like so:

`@import url("//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css");`

I was having trouble with glyphicons before, so this was an easy work-around. When my application loads, i am getting several 404 errors:

```
15:36:55.388 fonts/bootstrap/glyphicons-halflings-regular.woff:1 GET http://localhost:7165/fonts/bootstrap/glyphicons-halflings-regular.woff 
15:36:55.430 fonts/bootstrap/glyphicons-halflings-regular.ttf:1 GET http://localhost:7165/fonts/bootstrap/glyphicons-halflings-regular.ttf 
```

I am looking at a [previous issue](https://github.com/ga-wdi-boston/capstone-project/issues/166), but can't figure out what file the import lines need to be in.

If I get that working, I have a feeling I won't need the CDN

**Comment by cpearce31** [comment]
Take a look in `ember-cli-build.js`, you might see some similar import syntax to what Antony posted in the linked issue.
