### ISSUE TITLE
getting an error of could not find module ember-local-storage when populating code into services/auth.js

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/capstone-project#776]

**Comment by EricLScace** [comment]
I don't really want to re-build the whole code space from a virgin template with auth in it... But the Ember-Template has no auth at all... so was trying to understand & incorporate the auth mechanisms used in our other repos...

**Comment by tvcrawley** [comment]
Have you tried incorporating the code from the [ember-auth talk](https://git.generalassemb.ly/ga-wdi-boston/ember-auth)?

**Comment by EricLScace** [comment]
VM3060 vendor.js:4206 Uncaught 
EmberError {description: undefined, fileName: undefined, lineNumber: undefined, message: "Assertion Failed: You attempted to define a `{{lin…ect an unknown injection: 'service:flashMessages'", name: "Error"…}

**Comment by EricLScace** [comment]
Yes, that's what I've been working from.

**Comment by EricLScace** [comment]
Hmm... it seems I lack an app/storages/auth.js ...

**Comment by tvcrawley** [comment]
Looks like your app doesn't know what flashMessages is. Look closely at what files differ from `ember-auth` and the `ember-template`.
