### ISSUE TITLE
my function are working on local host but not on deployed site

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/capstone-project#777]
I am getting error
vendor.js:9678 POST https://thegreatmaster.herokuapp.com/sign-in 401 (Unauthorized)

**Comment by isharma-sharma** [comment]
www.google.com/_/chrome/newtab-serviceworker.js:61 Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported
    at www.google.com/_/chrome/newtab-serviceworker.js:61
    at <anonymous>
util.js:142 XHR finished loading: GET "https://www.google.com/maps/vt?pb=!1m4!1m3!1i17!2i93917!3i55231!1m4!1m3!1i1…ity_class!2s0!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!4e3!12m1!5b1&token=67058".
WG @ util.js:142
_.XG @ util.js:142
(anonymous) @ onion.js:20
WV.load @ onion.js:65
ZV @ onion.js:24
XV.l @ onion.js:65

**Comment by isharma-sharma** [comment]
All my function shows immediate response locally, but I need to refresh page to see my update function working on deployed version I'm not getting any error now in console,

**Comment by isharma-sharma** [comment]
again getting the same error on console
````
www.google.com/_/chrome/newtab-serviceworker.js:61 Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported

**Comment by cpearce31** [comment]
Do you have a file called `util.js`? What's on line 142?

**Comment by MicFin** [comment]
Do you have google chrome extensions running that might be interfering?
