### ISSUE TITLE
Heroku Deployment Error-Shocker

### ISSUE THREAD

**Issue by eshimel** [ga-wdi-boston/capstone-project#78]
I'm not able to push to Heroku yet.  I think it might have to do with my AWS keys, but I have set them in my heroku config vars, and don't know what else to.  The about section on heroku's site wasn't particularly enlightening for me.

Here's what I've done to try to resolve the issue on my own:
 gone through the heroku deployment repo twice to make sure that I didn't miss anything
Bundle installed just in case I missed some gem...no luck on this fix.
Pushed and rebased the repo in case I was missing something.
Attempted to look up the error and tried a few stackoverflow suggestions
The app seems to run fine on foreman.

Here's the error 

! [remote rejected] master -> master (pre-receive hook declined)

Here's what my Heroku logs says:
2015-12-18T11:47:30.909774+00:00 heroku[api]: Set AWS_SECRET_ACCESS_KEY config vars by edieshimel@gmail.com
2015-12-18T11:47:30.909774+00:00 heroku[api]: Release v4 created by edieshimel@gmail.com
2015-12-18T11:47:53.750557+00:00 heroku[api]: Set S3_BUCKET_NAME config vars by edieshimel@gmail.com
2015-12-18T11:47:53.750557+00:00 heroku[api]: Release v5 created by edieshimel@gmail.com
2015-12-18T11:53:20.796676+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-18T11:53:20.796686+00:00 heroku[slug-compiler]: Slug compilation failed: failed to compile Ruby app
2015-12-18T11:59:23.422990+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-18T11:59:23.423008+00:00 heroku[slug-compiler]: Slug compilation failed: failed to compile Ruby app
2015-12-18T12:00:26.047011+00:00 heroku[slug-compiler]: Slug compilation started

**Comment by GA-MEB** [comment]
http://stackoverflow.com/questions/23941742/pushing-to-heroku-slug-compilation-failed-failed-to-compile-ruby-app

On Fri, Dec 18, 2015 at 7:19 AM, Edie Shimel notifications@github.com
wrote:

> I'm not able to push to Heroku yet. I think it might have to do with my
> AWS keys, but I have set them in my heroku config vars, and don't know what
> else to. The about section on heroku's site wasn't particularly
> enlightening for me.
> 
> Here's what I've done to try to resolve the issue on my own:
> gone through the heroku deployment repo twice to make sure that I didn't
> miss anything
> Bundle installed just in case I missed some gem...no luck on this fix.
> Pushed and rebased the repo in case I was missing something.
> Attempted to look up the error and tried a few stackoverflow suggestions
> The app seems to run fine on foreman.
> 
> Here's the error
> 
> ! [remote rejected] master -> master (pre-receive hook declined)
> 
> Here's what my Heroku logs says:
> 2015-12-18T11:47:30.909774+00:00 heroku[api]: Set AWS_SECRET_ACCESS_KEY
> config vars by edieshimel@gmail.com
> 2015-12-18T11:47:30.909774+00:00 heroku[api]: Release v4 created by
> edieshimel@gmail.com
> 2015-12-18T11:47:53.750557+00:00 heroku[api]: Set S3_BUCKET_NAME config
> vars by edieshimel@gmail.com
> 2015-12-18T11:47:53.750557+00:00 heroku[api]: Release v5 created by
> edieshimel@gmail.com
> 2015-12-18T11:53:20.796676+00:00 heroku[slug-compiler]: Slug compilation
> started
> 2015-12-18T11:53:20.796686+00:00 heroku[slug-compiler]: Slug compilation
> failed: failed to compile Ruby app
> 2015-12-18T11:59:23.422990+00:00 heroku[slug-compiler]: Slug compilation
> started
> 2015-12-18T11:59:23.423008+00:00 heroku[slug-compiler]: Slug compilation
> failed: failed to compile Ruby app
> 2015-12-18T12:00:26.047011+00:00 heroku[slug-compiler]: Slug compilation
> started
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-wdi-boston/portfolio-capstone-project/issues/78.

## 

_Matt Brendzel_
_Educational Programs Producer | Developer In Residence_
General Assembly - Boston | 51 Melcher Street, Boston, MA 02210
matt.brendzel@generalassemb.ly | @mattbrendzel | @GA_Boston | (215) 839 9428
http://generalassemb.ly

Join the party. Sign up for the GA newsletter
https://generalassemb.ly/locations/boston/.

**Comment by jrhorn424** [comment]
I believe this was resolved in-person yesterday.
