### ISSUE TITLE
Grunt issue, can't deploy

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/capstone-project#781]
When trying to do a grunt command from the terminal (serve, deploy) I get the following message in my terminal:
```env: node: No such file or directory``` don't know how to fix this?

**Comment by cpearce31** [comment]
What do you see if you enter `which node` in terminal?

**Comment by ghost** [comment]
Nothing happens when I do that, when I type in echo $PATH I get ```//anaconda/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin``` if that helps

**Comment by cpearce31** [comment]
If you enter `nvm current`, do you see `v8.0.0`?

**Comment by ghost** [comment]
I get ```-bash: nvm: command not found```

**Comment by cpearce31** [comment]
Hmm, either nvm isn't installed, or it's not on your `$PATH`. Try running the nvm setup script from Installfest: https://github.com/ga-wdi-boston/orientation/blob/master/config/nvm.sh

**Comment by ghost** [comment]
I think it is a path issue, I did the update that Jordan gave us on Thursday sucessfully

**Comment by cpearce31** [comment]
Try running that script anyway, and then try `which nvm`

**Comment by cpearce31** [comment]
Also, open up `.bashrc` with `atom ~/.bashrc` and see if you have something like this:
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

**Comment by ghost** [comment]
Tried installing nvm but got this message  ```Warning: nvm 0.33.2 is already installed``` ran which nvm but got a message that nvm:command not found

**Comment by ghost** [comment]
Have the following in .bashrc:
```export NVM_DIR=~/.nvm
  source $(brew --prefix nvm)/nvm.sh
eval "$(hub alias -s)"```

```export PATH="/usr/local/bin:$PATH"```

**Comment by ghost** [comment]
export NVM_DIR=~/.nvm
  source $(brew --prefix nvm)/nvm.sh
eval "$(hub alias -s)"

**Comment by cpearce31** [comment]
Do you a `.nvm` directory in `~`?

**Comment by cpearce31** [comment]
And can you try typing `brew --prefix nvm` to see where Homebrew thinks that `nvm.sh` script is?

**Comment by ghost** [comment]
theres a .nvm folder in .bashrc, brew --prefix returns ```/usr/local/opt/nvm```

**Comment by cpearce31** [comment]
Let's try adding that to your path. Open `.bashrc` with Atom and add this: `export PATH="/usr/local/opt:$PATH"`. Then enter `source ~/.bashrc` in terminal. Then enter `nvm` and see if it works.

**Comment by ghost** [comment]
That worked, when running nvm current I get `v6.11.1` instead of command not found

**Comment by cpearce31** [comment]
Cool! That may actually be the correct version for our purposes. Are you able to `grunt deploy` now?

**Comment by ghost** [comment]
I can run grunt serve, will try grunt deploy next

**Comment by ghost** [comment]
Grunt deploy ran, will check if it works in the browser

**Comment by ghost** [comment]
Issue resolved, changed path in .bashrc to `export PATH="/usr/local/opt:$PATH"`.  Thank you very much
