### ISSUE TITLE
Deployment Issues Again

### ISSUE THREAD

**Issue by constaac** [ga-wdi-boston/capstone-project#782]
I got my deployment working after 4 hours on thursday night, and Im running into the same problems again.

I have tried several times, and here is my workflow:

blowup gh-pages local branch with: git branch -D gh-pages
blowup gh-pages remote branch with: git push origin --delete gh-pages
checked for ember-auth with global search
npm and bower installed
added and committed package files
changed rootURL: ‘/wine-mate-front-end’, to ‘/’ in environment.js
Ensured i was using var
Ensured I have apiHost line
Checked environment===production block equals:
```ENV.rootURL = '/wine-mate-front-end';
    ENV.locationType = 'hash';
    ENV.apiHost = 'https://wine-buddy-api.herokuapp.com/'
```
Ensured this line in application.js:
```import ENV from 'wine-mate-front-end/config/environment';```
Added and committed files
checked out to new gh-pages branch
remove dist from gitignore
No dist file -> run ember serve to create one
git add /dist and commit 
run ember build --environment=production
git add -A && git commit -m ‘Ember built
git subtree push --prefix dist origin gh-pages’

After All that I get a 404 every time, with the exception of my first attempt being a blank page.

Is there something more I have to do?

**Comment by constaac** [comment]
Subtree push output:
``` $ git subtree push --prefix dist origin gh-pages
git push using:  origin gh-pages
Counting objects: 49, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (46/46), done.
Writing objects: 100% (49/49), 2.55 MiB | 1.09 MiB/s, done.
Total 49 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), done.
To github.com:constaac/wine-mate-front-end.git
 * [new branch]      1c46ac99b3603953c238bc3b6dde4f92a45f366b -> gh-pages```

**Comment by constaac** [comment]
Ember Build Output:
```$ ember build --environment=production
⠧ Building[WARN] (broccoli-uglify-sourcemap) Minifying: `assets/vendor.js` took: 22541ms (more than 20,000ms)
cleaning up...
Built project successfully. Stored in "dist/".
File sizes:
 - dist/assets/vendor-49b743657e107f27adb6c6d24688d907.js: 1.24 MB (333.57 KB gzipped)
 - dist/assets/vendor-abfa9bed171bb3488cd440400a5a5e65.css: 24.75 KB (3.92 KB gzipped)
 - dist/assets/wine-mate-front-end-6314811d0524b710bca38b02002c9744.js: 80.47 KB (8.65 KB gzipped)
 - dist/assets/wine-mate-front-end-af2b4988142d90ed0462426f24bfe580.css: 127.13 KB (21.26 KB gzipped)
 - dist/moment/fastboot-moment-62eb34042848ca105b39d48fa2474ea3.js: 95 B (97 B gzipped)
 - dist/moment/fastboot-moment-timezone-abadb8be73831ba0ff2208c313da0af0.js: 104 B (107 B gzipped)```

**Comment by cpearce31** [comment]
For other consultants who may help troubleshoot this: I was able to fork, clone, and deploy Alex's app successfully on my machine.

**Comment by constaac** [comment]
I Just reran the process, I didn't have a dist folder this time, and did not run ember serve to recreate it. I only got a dist folder after running ember build. I added and commited dist before pushing the subtree, and still get a 404

**Comment by constaac** [comment]
Just nuked my local repo and cloned from git

Still no success

Note: there was no dist folder until I ember built, so going to repeat the process and run dependency installs and ember s before doing any steps

**Comment by constaac** [comment]
Still nothing!!

**Comment by constaac** [comment]
https://constaac.github.io/wine-mate-front-end/

**Comment by constaac** [comment]
So For a while Matt Gray was able to access my deployment, though anything computer on my network would get a 404, even when I cleared the cache. I was able to access it on my phone. My fix for my issue didnt work, So i made a minor change and redeployed, and now I'm back to square one with Matt, my computer, and my phone getting a 404

**Comment by constaac** [comment]
Now it works for me and he gets a 404 >.<

**Comment by constaac** [comment]
Works on other computers on my network but not on my phone

**Comment by constaac** [comment]
I already resubmitted too....

Clearing cache and using different browsers isn't fixing it

**Comment by constaac** [comment]
I couldn't even tell you what I did differently, but Its deployed
