### ISSUE TITLE
pre 1:1 chat

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#786]
I'd like to discuss potential ideas with a consultant briefly

**Comment by jordanallain** [comment]
do you have an ERD or anything prepared?

**Comment by ryanwk** [comment]
Yes but last night I realized it would be impossible to build what I was intending to in the timeframe we have. So right now I'm thinking I will redo my project 2 and after WDI I will build the app I was thinking of.

**Comment by jordanallain** [comment]
okay lets meet in the kitchen

**Comment by ryanwk** [comment]
ok

**Comment by jordanallain** [comment]
"close me @ryanwk !" - this issue
