### ISSUE TITLE
Ready to meet for 1:1

### ISSUE THREAD

**Issue by kailinc** [ga-wdi-boston/capstone-project#787]
Got my ERD, User Stories, Wireframe ready to go

Need Opinions about Scope
- React
- BootStrap
- Routes
- Stripe API

Client Repo: https://github.com/kailinc/mango-bytes

API Repo: https://github.com/kailinc/mango-bytes-api

Wireframes:https://drive.google.com/open?id=0Bxg3M0KoMGmAbDJEbVR0VDliUjQ

ERD:https://drive.google.com/open?id=0Bxg3M0KoMGmASHZzeDJic3VOUnc

**Comment by jordanallain** [comment]
want to meet in the kitchen for a chat?

**Comment by kailinc** [comment]
lets do it!

**Comment by jordanallain** [comment]
wanna close this bad boy up @kailinc ?

**Comment by kailinc** [comment]
Thanks @jordanallain  @sdavidson140 !
