### ISSUE TITLE
1:1 request for capstone project

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/capstone-project#788]
I would like to go over my idea for a capstone project. It is an app for organic gardeners and farmers to find out what kind of organic pest control methods are available for the veggies they grow. It is going to have lots of gross bug pictures in it!

User Stories:

![capstone-user-stories](https://user-images.githubusercontent.com/28842407/29714055-52571974-896f-11e7-9f81-cc53743f63f1.png)

Wireframe:

![organicks wireframe](https://user-images.githubusercontent.com/28842407/29714068-5d47d0f8-896f-11e7-8ccc-4fd3a86c0677.jpg)

ERD:

![organicks erd](https://user-images.githubusercontent.com/28842407/29714072-64fc5ee0-896f-11e7-8bb5-0d0e07e84bde.jpg)

**Comment by jordanallain** [comment]
are you all set with this now @3point14guy ?

**Comment by 3point14guy** [comment]
Met with Caleb and discussed the scope of the project and what was needed to meet MVP.  Will adjust the basic idea of the app to let users create their own virtual garden to satisfy CRUD requirements.  Will also start with just the veg and pest relationships first to meet MVP and then work to add the organic control methods.

Discussed hosting pics on photobucket vs imgur and making relationships optional while building out the join tables.
