### ISSUE TITLE
1:1 request for capstone

### ISSUE THREAD

**Issue by jltyler** [ga-wdi-boston/capstone-project#789]
I'm requesting a 1:1 chat to discuss my synthesizer idea for my capstone. In particular, the scope and requirements of the project.

Wireframes 
Main: [https://wireframe.cc/xw2anL](https://wireframe.cc/xw2anL)
Osc: [https://wireframe.cc/zUPe1I](https://wireframe.cc/zUPe1I)
Filter: [https://wireframe.cc/2uiU0q](https://wireframe.cc/2uiU0q)
Load: [https://wireframe.cc/5Dpjpd](https://wireframe.cc/5Dpjpd)

ERD
[https://wireframe.cc/zgILTK](https://wireframe.cc/zgILTK)

User stories
As a user, I can change 2 to 3 separate oscillator settings to produce varied waveforms
As a user, I can change filter settings to manipulate those waveforms
As a user, I can change envelope settings on the gain and filter
As a user, I can save oscillator settings and filter settings independently and reuse them
As a user, I can save my patches to a database to retrieve later
As.a user, I can save private patches that no one else can load
As a user, I can play notes with my patch on a visual keyboard or the physical keyboard
As a user, I can hook up a MIDI controller to play notes and control filter settings

**Comment by jordanallain** [comment]
want to meet up and go over this in the kitchen?
