### ISSUE TITLE
1:1 Request

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/capstone-project#791]
ERD and wireframes: http://imgur.com/a/wiBth

Concept: Web app containing easy to use financial wellness tools that help users visualize loans and interest payments, retirement investing, and general finances like rent-to-income
Stack: SQL -> Rails -> Browser template/JavaScript or Ember

User stories: 
As a user, I want to be able to...
"visualize loans with principal + interest rates"
"visualize how much my rent takes up from my income"
"compare my finances to others in country, state, age group"
"visualize the retirement investing"
"compare paying down loans to investing in stocks or index funds"
"share my loans and retirements with other users"

**Comment by jordanallain** [comment]
lets do this, kitchen time
