### ISSUE TITLE
1:1 Request

### ISSUE THREAD

**Issue by mak1323** [ga-wdi-boston/capstone-project#792]
This is my 1:1 request

My project idea is a Dungeons and Dragons (3.5) encounter tracker.

The inspiration for this project is that this is something that I actually want, I would definitely use, and it solves a problem that occurs when I’m DMing: “Who’s turn is it again?” 

The following is a link to my user stories:
https://goo.gl/photos/UPwfcXgSDpe8vZoU6

The target audience and user is a Dungeon Master or Game Master.

The following is a link to my ERD:
—Simple:
https://goo.gl/photos/niyfENCWbDUAqh1D6
—Complex:
https://goo.gl/photos/GVUNz2QMHpDd9S6P8

The following is my  wireframe:
—Simple:
https://goo.gl/photos/AEvq75s1U9XAwJ2Z6
—Complex:
https://goo.gl/photos/5njvQkMKdasv7kePA

I’m modeling my data as follows:
https://goo.gl/photos/yPK5fWNWRYCRbWgv6

I have yet to model my encounter data but I’m thinking it will look like:

|id|user_id|campaign_id|encounter_data|

encounter_data
```js
[
	{
	type: (char or monster),
	id: (char_id or monster_id),
	activeHp: num,
	initiative: num,
	isActive: bool,
	currentTurn: bool,
	},
	{
	type: (char or monster),
	id: (char_id or monster_id),
	activeHp: num,
	initiative: num,
	isActive: bool,
	currentTurn: bool,
	},
	{
	type: (char or monster),
	id: (char_id or monster_id),
	activeHp: num,
	initiative: num,
	isActive: bool,
	currentTurn: bool,
	}
]
```

The idea here is to create a nested schema expecting an array. This way I don’t straight modify the characters here in the game. I do however create new stats that are only prevalent to the scope of the current encounter.

I use this to allow myself to load characters and monsters generated by the user, allowing for full customization and full access of crud. 

I know how to approach this project using Browser Template, but I’m not sure about ember. I designed my wireframe with ember in mind, but I’m entirely sure how to approach some of the js functions using ember.

My current plan of attack is to create two or three repos. First I want to get my backend working and test that using my browser template crud action ability. Once I know all my backend and crud is working, I either want to make a new front end using ember or using browser template.

**Comment by jordanallain** [comment]
want to meet in the kitchen with me?

**Comment by mak1323** [comment]
Sure. Now good?
