### ISSUE TITLE
setting up backend 

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#797]
I'm redoing my project 2 and would like to set up the back end. 

These are the steps I am taking to recreate my backend which was initially based off of the rails-api-template:
So I figure first I'll clone my strongerBackEnd into a new local repo.
Generate new secret keys
create a new heroku app
connect my local repo to my heroku app and set the config vars accordingly
remove the old github remote origin and replace with a new remote origin.

Does this sound like a good idea? am I missing anything? will my backend work as anticipated if I do this?

Will migrating or any database things get messed up if I do this? It's been a while since I've worked with Rails. 

OR should I just be working in my original back end for project 2 but with a new ember template front end?

**Comment by cpearce31** [comment]
You can keep working on your original back-end, no need to clone or anything. See https://git.generalassemb.ly/ga-wdi-boston/capstone-project#redoing-project-two for the rest of the requirements for redoing project 2.

**Comment by ryanwk** [comment]
ok sounds good. Should I update the README to include something saying I redid the project?

**Comment by cpearce31** [comment]
No harm in adding more info to your README!
