### ISSUE TITLE
ember build error 

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#799]
I'm getting a build error with ember. 

error:
ga-wdi-boston.ember-auth/routes/exercise.js
export default Ember.Route.extend({
  model (params) {
    return this.get(â€˜storeâ€™).findRecord(â€˜exerciseâ€™, params.exercise_id);
  },
});

I noticed that my 'store' in some files is white. I think ember is having difficulty finding store?
I'm currently reading up on what might be going wrong.

**Comment by jordanallain** [comment]
> return this.get(â€˜storeâ€™).findRecord(â€˜exerciseâ€™, params.exercise_id);

what the heck is going on with this line? do you have some weird characters in there that aren't quotes or something?

**Comment by ryanwk** [comment]
yep, back tics, don't know how they got in there, but I'm going to replace all with quotes, it seems to be helping

**Comment by ryanwk** [comment]
that got rid of that error thanks
