### ISSUE TITLE
Can't connect to mongo from shell

### ISSUE THREAD

**Issue by gotwilk890** [ga-wdi-boston/capstone-project#8]

**Comment by gotwilk890** [comment]
Keeps crashing and saying connect error

**Comment by jrhorn424** [comment]
Post the exact error output. Full stracktrace if you can. Also, the exact command you ran, and a copy of the script if it was a script.

**Comment by srhoulam** [comment]
It was a combination of the startup script and being inconsistent with the mongo binary location after an OS upgrade (solved by updating and upgrading from homebrew) and a lockfile that prevented mongo from starting up.

**Comment by jrhorn424** [comment]
Sounds complicated! Thanks @srhoulam.
