### ISSUE TITLE
Trouble creating record in Ember

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/capstone-project#800]
I am trying to create a record in Ember like so:

games.js:
```javascript
export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('game');
  },
  actions: {
    createGame(game) {
      Ember.set(game, 'home', JSON.stringify(game.home))
      Ember.set(game, 'away', JSON.stringify(game.away))
      console.log(game)
      let newGame = this.get('store').createRecord('game', game)
      newGame.save()
    }
  }
});
```

I am getting a 422 Unprocessable Entity error, and when I check the request, the data being sent to the api is this:
{"game":{"date":null}}

which explains the error. The weird part though is that the console.log(game) right before the request logs game as a complete object like so:
Object {
   away: "{"team":"b"}"
   date: "2017-08-08"
   home: "{"team":"a"}"
}
and the Ember.set methods work on game as it is passed into the function.

I can't figure out why the object is being sent as {"game":{"date":null}} when I know that's not what I am passing in and would really appreciate a nudge in the right direction going into the weekend.

Thank you!

**Comment by jordanallain** [comment]
are you using rails? if so, can you add a game in the console?

**Comment by bradleyden** [comment]
Yes, I am using rails and was able to create games using the console when I was testing the show/index on the games (which is working).

I will try it again with the home and away keys since originally I just did date and let you know what happens.

**Comment by jordanallain** [comment]
maybe it just didn't like your date format? although it did seem fine.

**Comment by jordanallain** [comment]
what type do you have for the date in the schema?

**Comment by bradleyden** [comment]
create_table "games", force: :cascade do |t|
    t.date     "date"
    t.string   "home"
    t.string   "away"
    t.integer  "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_games_on_user_id", using: :btree
  end

^^That's my schema for game.
I'm using the date input built in to the form field, which has worked for me in the past in terms of formatting the date. I just can't figure out why the game object looks perfect in the console log, but then seems to send a different object in the actual ajax request.

**Comment by jordanallain** [comment]
You have a name attribute on the date input with a value of game[date]?

**Comment by payne-chris-r** [comment]
What did you tell Ember data a game's date attribute should be? Can you post the Ember model for Game?

**Comment by payne-chris-r** [comment]
Log the newly created record and see if it has date

**Comment by payne-chris-r** [comment]
It probably has to do with the model set up in that Ember doesn't think you're setting the game's date.

**Comment by payne-chris-r** [comment]
Slack me if you update this.

**Comment by bradleyden** [comment]
Thanks for the suggestions, and sorry for not getting back to you earlier-

I'm just looking back into this and am getting a new 500 error when I try to index, which wasn't happening before, so I can't get to my create game form anymore.

Hopefully I can figure out what is causing that and will update here/shoot you a slack message once I'm able to try your suggestions, or I will create a new issue if I can't figure out what's going on with index.

Thanks for your help!

**Comment by bradleyden** [comment]
Okay, I just solved the immediate issue-
My game model in Ember was set up as:
     date: DS.attr('date')
but the input field was generating a string, so by changing it to:
     date: DS.attr('string')
my data is being sent how I expect it. I'm still getting a 422, but now it is just a matter of tweaking my api to match the Ember model and expect the data as three strings rather than 2 strings and a date.
