### ISSUE TITLE
'The adapter rejected the commit because it was invalid'

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/capstone-project#802]
I am trying to create a record in Ember with a rails stack, and I recently managed to get the format of the data I'm sending to look how I want based on the way my api is set up (confirmed with console logs and the rails console), but when I try to submit the form to create a record, I am constantly getting a 422: Unproccessable entity error with this message: 'The adapter rejected the commit because it was invalid'

The data I'm sending seems to be exactly what the API expects, and I'm not sure what it means by adapter since this is a RESTful route and I haven't created an adapter for it in Ember.

I haven't seen this error before and Google has not been very helpful.

Here are as many code snippets as I think might be helpful:

Game Route:
```Javascript
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('game');
  },
  actions: {
    createGame(game) {
      let newGame = this.get('store').createRecord('game', game)
      newGame.save()
    }
  }
});
```
Ember Game Model:
```Javascript
export default DS.Model.extend({
  date: DS.attr('string'),
  home: DS.attr('string'),
  away: DS.attr('string')
});
```
Rails Create action in Game Controller:
```Ruby
def create
    @game = Game.new(game_params)

    if @game.save
      render json: @game, status: :created, location: @game
    else
      render json: @game.errors, status: :unprocessable_entity
    end
  end
```

Rails Schema for Game table:
```Ruby
create_table "games", force: :cascade do |t|
    t.string   "date"
    t.string   "home"
    t.string   "away"
    t.integer  "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_games_on_user_id", using: :btree
  end
```
Rails Game Model:
```Ruby
class Game < ApplicationRecord
  belongs_to :user
  validates :date, :home, :away, presence: true
end
```

Any ideas on where this error is coming from? I've been hung up on creating this resource for a while and I'm not sure what else to try. Thanks!

**Comment by bradleyden** [comment]
Update:

I am able to create games using the rails console, but I'm trying to use a curl script and am still getting the 422 error, so I know the issue is on the back end.

When I run the curl script, this is what I get back:
HTTP/1.1 422 Unprocessable Entity
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 318075ab-5cf8-48e1-ac95-8f9c4c24f3ea
X-Runtime: 0.012065
Vary: Origin
Transfer-Encoding: chunked

{"user":["must exist"]}

So it seems the request is being denied because I am not including the user id in the data, but I did include a token, so I'm not sure why it expects an explicit user id in the request when it doesn't for the example resource.

**Comment by bradleyden** [comment]
I tried updating the create function in the games controller to:
@game = current_user.games.build(game_params)
like it is set up in the examples controller.

Now I am getting a 500 error because current_user is not defined. The exact error is this:
NoMethodError (undefined method `games' for nil:NilClass):

I remember getting this error before, but I can't remember how to resolve it. current_user is being defined in application controller as it exists in the template, but I can't access the variable in the games controller.

I think I'm getting closer, but any help to get me over this last hump would really be appreciated.

**Comment by jordanallain** [comment]
Is your controller inheriting from open read or protected?

**Comment by bradleyden** [comment]
That was it!! It was still inheriting from ApplicationController, and that was definitely the solution when I encountered this problem back in project 2 as well. The POST request is finally working, thank you!
