### ISSUE TITLE
I can't get my exercises to show up when I click on the 'exercises' button

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#804]
I'm really struggling with Ember. I don't understand how any of it works. 
I've closely studied and attempted to follow the steps outlined in the ember-resources docs.
I have also reviewed ember-routing & components docs.
I have been consistently referencing my work against the commit history and code from the ember-resources training that had we completed in class. My squad and I were able to accomplish CRUD on examples. I can't even get the product of a GET request, to view a user's exercises, to work. 

I'm not getting any errors when you click on the 'exercises' button and none of the exercises appear.
The console seems to be telling me I've done the API request successfully. 
XHR finished loading: GET "http://localhost:4741/exercises".

components/exercise-list/card.js
```js
import Ember from 'ember';

export default Ember.Component.extend({
});
```
models/exercise.js:
```js
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  weight: DS.attr('integer')
});
```
routes/exercises.js
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('exercise');
  },
});
```
templates/components/exercises.hbs
```js
<h2>Exercises</h2>

<ul>
  <li>Exercise name: {{exercise.name}}</li>
{{#each model as |exercise|}}
  {{exercise-list/card exercise=exercise }}
{{/each}}

</ul>
{{#link-to "application"}} home {{/link-to}}

{{!-- <li>{{exercise.weight}}</li> --}}
```
templates/componenets/my-application.js
```js
      <ul class="nav navbar-nav">
        {{#if isAuthenticated}}
        <li>{{#link-to "users"}}Users{{/link-to}}</li>
        <li>{{#link-to "exercises"}}Exercises{{/link-to}}</li>
        {{/if}}
      </ul>
```

router.js
```js
Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('exercises');
});
```
backend exercise schema:
```js
  create_table "exercises", force: :cascade do |t|
    t.string   "name"
    t.integer  "weight"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
    t.index ["user_id"], name: "index_exercises_on_user_id", using: :btree
  end
```

At this point, I'm seriously considering scrapping this project idea altogether and building something different with tools that I understand how to use.

**Comment by payne-chris-r** [comment]
What happened to the previous issue like this? Stay focused. Stay calm. We got this. What's the immediate problem at hand? Does the curl request work? What request is Ember making?? Is it hitting the API at all? Try leaving the button outside of an isAurhenticated if statement so you can just see it.

**Comment by ryanwk** [comment]
I thought my previous issue might have stemmed from not being methodical. Previously, I was trying to make the ember-resources code from class work by swapping out "example" with "exercise" without really understanding why and how each piece came together. So, I took a step back and started from square one while following the ember resource documentation step by step. I spent most of the day reviewing ember docs and various ember lessons from last week in an attempt to learn more about how Ember works (still don't understand how ember works). This led me to my current issue which, interestingly, is the same place I got stuck before. 

Moved the button out of the isAuthenticated if statement. Still receiving the same error.
When the "exercises" button is pressed, console says this ```http://localhost:4741/exercises```, so Ember is making a GET request, which is good. It seems successful which makes me think this is a problem on the front end because the result of my GET request renders nothing that I would expect it should within the exercises view. 

I ran a curl script to create an exercise with the token of a user who is signed in, to ensure that there is an exercise in the database for this user. Then, I ran a curl script to get that user's exercises, which was successful. So, back-end seems to be working fine in that respect. 

The immediate problem at hand is unclear. My console is not giving me any failed requests or explicit errors. I do, however, recieve a red modal informing me that something went wrong whenever I press the "exercises" button. If successful, when a user presses this button, one should be brought to a view that displays a list of all of the current user's exercises. This doesn't occur.

**Comment by ryanwk** [comment]
Alright, found the culprit:

```js
models/exercise.js:

import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  weight: DS.attr('integer')
});
 ```
So, ```weight: DS.attr('integer')```, needed to be ```weight: DS.attr('number')```.


My main gripe with Ember at this point is that it failed to present any meaningful error handling when debugging this issue.
