### ISSUE TITLE
having difficulty w/ CRUD for a resource 

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#805]
I set up a resource called "routines" following the rails one-to-many documentation:
https://git.generalassemb.ly/ga-wdi-boston/rails-api-one-to-many

My local host returns an empty object for routines, so it seems to have gone well. Now, I'm trying to perform CRUD actions to test the resource before moving on. I'm using curl scripts and the terminal. 

The terminal presents me with this error:

$ TOKEN=BAhJIiVmZDJlYjAzMTJjNmFkNmJkODFhYjFiMTczNjA2OTE5ZQY6BkVG--f6cd3bed2a4aabef738a9a1a6ec83320b588618d  sh scripts/create-routine.sh 
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
X-Request-Id: dcc09770-5ab2-4a7b-b284-ee3a313304bd
X-Runtime: 0.034793
Vary: Origin
Content-Length: 11713

{"status":500,"error":"Internal Server Error","exception":"#\u003cNoMethodError: undefined method `routines' for #\u003cUser:0x007fa753d78ca8\u003e\u003e","traces":{"Application Trace":[{"id":1,"trace":"app/controllers/routines_controller.rb:18:in `create'"}],"Framework Trace":[{"id":0,"trace":"activemodel (5.0.1) lib/active_model/attribute_methods.rb:433:in `method_missing'"},{"id":2,"trace":"actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'"},{"id":3,"trace"...etc..etc..

what does this mean?
undefined method `routines'

curl script:
```sh
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/routines"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "routine": {
      "name": "upperbody",
      "date": "05-12-1992"
    }
  }'

echo
```

controller: 

```rb
class RoutinesController < OpenReadController
  before_action :set_routine, only: [:show, :update, :create, :destroy]

  # GET /routines
  def index
    @routines = Routine.all

    render json: @routines
  end

  # GET /routines/1
  def show
    render json: Routine.find(params[:id])
  end

  # POST /routines
  def create
    @routine = current_user.routines.build(routine_params)

    if @routine.save
      render json: @routine, status: :created, location: @routine
    else
      render json: @routine.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /routines/1
  def update
    if @routine.update(routine_params)
      render json: @routine
    else
      render json: @routine.errors, status: :unprocessable_entity
    end
  end

  # DELETE /routines/1
  def destroy
    @routine.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_routine
      @routine = current_user.routines.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def routine_params
      params.require(:routine).permit(:name, :date)
    end
end
```

I've played around with changing the before_action and create method in my routine controller to no avail.

**Comment by payne-chris-r** [comment]
What controller action is it hitting?

**Comment by ryanwk** [comment]
I'm not sure. I put logs under each method (index, show, create, etc) rails doesn't like logs. 

here's my server:
```
NameError (undefined local variable or method `console' for #<RoutinesController:0x007fa7558b0598>):
  
app/controllers/routines_controller.rb:7:in `index'
Started GET "/routines" for 127.0.0.1 at 2017-08-28 09:57:36 -0400
Processing by RoutinesController#index as HTML
  Routine Load (0.7ms)  SELECT "routines".* FROM "routines"
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Json (0.54ms)
Completed 200 OK in 11ms (Views: 3.0ms | ActiveRecord: 3.0ms)


Started POST "/routines" for 127.0.0.1 at 2017-08-28 09:57:42 -0400
Processing by RoutinesController#create as */*
  Parameters: {"routine"=>{"name"=>"upperbody", "date"=>"05-12-1992"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "64e7d46ad2a1c272223d14ed3ec0f24d"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 19ms (ActiveRecord: 1.9ms)

NoMethodError (undefined method `routines' for #<User:0x007fa7512bb470>):
``` 

The curl script uses a POST which is create and my route is correct ```/routines```

The error message tells me there's something wrong with line 57: 
```:[{"id":1,"trace":"app/controllers/routines_controller.rb:57:in `set_routine'"}],"Framework Trace":[{"id":0,"trace":"activemodel (5.0.1) lib/active_model/attribute_methods.rb:433:in `method_missing'"}```

In looking at line 57, I'm not sure what it means or what to modify? 
```rb
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_routine
      @routine = current_user.routines.find(params[:id])
    end
```

my server says there is no method called 'routines':

```
NoMethodError (undefined method `routines' for #<User:0x007fa7512bb470>):
```
I've compared my routine-controller with my exercise and example controller 
I have no idea what line 57 should look like and how to define a method called 'routines'

**Comment by scottyscripts** [comment]
So undefined method `routines` for User. It looks like on line 57 you are trying to say current_user.routines. This will only work if you set up and ActiveRecord relationship in your model. Can you post your model for routines and user? You could only say, User.routines (current_user.routines) if a user has many routines.

**Comment by ryanwk** [comment]
```rb
class Routine < ApplicationRecord
  belongs_to :user
  # has_many :exercise
end

# frozen_string_literal: true
class User < ApplicationRecord
  include Authentication
  has_many :exercises
end
```
i changed it to this:
```rb
class User < ApplicationRecord
  include Authentication
  has_many :exercises
  has_many :routines
end
```
and changed 57 to this: 
```rb
    # Use callbacks to share common setup or constraints between actions.
    def set_routine
      @routine = current_user.routines
    end
```
then ran curl script again, now it doesn't recognize create, I think? 

```rb
{"status":500,"error":"Internal Server Error","exception":"#\u003cActiveModel::UnknownAttributeError: unknown attribute 'user_id' for Routine.\u003e","traces":{"Application Trace":[{"id":15,"trace":"app/controllers/routines_controller.rb:19:in `create'"}]
```

changed create to look like this: 
```rb
  def create
    @routine = current_user.routines
```

**Comment by ryanwk** [comment]
Scott helped me understand my routines join table, and allowed me to see that I need to correct my routine schema and model and any affected controller methods

**Comment by payne-chris-r** [comment]
`      @routine = current_user.routines`
Is probably not correct.
