### ISSUE TITLE
Question about Capstone Requirements

### ISSUE THREAD

**Issue by kailinc** [ga-wdi-boston/capstone-project#806]
1. It said that a user needs to have CRUD actions on a resource. For my e-commerce project, a user's resource is cart. You can add, remove, and update things to cart. Once you pay, the attribute 'paid' becomes true. It doesn't make sense to delete cart to store history for the business and the user. To meet requirements, should I just have the delete action in the API and in the front end, I don't give use the action?

2. In previous projects, we always had to make the user sign up before interacting with our site. For my project, is it fine for guests (people not logged in) to add items to their cart and on check out they have to sign in to pay?

**Comment by payne-chris-r** [comment]
1. The 'remove' of something from the cart will be enough, as long as there is an additional update (like quantity).
2. Yes. You could also (to your question 1.) make the DELETE be the deleting of their cart if they opt not to sign in/checkout.

**Comment by kailinc** [comment]
1. Thanks got it!

2. For carts, I set it up like Example Resourece that user must be logged in and own the resource to delete it. I can gather the info on the front end for people not logged in and delete it in the front end. So that won't work. To overcome this, people signed in can have the option to clear their cart. That in turn would delete that cart. Will that work?

**Comment by scottyscripts** [comment]
That would absolutely work. Sounds like a great solution!

**Comment by kailinc** [comment]
nice! thanks @payne-chris-r @sdavidson140
