### ISSUE TITLE
many to many 

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#807]
I've closely followed the steps outlined in the rails-one-to-many docs and have read through the rails many-to-many docs. 

I'm trying to set up routine so that it has a many to many relationships with exercises.
Exercises have many routines and routines have many exercises
Users have many routines and users have many exercises

I set up my routine entity like so:
```js
class Routine < ApplicationRecord
  belongs_to :user
  # has_many :exercise
end

class Exercise < ApplicationRecord
  belongs_to :user
  # has_many :routine
end

```

routine schema
```js
create_table "routines", force: :cascade do |t|
    t.string   "name"
    t.date     "date"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
```

Read these:
https://git.generalassemb.ly/ga-wdi-boston/rails-api-one-to-many
https://github.com/ga-wdi-boston/rails-api-single-resource
http://guides.rubyonrails.org/association_basics.html

could someone push me in the right direction with how to achieve the many-to-many relationship here? 

I think I need to get routines to hold foreign keys for exercises and users.

**Comment by scottyscripts** [comment]
With a many to many relationship you do need a join table. Can you post a pic of your ERD for what you are trying to achieve? Rememeber how we set up the `has many through` relationships. You are heading in the right direction having a table that holds ids of two other tables, if routines is indeed what you want your join table to be. take a look here how we did it with loans, books, and borrowers. https://git.generalassemb.ly/ga-wdi-boston/rails-api-many-to-many

**Comment by ryanwk** [comment]
![image](https://user-images.githubusercontent.com/19196821/29775768-7111477e-8bd4-11e7-876b-14252d0581de.png)

**Comment by scottyscripts** [comment]
okay so in this instance you wouldn't want the crows feet directly from users to exercises if you have them going to routine as well. `Users --< Routines >-- Exercises`. So routines is acting as a join table between users and exercises. This establishes the 'Users have many exercises through routines' and 'Exercises have many Users through routines'. So From the rails docs, your `routines` table is like their manifests table http://guides.rubyonrails.org/association_basics.html#choosing-between-has-many-through-and-has-and-belongs-to-many

**Comment by ryanwk** [comment]
so routines is a join table?

**Comment by ryanwk** [comment]
Scott helped me understand my routines join table, and allowed me to see that I need to correct my routine schema and model and any effected controller methods
