### ISSUE TITLE
Flash messaging in ember

### ISSUE THREAD

**Issue by Azinck94** [ga-wdi-boston/capstone-project#808]
Hi guys, currently working on getting flash messaging up and running for all of my crud actions in my app, and have been generally following the trail that you guys employed in ember-auth-template for sign up message handling. From what I have read and gathered, I think that I need to inject that service into my route, as you guys did in the Application.js route with the following syntax:
```
export default Ember.Route.extend({
  auth: Ember.inject.service(),
  flashMessages: Ember.inject.service(),

  actions: {
    signOut () {
      this.get('auth').signOut()
        .then(() => this.get('store').unloadAll())
        .then(() => this.transitionTo('sign-in'))
        .then(() => {
          this.get('flashMessages').warning('You have been signed out.');
        })
        .catch(() => {
          this.get('flashMessages')
          .danger('There was a problem. Are you sure you\'re signed-in?');
        });

**Comment by Azinck94** [comment]
Now, I have tried injecting service in my customers.js route in the same manner like so:
```
import Ember from 'ember';

export default Ember.Route.extend({
  flashMessages: Ember.inject.service(),

  model (params) {
    return this.get('store').findAll('customer');
  },
  actions: {
    createCustomer (customer) {
      let newCustomer = this.get('store').createRecord('customer', customer);
        newCustomer.save();
        .then(() => {
          this.get('flashMessages').warning('You have been signed out.');
    },
    deleteCustomer (customer) {
      customer.destroyRecord();
     }
  },
});

**Comment by Azinck94** [comment]
But this is leading to a build error on the route. I can resolve this error by commenting out the .then function like so:
```
  actions: {
    createCustomer (customer) {
      let newCustomer = this.get('store').createRecord('customer', customer);
        newCustomer.save();
        // .then(() => {
        //   this.get('flashMessages').warning('You have been signed out.');
    },

**Comment by Azinck94** [comment]
But this leaves me back to square one, so TL:DR --> I know how to inject the service, but am struggling to incorporate a working .then function in the create customer action....Any advice or pointers on something I may be missing would be appreciated, as I think getting this done for create will make it quite easy to replicate the process for destroy and edit messaging. Thanks, Yall!

**Comment by scottyscripts** [comment]
You are definitely going in the right direction by injecting that service. What is your exact error happening? have you tried taking a look at what `this.get('flashMessages')` looks like, perhaps by logging it? Make sure `this` is what you expect it to be in this context.

**Comment by Azinck94** [comment]
Thanks Scripts! Here is what I am running with:
```
actions: {
    createCustomer (customer) {
      let newCustomer = this.get('store').createRecord('customer', customer);
        newCustomer.save();
        this.get('flashMessages')
        console.log(this)
    },

**Comment by Azinck94** [comment]
the console log produces the following:
```
Class {routeName: "customers", fullRouteName: "customers", _handlerName: "customers", _names: Array(0), connections: Array(1), …}

**Comment by scottyscripts** [comment]
try logging it inside the `.then` is `this` still referring to the same thing??

**Comment by Azinck94** [comment]
```actions: {
    createCustomer (customer) {
      let newCustomer = this.get('store').createRecord('customer', customer);
        newCustomer.save()
        .then(() => {
          this.get('flashMessages').warning('You have been signed out.')
          console.log(this)
        }
    },

**Comment by Azinck94** [comment]
^that produces another build error

**Comment by Azinck94** [comment]
```
Dang! Looks like a Build Error.

ga-wdi-boston.ember-auth/routes/customers.js

          console.log(this)
        }
    },

    deleteCustomer (customer) {
      customer.destroyRecord();

**Comment by Azinck94** [comment]
hold the phone, big dummy alert! I forgot to close the " .then(() => { " with a closing parenthese!

**Comment by jordanallain** [comment]
✋ 📞

**Comment by Azinck94** [comment]
this produces a similar if not identical console log:
``` 
Class {routeName: "customers", fullRouteName: "customers", _handlerName: "customers", _names: Array(0), connections: Array(1), …}

**Comment by jordanallain** [comment]
did you try to console.log `this.get('flashMessages')` as scripts suggested earlier? or is that console.logging `this` ?

**Comment by Azinck94** [comment]
Sorry! unaware that was what he was suggesting, my bad. Thought he just wanted me to check on what this was by console logging, will retry now

**Comment by Azinck94** [comment]
Got it working! Thanks, think it was just being slow for some weird reason but now have the message appearing when I create a customer
