### ISSUE TITLE
(Backend) Waterline can't connect to PostgreSQL

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/capstone-project#81]
**_Time used before posting: 8hrs.+**_
**_Resources:**_ Waterline Doc, PostgreSQL Waterline Adapter, Google, StackOverflow
## Location of documentation

[PostgreSQL Waterline Adapter](https://github.com/waterlinejs/postgresql-adapter)

[Water Line Docs](https://github.com/balderdashy/waterline-docs)

[Water Line Example Used](https://github.com/balderdashy/waterline-docs/blob/master/examples/src/getting-started.js)

[StackOverFlow Helpful Quesiton](http://stackoverflow.com/questions/21866476/how-to-set-database-connection-string-in-waterline-orm)

**_DataBase:**_ Postgres DB versions: 9.4
**_STACK:**_ NodeJS, Express, Postgres,
**_ORM:**_ Waterline (Subject to change)*

---
## What is he trying to do???

So am trying to use Waterline with the [PostgreSQL Waterline Adapter](https://github.com/waterlinejs/postgresql-adapter) to insert a hard coded entrys into my Postgres database. The location that I want to have this entry be inserted into is `homestatus` database. By the user `pi`. (`pi` doesn't have a password. I am hoping that it might make things easier )

On my way to solving this issue I was able to create an entry and put it into memory using (`sails-memory`) Package. [CODE: INTO MEMORY](https://gist.github.com/edesilets/7ab484b92a0ed8b865f8)
## What is going wrong???

I now wanted to insert this entry into the DB. [CODE: INTO DB](https://gist.github.com/edesilets/91d5d99f91cf47c5d80c) When I use this code I get the error of 

``` Bash
Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - error: password authentication failed for user "postgres"
[Error: Pool was destroyed]
```

So I know I am setting up the connection wrong. I read through the DOCS on [PostgreSQL Waterline Adapter](https://github.com/waterlinejs/postgresql-adapter). They say "O, put your connections code in `config/connections.js`" so I did. I put in the root of my project dir. Same error. So after a couple of hours trying to figure this out I did the unthinkable!!!! (FOR TESTING ONLY) I modified the node module default params for to have my connection details. [CODE: NPM HACK LINE 45](https://gist.github.com/edesilets/0498ef83352c1b80779f)  **_Even after the hack. I still receive the following error...**_ 

``` Bash
Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - error: password authentication failed for user "postgres"
[Error: Pool was destroyed]
```
## Other important Information

``` Bash
pi@node:~/thermal-comfort-system-api $ psql -h localhost -p 5432 -U pi -W pi
Password for user pi:
psql (9.4.6)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

pi=#
```
#### What the DBs are...

| Name | Owner | Encoding | Collate | Ctype | Access privileges |
| --- | --- | --- | --- | --- | --- |
| homestatus | pi | UTF8 | en_GB.UTF-8 | en_GB.UTF-8 |  |
| pi | postgres | UTF8 | en_GB.UTF-8 | en_GB.UTF-8 | =Tc/postgres  postgres=CTc/postgres pi=CTc/postgres |
| postgres | postgres | UTF8 | en_GB.UTF-8 | en_GB.UTF-8 | =Tc/postgres postgres=CTc/postgres pi=CTc/postgres |
| template0 | postgres | UTF8 | en_GB.UTF-8 | en_GB.UTF-8 | =c/postgres postgres=CTc/postgres |
| template1 | postgres | UTF8 | en_GB.UTF-8 | en_GB.UTF-8 | =c/postgres postgres=CTc/postgres |
| test1 | postgres | UTF8 | en_GB.UTF-8 | en_GB.UTF-8 |  |

**Comment by gaand** [comment]
What happens if you run the psql line and type `password` at the password prompt?  Does it fail?  I ask, because your gist shows you passing with the connections information `password: 'password'`.

**Comment by edesilets** [comment]
Whoops forgot to mention that the password used in 'Other important Information' is `password`.

Log in is successful. 

**_Updated Post**_*

 [CODE: NPM HACK LINE 45](https://gist.github.com/edesilets/0498ef83352c1b80779f)  **_Even after the hack I receive the error...**_ 

``` Bash
Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - error: password authentication failed for user "postgres"
[Error: Pool was destroyed]
```

**Comment by gaand** [comment]
I'm confused.  Your parenthetical from **What is he trying to do???** says "pi doesn't have a password. I am hoping that it might make things easier".

When you run psql are you typing in "password" at the prompt? 

I don't think it can be both.

**Comment by edesilets** [comment]
Whoops i was wrong i did end up putting a password of `password` on user: `pi` and it still doesn't work. Nor does the error change from 

``` Bash
Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - error: password authentication failed for user "postgres"
[Error: Pool was destroyed]
```

to 

``` Bash
Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - error: password authentication failed for user "pi"
[Error: Pool was destroyed]
```

**Comment by edesilets** [comment]
@MattB-GA-Boston  and I got to an actual error after this point. [Gist: new adapter error](https://gist.github.com/edesilets/8de2b1a52eb3cd244bb2ca4c4a272ed7)
We did `sudo -u postgres psql` then

``` sql
ALTER USER postgres WITH PASSWORD 'postgres';
```

This satisfied the default connection requirements within the `waterline-postgresql` adapter.js files. The error now being produced is [Gist: new adapter error](https://gist.github.com/edesilets/8de2b1a52eb3cd244bb2ca4c4a272ed7)

**Comment by jrhorn424** [comment]
This is an exemplary issue. I might crib this format and suggest others follow it in the future.

@edesilets Since you've gone with bookshelf.js, can we resolve this issue?

I'm happy to walk through debugging Waterline further if you wish.

**Comment by edesilets** [comment]
Issue resolved.

Resolution: Use bookshelf.js instead of waterline.
