### ISSUE TITLE
Displaying date

### ISSUE THREAD

**Issue by jbculbertson** [ga-wdi-boston/capstone-project#811]
I'm trying to figure out a way to display a date in a more readable way.  Currently it looks like this: 2017-08-27T16:49:45.348Z, and I'd love to convert that to something more user friendly.

I've tested the NPM package Moment, which does a great job, and I've gotten it to work in my file, but the issue I'm having is trying to get that into my handlebars template.

Here is the helper I'm attempting to register on my index.js.  My understanding is that after I do this, I can then call the helper (in this case its called 'formatDate' in my handlebars template.  

``` js
Handlebars.registerHelper('formatDate', function (date) {
    return (moment(date).format('MMMM DD YYYY'))
  })
```
But I'm getting errors.  Index doesn't know what Handlebars is, so even though the browser template comes with handlebars, I need to require it here, which feels a little weird.  Even then, trying to call this helper breaks my view, snippet below.  Nothing renders.

```js
<strong>{{run.ownerName}}</strong> ran <strong>{{run.distance}}</strong> miles{{formatDate run.date}}</div>
```
Does anyone have experience adding a Handlebars helper within browser template?

**Comment by jordanallain** [comment]
Here's a really simple helper I made:

i put this in my index.js document ready function because i had a blank repo and didn't want to make a bunch of files

 ```js
const templateCustom = require('./templates/sample.handlebars')

$(() => {
  $('.banana').html(templateCustom({
    val: 'dog'
  }))
})
```

that template is here:

```handlebars
{{#custom val}}
{{/custom}}
```

the `custom` helper i wrote lives in the helper folder and you don't need to register it:

```js
'use strict'

const custom = (val) => {
  if (val === 'cat') {
    return 'true'
  } else {
    return 'false'
  }
}

module.exports = custom
```

and thats it! had a blank div in my html with class=banana, but otherwise just needed those three bits

 ```js
$('.banana').html(templateCustom({
    val: 'dog'
  }))
```

when i change that val to cat it returns the string 'true' to my template, any other string will make it return 'false'

**Comment by jbculbertson** [comment]
many thanks Jordan - let me check this out

**Comment by jbculbertson** [comment]
awesome, this worked.  I should have suspected that the 'helpers' folder on browser template would have done some of the work to register this as a helper.  

For anyone in the future, this was too easy - add a helper function in the folder as Jordan mentions, and then you can call that function within your template.  I added Moment to my project, which made the process even easier.

My helper:
```js
'use strict'

const moment = require('moment')

const formatDate = (date) => {
  return moment(date).format('MMMM DD YYYY')
}

module.exports = formatDate
```
Calling it within my template:
```js
{{#formatDate run.date}}
           {{/formatDate}}
```
