### ISSUE TITLE
fix schema

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#812]
It's been a while since I've used rails. Since I am redoing project 2 I am using my old backend that has a one to many relationship between users and exercises. My new concept requires a ```routines``` join table. Users have many exercises through routines.  

So far I've ran into some difficulty utilizing my current schema in an attempt to perform CRUD actions over a routine entity. These issues are outlined here: 
https://github.com/ga-wdi-boston/capstone-project/issues/807
https://github.com/ga-wdi-boston/capstone-project/issues/805

this is my goal:
Remove user_id from exercises schema
Add user_id and exercise_id to routines schema

Set up model to reflect those changes:
User has many routines
User has many exercises through routines
Routines belongs to users
Routines belongs to exercises
Exercise has many routines and 
Exercise has many users through routines

This is my current schema: 
```rb
  create_table "exercises", force: :cascade do |t|
    t.string   "name"
    t.integer  "weight"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
    t.index ["user_id"], name: "index_exercises_on_user_id", using: :btree
  end

  create_table "routines", force: :cascade do |t|
    t.string   "name"
    t.date     "date"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", force: :cascade do |t|
    t.string   "email",           null: false
    t.string   "token",           null: false
    t.string   "password_digest", null: false
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.index ["email"], name: "index_users_on_email", unique: true, using: :btree
    t.index ["token"], name: "index_users_on_token", unique: true, using: :btree
  end
```

I've read about many to many relationships here:
http://edgeguides.rubyonrails.org/active_record_migrations.html
https://git.generalassemb.ly/ga-wdi-boston/rails-api-many-to-many

I have been trying to figure out how to remove the user_id foreign key from my exercises table so that I can then add the foreign keys ```exercise_id and user_id``` to my ```routine``` table.  

I've found these resources related to how to achieve that goal: 
http://api.rubyonrails.org/v4.2/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_foreign_key
https://stackoverflow.com/questions/23718292/foreigner-remove-foreign-key
https://stackoverflow.com/questions/5648970/rails-migration-with-adding-and-removing-reference

I threw this in the terminal and that didn't work:
```
 remove_foreign_key :exercises, name:user_id
```

should I roll back a migration to the point where I had added the user_id reference? If so, how do I do this?
should I drop the DB, start over and set up the entities according to my new concept? If so, how do I do this?

I'm terrified of blowing up my back end and starting over, please advise.

**Comment by scottyscripts** [comment]
so it sounds like you want to `run a migration to remove a column from a table`. I think this is what you are looking for https://stackoverflow.com/questions/38820188/rails-5-how-to-remove-a-column-from-a-database

**Comment by scottyscripts** [comment]
even if you dropped your database all of those migrations would still exist. Rather than rolling back and deleting migration files (that can lead to craziness and is generally bad practice), you can generate new migrations that will remove the columns you don't need and add the ones you do

**Comment by ryanwk** [comment]
Ok, so I can remove a column from the exercises table with something like this ```rails g migration RemoveUserFromExercises user_id:integer``` and then try to generate a migration that adds a foreign key to routines for exercises and user with something like this ``` rails generate migration AddExerciseRefToRoutine exercise: references``` 
and ```rails generate migration AddUserRefToRoutine user:references`` `

or I can drop the database and run a migration for exercises with the appropriate columns and then run a migration for routines with the appropriate columns (including foreign keys for exercises and user). 

Which approach do you recommend?

**Comment by scottyscripts** [comment]
you are on the right track with the first approach. For `RemoveUserFromExercises user_id:integer` you can say user instead of user_id. It is not an integer type though. It is `references`. Go the first approach though. This way you keep a record of what you have done.

**Comment by ryanwk** [comment]
ok, so I have the schema and models updated to reflect the changes we discussed. I've migrated all looks well. I just ran the curl script to create an exercise and got a new error. I'll open a new issue with that error, thank you Scott!
