### ISSUE TITLE
ActionController::RoutingError: uninitialized constant in Rails

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/capstone-project#813]
I seem to be getting a routing error that I can't figure out in Rails-

I created a resource for plate appearances but get this error when I try to run a basic index request through the browser (with http://localhost:4741/pas)

Looking online, it seems like this is almost always an error caused by a misspelled filename, but I've been looking for a while now and can't find what the problem is.

Rails router:
```Ruby
Rails.application.routes.draw do
  resources :pas
  resources :games
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```

pas-controller.rb
```Ruby
class PasController < ProtectedController
  before_action :set_pa, only: [:show, :update, :destroy]

  # GET /pas
  def index
    @pas = Pa.all

    render json: @pas
  end

  # GET /pas/1
  def show
    render json: @pa
  end

  # POST /pas
  def create
    @pa = Pa.create(pa_params)

    if @pa.save
      render json: @pa, status: :created, location: @pa
    else
      render json: @pa.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /pas/1
  def update
    if @pa.update(pa_params)
      render json: @pa
    else
      render json: @pa.errors, status: :unprocessable_entity
    end
  end

  # DELETE /pas/1
  def destroy
    @pa.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pa
      @pa = Pa.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pa_params
      params.require(:pa).permit(:inning, :batter, :pitcher, :runs, :outs, :errors, :result, :game_id)
    end
end
```

Any idea why I can't get this error to go away?  I've checked my file naming pretty carefully and have restarted the rails server, and I can't really progress on getting the CRUD for this resource done as long as I get a 404 for every request I send.

Thank you!

**Comment by scottyscripts** [comment]
can you update with the full error appearing in your rails console?

**Comment by bradleyden** [comment]
Actually just figured this one out. I could've sworn the dash was an underscore all morning but I just checked again and that was the problem. changing pas-controller.rb to pas_controller.rb fixed it.
