### ISSUE TITLE
Getting confused on foreign keys

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/capstone-project#814]
I am getting confused on this foreign key bit.  A user can  have multiple vegetables in their garden so it seems to me that I would rails generate AddVegetableToUsers vegetable:belongs_to.  

In my project two, I did it the exact opposite and it worked fine; AddUserToMovies. I added users to movies and you can see a list of movies belonging to that user.  

Maybe someone can help me sort out why I am thinking about this backwards?

**Comment by jordanallain** [comment]
If a user can have many vegetables, would it make sense to store a bunch of vegetable ID's on one user? or just a user ID once on each vegetable?

**Comment by 3point14guy** [comment]
So, you can retrieve all the veggies with user ID xxx the second way. How is that different from having multiple vegetable IDs stored with each user and you retrieve all the veggie IDs from that user?  You either have a bunch of veggie IDs or a bunch of user IDs.  You are only going to have a few dozen vegetables, but a real website could have tens of thousands of users.

**Comment by jordanallain** [comment]
well one reason is that you can't store arrays in SQL. So if you have one row that represents one user in the user table, how else could you store multiple veggie ID's on that one user?

if each veggie has a column for user_id, it means we can just store the user_id on multiple veggies.

**Comment by payne-chris-r** [comment]
Remember, if you're ever having the "I'll just store an array in this field" thought you've probably inverted your relationship!

**Comment by 3point14guy** [comment]
Sorry, I feel like I lost something fundamental in the weeks since we went over this in class.  Why won't we end up with an array of user IDs in the Veggie table this way?

**Comment by 3point14guy** [comment]
Besides the fact that we can't have arrays in SQL...

**Comment by jordanallain** [comment]
each veggie only takes up one row, one of the columns of the row is for a singular user_id

**Comment by 3point14guy** [comment]
After talking with Scott, it turns out the way I set up project two was a slightly different use case, but I was trying to think about it in the same way.  I had users that had the same movie in their lists, but only because they created that movie in their lists independently.  It gave the appearance of multiple users having the same resource.  This time, users are choosing from the same list of resources so I need a join table to accomplish multiple users all having the same veggies.
