### ISSUE TITLE
Error when making initial push to heroku 

### ISSUE THREAD

**Issue by Fcarrion001** [ga-wdi-boston/capstone-project#815]
I am using the rails-api-template as my backend
I downloaded and renamed the file and bundle installed

This is the heroku error
```heroku
No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
```
Upon investigation I found a command that will allow me to set the buildpack for ruby 
```sh
heroku buildpacks:set heroku/ruby
```
Before using this though I wanted to create this issue to be sure I should do this given that it was not necessary before, and I do not want to blow my project up

**Comment by scottyscripts** [comment]
I am assuming that you followed all of the steps in https://git.generalassemb.ly/ga-wdi-boston/rails-heroku-setup-guide . Make sure that you are in the correct repo when pushing as well. Could you just verify that for me quick. Also make sure you bundle install first. make sure you have an initial commit.

**Comment by Fcarrion001** [comment]
Yes Ive been following both the rails-api-template setup guide and the guide you linked above.
I just double checked and I am in the correct repo, I have an initial commit, and I have bundle installed. 

However, my initial commit only has the README.md in it I will commit and push the rest of the template now and see if that makes a difference

**Comment by Fcarrion001** [comment]
That worked thank you
