### ISSUE TITLE
1 on 1 for discussion over scope and method

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/capstone-project#816]
In my web app, I have a rails resource for Loans. Each Loan has a set of properties that will need to be entered in by a user and a set of properties that can be gathered from the manually entered properties through some mathematical equations. I am trying to figure out whether to store those implied properties on the back end or the front and how those calculations would take place on the front.

Can I get a few minutes with a consultant to figure out the best strategy?

Detailed view of Loan Resource

Loan
Manually entered
- Principal (P)
- Interest rate (R)
- Length of loan (L)
- Current Payment (CP)

Implied
- Minimum Monthly Payment (MP) = (P x R) / [1 - (1 + R)^(-n)
- MP going toward interest (IMP) = MP + (1 + R)^(n-1) x (P x R - MP) 
- MP going toward principal (PMP) = MP - PMP
- Total Amount over life of loan (Ta) = (MP x L)
- Total Interest over life of loan (Ti) = (MP x L) - P
- Period (N) = Period of the loan
- Revised loan length (nL) = ???
- Custom Payment going toward principal (PCP) = PMP + (CP - MP)
- Remaining Balance (Rb) = P - (PMP x N)
- Custom Remaining Balance (CRb) = P - (PCP x N)

**Comment by payne-chris-r** [comment]
You prrrobably want your BE to handle the calculations. They should happen in the serializer if they change frequently (or change with time), or in the controller and stored in the db if they change infrequently (like on input and never again).

They're kind of like virtuals, right? I think the serializer is the right place for them.

**Comment by CoreyFedde** [comment]
So on creation of a Loan, the back end runs the input data through the equations to create virtuals that could be shown in a handlebars template?

I was originally hoping to allow users that were not signed in to manually enter the data for a loan and see the results, but if the calculations are done on the BE, that would likely only be available for users that are signed in, right? Probably a bad idea to allow users to create loans on the back end without auth?

**Comment by payne-chris-r** [comment]
Not necessarily. You could create a new loan in the BE and get the "virtuals" back. Kinda depends on the UI flow. I'm thinking:

**Comment by payne-chris-r** [comment]
IF authenticated CREATE req, current_user.loan create, etc
Can get it back, yadda yadda yadda
All of this is like normal ^ 
IF unauth CREATE req, loan.create -> serialize out with virtuals

**Comment by payne-chris-r** [comment]
If you're not sure how to check for auth/not I can help you. If you don't want to SAVE the random non-authenticated user's loan, that's fine. I think with this kind of app idea, saving that data mayyyy be advantages down the line for your "business"

**Comment by CoreyFedde** [comment]
This makes more sense. I was originally thinking of trying to delete the newly created loan after the non-authenticated users left the page, but it might be easier and more advantageous for the "business", like you said, to just keep them in the database with no user_id referenced. 

I might check back in with you when I get to the check for auth/unauth section.

Thanks

**Comment by payne-chris-r** [comment]
You can do what you've said--it would be really cool. Easy to do in Ember. But either way you should solve this problem first--THEN that one.

**Comment by payne-chris-r** [comment]
*easier
