### ISSUE TITLE
Trouble with creating virtual attributes

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/capstone-project#819]
I'm pretty lost on creating virtual attributes in Rails. Can I get some assistance or a point in the right direction?

**Comment by CoreyFedde** [comment]
What I have so far: You can add an attribute in the serializer that is not in the schema and define it  by use attributes that are defined. The big question is whether these should stay in the serializer or the model.

**Comment by CoreyFedde** [comment]
Update: defining any of the "virtuals" in the serializer with object.attribute make it null or throw a 500 server error.

**Comment by jordanallain** [comment]
did you define the virtual as a method in the serializer or your class? any relevant code?

**Comment by scottyscripts** [comment]
can you post the code throwing the error in your serializer??

**Comment by CoreyFedde** [comment]
Yes, it was a method in the serializer. Most sources online point to putting virtual attributes in the model, so I moved it. It is currently working when I return an attribute, but is not working right now with an equation I am trying to enter.

```ruby
class Loan < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'

#reader_attr
  def monthly_payment
    self[:monthly_payment]
  end
# virtual attribute
  def monthly_payment
    ([principal] x [interest_rate]) / (1 - (1 + [interest_rate])^(-1))
  end
end
```

**Comment by CoreyFedde** [comment]
Controller
```ruby
  def loan_params
      params.require(:loan).permit(:name, :lender, :principal, :interest_rate, :loan_length, :start_date, :minimum_monthly_payment, :current_monthly_payment, :monthly_payment)
    end
```

**Comment by CoreyFedde** [comment]
Currently getting an error in my linter for the model that is 

"unexpected tIDENTIFIER , expecting ')'"

**Comment by CoreyFedde** [comment]
I previously tried calling the attributes as object."attribute". That format worked in the serializer, but not in the model. [attribute] does work in the model.

**Comment by jordanallain** [comment]
can you post the model code?

**Comment by scottyscripts** [comment]
remember that exponent operator in ruby is `**`

**Comment by CoreyFedde** [comment]
@jordanallain 
```ruby
class Loan < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'

#reader_attr
  def monthly_payment
    self[:monthly_payment]
  end
# virtual attribute
  def monthly_payment
    ([principal] x [interest_rate]) / (1 - (1 + [interest_rate])^(-1))
  end
end
```

**Comment by CoreyFedde** [comment]
Goofed on the ruby symbols...
Update the code, but still not working

```ruby
def monthly_payment
    # [principal]
    (([principal]*[interest_rate]) / (1 - (1 + [interest_rate])**(-1)))
  end
```
@sdavidson140

**Comment by scottyscripts** [comment]
do you have reader and writer attributes for principal and interest rate? if not you have to specify self[:principal] etc

**Comment by CoreyFedde** [comment]
Would the reader and writer attributes need to be in the model?

**Comment by CoreyFedde** [comment]
Solved!

In Ruby anything divided by zero is recognized as NaN, which is not a number. When my method was iterating through my examples, it was throwing an error when it came across any example that was divided by zero. 

To solve that problem, I added an if statement that checks if either of the attributes I was using was zero before starting the equation.

Final code:
```ruby
def monthly_payment
    if principal.zero? || interest_rate.zero?
      0
    else
    # interest_rate
    # (1 - (1 + interest_rate)**(-1))
    # (principal * interest_rate) / (0)
      (principal * interest_rate) / (1 - (1 + interest_rate)**(-1))
    end
  end
```
