### ISSUE TITLE
Controller Confusion

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/capstone-project#82]
I have worked on/finished my models, migrations, and serializers. I am now working on my controllers and am having confusion on how I should be setting them up. I have a Game, Like and User model. Users have many Games through likes and vice versa. I only want Users to be able to see the games and like them therefore in the controller I put:

```
class GamesController < ApplicationController
  def index
    render :json => Game.all
  end

  def show
    render :json => @game
  end
end
```

For likes, I want users to be able to like a game, and unlike a game but only if they're the same user that liked the game. This is the controller I'm struggling with, any advice on how I should approach this?

@MattB-GA-Boston @jrhorn424 @gaand @J-Weeks

**Comment by jdamiron** [comment]
My intuition tells I'm going to want an index action to get all likes, even though I only want them directly associated with a single game. The next action should be create which would create a like, and possibly destroy which acts as unliking, is this the correct way to think about it?

**Comment by jdamiron** [comment]
Here is my ERD:

![img_0938](https://cloud.githubusercontent.com/assets/16493127/14191499/22166338-f766-11e5-83ba-4edd0445f112.JPG)

**Comment by GA-MEB** [comment]
Can you explain what you mean by this?

>  "I only want Users to be able to see the games and like them"

It also sounds like you want a Like to not just connect a Game and a User, but to be a _unique_ connection that is either a "like" or a "dislike". Is that correct?

**Comment by jrhorn424** [comment]
> For likes, I want users to be able to like a game, and unlike a game but only if they're the same user that liked the game.

You'll need to scope the actions in the Likes controller by `current_user`. I think based on your description, when a user un-likes a game, that would delete a row in the likes table, so you'll need to put your scoped query into `likes#destroy`.

**Comment by jdamiron** [comment]
@MattB-GA-Boston 

Users should not be able to create new games, destroy, or update them, they will simply be displayed on the page. The only reason why I have likes as it's own table is because when a user likes a game that game will be added to their liked-games collection and when they unlike it is removed from that collection. Do I need another table to display this liked-games collection?

What @jrhorn424 mentioned answered my question regarding allowing the same user to like and unlike a game.

**Comment by GA-MEB** [comment]
@jdamiron
If users can only 'read' Games, then yes: don't create controller actions for 'create', 'update', or 'destroy'.
Though in the code example above, you tried to use `@game` without defining it.

You do not need a 'liked games' table, since 'liked games' is just the set of games associated with a User's Likes. 
Each User will have a `.games` method (representing games liked) if you set up `has_many ..., though ...` for Users, Likes, and Games.

**Comment by jrhorn424** [comment]
I sense some confusion. It's likely my own.

I read @jdamiron to mean "do I need a join table?" when he said:

> Do I need another table to display this liked-games collection?

Which is precisely the advice @MattB-GA-Boston gave when he said:

> Each User will have a .games method (representing games liked) if you set up has_many ..., though ... for Users, Likes, and Games.

I just wanted to re-iterate that a join table here is a good idea, and to add that, for this feature, a controller specifically for the join table (create and delete) is appropriate.

**Comment by jrhorn424** [comment]
@jdamiron If this cleared up your initial confusion (based on your OP and title), would you mind closing? Thanks.
