### ISSUE TITLE
Creating a resource in rails that belongs to another resource.

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/capstone-project#821]
I think I'm in a similar spot to Ryan's recent issue, but I still need some more help.

I am feeling very rusty on Rails and can't create a resource that belongs to an existing resource to save my life right now. I have my initial resource, Games, that I'm able to CRUD on without an issue, and I created a new resource, PAs, so that Users have many games which have many PAs.

Whenever I try to create a new PA that belongs to a Game, I get a 422 Unprocessable Entity error because I can't seem to pass the game_id into the request. I'm trying to model my API after the Listr example, but I feel like I'm getting to the point where I'm trying things and only making things worse for myself.

Here is my console error:
```
Started POST "/pas" for 127.0.0.1 at 2017-08-28 15:35:58 -0400
Processing by PasController#create as HTML
  Parameters: {"pa"=>{"inning"=>"1", "batter"=>"1", "pitcher"=>"1", "runs"=>"1", "outs"=>"1", "def_error"=>"1", "outcome"=>"1"}}
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "1fda24ff81592b1d639ea92d28bbed24"], ["LIMIT", 1]]
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.11ms)
Completed 422 Unprocessable Entity in 27ms (Views: 2.5ms | ActiveRecord: 3.1ms)

```

PA controller:
```Ruby
class PasController < ProtectedController
  before_action :set_pa, only: [:show, :update, :destroy]

  # GET /pas
  def index
    @pas = Pa.all

    render json: @pas
  end

  # GET /pas/1
  def show
    render json: @pa
  end

  # POST /pas
  def create
    @pa = Pa.new(pa_params)

    if @pa.save
      render json: @pa, status: :created, location: @pa
    else
      render json: @pa.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /pas/1
  def update
    if @pa.update(pa_params)
      render json: @pa
    else
      render json: @pa.errors, status: :unprocessable_entity
    end
  end

  # DELETE /pas/1
  def destroy
    @pa.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pa
      @pa = Pa.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pa_params
      params.require(:pa).permit(:inning, :batter, :pitcher, :runs, :outs, :def_error, :outcome, :game_id)
    end
end
```
Schema for two resource tables:
```Ruby
create_table "games", force: :cascade do |t|
    t.string   "date",       null: false
    t.string   "home",       null: false
    t.string   "away",       null: false
    t.integer  "user_id",    null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_games_on_user_id", using: :btree
  end

  create_table "pas", force: :cascade do |t|
    t.integer  "inning"
    t.integer  "batter"
    t.integer  "pitcher"
    t.integer  "runs"
    t.integer  "outs"
    t.integer  "def_error"
    t.string   "outcome"
    t.integer  "game_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["game_id"], name: "index_pas_on_game_id", using: :btree
  end
```
I'll leave it at that for now so the post doesn't just become my entire api, but if there's any other code you'd like to see let me know. Thanks!

**Comment by jordanallain** [comment]
is the relationship set up in your models?

**Comment by bradleyden** [comment]
Yes, models are set up like this:

```Ruby
class User < ApplicationRecord
  include Authentication
  has_many :games
  has_many :pas, through: :games
end

class Pa < ApplicationRecord
  belongs_to :game
end

class Game < ApplicationRecord
  belongs_to :user
  has_many :pas
  validates :date, :home, :away, presence: true
end
```
Each in its own file, just combined for easier readability.

**Comment by jordanallain** [comment]
`has_many :pas, through: :games`

this is the syntax that we would use for a join table. is `games` a join table that connects User to Pas? If it is you should have the inverse where Pas has_many Users through games

**Comment by bradleyden** [comment]
It isn't really a join table, since there isn't a many to many relationship. My relationship is One User has Many Games, and One Game has Many PAs. How would this data be structured if not with a has_many, through:?

**Comment by jordanallain** [comment]
If a game is owned by a user, and a pa is owned by a game, you shouldn't need to directly associate the user with the pa

User
has_many :games

Game
belongs_to :user
has_many :pas

Pa
belongs_to :game

does something like this look correct based on your ERD?

**Comment by bradleyden** [comment]
Yes, that looks correct, and that is actually how I had it set up initially. I'm still getting the same 422 error when it is set up like that, though.

**Comment by jordanallain** [comment]
what is the error? same as the one from your first post?

**Comment by bradleyden** [comment]
yeah, the browser console gives a 422 and says: 'The adapter rejected the commit because it was invalid'

The rails server console prints the same error from the original post.

**Comment by payne-chris-r** [comment]
Wut is a PA?

**Comment by payne-chris-r** [comment]
Parental Advisory?

**Comment by bradleyden** [comment]
Plate Appearance

I knew I would misspell appearance at some point so I went with the abbreviation

**Comment by payne-chris-r** [comment]
Abbrevs !gud

**Comment by payne-chris-r** [comment]
What's a plate appearance?

**Comment by MicFin** [comment]
Why are you not passing the `game_id` that the `pa` belongs to with the request?
```
"pa"=>{"inning"=>"1", "batter"=>"1", "pitcher"=>"1", "runs"=>"1", "outs"=>"1", "def_error"=>"1", "outcome"=>"1"}
```
If it's because you are relying on `current_user` then you should add the `game_id` before you try to save the `pa` in your controller.

**Comment by bradleyden** [comment]
@MicFin Just talked with Chris, my confusion was that I was modelling my front end after Listr, which had an adapter for the routes, but my front end was RESTful, so I didn't include the game_id. I think I'm clear on where I was going wrong with that moment of clarity, so I will close the issue while I revise my front end to pass the ID.

Thanks everyone!
