### ISSUE TITLE
looking for guidance regarding a many:through relationship

### ISSUE THREAD

**Issue by Azinck94** [ga-wdi-boston/capstone-project#822]
Hey guys, I am currently planning out my reach goal of creating a way for my users to schedule meetings with customers in my database. I wanted to make sure I nailed down exactly the best way to go about setting up my relationship structure before I got started tonight. I wanted to have each customer route have an option to input a date to setup a meeting for the user. A user will have many meetings, and a meeting with belong to a customer and a user. My current idea for the model's structure in rails is based off  the doctor-patient-appointment example:
```


class User < ApplicationRecord  
has_many :customers  
has_many :meetings, through: :customers
end 
class Meeting < ApplicationRecord  
belongs_to :user
 belongs_to :customer
end
 class Customer < ApplicationRecord  
belongs_to :user
end
--

**Comment by Azinck94** [comment]
Does this seem to be heading in generally the right direction or is there a more efficient way to accomplish this goal? Thanks!

**Comment by jordanallain** [comment]
if meeting is a join table of users and customers, you'll want that has_many through: in both the user and customer models.

**Comment by Azinck94** [comment]
ok great thanks... something like this? 
```

class User < ApplicationRecord  
has_many :customers  
has_many :meetings, through: :customers
end 
class Meeting < ApplicationRecord  
belongs_to :user
 belongs_to :customer
end
 class Customer < ApplicationRecord  
belongs_to :user
has_many :meetings, through: :users
end
--

**Comment by jordanallain** [comment]
looks good to me!

**Comment by Azinck94** [comment]
ok great thanks Jordan!
