### ISSUE TITLE
1:1 for capstone project

### ISSUE THREAD

**Issue by Fcarrion001** [ga-wdi-boston/capstone-project#823]
I am making a video game wishlist that uses Rails as the api, and browser template for now on the front-end.  I am also using a 3rd-party api for the games.
I would like to talk with someone about the scope of my project and to discuss what the order of operations should be when incorporating a 3rd party api

**Comment by jordanallain** [comment]
do you have ERD and user stories and wireframes?

**Comment by Fcarrion001** [comment]
https://www.dropbox.com/s/izak5rco57lcfqg/Screenshot%202017-08-28%2015.59.25.png?dl=0
https://www.dropbox.com/s/1isqfalv5qywl3s/Screenshot%202017-08-28%2015.59.45.png?dl=0
https://www.dropbox.com/s/i43l8iv8bq5itxd/Screenshot%202017-08-28%2016.00.02.png?dl=0

My user stories reflect my original plan which I know think is a bit too much to attempt right now 

Idea
    Fullstack app that allows the user create a wishlist of video games coming out.
    

User stories

As a user, I want to be able to make a wishlist of video games, so that I do not have to commit them to memory.

As a user, I want to be able to look at a list of video games, so that I know which games are coming out.

As a user, I want to be able to be reminded of which games are close to release, so that I do not miss pre-order bonuses.

As a user, I want to be able to keep track of games I have preordered, so that I can pick them up as soon as they come out.

As a user, I want to be able to see how much money I have put down on a game, so that I know what I am going to have to pay in the future, and when.



-Things I think/know I will need

* Front and back end
* Backend will be rails
* Front end will begin with browser template but the plan is to switch to ember
* I will need to connect to a third party api (plan is gamestop)
* I need to research if gamestop api is in fact open to outside developers
* I will need to have user and game tables, with wishlist and preordered_games as join tables.
* Third party api will preferably include game price, if not, I can make assumptions based on the system the game is coming out for and throw a disclaimer on the matter to the user.
* I will need logic to check for how close a game is coming out to alert the user within a given timeframe
    * Perhaps Boolean attributes for releasedSoon and outNow for both join tables (wishlist and preordered).
        * Embers toggle method would be useful to apply class, attribute and css when needed.
* 
* Games will not be able to be created, destroyed, or updated by the user
* Games can only be added to, or removed from the wishlist
* Stackoverflow suggests a tableless model for the third party api
* 3rd party api uses numbers to represent data with limited defined possibilities ex) genre, region, etc.
    * These will need to be translated back to the values they represent
    * Look into using the third party api or define the values in the front or back end.
* Will need search functionality for games
    * Controller will need custom param queries
    * The search results will need an option to add to the wishlist

**Comment by jordanallain** [comment]
okay wanna meet in the kitchen to discuss?

**Comment by Fcarrion001** [comment]
Yes please
