### ISSUE TITLE
update routine

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#824]
I'm trying to run a curl script to update a routine but I keep getting this error:
```
"app/controllers/routines_controller.rb:52:in `set_routine'"
```

curl script: 
```sh
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/routines"
curl "${API}${URL_PATH}/${ID}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
  --data '{
    "routine": {
      "name": "lowerbody",
      "routine_id": "1"
    }
  }'

echo
```

```rb 
class RoutinesController < OpenReadController
  before_action :set_routine, only: [ :show, :update, :destroy]

  # PATCH/PUT /routines/1
  def update
    binding.pry
    if @routine.update(routine_params)

      render json: @routine
    else
      render json: @routine.errors, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_routine
      @routine = current_user.routine.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def routine_params
      params.require(:routine).permit(:name, :exercise_id, :routine_id)
    end
end
```
I tried removing ```     "routine_id": "1" ``` from data within my curl script 
I added ``` :routine_id``` to routine_params
I tried removing ```:update``` from set_before 
I put a binding.pry in the update method (which doesn't work) 
The path of the curl script looks fine but I can't get to routines/1 without getting that error in my browser.
I've read through this issue: 
https://stackoverflow.com/questions/21213230/routing-error-no-route-matches-patch-locations

I'm totally stuck and have exhausted any ideas on how to solve this.

**Comment by jordanallain** [comment]
did you just try `id` ?

you are inside of the routine object so you shouldn't need to specify that it is a `routine_id`

**Comment by jordanallain** [comment]
actually, if you are specifying the ID in the URL you shouldn't need to pass it in in the data object.

**Comment by jordanallain** [comment]
remind me again of your ERD? is routines a join table? if it is you need to permit user_id

**Comment by ryanwk** [comment]
Yeah, that doesn't seem to have an effect. 
Even when trying to access it manually from the browser ```http://localhost:4741/routines/1```
I still get the error in question 
```js
"status": 500,
"error": "Internal Server Error",
"exception": "#<NoMethodError: undefined method `routine' for nil:NilClass>",
"traces": {
"Application Trace": [
{
"id": 0,
"trace": "app/controllers/routines_controller.rb:52:in `set_routine'"
```

**Comment by ryanwk** [comment]
Yeah, routines is a join table. 

User has many routines
User has many exercises through routines
Routines belongs to users
Routines belongs to exercises
Exercise has many routines and 
Exercise has many users through routines

**Comment by ryanwk** [comment]
This doesn't seem to alleviate the situation. 
```rb
    def routine_params
      params.require(:routine).permit(:name, :exercise_id, :routine_id, :user_id)
    end
```
Otherwise I'm not sure what you mean by permit user_id, in the data object of the curl request?

**Comment by jordanallain** [comment]
do all of your controllers inherit from open read or protected controller?

**Comment by ryanwk** [comment]
exercises and users are protected where routines inherits from open read. Should that be changed? Eventually, I'd like to set routines to inherit from the protected controller. The only reason it's inheriting from open read is because I'm using localhost:4741 for visibility while working with the backend

**Comment by ryanwk** [comment]
I set the routines controller to inherit from protected controller to match my other entities. I can't see the error in my local host because access is denied but the error I'm getting from my server is as follows:
```ActionController::RoutingError (No route matches [PATCH] "/routines"):```
I tried it again after reverting back to openRead and I got the same error again:
```ActionController::RoutingError (No route matches [PATCH] "/routines"):```

Then I tried setting all of the controllers to openRead and got the same error again. I tried a variety of routes /routine, /routines, etc. Still no luck. I tried changing the curl script in a variety of ways, removed just the authorization line, removed just the header line, removed just the id parameter and hardcoded an id in, removed just the id property of the data object, etc. 

So it appears I have a new error, normally I would open a new issue regarding this error, however, I don't know what I did to get this new error. I'm pretty lost here. I'm thinking maybe adding user_id to routine_params might have done something? Regardless, I'm still unable to hit the binding.pry that is sitting on the update method of my routine controller.

**Comment by ryanwk** [comment]
I tried going into routes and testing different variations:
```rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :routines
  resources :exercises, except: %i[show new edit]
  resources :examples, except: %i[new edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: %i[index show]
end

```

tried 
resources :routines
resources :routines, except: %i[show]
resources :routine

**Comment by scottyscripts** [comment]
If the original issue was "exception": "#<NoMethodError: undefined method `routine' for nil:NilClass>", then it is definitely hitting your route. Can you use binding.pry to verify that you are entering your update function and stepping through it there? What is the most recent error message??

**Comment by ryanwk** [comment]
I have binding.pry on the update method and it doesn't pause the server to let me mess around with things in pry, it's not getting to binding.pry.

**Comment by ryanwk** [comment]
this is the error I've been getting consistently: 
server:
```
Started PATCH "/routines/" for 127.0.0.1 at 2017-08-29 09:55:44 -0400
  
ActionController::RoutingError (No route matches [PATCH] "/routines"):
  
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
puma (3.7.0) lib/puma/configuration.rb:226:in `call'
puma (3.7.0) lib/puma/server.rb:578:in `handle_request'
puma (3.7.0) lib/puma/server.rb:415:in `process_client'
puma (3.7.0) lib/puma/server.rb:275:in `block in run'
puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```
curl request from terminal
```
~/wdi/projects/strongerBackEnd (routine)
$ TOKEN=BAhJIiVlZDBkYmZhYmVhOTFkMWJjOTEwMzEwOWE2Mjg4MTM2ZgY6BkVG--f81f1ca5ebf76f15c1ccf2164e3ce56c3fd2d307 sh scripts/update-routine.sh 
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8
X-Request-Id: f00245ef-bd56-474d-87d8-c8f9d78a73bc
X-Runtime: 0.025921
Vary: Origin
Content-Length: 3771

{"status":404,"error":"Not Found","exception":"#\u003cActionController::RoutingError: No route matches [PATCH] \"/routines\"\u003e","traces":{"Application Trace":[],"Framework Trace":[{"id":0,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'"},{"id":1,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":2,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":3,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":4,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'"}
```

**Comment by payne-chris-r** [comment]
Do you have a route for a PATCH to /routines? show me your router?

**Comment by ryanwk** [comment]
tried placing the ID in the terminal with the curl request:
```
~/wdi/projects/strongerBackEnd (routine)
$ TOKEN=BAhJIiU5YmU1YjA4OThiMzBhNjQ2MDc1Y2U3MjBkYmFlMTUzMQY6BkVG--c7aed48fac5fe45c44960dfa31e1dcae74cd4d81 ID=1 sh scripts/update-routine.sh 
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
X-Request-Id: 13ce50a0-3ae2-4730-9348-f9de73c755d6
X-Runtime: 0.048454
Vary: Origin
Content-Length: 11871

{"status":500,"error":"Internal Server Error","exception":"#\u003cNoMethodError: undefined method `routine' for #\u003cUser:0x007f7f7cfb79f0\u003e\nDid you mean?  routines\n               routines=\u003e","traces":{"Application Trace":[{"id":1,"trace":"app/controllers/routines_controller.rb:51:in `set_routine'"}],"Framework Trace":[{"id":0,"trace":"activemodel (5.0.1) lib/active_model/attribute_methods.rb:433:in `method_missing'"},{"id":2,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'"},{"id":3,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:150:in `block (2 levels) 

server:
Started PATCH "/routines/1" for 127.0.0.1 at 2017-08-29 10:28:39 -0400
Processing by RoutinesController#update as */*
  Parameters: {"routine"=>{"name"=>"lowerbody"}, "id"=>"1"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "9be5b0898b30a646075ce720dbae1531"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 7ms (ActiveRecord: 0.2ms)


  
NoMethodError (undefined method `routine' for #<User:0x007f7f7c907920>
Did you mean?  routines
               routines=):
  
app/controllers/routines_controller.rb:51:in `set_routine'
```

Then tried removing the pluralization of routines from within the curl script and got this:
```
TOKEN=BAhJIiU5YmU1YjA4OThiMzBhNjQ2MDc1Y2U3MjBkYmFlMTUzMQY6BkVG--c7aed48fac5fe45c44960dfa31e1dcae74cd4d81 ID=1 sh scripts/update-routine.sh 
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8
X-Request-Id: b2ee3ba1-499c-4585-964d-4bbfa787de6e
X-Runtime: 0.008863
Vary: Origin
Content-Length: 3772

{"status":404,"error":"Not Found","exception":"#\u003cActionController::RoutingError: No route matches [PATCH] \"/routine/1\"\u003e","traces":{"Application Trace":[],"Framework Trace":[{"id":0,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'"},{"id":1,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":2,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":3,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":4,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in 

server:
ActionController::RoutingError (No route matches [PATCH] "/routine/1"):
```

**Comment by ryanwk** [comment]
routes, tried testing different variations too:
```ruby
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :routines
  resources :exercises, except: %i[show new edit]
  resources :examples, except: %i[new edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: %i[index show]
end
```
tried
resources :routines
resources :routines, except: %i[show]
resources :routine

**Comment by ryanwk** [comment]
should I try writing it out like this one?
```
  patch '/change-password/:id' => 'users#changepw'

```

would it be something like this then? 
```
  patch '/routines/:id' => 'users# ? '

```

**Comment by payne-chris-r** [comment]
You want `resources :routines`

**Comment by ryanwk** [comment]
ok, that's what I have currently been working with while getting these errors.

**Comment by payne-chris-r** [comment]
When we make PATCH requests, what is typically the route we hit? Let's say I want to update book with id 45, what does my request look like?

**Comment by ryanwk** [comment]
PATCH /books/:id 
/books/45

TOKEN=xyz ID=45 sh scripts/update-book.sh


API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/books"
curl "${API}${URL_PATH}/${ID}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
  --data '{
    "book": {
      "update": "update"
    }
  }'

**Comment by payne-chris-r** [comment]
Yeah, so we need to make sure we're making the request to `/routines/34` (or whatever the ID is).
Onto the next error:
500: undefinied method .routine for User. You've gotten something similar to this before. What was it last time?

**Comment by ryanwk** [comment]
I might have solved that issue previously by adding user_id to the routine_params
```
    def routine_params
      params.require(:routine).permit(:name, :exercise_id, :routine_id, :user_id)
    end
```
Which is it's current state. Is that correct?

**Comment by ryanwk** [comment]
I added those permissions to the user here, without success: 
```rb
  def user_creds
    params.require(:credentials)
          .permit(:email, :password, :password_confirmation, :exercise_id, :routine_id, :user_id)
  end
```

**Comment by payne-chris-r** [comment]
You shouldn't need `routine_id` or `user_id` in your routine_params.
The routine id should come from the URL you're making the request to (`/routines/:id`), and the User id should come from the TOKEN being sent.

**Comment by ryanwk** [comment]
OK, so I removed routine_id & user_id from routine_params, same error.

**Comment by payne-chris-r** [comment]
Word. I'm gonna come look.

**Comment by ryanwk** [comment]
This was the oh so glaring culprit:
    def set_routine
      @routine = current_user._**routines.**_find(params[:id])
    end

just like the error message said..
