### ISSUE TITLE
Ember link-to only works once until page is reset

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/capstone-project#828]
I'm having a weird issue with a link in my app. I have an edit-plate-appearance route with a basic 'go back' link at the bottom of the form, and I'm able to pass in the game id to generate the proper link back to my game/:game_id route.

However, once I click this link, that link stops working for all of my plate appearance forms until I do a hard restart on the page. I inspected the element in the DOM, and when it loads the first time, the href value on the link is '/games/25' which does what I want it to. But once I click the link and come back, the href is stuck at # until I reset the page.

Another thing I'm noticing is that my fields in the edit plate appearance form  populate automatically initially, but then nothing is passed in when I click 'go back' and then click into another plate appearance to edit it. So basically, whenever the 'go back' button works, the fields are populated. Then once it stops working, the fields are no longer populated when I hit the edit route, which tells me it must have something to do with the data not being passed into the route the second time.

The form itself:
```Javascript
<h3>Edit Plate Appearance</h3>
<form {{action 'editPlateappearance' on='submit'}} >
  Inning:
  {{input type='number' placeholder='Inning' value=plateappearance.inning}}
  Batter:
  {{input type='number' placeholder='Batter' value=plateappearance.batter}}
  Pitcher:
  {{input type='number' placeholder='Pitcher' value=plateappearance.pitcher}}
  Outcome:
  {{input placeholder='outcome' value=plateappearance.outcome}}
  Runs:
  {{input type='number' placeholder='Runs' value=plateappearance.runs}}
  Errors:
  {{input type='number' placeholder='Errors' value=plateappearance.def_error}}
  Outs:
  {{input type='number' placeholder='Outs' value=plateappearance.outs}}
  <button type='submit'>Save</button>
</form>
```
Where the form is linked (with go back button):
```Javascript
{{edit-plateappearance-form plateappearance=model editPlateappearance='editPlateappearance'}}

{{#link-to 'game' model.game}} Go Back {{/link-to}}

```

Any idea why the data might be passing in correctly initially and then stop after the first time? I'm having trouble finding exact problem on Google, and it's tough to debug because I'm not getting any errors.

Thanks!

**Comment by payne-chris-r** [comment]
Yeah. I'm gonna need some time with this one. You in 5?

**Comment by payne-chris-r** [comment]
It has to do with not passing the right data when transition. That it's there on route load but not on transition.

**Comment by bradleyden** [comment]
I'm in 4 and could meet you here or somewhere else to take a look whenever you have a minute.

**Comment by bradleyden** [comment]
Actually, that makes a lot of sense and I think I'm on to something- I think I have it now where I'm passing in game data when the page is transitioned to, and plate appearance data when the route loads, so the fields only populate when the PA data goes in, and the go back button only works when the game data goes in.

I think I may be getting close to a solution on my own, but would still appreciate some help if you want to take a look!

**Comment by bradleyden** [comment]
Solution: my model hook was not defined in my edit-plate-appearances route. Without it, model was defined as game rather than plate appearance on transition, which broke my data.
