### ISSUE TITLE
ERD Help: User roles, etc

### ISSUE THREAD

**Issue by jpfriedman18** [ga-wdi-boston/capstone-project#83]
Concept for my app: allows teachers to create and grade writing prompts for their students.

User stories: Teachers can create a new writing prompt for students. Students can choose a prompt (or be assigned one by teacher, not sure yet) and write/submit a response to the prompt. Teachers can then see responses to their prompts and evaluate them (give 1-10 scores for grammar, vocabulary, spelling, etc). Students can then see their scores for a response after it has been evaluated. I'd also like students to be able to see their average scores for each category across all their responses.

Nouns: teachers, students, prompts, prompt responses, evaluations/scores

Where I need ERD help:
- User Roles: would it be better to have separate Teacher and Student models inheriting from the User model? Or should I simply add isTeacher and isStudent attributes to the User model?
- Should evaluations/scores for a response be stored on the prompt response model? I feel like it may be better to have a separate model for evaluations that can be created by teachers and read by students.
- How to deal with students' average scores? Should they be stored as attributes on the Student model? Or should they just be computed by a method on the Students controller and then sent to the front end?

**Comment by GA-MEB** [comment]
Average scores should be a computed property. I would suggest doing it either (a) in a serializer on the back-end, or (b) as a computed property in Ember.

**Comment by jrhorn424** [comment]
These methods might be helpful: [ActiveRecord::Calculations](http://api.rubyonrails.org/classes/ActiveRecord/Calculations.html)

@jpfriedman18 and I talked about this for a bit on Friday. I believe @MattB-GA-Boston and possibly @faetea provided help as well. If anyone else has notes, please add. @jpfriedman18 we should get your modeling done ASAP so you can work on features. If things change in the future, it's easiest to change columns, then harder to change relationships and entity names.

> User Roles: would it be better to have separate Teacher and Student models inheriting from the User model? Or should I simply add isTeacher and isStudent attributes to the User model?

Separate tables are a good idea. With active record, your intuition on inheritance needs to be checked. You probably **do not** want to use inheritance for your models. They should be related using relationships.

> Should evaluations/scores for a response be stored on the prompt response model? I feel like it may be better to have a separate model for evaluations that can be created by teachers and read by students.

Yes, feedback should be separate.

> How to deal with students' average scores? Should they be stored as attributes on the Student model? Or should they just be computed by a method on the Students controller and then sent to the front end?

Computed. It doesn't really matter where for your immediate purpose, but there are some advantages to doing this on the backend.

If this addresses your initial concerns, please close the issue @jpfriedman18.

I'm willing to give you further help on modeling once you've built a few features to get a feel for how your user stories and ERD affect each other.

**Comment by jrhorn424** [comment]
I want to elaborate more on this:

> With active record, your intuition on inheritance needs to be checked. 

Inheriting from a Model which itself inherits from ActiveRecord is the first step toward single-table-inheritance polymorphic relationships. Left unchecked, STI and PR destroy millions of families and homes each year. Please report STI and PR use to your local authorities.

Kidding, of course. STI and PR are things most database designers abhor. It's not even very straightforward for beginning application developers, in my opinion. However, after you get the basics working, if you want a challenge, you can try making inheritance work for roles. Advanced Active Record is the chapter in the Rails 4 Way that introduced me to these concepts. Here's a preview of it: http://www.informit.com/articles/article.aspx?p=2220311&seqNum=4
