### ISSUE TITLE
Dropdown/Radio Buttons with Ember data binding?

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/capstone-project#835]
I've got my CRUD working using the method of data binding we did in class, but I'm hoping to modify a couple fields to use a dropdown or radio buttons.

I'm wondering how that works with data binding, since I can't use the value attribute to both define the option values and bind them to the object. It seems like a very simple thing to do, but I have tried a few things and can't find a simple answer on Google.

Here is what I have currently, to hopefully give an idea of what I need to accomplish:
```JavaScript
<form {{action 'createPlateappearance' on='submit'}} >
  <select>
    <option value=newPlateappearance.inning_half>TOP</option>
    <option value=newPlateappearance.inning_half>BOT</option>
  </select>
  {{input type='number' placeholder='Inning' value=newPlateappearance.inning}}
  {{input type='number' placeholder='Batter' value=newPlateappearance.batter}}
  {{input type='number' placeholder='Pitcher' value=newPlateappearance.pitcher}}
  {{input placeholder='Outcome' value=newPlateappearance.outcome}}
  {{input type='number' placeholder='Runs' value=newPlateappearance.runs}}
  {{input type='number' placeholder='Errors' value=newPlateappearance.def_error}}
  {{input type='number' placeholder='Outs' value=newPlateappearance.outs}}
  <button type='submit'>New</button>
</form>
```
Thanks!

**Comment by scottyscripts** [comment]
have you tried putting the value attribute on the select tag instead of on the option?

**Comment by scottyscripts** [comment]
This is the example i showed you from my personal app
in the template for my create form (`create-hike-form.hbs`) I had 
```
<div class="form-group">
  <label for="mountain-select">Mountain</label>
  <select onchange={{action 'updateMountain' value="target.value"}} id="mountain-select">
    <option disabled selected>Select a mountain</option>
    {{#each mountains as |mountain|}}
    <option value={{mountain.id}}>{{mountain.name}}</option>
    {{/each}}
  </select>
</div>
```
then in the corresponding component js file (`create-hike-form.js`) I had an action that looks like 
```
    actions: {
      updateMountain(mountain) {
        console.log(mountain)
        this.set('hikeData.mountain', mountain)
      },
```
where mountain is the updated value of the <option> selected

**Comment by bradleyden** [comment]
It worked! This was exactly the solution I was looking for, thanks Scott!
