### ISSUE TITLE
Ember + theme

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#839]
Does the Ember template allow themes? or does it kill it when deploying like browser-template?

**Comment by jordanallain** [comment]
What do you mean by themes? Do you mean using a bootstrap template or something?

**Comment by ryanwk** [comment]
yeah a bootstrap template

**Comment by scottyscripts** [comment]
I need more specifics to answer this question. What exactly are you trying to do? What have you tried so far?

**Comment by ryanwk** [comment]
Haven't tried anything yet was just curious. Browser template, when deployed, shuts down any type of full on bootstrap theme that I've tried to employ in the past. With browser template, script tags in the header don't require properly and it can be tricky importing css/scss files to index.scss due to some mechanism of webpack within the browser template? I was wondering if the same would happen with the Ember template. 

The root of this thought stems from the realization that I won't have time to style my app before Friday morning. So, if I could use a quick bootstrap theme with all the bells and whistles and only some minor modifications, it would help. If not, that's totally fine. I can style it by hand at a later date.

**Comment by scottyscripts** [comment]
You can not add script tags in the header in HTML the way things are configured to build. I would not worry about styling at this point. Having CRUD functional is way more important to get at this point. Styling your app is the last step in the process.

**Comment by ryanwk** [comment]
ok got it thanks!
