### ISSUE TITLE
1 : 1 Request 

### ISSUE THREAD

**Issue by Fcarrion001** [ga-wdi-boston/capstone-project#841]
I am having trouble accessing the data being referenced by my join table. When I google it all I see is SQL but I can't figure out what I need to do in rails that will be the equivalent. Also, my I ideas for my project has changed a bit so I would like to touch base with a consultant again to make sure I am on the right track.

**Comment by Fcarrion001** [comment]
Update
I think I found a solution I am benefitting from a fresh start today, I think my brain was fried yesterday

```ruby 
def index
    Game.connection
    @game = Game
    @wanted_games = @game.joins(:wanted_games).where(wanted_games: { user_id: current_user })
    render json: @wanted_games
  end
```
I still need to test with other users but it looks like this might work
I would still like a 1:1 though
Thanks

**Comment by jordanallain** [comment]
i'm in the kitchen when you're ready

**Comment by Fcarrion001** [comment]
Thanks Jordan
