### ISSUE TITLE
handlebars results not displaying in browser

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/capstone-project#842]
I can't seem to get a particular handlebars table to output to the browser.  There are _many_ issues in the queue about this and I feel like I have implemented the results others have found useful.  I am pretty sure it is the way I am passing the data that is the problem.

```hbs
{{#each vegetables as |vegetable|}}

<div class="your-list">
      <li><h3>{{vegetable.name}}</h3></li>
      <li><img class="thumbnail" src={{vegetable.image}}></li>
      <br/>
      <li><textarea rows="4" cols="20">{{vegetable.comment}}</textarea></li>
      <br/>
      <li><button data-id="{{vegetable.id}}" class="update-comments-button dropbtn"> Edit Comments </button></li>
      <li><button data-id="{{vegetable.id}}" class="delete-veggie-button dropbtn"> Delete </button></li>
</div>

{{/each}}
```
```js
const getGardenSuccess = function (data) {
  console.log('getGardenSuccess', data)
  console.log('store.garden is ', data.vegetable)
  const displayGardenHTML = displayGardenTemplate({ vegetables: data.vegetable })
  $('.your-list').empty()
  $('.your-list').append(displayGardenHTML)
  $('.your-list').show()
}
```
console output:

![image](https://user-images.githubusercontent.com/28842407/29872707-ae6191e8-8d5e-11e7-8368-fabd707d8524.png)

**Comment by 3point14guy** [comment]
Update:

I changed 
```js
const displayGardenHTML = displayGardenTemplate({ vegetables: data.vegetable })
```
to 

```js
const displayGardenHTML = displayGardenTemplate({ vegetables: data })
```
as data.vegetable was undefined.  Now, only the first item displays.  To me, this confirms that there is something wrong with the way I am passing the data.

**Comment by scottyscripts** [comment]
are you trying to render data about `vegetables` or `gardens`. Your logged data object looks like it is a list of `gardens` `data.gardens` but the helper looks like you are working with vegetables?

**Comment by scottyscripts** [comment]
`data.vegetables` is undefined, what about `data.gardens`

**Comment by 3point14guy** [comment]
So my thought process is that I could use the data from the vegetables table since it is the same information that is going into a garden.

data.garden is also undefined

**Comment by scottyscripts** [comment]
ahhh i see. So `data.garden` is undefined. Look at the object you logged. What is the name of the property it has. Not `data.garden` but it is very close.

**Comment by 3point14guy** [comment]
The darn plural/singular thing bit me again!!  

data.gardens (plural) fixes things:

```js
const getGardenSuccess = function (data) {
  console.log('getGardenSuccess data is ', data.gardens)
  const displayGardenHTML = displayGardenTemplate({ gardens: data.gardens })
  $('.your-list').empty()
  $('.your-list').append(displayGardenHTML)
  $('.your-list').show()
}
```

**Comment by 3point14guy** [comment]
```
test
```
