### ISSUE TITLE
Initial deployment fail

### ISSUE THREAD

**Issue by mak1323** [ga-wdi-boston/capstone-project#847]
Followed steps exactly, initial deploy failed for ember.

**Comment by scottyscripts** [comment]
Is anything showing up on the screen? Do you have console errors or is it a 404 page??

**Comment by mak1323** [comment]
Got to the stage of ember build --production and failed.

**Comment by mak1323** [comment]
Followed steps and added some extra steps
Deploy is good.
Had to delete npm nodes, bower components, and my entire dist folder before being abe to deploy.
