### ISSUE TITLE
paused on breakpoint

### ISSUE THREAD

**Issue by jillrizley** [ga-wdi-boston/capstone-project#848]
I'm not totally used if i clicked on something or changed something in my code to make this pop up, but there were no buggy errors before this, and now when I load my localhost, it is immediately paused with this `paused on breakpoint` I have looked online but it just says to un click breakpoints, but it looks like I have non clicked to un click!

this is the error it is highlighting, if thats helpful

```
var rerrorNames = /^(Eval|Internal|Range|Reference|Syntax|Type|URI)Error$/;
```

**Comment by scottyscripts** [comment]
Can you check in atom to see if you have linter errors anywhere. Usually when it goes straight into a debugger there is a syntax error causing things to act wonky

**Comment by jillrizley** [comment]
I couldn't find anything in my front or back. The only thing I see if CSS related, but its just being picky, not actually anything wrong.

**Comment by jillrizley** [comment]
Jeff just came to the rescue. Clicked on something in the jquery dev tools that made a debugger in the browser at that point in the code. All fixed!
