### ISSUE TITLE
(Backend) Express Won't start.

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/capstone-project#85]
### What am I trying to do?

I want to fire up express from `/express` not `/`
### What I did....

[CODE: my package.json](https://gist.github.com/edesilets/4549615cc99308d157fbbadcf1637490)

**Comment by GA-MEB** [comment]
Error message?

**Comment by edesilets** [comment]
``` bash
>npm start

> thermal-comfort-system-api@1.0.0 start /Users/erdesi90562/projects/thermal-comfort-system-API
> ./express/bin/express server

module.js:340
    throw err;
    ^

Error: Cannot find module '/Users/erdesi90562/projects/thermal-comfort-system-API/server.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
/Users/erdesi90562/projects/thermal-comfort-system-API
```

I am unsure why its not looking within the express dir.

**Comment by gaand** [comment]
Are you using the `express-template` repo?

Moving files around almost certainly caused this problem.

**Comment by jrhorn424** [comment]
Was this resolved @edesilets?

`thermal-comfort-system-API/server.js` is missing. Assuming you're in the project directory when you typed `npm start`, this file should be a sibling of `package.json`.

**Comment by edesilets** [comment]
The Solution I found was:

Modify `./express/bin/express` to

``` bash
#!/bin/sh

case ${1} in
  s|server)
    NODE_PATH=${PWD} node ${PWD}/express/server.js
    ;;
  *)
  echo "${1} unknown command"
sac
```

Node might need to be updated.
