### ISSUE TITLE
front end feature addition

### ISSUE THREAD

**Issue by Azinck94** [ga-wdi-boston/capstone-project#851]
Hi guys, so I'm pretty clear on how to accomplish the back end side of things, but I'm looking for a good way to have a schedule meetings option for my front end interface. I want users to be able to click on a customer and within that customer's template have an option for adding a meeting with that specific customer which will be displayed in a meetings route. I have mapped out a lot of this on the whiteboard but am wondering if someone could have a quick chat with me about it before the end of the day.

**Comment by payne-chris-r** [comment]
Yes. I'm chatting with Corey first, then you.

**Comment by payne-chris-r** [comment]
Add your solution when you decide!

**Comment by Azinck94** [comment]
will do!

**Comment by Azinck94** [comment]
So... here is what I have gone with for what I am planning:

Use `ember generate component customer-list/meeting-form` to create
a component for my form.

 meeting-form will bind the value of its input field to a newMeeting object
- meeting-form when submitted will send the action and newMeeting up and also
sets the newMeeting content back to null
- customer-list component sends the action and meeting up to the route
- the customer.js route creates a new record and saves it

**Comment by Azinck94** [comment]
I will update as I complete each of those steps will what the route files and template files look like

**Comment by Azinck94** [comment]
here is the customer-list.js:
```
import Ember from 'ember';

export default Ember.Component.extend({
  classNames: ['customer'],
  classNameBindings: ['customerDetailHidden'],
  customerDetailHidden: false,
  newMeeting: {
    content: null,
    done: false
  },
  actions: {
    toggleMeetingDone (meeting) {
        return this.sendAction('toggleMeetingDone', meeting);
    },
    toggleCustomerDetail () {
      return this.toggleProperty('customerDetailHidden');
    },
    deleteMeeting (meeting) {
       return this.sendAction('deleteMeeting', meeting);
     },
     createMeeting () {
       let meeting = this.get('newMeeting');
       meeting.customer = this.get('customer');
       this.sendAction('createMeeting', meeting);
       this.set('newMeeting.content', null);
      }
  },
});

**Comment by Azinck94** [comment]
customer.js route:
```
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('customer', params.customer_id);
  },
  actions: {
   toggleMeetingDone (meeting) {
      meeting.toggleProperty('done');
      meeting.save();
    },
    deleteMeeting (meeting) {
      meeting.destroyRecord();
    },
    createMeeting (meeting) {
      let meetingRecord = this.get('store').createRecord('meeting', meeting);
      meetingRecord.save();
     }
  },
});

**Comment by Azinck94** [comment]
I extended the ApplicationAdapter as well:
meeting.js:
```
import ApplicationAdapter from './application';

 export default ApplicationAdapter.extend({
   createRecord(store, type, record){
     const api = this.get('host');
     const serialized = this.serialize(record, {includeID: true});
     const customerId = serialized.customer_id;
     const url = `${api}/customers/${customerId}/meetings`;
     const data = {meeting: serialized};
     return this.ajax(url, 'POST', {data});
   }
 });

**Comment by Azinck94** [comment]
getting a " Uncaught TypeError: Cannot read property 'create' of undefined" when trying to add a meeting now, going to dig around a little bit and try to diagnose... will post updates

**Comment by jordanallain** [comment]
are you calling .create on something that you thought was defined?

**Comment by Azinck94** [comment]
trudging along my friend, created the model for meeting.js:
```
import DS from 'ember-data';

export default DS.Model.extend({
  content: DS.attr('date'),
  done: DS.attr('boolean'),
  customer: DS.belongsTo('customer')
});

**Comment by Azinck94** [comment]
Now I am getting the following on a create attempt:
```
"POST http://localhost:4741/customers/32/meetings 404 (Not Found)
11:02:18.575 ember.debug.js:16905 Ember Data Request POST http://localhost:4741/customers/32/meetings returned a 404
Payload (Empty Content-Type)
[object Object]
Error"

**Comment by Azinck94** [comment]
looks like the route does not exist,(clearly) but after talking to chris I decided I didnt want to post to a seperate route but instead to merely post to the specific customer route, will look through my code to see where I am defining the post route.

**Comment by Azinck94** [comment]
is this perhaps in part being caused by the applicationadaptor line:
```
  const url = `${api}/customers/${customerId}/meetings`;

**Comment by Azinck94** [comment]
^nope, tried changing that to end with "${customerId}" but same error

**Comment by scottyscripts** [comment]
What adapter file is `const url = `${api}/customers/${customerId}/meetings`;` in? Where was it trying to make the POST requrest when you changed that url?

**Comment by Azinck94** [comment]
meeting.js adaptor

**Comment by Azinck94** [comment]
I have been trying to follow the guidelines outlined in ember resources for creating "items" because it is remarkably similar with what I am trying to accomplish here.

**Comment by Azinck94** [comment]
POST http://localhost:4741/customers/32/meetings 404 (Not Found) is where its trying to make a post to , which seems like a problem

**Comment by Azinck94** [comment]
I want to make a post to here correct: http://localhost:4741/customers/32 ??? Because I want to be able to display the created meeting on the specific handlebars card for that customer

**Comment by payne-chris-r** [comment]
You probably don't want to be messing with the adapter. Do you have nested routes on your API?

**Comment by Azinck94** [comment]
No just a has many belongs to relationship between customers and meetings. a customer has many meetings but a meeting belongs to a customer.

**Comment by Azinck94** [comment]
now Im getting the following error when trying to migrate in order to add foreign key for  customer to meeting:
```
 add_foreign_key(:customer, {:foreign_key=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "customer" does not exist
: ALTER TABLE "customer" ADD CONSTRAINT "fk_rails_178f1d43f2"
FOREIGN KEY ("{:foreign_key=>true}_id")
  REFERENCES "{:foreign_key=>true}" ("id")

**Comment by Azinck94** [comment]
Ive tried two migrations, here is the first:
```
class MigrationName < ActiveRecord::Migration[5.0]
  def change
    change_table :meetings do |t|
      add_foreign_key :customer, foreign_key: true
    end
  end
end

**Comment by Azinck94** [comment]
here is the second:
```
class AddCustomertoMeetings < ActiveRecord::Migration[5.0]
  def change
    add_reference :meetings, :customer, index: true
  end
end

**Comment by scottyscripts** [comment]
do you have both of these in your migrations folder. If so, destroy the first one

**Comment by Azinck94** [comment]
didnt need adaptor, added relationship to the back end, fixed serializers and renamed :date to :scheduled_at because :date is a reserved name

**Comment by Azinck94** [comment]
Last thing to accomplish is finding a way to show the newly created meeting: 
I input scheduledAt and receive a successful post response, but am getting hung up on this last step:
