### ISSUE TITLE
trouble with patch showing up on click

### ISSUE THREAD

**Issue by jillrizley** [ga-wdi-boston/capstone-project#858]
Having issues with my PATCH. I want to update the album so it updates immediately. I can sign out and in and it updates and I am getting a PATCH. however, after trying what feels like everything, I can’t seem to get it to update after submit. I think I’m probably just missing something silly. I know it says album of undefined, but I'm not sure what I am supposed to add to the UI

I get this error in the web dev console

```
jquery.js:3860 jQuery.Deferred exception: Cannot read property 'album' of undefined TypeError: Cannot read property 'album' of undefined  at HTMLFormElement.onUpdateSuccess 
```

API
```js
const update = function (data, id) {
  return $.ajax({
    method: 'PATCH',
    url: config.apiOrigin + '/albums/' + id,
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```

events
```js
const updateAlbum = function (e) {
  e.preventDefault()
  const data = getFormFields(e.target)
  api.update(data, data.album.id)
    .then(ui.onUpdateSuccess.bind(this))
}
```

UI (albumTemplate is my handlebars)
```js
const onUpdateSuccess = function (data) {
  $('#editAlbumModal').modal('hide')
  $('#content').append(albumTemplate(data.album))
}
```

**Comment by payne-chris-r** [comment]
Why are you binding `this`?

**Comment by payne-chris-r** [comment]
What is `data` in onUpdateSuccess?

**Comment by jillrizley** [comment]
Good point, the binding isn't needed. The `data` is the updated information I entered. I think I'm having trouble with where the information is going as well. Not sure if content is the right place for it.

**Comment by scottyscripts** [comment]
Can you post what `data` actually looks like when you log it in your `onUpdateSuccess` function?

**Comment by jillrizley** [comment]
ohhhh crap. undefined. not sure where I'm making the error

```
jquery.js:3860 jQuery.Deferred exception: Cannot read property 'album' of undefined TypeError: Cannot read property 'album' of undefined
    at Object.onUpdateSuccess (http://localhost:7165/public/application.js:1008:42)
    at mightThrow (http://localhost:7165/public/vendor.js:13220:29)
    at process (http://localhost:7165/public/vendor.js:13288:12) undefined
```

**Comment by scottyscripts** [comment]
Does your update controller action in your API currently return any data?

**Comment by MicFin** [comment]
Status?

**Comment by jillrizley** [comment]
ah sorry! forgot to write back, I worked it out!!
