### ISSUE TITLE
Wireframes/ERD Help

### ISSUE THREAD

**Issue by dumplingpuff** [ga-wdi-boston/capstone-project#86]
I feel little iffy about the setup of my erd just wanted some advice on it.  So far I have decided to go with rails on this project.  I attached both the wireframe and a quick sketch of the ERD.
![quick-erd](https://cloud.githubusercontent.com/assets/14882368/14220264/efb42a34-f82c-11e5-98d1-d5e7fc1e33bc.jpg)
![wireframes](https://cloud.githubusercontent.com/assets/14882368/14220267/f38253a2-f82c-11e5-86c8-ab97112cff54.jpg)

**Comment by GA-MEB** [comment]
What's the premise?
