### ISSUE TITLE
unable to create, join table

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/capstone-project#862]
When trying to create a record in my join table, I am getting the error:
```
{"status":500,"error":"Internal Server Error","exception":"#\u003cNameError: undefined local variable or method `dinner_and_diners' for #\u003cClass:0x007f827af2f018
```
I double checked my pluralization and made sure that I have things set up the same way as in my other working join table.  What I noticed in schema is that my join tables are set up a little differently and I think that is the problem.  I think I need to create the join table again and just want to double check before doing a rollback and possibly messing things up further.

working table:
```rb
  create_table "gardens", force: :cascade do |t|
    t.integer  "vegetable_id"
    t.integer  "user_id"
    t.datetime "created_at",   null: false
    t.datetime "updated_at",   null: false
    t.index ["user_id"], name: "index_gardens_on_user_id", using: :btree
    t.index ["vegetable_id"], name: "index_gardens_on_vegetable_id", using: :btree
  end
```
non-working? table:
```rb
  create_table "dinner_and_diners", force: :cascade do |t|
    t.integer  "vegetables_id"
    t.integer  "pests_id"
    t.datetime "created_at",    null: false
    t.datetime "updated_at",    null: false
    t.index ["pests_id"], name: "index_dinner_and_diners_on_pests_id", using: :btree
    t.index ["vegetables_id"], name: "index_dinner_and_diners_on_vegetables_id", using: :btree
  end
```
The difference is that I have pluralized ids in dinner_and_diners and singular ones in gardens. 

Do I need to rollback and recreate this table or is there another way to update these keys?

**Comment by jordanallain** [comment]
can you tell me what the relationship is supposed to look like? what is the relationship between dinner_and_diners and gardens and pests and vegetables?

**Comment by 3point14guy** [comment]
gardens doesn't really come into play other than it is a working example of the type of relationship that exists between dinner_and_diners, pests and vegetables.

dinner_and_diners is the join table where pests and vegetables cross reference one another.  A pest can dine on many vegetables and vegetables can be dinner for many pests.

**Comment by 3point14guy** [comment]
let me clarify:
A pest can dine on many different vegetables and a vegetable can be dinner for many different pests.

**Comment by jordanallain** [comment]
okay, so your join table schema should say pest_id and vegetable_id you are correct.

**Comment by 3point14guy** [comment]
should I rollback or is there another way to do it?

**Comment by jordanallain** [comment]
you could write a migration to alter the column name if you want, but i would roll back and create the join table the right way because rails is handling some of the connections for you with its generate command.

**Comment by 3point14guy** [comment]
ok.  going to fix my schema by doing a rollback.  One last question on this...if I do the rollback, I CAN in that instance, edit the migration file before running db:migrate again, correct?  Or is it just better to delete the migration and run generate scaffold again?

**Comment by jordanallain** [comment]
if you roll back you can edit the migration file that was rolled back before migrating it again.

**Comment by 3point14guy** [comment]
Thanks for all the good info, Jordan, and especially the PROMPT responses!!!
