### ISSUE TITLE
Params is not being added to my 3rd party request

### ISSUE THREAD

**Issue by Fcarrion001** [ga-wdi-boston/capstone-project#863]
I am using an http gem to make api calls from my games controller and I am mimicking the docs but the parameter is not being added. 

This is the custom route. I added an :id param so that it can be targeted for my requests to the 3rd 
party api
```ruby
get '/api-games/:id' => 'games#showapi'
```
This is the method in the controller referenced by the route 
```ruby
def showapi
    user_key = ENV['USER_KEY']
    @games = HTTP.headers(:accept => 'application/json', 'user-key' => user_key)
              .get("https://api-2445582011268.apicast.io/games/", :params => {:id => params[:id]}).to_s

              render json: @games
end
```
This is the curl script
```sh
#!/bin/bash
curl http://localhost:4741/api-games/${ID} \
  --include \
  --request GET \
  --header "Authorization: Token token=$TOKEN"

echo
```

**Comment by jordanallain** [comment]
can you display the params inside that method to see what it looks like?

**Comment by Fcarrion001** [comment]
"this is params"
"1"
"this is :params"
:params

**Comment by jordanallain** [comment]
is that right?

**Comment by Fcarrion001** [comment]
params is actually params[:id] and that is right
I dont know what the :params is supposed to be if anything

**Comment by payne-chris-r** [comment]
I'm confused. What's the problem?

**Comment by payne-chris-r** [comment]
Link to the docs?

**Comment by Fcarrion001** [comment]
This is what the url request should look like
```ruby
"https://api-2445582011268.apicast.io/games/1"
```
this is what is being passed in
```ruby
"https://api-2445582011268.apicast.io/games/"
```

**Comment by Fcarrion001** [comment]
https://github.com/httprb/http/wiki/Passing-Parameters

**Comment by Fcarrion001** [comment]
Issue Resolved

Used string interpolation instead of the method provided by the docs and it works fine now
```ruby
  @games = HTTP.headers(:accept => 'application/json', 'user-key' => user_key)
              .get("https://api-2445582011268.apicast.io/games/#{params[:id]}").to_s
```
