### ISSUE TITLE
1:1 ember

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#864]
Here's my plan:
There is a view for exercises and a view for routines. The exercises view simply lists all of the exercises in the database, within this view users can create an exercise and add it to the global list. The routines view lists all of the routines a user has created when they are signed in, within this view user's will be able to create a routine and add it to the list or change the name of a current routine. I'd like a user to be able to click a routine on the routines view and have it bring them to a routine view. A routine view will then list exercises specific to that routine, so that would probably be a routine-exercise view? On this routine-exercise view, users will be able to add an exercise from the global list to their routine, update the weight of an exercise on their routine, and delete an exercise from their routine.

Wireframe:
![image](https://user-images.githubusercontent.com/19196821/29927767-4c68ed56-8e35-11e7-80ab-7fb330f17435.png)

This is how I perceive Ember works:
![image](https://user-images.githubusercontent.com/19196821/29927792-5b54e298-8e35-11e7-90ed-0dcc7472c954.png)

![image](https://user-images.githubusercontent.com/19196821/29927921-b70d193e-8e35-11e7-9a1a-b2a002dd2ef7.png)

But when it comes to implementing this (generating models, routes, components) and getting the pieces to connect I am completely lost. 

Please for the love of god some one sit down and explain this to me.

**Comment by payne-chris-r** [comment]
Cant find you. Come find me.

**Comment by ryanwk** [comment]
Thanks Chris.
