### ISSUE TITLE
Loan and Edit page blank on refresh

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/capstone-project#867]
I have a single resource view linked to by clicking on the title of the resource on a list and a resource-edit view that is also led from a link from the loans list, similar to how we displayed lists and they would take you to a list view. 

In my case it is Loans -> Loan and Loans -> Loan-edit.

When following a link both Loan and Loan-edit display properly. However, when you refresh the page while on those views they are blank.

I can reproduce the error, but am not sure how to fix it. I am also concerned this is a user facing error.

**Comment by payne-chris-r** [comment]
What does the model hook return?

**Comment by CoreyFedde** [comment]
@payne-chris-r
Loan
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model (params) {
    return this.get('store').findRecord('loan', params.loan_id)
  },
  actions: {
    createLoan(loan) {
      let newLoan = this.get('store').createRecord('loan', loan)
      newLoan.save()
    },
    deleteLoan(loan) {
      loan.destroyRecord()
    }
  }
});
```
Loan-edit
```js
export default Ember.Route.extend({
  actions: {
    updateLoan(loan){
      loan.save()
      .then(() => {
        this.transitionTo('loans')
      })
    }
  }
});
``` 
no Model in loan-edit

**Comment by payne-chris-r** [comment]
Then that's your problem. Is loan-edit nested under 'loan'?
Aka, is it:
loans: `/loans`
loan: `/loans/:loan_id`
loan-edit: `/loans/:loan_id/edit`
???
or:
loans: `/loans`
loan: `/loans/:loan_id`
--> loan-edit: `/loans/:loan_id/edit` (nested)
??

**Comment by CoreyFedde** [comment]
```js
this.route('loans');
  this.route('loan', { path: '/loans/:loan_id' });
this.route('loans-edit', { path: '/loans/:loan_id/edit'});
```
Loans-edit is accessed from a link from Loans

**Comment by CoreyFedde** [comment]
On the server side, in the controller the loan needs to be set before a show request. Once updated, the pages appear on refresh.

```ruby
before_action :set_loan, only: [:show, :update, :destroy]

def show
    p "loan is", @loan
    render json: @loan
  end

def set_loan
      @loan = current_user.loans.find(params[:id])
    end
```
