### ISSUE TITLE
Ember: What to do with unused routes

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/capstone-project#869]
I have a few routes that will be useful for my project in the long-run, but for the presentation and MVP are not currently used.

I have added a before model to the routes that redirect it to the index. I think its a solution, but I wanted to make sure it was acceptable for the mvp.

Example:
```js
export default Ember.Route.extend({
  beforeModel() {
    this.transitionTo('index');
  }
  // model () {
  //   return this.get('store').findAll('user');
  // },
});
```

**Comment by payne-chris-r** [comment]
That's exactly what you should do--or just remove them from the router until they're ready to go.

**Comment by CoreyFedde** [comment]
Thanks @payne-chris-r
