### ISSUE TITLE
deployment 400 bad request error

### ISSUE THREAD

**Issue by jillrizley** [ga-wdi-boston/capstone-project#872]
Deployed but I don't think the back-end is hitting. I have the heroku as production in config file, but I get a Bad Request error. Not sure where the issue is coming from. I am looking through some old issues, but I wanted to get this in now in case I can't figure it out.

https://jillrizley.github.io/capstone-front-end/

`vendor.js:9723 POST https://rocky-scrubland-71771.herokuapp.com/sign-up 400 (Bad Request)`

**Comment by payne-chris-r** [comment]
Can you make a curl req to it?

**Comment by jillrizley** [comment]
not sure what happened, but now everything works! Andrew sat down next to me and sprinkled some magic on my computer I guess

**Comment by payne-chris-r** [comment]
Classic Andrew and his magic sprinkles.
