### ISSUE TITLE
Problem with deployment

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/capstone-project#875]
Following the Ember deployment guide, I've gotten to the point where I have a service/ember-ajax file, but my code is no longer working. 

The next step is to commit and make sure it all works on master, but I want to make sure I've not done something wrong before deploying.

**Comment by payne-chris-r** [comment]
You don't need a `service/ember-ajax` file. It's just `service/ajax.js` I believe.

**Comment by payne-chris-r** [comment]
Please close this?

**Comment by payne-chris-r** [comment]
Did you resolve it?

**Comment by CoreyFedde** [comment]
The local server needs to be restarted after the name change.

Working.
