### ISSUE TITLE
Question about ERM

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/capstone-project#88]
Hi, 

I decided to do a refrigerator/ pantry expiration app. Users would be able to enter in the food they have in their freezer, fridge, and pantry(cupboard) and they can enter when they bought the food item and when it is expired, and when the user wants to be alerted(by email/ text?) about their food expiring.  I want to add a 3rd party App that will give users recipe of meals that they can make with their food. Users can enter in the food item that is about to expire and find recipes to make. 

Also the User can update and delete their food item. If they delete their item, the app will ask the user what they did with the food : throw away, eat, or donate( give to a friend or donate to shelter ) the app can also give users link to food shelter to donate food( feature I will do if I meet my goals for the project) 

Users would be able to view what they did with their food: what food, and how many items they ate, threw away, and donated. 

Below is my Entity Relationship Model

![image](https://cloud.githubusercontent.com/assets/16465193/14229138/d54962aa-f8f8-11e5-9810-89766dc46c14.png)

Can you tell me if the ERM Makes sense? I don't have any attribute for the models: (fridge, freezer, and pantry) is that okay?

**Comment by Knguyen21** [comment]
Or would it be better if I combine the fridge, freezer, and pantry into one model called storage. and the storage can have attribute type: string. And the type could be fridge, freezer, or pantry. 

![image](https://cloud.githubusercontent.com/assets/16465193/14229382/6f3e9ce8-f900-11e5-896e-34f48cceec9b.png)

![image](https://cloud.githubusercontent.com/assets/16465193/14229383/762c0d42-f900-11e5-8023-c6754b6d2492.png)

**Comment by Knguyen21** [comment]
I updated my ERD. FYI, I am considering using a 3rd party API for the recipe, IF I HAVE TIME. 
I would like to go over my ERD and make sure it is correct.  

User Story:
Users would be able to enter in the food they have in their freezer, fridge, and pantry(cupboard) and they can enter when they bought the food item and when it is expired, and when the user wants to be alerted(by email/ text?) about their food expiring. I want to add a 3rd party App that will give users recipe of meals that they can make with their food. Users can enter in the food item that is about to expire and find recipes to make.

Also the User can update and delete their food item. If they delete their item, the app will ask the user what they did with the food : throw away, eat, or donate( give to a friend or donate to shelter ) the app can also give users link to food shelter to donate food( feature I will do if I meet my goals for the project)

Users would be able to view what they did with their food: what food, and how many items they ate, threw away, and donated.

![screen shot 2016-04-04 at 9 32 08 am](https://cloud.githubusercontent.com/assets/16465193/14249531/2cb452b6-fa48-11e5-9c03-b0e858128f89.png)

**Comment by faetea** [comment]
Why are you making a Recipe Model?  Seems unnecessary if the recipes are from an external application you would be connecting the user to.  Tho it really depends on how that external website/API works, and if you are allowing the User to save their favorite Recipes or something.

User, Storage, Disposal and Food Modals look like good relationships.

Disposal will need to be an Update action, not a Delete action.  A Delete action would be for removing the food row from the Food table in the database.  This will destroy all record of what they did with their food.

**Comment by GA-MEB** [comment]
@faetea I respectfully disagree about the Storage and Disposal resources - I think they could easily be represented as properties of Foods. @Knguyen21, is there a specific business reason for splitting them out into separate entities?

**Comment by Knguyen21** [comment]
OH okay... When the user click on update ( a modal will pop up that says, "update info" (button) and  How did you disposed of the food "ate"(button)  "trash" (button) "donate (button).  When they click on "ate "button, for example, the food will be assigned the disposal id and then the Browser will delete the food( not delete from database, but empty the content from the page. 

Would that make more sense?

**Comment by Knguyen21** [comment]
![img_20160404_095654 copy](https://cloud.githubusercontent.com/assets/16465193/14250417/5f92394c-fa4c-11e5-8c88-ff8ff6ddd5c3.jpg)

**Comment by Knguyen21** [comment]
I thought they needed to be separate models because I want to display the , fridge, freezer, and pantry. and have the user enter the food items for each storage . I'm now confused which one would be better have the disposal and storage as separate models or have as an attribute for foods?

**Comment by GA-MEB** [comment]
I still don't see why updating a property on the given Food isn't simpler. 

As far as your UI, what are you using for your front end? Ember? Angular? Vanilla JS and jQuery?

**Comment by Knguyen21** [comment]
Front end: Ember
Backend: Rails

**Comment by Knguyen21** [comment]
also if I only have a user and food model, would that still fulfill the requirement?? "Be a complete product, which most likely means multiple relationships and CRUD functionality for at least a couple models"

**Comment by jrhorn424** [comment]
I agree that storage and disposal could be modeled as string columns on foods.

A next step would be changing them over from strings to enums, or even better, having "lookup tables", which are essentially glossaries that are used to define what kind of string values are acceptable... think about a table of U.S. states. If we had a table listing all the states, then added foreign keys to an address table, if Massachusetts ever changed its name to Bostonia, we'd only have to update one thing (the string in our lookup table).

**Comment by jrhorn424** [comment]
Your app as you describe only needs one model. It's not a bad idea. If you only have one model but you have text notifications working, I'd be sufficiently impressed. That means you need to get  CRUD out of the way ASAP and start working on ambitious features.

**Comment by Knguyen21** [comment]
Hi Jeff,
I reread your previous comment about changing the string to enum or having lookup table. I updated my model so it's only user has many food. I add the storage and disposal as an attribute to foods. They are both string. There's only 3 storage: "freezer", "fridge", and "pantry". Users's can NOT change where it goes because it goes against my wireframe. I want users to click on the fridge/ freezer/ or pantry picture and then they add whatever food they want in it.  And when the dispose of something it gets removed from the browser, so user can not view it in the storage area"ex fridge" anymore. The food name  is now displayed in  in the "disposal storage" page. 

In my case, do you think it would be okay to keep the storage and disposal as a string?

**Comment by jrhorn424** [comment]
Sounds great! Excellent reasoning.

**Comment by jrhorn424** [comment]
(You're thinking like a developer!)

One more question. Is the string specified as part of a radio button or select? That can enforce (weakly) the requirement that only three strings are valid. Changing it to an enum would enforce it a bit more strictly. No need to worry about that now, but you should at least make sure picking a storage isn't filling in a text box.

**Comment by Knguyen21** [comment]
It's not filling any text box at all. In the homepage, I will have an image of a freezer, a fridge, and a pantry, and a disposal storage ( box or something). If the user clicks on the image of the fridge( a div ) the page will load with just the fridge form for users to enter all items in the fridge. All the food will have storage="fridge" automatically entered in the backend. and a Get request will display all the food items that have attribute storage="fridge" using Ember handlebars. 

As for the disposal, the user will have a radio button in the fridge page  to answer how they disposed of the item ("ate", "trash", "donate". ) The food item will then be removed from the fridge page and displayed int the disposal page, where there's a column for "Ate", "Trash", "Donate", and disposed food items will be displayed in their respective column.

I also wanted to let user organize their food based on category: produce, condiments, meat, dairy, other, drinks, (still trying to think of categories) The category will be in a dropdown toggle list and users can update the category. The category's value will be hardcoded in to the value of the lists in the dropdown toggle.
(This is another case where I wonder if it's okay to still use string for column category in foods table. ) I will

**Comment by jrhorn424** [comment]
Strings are OK in all those cases. :+1:

**Comment by Knguyen21** [comment]
Thanks!
