### ISSUE TITLE
Trying to Bulk Load Data (CSV) to Heroku 

### ISSUE THREAD

**Issue by kailinc** [ga-wdi-boston/capstone-project#881]
My project is done and ready to go, but I need to bulk load items data into the Heroku API. It seems like I have to use mLab to do this. 

Documentation from mLab
```terminal 
mongoimport -h ds159033.mlab.com:59033 -d heroku_j0xn3n47 -c <collection> -u <user> -p <password> --file <input .csv file> --type csv --headerline
```
My user is 'heroku_j0xn3n47'. 

I tried the following command and I am getting an error.

Command I tried 
```Terminal
$ mongoimport -h ds159033.mlab.com:59033 -d heroku_j0xn3n47 -c items -u heroku_j0xn3n47 -p xxxxxxxxx  --file data/languages.csv --type csv --headerline
```

Error Received
```Terminal
2017-09-04T15:02:42.887-0400	Failed: error connecting to db server: server returned error on SASL authentication step: Authentication failed.
2017-09-04T15:02:42.887-0400	imported 0 documents
```

**Comment by jordanallain** [comment]
you have to create a db user on mlab's website and then sign in with that username and password

**Comment by kailinc** [comment]
That might have been it. I just made a create action and made items one by one. =_=
