### ISSUE TITLE
Request for 1-1 to review ERD & Rails issues

### ISSUE THREAD

**Issue by msyao** [ga-wdi-boston/capstone-project#89]
Hi,
Could I meet with someone to discuss my ERD for the project? I want to see how I have currently structured my Postgres database makes sense with the ERD, etc some other questions I will have (implement admin user who can only CRUD posts, and associating admin with posts).

My ERD and user story is shown on my Trello board:
https://trello.com/b/FzoDbOkG/just-feel-pepper

**Comment by faetea** [comment]
the only thing I see missing is: Posts belongs_to Admin
You don't want your Admins to be able to submit reviews, correct?

**Comment by msyao** [comment]
Hi Allie - that is correct. I don't want **Admins** to CRUD reviews only on pepper posts that will have **User** reviews.

I think I'd like a in-person 1-1 to discuss this tomorrow.
Thank you very much!
:smile:

**Comment by jrhorn424** [comment]
This looks good. I like your user stories.

Usually, I would suggest keeping one User resource, and adding an `admin?` boolean column to indicate that user account is an administrator. However, I think in this case it could make sense to have separate accounts associated with separate resources.

Keep in mind, this means you will likely have two sets of routes for sign-in, sign-up, change-password, sign-out: one set for admins, one set for regular users. You can have a look at how we've implemented the User model if you want to make your own Admin. @gaand Do you know if @msyao can just mix-in auth as a concern yet, and which backend she could use for that if they're different in that regard?

You'll (probably) need two sets of controllers with largely identical actions as well.

**Comment by jrhorn424** [comment]
I spoke to @gaand and implementing another model for login shouldn't be tedious. You will have to duplicate the controller by hand, however, and setup separate (probably namespaced) routes.

**Comment by msyao** [comment]
Hi :neckbeard: Jeff - thank you very much :exclamation: 

I will look into it and do.
I will close the issue for now.
