### ISSUE TITLE
Request to review my project scope and creating a user profile with rails

### ISSUE THREAD

**Issue by gracenjambi** [ga-wdi-boston/capstone-project#9]
I have been trying to plan how the user and profiles will work.

I need an admin user and a company profile, then each user needs to have a profile that they can add when registering  and an administrator that can add and remove users.

**Comment by jrhorn424** [comment]
What you're working on is called "authorization", which is distinct from authentication. I'd start with a column in your User table (admin) that is a boolean. Then, whatever controller action you use to delete users will check to see if that user is an admin before doing the delete.

What kinds of profiles do you have? User profiles and company profiles, or just company profiles?

**Comment by gracenjambi** [comment]
I want to have 1 company profile
Then each user will have a profile which they will create on registration.
Then there is 1 admin who can further manage users

**Comment by jrhorn424** [comment]
Well, I wouldn't call them both profiles. Maybe call the company profile a summary? Your choice.

The rest of my advice about authorization still applies.

**Comment by gracenjambi** [comment]
ok thank you will proceed setting these up and will open a new issue if I need more help.
