### ISSUE TITLE
Rails - Server Error: "PG::ConnectionBad"

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/capstone-project#91]
When I try to load localhost:3000, the browser displays this error:

```
could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

Extracted source (around line #651):
        # connected server's characteristics.
        def connect
          @connection = PGconn.connect(@connection_parameters)

          # Money type has a fixed precision of 10 in PostgreSQL 8.2 and below, and as of
          # PostgreSQL 8.3 it has a fixed precision of 19. PostgreSQLColumn.extract_precision
```

It looks like this:
![image](https://cloud.githubusercontent.com/assets/8867447/14235264/e950ec22-f9c6-11e5-985e-07e09748730e.png)

When I try to run the sign-up curl script, the server logs the following error: 

```
Started POST "/sign-up" for ::1 at 2016-04-03 16:43:50 -0400

PG::ConnectionBad (could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
):
```

Any help would be appreciated

**Comment by faetea** [comment]
What messages are you seeing that indicates that psql is running at all?  Need more information to understand situation.

**Comment by gaand** [comment]
It is unlikely that PostgreSQL is running based on this error.
Does `brew services list` show `postgresql started ...`?

**Comment by MFBrewster** [comment]
Hanging postgres server process was blocking postgres from running. Issue resolved.

**Comment by pensebien** [comment]
I think postgres is running in this case
I think as the [link](https://postgresapp.com/documentation/troubleshooting.html) show here, there is could be a cases like that.
