### ISSUE TITLE
Modeling Songs, Playlists, and Comments

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/capstone-project#92]
https://www.dropbox.com/sh/cb05r5mgpvt8t91/AAAEmG-b2LRDPL9Dxjg7fFtIa?dl=0

There is the link to my initial ERD's and user stories. I have a basic idea of what I will be doing. I need guidance on whether or not I have the proper scope and I need some suggestions as to how to move forward.

**Comment by jrhorn424** [comment]
@kpie89 and I discussed normalization strategies for soundcloud IDs. The soundcloud API has songs with an ID that @kpie89 wants to use in two places: `Playlist` and `Comment`. `Playlist` is a wrapper with extra data for _one_ song. A `Comment` is the same. In this domain, someone picks a song that starts a "playlist". Someone else can pick a different song that appears as a "comment" on that playlist.

I suggested a one-to-one between `Song` and `Comment`, and a one-to-one between `Song` and `Playlist`.

@gaand What is your advice for placing the foreign key on these relationships? Do you have any rules or guidelines for placing foreign keys on one-to-ones?

**Comment by gaand** [comment]
one-to-one is a special case of one-to-many.  one-to-many the owner/parent is the one and the owned/child is the many.  Given that, the foreign key goes on the entity that is owned (e.g. profile has a foreign key to user).  

But, are songs normalized?  So, one song per sound cloud song?  If so, then playlist and comment have the foreign key.  From there it can only go to many-to-many.

I think that's right.

**Comment by jrhorn424** [comment]
I see. Let me see if I have that straight.

Say we have a User and a Profile. We've been saying `Profile belongs_to User`. It doesn't really make sense for a `Profile` to `has_many :users`. But, by storing `user_id` on `profiles`, we make it simpler to upgrade `User` to `has_many :profiles` in the future.

`Song` is normalized in the way you suggest. By storing `song_id` on `comments` and `playlists`, a `Song` can `has_many :playlists` and `has_many :comments`.

@kpie89, in retrospect, this probably should be a one-to-many, not a one-to-one. I apologize if that was a source of confusion for you when we talked earlier. If you've decided to store the foreign key on `comments` and `playlists` as @gaand suggested, you should be able to make this change in a straightforward fashion.

**Comment by jrhorn424** [comment]
Just spoke with @kpie89. I gave poor advice this morning and asked him to associate his resources directly with a `Profile` (called a `Person` in his app). It was bad advice in this case because @kpie89 wanted `Profile` to be something optionally filled out for each user.

Turns out you can't reach through a nil.
