### ISSUE TITLE
Requesting Initial 1 on 1 to review ERD and design plan.

### ISSUE THREAD

**Issue by ajordon** [ga-wdi-boston/capstone-project#93]
I am creating a teaching tool to maintain students assignments and what not.

![image](https://cloud.githubusercontent.com/assets/6088950/14248813/87392c88-fa44-11e5-8595-844236d6dde0.png)

**Comment by jrhorn424** [comment]
Do you have any wireframes? User stories would be good as well.

It's hard to know if the modeling is good without a feature set. Models serve your features, not the other way around.

Thanks!

**Comment by ajordon** [comment]
[Design_docs.pdf](https://github.com/ga-wdi-boston/capstone-project/files/202649/Design_docs.pdf)

**Comment by ajordon** [comment]
Updated ERD and user stories to reflect discussion notes. Will continue designing my back end API

**Comment by jrhorn424** [comment]
Looks good. Thanks for updating!
