### ISSUE TITLE
(Backend) Understanding Mongoose vs bookself

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/capstone-project#96]
Just trying to understand the piece of code below. I am looking to do the same thing in bookshelf.

``` javascript

userSchema.methods.comparePassword = function (password) {
  let _this = this;

  return new Promise((resolve, reject) =>
    bcrypt.compare(password, _this.passwordDigest, (err, data) =>
        err ? reject(err) : data ? resolve(data) : reject(new Error('Not Authorized')))
    ).then(() => _this);
};
```

My confusion arrises from `userSchema.methods.comparePassword`. I would like to verbally discuss this code if possible.

> Possibly looking at using bookshelf-secure-password. "Adds a method to set and authenticate against a BCrypt password."

**Comment by jrhorn424** [comment]
The provided auth is provided via Mongo with Mongoose, as you've noticed. Is it possible for you to just use auth as-is and use bookshelf where needed?

If not, you'll be re-implementing the model layer of auth. If that's something you want to do, go for it.

Other options include trying to use `passport` with a simple token. Not pretty, either.

> My confusion arrises from userSchema.methods.comparePassword

If this were any other language, say Ruby, this would saying add a class method called "comparePassword" that decides whether the user supplied a matching password.

I'm not sure whether that method works as written (we broke it at some point, sorry). @gaand Can you comment?

**Comment by gaand** [comment]
If bookshelf provides a way of attaching methods to models, then reimplementing the template model seems straightforward.  It may not even require a code change to the methods `comparePassword` and `setPassword`.

**Comment by jrhorn424** [comment]
We discovered this morning that Bookshelf allows setting methods on model creation, since it uses the `extend` pattern of inheritance.

``` diff
bookshelf.Model.extend({
-  customMethod () => "goes here"
+  customMethod () { "goes here" } // thanks @gaand
});
```

**Comment by gaand** [comment]
I think you may need need to write it as

``` js
bookshelf.Model.extend({
  customMethod () { "goes here" }
});
```

so `this` is available.

**Comment by jrhorn424** [comment]
You're right. My mistake. :smile:

**Comment by edesilets** [comment]
Thanks for the help gents. CustomMethods are work. Thanks.
