### ISSUE TITLE
Ember call for data from store not working

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/capstone-project#97]
I'm trying to add a dropdown menu to the signup form, so that a new user can associate their account with their organization when they register. However I can't seem to get the organization data into this component. The console.log for the model does not appear, so I don't think it is getting called at all.

The code for the dropdown, in the sign-up-form component's template.hbs:

```
<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Choose Your Company
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    {{#each model as |organization|}}
      <li>{{organization.name}}</li>
    {{/each}}
  </ul>
</div><br>
```

The reference to the organization model in the sign-up-form component.js

```
model: function() {
  console.log("model called for organizations");
  return this.store.findAll('organization');
  },
```

If I put the following code on the organization route/template itself, the dropdown menu works. But I don't want it to be on the organization route.

**Comment by jrhorn424** [comment]
Model hooks only work in routes. If you want it in the sign-up route, you can put it there. Something like:

``` js
model: function() {
  return {
    organizations: this.store.findAll('organization'),
    other: "things go here"
  },
```

``` hbs
    {{#each model.organizations as |organization|}}
      <li>{{organization.name}}</li>
    {{/each}}
```

**Comment by jenweber** [comment]
Even with this model code available in the Sign Up route, the drop down (located in the sign-up-form component template) still does not populate. Do I somehow need to pass the data to the component via the reference in the sign-up route template? The model is now getting called, according to my console logs.

{{sign-up-form submit="signUp" //something here???//}}

**Comment by jrhorn424** [comment]
``` hbs
{{sign-up-form submit="signUp" organizations=model.organizations}}
```

``` hbs
{{#each organizations as |organization|}}
  <li>{{organization.name}}</li>
{{/each}}
```

**Comment by jenweber** [comment]
Cool, that worked! Thanks!
