### ISSUE TITLE
trips model hook in route throwing an error.

### ISSUE THREAD

**Issue by dumplingpuff** [ga-wdi-boston/capstone-project#98]
Whenever I load my trips template I keep getting an error that says: TypeError: Cannot read property 'some' of undefined.  

This is how I set up my routes.

```
// trips route
import Ember from 'ember';

export default Ember.Route.extend({
  model: function(){
    return this.store.findAll('trip');
  }
});
```

I even set up a trip adapter and model.

```
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  location: DS.attr('string'),
  arrival: DS.attr('date'),
  departure: DS.attr('date'),
  description: DS.attr('text'),

  users: DS.hasMany('users', {async: true})
});
```

Maybe the association in the back end of Many to Many relationship with User and Trip that could be causing this.  I am kind of unsure of why this error is throwing.

**Comment by jrhorn424** [comment]
@jenweber Had a similar error earlier.

We'll need to see your template and any other related code you can think of.

**Comment by dumplingpuff** [comment]
To keep everything clear I actually removed everything except for the navbar to see what kind of issue it is.
This is all in my trips template, it doesn't even link to my component yet.

```
{{navbar-normal}}
```

The entire /trips page doesn't load, it just throws an error.

**Comment by dumplingpuff** [comment]
When I removed the model hook the page loads fine, so I am think it has to do with the way I hitting the back end or the way the model in the front end is set up.  Would you like to see some back end code?

**Comment by dumplingpuff** [comment]
Celena is having a similar issue, we think it is because of embedded json and ember doesn't like that.

**Comment by faetea** [comment]
`TypeError: Cannot read property 'some' of undefined.`  So you need to figure out what it isn't seeing as defined.  Ember has a lot of layers and if something isn't defined it means a connection isn't being made somewhere between those layers.

We need more information about what is happening, what you have tried already, and what code you have.

**Comment by jrhorn424** [comment]
There should be a line number and file associated with that error message in your console.

If you can't find it immediately, we may need to look at your full backtrace from the console.

**Comment by jrhorn424** [comment]
> Celena is having a similar issue, we think it is because of embedded json and ember doesn't like that.

I don't know what you mean by embedded JSON. If you mean nested, Ember is fine with that.

**Comment by dumplingpuff** [comment]
The error is pointing to route file in application it is look at the some method.

```
    error (reason) {
      let unauthorized = reason.errors.some((error) => {
        return error.status === "401";
      });
```

**Comment by faetea** [comment]
Jason, you showed me that the template will render when the model is not present and the template will not render if the model is not present.  You need to show us all of the code that touches the template, route, and model, that you are making the change to.  

I showed you that the `TypeError: Cannot read property 'some' of undefined` was pointing the the application/route.js, so that you would understand that although it was the trip/route.js were you were making the change it was the application/route.js that was throwing the error.  

We still need more code/information.

**Comment by jrhorn424** [comment]
OK, that's definitely the issue. It bubbled up and was caught at the application level.

I've been wrestling with how to deal with these errors. I've come up with a few different approaches. I won't guarantee this is foolproof, and it may cause problems later, but try this instead:

``` js
if (reason.errors) {
  var unauthorized = reason.errors.some((error) => {
    return error.status === "401";
  });
}
```

**Comment by jrhorn424** [comment]
@dumplingpuff Can we speak about this when you're done talking with @faetea?

@faetea Please assign yourself to an issue when meeting with developers.

**Comment by jrhorn424** [comment]
Deleted the adapter for trips since it wasn't needed. I suspect the generated adapter was inheriting from the wrong adapter.

Also,

``` diff
- return this.store.findAll('trip');
+ return this.get('store').findAll('trip');
```

**Comment by jrhorn424** [comment]
@dumplingpuff Can we mark this resolved?

**Comment by dumplingpuff** [comment]
Adapter for each pod was removed, thanks.
